### ISSUE TITLE
classification of functions in a package

### ISSUE THREAD

**Issue by DanGrayson** [Macaulay2/M2#1000]
Frank Schreyer and David Eisenbud suggest that a package's documentation should be able to put the documentation nodes for functions into various subheadings, as manually illustrated here: https://faculty.math.illinois.edu/Macaulay2/doc/Macaulay2-1.14/share/doc/Macaulay2/K3Carpets/html/.

**Comment by mahrud** [comment]
Writing the front page documentation of a package is essentially like designing a website. We could probably provide examples to make this easier, or maybe add an optional SimpleDoc tag for grouping?

**Comment by DanGrayson** [comment]
This would be a good application of "Subnodes", an option to "document" and is available in SimpleDoc, as it is how a sequential book is organized, too.

**Comment by mahrud** [comment]
Added in the SimpleDoc PR. Subnode can be used within Description. The syntax is more advanced, in particular, it supports nesting and @...@ replacement.

**Comment by mahrud** [comment]
As an example, this:
```m2
    Subnodes
      :Syntax for special characters
        :Wildcard
          @TT "."@	-- match any character except the newline character
        :Anchors
          @TT "^"@	-- match the beginning of the string or the beginning of a line
          @TT "$"@	-- match the end of the string or the end of a line
```
Turns into this:

![image](https://user-images.githubusercontent.com/3147718/89482931-8d8ece00-d760-11ea-8056-167500409205.png)

If the line doesn't start with ":" or "@", then it is treated as a documentation key and passed through TOH as usual.
