### ISSUE TITLE
viewHelp fails to find recently installed package

### ISSUE THREAD

**Issue by DanGrayson** [Macaulay2/M2#1006]
Usually
```
installPackage "Foo"
viewHelp Foo
```
works, but sometimes `viewHelp` complains that Foo is not installed on the prefixPath, even if other packages have been previously installed.  Restarting M2 fixes this.

**Comment by DanGrayson** [comment]
Actually, I think the error message is just wrong: the package is installed, but there is no documentation node for the package.

**Comment by mahrud** [comment]
This seems to be working, possibly fixed since my changes to help and viewHelp. Feel free to reopen if it persists.
