### ISSUE TITLE
GC_MAXIMUM_HEAP_SIZE=400M fails

### ISSUE THREAD

**Issue by DanGrayson** [Macaulay2/M2#1007]
Under Mac OS I've seen GC_MAXIMUM_HEAP_SIZE=400M get rejected as a bad value, and then M2 can't start, because there is not enough memory (?).  The users had our binary distribution, which comes with libgc, so what could the problem be?  It might be related to setting that environment variable previously.

For users, the problem arises when examples are run -- they all fail.

**Comment by mahrud** [comment]
Closing this, but feel free to reopen if it can be reproduced.
