### ISSUE TITLE
libgccpp might be needed in some external GC configs (for eigen branch)

### ISSUE THREAD

**Issue by dimpase** [Macaulay2/M2#1021]
On current Gentoo Linux using GC version 8 one gets linking error
```
undefined reference to `GC_throw_bad_alloc()'
``` 
while linking `bin/M2-binary`. The reason is that the function in question is in a separate C++ library, called `libgccpp`
```
$ nm -D --demangle /usr/lib64/libgccpp.so | grep throw
                 U __cxa_throw
0000000000001140 T GC_throw_bad_alloc()
```
or more precisely 
```
$ nm -D /usr/lib64/libgccpp.so | grep throw
                 U __cxa_throw
0000000000001140 T _Z18GC_throw_bad_allocv
```
(name mangled, as it's C++) --- rather than in `libgc`

So `./configure` should test for presense of `GC_throw_bad_alloc()'
in `libgc` and in `libgccpp`.

**Comment by dimpase** [comment]
forgot to say that it's @antonleykin 's `eigen` branch

**Comment by DanGrayson** [comment]
We don't want to link that library in, because it remaps " operator new "
to a libgc memory allocator.  So we should find out what code is referring
to it.

**Comment by dimpase** [comment]
apparently something only present in eigen branch

**Comment by dimpase** [comment]
But there are ways around that `new::` repalcements, as outlined in https://github.com/ivmai/bdwgc/blob/master/include/gc_cpp.h
Namely, only in classes derived from `gc` this replacement happens, and
also there is syntax
```
  A* a = new (NoGC) A;   // a is uncollectible.
```
to prevent GC-ing.

**Comment by DanGrayson** [comment]
Re: "only in classes derived from gc this replacement happens"

That's not right.

**Comment by dimpase** [comment]
> That's not right.

well, I merely ready this in the long comments in that header, perhaps it's not correct, I don't know.

Anyway, could it be that just passing `-fno-exceptions` flags to the C++ compiler will prevent the need for `GC_throw_bad_alloc()`, so that `libgccpp` can be skipped, as intended?

**Comment by dimpase** [comment]
OK, I think we know what's going on. It is a recent change n GC, see
https://github.com/ivmai/bdwgc/issues/268
Basically, `GC_throw_bad_alloc()`is always there on GC 8+ with gc_cpp used.

@ivmai says there it's safe to link to  `libgccpp`, it should not modify the behaviour.
This contradicts 
```
dnl Note: we don't include -lgccpp below, because linking with that library is what replaces ::new and friends with GC_MALLOC_UNCOLLECTABLE and friends:
```

Also, note that @DanGrayson and @mikestillman had back-to-back commits in eigen branch that modified `VERSION` of GC back and force.

**Comment by dimpase** [comment]
We confirm that
```diff
--- a/M2/configure.ac
+++ b/M2/configure.ac
@@ -806,7 +806,7 @@ dnl Note: we don't include -lgccpp below, because linking with that library is w
 if [ pkg-config --exists bdw-gc ]
 then AC_MSG_RESULT(yes)
      CPPFLAGS="`pkg-config --cflags-only-I bdw-gc | sed -e 's=^-I/=-isystem /=g' -e 's= -I/= -isystem /=g'` $CPPFLAGS"
-     LIBS="-lgc $LIBS"
+     LIBS="-lgc -lgccpp $LIBS"
      FOUND_gc=yes
 else AC_MSG_RESULT(no)
      BUILD_gc=yes
```
enables eigen branch to build from scratch, and pass many tests (it looked as if 27 examples  failed due to certain `ulimits` being too tight).

**Comment by dimpase** [comment]
I've opened https://github.com/antonleykin/M2/pull/5 to deal with this

**Comment by dimpase** [comment]
It seems arb is a very natural choice (we use arb quite a bit in Sage) for univariate root finding:
http://arblib.org/#polynomials-and-power-series
it uses flint as the backend, and is well-adjusted to it.

**Comment by mahrud** [comment]
This seems to be resolved. Please reopen if I'm mistaken.
