### ISSUE TITLE
using --enable-debug switch in configure leads to "undefined reference to `GC_check_annotated_obj'"

### ISSUE THREAD

**Issue by dimpase** [Macaulay2/M2#1027]
the build (of [`eigen` branch](https://github.com/antonleykin/M2/tree/eigen)) then ends with
```
...
-o "/home/dimpase/work/M2/M2/usr-dist/x86_64-Linux-Debian-10/bin/M2-binary".tmp
/usr/bin/ld: ../d/M2.o: in function `M2_tostring':
/home/dimpase/work/M2/M2/Macaulay2/d/M2.d:33: undefined reference to `GC_check_annotated_obj'
/usr/bin/ld: ../d/M2.o: in function `M2_makearrayint':
/home/dimpase/work/M2/M2/Macaulay2/d/M2.d:43: undefined reference to `GC_check_annotated_obj'
/usr/bin/ld: ../d/M2.o: in function `M2_tocharstar':
/home/dimpase/work/M2/M2/Macaulay2/d/M2.d:50: undefined reference to `GC_check_annotated_obj'
/usr/bin/ld: ../d/M2.o: in function `M2_tocharstarOrNull':
/home/dimpase/work/M2/M2/Macaulay2/d/M2.d:59: undefined reference to `GC_check_annotated_obj'
/usr/bin/ld: ../d/M2.o: in function `M2_tostringn':
/home/dimpase/work/M2/M2/Macaulay2/d/M2.d:66: undefined reference to `GC_check_annotated_obj'
/usr/bin/ld: ../d/M2.o:/home/dimpase/work/M2/M2/Macaulay2/d/M2.d:75: more undefined references to `GC_check_annotated_obj' follow
collect2: error: ld returned 1 exit status
```
I presume this is due to appropriate confugure switch not passed to the building process for GC
(which is v8.0.4), and so it does not build the correct version of the library, with `GC_check_annotated_obj` included.

**Comment by DanGrayson** [comment]
There is no eigen branch here.  You want to report this on Anton's repository.

**Comment by dimpase** [comment]
I am pretty sure this is the problem on the master branch, too, as the calls to `GC_check_annotated_obj` are there since 2010.

Basically, with gc 8.0.4 one needs to modify `libraries/gc/Makefile.in` as follows
```diff
 ifeq (@DEBUG@,yes)
-CONFIGOPTIONS += --enable-gc-debug
+CONFIGOPTIONS += --enable-gc-debug --enable-static
```

to make sure that `GC_check_annotated_obj` is exported to libgc.

**Comment by DanGrayson** [comment]
Well, try it on the master branch and let us know.

**Comment by dimpase** [comment]
for the time being, see https://github.com/antonleykin/M2/pull/7

**Comment by mahrud** [comment]
Leaving this commit, which disables that function, for future reference: https://github.com/Macaulay2/M2/commit/e149f3a2df3c2cf1be6fc0eb98a0c3ce4080e0f2

**Comment by DanGrayson** [comment]
Good point.
