### ISSUE TITLE
betti for ChainComplexes (that are not free resolutions of modules over polynomial rings)

### ISSUE THREAD

**Issue by antonleykin** [Macaulay2/M2#1028]
It looks like `betti` applied to a `ChainComplex` was designed only with betti numbers for free resolutions in mind. Below is an example with a complex of ZZ-modules, where the expected answer could be 1 and 2 (in homological degrees 0 and 1 respectively) if interpreted as rank of the free part of the homology modules. 
 
```i1 : C = chainComplex matrix{{3,0,0},{0,0,0}}

       2       3
o1 = ZZ  <-- ZZ
              
     0       1

o1 : ChainComplex

i2 : prune HH C

o2 = 0 : cokernel | 3 |
                  | 0 |

           2
     1 : ZZ            

o2 : GradedModule

i3 : betti C

            0 1
o3 = total: 2 3
        -1: . 3
         0: 2 .

o3 : BettiTally
```

**Comment by DanGrayson** [comment]
Probably it should just give an error if the modules are not free.

**Comment by antonleykin** [comment]
Agree. 
Some people may expect `betti C` for a chain complex `C` to return the degrees of `HH C` not `C` itself. This is what Sage outputs, but I guess for M2 a `ChainComplex` is inherited from `GradedModule`, so we should not change its behavior.

**Comment by DanGrayson** [comment]
That's strange behavior in sage.  How then do you get the betti table of a free resolution of a module in sage?

**Comment by antonleykin** [comment]
They call M2 :)

**Comment by DanGrayson** [comment]
Fixed:
```
commit 88a412817c25f06ace8c0896df9a65d3e1b54d4f (HEAD -> master, origin/master, origin/HEAD)
Author: Daniel R. Grayson <dan@math.uiuc.edu>
Date:   Thu Oct 10 21:02:22 2019 -0500

    betti now gives an error if a chain complex has non-free modules in it
```
