### ISSUE TITLE
segfault for a primary decomposition

### ISSUE THREAD

**Issue by jakobkroeker** [Macaulay2/M2#103]
here is a failing example:
```
rng = QQ[x,y,z]
I =  ideal(-(1/2)*x*y-3*x,-(1/2)*x*y-3*y)
  primaryDecomposition I --sefgault.
-------
in Singular:
LIB("primdec.lib");
ring rng = 0,(x,y,z),dp;
ideal I = -(1/2)*x*y-3*x,-(1/2)*x*y-3*y;
primdecSY(I);
```
can you reproduce the issue?

Remark:
I'm working on  a framework prototype for a fine-grained control of generating random ideals in comparison to  `random(5,rng)` 
( e.g control number of polynomial terms, max coefficient value, number of ideal generators and other parameters)

If you are interested, I can post it here. In general I'm interested in feedback.
It could be used to throw random ideals at other M2 interfaces 
(which is a very basic method to hunt for bugs)

**Comment by mikestillman** [comment]
This works in version 1.7, and also on master, so I'm closing this issue.
