### ISSUE TITLE
Make realPart a method function

### ISSUE THREAD

**Issue by jchen419** [Macaulay2/M2#1037]
Currently `realPart` is a `CompiledFunction`, which does not allow for overloading. It would be useful to make it a `MethodFunction`, to allow functionality such as

`realPart Matrix := Matrix => A -> matrix apply(entries A, r -> r/realPart)` 

Similarly for `imaginaryPart`.

**Comment by DanGrayson** [comment]
Good idea.

**Comment by pepperhdj** [comment]
Dylan and I would like to take a look like this.

**Comment by DanGrayson** [comment]
Great.  What is your name?  (How about putting it and your portrait into your profile?)  What is Dylan's name and github id?  (I'll assign him, too.)

**Comment by dylanpeifer** [comment]
This issue can be closed now. It looks like GitHub recognized the pull request mentioned this issue but not that it fixed it.

**Comment by DanGrayson** [comment]
I think if you had said "resolves #1037" it would have figure it out.
