### ISSUE TITLE
D-module code gives different answers now

### ISSUE THREAD

**Issue by DanGrayson** [Macaulay2/M2#1048]
The expected test output in Macaulay2/packages/ComputationsBook/d-modules/ is:
```
    i89 : I = gkz(matrix{{1,2}}, {5})

                  2
    o89 = ideal (D  - D , x D  + 2x D  - 5)
                  1    2   1 1     2 2

    o89 : Ideal of QQ[x , x , D , D ]
                       1   2   1   2
```
but now we get:
```
    i89 : I = gkz(matrix{{1,2}}, {5})

                                    2
    o89 = ideal (x D  + 2x D  - 5, D  - D )
                  1 1     2 2       1    2

    o89 : Ideal of QQ[x , x , D , D ]
                       1   2   1   2
```
@antonleykin  -  Do you want to fix the code or change the test?

**Comment by antonleykin** [comment]
It looks like the only difference is the order of generators.
I guess one should change the test.

**Comment by DanGrayson** [comment]
Another possibility would be to sort the final answer to make it resistant to changes in the code further down.

**Comment by DanGrayson** [comment]
I've changed the test.
