### ISSUE TITLE
gfan under ubuntu and M2 1.15 (and master) seems incompatible

### ISSUE THREAD

**Issue by mikestillman** [Macaulay2/M2#1066]
I tried to compile M2 master under ubuntu 18.04, and got errors while building (I will have to rerun to see where the problem was).  It appears to be: the version included with ubuntu (after apt-get install) seems to be a version which doesn't work with our interface, and our configure script doesn't check (well, we didn't know we needed to check!).  In fact, our configure script doesn't allow gfan to be built by M2 either.

This description is a bit vague still, I will be more precise when I rebuild M2 on ubuntu.  I just wanted to get this in as an issue, to not forget it.

**Comment by DanGrayson** [comment]
I just looked at my Ubuntu builds for 1.15 on 16.04 and 18.04, and for those, I built gfan.  I see also that INSTALL doesn't recommend installing gfan (with apt-get).  So maybe I also encountered a problem, because it is installed on my 18.04 system.  You could leave it to me for later -- this doesn't get forgotten, because when we make another release, I'll run into it.

**Comment by d-torrance** [comment]
I was having some troubles getting the Debian gfan package to play nicely with Macaulay2, did a search, and found this issue.  I finally fixed my problem when I figured out what that the `path` config option needed to be set to.  It doesn't give a very helpful error message when it's not set correctly!  I wonder if that's what you were getting?

Here's an example (on Ubuntu 19.10) that shows both M2's and Ubuntu's gfan packages working, and also shows the error message that's raised when `path` isn't set correctly:

    Macaulay2, version 1.15
    with packages: ConwayPolynomials, Elimination, IntegralClosure, InverseSystems,
                   LLLBases, PrimaryDecomposition, ReesAlgebra, TangentCone,
                   Truncations
    
    i1 : R = QQ[x, y, z]
    
    o1 = R
    
    o1 : PolynomialRing
    
    i2 : I = ideal(x^2 * y - y^2, y^2 * x - x^2)
    
                 2     2     2    2
    o2 = ideal (x y - y , x*y  - x )
    
    o2 : Ideal of R
    
    i3 : -- M2 copy of gfan --
         loadPackage("gfanInterface",
             Configuration => { "path" => "/usr/libexec/Macaulay2/bin/"},
             Reload => true)
    
    o3 = gfanInterface
    
    o3 : Package
    
    i4 : gfan I
    
    o4 = {{(y^5) -y^2, (x*y^2) -y^4, (x^2) -y^4}, {(x^3) -y^3, (x^2*y) -y^2,
         --------------------------------------------------------------------------
         (x*y^2) -x^2, (y^4) -x^2}, {(x^4) -y^2, (x^2*y) -y^2, (x*y^2) -x^2, (y^3)
         --------------------------------------------------------------------------
         -x^3}, {(x^5) -x^2, (x^2*y) -x^4, (y^2) -x^4}}
    
    o4 : List
    
    i5 : -- Ubuntu gfan package --
         loadPackage("gfanInterface",
             Configuration => { "path" => "/usr/bin/"},
             Reload => true)
    
    o5 = gfanInterface
    
    o5 : Package
    
    i6 : gfan I
    
    o6 = {{(y^5) -y^2, (x*y^2) -y^4, (x^2) -y^4}, {(x^3) -y^3, (x^2*y) -y^2,
         --------------------------------------------------------------------------
         (x*y^2) -x^2, (y^4) -x^2}, {(x^4) -y^2, (x^2*y) -y^2, (x*y^2) -x^2, (y^3)
         --------------------------------------------------------------------------
         -x^3}, {(x^5) -x^2, (x^2*y) -x^4, (y^2) -x^4}}
    
    o6 : List
    
    i7 : -- not very useful error messages with bad path --
         loadPackage("gfanInterface",
             Configuration => { "path" => "foo"},
             Reload => true)
    
    o7 = gfanInterface
    
    o7 : Package
    
    i8 : gfan I
    stdio:17:1:(3): error: expected a list, sequence, hash table, or string

**Comment by DanGrayson** [comment]
Do you want to fix it, or shall we ask @dmaclagan to ?  She's listed as the current maintainer.

**Comment by d-torrance** [comment]
I'm about to submit a pull request with a fix, at least to the "gfan's doesn't give us useful error messages" problem.  I'm assuming that this issue originally cropped up because `path` wasn't configured properly to find the Ubuntu package, which was the problem for me.

**Comment by DanGrayson** [comment]
One good way to do it would be to look for it in the PATH, but first append prefixDirectory | currentLayout#"programs" to the PATH.
