### ISSUE TITLE
intersect code disables inheritance

### ISSUE THREAD

**Issue by aarondall** [Macaulay2/M2#1076]
After writing some code that defines a new class X of MonomialIdeal I found that  intersecting an ideal of type X with any other ideal returns an error. The problem is in the code for `intersect(Sequence)`. Instead of testing if `instance(I, MonomialIdeal)`, intersect checks if `class M === MonomialIdeal` in violation of "Use Of Types" section of the [style guide](https://github.com/Macaulay2/M2/wiki/Package-Writing-Style-Guide).

**Comment by DanGrayson** [comment]
Thanks!  Would you like to fix that for us?

**Comment by aarondall** [comment]
Absolutely. But I'm having trouble installing the new version of M2 but I'll sort it out shortly and make the changes. Does it make sense to change all 363 instances in the code (as of v 1.12) of this sort of thing. Or might there be instances when disabling inheritance is the desired effect?

**Comment by DanGrayson** [comment]
I see only 2 instances of `class M === MonomialIdeal`, both in monideal.m2.  But perhaps you are referring to instances of `class something === something`.  Doing a blind replacement of all of them might not be a good idea, and for many of them, it may not be necessary.  For now it's probably best to just fix bugs.

**Comment by pzinn** [comment]
I noticed this too, good it's now an official issue (and I don't have to fix it myself!)

**Comment by mahrud** [comment]
This is fixed in #1385.
