### ISSUE TITLE
font size of examples

### ISSUE THREAD

**Issue by DanGrayson** [Macaulay2/M2#1088]
Currently example output is hard to read in the html documentation, because it is small:
<img width="428" alt="Screen Shot 2020-04-10 at 2 29 15 PM" src="https://user-images.githubusercontent.com/700228/79017779-c95db200-7b37-11ea-8022-46b6668eed76.png">
This is governed in `doc.css`:
<img width="381" alt="Screen Shot 2020-04-10 at 2 29 24 PM" src="https://user-images.githubusercontent.com/700228/79017810-d8446480-7b37-11ea-9399-cc25afe76888.png">
Turning off font-size and line-height seems to help:
<img width="529" alt="Screen Shot 2020-04-10 at 2 31 30 PM" src="https://user-images.githubusercontent.com/700228/79017876-ff9b3180-7b37-11ea-830b-4285a4c448d6.png">
<img width="268" alt="Screen Shot 2020-04-10 at 2 31 50 PM" src="https://user-images.githubusercontent.com/700228/79017891-0b86f380-7b38-11ea-97f1-c6dd8461da05.png">

**Comment by DanGrayson** [comment]
I commented out those lines in doc.css for this file, and it looks okay on a computer, but not a phone: [https://faculty.math.illinois.edu/Macaulay2/doc/Macaulay2-1.14/share/doc/Macaulay2/LocalRings/html/index.html](url).

What's going on?  @mahrud ?

**Comment by DanGrayson** [comment]
Here's the way it looks on a phone:
![Screenshot_20200411-093337](https://user-images.githubusercontent.com/700228/79046611-ada9e880-7bd7-11ea-9ec4-a18a3da7e3c7.png)

**Comment by DanGrayson** [comment]
On the other hand, it looks like this in firefox on my phone:
![Screenshot_20200411-152958](https://user-images.githubusercontent.com/700228/79054343-9daafc80-7c09-11ea-9065-8dd39357eae2.png)

**Comment by mahrud** [comment]
@DanGrayson, I don't think we should manually write or edit a css file from scratch. Take a look at [this page](https://www.w3schools.com/html/html_responsive.asp) on responsive web design. I used [Bootstrap](https://www.w3schools.com/bootstrap/default.asp) for my documentation generator, and if you're okay with changing things up a little bit I can make a PR for doing so.

**Comment by DanGrayson** [comment]
I think we have evidence here of a bug in Android chrome that's not in Android firefox and should figure it out.  Can you try that page out on your phone?
