### ISSUE TITLE
Delete Macaulay2/nash

### ISSUE THREAD

**Issue by mahrud** [Macaulay2/M2#1090]
The comment above `nash.c` reads:

>  nash = "naive shell"
>  a replacement for bash designed just to do commands like this:
> 	/bin/nash -c "exec command arg1 arg2 ..."
>  Hopefully we can use it to make gdb more transparent.

It is potentially useful, but it's not relevant to Macaulay2, so perhaps moving it to a personal repository is more appropriate.

**Comment by DanGrayson** [comment]
done in commit 34684f60e5d61f3b6680cf0b96ec5ba8cf4c86df
