### ISSUE TITLE
Replace Macaulay2/regex with better regex engine

### ISSUE THREAD

**Issue by mahrud** [Macaulay2/M2#1092]
`regex.h` exists on modern systems and is compatible with the rest of our code. Only this chunk would need to be removed or put in a `#ifndef HAVE_REGEX_H` clause:
https://github.com/Macaulay2/M2/blob/002e48263d67673713f9ef42422484181eee1978/M2/Macaulay2/d/scclib.c#L975-L986
See https://github.com/mahrud/M2/commit/57c7ff009a61f308b199df64127f2e6d6c74c2e1 for an example of a fix while keeping the regex directory (note that this also makes building object files in the regex directory unnecessary), though I think we would be fine deleting it.

I tested this on the CMake build and works fine, at least on Linux. A test on Mac would be great.

**Comment by mahrud** [comment]
@DanGrayson, I implemented and tested this on the master branch with this commit: https://github.com/mahrud/M2/commit/111fd551427e844a87151e9bd32711b06e91ac02. Feel free to cherry-pick that commit to the master, though it might be easier to wait and merge the cmake branch, as it already includes these changes.

**Comment by DanGrayson** [comment]
I'd like to get it now.  What OS's have you tested it on?

**Comment by mahrud** [comment]
I've only tested it on Linux.

**Comment by mahrud** [comment]
Continuing the regex discussion from #1095.

> Maybe that's why we include the regex code -- because we like the GNU syntax better than the POSIX syntax. One difference seems to be whether grouping uses `\(...\)` or `(...)`.

[This document](http://web.mit.edu/gnu/doc/html/regex_7.html) describes both APIs. The main advantage of the POSIX API seems to be its portability, so that we don't have to maintain regex code. There's also the [Perl-Compatible Regular Expression](https://www.pcre.org/) library in pcre.h which seems universal. Boost also has a regex library which [supports both](https://www.boost.org/doc/libs/1_72_0/libs/regex/doc/html/boost_regex/syntax.html) POSIX and Perl syntax, so can be a plug-in replacement if neither are present on a system.

**Comment by DanGrayson** [comment]
This code is basically maintenance free, probably less of a headache than writing and maintaining code that searches for compatible code in libraries on the system.

**Comment by mahrud** [comment]
It seems like [lookaheads and lookbehinds](https://www.regular-expressions.info/refadv.html) are not supported:
```
i166 : regex("A(?!B)", "AC AB")
stdio:160:1:(3): error: regex: Invalid preceding regular expression
```
Expected output is a match for "AC" but not "AB".

**Comment by DanGrayson** [comment]
Hmm, it seems the expected match should be the "A" that doesn't have "B" after it.  In any case, that feature sounds useful.

Would you like to try it?  Can you test it on more than one OS?

**Comment by DanGrayson** [comment]
I just looked at what you wrote last month again, and it seems the change is almost trivial.  This bit:
```
#ifdef HAVE_REGEX_H
#include <regex.h>
#else
#include "../regex/regex.h"
#endif 
```
, though, we can do without.  We'll just require regex.h in the system, since we can't tolerate having two copies of Macaulay2 out there with different behavior, and delete `Macaulay2/regex`.  And we should have a test for the modern features of the regular expressions, to make sure they're present.  And then we should document the new features in the documentation node `Macaulay2Doc::regular expressions`.

**Comment by mahrud** [comment]
The problem, as was noted before, is that we use the GNU regex API, which
is not available outside Linux distributions, even if regex.h is present.
The POSIX regex API is more widely available in regex.h, which would
allow us to replace Macaulay2/regex. However, even that doesn't support
lookaheads. Seems like Boost, PCRE, or the C++ std::regex library at least
partially support lookaheads.

I'm not sure where in the d or m2 directories regex functions are defined,
but this would require at least refactoring the section in scclib.c dealing
with regex.

**Comment by DanGrayson** [comment]
As a minimum requirement, the regular expression facility we present to users should be uniform across systems.  On the Mac, I've just looked at the man page for "re_format -- POSIX 1003.2 regular expressions", and it seems that lookahead is not implemented.

On Arch linux, the man pages available are confusing, listing BSD, POSIX, and POSIX.2 styles.

What about the current version of glibc?  Does it support the features you want?  We could extract the code from it as I did 15 years ago, and replace the files in Macaulay2/regex with it, continuing to ensure uniformity across systems.  Presumably the API is the same still.  The info page at https://www.gnu.org/software/libc/manual/html_node/Regular-Expressions.html#Regular-Expressions gives no clue, at least to me.

**Comment by mikestillman** [comment]
I don’t know how good it is, but the c++ standard (as Mahrud mentioned) has a regex library.

**Comment by mahrud** [comment]
@DanGrayson is there any facility for calling an arbitrary C function directly from top level? (even without any arguments)

**Comment by DanGrayson** [comment]
> @DanGrayson is there any facility for calling an arbitrary C function directly from top level? (even without any arguments)

No, there isn't.

**Comment by mahrud** [comment]
I've been trying to take another stab at this for a while, but I'm beginning to think that there isn't a solution that is completely backwards compatible with the current behavior of `regex`. For instance, I can't find any regex engines that would replicate this behavior:
```m2
s = "zzxayyzz";
m = regex(".*?(a|xayy)", s) -- {(0, 6), (2, 4)}
m / (x -> substring(x, s)) -- {zzxayy, xayy}
```
The first output is a reasonable "leftmost, longest" match, as expected from the ERE (extended regular expression) flavor. However, the second output shouldn't be there for the flavor that we're using.

Also, in more flexible regex flavors, you can specify whether you want a greedy or non-greedy match. For instance using the Perl flavor:
```
[mahrud@noether ~]$ echo zzxayyzz | grep -oP ".*(a|xayy)"
zzxa
[mahrud@noether ~]$ echo zzxayyzz | grep -oP ".*?(a|xayy)"
zzxayy
```
The former is "leftmost, lazy", the latter is "leftmost, greedy". But again, no

The closest match I could find involves changing the input regex a little bit from `.*` to `.*?`: using the ECMA flavor, this code:
```cpp
#include <iostream>
#include <string>
#include <regex>
 
int main()
{
    std::string str = "zzxayyzz";
    std::regex re1(".*?(a|xayy)"); // ECMA
    std::smatch m{};
    std::regex_search(str, m, re1);
    for(auto m0 : m)
      std::cout << m0 << ' ';
    std::cout << std::endl;
}
```
gives this output:
```
[mahrud@noether e]$ g++ -std=gnu++14 regex.cpp ; ./a.out 
zzxayy xayy 
```

I'm not sure if such edge cases would break any packages, but honestly I'm beginning to worry that the regex code in M2 might be broken. Here is something unreasonable:
```m2
regex ( "(.*[^ ])?", "abcdef" ) -- {(0, 6), (0, 6)}
```

**Comment by DanGrayson** [comment]
> ```m2
> s = "zzxayyzz";
> m = regex(".*?(a|xayy)", s) -- {(0, 6), (2, 4)}
> m / (x -> substring(x, s)) -- {zzxayy, xayy}
> ```
> 
> ... However, the second output shouldn't be there for the flavor that we're using.
> 

Why shouldn't it be there?

**Comment by mahrud** [comment]
The output of a regular expression check depends on certain assumptions that are baked into the algorithm, and for uniformity are called its flavor. The ERE flavor, which is what we're using based on this line:
https://github.com/Macaulay2/M2/blob/b7f5da4a783b2d664350caf2fde037927c86d7d7/M2/Macaulay2/d/scclib.c#L872
should not return that substring, because in ERE the rule is "leftmost, longest" match. "xayy" can be extended on the left. I thought perhaps the rest of our code is responsible for doing more, like doing another regex search starting a few characters in, but then why isn't `zxayy` listed?

**Comment by DanGrayson** [comment]
I think the reason the (2,4) is present is to indicate which substring the sub-regular-expression in parentheses `(a|xayy)` matched.  So it is correct.

**Comment by mahrud** [comment]
Ah, right, I completely forgot about the subexpressions. I think I'm confused about this C++ code:
```cpp
#include <iostream>
#include <string>
#include <regex>
 
int main()
{
    std::string str = "zzxayyzz";
    std::regex re(".*(a|xayy)", std::regex::extended); // POSIX
 
    std::smatch m;
    std::regex_search(str, m, re);
    for(auto m0 : m)
      std::cout << " POSIX (leftmost longest)  match: " << m0 << '\n';
}
```
What does it output for you? I think for me it is giving the wrong thing:
```
[mahrud@noether mahrud]$ clang++ -std=gnu++20 extended.cpp ; ./a.out 
 POSIX (leftmost longest)  match: zzxa
 POSIX (leftmost longest)  match: a
```

**Comment by mahrud** [comment]
I've experimented with pcre2 and std::regex, and pcre2 has a few more fancy features, but mainly I'm worried about the consistency of std::regex on different compilers.

One thing is that switching to any flavor that has special features like lookaheads would also require changing `.*(a|xayy)` to `.*?(a|xayy)` to keep the output consistent. I don't imagine this being an issue in too many places, but it's still kind of a breaking change. @mikestillman do you have any thoughts on this?

**Comment by DanGrayson** [comment]
> Ah, right, I completely forgot about the subexpressions. I think I'm confused about this C++ code:
> 
> ```c++
> #include <iostream>
> #include <string>
> #include <regex>
>  
> int main()
> {
>     std::string str = "zzxayyzz";
>     std::regex re(".*(a|xayy)", std::regex::extended); // POSIX
>  
>     std::smatch m;
>     std::regex_search(str, m, re);
>     for(auto m0 : m)
>       std::cout << " POSIX (leftmost longest)  match: " << m0 << '\n';
> }
> ```
> 
> What does it output for you? I think for me it is giving the wrong thing:
> 
> ```
> [mahrud@noether mahrud]$ clang++ -std=gnu++20 extended.cpp ; ./a.out 
>  POSIX (leftmost longest)  match: zzxa
>  POSIX (leftmost longest)  match: a
> ```

I get this:

```
-*- mode: compilation; default-directory: "/tmp/" -*-
Compilation started at Mon Jul 20 12:25:38

make -j1 foo && ./foo
g++     foo.cc   -o foo
foo.cc:12:9: warning: 'auto' type specifier is a C++11 extension [-Wc++11-extensions]
    for(auto m0 : m)
        ^
foo.cc:12:17: warning: range-based for loop is a C++11 extension [-Wc++11-extensions]
    for(auto m0 : m)
                ^
2 warnings generated.
 POSIX (leftmost longest)  match: zzxayy
 POSIX (leftmost longest)  match: xayy

Compilation finished at Mon Jul 20 12:25:39
```

**Comment by DanGrayson** [comment]
Breaking-changes are not good.

**Comment by mahrud** [comment]
> Breaking-changes are not good.

I looked into this more, and I don't think this is a breaking change anymore, though it may break code that is written with incorrect assumptions. In the case of `.*(a|xayy)` matching `zzxayyzz`, both `{zzxayy, xayy}` and `{zzxa, a}` are equally valid matches based on the given regular expression, including the captured subexpression, so a program that uses that regular expression should be able to handle that output.

The benefit of moving beyond ERE is that the programmers would have the option to specify whether they want a quantifier like `.*` to be greedy or lazy by using `.*?`. Even programs that assume regex returns the "leftmost, longest" match would be easily fixed by adding `?`.

Take a look at [this discussion](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2003/n1429.htm#syntax_discussion) on the benefits of the ECMAScript flavor:
> The main advantage offered by ECMAScript is that the richer syntax makes it very much easier to author patterns that will match sections of mark-up languages. For example to match a "<font>…</font>" section using the POSIX syntax is much more complicated than it first seems, the obvious expression:
> `<font[^>]*>.*</font>`
would match everything from the first occurrence of "<font" to the last occurrence of "</font>", including any intervening <font> or </font> tags. It is possible to do the right thing using something much more complex like:
> `<font[^>]*>([^<]|<[^/]|</[^f]|</f[^o]|</fo[^n]|</fon[^t]|</font[^>])*</font>`
> which is not especially memorable (nor even a general solution). Where as the ECMAScript equivalent:
> `<font[^>]*>.*?</font>`
> is very much easier.

If all that sounds okay, I'll go ahead with a PR using std::regex so we can properly test it out on various machines.

**Comment by mahrud** [comment]
> If all that sounds okay, I'll go ahead with a PR using std::regex so we can properly test it out on various machines.

I just found out that std::regex and boost::regex have identical syntax, but boost::regex seems to be more uniformly supported, so I'll use that instead.

**Comment by DanGrayson** [comment]
It's probably okay to assign a new meaning to `.*?`, since it looks so strange and we don't document it, provided the old behavior of `.*` is preserved.

**Comment by mahrud** [comment]
The new meaning is for `?`, which can be added to both `*` and `+`.

**Comment by mahrud** [comment]
@DanGrayson is this a bug?
```m2
regex("A", 1, -2, " A ") -- {(1, 1)}
regex("A", 0, -2, " A ") -- null
```
The documentation doesn't seem to imply this behavior.

**Comment by mahrud** [comment]
Also, Dan, would you be okay with dropping support for this part of the current regex function?
> If range is negative, then positions to the left of the starting position are examined for matches.

This is not easily doable in boost or std::regex, and it seems like it isn't used anywhere other than in the documentation:
```m2
[mahrud@noether M2]$ grep -R regex Macaulay2/packages/ | grep -e ", *-"
Macaulay2/packages/Macaulay2Doc/functions/regex-doc.m2:     m = regex("^.*$",8,-8,s)
Macaulay2/packages/Macaulay2Doc/functions/regex-doc.m2:     m = regex("^",10,-10,s)
Macaulay2/packages/Macaulay2Doc/functions/regex-doc.m2:     m = regex("^.*$",4,-10,s)
Macaulay2/packages/Macaulay2Doc/functions/regex-doc.m2:     m = regex("a.*$",4,-10,s)
```

**Comment by mahrud** [comment]
I can't tell if this is a bug either. What does `(-1, 0)` mean here?
```m2
regex(///([^\\])?(@)///, "@haha") -- {(0, 1), (-1, 0), (0, 1)}
```

**Comment by mahrud** [comment]
> Also, Dan, would you be okay with dropping support for this part of the current regex function?
> 
> > If range is negative, then positions to the left of the starting position are examined for matches.
> 
> By the way, this is not a POSIX feature, it's just something that `re_search` from GNU `regex.h` does (here is [the documentation](http://web.mit.edu/gnu/doc/html/regex_7.html#SEC48) for it), so I don't feel bad about losing it and just modifying the documentation.

I managed to implement this, but it breaks lookaheads and lookbehinds completely, and I don't think there's any way to fix it.

**Comment by mahrud** [comment]
Compromise: regex(String, String) supports lookaround, regex(String, ZZ, ZZ, String) doesn't (unless start=0 and range=length).

**Comment by DanGrayson** [comment]
> @DanGrayson is this a bug?
> 
> ```m2
> regex("A", 1, -2, " A ") -- {(1, 1)}
> regex("A", 0, -2, " A ") -- null
> ```
> 
> The documentation doesn't seem to imply this behavior.

The documentation is not very good.  Experimentation shows that `regex(p,n,r,s)` will match p in s at any starting position between n and n+r, endpoints included, and the two results you ask about are consistent with that.  In your second example, there is no match, because 1 is not between 0 and 0-2.

**Comment by DanGrayson** [comment]
> > Also, Dan, would you be okay with dropping support for this part of the current regex function?
> > > If range is negative, then positions to the left of the starting position are examined for matches.

No, I like upward compatibility a lot.

> > 
> > 
> > By the way, this is not a POSIX feature, it's just something that `re_search` from GNU `regex.h` does (here is [the documentation](http://web.mit.edu/gnu/doc/html/regex_7.html#SEC48) for it), so I don't feel bad about losing it and just modifying the documentation.

I feel bad about breaking people's code.

> 
> I managed to implement this, but it breaks lookaheads and lookbehinds completely, and I don't think there's any way to fix it.

**Comment by DanGrayson** [comment]
> I can't tell if this is a bug either. What does `(-1, 0)` mean here?
> 
> ```m2
> regex(///([^\\])?(@)///, "@haha") -- {(0, 1), (-1, 0), (0, 1)}
> ```

It means there was no match for parenthesized subexpression #1.

**Comment by DanGrayson** [comment]
> Compromise: regex(String, String) supports lookaround, regex(String, ZZ, ZZ, String) doesn't (unless start=0 and range=length).

If that preserves upward compatibility, then it's a fine compromise.  (I don't know what "lookaround" is.)

**Comment by mahrud** [comment]
> The documentation is not very good. Experimentation shows that `regex(p,n,r,s)` will match p in s at any starting position between n and n+r, endpoints included, and the two results you ask about are consistent with that. In your second example, there is no match, because 1 is not between 0 and 0-2.

This is very strange, but okay.

> I feel bad about breaking people's code.

I checked, nobody uses `regex(String,ZZ,ZZ,String)` other than in the documentation (which, as you said, is not very good at documenting the behavior either). Unless they have it in private code, but private code breaks all the time.

> It means there was no match for parenthesized subexpression #1.

I'm not sure if this is standard. Boost::regex gives `(5,0)` instead. Note that 5 is the end of the string. Fortunately, `substring(5,0,"@haha") == substring(-1,0, "@haha")`.

> If that preserves upward compatibility, then it's a fine compromise. (I don't know what "lookaround" is.)

Lookaround is a collective term for lookbehind and lookahead:
```m2
regex("A(?!C)","ACAB") -- The A without C after it {(2, 1)}
regex("(?<!C)A","ACAB") -- The A without C before it {(0, 1)}
```

**Comment by DanGrayson** [comment]
> > The documentation is not very good. Experimentation shows that `regex(p,n,r,s)` will match p in s at any starting position between n and n+r, endpoints included, and the two results you ask about are consistent with that. In your second example, there is no match, because 1 is not between 0 and 0-2.
> 
> This is very strange, but okay.
> 
> > I feel bad about breaking people's code.
> 
> I checked, nobody uses `regex(String,ZZ,ZZ,String)` other than in the documentation (which, as you said, is not very good at documenting the behavior either). Unless they have it in private code, but private code breaks all the time.
> 
> > It means there was no match for parenthesized subexpression #1.
> 
> I'm not sure if this is standard. Boost::regex gives `(5,0)` instead. Note that 5 is the end of the string. Fortunately, `substring(5,0,"@haha") == substring(-1,0, "@haha")`.

Not by fortune, but by intent.  The problem with `(5,0)` is that it's in bounds, so you can't tell whether the match is legitimate.

**Comment by mahrud** [comment]
> Not by fortune, but by intent. The problem with (5,0) is that it's in bounds, so you can't tell whether the match is legitimate.

What? Like I said, it is not standard. The zero clearly tells you that it didn't match a real substring. If anything, the choice of the "first character" should not be something wrong:
```m2
"ABCD"_((regex("A(B)?(C)", "ABCD"))#1#0) -- B
"ACD"_((regex("A(B)?(C)", "ACD"))#1#0) -- D
```

**Comment by DanGrayson** [comment]
> > Not by fortune, but by intent. The problem with (5,0) is that it's in bounds, so you can't tell whether the match is legitimate.
> 
> What? The zero clearly tells you that it didn't match a real substring. 

Not true: some regular expressions match a string of length 0.

> If anything, the choice of the "first character" should not be something wrong:
> 
> ```m2
> "ABCD"_((regex("A(B)?(C)", "ABCD"))#1#0) -- B
> "ACD"_((regex("A(B)?(C)", "ACD"))#1#0) -- D
> ```
> 

Actually, those are right, since it's invalid to apply `#0` to a match of length 0.

> Like I said, it is not standard.

It's better than the standard.

**Comment by mahrud** [comment]
@DanGrayson I'm confused about something in 1.16:
```m2
regex("A*(.*)", "AAABBB") -- {(0, 6), (3, 3)}
```
However, since we're using the POSIX Extended syntax, I would have expected the first subexpression to also be matched against the leftmost longest match, which in this case would give `{(0, 6), (0, 6)}`. Isn't that right? Here is the [standard reference](https://pubs.opengroup.org/onlinepubs/9699919799.2008edition/xrat/V4_xbd_chap09.html#tag_21_09_01):
> Conceptually, the implementation must examine every possible match and among those that yield the leftmost longest total matches, pick the one that does the longest match for the leftmost subexpression, and so on.

I can't figure out how this follows from the standards, and even `sed -E` doesn't seem to respect this rule:
```
echo "AAABBB" | sed -E 's/.*(.*)/\1/'

```
(The output is empty!)


Unrelated, but here is an infinite loop bug:
```m2
separateRegexp("\n*", "ABC")
```
What do you think the correct answer should be? `{"ABC"}` or `{"A", "B", "C"}`?

**Comment by DanGrayson** [comment]
I think`A*` is also a subexpression.

**Comment by mahrud** [comment]
> I think`A*` is also a subexpression.

That doesn't seem right, based on the examples and references.
