### ISSUE TITLE
Move kernel/bibasis + use/remove kernel/mixed-cells

### ISSUE THREAD

**Issue by mahrud** [Macaulay2/M2#1093]
- The contents of [mixed-cells](https://github.com/Macaulay2/M2/tree/master/M2/Macaulay2/kernel/mixed-cells) doesn't seem to be used anywhere
- [bibasis](https://github.com/Macaulay2/M2/tree/master/M2/Macaulay2/kernel/bibasis) is used in e/engine.h, so maybe it should become a subdirectory of Macaulay2/e.

Then Macaulay2/kernel can be removed.

**Comment by mahrud** [comment]
@DanGrayson, commit https://github.com/mahrud/M2/commit/111fd551427e844a87151e9bd32711b06e91ac02 moves kernel/bibasis to e/bibasis for the master branch. However, it is already included in the cmake branch, so it might be easier to just merge with the cmake branch and avoid future merge conflicts.

@antonleykin, do you know what is the status of mixed-cells?

**Comment by DanGrayson** [comment]
I like incremental changes.  Shall I cherry pick it, or do you want to make a pull request?

**Comment by mahrud** [comment]
Okay, I'll make a pull request with all the clean ups then.
