### ISSUE TITLE
Remove Macaulay2/e-includes

### ISSUE THREAD

**Issue by mahrud** [Macaulay2/M2#1094]
This directory seems to serve 4 unrelated purposes:

1. The README reads:
> The purpose of this directory is to make the include files needed by the source files in ../e/.

However, most header files are already in Macaulay2/e, and I think keeping .cpp and .hpp files together makes more sense.

2. [doc-generateD](https://github.com/Macaulay2/M2/blob/master/M2/Macaulay2/e-includes/doc-generateD) states: (along with much more)
> Want to automate the process of writing d functions.

This seems very useful, but other than templates.txt, no other files here seem to be related to this. Perhaps this can move to a separate branch for that project.

3. The [Makefile](https://github.com/Macaulay2/M2/blob/master/M2/Macaulay2/e-includes/Makefile.in) has three targets to read the file `geoT.hpp` and use some `sed` rules to generate `geogbvec.hpp`, `geores.hpp`, and `geovec.hpp`:
  - `geogbvec.hpp` is generated, but the class `gbvectorHeap` is actually defined in `e/gbring.hpp`;
  - `geores.hpp` is included in `e/res-a0.cpp`;
  - `geovec.hpp` is never generated, but `e/geovec.hpp` exists and looks approximately as if the generated output was saved there.

Since testing with `geores.hpp` was easier, I wrote a templated geobucket type and replaced it with `geores.hpp` and everything seems to have worked fine.

4. install [statuscodes](https://github.com/Macaulay2/M2/blob/master/M2/Macaulay2/e-includes/statuscodes) in the Core directory and generate statuscodes.h from it.

These two files are only used by `m2/gb.m2` and `e/engine.h` as enums, but perhaps there's a better way to do this so we don't have an extra moving part in the build.

**Comment by mahrud** [comment]
3. correction: the generated geovec.hpp is not the same as e/geovec.hpp. Seems like a few functions are specialized, like `add_vec_to`, `n_nonzero_terms`, and `remove_vec`.

**Comment by mahrud** [comment]
Done in https://github.com/mahrud/M2/commit/7417f65ea4080e68e4b47bd9066bf50246e431f3.

(equivalently in https://github.com/mahrud/M2/commit/111fd551427e844a87151e9bd32711b06e91ac02 for the master branch)

**Comment by DanGrayson** [comment]
I've reopened this so we can consider incorporating it into the master branch now.
