### ISSUE TITLE
Index shift issue in TateOnProducts

### ISSUE THREAD

**Issue by mahrud** [Macaulay2/M2#1100]
Last VirtualResolutions PR attempted to fix a small indexing issue in TateOnProducts to correct the computation of tateResolutions for products of three or more projective spaces, but because there wasn't enough time before the deadline, that change was reverted.

Please re-revert this commit: https://github.com/Macaulay2/M2/pull/1046/commits/bb45e1547bfed9d0f21d7a76c06fd40ce45cb254

See the review: https://github.com/Macaulay2/M2/pull/1046#pullrequestreview-317687010

**Comment by DanGrayson** [comment]
To whom is "Please ..." addressed?
