### ISSUE TITLE
Error when running make check

### ISSUE THREAD

**Issue by aarondall** [Macaulay2/M2#1108]
During a clean install on a MacBook running 10.15.4 I get the following error when attempting to run the optional `make check`. I'm wondering if there's a fix for that or if I should just skip the check and go directly to the install.  

```
testing: schenck-book-7.m2
../../../m2/debugging.m2:20:6:(1):[39]: error: the file /Users/mybrittlepony/M2
/M2/Macaulay2/packages/Macaulay2Doc/test/pushforward.m2 did not define a package 
called PushForward
../../../m2/packages.m2:66:46:(1):[38]: --back trace--
../../../m2/methods.m2:119:80:(1):[37]: --back trace--
../../../m2/option.m2:15:8:(1):[36]: --back trace--
../../../m2/packages.m2:88:11:(1):[35]: --back trace--
../../../m2/methods.m2:119:80:(1):[34]: --back trace--
../../../m2/option.m2:15:8:(1):[33]: --back trace--
../../../m2/packages.m2:305:6:(1):[31]: --back trace--
../../../m2/methods.m2:119:80:(1):[30]: --back trace--
../../../m2/option.m2:15:8:(1):[29]: --back trace--
../../Schubert2.m2:2:1:(3):[28]: --back trace--
../../../m2/setup.m2:113:27:(1):[28]: --back trace--
../../../m2/setup.m2:106:18:(1):[27]: --back trace--
../../../m2/setup.m2:126:41:(1):[26]: --back trace--
../../../m2/setup.m2:129:6:(1):[25]: --back trace--
../../../m2/packages.m2:62:6:(1):[24]: --back trace--
../../../m2/methods.m2:119:80:(1):[23]: --back trace--
../../../m2/option.m2:15:8:(1):[22]: --back trace--
../../../m2/packages.m2:88:11:(1):[21]: --back trace--
../../../m2/methods.m2:119:80:(1):[20]: --back trace--
../../../m2/option.m2:15:8:(1):[19]: --back trace--
../../../m2/packages.m2:164:6:(1):[17]: --back trace--
../../../m2/methods.m2:119:80:(1):[16]: --back trace--
../../../m2/option.m2:15:8:(1):[15]: --back trace--
../../NormalToricVarieties.m2:18:1:(3):[14]: --back trace--
../../../m2/setup.m2:113:27:(1):[14]: --back trace--
../../../m2/setup.m2:106:18:(1):[13]: --back trace--
../../../m2/setup.m2:126:41:(1):[12]: --back trace--
../../../m2/setup.m2:129:6:(1):[11]: --back trace--
../../../m2/packages.m2:62:6:(1):[10]: --back trace--
../../../m2/methods.m2:119:80:(1):[9]: --back trace--
../../../m2/option.m2:15:8:(1):[8]: --back trace--
../../../m2/packages.m2:88:11:(1):[7]: --back trace--
../../../m2/methods.m2:119:80:(1):[6]: --back trace--
schenck-book-7.m2:1:1:(3):[4]: --back trace--
../../../m2/setup.m2:113:27:(1):[4]: --back trace--
../../../m2/setup.m2:106:18:(1):[3]: --back trace--
../../../m2/setup.m2:126:41:(1):[2]: --back trace--
../../../m2/setup.m2:131:24:(1):[1]: --back trace--
../../../d/startup.m2.in:723:10:(0): --back trace--
schenck-book-7.errors:0: error output left here for the errors above:
gmake[2]: *** [Makefile.test:67: schenck-book-7.out] Error 1
gmake[2]: Leaving directory '/Users/mybrittlepony/M2/M2/Macaulay2/packages/Macaulay2Doc/test'
gmake[1]: *** [Makefile:20: check-in-packages/Macaulay2Doc/test] Error 2
gmake[1]: Leaving directory '/Users/mybrittlepony/M2/M2/Macaulay2'
gmake: *** [GNUmakefile:196: check-in-Macaulay2] Error 2
gmake: Leaving directory '/Users/mybrittlepony/M2/M2'
```

**Comment by mikestillman** [comment]
Where are you running the `make check`?  It looks as if the `Macaulay2/test` directory is on your path for some reason.  When the test `schenck-book-7` is being run, it is trying to load the package `PushForward`.  But, since you appear to be on a mac which has case insensitive file names, it sees the file `pushforward.m2`, and mistakenly uses that file.

Usually, to run the tests, you should be in the build tree, either at the top of it, or in its `Macaulay2` subdirectory.  There, run `make check`.  But this is good to note!  We should rename that test, especially as far as I can tell, it has not much to do with the pushForward function.

**Comment by aarondall** [comment]
The clone of the git repository is in my home folder. I'm running the `make check` from the M2 subdirectory that includes the INSTALL instructions which state

> Now the directory to be in is the one containing this file in the source
> distribution -- it is called "M2", and is a subdirectory of the top level
> directory of the source tree. 

Is that not the right place to be?

**Comment by DanGrayson** [comment]
The problem seems to be that "." is on the path, he is building in the source tree, the OS is case-insensitive, and the current directory is `packages/Macaulay2Doc/test/`.  But why haven't we run into this before?

**Comment by aarondall** [comment]
Any hints on how to proceed? I've recently done a factor reset of my machine, if that info helps in anyway...

**Comment by DanGrayson** [comment]
The quick work-around would be to build in a directory other than the source directory.

**Comment by DanGrayson** [comment]
... maybe.

**Comment by aarondall** [comment]
Does that just amount to using a prefix in the second line below to point to some other directory in my home folder, say? Or is there more to it than that? 

```
make
./configure --enable-download --prefix=/foo/bar
make
make check                      # optional
make install
```

Thanks for all your help so far!

**Comment by DanGrayson** [comment]
No, you have to be in another directory.  Simplest for you might be this:
```
cd BUILD/dan
make
```

**Comment by mahrud** [comment]
Closing in favor of #3145.
