### ISSUE TITLE
prune doesn't preserve degrees in polynomial rings over ZZ

### ISSUE THREAD

**Issue by mikestillman** [Macaulay2/M2#1116]
The following code forgets the degrees of the generators of `prune coker f`.  This code works fine over a field.  This is a bug.
```
S = ZZ[a,b]
f = map(S^{-2, -2, -3},S^{-3, -4},{{-b, 0}, {a, -b^2}, {-1, a}})
isHomogeneous f
assert(degrees coker f == {{2}, {2}, {3}})
assert(degrees prune coker f != {{0}, {0}})
 ```

**Comment by DanGrayson** [comment]
To fix it, we could preserve the free modules provided by `mingens` in the following code for reuse when reconstituting the matrix f from the mutable matrix f in the line `f = matrix f`.
```
o35 = ../../../../Macaulay2/m2/modules2.m2:400:54-420:17: --source code:
      addHook(Module, symbol minimalPresentation, (opts,M) -> (
                -- we try to handle any module here, without any information about the ring
                f := mutableMatrix mingens gb presentation M;
                row := 0;
                piv := new MutableHashTable;
                pivColumns := new MutableHashTable;
                scan(numRows f, row -> (
                     scan(numColumns f, col -> if not pivColumns#?col and isUnit f_(row,col) then (
                                    piv##piv = (row,col);
                                    pivColumns#col = true;
                                    columnMult(f,col,1//f_(row,col));
                                    scan(numColumns f, j -> if j != col then columnAdd(f,j,-f_(row,j),col));
                                    break))));
                piv = values piv;
                f = matrix f;
                rows := first \ piv;
                cols := last \ piv;
                f = submatrix'(f,rows,cols);
                N := cokernel f;
                N.cache.pruningMap = map(M,N,submatrix'(id_(cover M),rows));
                break N))
```

**Comment by DanGrayson** [comment]
That code is 14 years old!

**Comment by DanGrayson** [comment]
The change I made broke two tests overnight, so I've reverted it, see fd78760e774de81d1a8bdc13877f90539537600c .

**Comment by DanGrayson** [comment]
Here are the input files for the tests:
[6.m2.txt](https://github.com/Macaulay2/M2/files/4581199/6.m2.txt)
[4.m2.txt](https://github.com/Macaulay2/M2/files/4581200/4.m2.txt)

**Comment by mikestillman** [comment]
The fix I have makes `FastLinAlg` fail a couple of tests, the ones that @DanGrayson mentions.  I know how to fix that, I think.  This might be considered a bug in `FastLinAlg`, and if so, I'll post that as a new issue.

**Comment by DanGrayson** [comment]
How does your fix compare to my fix?

**Comment by mikestillman** [comment]
I just looked at your fix, I think. And it appears to be IDENTICAL to the one I did (even to names of variable, spacing).  Scary!  I should have looked at that first, sorry.

I think the problem though is that if the module is not graded, then this function originally set all generators to be of degree 0 (as it probably should), and it appears that the `FastLinAlg` package is using that somehow in their code.  Is this true @kschwede ?

I think I'll add in a check for homogeneity.  If the module is not homogeneous, then we won't set the degrees of the resulting map from the input data.

**Comment by mikestillman** [comment]
I am pushing a fix.  It runs on the three examples above, and shouldn't affect (always a bad way of thinking in programming!) most other uses.  I will run the examples and tests now too.

**Comment by DanGrayson** [comment]
That sure looks like my fix!  Amazing.  Great minds think alike.

But my fix broke those two examples.

**Comment by mikestillman** [comment]
All 3 of the examples here, which previously failed, now work.  So I'm closing this issue.
