### ISSUE TITLE
IntegralClosure gives wrong answers

### ISSUE THREAD

**Issue by unlblh** [Macaulay2/M2#1117]
The IntegralClosure package doesn't work correctly 
for integral closures of ideals in polynomial rings.
Even for a relatively simple monomial ideal, versions
1.4 and 1.9.2 give the wrong answer, but at least the answer
is an ideal that includes the starting ideal. Version 1.14
claims the closure is the empty ideal.

Let I=ideal(abd,ace,bcf,def) be in the ring QQ[a,b,c,d,e,f].
It is fairly easy by hand to show that (abcdef)^2 is in I^4 but not in I^2.
Thus abcdef is in the integral closure of I^2 but not in I^2. This is not what
Macaulay2 finds.

Here's the code for the computation.
```
R=QQ[a,b,c,d,e,f]
I=ideal(a*b*d,a*c*e,b*c*f,d*e*f);
J=I^2;
K=integralClosure(I,2)
F=ideal(a*b*c*d*e*f);
isSubset(F,J)
isSubset(F,K)
isSubset(F^2,J^2)
K==J
```
Below are two sample sessions, one using version 1.9.2 (which agreed with version 1.4
which I also ran), and the other using version 1.14.
The commands 
```
isSubset(F,J)
isSubset(F^2,J^2)
```
show (abcdef)^2 is in (I^2)^2 but that F is not in I^2, as I verified by hand.
Thus F should be in the integral closure K of J=I^2, but isSubset(F,K)
comes back false. In fact, it turns out under version 1.9.2 (and 1.4), 
K==J comes back true, so Macaulay2 claims I^2 is integrally closed, 
which is not the case. Under version 1.14 both isSubset(F,K) and K==J came 
back false, because K came back as the empty ideal.

Here's the date the output below was obtained: May 2, 2020, 10:39 EST

The following session was run on a MacBook with 16G ram under MacOS 10.15.3
(I got the same results with version 1.4 on a 2008 MacBook under 10.6.8.)	
```
Macaulay2, version 1.9.2
with packages: ConwayPolynomials, Elimination, IntegralClosure, LLLBases,
               PrimaryDecomposition, ReesAlgebra, TangentCone

i1 : R=QQ[a,b,c,d,e,f]

o1 = R

o1 : PolynomialRing

i2 : I=ideal(a*b*d,a*c*e,b*c*f,d*e*f);

o2 : Ideal of R

i3 : J=I^2;

o3 : Ideal of R

i4 : K=integralClosure(I,2)

             2 2 2           2   2 2 2         2        2          2    
o4 = ideal (d e f , b*c*d*e*f , b c f , a*c*d*e f, a*b*d e*f, a*b*c e*f,
     ---------------------------------------------------------------------------
        2        2 2 2   2          2 2 2
     a*b c*d*f, a c e , a b*c*d*e, a b d )

o4 : Ideal of R

i5 : F=ideal(a*b*c*d*e*f);

o5 : Ideal of R

i6 : isSubset(F,J)

o6 = false

i7 : isSubset(F,K)

o7 = false

i8 : isSubset(F^2,J^2)

o8 = true

i9 : K==J

o9 = true
```

Here's a session run on http://habanero.math.cornell.edu:3690 using Safari 13.0.5 on the same MacBook with 16G ram under MacOS 10.15.3.
```
Macaulay2, version 1.14
--storing configuration for package FourTiTwo in /home/m2user/.Macaulay2/init-FourTiTwo.m2
--storing configuration for package Topcom in /home/m2user/.Macaulay2/init-Topcom.m2
with packages: ConwayPolynomials, Elimination, IntegralClosure, InverseSystems, LLLBases,
               PrimaryDecomposition, ReesAlgebra, TangentCone, Truncations

i1 : R=QQ[a,b,c,d,e,f]

o1 = R

o1 : PolynomialRing

i2 : I=ideal(a*b*d,a*c*e,b*c*f,d*e*f);

o2 : Ideal of R

i3 : J=I^2;

o3 : Ideal of R

i4 : K=integralClosure(I,2)

o4 = ideal ()

o4 : Ideal of R

i5 : F=ideal(a*b*c*d*e*f);

o5 : Ideal of R

i6 : isSubset(F,J)

o6 = false

i7 : isSubset(F,K)

o7 = false

i8 : isSubset(F^2,J^2)

o8 = true

i9 : K==J

o9 = false
```

**Comment by DanGrayson** [comment]
Compare with #846

**Comment by unlblh** [comment]
The people discussing this at #846 seem to have the impression that this is a bug that occurred
recently, but my tests suggest the IntegralClosure package has not worked since at least 2008.

Versions 1.4 through 1.9 compute simple examples correctly but fail with slightly more
complicated examples; however the incorrectness of the output is not obvious. Recent versions
like 1.13 and later have the advantage of giving output that is obviously incorrect.

On May 3, 2020, at 9:53 AM, Daniel R. Grayson <notifications@github.com<mailto:notifications@github.com>> wrote:



Compare with #846<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_Macaulay2_M2_issues_846&d=DwMCaQ&c=Cu5g146wZdoqVuKpTNsYHeFX_rg6kWhlkLF8Eft-wwo&r=R7FLfN02u5ptRRdcMFCkzibLgtqsK3Vo8nrC8o-jwkU&m=8_lJRX9LQFqiX4iEmjozkl1N3YoOyk8s1G4zqBLk8Mk&s=yTne5apXHAptgi-pnqFPdiqRM7NFK5AA5CPDt8Jg-vY&e=>

**Comment by eisenbud** [comment]
@unlblh: Mike Stillman and I have been working on fixing the
IntegralClosure.m2 bug that you pointed out below -- thanks for the simple
example! We have code that does this one correctly now (not yet in the main
repo) but we'd like to test it on other examples. We have some...but
perhaps you have different ones. If you have some you're interested in, or
feel are indicative, please let us know!

(best to write to me and Mike directly: de@msri.org and
mikestillman1@gmail.com , for example.)

Thanks,

David
--
David Eisenbud, Director,
Mathematical Sciences Research Institute
and Professor of Mathematics,
University of California, Berkeley
