### ISSUE TITLE
configure.ac pow/libm not found.

### ISSUE THREAD

**Issue by Wolfereign** [Macaulay2/M2#1119]
Hi, I'm trying to compile Macaulay2 version 1.15 (also tried master branch) but I keep getting an error that configure cannot find the libm math library.  I don't get this error in 1.14.0.1 and earlier but I cannot build those due to a libflint.so linking error.

```configure.ac
AC_SEARCH_LIBS(pow,m,,AC_MSG_ERROR(libm not found or not linkable))
```
![image](https://user-images.githubusercontent.com/5723368/80929382-d18cc400-8d68-11ea-86eb-7c736970c027.png)

![image](https://user-images.githubusercontent.com/5723368/80929931-26cad480-8d6d-11ea-9638-ee7c8aaedd85.png)

![image](https://user-images.githubusercontent.com/5723368/80929977-73161480-8d6d-11ea-8405-f00748317263.png)

[spack-build-out.txt](https://github.com/Macaulay2/M2/files/4572356/spack-build-out.txt) (Console Output)
[config.log](https://github.com/Macaulay2/M2/files/4572359/config.log) (M2 config.log file)
[package.py.txt](https://github.com/Macaulay2/M2/files/4572369/package.py.txt) (Spack build/package recipe)

Just to give context I'm building Macaulay2 with the [Spack Package Manager](https://spack.io/) for my HPC Cluster.  I'm using the CentOS 7 and the GCC that ships with it (including the static libraries).  I've also tried this with GCC 9.2.0 with the same error.

If you have any ideas on what I'm missing please let me know.

**Comment by DanGrayson** [comment]
I think it's a long-standing bug in my configure.ac script.  Relative to the master branch, this patch ought to fix it:
```
diff --git a/M2/configure.ac b/M2/configure.ac
index 0d1943f5e..656850b57 100644
--- a/M2/configure.ac
+++ b/M2/configure.ac
@@ -1751,9 +1751,12 @@ AC_PREPROC_IFELSE(
    [AC_LANG_SOURCE([[
 	#include <libxml2/libxml/xmlexports.h>
 	]])],
-   LIBXML_LOCATION=` grep libxml2/libxml/xmlexports.h conftest.i | sed 's=.* "\(.*\)/libxml/xmlexports.h.*=\1=' `)
-AC_MSG_NOTICE(found in libxml2: will search for include files also in $LIBXML_LOCATION)
-CPPFLAGS="-isystem $LIBXML_LOCATION $CPPFLAGS"
+   [ LIBXML_LOCATION=` grep libxml2/libxml/xmlexports.h conftest.i | sed 's=.* "\(.*\)/libxml/xmlexports.h.*=\1=' `
+     AC_MSG_NOTICE(libxml found in libxml2: will search for include files also in $LIBXML_LOCATION)
+     CPPFLAGS="-isystem $LIBXML_LOCATION $CPPFLAGS"
+     ]
+   )
+
 AC_CHECK_HEADERS(libxml/xmlexports.h libxml/parser.h)
 
 AC_SEARCH_LIBS(pow,m,,AC_MSG_ERROR(libm not found or not linkable))
```

**Comment by DanGrayson** [comment]
... and I've just pushed it as commit 7e4b88772ac7e0f84d9af8241e134cb3bde84105

**Comment by Wolfereign** [comment]
Just tested the patch and that fixed the error I mentioned above.  Thank you for the quick response!

**Comment by DanGrayson** [comment]
Thank you for the detailed bug report!
