### ISSUE TITLE
volume errors in Polyhedra package

### ISSUE THREAD

**Issue by d-torrance** [Macaulay2/M2#1120]
I'm getting the following errors when building the documentation for the `Polyhedra` package.  Note that this build is from my draft of a Debian package based on the `eigen` branch.  I'm not sure if this issue is present in `master` or not.

    root@gloria:/build/macaulay2-1.14.0.1-652-g728c8a3f0/M2/usr-dist/common/share/doc/Macaulay2/Polyhedra/example-output# cat *.errors
    -- -*- M2-comint -*- hash: -140647972
    
    i1 : latticeVolume hypercube 3
    stdio:1:1:(3): error: expected argument 1 to be a list, sequence, or an integer
    -- -*- M2-comint -*- hash: -1180532819
    
    i1 : P = crossPolytope 2
    
    o1 = P
    
    o1 : Polyhedron
    
    i2 : Q = hypercube 2
    
    o2 = Q
    
    o2 : Polyhedron
    
    i3 : mixedVolume {P,Q}
    stdio:3:1:(3): error: expected argument 1 to be a list, sequence, or an integer
    -- -*- M2-comint -*- hash: -2068086932
    
    i1 : P = crossPolytope 2
    
    o1 = P
    
    o1 : Polyhedron
    
    i2 : Q = secondaryPolytope P
    stdio:2:5:(3): error: expected argument 1 to be a list, sequence, or an integer
    -- -*- M2-comint -*- hash: 820909247
    
    i1 : P = crossPolytope 3
    
    o1 = P
    
    o1 : Polyhedron
    
    i2 : volume P
    stdio:2:1:(3): error: expected argument 1 to be a list, sequence, or an integer

**Comment by d-torrance** [comment]
I noticed that the `Polyhedra`  requires the `Topcom` package, but TOPCOM itself isn't available yet in Debian, and I didn't build it.  Could that be the source of the error messages?

**Comment by DanGrayson** [comment]
> I noticed that the `Polyhedra` requires the `Topcom` package, but TOPCOM itself isn't available yet in Debian, and I didn't build it. Could that be the source of the error messages?

No, we build it ourselves and include it, if it's not in the OS.

**Comment by DanGrayson** [comment]
I don't know what could be causing that, and I've never seen it at this end.  Perhaps turn on debugging for the packages involved and track it down.  Or give me a pointer to your development branch.

**Comment by d-torrance** [comment]
I'm specifically not building it by including `topcom` in the `--with-unbuilt-programs` option to `configure`.  Since this is the for the draft of the Debian package, I'm trying to get Macaulay2 to use only other Debian packages and build nothing except itself.

I'm pretty certain now that this is the source of this error.  I was getting a similar error with `gfanInterface`, and I hadn't patched it yet to point to the Debian copy of gfan.  So this will likely be resolved once TOPCOM is in Debian (which I'm also working on).

I'll go ahead and close this issue.  Sorry for the noise!

**Comment by DanGrayson** [comment]
Oh, okay.  But still, if it's caused by the program not being found, the package should give a more illuminating error message.  That can be regarded as a bug in it, worth reporting if confirmed.

**Comment by d-torrance** [comment]
Great point.  I just opened #1121 to address this.

**Comment by DanGrayson** [comment]
Now I'm getting the failure of gfanInterface examples under Arch Linux, where I've installed gfan.
I'll make an issue.

**Comment by DanGrayson** [comment]
Wait a minute, I think we already had an issue for gfanInterface, but I can't find it ...

**Comment by d-torrance** [comment]
Closing since the underlying problem is addressed in #1121.
