### ISSUE TITLE
Why a new language?

### ISSUE THREAD

**Issue by scratchmex** [Macaulay2/M2#1122]
As the title says, I'm just curious why implement a **new** programming language and all the difficulties that entails, like:
- parser
- compiler
- types

and not implement the algorithms in a language that supports C++ as backend like Python for example.

**Comment by DanGrayson** [comment]
Are you referring to the language the files M2/Macaulay2/d/*.d are written in, or to the top level interpreted language?

If the former, then I wanted a type-safe compiled language that I could compile on any machine that had a C compiler.  If the latter, then I wanted to support mathematics in a particular way.  

Both decisions were made in 1992.

**Comment by radoslavraynov** [comment]
... which makes M2 decidedly not new :D Python's first release is from 1991, Java's from 1995.

(On the other hand, I've actually always wanted to decouple M2's runtime from the core and have, e.g., a headless compile-only variant or a Python variant. If Python or friends are used for the top-level, then d isn't needed.)
