### ISSUE TITLE
`make check-libtool` doesn't work as expected?

### ISSUE THREAD

**Issue by haerski** [Macaulay2/M2#1128]
My libtool version is listed as `2.4.6.42-b88ce-dirty`, and because of this, the command `make` fails when checking the libtool version (libtool is too old). The part in `M2/Makefile` that parses the libtool version is

    MAJOR=`libtool --version | sed -e '1s/.* \([1-9][0-9]*\)\..*/\1/' -e '2,$$d'` ;
    MINOR=`libtool --version | sed -e '1s/.*\.\([1-9][0-9]*\)\..*/\1/' -e '2,$$d'` ;
    BABY=`libtool --version | sed -e '1s/.*\..*\.\([1-9][0-9]*\)/\1/' -e '2,$$d'` ;

In my case, `MAJOR` is `4`, `MINOR` is `6`, and `BABY` is `42-b88ce-dirty`. Is this working as intended? I would assume it should be `MAJOR.MINOR.BABY = 2.4.6`, right?

I don't get the error when I run `make get-tools`, and `./configure` runs fine, but the second `make` eventually throws a libtool version mismatch error.

**Comment by DanGrayson** [comment]
fixed in commit aafec95afd3b3bf0c52c1f777562b38471a0a436 on the master branch
