### ISSUE TITLE
TAR file downloads missing

### ISSUE THREAD

**Issue by Wolfereign** [Macaulay2/M2#1129]
I'm looking to install Macauley2 for a HPC cluster running CentOS 7.  We typically handle software using Lmod/TLC modules, on shared storage, and keep the individual compute nodes as minimal as possible.  My attempts at compiling from source are slow going (using Spack and external libraries) and I would like to get the newest release available to my users as soon as possible while I workout bugs with my build system.

I tried following the instructions here [http://www2.macaulay2.com/Macaulay2/Downloads/GNU-Linux/InstallingFromTarFiles.txt](http://www2.macaulay2.com/Macaulay2/Downloads/GNU-Linux/InstallingFromTarFiles.txt) but the download files for the architecture are missing at [http://www2.macaulay2.com/Macaulay2/Downloads/GNU-Linux/Generic/index.html](http://www2.macaulay2.com/Macaulay2/Downloads/GNU-Linux/Generic/index.html).

I also looked at downloading the tar files for CentOS/Rhel specifically but the newest was for 1.11 (2018).

Is there any chance a newer precompiled version can be made available in the TAR format.

**Comment by DanGrayson** [comment]
What about trying the rpm files (for M2 1.15) at https://faculty.math.illinois.edu/Macaulay2/Downloads/GNU-Linux/Red%20Hat%20Enterprise,%20CentOS,%20Scientific%20Linux/index.html built for Scientific Linux?  It ought to be compatible.

**Comment by Wolfereign** [comment]
If I use the RPM I would need to install the software and multiple dependencies on 50+ nodes instead of putting the software on shared storage and using a module system to load it.  

I'll keep working on compiling with external dependencies (may have a few bugs reports to put in).  I just figured I would check if the TAR limited dependency  that was mentioned were available on a newer version.  The current, older, one worked when combined with loading a few dependencies through Lmod on non-standard paths.

**Comment by DanGrayson** [comment]
I'm not sure what the problem is with rpm's since it's easy to extract the files within them and put them where you want.  Could you clarify?

What do you mean by "the TAR limited dependency"?  Maybe you're saying that you want a version compiled statically that uses as few dynamic libraries as possible, and thus has as few dependencies as possible.  We gave up trying to do that years ago for lack of demand.

**Comment by Wolfereign** [comment]
I hadn't considered manually extracting the contents from the RPM.  I'll give that a go.
