### ISSUE TITLE
a git issue

### ISSUE THREAD

**Issue by DanGrayson** [Macaulay2/M2#1132]
How does one resolve a submodule conflict?  Mike wants to know.

**Comment by radoslavraynov** [comment]
Submodules &mdash; for the purpose of git &mdash; are just SHA-1 (or SHA-256) hashes. If you have a conflict it's probably just because the two commits have the submodule pointing to a different commit in the original repo. Just go to the repo, resolve (e.g. by finding the later version) and restamp the submodule hash.

**Comment by DanGrayson** [comment]
There are undefined words in what you said: "resolve", "finding", "restamp".

**Comment by mahrud** [comment]
Why doesn't the configure script run `git submodule sync`?  This is what cmake does.

**Comment by DanGrayson** [comment]
Is it useful?

**Comment by mahrud** [comment]
Yes, and sorry, I meant submodule update. This is the full command:
```
git submodule update --init --recursive
```

**Comment by DanGrayson** [comment]
I think `git submodule update` should be left to the user: imagine working on the code of one of the submodules to repair it or to develop it.  You wouldn't want running configure to screw up what branch of the submodule you're on.

**Comment by mahrud** [comment]
That's easy: first you commit the changes within the submodule, then
outside the submodule you add and commit the change in the submodule commit
hash.

Or you can have an option for disabling submodule updates, like
`cmade -DGIT_SUBMODULE=off`.

**Comment by DanGrayson** [comment]
No, because you want to test your changes to the submodule before committing them.  And you may want to consult other developers of M2 before committing changes to it.

**Comment by mahrud** [comment]
Just run `cmake -DGIT_SUBMODULE=off .`, or an equivalent for configure, to
disable that.

**Comment by DanGrayson** [comment]
Ah, so your suggestion can be interpreted this way:

By default, the top level makefile, M2/GNUmakefile.in, should update the submodules, since
that helps naive users keep the entire tree up to date, and there should also be a configure script
option added to disable that, for the convenience of the developers who want to develop 
code within a submodule.

That would make a nice issue.  Would you like to post it?
