### ISSUE TITLE
Modifying the complex from res I changes the cached value.

### ISSUE THREAD

**Issue by jkyang92** [Macaulay2/M2#1137]
Since resolutions are cached, the following code causes `res I` to return the wrong complex

```
R = QQ[x,y];
I = ideal(x,y);
r = res I;
print r;
r#0 = R^2;
print res I;
```

The straightforward fix would be to return a copy rather than the cached value.

--
Jay Yang

**Comment by DanGrayson** [comment]
This probably doesn't need to be fixed, since the user intentionally changed the resolution by typing `r#0 = R^2`.

**Comment by mahrud** [comment]
Also, I don't know if making copies of resolutions is a good idea. It could really slow down things involving huge resolutions. Would it be reasonable to make resolutions returned by `res` immutable?

**Comment by mahrud** [comment]
I think this can be close. Feel free to reopen if further discussion is needed.
