### ISSUE TITLE
Hypertext types update to allow more attributes

### ISSUE THREAD

**Issue by pzinn** [Macaulay2/M2#1142]
Title says it all. Descendants of `Hypertext`, i.e., types which imitate the structure of html, should be made more useful by adding more allowed attributes.
e.g., `IMG` should have attributes `width`, `height`, `style` and probably plenty more.

I will look into it soon, but this is just so I don't forget.

**Comment by DanGrayson** [comment]
Good idea.  Any volunteers?

**Comment by DanGrayson** [comment]
Oh, I guess you're volunteering, so I'll assign you.

**Comment by pzinn** [comment]
Found a couple of bugs along the way. One of the more annoying ones:
```
i1 : needsPackage "Text"
o1 = Text
o1 : Package

i2 : new LI from "hi" -- should accept but doesn't
stdio:2:1:(3): error: expected new class to be a specialization of the old one

i3 : LI "hi" -- works fine
o3 = hi
o3 : LI

i4 : new LI from 1 -- should probably reject but not with cryptic message
stdio:4:1:(3): error: expected new class to be a specialization of the old one

i5 : LI 1 -- should probably reject but not with cryptic message
stdio:5:1:(3): error: expected new class to be a specialization of the old one
```

**Comment by pzinn** [comment]
I agree with this comment:
```
TEX = withQname_"#PCDATA" new MarkUpType of Hypertext -- TEX really needs to be processed further so its output can be checked, too!

```

**Comment by pzinn** [comment]
... and with this one:
```
DIV1 = withQname_"div" withOptions_{"class"=>"single"} new MarkUpType of HypertextContainer -- phase this one out!
```
once `DIV` has all its options, is there any reason to keep `DIV1 {...}` rather than writing `DIV{"class"=>"single",...}`? I don't think so.

**Comment by DanGrayson** [comment]
> i4 : new LI from 1 -- should probably reject but not with cryptic message
> stdio:4:1:(3): error: expected new class to be a specialization of the old one
> 
> i5 : LI 1 -- should probably reject but not with cryptic message
> stdio:5:1:(3): error: expected new class to be a specialization of the old one
> ```

Maybe the message should be "expected new class to be a specialization of the old one or to find a matching method for `NewFromMethod`".

**Comment by DanGrayson** [comment]
> TABLE {{1},{2,3},{4,5}}

On the other hand, there is the function `validate`:

```
i14 : validate TABLE {{1},{2,3},{4,5}}
stdio:14:1:(3): error: "{1}" is of an unrecognized type "List" with no qname, appearing in hypertext during validation

i15 : validate TABLE {TR {1}, TR {2,3}, TR {4,5}}
stdio:15:1:(3): error: "1" is of an unrecognized type "ZZ" with no qname, appearing in hypertext during validation

i16 : validate TABLE {TR {TD 1}, TR {TD 2,TD 3}, TR {TD 4,TD 5}}
stdio:16:21:(3): error: expected new class to be a specialization of the old one

i17 : validate TABLE {TR {TD "1"}, TR {TD "2",TD "3"}, TR {TD "4",TD "5"}}

o17 = 1 
      23
      45

o17 : TABLE

i18 : html TABLE {TR {TD "1"}, TR {TD "2",TD "3"}, TR {TD "4",TD "5"}}

o18 = <table><tr><td>1</td></tr>
      <tr><td>2</td><td>3</td></tr>
      <tr><td>4</td><td>5</td></tr>
      </table>
```

**Comment by pzinn** [comment]
> > TABLE {{1},{2,3},{4,5}}
> 
> On the other hand, there is the function `validate`:
> 
true but I still think that there should be (as the documentation suggests) a
`new TABLE from List := ...` which adds the appopriate `TR` and `TD` as needed (there is something like that for `UL`).

**Comment by DanGrayson** [comment]
Good idea.  It would also be good to make hypertext operators idempotent:
```
i21 : peek TR TR "asdf"

o21 = TR{TR{"asdf"}}

i22 : peek TR "asdf"

o22 = TR{"asdf"}
```

**Comment by DanGrayson** [comment]
... or would it?

**Comment by pzinn** [comment]
sure, that'd be another way of implementing it -- forcing the TR, TD, LI etc in their respective containers but making them idempotent. I'll give it a try.

**Comment by pzinn** [comment]
I changed my mind. Not all Hypertext types should be idempotent -- there are cases where it be necessary to have say `DIV DIV` and it would create hard-to-detect bugs. on the other hand, changing the code of only `TR`, `TD`, `LI` seems rather arbitrary. I'll just code `new TABLE from List` the same way as the current `new UL from List`.

**Comment by pzinn** [comment]
> > ```
> > i4 : new LI from 1 -- should probably reject but not with cryptic message
> > stdio:4:1:(3): error: expected new class to be a specialization of the old one
> > 
> > i5 : LI 1 -- should probably reject but not with cryptic message
> > stdio:5:1:(3): error: expected new class to be a specialization of the old one
> > ```
> 
> Maybe the message should be "expected new class to be a specialization of the old one or to find a matching method for `NewFromMethod`".

yeah, such a message does occur, say with
```
i14 : new LI from hashTable{}
stdio:14:1:(3): error: expected a list (in absence of a 'new' method)
```
anyway, back to my original point. I have this suspicion that these lines are incorrect:
```
new MarkUpType from Thing := (M,x) -> new M from {x}
new MarkUpType from List := (M,x) -> new M from x
new MarkUpType from Sequence := (M,x) -> new M from toList x
```
we never define any `MarkUpType` this way. Maybe what you really meant was have methods for `Hypertext`, not `MarkUpType`?

**Comment by DanGrayson** [comment]
That seems likely, why not try it out?  Except for the second line, which seems redundant.
