### ISSUE TITLE
minor: 'make check' for Flint: out of mem with default OS settings

### ISSUE THREAD

**Issue by jakobkroeker** [Macaulay2/M2#115]
Hello,

I observe that running tests for Flint with enabled garbage collector may run out of memory (at least on a) RedHat/Fedora system with moderate RAM (4-6GB) size using default OS disk swap settings.

The reason for this seems the fact that almost all memory is used by the OS to cache disk(?) IO (see output of 'free', column 'cached').
Even if I read somewhere in the web that the system releases
the cache f it is needed seems not true or the cache was released too late(?).

Solution:
For me it did work to adjust the swappiness setting (default value is 60) :

```
sudo sysctl vm.swappiness=25
```

and purge most of the cache cache:

```
 echo 3 | sudo tee /proc/sys/vm/drop_caches
```

Maybe this should be mentioned somewhere in the documentation / Wiki ?

**Comment by DanGrayson** [comment]
This issue seems stale, so I'm closing it.
