### ISSUE TITLE
fix elapsedTime

### ISSUE THREAD

**Issue by DanGrayson** [Macaulay2/M2#1156]
Maybe elapsedTime should refrain from printing after an interrupt:
```
Macaulay2, version 1.15.0.1
with packages: ConwayPolynomials, Elimination, IntegralClosure, InverseSystems, LLLBases, PrimaryDecomposition, ReesAlgebra, TangentCone, Truncations

i1 : elapsedTime while true do 1
  C-c C-cstdio:1:19:(3): error: interrupted
     -- 0.980661 seconds elapsed
```

**Comment by mahrud** [comment]
Why? Isn't it useful to know how much time was spent before you gave up on some computation?

**Comment by DanGrayson** [comment]
Right, you might want to know.  That's why I said "maybe".  

On the other hand, when you interrupt something, you may wish it to quietly stop so you can try something else.

I've never noticed this before, but I wonder whether users have and have grown to like the feature.
