### ISSUE TITLE
check "Macaulay2Doc" fails

### ISSUE THREAD

**Issue by d-torrance** [Macaulay2/M2#1157]
When trying to run the tests from the Macaulay2Doc package, the following error occurs:

```
Macaulay2, version 1.15
with packages: ConwayPolynomials, Elimination, IntegralClosure, InverseSystems,
               LLLBases, PrimaryDecomposition, ReesAlgebra, TangentCone,
               Truncations

i1 : check "Macaulay2Doc"
/usr/share/Macaulay2/Macaulay2Doc/doc13.m2:224:1:(2):[22]: error: couldn't find file /home/dan/src/M2/M2.git/M2/Macaulay2/d/startup.m2.in
```

This appears to be coming from the build directory, so perhaps this is related to #1149?

**Comment by DanGrayson** [comment]
I haven't seen that before, but perhaps we have a test that tries to display source code of a function that lies in that file.
```
i6 : code(symbol |, String, ZZ)
stdio:6:1:(3): error: couldn't find file /Users/dan/src/M2/M2/M2/Macaulay2/d/startup.m2.in
```

**Comment by d-torrance** [comment]
This issue goes away when I comment out the `SourceCode` option in the documentation of `applicationDirectory`:

https://github.com/Macaulay2/M2/blob/ea039800e10a6d8e4708312ebb5edac3fda88479/M2/Macaulay2/packages/Macaulay2Doc/doc13.m2#L224-L235

**Comment by DanGrayson** [comment]
That's it, then.  Thanks!

Fixed in commit 728c6321104d878fdc166faf751a20b6cdc9f801

**Comment by d-torrance** [comment]
I actually found the underlying bug that's causing the error!  The source code for the functions defined in `startup.m2.in` is available in `startupString`, but we were only actually looking there if `locate` returned `"layout.m2"`.  But apparently `layout.m2` hasn't existed since 2009! (fb2a04e)

I have a working patch:

```
i3 : code applicationDirectory

o3 = /home/dan/src/M2/M2.git/M2/Macaulay2/d/startup.m2.in:253:32-263:16: --source code:
          applicationDirectory = () -> (
               if getenv "HOME" =!= ""
               then (
                    getenv "HOME" | "/" |
                    -- we allow the user to change applicationDirectorySuffix to a string or a function
                    if instance(applicationDirectorySuffix, Function)
                    then applicationDirectorySuffix()
                    else applicationDirectorySuffix
                    )
               else error "environment variable HOME not set"
               );

```

I'll prepare a pull request with the fix.

**Comment by DanGrayson** [comment]
That will be a good fix, in addition!
