### ISSUE TITLE
feature request: build some parts in parallel

### ISSUE THREAD

**Issue by jakobkroeker** [Macaulay2/M2#116]
is it possible to build some parts in parallel,
e.g. 
- the documentation/package tests using 'GNU parallel' (or other tools?)
- Flint lib using 'make -j...' ? 

What has to be done?

**Comment by mahrud** [comment]
I think the CMake build accomplishes this, so it could be closed. Building libraries in parallel with autotools can be tracked in #1265 and single Makefile progress can be tracked in #26.
