### ISSUE TITLE
statuscodes no longer installed

### ISSUE THREAD

**Issue by d-torrance** [Macaulay2/M2#1162]
I was running some tests on the draft of the Debian package, based on the eigen branch, and got the following error:

```
/usr/share/Macaulay2/Core/gb.m2:4:12:(1):[7]: error: opening input file "/usr/share/Macaulay2/Core/statuscodes" failed: No such file or directory
/usr/share/Macaulay2/Core/setup.m2:113:27:(1):[6]: --back trace--
/usr/share/Macaulay2/Core/setup.m2:106:18:(1):[5]: --back trace--
/usr/share/Macaulay2/Core/setup.m2:126:41:(1):[4]: --back trace--
/usr/share/Macaulay2/Core/setup.m2:129:6:(1):[3]: --back trace--
/usr/share/Macaulay2/Core/setup.m2:147:1:(1):[2]: --back trace--
/build/macaulay2-1.14.0.1.780.g85cb3fc75/M2/Macaulay2/d/startup.m2.in:446:11:(0):[2]: --back trace--
/build/macaulay2-1.14.0.1.780.g85cb3fc75/M2/Macaulay2/d/startup.m2.in:620:14:(0):[1]: --back trace--
/build/macaulay2-1.14.0.1.780.g85cb3fc75/M2/Macaulay2/d/startup.m2.in:617:35:(0):[1]: --back trace--
```

This was the code that was running at the time:
```
skip = {"Macaulay2Doc"}
pkgs = separate_" " version#"packages"
scan(pkgs, pkg -> if not member(pkg, skip) then check pkg)
```
(I'm not sure which package it was checking at the time, and the chroot that was set up for the build has already been deleted...)

It looks like `statuscodes` was moved in 04192c0.

**Comment by DanGrayson** [comment]
@mahrud will probably understand this ...

**Comment by mahrud** [comment]
Can I make a PR to remove statuscodes altogether and just define the contents here?
https://github.com/Macaulay2/M2/blob/19872f1001ada8c15632cf13fa2b56aa9bf24b9d/M2/Macaulay2/e/engine.h#L1647-L1651
The only thing we need to worry about is keeping it in sync with `m2/statuscodes`, but these status codes haven't changes since [Apr 25, 2010](https://github.com/Macaulay2/M2/commits/release-1.15/M2/Macaulay2/e-includes/statuscodes), so with just a line of comment in engine.h and gb.m2, I think we're safe from them getting unsynced. Here is the only other place it is used:
https://github.com/Macaulay2/M2/blob/19872f1001ada8c15632cf13fa2b56aa9bf24b9d/M2/Macaulay2/m2/gb.m2#L3-L5

**Comment by DanGrayson** [comment]
Well, what if a change is made in the future?  Then a bug would result from not making corresponding changes to two files.  So it doesn't seem to be a good idea.

**Comment by mahrud** [comment]
There must be hundreds of changes that if made only in one of d, e, or m2 directories it would result in a bug, so I don't think that's a good argument. I think should just document it (even just with comments) and perhaps add tests.

**Comment by DanGrayson** [comment]
I think it's a good argument.

**Comment by mahrud** [comment]
Just add `statuscodes` to this line:
https://github.com/Macaulay2/M2/blob/e8b2e860a1638bf5d21a2e1bb0c09984eda0d6a6/M2/Macaulay2/m2/Makefile.in#L153
That should fix this.

**Comment by DanGrayson** [comment]
> Just add `statuscodes` to this line:
> https://github.com/Macaulay2/M2/blob/e8b2e860a1638bf5d21a2e1bb0c09984eda0d6a6/M2/Macaulay2/m2/Makefile.in#L153
> 
> 
> That should fix this.

That'll probably work.  I'll add it to the master branch and test it.

**Comment by DanGrayson** [comment]
I added that change suggested by Mahrud to the master branch.

**Comment by DanGrayson** [comment]
... and merged it into Anton's eigen branch.

**Comment by mahrud** [comment]
Is this fixed now?

**Comment by DanGrayson** [comment]
Yes, closing.
