### ISSUE TITLE
finding external programs

### ISSUE THREAD

**Issue by DanGrayson** [Macaulay2/M2#1165]
Ubuntu installs the programs of 4ti2 with the prefix "4ti2-" attached to their names.  Teach the package FourTiTwo how to find them there or under the non-prefixed name.

(Maybe test for the presence of "4ti2-markov" and "markov" on the PATH, and record the result for subsequent use.)

**Comment by d-torrance** [comment]
This is also the case for nauty and (once it enters Debian) topcom.  "nauty-" and "topcom-" prefixes, respectively.

**Comment by DanGrayson** [comment]
It's also the case for gfan and normaliz.

**Comment by DanGrayson** [comment]
Maybe we need a top-down change for the way all interface packages find their programs: look for the program on the PATH after looking in the internal M2 place.  Packages could implement that by having the shell modify the PATH first when they try to run the external program, putting the internal M2 place at the start.  We could make that easier by having a core M2 function that does that simple thing.

**Comment by mikestillman** [comment]
I think this is a very good idea.  At the moment, everyone has to discover what to do (e.g. by looking at one of the current interface packages), and the resulting interfaces are inconsistent.

However, a version on the system can either be too old (and so we don't want to use it), or newer (perhaps fixing bugs in the distributed version).  We should allow the user to select somehow between the system version, and the M2-distributed version.

**Comment by mikestillman** [comment]
@DanGrayson here is the sort of warning I am receiving now, while compiling the e directory.  Either we need to quiet this one warning down, or (perhaps better): `scc` should define this as a class?  Actually, I'm not sure how to fix this, as currently, `engine-exports.h` needs to work with both C and C++.  Perhaps have `scc` place an ifdef for c++?  Or perhaps have these types included from one .h file?

```
CXX x-ringmap.cpp
In file included from ../../../../../../Macaulay2/e/x-ringmap.cpp:1:
../../../../../../Macaulay2/e/engine.h:14:1: warning: class 'Monomial' was previously declared as a struct [-Wmismatched-tags]
class Monomial;
^
../d/engine-exports.h:106:22: note: previous use is here
typedef const struct Monomial * engine_RawMonomial;
                     ^
In file included from ../../../../../../Macaulay2/e/x-ringmap.cpp:1:
../../../../../../Macaulay2/e/engine.h:15:1: warning: class 'Monoid' was previously declared as a struct [-Wmismatched-tags]
class Monoid;
^
../d/engine-exports.h:111:22: note: previous use is here
typedef const struct Monoid * engine_RawMonoid;
                     ^
In file included from ../../../../../../Macaulay2/e/x-ringmap.cpp:1:
../../../../../../Macaulay2/e/engine.h:16:1: warning: class 'Ring' was previously declared as a struct [-Wmismatched-tags]
class Ring;
^
../d/engine-exports.h:113:22: note: previous use is here
typedef const struct Ring * engine_RawRing;
```

**Comment by DanGrayson** [comment]
> I think this is a very good idea. At the moment, everyone has to discover what to do (e.g. by looking at one of the current interface packages), and the resulting interfaces are inconsistent.
> 
> However, a version on the system can either be too old (and so we don't want to use it), or newer (perhaps fixing bugs in the distributed version). We should allow the user to select somehow between the system version, and the M2-distributed version.

The selection could be made by setting a package configuration value.

**Comment by DanGrayson** [comment]
Maybe it should be an option to newPackage:
```
     ExternalPrograms => { "walk", "ppi", "zbasis", ... }
```
That would result in a configuration option or two being added: whether to look first internally or externally; a prefix for the names; a suffix for the names; a directory to find them in.

**Comment by DanGrayson** [comment]
There would also have to be some way for a downstream builder of a distribution, such as for Debian, to specify the information, so the user doesn't have to futz with configuration.

**Comment by DanGrayson** [comment]
@d-torrance -- are we encountering, under Ubuntu, some of the other packages you maintain?

**Comment by d-torrance** [comment]
Yes.  Pretty much all of the math software in Debian is co-maintained by members of the Debian Science Team, which I'm a member of.  I don't think I've worked on 4ti2 specifically, but I've done a bunch of work on some of the others like gfan and cohomcalg.

**Comment by DanGrayson** [comment]
Is there a website where we can view the team's packages and proposed packages (in math)?

**Comment by d-torrance** [comment]
Yes!
https://blends.debian.org/science/tasks/mathematics
https://blends.debian.org/science/tasks/mathematics-dev

Most of these are maintained in git:
https://salsa.debian.org/science-team

**Comment by d-torrance** [comment]
Currently, I'm just patching the packages themselves to deal with configuration.  For example, [for 4ti2](https://salsa.debian.org/science-team/macaulay2/-/blob/master/debian/patches/use_debian_4ti2.patch):

```
--- a/M2/Macaulay2/packages/FourTiTwo.m2
+++ b/M2/Macaulay2/packages/FourTiTwo.m2
@@ -24,7 +24,7 @@
 	     {Name => "Sonja Petrovic", Email => "petrovic@psu.edu"}
 	     },
     	Headline => "Interface to 4ti2",
-	Configuration => { "path" => "",
+	Configuration => { "path" => "/usr/bin/4ti2-",
 	     "keep files" => true
 	      },
     	DebuggingMode => false
```

**Comment by DanGrayson** [comment]
Ah, that's simple enough, but it might cause conflicts later on as code changes.  Still, resolving such conflicts is rather quick.

**Comment by DanGrayson** [comment]
> Maybe we need a top-down change for the way all interface packages find their programs: look for the program on the PATH after looking in the internal M2 place. Packages could implement that by having the shell modify the PATH first when they try to run the external program, putting the internal M2 place at the start. We could make that easier by having a core M2 function that does that simple thing.

In addition, we could have a subdirectory of the user's application directory on the PATH (if `-q` is not on the command line), which is in front of the standard internal M2 directory for programs.  This would allow users to experiment with more recent versions by putting programs there, but would still allow us to help users debug things (by telling them to add `-q` to the command line).

**Comment by DanGrayson** [comment]
We also need a way to search along the PATH for the first occurrence of a program whose name matches one of several, such as "4ti2-markov" and "markov" .

**Comment by mahrud** [comment]
Ref: #1368

**Comment by d-torrance** [comment]
With the merging of #1513, I think we can close this issue.
