### ISSUE TITLE
Remove tag from Debian git?

### ISSUE THREAD

**Issue by d-torrance** [Macaulay2/M2#1189]
A few days ago, I pushed the tag `upstream/1.14.0.1.786.g30c2485c7` to the [Debian git repository](https://salsa.debian.org/science-team/macaulay2) to do some testing.  It looks like it got pushed to the main repository.  I'm not sure if it should be there, because now it shows up as a [release](https://github.com/Macaulay2/M2/releases).  I've actually removed it in the Debian repository and will wait until an official release to start pushing any more tags there.

**Comment by DanGrayson** [comment]
I was wondering where that came from!  I wonder if a tag can be part of a pull request ...

**Comment by d-torrance** [comment]
Looks like you got it!  I'll go ahead and close this issue.
