### ISSUE TITLE
debian and frobby

### ISSUE THREAD

**Issue by DanGrayson** [Macaulay2/M2#1200]
Roune has no time to develop frobby further, and there is at least one change we want to make to it (making the version number available).  How do we get debian to recognize us as "upstream" for their purposes?

@d-torrance

**Comment by d-torrance** [comment]
That's easy because I'm the maintainer of frobby in Debian.  :)

I'll use the M2 frobby repo for all my future packaging work.

**Comment by DanGrayson** [comment]
What patches are you currently applying?  It turns out the patches we were applying were needed and many.

**Comment by DanGrayson** [comment]
... as I have just confirmed by trying to compile v0.9.0 with no patches.

**Comment by d-torrance** [comment]
Quite a few!

https://salsa.debian.org/science-team/frobby/-/tree/master/debian/patches

**Comment by DanGrayson** [comment]
Thanks!  I've made branch there for your patches.  Now we have 3 patch branches competing with each other.
