### ISSUE TITLE
Automate building new language grammars

### ISSUE THREAD

**Issue by mahrud** [Macaulay2/M2#1210]
The PR to [add Macaulay2 highlighting to Linguist](https://github.com/github/linguist/pull/4844) has been merged, but Linguist needs to make a release before it goes into effect. That should be soon, but ideally we should update the [language grammar](https://github.com/Macaulay2/language-macaulay2/blob/master/grammars/macaulay2.cson) to include recent changes before then.

_Originally posted by @mahrud in https://github.com/Macaulay2/M2/pull/1190/files_

**Comment by mahrud** [comment]
Linguist made a new release last night, but I updated the grammar manually before that. Here is a demo of the syntax highlighting:
https://github.com/Macaulay2/M2/blob/93582031d79af22bb6605b63d33da0a1b6479c48/M2/Macaulay2/m2/schubert.m2#L56-L61

Also, language analysis for the repository before the change:
![2020-06-17-043027_1231x120_scrot](https://user-images.githubusercontent.com/3147718/84923637-10fb3f80-b08d-11ea-81b0-1c65f9a3f141.png)
versus now:
![2020-06-17-111352_1229x117_scrot](https://user-images.githubusercontent.com/3147718/84923655-16f12080-b08d-11ea-83d8-f15a270cea56.png)

**Comment by DanGrayson** [comment]
Great!

**Comment by mikestillman** [comment]
Yes, very nice!

**Comment by radoslavraynov** [comment]
Is the M2 color an approximation of the M2 webpage background?
