### ISSUE TITLE
toString vs net Type inconsistency

### ISSUE THREAD

**Issue by pzinn** [Macaulay2/M2#1218]
another minor issue (and easily fixable), but it's the season for bug fixing...
compare the two codes below. there are slight differences (besides the normal `toString`/`net` differences): `toString` shows `parent X`, whereas `net` doesn't; `net` has this extra `if #X > 0` test. I think they should be uniformized. (in which case, should `parent X` be shown? I'd say yes).

```
i1 : code(toString,Type)

o1 = -- code for method: toString(Type)
     /usr/share/Macaulay2/Core/nets.m2:28:20-33:81: --source code:
     toString Type := X -> (
          if hasAnAttribute X then (
               if hasAttribute(X,PrintNames) then return getAttribute(X,PrintNames);
               if hasAttribute(X,ReverseDictionary) then return toString getAttribute(X,ReverseDictionary);
               );
          concatenate(toString class X, " of ", toString parent X, "{...", toString(#X), "...}"))

i2 : code(net,Type)

o2 = -- code for method: net(Type)
     /usr/share/Macaulay2/Core/nets.m2:213:15-219:70: --source code:
     net Type := X -> (
          if hasAnAttribute X then (
               if hasAttribute(X,PrintNet) then return getAttribute(X,PrintNet);
               if hasAttribute(X,PrintNames) then return net getAttribute(X,PrintNames);
               if hasAttribute(X,ReverseDictionary) then return toString getAttribute(X,ReverseDictionary);
               );
          horizontalJoin ( net class X, if #X > 0 then ("{...", toString(#X), "...}") else "{}" ))
```

**Comment by pzinn** [comment]
also, there's no `texMath Type` (it uses `texMath HashTable` which again has a similar but subtly different output than the above)

**Comment by pzinn** [comment]
might want to add a `texMath Type` too if showing `parent X`

**Comment by DanGrayson** [comment]
Sounds good to me!

**Comment by pzinn** [comment]
just to remember what the issue when the time comes to fix it:
currently both the `net` and `toString` output are ugly:
```
i1 : new Type of List

o1 = Type{}

o1 : Type

i2 : toString oo

o2 = Type of List{...0...}
```
Probably something in between, like `Type of List`, would be preferrable.
