### ISSUE TITLE
missing config file?

### ISSUE THREAD

**Issue by wjb19** [Macaulay2/M2#122]
Hi Folks;
Went to run configure, got most the way through the process, and encountered this guy: 

config.status: error: cannot find input file: include/M2/config.h.in

system details:

[install@biostar M2]$ uname -a
Linux biostar.psu.edu 2.6.32-431.3.1.el6.x86_64 #1 SMP Fri Dec 13 06:58:20 EST 2013 x86_64 x86_64 x86_64 GNU/Linux

[install@biostar M2]$ autoconf --version
autoconf (GNU Autoconf) 2.63
Copyright (C) 2008 Free Software Foundation, Inc.
License GPLv2+: GNU GPL version 2 or later
http://gnu.org/licenses/old-licenses/gpl-2.0.html
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by David J. MacKenzie and Akim Demaille.

thanks for your assistance! -bill brouwer

**Comment by MisesEnForce** [comment]
What do you mean by "know to RTM" ? (Because I have the same issue than yours....) Thx !

**Comment by DanGrayson** [comment]
RTM = read the manual

**Comment by DanGrayson** [comment]
... in this case, the INSTALL file, I'm guessing.
