### ISSUE TITLE
improve package and simpledoc documentation

### ISSUE THREAD

**Issue by mikestillman** [Macaulay2/M2#1220]
The documentation for packages, and the SimpleDoc format could be improved.  I will edit this list with suggestions, things done, etc.  Help would be welcome!

Here are some of the doc nodes for packages and documentation, and sometimes a few suggestions for things that should be changed.  Perhaps these nodes should even be consolidated somehow.

* The node and package `SimpleDoc`
  - Have a getting started node, where one sees the basic use of SimpleDoc.
  - Have a node (currently the `doc` node) that describes the general format, and also how to do some common things (e.g. having a list of items, adding a URL link).
  - How to write math in a doc node
* The node `Package`
  - make sure `SimpleDoc` is linked to!
  - Similarly, `packageTemplate` should be visible from here
  - `packageTemplate` should include the `end--` near the end of the file.
* The node `packages`
* The node `creating a package`
* The node `an example of a package`
  - should link to `packageTemplate` (in `SimpleDoc`)
  - Perhaps use `doc` rather than `multidoc` for doc here
* Node `informing others about your package`
  - Seems out of date.
* The node `writing documentation`
  -- Doesn't even mention `SimpleDoc`, or `docTemplate`.  It should be based on `SimpleDoc` I think.
* The node `conventions for documentation`
  -- Also out of date.

**Comment by mahrud** [comment]
Do all of the above need to be documentation nodes written within Macaulay2? I'm wondering if using a more expressive format would make more sense.

**Comment by mikestillman** [comment]
@mahrud : What do you have in mind?

**Comment by mahrud** [comment]
Nothing specific, other than maybe unifying all the nodes you mentioned into one that is linked on the front page. I was just looking around, and it seems common to have separate formats for _manuals_ (e.g. setup M2 with emacs, start a package, tutorials, etc.), language _reference_, and package _documentation_. It's not the same everywhere, of course. Here are a few examples from [Go](https://www.golang-book.com/books/intro/11), [Julia](https://julialang.github.io/Pkg.jl/v1/creating-packages/), [Rust](https://doc.rust-lang.org/cargo/guide/creating-a-new-project.html), and [GAP](https://www.gap-system.org/Manuals/pkg/example/doc/chapA.html).

**Comment by DanGrayson** [comment]
`TO document` should work, but `(document,List)` is undocumented.

**Comment by mahrud** [comment]
What about `writing documentation`?

**Comment by DanGrayson** [comment]
For that, use `TO "writing documentation"`

Actually, I was wrong: `TO (document,List)` and `TO document` would point to the same node.

**Comment by mahrud** [comment]
Among the three, only `TO document` seems to be working within package
documentation.

**Comment by DanGrayson** [comment]
Can you point me to an instance of the two not working?

**Comment by mahrud** [comment]
Well, `writing documentation` is never linked to outside of it's parent section! Try checking out and installing from my SimpleDoc PR #1234 and looking at the top node:
> **writing documentation (missing documentation)**

Alternatively, see this part of [simpleDocFrob](https://faculty.math.illinois.edu/Macaulay2/doc/Macaulay2-1.15/share/doc/Macaulay2/SimpleDoc/html/_simple__Doc__Frob_lp__Z__Z_cm__Matrix_rp.html) on the official documentation page:
> Each paragraph of text begins with "Text". The following line starts a sequence of Macaulay2 example input lines. However, see **matrix(List) (missing documentation).**

Or at the bottom:
> **directSum(List) (missing documentation)** -- direct sum of modules or maps

**Comment by mahrud** [comment]
Do we still want people to use the `document List` function going forward, or should it be phased out? For instance, should ["overview documentation template
"](https://faculty.math.illinois.edu/Macaulay2/doc/Macaulay2-1.12/share/doc/Macaulay2/Macaulay2Doc/html/_overview_spdocumentation_sptemplate.html) be deleted?

**Comment by DanGrayson** [comment]
No, let people choose what they want.

I still think multidoc and doc should be merged, by the way.

**Comment by mahrud** [comment]
@mikestillman I'll close this as fixed in the PR above. If you have any other suggestions or anything is amiss, please reopen.
