### ISSUE TITLE
improve `hooks` mechanism

### ISSUE THREAD

**Issue by mikestillman** [Macaulay2/M2#1225]
Hooks are a useful way to choose algorithms or specific functions to run.

There are some improvements that should be made though:
* Improve the documentation.  There should be a doc node that explains how to do this
* Need a function to get the list of hook functions, and be able to locate their code.
* Perhaps change `(break result)` to just return something non-null instead.
* How to find which functions/methods allow hooks.

**Comment by mahrud** [comment]
Related: #1153, shall we merge this there?

**Comment by mikestillman** [comment]
Yes, let's do that.
