### ISSUE TITLE
epkg link broken

### ISSUE THREAD

**Issue by d-torrance** [Macaulay2/M2#1235]
There's a documentation page for [epkg](https://faculty.math.illinois.edu/Macaulay2/doc/Macaulay2-1.15/share/doc/Macaulay2/Macaulay2Doc/html/_epkg.html) linked from the one for [installPackage](https://faculty.math.illinois.edu/Macaulay2/doc/Macaulay2-1.15/share/doc/Macaulay2/Macaulay2Doc/html/_install__Package.html).  It's also mentioned in `INSTALL`:

https://github.com/Macaulay2/M2/blob/99b7b7e918e9c79dae00b6827284cb77fc7e5bbd/M2/INSTALL#L312-L315

However, the link (http://www.encap.org/epkg/) is broken.  Is this software still relevant?  If so, what should the link be?  The only place I could find it after a quick google search is [Dan's Github repository](https://github.com/DanGrayson/epkg).  Or should references to it be removed?

**Comment by DanGrayson** [comment]
Let's redirect the link to my github repository, where I saved the code.  I still use it, and others might find it useful.

**Comment by DanGrayson** [comment]
It might also be good to add an option to the code in `M2/Macaulay2/html-check-links/` that tells it to verify external links still work.  Currently it just checks for broken internal links.
