### ISSUE TITLE
document `exportFrom`.  Should we also have an `importFrom`?

### ISSUE THREAD

**Issue by mikestillman** [Macaulay2/M2#1236]
I have just found a method in the Core I didn't realize existed: `exportFrom`.  It is used in 4 packages, basically allowing a package to export symbols from `Core` or another package, without doing e.g. `debug Core`.

* Perhaps add a function `importFrom_Core "name"`, `(importFrom, Package, String)`, which would allow a package to bring in low level routines in the Core,  but would not export it.
* Document both of these functions

@DanGrayson , what do you think?

**Comment by DanGrayson** [comment]
Here's a better way, perhaps.  Let's get rid of `exportFrom`, which combines two operations.  Let's allow `export` to accept a symbol, even one from another package, and let's make a function that can get a symbol from another package and call it `getPrivateSymbol`.  Then you could do this:
```
foo := getPrivateSymbol(Foo, "foo")
export foo
```

**Comment by mahrud** [comment]
I like `import` better than `getPrivateSymbol`. Reminds me of
```python
from foo import bar1, bar2
from foo import *
from foo import bar3 as barber
```
in Python ([documentation](https://docs.python.org/3/tutorial/modules.html#more-on-modules)) and
```javascript
import bar from "foo"
import * from "foo"
import { bar1, bar2 } from "path/to/foo"
```
in JavaScript ([documentation](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import#Description)).

**Comment by mahrud** [comment]
I wrote a basic implementation of this, but would like to keep this open to implement a more advanced version that would work with namespaces as in #1184.

**Comment by mahrud** [comment]
I'll close this, but mention the suggestion above in that issue.
