### ISSUE TITLE
upgrade flint to 2.6.0

### ISSUE THREAD

**Issue by DanGrayson** [Macaulay2/M2#1242]
... and arrange for `configure` to detect it and use it, if it's already installed.

**Comment by mahrud** [comment]
See: https://github.com/Macaulay2/flint2/pull/3

**Comment by mahrud** [comment]
Shall we also use submodules for flint? I would do it, but I'm not sure how to enforce dependencies between libraries that are submodules and those that are not. The CMake build does this in one line:
https://github.com/Macaulay2/M2/blob/6da6a66ecfd54bbf8dfb758ba459a5e6e7aad237/M2/cmake/build-libraries.cmake#L375

Which calls the following function:
https://github.com/Macaulay2/M2/blob/6da6a66ecfd54bbf8dfb758ba459a5e6e7aad237/M2/cmake/build-libraries.cmake#L96-L108

There are two components: libraries and programs, which have targets `build-libraries` and `build-programs`. The command above adds a dependency on `build-flint` if `FLINT_FOUND` is false. Further, it imposes dependencies on `build-mp` (gmp or mpir), `build-mpfr`, and `build-ntl`.

**Comment by DanGrayson** [comment]
Yes, let's go ahead with that now.

I'll have to review GNUmakefile.in to see what's what -- I don't remember.  It probably needs improvement.  You can handle the cmake side.  I see you've already updated the "flint2" submodule.

**Comment by mahrud** [comment]
The CMake side is done.

**Comment by mahrud** [comment]
Is this closed by #1280?
