### ISSUE TITLE
Endomorphisms

### ISSUE THREAD

**Issue by mikestillman** [Macaulay2/M2#1252]
Make `End` into a method, with Options=>true.

Currently, it is defined in `m2/modules2.m2` as `End = (M) -> Hom(M,M)`

**Comment by pepperhdj** [comment]
What's the point of having options on End? Hom doesn't take any options. Should Hom take options too?

**Comment by mahrud** [comment]
I think an option for the category would be useful; e.g. endomorphisms of R=kk[x]/x^2 over R vs. over kk. If the object is graded, homomorphisms of a certain degree might also be useful, because I don't think Hom currently carries the degree information.
