### ISSUE TITLE
canned examples

### ISSUE THREAD

**Issue by DanGrayson** [Macaulay2/M2#1258]
There should be a way to generate canned examples, which duplicates the internal method for making examples in documentation, namely this:
```
document {
     Key => "foo",
     TABLE splice { "class" => "examples", 
	  TR TD PRE ///
i1 : loadPackage "Foo"

o1 = Foo

o1 : Package///,
	  TR TD PRE ///
i2 : viewHelp oo
///
}}
```
The point is to get those nice lines between the individual input/output triples, as in 
<img width="396" alt="Screen Shot 2020-06-10 at 1 43 43 PM" src="https://user-images.githubusercontent.com/700228/84301475-772a1480-ab19-11ea-9d94-534091b9f03c.png">

**Comment by mahrud** [comment]
Try:
```m2
importFrom_Core {"separateM2output"}
beginDocumentation()
s = "\ni1 : 4 * 4\n\no1 = 16\n\ni2 : 12 + 16;\n\ni3 : 11\n\no3 = 11\n\ni4 : \n"
document { Key => "foo", TABLE{"class" => "examples", TR \\ TD \ PRE \ separateM2output s} };
help foo
```
Maybe separateM2output would need to be renamed into something and exported, but this doesn't seem like a common enough occurrence to make it worth that.

Perhaps this should also be added here:
https://github.com/Macaulay2/M2/blob/1e47260755100936bafd60d64013672dedd3941f/M2/Macaulay2/packages/SimpleDoc.m2#L246-L248
