### ISSUE TITLE
Cannot find source file: rand.c

### ISSUE THREAD

**Issue by yurivict** [Macaulay2/M2#1259]
```
-- Detecting CXX compile features - done
-- Configuring done
CMake Error at Macaulay2/e/CMakeLists.txt:1 (add_library):
  Cannot find source file:

    rand.c

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
  .hpp .hxx .in .txx
```

FreeBSD 12.1
clang-9
Version: 1.15.1.0

**Comment by mahrud** [comment]
@yurivict did the autotools build work for you? None of our sources need `rand.c`, so I'm not sure where this is coming from.

**Comment by yurivict** [comment]
> None of our sources need rand.c, so I'm not sure where this is coming from.

It's listed in one of CMakeLists.txt files.

**Comment by mahrud** [comment]
Which one? I can't find it in any.

**Comment by mahrud** [comment]
@yurivict I think your repository is too old. Older than when the cmake branch was merged. Pull the latest changes from either master or development branch and try again. Refer to [INSTALL-CMake.md](https://github.com/Macaulay2/M2/blob/master/M2/INSTALL-CMake.md) for more details.

**Comment by yurivict** [comment]
```M2/Macaulay2/e/CMakeLists.txt``` has rand.c:

![image](https://user-images.githubusercontent.com/271906/84398220-89a55c00-abb4-11ea-8ed4-fe3f145984e1.png)

**Comment by mahrud** [comment]
@yurivict That's not the version in the repository:
https://github.com/Macaulay2/M2/blob/3ebd5e7d684a91b99a2af0b2927a969e996120ad/M2/Macaulay2/e/CMakeLists.txt#L30-L32

I'm guessing you downloaded the 1.15.1.0 zip file from the releases tab, which is only three weeks old but is missed 4 months worth of change in the CMake builds :)

@DanGrayson could you make a new release?

**Comment by mikestillman** [comment]
I believe, even though we haven't yet announced it, that the next release will be created at the end of the month.  Dan and I haven't talked about it yet though, so I'm not sure that is completely correct.

**Comment by mahrud** [comment]
I was just suggesting a new github tag `release-1.15.2.0` (or even 15.1.1) in the meantime, so people who download the latest zipped archive from the [releases](https://github.com/Macaulay2/M2/releases) tab aren't surprised when CMake doesn't work.

However, I just realized that this would still not work, since submodules aren't included in zipped archives. So @yurivict, you should follow the steps in INSTALL-CMake.md to clone the git repository and build from that.

And please let me know whether you succeed or run into any other issues, I'm quite curious to know if things work well on FreeBSD.

**Comment by DanGrayson** [comment]
I wish there were a way to get rid of all the releases on the releases tab -- that would avoid possible confusion.

**Comment by yurivict** [comment]
You can delete releases.

Using a git utility, delete the tag and push it to GitHub.

**Comment by DanGrayson** [comment]
I like the tags, though.

**Comment by mahrud** [comment]
@yurivict did you run into any other issues building M2 on freebsd?

**Comment by yurivict** [comment]
The next issue is: https://github.com/Macaulay2/M2/issues/1274

**Comment by mahrud** [comment]
Okay, I'll close this one then!
