### ISSUE TITLE
action - get config.log

### ISSUE THREAD

**Issue by DanGrayson** [Macaulay2/M2#1272]
It would be great if we could get a copy of `config.log` from a build by github actions, especially if the build fails during the configuration stage.

@radoslavraynov

**Comment by radoslavraynov** [comment]
I'll bundle it together with the conditional (and may be some other things) and submit a PR.

**Comment by DanGrayson** [comment]
I figured out the problem with tgoto, by the way!

**Comment by DanGrayson** [comment]
We have one build failing now, in part because a boost file is not found, even though boost is installed with homebrew.  So seeing config.log might explain exactly why.

**Comment by DanGrayson** [comment]
... https://github.com/Macaulay2/M2/runs/774035860?check_suite_focus=true#step:11:22547

**Comment by mahrud** [comment]
`CMakeFiles/CMakeOutput.log` and `CMakeFiles/CMakeError.log` would be useful as well.
