### ISSUE TITLE
boost library installation -- autotools

### ISSUE THREAD

**Issue by DanGrayson** [Macaulay2/M2#1283]
We install the boost library incorrectly when it's not present on the system.  The files should go into a subdirectory `usr-host/include/boost`.

And since there are so many of them, instead of putting them there, it would be good to add a `-I` option to the CC command line.

(Boost is 1.32GB !  Isn't that excessive?  Is it worth it? )

**Comment by mahrud** [comment]
You can always say it's a requirement. Any reasonable system with a C++ compiler has Boost packaged. Same with OpenBLAS.

**Comment by mikestillman** [comment]
I'd be happy to place Boost as a system prereq: brew has it, and probably all linux and freebsd do too, even windows?  There is no need to compile it ourselves.  Unless, we are using versions which don't match the installed versions.  But that is probably not too likely.

**Comment by DanGrayson** [comment]
Okay, let's do that.
