### ISSUE TITLE
Switch to KaTeX for rendering math in documentation

### ISSUE THREAD

**Issue by mahrud** [Macaulay2/M2#1288]
[KaTeX](https://katex.org/) is a javascript library for rendering math. We could use it two ways:
- load the javascript library in html files and let the browser handle it.
- use server side rendering, which would mean adding a dependency on Node.js.

I think the first option is probably best.

With this change, I think we should also remove the `TEX` type (or make it idempotent) and delete `m2/texhtml.m2` and other `TEX` related methods.

**Comment by mahrud** [comment]
Related: #522, #706, #856, #981.

**Comment by pzinn** [comment]
there is a lot of similarity with what I do for the web app. it''s tempting to use the same command `htmlWithTex` or at least something analogous. we can discuss this.

**Comment by mahrud** [comment]
Yes, I noticed you use that in the webapp. However, I think we need to change `html TEX` in order to improve the online documentation.

**Comment by mahrud** [comment]
@DanGrayson do you think there's any reason to keep `texhtml.m2` around if there's a better way of presenting math in the browser that doesn't require maintenance?

**Comment by DanGrayson** [comment]
> @DanGrayson do you think there's any reason to keep `texhtml.m2` around if there's a better way of presenting math in the browser that doesn't require maintenance?

The file would remain, but it would shrink from 200 lines to 5, because the body of the method for `html TEX` would convert tex to html by passing the tex through the katex renderer.

**Comment by mahrud** [comment]
> The file would remain, but it would shrink from 200 lines to 5, because the body of the method for `html TEX` would convert tex to html by passing the tex through the katex renderer.

Sure, I guess if it's just 5 lines it might as well move to `html.m2`. Also, assuming we use client-side rendering, the output would just be `$ ... $` and in the html we would include a katex.js library. Server-side rendering would be a hassle, especially since we would need Node.js installed.

**Comment by DanGrayson** [comment]
Not so much of a hassle, since we already install, or have the builder install, umpteen dozen other libraries.  Isn't Node.js universally available?  It's better for us to encounter the error messages than the user, so running katex at build-time might be the way to go.  (I wouldn't use the phrase "server side" to describe that.)

**Comment by mahrud** [comment]
Node.js is easily available, but installing the katex package (and its requirements, and whether they need to be installed locally or globally, and whether the user has permission, and whether they're found on the path, etc. ...) is much, much more of a hassle. Why would the user encounter any errors?

**Comment by DanGrayson** [comment]
Apparently all it takes to install katex is `npm install katex`.

Imagine a user who wants to post the documentation for their package on their own web site: do you want that user to have to figure out where to put the javascript code for katex, too?  I don't.

**Comment by mahrud** [comment]
Dan, I don't need to imagne: I am a user who wants to post the
documentation on my page :)
And I do what katex.org recommends, which is load the javascript code from
jsdeliver.net: https://katex.org/docs/browser.html

We can add an option for prerendering the latex if you'd like, but that's
not my first priority, so I'll happen later.

**Comment by DanGrayson** [comment]
If you load the katex javascript code from jsdeliver.net at browsing time, then the user can't be offline when viewing the documentation.  That won't be acceptable.

**Comment by mahrud** [comment]
Okay then put it in the Style package or something! The users don't need to
figure out where to put those files because the system takes care of them.
I'm sure you could have thought of this solution, so why are you being
nitpicky, Dan?

**Comment by DanGrayson** [comment]
> Okay then put it in the Style package or something! The users don't need to figure out where to put those files because the system takes care of them.

That's true, but then the same html files can't be posted on the user's webpage, because the links to those files will be broken.  I think we want the html files to work both locally (offline) and on the user's home page.

Here's a possible solution: put the required javascript also in the Style package, as you suggest, but the first time the user installs a package somewhere, install also the Style package there, if it's not already installed there.  It would be an installation prerequisite.  And then ensure that the links to the javascript and the css go to that copy of the Style package, rather than to the system's copy, and ensure that the links are relative and short, not absolute.  Then, when the user wants to post the html on a webpage, he copies the contents of `local/share/doc/Macaulay2/Foo` and `local/share/doc/Macaulay2/Style`.

> I'm sure you could have thought of this solution, so why are you being nitpicky, Dan? You asked what a user who wants this for their **website** should do, and I said they should use jsdeliver. Websites aren't accessible offline, and I never suggested to do that for the documentation! You can at the very least wait until there's a working example in front of you before throwing stones at the idea!

No, it's better to plan ahead, jointly, before writing code.  And writing code is nitpicky, so the planning has to be nitpicky, too.

And you did suggest doing it for the documentation, as the function in texhtml.m2 is used to make the documentation.

**Comment by mahrud** [comment]
> And you did suggest doing it for the documentation, as the function in texhtml.m2 is used to make the documentation.

"html TEX" does not insert the lines that load katex.js into html.

@pzinn how do you use katex in your webapp?

**Comment by mahrud** [comment]
Here is another issue with `TEX` from [changes, v1.16](https://faculty.math.illinois.edu/Macaulay2/doc/Macaulay2/share/doc/Macaulay2/Macaulay2Doc/html/_changes_cm_sp1.16.html):
![image](https://user-images.githubusercontent.com/3147718/90988145-39545e00-e556-11ea-826c-6285bc8172b3.png)

The problem is that M2 has 2 different markup syntaxes that don't intermix well; in this case putting a `TO` element inside `TEX` doesn't work. Similarly, since net and info don't render LaTeX, we end up with documentation nodes that are broken in either format. This is from the top page of VirtualResolutions viewed with help:
```m2
     As a running example, consider three points $([1:1],[1:4])$,
     $([1:2],[1:5])$, and $([1:3],[1:6])$ in $\mathbb{P}^1 \times \mathbb{P}^1$.
```

I'm not sure what's the best thing to do, but here's a suggestion in three steps:
- deprecate TEX, and make browsers render math with KaTeX
- replace non-math LaTeX in documentation, such as `{\bf ...}`, with `BOLD`, etc.
- optionally: make M2 render math inside `$...$` and other delimiters, though it might be okay to make people just read LaTeX.

**Comment by pzinn** [comment]
First, just to clarify, my use of KaTeX is a little bit different then the one you're discussing now for the documentation. For me the goal is to typeset Macaulay2 expressions (typically, by invoking `texMath`), whereas for you the TeX content is provided as is. The latter is in principle simpler: all you have to do is insert the TeX as is in the HTML document and then invoke KaTeX  -- of course that means the document must somewhere load the KaTeX script; this must be done in the <head> somewhere, so not together with the actual TeX content. That shouldn't be a problem: it doesn't hurt to have KaTeX loaded no matter what -- it's pretty small.

**Comment by pzinn** [comment]
Also, in the web interface I call KaTeX on the fly, but there's a simpler option for static content which is to use KaTeX's extension autorender.js which automatically converts all the (La)TeX on the page once it's loaded.

**Comment by mahrud** [comment]
> Also, in the web interface I invoke KaTeX on the fly, but there's a simpler option for static content which is to use KaTeX's extension autorender.js which automatically converts all the (La)TeX on the page once it's loaded.

The pull request I made it actually pretty trivial. It adds the js and css files to the Style package and loads them in the header, along with the auto-render extension. However, as far as I can tell KaTeX only renders math, not full TeX. This is the main problem at the moment.

**Comment by pzinn** [comment]
Ah, yes, that's another important difference, KaTeX only deals with math TeX, which makes sense because non-math stuff can be rendered equally well in normal HTML. Overall, I agree with your 3-step solution.

**Comment by mahrud** [comment]
Actually, disregard what I said about disallowing TeX like `{\tt ..}`, and I just realized that using the new regex flavor it's super easy to parse it into our own Hypertext types. The key part is regex being able to detect matching brackets, which it now can.

**Comment by mahrud** [comment]
@pzinn is htmlWithTex still necessary?

**Comment by pzinn** [comment]
I still think `htmlWithTex' does something different, see my comment above. I'll look into your code in a bit, though.

**Comment by mahrud** [comment]
I see that there are differences, but I'm wondering if they can be folded into html (e.g. the before and after prints). Some methods of html need to go away as well, like (html, Matrix) ...

**Comment by pzinn** [comment]
As I mentioned during my talk, we're in disagreement here. I think html should be applicable to any type and produce html output, you don't...

**Comment by mahrud** [comment]
Maybe I'll make a new issue about this instead.

**Comment by mahrud** [comment]
Uhh, no, we're not! I'm essentially saying html should be replaced with htmlWithTex!!
Currently this is what (html, Matrix) does:
```m2
i1 : html random(ZZ^3,ZZ^3)

o1 = <table>
       <tr>
         <td>
     9    </td>
         <td>
     2    </td>
         <td>
     5    </td>
       </tr>
       <tr>
         <td>
     5    </td>
         <td>
     7    </td>
         <td>
     3    </td>
       </tr>
       <tr>
         <td>
     8    </td>
         <td>
     3    </td>
         <td>
     0    </td>
       </tr>
     </table>
```
Do you disagree that this should go away?

**Comment by pzinn** [comment]
apart from the slightly weird indentation, I think this is the correct output, yes.

**Comment by mahrud** [comment]
By "the (html, Matrix) method should go away" I mean that html should do one thing for all math objects: convert to tex and wrap them in $!

**Comment by mahrud** [comment]
> apart from the slightly weird indentation, I think this is the correct output, yes.

Are you saying you prefer the top output over the bottom output??

![image](https://user-images.githubusercontent.com/3147718/94995095-80743c80-0561-11eb-87a6-e6a2e818a057.png)

**Comment by pzinn** [comment]
we definitely should discuss this in more detail at some point, but my short answer: I think `html` should indeed produce html code, not tex code. if one wants mixed output, a method like  `htmlWithTex` would be appropriate, yes. or the user should be allowed to directly insert tex code into his HTML using TEX or something like that, but it's a different story. I didn't follow your recent changes, so am not sure if they contradict the philosophy above.
