### ISSUE TITLE
package DecomposableSparseSystems

### ISSUE THREAD

**Issue by DanGrayson** [Macaulay2/M2#1294]
The program phcpack isn't installed on every user's system, so detect its presence and enable re-running the examples and running the tests conditionally. This involves the use of the option OptionalComponentsPresent to newPackage. Three packages have started using this option already.

Meanwhile, I've modified the package (currently just on the branch development) to disable running the tests and examples, and to cache the example output when they are run.

**Comment by DanGrayson** [comment]
A better idea is to wait for #1295.  After PHCpack detects the presence of the program, this package can simply consult `(options PHCpack).OptionalComponentsPresent`.

**Comment by JoseMath** [comment]
Did #1295 get resolved to where we should consult (options PHCpack).OptionalComponentsPresent or some other way?

**Comment by DanGrayson** [comment]
Not yet -- I'll take a look today at what Anton did, perhaps fixing it.  I could fix yours, too, if you like ...

**Comment by DanGrayson** [comment]
Yes, that's been merged in, so you can do it like this:
```

i1 : needsPackage "PHCpack"

o1 = PHCpack

o1 : Package

i2 : (options PHCpack).OptionalComponentsPresent

o2 = true
```

**Comment by JoseMath** [comment]
> Not yet -- I'll take a look today at what Anton did, perhaps fixing it. I could fix yours, too, if you like ...

That would be great if you could fix ours too. Thank you~
