### ISSUE TITLE
package PHCpack

### ISSUE THREAD

**Issue by DanGrayson** [Macaulay2/M2#1295]
The program phcpack isn't installed on every user's system, so detect its presence and enable re-running the examples and running the tests conditionally. This involves the use of the option OptionalComponentsPresent to newPackage. Three packages have started using this option already.

**Comment by mahrud** [comment]
By the way, the link to phcpack in INSTALL is broken.

**Comment by DanGrayson** [comment]
Thanks, I've fixed it.

**Comment by mahrud** [comment]
The bertini link is also incorrect. This is the correct link: https://bertini.nd.edu (the latest version is v1.6 in 2018, but the version you linked has up to v1.4 in 2013).

**Comment by antonleykin** [comment]
PHCpack package header has 
```
  Configuration => { 
    "path" => "",
    "PHCexe"=>"phc", 
    "keep files" => true
  },
```
Should `OptionalComponentsPresent` be checking the presence of the defaults?

**Comment by DanGrayson** [comment]
The idea is that you would have code that tests for the presence of phcpack on the PATH, and, if it's there, provide "true" as the value for OptionalComponentsPresent.  Then the examples would get rerun (automatically) and you could arrange for tests to run, too.

Hmm, maybe the function "check" should be modified so if the optional components are not present, then no tests are run.

**Comment by antonleykin** [comment]
I guess the question is: at what point `OptionalComponentsPresent` is getting used?
If this happens *before* the package is loaded then... e.g., the way `Tropical` is using is likely invalid.

**Comment by DanGrayson** [comment]
But `Tropical` doesn't use it.  (That line is commented out.)

The value is used by `newPackage` to set `UseCachedExampleOutput` at load time.  And then at install time, that determines whether the examples are rerun or the old results are used.
