### ISSUE TITLE
workflow action should run tests

### ISSUE THREAD

**Issue by DanGrayson** [Macaulay2/M2#1299]
We should also run the tests in at least one of the github action workflow jobs.  How many?  Which?

**Comment by mahrud** [comment]
Currently the autotools builds that run `make check` take about 5 hours, which is simply too much for virtually all commits. In particular, only commits that change one of:
- the submodules
- the libraries directory
- the autotools or cmake scripts
should run library tests. We do more testing of flint and factory than flint and factory repositories themselves!! That's a waste of time and resources.

**Comment by mahrud** [comment]
Probably the easiest way to do this is to add a separate workflows for building and testing various pieces (e.g. libraries + M2, package examples, Core tests, package tests, library tests) and they would be triggered based on the commit diff.
