### ISSUE TITLE
Feature request: C calls in top level (foreign function interface)

### ISSUE THREAD

**Issue by mahrud** [Macaulay2/M2#1310]
[FFI](https://en.wikipedia.org/wiki/Foreign_function_interface) would allow top level interaction with system calls and dynamic libraries without the need to add bindings in the d language and recompile.

Here's are some examples:
- haskell [demo](https://wiki.haskell.org/FFI_Introduction) and [documentation](https://wiki.haskell.org/Foreign_Function_Interface).
- Julia [manual](https://docs.julialang.org/en/v1/manual/calling-c-and-fortran-code/).

**Comment by DanGrayson** [comment]
This would be a valuable feature, especially if the interface would parse library include files and figure out what to do from them (who wants to manually type 1000 function declarations?).  Implementing it would be a big challenge and take a lot of time.

**Comment by mahrud** [comment]
Thanks, @d-torrance!
