### ISSUE TITLE
degreeLength(QQ[]) should be 0

### ISSUE THREAD

**Issue by mahrud** [Macaulay2/M2#1312]
I think this is incorrect, but maybe I'm misinterpreting it:
```m2
i1 : degreeLength QQ
o1 = 0
i2 : degreeLength(QQ[])
o2 = 1
```

**Comment by mikestillman** [comment]
I think this is correct.  Part of the point of making polynomial rings like this is to get access to arbitrary gradings.  The default though is singly graded (degreeLength = 1)

**Comment by mahrud** [comment]
Ah, okay. There isn't a DegreeLength option for monoid, though. Is there another trick for defining Q as a polynomial ring?

Also, I think because of that default, this doesn't work:
```m2
i28 : basis(0,QQ[])
stdio:28:1:(3): error: expected degrees of length 0

i29 : basis({0},QQ[])
stdio:29:1:(3): error: expected degrees of length 0

i30 : basis({0},QQ[x])

o30 = | 1 |

                    1             1
o30 : Matrix (QQ[x])  <--- (QQ[x])

i31 : basis(0,QQ[x])

o31 = | 1 |

                    1             1
o31 : Matrix (QQ[x])  <--- (QQ[x])
```

**Comment by mikestillman** [comment]
Now those look more like things that we should fix!

**Comment by mahrud** [comment]
Looks like this works though:
```m2
i14 : basis({},QQ[DegreeRank => 0])

o14 = | 1 |

                   1            1
o14 : Matrix (QQ[])  <--- (QQ[])
```
So the default should just check for an empty array as an edge case.

Also, is degree rank always the same as degree length?
https://github.com/mahrud/M2/blob/5ac7eb2c06c97a473e60cc512b42c1adbe4bacc3/M2/Macaulay2/m2/ofcm.m2#L238

**Comment by DanGrayson** [comment]
Shoot, it looks like we're using two words where one would have sufficed!:
```
i21 : R = QQ [a,b,c,DegreeRank=>3]

o21 = R

o21 : PolynomialRing

i22 : degreeLength R

o22 = 3
```

**Comment by DanGrayson** [comment]
Who's going to volunteer to fix that?  Mahrud?

**Comment by DanGrayson** [comment]
This bug might be related and needs to be fixed:
```m2
Macaulay2, version 1.15.1.0
with packages: ConwayPolynomials, Elimination, IntegralClosure, InverseSystems, LLLBases,
               PrimaryDecomposition, ReesAlgebra, TangentCone, Truncations

i1 : R = QQ[x,Degrees=>{{0}}]

o1 = R

o1 : PolynomialRing

i2 : basis_1 R

o2 = | 1 |

             1       1
o2 : Matrix R  <--- R
```

**Comment by mahrud** [comment]
I'm pretty sure this is not intentional, right?
```m2
i2 : degreeLength degreesMonoid 0

o2 = 1

i3 : degreeLength degreesRing 0

o3 = 0
```

**Comment by DanGrayson** [comment]
The first one looks like a bug:
```m2
i6 : degreeLength degreesMonoid 2

o6 = 0

i7 : degreeLength degreesMonoid 1

o7 = 0

i8 : degreeLength degreesMonoid 0

o8 = 1
```
