### ISSUE TITLE
timing-quotient.m2 failing

### ISSUE THREAD

**Issue by d-torrance** [Macaulay2/M2#1316]
The last test is failing for me:

https://github.com/Macaulay2/M2/blob/92af2b930403302538a9311e1b5c400fb4c5e0f9/M2/Macaulay2/tests/normal/timing-quotient.m2#L219-L223

I dug a little further, and it's hanging when we get to this call to `factorize` from factory:

https://github.com/Macaulay2/M2/blob/92af2b930403302538a9311e1b5c400fb4c5e0f9/M2/Macaulay2/e/x-factor.cpp#L699-L704

I'm building Macaulay2 using the Debian/Ubuntu singular package, which is version 4.1.1.  This is happening in both Ubuntu 19.10 and Debian unstable.

**Comment by DanGrayson** [comment]
How much slower is it than the test requires?

**Comment by mahrud** [comment]
I think the problem is that the distributed `libsingular-factory-4.1.1.so` is linked with `libflint-2.5.2.so`, which is missing a major factorization speed improvement added in v2.6.0. I'm guessing that before the eigen branch we used Pari for this method.

Also, `linsingular-factory` is compiled with different flags and without a patch, should we even be using it even if it is present? The CMake build doesn't.

**Comment by DanGrayson** [comment]
Another issue will be that factory 4.1.3 returns results sorted in a different order than does 4.1.1, for that reason also it's a good idea to insist on 4.1.3, since we have 1 test that will fail in that case.

**Comment by DanGrayson** [comment]
I'll fix the configure script to require 4.1.3.

**Comment by d-torrance** [comment]
> How much slower is it than the test requires?

It just hangs until the process is killed:

```
testing: timing-quotient.m2
Command terminated by signal 9
89.83user 0.14system 1:29.96elapsed 100%CPU (0avgtext+0avgdata 112920maxresident)k
timing-quotient.errors:0: error output left here for the errors above:
make[5]: *** [../Makefile.test:67: timing-quotient.out] Error 137
```

> I think the problem is that the distributed `libsingular-factory-4.1.1.so` is linked with `libflint-2.5.2.so`, which is missing a major factorization speed improvement added in v2.6.0. I'm guessing that before the eigen branch we used Pari for this method.

My understanding is that the pari -> flint switch was for factoring over ZZ, right?  This test is factoring over QQ[x,y,z], and there have only been very minimal changes to polynomial factorization:

```
profzoom@gloria:~/src/macaulay2/M2/M2/Macaulay2/e$ git diff origin/release-1.15 origin/development -- x-factor.cpp
diff --git a/M2/Macaulay2/e/x-factor.cpp b/M2/Macaulay2/e/x-factor.cpp
index 6a151054c..6780dca1f 100644
--- a/M2/Macaulay2/e/x-factor.cpp
+++ b/M2/Macaulay2/e/x-factor.cpp
@@ -1,7 +1,5 @@
 // copyright Daniel R. Grayson, 1995
 
-#include "../d/M2inits.h"
-
 #include "exceptions.hpp"
 #include <M2/config.h>
 #include <assert.h>
@@ -465,7 +463,7 @@ static CanonicalForm convertToFactory(const RingElement &g, bool inExtension)
   return f;
 }
 
-void displayCF(PolynomialRing *R, const CanonicalForm &h)  // for debugging
+void displayCF(const PolynomialRing *R, const CanonicalForm &h)  // for debugging
 {
   buffer o;
   const RingElement *g = convertToM2(R, h);
```

I'm confused because I don't have any problems factoring the same polynomial in Ubuntu 19.10 with factory 4.1.1 using:

- the Macaulay2 package from the https://faculty.math.illinois.edu/ repo
- Singular itself
- a small C++ program which just constructs this polynomial and factors it using factory

The latter two are using the same Ubuntu package of factory that are giving me problems when I build Macaulay2.

**Comment by DanGrayson** [comment]
Doug, does it work with factory 4.1.3?  If so, could you package factory separately from singular for debian?

**Comment by d-torrance** [comment]
I figured out the problem!  It works in 1.15 because of this patch:

https://github.com/Macaulay2/M2/blob/73b3517451d05f708c64d734713fd174dfc689f6/M2/libraries/factory/patch-4.1.1#L20

If I add that line to `x-factor.cpp`, then the test works just fine.  (I'm still not sure why it worked in Singular or in my little C++ program without the patch...)

> Doug, does it work with factory 4.1.3?

It should, as the patch was applied before the 4.1.2 release:
https://github.com/Singular/Sources/commit/a75617a

> If so, could you package factory separately from singular for debian?

Singular 4.1.2 has already been packaged for Debian, but for *experimental* instead of *unstable*.  (Note that *unstable* packages migrate to *testing* after several days (and to Ubuntu), and the packages in *testing* eventually become part of the next *stable* release after a freeze, which usually happens every two years.)

It looks like the Debian Sage maintainers want to hold off on uploading 4.1.2 or 4.1.3 to *unstable* until it works nicely with Sage:

* https://alioth-lists.debian.net/pipermail/debian-science-sagemath/2019-November/001582.html
* https://trac.sagemath.org/ticket/25993

So for now, I'll just patch `x-factor.cpp`.

Question: Would it be worth submitting this patch upstream so Macaulay2 can be built with older version of factory?

**Comment by DanGrayson** [comment]
> Question: Would it be worth submitting this patch upstream so Macaulay2 can be built with older version of factory?

Yes, even though we are now going to insist on 4.1.3.

**Comment by d-torrance** [comment]
> > Question: Would it be worth submitting this patch upstream so Macaulay2 can be built with older version of factory?
> 
> Yes, even though we are now going to insist on 4.1.3.

Sounds good!  I'll submit a PR once I make sure everything still builds okay with the patch.

So the 4.1.3 requirement is just because of another failing test?  Which one is it?  I haven't had any problems with any other tests using the 4.1.1 package in Debian.

**Comment by DanGrayson** [comment]
I think it's one in the computations book.  The test has not yet been fixed, i.e., it fails *only* with 4.1.3, because a list of factors comes out in a different order.

**Comment by d-torrance** [comment]
> I think it's one in the computations book. The test has not yet been fixed, i.e., it fails _only_ with 4.1.3, because a list of factors comes out in a different order.

Gotcha.  Would it make sense to change the test so that it sorts the factors?  Or maybe have a different expected output based on the version of factory, similar to:

https://github.com/Macaulay2/M2/blob/73b3517451d05f708c64d734713fd174dfc689f6/M2/Macaulay2/tests/ComputationsBook/varieties/Makefile.in#L4-L9

**Comment by DanGrayson** [comment]
Probably what makes the most sense is always to sort the factors returned by factory in the C++ routine that calls it.  Our engine algorithms should always have chosen for them a good canonical ordering of results, so changes in algorithms don't affect results.  That's for the future, though.  When I encounter the broken test while preparing distributions (soon), I'll make an issue and tag @mikestillman .

By the way, I stopped preparing distributions for 32 bit machines years ago.

**Comment by mahrud** [comment]
@d-torrance do you know why `libsingular4-dev` installs some header files in a subdirectory of `/usr/lib`? The nonstandard behavior is part of the reason I decided to ignore it in the CMake build.

**Comment by d-torrance** [comment]
> @d-torrance do you know why `libsingular4-dev` installs some header files in a subdirectory of `/usr/lib`? The nonstandard behavior is part of the reason I decided to ignore it in the CMake build.

I don't see any header files in `/usr/lib`, but there are several under `/usr/include/x86_64-linux-gnu`.  Is that what you're referring to?  (Here's the [list of the files](https://packages.debian.org/sid/amd64/libsingular4-dev/filelist) in the package.)  Those are the architecture-dependent header files.  Debian puts them there for [multiarch](https://wiki.debian.org/Multiarch) support, e.g., for running 32-bit applications on a 64-bit system, cross-building, etc.  The compiler should be able to find them just fine using `pkg-config`:

```
profzoom@gloria:~$ pkg-config --cflags singular-factory
-DSING_NDEBUG -DOM_NDEBUG -DSING_NDEBUG -DOM_NDEBUG -I/usr/include/x86_64-linux-gnu/singular -I/usr/include/singular -I/usr/include/x86_64-linux-gnu/singular -I/usr/include/singular -I/usr/include/x86_64-linux-gnu/singular -I/usr/include/singular
```
