### ISSUE TITLE
Matrices are not printed correctly when the coefficient field was declared with toField

### ISSUE THREAD

**Issue by tom111** [Macaulay2/M2#132]
The routine that prints a matrix to the screen seems to fail when the coefficient field was constructed with "toField". Here is an example:

i1 : R = (toField (QQ[z]/(z^2+1)))[x]
i2 : matrix {{x^2+x+1}}
o2 = | 1x21x1 | 

I could accept the coefficient "1" being printed, but the "+" are missing.  Note that printing outside of a matrix works.  Also note that when leaving away toField also works:

i3 : R = (QQ[z]/(z^2+1))[x]
i4 : matrix {{x^2+x+1}}
o4 = | x2+x+1 |

**Comment by mikestillman** [comment]
This issue looks like it has been fixed, without closing this issue.  I'm going to close it now.
