### ISSUE TITLE
 fix the configure script to require factory 4.1.3.

### ISSUE THREAD

**Issue by DanGrayson** [Macaulay2/M2#1320]
I'll fix the configure script to require 4.1.3.

_Originally posted by @DanGrayson in https://github.com/Macaulay2/M2/issues/1316#issuecomment-647502727_

**Comment by mahrud** [comment]
To keep build systems in sync, you can change this line at the same time:
https://github.com/Macaulay2/M2/blob/73b3517451d05f708c64d734713fd174dfc689f6/M2/cmake/check-libraries.cmake#L124
