### ISSUE TITLE
name mismatches

### ISSUE THREAD

**Issue by mikestillman** [Macaulay2/M2#1335]
We have two functions: `LUdecomposition`, and `QRDecomposition`, one with lower case d, one with upper.  How can we fix this?  @DanGrayson suggestions?  Also, perhaps SVD should be named SVDdecomposition.  But we can't really change those function names at this point, I suppose.  We could make synonyms?  Or 2 versions, one which complains about being deprecated?

**Comment by DanGrayson** [comment]
Let's just leave it.  (What mathematicians can we blame for those horrible names?)

Or change them both to sensible names, such as `lowerUpperDecomposition` and `orthogonalUpperDecomposition`.

The D in SVD means decomposition, so SVDdecomposition would be strange!

**Comment by DanGrayson** [comment]
Change SVD to `singularValuesDecomposition`.

**Comment by mahrud** [comment]
Closing in favor of #2687.
