### ISSUE TITLE
pari documentation

### ISSUE THREAD

**Issue by DanGrayson** [Macaulay2/M2#1343]
Now that we no longer link to PARI, we should remove references to it in the documentation that imply we do.

**Comment by mahrud** [comment]
Should the node `pari` be removed? Currently that only says that PARI was used from 1.2 to 1.15, but `changes.m2` includes that information.

**Comment by mahrud** [comment]
The `pari` node is also linked to from the entry in `changes.m2`, but I could turn `TO "pari"` into a link to PARI's website instead.

**Comment by DanGrayson** [comment]
Sounds good to me.
