### ISSUE TITLE
GraphicalModels hiddenMap function doesn't respect coefficient ring

### ISSUE THREAD

**Issue by jeremy9959** [Macaulay2/M2#1362]
The `hiddenMap` function in the GraphicalModels package doesn't respect the coefficients of the ring.  Here's a patch.
 
```diff
***************
*** 1145,1165 ****
  -- observed) random variables is now a hidden variable. 
  ------------------------------------------------------------------
  
  hiddenMap = method()
  hiddenMap(ZZ,Ring) := RingMap => (v,A) -> (
       v = v-1;
       p := i -> A.markovVariables#i;
       if not A.?markovRingData then error "expected a ring created with markovRing";
       d := A.markovRingData;
       e := drop(d, {v,v});
!      S := markovRing (e, Coefficients=>coefficientRing(A));
       dv := d#v;
       F := toList apply(((#e):1) .. e, i -> (
  	       sum(apply(toList(1..dv), j -> (
  			      newi := join(take(i,v), {j}, take(i,v-#d+1));
  			      p newi)))));
       map(A,S,F))
  
  
  ------------------------------------------------------------------
  -- identifyParameters (Ring,MixedGraph)
--- 1145,1165 ----
  -- observed) random variables is now a hidden variable. 
  ------------------------------------------------------------------
  
  hiddenMap = method()
  hiddenMap(ZZ,Ring) := RingMap => (v,A) -> (
       v = v-1;
       p := i -> A.markovVariables#i;
       if not A.?markovRingData then error "expected a ring created with markovRing";
       d := A.markovRingData;
       e := drop(d, {v,v});
!      S := markovRing (e);
       dv := d#v;
       F := toList apply(((#e):1) .. e, i -> (
  	       sum(apply(toList(1..dv), j -> (
  			      newi := join(take(i,v), {j}, take(i,v-#d+1));
  			      p newi)))));
       map(A,S,F))
  
  
  ------------------------------------------------------------------
  -- identifyParameters (Ring,MixedGraph)
```

**Comment by Sondzus** [comment]
@luisgarciapuente  Here it is! :)

**Comment by luisgarciapuente** [comment]
This change works. Dan: can you accept the patch?

**Comment by DanGrayson** [comment]
Luis, could you submit a pull request including the changed line?  Then github will runs tests for us on it.

**Comment by luisgarciapuente** [comment]
Hi Dan,

We are actually making several other changes to GraphicalModels.m2 as we prepare to submit a new package GraphicalModelsMLE.m2 for Macaulay2's next release. So I will include this change with all the others if that is ok.

**Comment by jeremy9959** [comment]
Hi @luisgarciapuente, I'm finding the graphical models package very useful and i'm interested in the improvements you are making.  Would you be willing to share more info on where that's going?  You can email me directly, I'm easily findable at UConn. Thanks a lot.

**Comment by DanGrayson** [comment]
> Hi Dan,
> 
> We are actually making several other changes to GraphicalModels.m2 as we prepare to submit a new package GraphicalModelsMLE.m2 for Macaulay2's next release. So I will include this change with all the others if that is ok.

Sure.

**Comment by mikestillman** [comment]
Hi @luisgarciapuente , how are your changes going for the graphical models package?

**Comment by luisgarciapuente** [comment]
Hi Mike,

We submitted all the changes in time for the new M2 release, including the change on the hiddenMap function.

Best,

Luis

**Comment by luisgarciapuente** [comment]
Thanks, in deed those things are fixed now

Luis
