### ISSUE TITLE
line wrapping has changed for the worse

### ISSUE THREAD

**Issue by DanGrayson** [Macaulay2/M2#1372]
Compare https://faculty.math.illinois.edu/Macaulay2/doc/Macaulay2-1.15/share/doc/Macaulay2/Macaulay2Doc/html/_elimination_spof_spvariables.html to https://faculty.math.illinois.edu/Macaulay2/doc/Macaulay2-1.16/share/doc/Macaulay2/Macaulay2Doc/html/_elimination_spof_spvariables.html : 

<img width="488" alt="Screen Shot 2020-07-06 at 10 24 27 AM" src="https://user-images.githubusercontent.com/700228/86604122-95453200-bf6a-11ea-906e-3a16d37131a3.png">

<img width="639" alt="Screen Shot 2020-07-06 at 10 24 47 AM" src="https://user-images.githubusercontent.com/700228/86604136-9aa27c80-bf6a-11ea-89ac-30130df4c3e1.png">

**Comment by DanGrayson** [comment]
@d-torrance -- this could be from your commit 3a686bc6b0d960f979fc72c4bc475abe765b2c02

**Comment by DanGrayson** [comment]
I'd like to get this fixed before releasing 1.16.  Thanks to @giovannistagliano for letting me know about the problem.

**Comment by d-torrance** [comment]
Yikes!  Yeah, it's definitely that commit.  Feel free to revert.

In many instances, I think the commit provides an improvement, especially when using `help` inside Macaulay2 (e.g., the screenshots I provided in https://github.com/Macaulay2/M2/pull/1337#issue-440148436).  But certainly anything like the example above involving printing the net form of a polynomial with the exponents on a separate line will look horrible!

The number of build paths that are split between lines when wrapping the examples (the original reason for the commit) is very small.  We'll still catch most of them without this commit.

**Comment by d-torrance** [comment]
In fact, even without 3a686bc, I don't get any build paths in the documentation.  Some of the examples look a little odd because long build paths have been replaced with shorter paths and it looks like things were wrapped a bit too much.  But nowhere near as bad as the first example above!

```
i1 : path

o1 = {./, /usr/share/Macaulay2/Core/,
     ------------------------------------------------------------------------
     /usr/share/Macaulay2/,
     ------------------------------------------------------------------------
     /usr/share/
     ------------------------------------------------------------------------
     Macaulay2/Core/, /usr/
     ------------------------------------------------------------------------
     common/share/Macaulay2/}

o1 : List

i2 : path = append(path, "~/resolutions/")

o2 = {./, /usr/share/Macaulay2/Core/,
     ------------------------------------------------------------------------
     /usr/share/Macaulay2/,
     ------------------------------------------------------------------------
     /usr/share/
     ------------------------------------------------------------------------
     Macaulay2/Core/, /usr/
     ------------------------------------------------------------------------
     common/share/Macaulay2/, ~/resolutions/}

o2 : List
```

**Comment by DanGrayson** [comment]
By the way, there are two other things we could do:

- (1) Change `temporaryFilename` so it ignores the system's suggestion and just puts something in `/tmp`.  That would make something a lot shorter than `/var/folders/46/9b86vqxj4hjcngvy7kd7sb140000gn/T/M2-36697-0/0`.

- (2) increase the printWidth value in use during example generation.

**Comment by DanGrayson** [comment]
The problem with the line wrapping in the screen shots in https://github.com/Macaulay2/M2/pull/1337#issue-440148436 is that you are using a terminal that wraps the lines.  Emacs does a better job:
<img width="1393" alt="Screen Shot 2020-07-07 at 12 45 47 PM" src="https://user-images.githubusercontent.com/700228/86814833-87191380-c047-11ea-8bf4-8efd1ea290d9.png">

**Comment by d-torrance** [comment]
> The problem with the line wrapping in the screen shots in [#1337 (comment)](https://github.com/Macaulay2/M2/pull/1337#issue-440148436) is that you are using a terminal that wraps the lines. Emacs does a better job:

That's true! I mostly use Emacs, but was using the terminal to run a newly-installed Debian package in a chroot when I was working on that pull request.

**Comment by DanGrayson** [comment]
I've just discovered that `xterm` can be told not to wrap, with the `+aw` option.

<img width="1067" alt="Screen Shot 2020-07-07 at 2 04 35 PM" src="https://user-images.githubusercontent.com/700228/86823401-6f935800-c052-11ea-93f0-b42f91bd27be.png">
