### ISSUE TITLE
CMake does not detect OpenMP flags with clang-10 on macOS

### ISSUE THREAD

**Issue by mahrud** [Macaulay2/M2#1376]
@moorewf reported that using clang-10 installed via `brew install llvm libomp`, CMake doesn't seem to be able to find OpenMP flags, which causes csdp build to fail. My various attempts at giving CMake the prefix to find libomp.dylib failed.

The autotools build seems to be unaffected.

**Comment by DanGrayson** [comment]
What does "to find OpenMP flags" mean?

**Comment by mahrud** [comment]
Detect "-fopenmp".

**Comment by DanGrayson** [comment]
Where is your code for determining the flag?

**Comment by mahrud** [comment]
The point is that CMake does that, not me, and for some reason it's failing.

**Comment by mikestillman** [comment]
cmake has been pretty good at finding the correct openmp flags.  I am probably using an older vbersion now of "latest clang" (9.0.0, not 10.0.0), but here is what I do to get cmake to work on 9.0.0. (this is my Makefile entry to create the build directory)
```
cmake-latestclang:
	mkdir -p builds.tmp/cmake-latestclang
	cd builds.tmp/cmake-latestclang; cmake \
		-GNinja \
	        -DCMAKE_C_COMPILER:FILEPATH=/usr/local/opt/llvm/bin/clang \
		-DCMAKE_CXX_COMPILER:FILEPATH=/usr/local/opt/llvm/bin/clang++ \
		-DCMAKE_BUILD_TYPE=RelWithDebInfo \
		-DBUILD_TESTING=on \
		-DBUILD_DOCS=on \
		../../../..
```

Should I upgrade and retry it?

**Comment by DanGrayson** [comment]
It works on my machine, too, which has clang 11.

**Comment by DanGrayson** [comment]
What it finds is `-Xclang -fopenmp`.

**Comment by mahrud** [comment]
@mikestillman This alone doesn't seem to suffice. Here is the tests on github actions:
https://github.com/mahrud/M2/runs/846593963?check_suite_focus=true#step:8:67

@DanGrayson this issue is specifically about the latest version of clang available from the llvm brew package, which is clang-10.

**Comment by DanGrayson** [comment]
What's the syntax for telling cmake to use a different compiler?

**Comment by moorewf** [comment]
I think commands such as

set(CMAKE_C_COMPILER "/path/to/your/c/compiler/executable")
set(CMAKE_CXX_COMPILER "/path/to/your/cpp/compiler/executable")

do the trick when in a cmake file.  To do it at the command line, add
something like

-DCMAKE_C_COMPILER:FILEPATH=/path/to/your/c/compiler/executable
-DCMAKE_CXX_COMPILER:FILEPATH=/path/to/your/cpp/compiler/executable

to the cmake command at the command line.

**Comment by mahrud** [comment]
Alternatively, on the first run of cmake you can do something like this:
CC=`which clang-10` CXX=`which clang++-10` cmake ....
CMake will initialize a number of variables from environment variables.

**Comment by DanGrayson** [comment]
I think you have to add `-L/usr/local/lib` so it finds the library:
```
einsteinium$ /usr/local/opt/llvm/bin/clang++ -L/usr/local/lib -Xclang -fopenmp -lomp foo.cc
einsteinium$ /usr/local/opt/llvm/bin/clang++ -Xclang -fopenmp -lomp foo.cc
ld: library not found for -lomp
clang-10: error: linker command failed with exit code 1 (use -v to see invocation)
```

Also `-I/usr/local/include`.

**Comment by mahrud** [comment]
@DanGrayson The point is that CMake should detect and set those parameters, not us. In particular, llvm from brew already includes libomp.dylib, so we shouldn't need to add `-L/usr/local/lib`. Turns out, on macOS clang sets the sysroot to the Xcode SDK directory, and somehow misses its own library directories, but not header directories. Also `-Xclang` is only needed with AppleClang.

@moorewf This is probably a bug in clang, but for now I made a [new PR](#1379) which should work along with the following addition:
```
LIBRARY_PATH=`llvm-config --libdir` cmake ...
```
The llvm-config executable should be next to `clang-10`, so probably `/usr/local/opt/llvm/bin/llvm-config` with brew. I tested this on Github Actions, but if you get a chance to pull my `feature/cmake` branch and try it out, let me know if it works.

To be clear, setting `LIBRARY_PATH` is not the same thing as passing a `-L..` flag. It tells clang (not cmake!) where to look for its internal libraries, and once clang can find them, cmake can properly detect the OpenMP flags and libraries.

**Comment by DanGrayson** [comment]
> @DanGrayson The point is that CMake should detect and set those parameters, not us. In particular, llvm from brew already includes libomp.dylib, so we shouldn't need to add `-L/usr/local/lib`. 

Right.  Fix cmake by adding `-L/usr/local/lib` in its scripts.  Or fix homebrew so it builds a clang that looks in /usr/local/lib.

**Comment by mahrud** [comment]
Like I said, Clang includes libomp, and it is not in /use/local/lib.
Hardcoding the brew prefix is a hack.

**Comment by moorewf** [comment]
@mahrud I was able to get it to work with the updates in your feature/cmake
branch together with setting the LIBRARY_PATH in the call to cmake.  I also
noticed you placed a blurb on this in the INSTALL-CMake.md file.  Thanks
for your help!
