### ISSUE TITLE
Relocate the portion of Truncations that uses Polyhedra

### ISSUE THREAD

**Issue by mahrud** [Macaulay2/M2#1377]
When M2 loads, a number of packages are preloaded. I believe this is done by `last.m2` when it reads [m2/installedPackages](https://github.com/Macaulay2/M2/blob/master/M2/Macaulay2/m2/installedpackages). This lists corresponds to the initial value of `loadedPackages` (minus Core).

However, this doesn't quite correspond to the list of packages printed when M2 starts (Classic and SimpleDoc are missing) nor does it include about 7 packages that are loaded as dependencies and visible via `loadedFiles`: Parsing, Text, FourTiTwo, FourierMotzkin, Normaliz, Topcom, and Polyhedra.

In particular, in order to define Ext and cohomology, `varieties.m2` and `local.m2` call needsPackage on Truncations, which in turn loads Polyhedra's ~60 files. This could be simplified to speed up load times. Here are three ways I can think of:
- move Ext and cohomology elsewhere (e.g. Complexes?);
- use autoload instead of needsPackage;
- relocate the portion of Truncations that uses Polyhedra to the Polyhedra package.

**Comment by mahrud** [comment]
> * use autoload instead of needsPackage;

Related to this, perhaps it would be good to have a version of [`autoload`](http://www2.macaulay2.com/Macaulay2/doc/Macaulay2-1.16/share/doc/Macaulay2/Macaulay2Doc/html/_autoload_lp__Symbol_cm__String_rp.html) for method functions, in particular `truncate`.

**Comment by mahrud** [comment]
@DanGrayson the suggestion about would be good to implement, if you can think of a way to do it. Or any of the alternatives in the top comment.

**Comment by DanGrayson** [comment]
Loading Polyhedra takes only 0.13 seconds:
```m2
+ M2 --no-readline -q --print-width 218 --no-preload
Macaulay2, version 1.16.0.2

i1 : time loadPackage "Polyhedra"
     -- used 0.130304 seconds

o1 = Polyhedra

o1 : Package
```

Is it worth worrying about?

**Comment by mahrud** [comment]
Yes, try uninstalling all packages first! It takes about 4 seconds on my machine.
The user would obviously get M2 with all packages preinstalled, but the problem is that while examples are being generated, new instances of M2 are starting and loading about 70 files (Polyhedra alone has 60 files) that they don't need, unless they call the `truncate` command.

**Comment by DanGrayson** [comment]
Maybe we should have fewer preloaded packages, so Polyhedra isn't included.

**Comment by mahrud** [comment]
The point, precisely, is that **Truncations** is the one that loads Polyhedra! I already did this in #1661, but it would be better to implement one of the changes I suggested above, so `truncate` can be made independent of Polyhedra.

**Comment by DanGrayson** [comment]
Still, why preload Truncations?  The more that gets moved into (small) packages, the better.

**Comment by mahrud** [comment]
Truncations is very tiny, and truncate is pretty useful, to the point that I think it _should_ be preloaded. So I want to reiterate something that I think would be great:

> Related to this, perhaps it would be good to have a version of [`autoload`](http://www2.macaulay2.com/Macaulay2/doc/Macaulay2-1.16/share/doc/Macaulay2/Macaulay2Doc/html/_autoload_lp__Symbol_cm__String_rp.html) for method functions declared in `shared.m2`, in particular `truncate`.

This would hold off on loading all of Polyhedra until at least the method keys of truncate that come from Truncations are called.

**Comment by DanGrayson** [comment]
More use of autoloading would indeed be good.
