### ISSUE TITLE
--top-srcdir, source directory, and m2 directory

### ISSUE THREAD

**Issue by mahrud** [Macaulay2/M2#1397]
First, the `--top-srcdir` flag (mentioned in `M2 --help`, the man page, etc.) is wrong. The correct flag seems to be `--srcdir`, but even then, I'm not sure that it's doing the right thing.

When running the compiled M2 binary from a build directory, here is the behavior:
```bash
[mahrud@noether build]$ ./M2 -q --silent -e 'print stack path; exit 0'
./
../../Macaulay2/m2/
../../Macaulay2/packages/
Macaulay2/m2/
usr-dist/common/share/Macaulay2/Core/
usr-dist/common/share/Macaulay2/
[mahrud@noether build]$ ./M2 --srcdir /home/mahrud/Projects/M2/M2/M2 -q --silent -e 'print stack path; exit 0'
./
../../Macaulay2/m2/
../../Macaulay2/packages/
Macaulay2/m2/
usr-dist/common/share/Macaulay2/Core/
usr-dist/common/share/Macaulay2/
```
So nothing is added, but presumably a few things should be removed. Also, when running an installed M2 binary from anywhere, for instance the source directory, here is the behavior:
```bash
[mahrud@noether M2]$ M2 -q --silent -e 'print stack path; exit 0'
./
/usr/local/share/Macaulay2/Core/
/usr/local/share/Macaulay2/
[mahrud@noether M2]$ M2 -q --srcdir /home/mahrud/Projects/M2/M2/M2 --silent -e 'print stack path; exit 0'
./
Macaulay2/packages/
/usr/local/share/Macaulay2/Core/
/usr/local/share/Macaulay2/
```
So only `Macaulay2/packages/` is added, which misses `Macaulay2/m2`! Meaning that if I had changed some stuff in my source and I wanted to try out those changes, they would not be used.

As a potential solution, after moving `m2` to `Core` in the source directory, here is the behavior:
```bash
[mahrud@noether M2]$ M2 -q --srcdir /home/mahrud/Projects/M2/M2/M2 --silent -e 'print stack path; exit 0'
./
Macaulay2/Core/
Macaulay2/packages/
/usr/local/share/Macaulay2/Core/
/usr/local/share/Macaulay2/
```

An alternative, provided by @DanGrayson, is to move `m2` to `packages/Core`. This has the benefit of matching the installed directory structure under `share/Macaulay2`.

**Comment by DanGrayson** [comment]
I don't like the idea of moving files, since it breaks the history as viewed by `git blame`.

**Comment by mahrud** [comment]
@DanGrayson there's a lot more to this issue. Moving files is just one option, but even then [there are ways](https://stackoverflow.com/questions/29468273/why-git-blame-does-not-follow-renames) to use `git blame`. For instance, I recently moved a file (I think html.m2) to installPackage.m2, and you can see a perfectly fine `git blame` here: https://github.com/Macaulay2/M2/blame/master/M2/Macaulay2/m2/installPackage.m2

Also, I'd like to think M2 has at least as much changes awaiting to occur in the future than it has in the past, so moving files, when it improves organization, is better done now than later.

**Comment by mahrud** [comment]
The `--help` usage and the man page are out of sync. Would be good to make one of them based on the other, and perhaps even use that to generate the [documentation node](http://www2.macaulay2.com/Macaulay2/doc/Macaulay2/share/doc/Macaulay2/Macaulay2Doc/html/___Invoking_spthe_spprogram.html).

**Comment by DanGrayson** [comment]
> The `--help` usage and the man page are out of sync. Would be good to make one of them based on the other

Good catch.  But here's the code:
```m2
     "The options that can be provided on the command line may be displayed by running ", TT "M2 --help", ", as follows.",
     EXAMPLE ///run "M2 --help";///,
```

The problem is that we have a bug in how we generate the documentation node: it looks on the PATH for "M2", instead of using the same M2 currently being run.

A good way to fix that would be prepend Macaulay2's "bin" directory to the PATH in the "M2" shell script.  We might as well also prepend Macaulay2's libexec/bin directory to the path, so various programs (4ti2, etc.) are on the path.

Here is the current M2 shell script:
```sh
#! /bin/sh
# We assume that @ pre_bindir @/.. is ${pre_exec_prefix} (see configure.ac)
case "darwin20.1.0" in
   cygwin) export PATH=`dirname "$0"`/../lib/Macaulay2/lib:$PATH ;;
  darwin*) # Mac OS X:
           export DYLD_LIBRARY_PATH=`dirname "$0"`/../lib/Macaulay2/lib:$DYLD_LIBRARY_PATH ;;
        *) export   LD_LIBRARY_PATH=`dirname "$0"`/../lib/Macaulay2/lib:$LD_LIBRARY_PATH ;;
esac
exec `dirname "$0"`/M2-binary "$@"
# Local Variables:
# compile-command: "make -C $M2BUILDDIR/Macaulay2/bin M2 "
# End:
```
