### ISSUE TITLE
autotools should allow using linuxbrew

### ISSUE THREAD

**Issue by mahrud** [Macaulay2/M2#1412]
Autotools uses brew by assuming that the path is `/usr/local`, which is not always correct. Instead it should use `brew --prefix`, which would also work with linuxbrew. This would be easy to do (see 4934130), but autotools doesn't correctly pass the header and library search directories to other libraries (see https://github.com/Macaulay2/M2/pull/1379#issuecomment-657587746). See #1379 for background.

A main advantage is that packages like flint are more frequently updated on brew than on the standard linux distribution channels.

This is a requirement for using the autotools build for a brew formula, though the cmake build works okay in a formula at the moment.

**Comment by DanGrayson** [comment]
The configure script should not assume the user wants it to look at the files in `brew --prefix`.  That should be left to the user, who can set LDFLAGS and CPPFLAGS appropriately.

It is safe, by contrast, to look in /usr/local -- that's where things are put for everyone to use.

**Comment by mahrud** [comment]
But setting LDFLAGS and CPPFLAGS alone doesn't work. See the error with factory not finding flint and ntl: https://github.com/Macaulay2/M2/runs/865379589

**Comment by DanGrayson** [comment]
I looked at it and had no clue about why factory didn't find ntl, so I don't get your point.

**Comment by mahrud** [comment]
My point is that simply passing LDFLAGS and CPPFLAGS does not suffice for
telling autotools where to find brew libraries.

**Comment by DanGrayson** [comment]
> My point is that simply passing LDFLAGS and CPPFLAGS does not suffice for telling autotools where to find brew libraries.

Why not?

**Comment by mahrud** [comment]
> Why not?

Because it failed when I tried it! Something is broken, such that if I provide the right LDFLAGS:
```
configure: using LDFLAGS           =  ... -L/home/linuxbrew/.linuxbrew/lib ...
```
And CPPFLAGS:
```
configure: using CPPFLAGS          = ... -I/usr/include -I/home/linuxbrew/.linuxbrew/include ...
```
Then M2 can find ntl and flint install via brew:
```
configure: using BUILDLIBLIST  =  gc readline factory mpsolve frobby cddlib gtest
```
But when it tries to compile factory, it fails:
```
config.status: executing config.h commands
config.status: creating 'config.h' - prefix '' for '_config.h' defines
config.status: executing libtool commands
+ set -x
+ grep ^.define HAVE_NTL 1 _config.h
../Makefile.library:180: recipe for target '.configured-4.1.1' failed
gmake[2]: Leaving directory '/home/runner/work/M2/M2/M2/BUILD/build/libraries/factory'
Makefile:7: recipe for target 'all-in-factory' failed
```
What do you not get about my point?

If you want the full log, see the link to the github build above. You can find the commit number to run it locally, or click "re-run jobs" to run it again and get the artifacts.

And this is not the only issue; bdw-gc and cddlib were also installed via brew, but autotools did failed to detect them.

**Comment by DanGrayson** [comment]
Yes, something is broken, but that doesn't allow one to conclude that "passing LDFLAGS and CPPFLAGS does not suffice for telling autotools where to find brew libraries."  That's a logical leap.

A library such as NTL consists of two parts: the include files that contain the declarations, and the object files that contain the code.  There's nothing else.

If the factory configure script fails to detect NTL, then it's for some reason.  We'd have to look at the config.log file made by factory's configure script to figure it out.

**Comment by mahrud** [comment]
Sure, I interpret what I said as "passing those variables is not enough because more needs to happen based on those variables on our end". Consider what cmake does:
- user passes a variable ``-DCMAKE_SYSTEM_PREFIX_PATH="/usr;`brew --prefix`"``
- `cmake/check-libraries.cmake` calls `find_package(Flint)`, which runs `cmake/FindFlint.cmake` in our repository
  - that script first looks for a system-wide `FlindModule.cmake`
  - if not found, runs `find_path` to find the header directory and `find_library` to find the libraries
  - those commands look under every standard directory rooted at the given `CMAKE_SYSTEM_PREFIX_PATH` and if the version of the flint is good enough, define three parameters:
  - `FLINT_ROOT`, `FLINT_INCLUDE_DIR`, `FLINT_LIBRARIES`
- same situation happens with NTL, Factory, etc.
- if Factory isn't found, `cmake/build-libraries.cmake` has the instructions for how to build it, and in particular it passes `--with-ntl=${NTL_ROOT} --with-flint=${FLINT_ROOT}` to the configure script.

In comparison, `libraries/factory/Makefile.in` only sets `--with-ntl` and `--with-flint` to the `usr- host` path when we build the libraries, and otherwise just passes LDFLAGS and CPPFLAGS. But factory doesn't use those flags for finding ntl and flint, which brings me to say that passing the standard flags doesn't suffice!

All that aside, even gc and cddlib aren't found, which isn't the fault of another library anymore.

**Comment by DanGrayson** [comment]
> But factory doesn't use those flags for finding ntl and flint,

Under Mac OS X, when not building NTL, I pass these flags, among others to factory's configure script:
```
CPPFLAGS=-I/Users/dan/src/M2/M2.git/M2/include -I/Users/dan/src/M2/M2.git/M2/BUILD/dan/builds.tmp/gallium-master/include -I/Users/dan/src/M2/M2.git/M2/BUILD/dan/builds.tmp/gallium-master/usr-host/include -I/Users/dan/src/M2/M2.git/M2/BUILD/dan/builds.tmp/gallium-master/usr-host/include/cdd  -I/Users/dan/src/M2/M2.git/M2/submodules/memtailor/src  -I/Users/dan/src/M2/M2.git/M2/submodules/mathic/src  -I/Users/dan/src/M2/M2.git/M2/submodules/mathicgb/src  -I/Users/dan/src/M2/M2.git/M2/submodules/fflas_ffpack/src  -I/Users/dan/src/M2/M2.git/M2/submodules/givaro/src -isystem /usr/local/Cellar/libatomic_ops/7.6.10/include -isystem /usr/local/Cellar/bdw-gc/8.0.4/include  -I/usr/include -I/usr/local/include -DNDEBUG -I/usr/local/Cellar/eigen/3.3.7/include/eigen3
LDFLAGS=-L/Users/dan/src/M2/M2.git/M2/BUILD/dan/builds.tmp/gallium-master/usr-host/lib  -L/Users/dan/src/M2/M2.git/M2/BUILD/dan/builds.tmp/gallium-master/submodules/memtailor/.libs  -L/Users/dan/src/M2/M2.git/M2/BUILD/dan/builds.tmp/gallium-master/submodules/mathic/.libs  -L/Users/dan/src/M2/M2.git/M2/BUILD/dan/builds.tmp/gallium-master/submodules/mathicgb/.libs -L/usr/lib -L/usr/local/lib -g3 -headerpad_max_install_names
```

And then it uses these command lines to check for ntl:
```
g++ -o conftest -std=gnu++14 -g3 -O2  -Wno-mismatched-tags -w -Wno-deprecated-register -pipe -fno-common -g0 -O3 -Wno-unused-function -Wno-trigraphs -Wno-unused-parameter -Wunknown-pragmas -Wno-unused-variable -fomit-frame-pointer -fwrapv -fvisibility=default -finline-functions -fno-exceptions -fno-threadsafe-statics -funroll-loops -fno-delete-null-pointer-checks -fno-rtti -Qunused-arguments -I/usr/local/include  -I/Users/dan/src/M2/M2.git/M2/include -I/Users/dan/src/M2/M2.git/M2/BUILD/dan/builds.tmp/gallium-master/include -I/Users/dan/src/M2/M2.git/M2/BUILD/dan/builds.tmp/gallium-master/usr-host/include -I/Users/dan/src/M2/M2.git/M2/BUILD/dan/builds.tmp/gallium-master/usr-host/include/cdd  -I/Users/dan/src/M2/M2.git/M2/submodules/memtailor/src  -I/Users/dan/src/M2/M2.git/M2/submodules/mathic/src  -I/Users/dan/src/M2/M2.git/M2/submodules/mathicgb/src  -I/Users/dan/src/M2/M2.git/M2/submodules/fflas_ffpack/src  -I/Users/dan/src/M2/M2.git/M2/submodules/givaro/src -isystem /usr/local/Cellar/libatomic_ops/7.6.10/include -isystem /usr/local/Cellar/bdw-gc/8.0.4/include  -I/usr/include -I/usr/local/include -DNDEBUG -I/usr/local/Cellar/eigen/3.3.7/include/eigen3 -Dmpz_div_2exp=mpz_fdiv_q_2exp -Dmpz_div_ui=mpz_fdiv_q_ui -Dmpz_div=mpz_fdiv_q -L/Users/dan/src/M2/M2.git/M2/BUILD/dan/builds.tmp/gallium-master/usr-host/lib  -L/Users/dan/src/M2/M2.git/M2/BUILD/dan/builds.tmp/gallium-master/submodules/memtailor/.libs  -L/Users/dan/src/M2/M2.git/M2/BUILD/dan/builds.tmp/gallium-master/submodules/mathic/.libs  -L/Users/dan/src/M2/M2.git/M2/BUILD/dan/builds.tmp/gallium-master/submodules/mathicgb/.libs -L/usr/lib -L/usr/local/lib -g3 -headerpad_max_install_names -pipe -fno-common -g0 -O3 -Wno-unused-function -Wno-trigraphs -Wno-unused-parameter -Wunknown-pragmas -Wno-unused-variable -fomit-frame-pointer -fwrapv -fvisibility=default -finline-functions -fno-exceptions -fno-threadsafe-statics -funroll-loops -fno-delete-null-pointer-checks -Qunused-arguments conftest.cpp -lm  -L/usr/local/lib -lntl -lgmp
g++ -o conftest -std=gnu++14 -g3 -O2  -Wno-mismatched-tags -w -Wno-deprecated-register -pipe -fno-common -g0 -O3 -Wno-unused-function -Wno-trigraphs -Wno-unused-parameter -Wunknown-pragmas -Wno-unused-variable -fomit-frame-pointer -fwrapv -fvisibility=default -finline-functions -fno-exceptions -fno-threadsafe-statics -funroll-loops -fno-delete-null-pointer-checks -fno-rtti -Qunused-arguments -I/usr/local/include  -I/Users/dan/src/M2/M2.git/M2/include -I/Users/dan/src/M2/M2.git/M2/BUILD/dan/builds.tmp/gallium-master/include -I/Users/dan/src/M2/M2.git/M2/BUILD/dan/builds.tmp/gallium-master/usr-host/include -I/Users/dan/src/M2/M2.git/M2/BUILD/dan/builds.tmp/gallium-master/usr-host/include/cdd  -I/Users/dan/src/M2/M2.git/M2/submodules/memtailor/src  -I/Users/dan/src/M2/M2.git/M2/submodules/mathic/src  -I/Users/dan/src/M2/M2.git/M2/submodules/mathicgb/src  -I/Users/dan/src/M2/M2.git/M2/submodules/fflas_ffpack/src  -I/Users/dan/src/M2/M2.git/M2/submodules/givaro/src -isystem /usr/local/Cellar/libatomic_ops/7.6.10/include -isystem /usr/local/Cellar/bdw-gc/8.0.4/include  -I/usr/include -I/usr/local/include -DNDEBUG -I/usr/local/Cellar/eigen/3.3.7/include/eigen3 -Dmpz_div_2exp=mpz_fdiv_q_2exp -Dmpz_div_ui=mpz_fdiv_q_ui -Dmpz_div=mpz_fdiv_q -L/Users/dan/src/M2/M2.git/M2/BUILD/dan/builds.tmp/gallium-master/usr-host/lib  -L/Users/dan/src/M2/M2.git/M2/BUILD/dan/builds.tmp/gallium-master/submodules/memtailor/.libs  -L/Users/dan/src/M2/M2.git/M2/BUILD/dan/builds.tmp/gallium-master/submodules/mathic/.libs  -L/Users/dan/src/M2/M2.git/M2/BUILD/dan/builds.tmp/gallium-master/submodules/mathicgb/.libs -L/usr/lib -L/usr/local/lib -g3 -headerpad_max_install_names -pipe -fno-common -g0 -O3 -Wno-unused-function -Wno-trigraphs -Wno-unused-parameter -Wunknown-pragmas -Wno-unused-variable -fomit-frame-pointer -fwrapv -fvisibility=default -finline-functions -fno-exceptions -fno-threadsafe-statics -funroll-loops -fno-delete-null-pointer-checks -Qunused-arguments conftest.cpp -lm  -L/usr/local/lib -lntl -lgmp
```

So factory does use those flags.

**Comment by DanGrayson** [comment]
The factory library has an autoconf configure script, and such scripts always pay attention to CPPFLAGS and LDFLAGS.

**Comment by mahrud** [comment]
This is your writing:
```
# Factory's configure script doesn't find libraries using the standard autoconf macros (sigh), so
# it is necessary to examine the log (in the code below) to ensure that flint and ntl are both found.
```

**Comment by DanGrayson** [comment]
That's true, too.  It probably means that the configure script doesn't *insist* on finding ntl.  It doesn't give an error if it's not found.   That's why we grep for "define HAVE_NTL 1" afterwards.

But autoconf configure scripts do pay attention to CPPFLAGS and LDFLAGS, and so does this one.

**Comment by mahrud** [comment]
> So factory does use those flags.

You could also just look into the factory scripts, in `m4/ntl-check.m4` and `m4/flint-check.m4` to know that I'm not lying and they really don't use LDFLAGS.

Are you saying it works for you so this isn't an issue? If so then feel free to close this issue as won't fix.

**Comment by DanGrayson** [comment]
> > So factory does use those flags.
> 
> You could also just look into the factory scripts, in `m4/ntl-check.m4` and `m4/flint-check.m4` to know that I'm not lying and they really don't use LDFLAGS.

Not explicitly, but those files use macros AC_TRY_LINK and AC_TRY_RUN, which use LDFLAGS and CPPFLAGS.

> 
> Are you saying it works for you so this isn't an issue? If so then feel free to close this issue as won't fix.

I haven't seen factory fail to find ntl in a long time, but if it's happening for you, we should debug it.

**Comment by mahrud** [comment]
> I haven't seen factory fail to find ntl in a long time, but if it's happening for you, we should debug it.

This whole issue, starting from the beginning, has been me trying to convince you that this is happening to me:

### bug 1: factory fails to find ntl and flint installed via brew
Steps to reproduce:
- use ubuntu
- install brew (the command on brew.sh works on linux too)
- brew install ntl flint
- build M2 with autotools, giving it CPPFLAGS and LDFLAGS based on brew --prefix

### bug 2: autotools fails to find gc and cddlib installed via brew
Steps to reproduce:
- use ubuntu
- install brew
- brew install cddlib bdw-gc
- build M2 with autotools

### bug 2.5: if you force autotools to find gc via brew, it will eventually crash
- here is the build log: https://github.com/Macaulay2/M2/runs/874911997
- here is the config log and example error file: https://github.com/Macaulay2/M2/suites/920214896/artifacts/11243506
- Here is the stacktrace:
```m2

i1 : R = CC[x_(1,1)..x_(3,5)];

i2 : F = (minors(3, genericMatrix(R, 3, 5)))_*;

i3 : W = pseudoWitnessSet(F, ideal 0_R)
-- SIGSEGV
-* stack trace, pid: 115838
 0# 0x000055F07BFAECA7 in /home/runner/work/M2/M2/M2/BUILD/build/usr-dist/x86_64-Linux-Ubuntu-18.04/bin/M2-binary
 1# 0x000055F07BFAEE6A in /home/runner/work/M2/M2/M2/BUILD/build/usr-dist/x86_64-Linux-Ubuntu-18.04/bin/M2-binary
 2# 0x00007F85D6C39FD0 in /lib/x86_64-linux-gnu/libc.so.6
 3# 0x00007F85D6D89D8F in /lib/x86_64-linux-gnu/libc.so.6
 4# 0x000055F07C0CA5DF in /home/runner/work/M2/M2/M2/BUILD/build/usr-dist/x86_64-Linux-Ubuntu-18.04/bin/M2-binary
 5# 0x000055F07C0CA268 in /home/runner/work/M2/M2/M2/BUILD/build/usr-dist/x86_64-Linux-Ubuntu-18.04/bin/M2-binary
 6# 0x000055F07C00CBFD in /home/runner/work/M2/M2/M2/BUILD/build/usr-dist/x86_64-Linux-Ubuntu-18.04/bin/M2-binary
 7# 0x000055F07BFDB960 in /home/runner/work/M2/M2/M2/BUILD/build/usr-dist/x86_64-Linux-Ubuntu-18.04/bin/M2-binary
...
106# 0x000055F07C2B3799 in /home/runner/work/M2/M2/M2/BUILD/build/usr-dist/x86_64-Linux-Ubuntu-18.04/bin/M2-binary
107# GC_inner_start_routine in /home/linuxbrew/.linuxbrew/lib/libgc.so.1
108# GC_call_with_stack_base in /home/linuxbrew/.linuxbrew/lib/libgc.so.1
109# 0x00007F85D75CB6DB in /lib/x86_64-linux-gnu/libpthread.so.0
110# clone in /lib/x86_64-linux-gnu/libc.so.6
-- end stack trace *-
```
Not that `libgc.so.1` is the brew installation.

**Comment by DanGrayson** [comment]
Concerning bug 1, I looked again at https://github.com/Macaulay2/M2/runs/865379589, which you pointed me at above, in the ubuntu autotools gcc9 build.  

You seem to have modified the configure script to use homebrew's file automatically, which is not a good idea, as I have said:
```
2020-07-13T13:49:23.7929722Z configure: configuring Macaulay2 version 1.16.0.1
2020-07-13T13:49:23.7971294Z relevant environment variable values, if any:
2020-07-13T13:49:23.7972578Z    CC = gcc-9
2020-07-13T13:49:23.7973224Z    CXX = g++-9
2020-07-13T13:49:23.8089857Z checking whether Homebrew is available... yes, adding /home/linuxbrew/.linuxbrew to header and library search paths
```

In any case, the top level configure  script finds ntl (even though it 
```
2020-07-13T13:49:36.8173319Z checking NTL/version.h usability... yes
2020-07-13T13:49:36.8270881Z checking NTL/version.h presence... yes
2020-07-13T13:49:36.8271661Z checking for NTL/version.h... yes
2020-07-13T13:49:37.4587900Z checking whether libntl is present and usable... yes
```

The factory configure script does not:
```
2020-07-13T13:50:58.8166871Z configure: WARNING: Unable to find NTL (which is strongly recommended) on your machine: please use --with-ntl=PATH_TO_DIR_CONTAINING_LIB_AND_INCLUDE (see also ./configure --help if you do not understand what we are talking about)
2020-07-13T13:50:58.8167245Z checking for library containing sem_wait... -lpthread
2020-07-13T13:50:58.8167656Z checking for NTL >= 5.0... not found
```

Here is the factory configure command line:
```
2020-07-13T13:50:53.1025925Z + ./configure --prefix=/home/runner/work/M2/M2/M2/BUILD/build/usr-host AR=ar AS=as DLLTOOL=false OBJDUMP=objdump STRIP=strip CXXFLAGS=-std=gnu++14 -g3 -O2  -w -Wno-deprecated-register CFLAGS=-std=gnu11 -g3 -O2 -w -Wimplicit -Werror FFLAGS=-O2 FCFLAGS=-O2 TARGET_ARCH= CPPFLAGS=-I/home/runner/work/M2/M2/M2/BUILD/build/../../include -I/home/runner/work/M2/M2/M2/BUILD/build/include -I/home/runner/work/M2/M2/M2/BUILD/build/usr-host/include -I/home/runner/work/M2/M2/M2/BUILD/build/usr-host/include/cdd  -I/home/runner/work/M2/M2/M2/BUILD/build/../../submodules/memtailor/src  -I/home/runner/work/M2/M2/M2/BUILD/build/../../submodules/mathic/src  -I/home/runner/work/M2/M2/M2/BUILD/build/../../submodules/mathicgb/src  -I/home/runner/work/M2/M2/M2/BUILD/build/../../submodules/fflas_ffpack/src  -I/home/runner/work/M2/M2/M2/BUILD/build/../../submodules/givaro/src -isystem /usr/include/libxml2 -isystem /usr/include/x86_64-linux-gnu -isystem /usr/include/x86_64-linux-gnu   -I/usr/include -I/home/linuxbrew/.linuxbrew/include -DNDEBUG -I/usr/include/eigen3 -Dmpz_div_2exp=mpz_fdiv_q_2exp -Dmpz_div_ui=mpz_fdiv_q_ui -Dmpz_div=mpz_fdiv_q CC=gcc-9 CXX=g++-9 LDFLAGS=-L/home/runner/work/M2/M2/M2/BUILD/build/usr-host/lib  -L/home/runner/work/M2/M2/M2/BUILD/build/submodules/memtailor/.libs  -L/home/runner/work/M2/M2/M2/BUILD/build/submodules/mathic/.libs  -L/home/runner/work/M2/M2/M2/BUILD/build/submodules/mathicgb/.libs -L/usr/lib -L/home/linuxbrew/.linuxbrew/lib -g3 LOADLIBES= LDLIBS= --disable-omalloc --enable-streamio --includedir=/home/runner/work/M2/M2/M2/BUILD/build/usr-host/include/ --disable-shared --without-Singular --cache-file=/dev/null
```
The homebrew directories are present.

It's rather unlikely that the version number on the homebrew ntl package is less than 5.0, since it's at 11.4.3 on the Mac homebrew.  Also, it seems the error would have been displayed as "Sorry, your NTL version is too old or not configured with NTL_GMP_LIP=on. Disabling." if the version number were too old.

So, as I said yesterday, we'd have to look at the config.log file made by factory's configure script to figure it out.   There we would see the exact compiler command lines and compiler source files that were compiled to find ntl, together with the text of the error messages from the compiler.

I see you have some more recent runs where such log files are provided as an artifact, but in those, ntl was found by factory.  Can you get one that reflects this bug?

Or we have to reproduce this on one of our own machines.

**Comment by DanGrayson** [comment]
PS: I see Ubuntu 20.04 is available as runner on github actions: https://docs.github.com/en/actions/reference/virtual-environments-for-github-hosted-runners#supported-runners-and-hardware-resources

Let's switch to that.

**Comment by DanGrayson** [comment]
> Concerning bug 1, I looked again at https://github.com/Macaulay2/M2/runs/865379589, which you pointed me at above, in the ubuntu autotools gcc9 build.
> 
> You seem to have modified the configure script to use homebrew's files automatically, which is not a good idea, as I have said:
> 
> ```
> 2020-07-13T13:49:23.7929722Z configure: configuring Macaulay2 version 1.16.0.1
> 2020-07-13T13:49:23.7971294Z relevant environment variable values, if any:
> 2020-07-13T13:49:23.7972578Z    CC = gcc-9
> 2020-07-13T13:49:23.7973224Z    CXX = g++-9
> 2020-07-13T13:49:23.8089857Z checking whether Homebrew is available... yes, adding /home/linuxbrew/.linuxbrew to header and library search paths
> ```
> 
> In any case, the top level configure script finds ntl :
> 
> ```
> 2020-07-13T13:49:36.8173319Z checking NTL/version.h usability... yes
> 2020-07-13T13:49:36.8270881Z checking NTL/version.h presence... yes
> 2020-07-13T13:49:36.8271661Z checking for NTL/version.h... yes
> 2020-07-13T13:49:37.4587900Z checking whether libntl is present and usable... yes
> ```
> 
> The factory configure script does not:
> 
> ```
> 2020-07-13T13:50:58.8166871Z configure: WARNING: Unable to find NTL (which is strongly recommended) on your machine: please use --with-ntl=PATH_TO_DIR_CONTAINING_LIB_AND_INCLUDE (see also ./configure --help if you do not understand what we are talking about)
> 2020-07-13T13:50:58.8167245Z checking for library containing sem_wait... -lpthread
> 2020-07-13T13:50:58.8167656Z checking for NTL >= 5.0... not found
> ```
> 
> Here is the factory configure command line:
> 
> ```
> 2020-07-13T13:50:53.1025925Z + ./configure --prefix=/home/runner/work/M2/M2/M2/BUILD/build/usr-host AR=ar AS=as DLLTOOL=false OBJDUMP=objdump STRIP=strip CXXFLAGS=-std=gnu++14 -g3 -O2  -w -Wno-deprecated-register CFLAGS=-std=gnu11 -g3 -O2 -w -Wimplicit -Werror FFLAGS=-O2 FCFLAGS=-O2 TARGET_ARCH= CPPFLAGS=-I/home/runner/work/M2/M2/M2/BUILD/build/../../include -I/home/runner/work/M2/M2/M2/BUILD/build/include -I/home/runner/work/M2/M2/M2/BUILD/build/usr-host/include -I/home/runner/work/M2/M2/M2/BUILD/build/usr-host/include/cdd  -I/home/runner/work/M2/M2/M2/BUILD/build/../../submodules/memtailor/src  -I/home/runner/work/M2/M2/M2/BUILD/build/../../submodules/mathic/src  -I/home/runner/work/M2/M2/M2/BUILD/build/../../submodules/mathicgb/src  -I/home/runner/work/M2/M2/M2/BUILD/build/../../submodules/fflas_ffpack/src  -I/home/runner/work/M2/M2/M2/BUILD/build/../../submodules/givaro/src -isystem /usr/include/libxml2 -isystem /usr/include/x86_64-linux-gnu -isystem /usr/include/x86_64-linux-gnu   -I/usr/include -I/home/linuxbrew/.linuxbrew/include -DNDEBUG -I/usr/include/eigen3 -Dmpz_div_2exp=mpz_fdiv_q_2exp -Dmpz_div_ui=mpz_fdiv_q_ui -Dmpz_div=mpz_fdiv_q CC=gcc-9 CXX=g++-9 LDFLAGS=-L/home/runner/work/M2/M2/M2/BUILD/build/usr-host/lib  -L/home/runner/work/M2/M2/M2/BUILD/build/submodules/memtailor/.libs  -L/home/runner/work/M2/M2/M2/BUILD/build/submodules/mathic/.libs  -L/home/runner/work/M2/M2/M2/BUILD/build/submodules/mathicgb/.libs -L/usr/lib -L/home/linuxbrew/.linuxbrew/lib -g3 LOADLIBES= LDLIBS= --disable-omalloc --enable-streamio --includedir=/home/runner/work/M2/M2/M2/BUILD/build/usr-host/include/ --disable-shared --without-Singular --cache-file=/dev/null
> ```
> 
> The homebrew directories are present.
> 
> It's rather unlikely that the version number on the homebrew ntl package is less than 5.0, since it's at 11.4.3 on the Mac homebrew. Also, it seems the error would have been displayed as "Sorry, your NTL version is too old or not configured with NTL_GMP_LIP=on. Disabling." if the version number were too old.
> 
> So, as I said yesterday, we'd have to look at the config.log file made by factory's configure script to figure it out. There we would see the exact compiler command lines and compiler source files that were compiled to find ntl, together with the text of the error messages from the compiler.
> 
> I see you have some more recent runs where such log files are provided as an artifact, but in those, ntl was found by factory. Can you get one that reflects this bug?
> 
> Or we have to reproduce this on one of our own machines.

**Comment by DanGrayson** [comment]
I managed to reproduce it at home and to look at the log file.  I owe you an apology -- you were right about the macro in `factory/build/m4/ntl-check.m4` needing something more the find ntl!  The point is that in this code:
```
for NTL_HOME in ${NTL_HOME_PATH}
 do
if test -r "$NTL_HOME/include/NTL/ZZ.h"; then
...
```
it insists on being able to find NTL/ZZ.h on its idea of the path, rather than on the compiler's idea of the path.

I'll prepare a patch.

**Comment by DanGrayson** [comment]
Try this: https://github.com/DanGrayson/M2/commit/b3d9952615e59bdac5db245e4733d7bc0731b87a

**Comment by mahrud** [comment]
The scripts you patched have changed significantly in Factory v4.1.3, so perhaps it would be a better idea to fix #1168 first and see if the problem is resolved. It's possible that the Factory built by the CMake build doesn't have a problem finding ntl and flint because it is version 4.1.3.

**Comment by DanGrayson** [comment]
I just checked, and the factory 4.1.3 configure script still has the same misfeature in it.

When we upgrade to 4.1.3 I'll just update the patch file.

Tests do show that my commit above does fix it.

**Comment by mahrud** [comment]
I don't like patches that we can't eventually submit to the upstream (I can't imagine them be interested in completely removing `--with-gmp`, `--with-ntl`, and `--with-flint` options), but if it works for you then sure.

Any ideas about these two?

- [ ] bug 2: autotools fails to find gc and cddlib installed via brew
- [ ] bug 2.5: if you force autotools to find gc via brew, it will eventually crash

**Comment by DanGrayson** [comment]
> Any ideas about these two?
> 
> * [ ]  bug 2: autotools fails to find gc and cddlib installed via brew

Does this refer to the top level configure script?

> * [ ]  bug 2.5: if you force autotools to find gc via brew, it will eventually crash

What does "force" mean?

**Comment by mahrud** [comment]
> I think I could convince them.

Isn't `--with-X` a standard autotools pattern?

> > * [ ]   bug 2: autotools fails to find gc and cddlib installed via brew
> 
> Does this refer to the top level configure script?

Yes.

**Comment by DanGrayson** [comment]
> > I think I could convince them.
> 
> Isn't `--with-X` a standard autotools pattern?

Sure, but they should implement it better.

**Comment by DanGrayson** [comment]
> > > I think I could convince them.
> > 
> > 
> > Isn't `--with-X` a standard autotools pattern?
> 
> Sure, but they should implement it better.

... but you make good point -- my patch doesn't implement it for them.  What `--with-ntl=foo` should do
is to add `-Lfoo/lib` to LDFLAGS and add `-Ifoo/include` to CPPFLAGS.  That way `--with-ntl=foo` would not
be mandatory.

**Comment by mahrud** [comment]
That would be ideal. One thing that I'm not sure how to approach is whether you'd need to take the architecture into account for systems like ubuntu where you have `/usr/lib/x86-64...` and `/usr/include/x86-64...` as the main directories containing the libraries and headers or `/usr/lib64` on fedora :/

**Comment by DanGrayson** [comment]
No need to adapt that approach for that case, as simply setting LDFLAGS and CPPFLAGS appropriately would take care of it.

**Comment by mahrud** [comment]
> Try this: [DanGrayson@b3d9952](https://github.com/DanGrayson/M2/commit/b3d9952615e59bdac5db245e4733d7bc0731b87a)

Was this ever put into development?

**Comment by DanGrayson** [comment]
> > Try this: [DanGrayson@b3d9952](https://github.com/DanGrayson/M2/commit/b3d9952615e59bdac5db245e4733d7bc0731b87a)
> 
> Was this ever put into development?

Not by me.
