### ISSUE TITLE
Incorrect STL merging by ld

### ISSUE THREAD

**Issue by ochachacha** [Macaulay2/M2#1414]
Dear all,

I made another attempt at making this thing run with Cygwin and it is mostly working.
I'm currently running through the packages and so far only "SimplicialComplexes" is reporting error.
(I'm too tired to debug for it. Maybe someone can go take a look...)
During the process I've discovered a problem, so I'd like to make a report.

**Background**
When ld tries to link all components together, as a standard behavior it will try to merge all the STL template codes; more specifically, it will gather all implementations (not import stubs--actually pieces of STL, which are mostly inline functions) of the same template function, choose one of them, and link everyone to the said implementation / inline it into everyone. How this is done is completely linker-specific; C++ has no standard for it.

**Specific Problem**
1. Some of our code is GC-managed (the main engine), some isn't (mathicgb, for instance).
2. The template code may involve memory allocation and release (an instance would be vector::_M_default_append, which allocates for more memory when the vector is not long enough).
3. Therefore, GC-managed code and non-managed code will have incompatible template implementations (passing a GC-managed pointer to the native "delete" is going to result int SIGABRT, and I believe vice versa).
[Note: If all such template codes are already inline, we would be okay, because the linker wouldn't try to de-duplicate assembly code (as far as I can tell). However, some of those functions remain as separated functions in the .o files.]
4. During the final linking, the ld implementation on cygwin will merge all implementations with the same function name (as long as that info is available), resulting in GC-managed template code being linked into non-managed code.

The specific instance I observed is that reduceToEchelonForm in "mathicgb/F4MatrixReducer.cpp" (line 398) in mathicgb will crash because it's calling the GC-managed vector::_M_default_append, but later releases that vector using the default delete.

**Solution**
My current solution is to manually rename those STL functions inside the static libraries using objcopy (or you can strip them away, same thing). This is obviously a hack and it produces larger executable (due to the presence of multiple copies of the STL codes).
In general, there is no way to control how ld does the merging, so I actually can't think of an elegant way around this.

**Comment by DanGrayson** [comment]
Hi.  Are you willing to reveal who you are?

What do you mean by "making this thing run with Cygwin"?  Are you trying to compile Macaulay2 under cygwin?  We gave up on that long ago, and now that Windows 10 offers ubuntu, it doesn't seem necessary.

What do you mean by "Id"?

What do you mean by "merging"?

What do you mean by "the static libraries"?  Most of our libraries come in both dynamic and static forms.

@mikestillman -- you may want to look at the line number mentioned above in mathicgb to see if we're mingling gc-pointers with malloc-pointers.

**Comment by ochachacha** [comment]
Hi there,

I'm just a student working in related area. I have no problem signing my real name if that's strictly necessary, but otherwise usually I'd prefer a bit anonymity...Just let me know if you really need that info.

1. Yes compiling it under Cygwin. It's running on my computer right now without major problem (it has gone through all of the packages and is failing on only two of them).

2. By "ld" I mean the linker.

3. By "merging" I mean that the linker's action of combining multiple copies of the STL code into a single copy. For instance, see this StackOverflow question: https://stackoverflow.com/questions/38662972/does-the-linker-usually-optimize-away-duplicated-code-from-different-c-templat

4. By static libraries I mean things under "submodules", which become .a (static library) files and ultimately get linked to the main program during the final stage of compiling.

**Comment by DanGrayson** [comment]
Thanks for the further info, and congratulations on figuring out the cause of the crash!  That must have been hard.

But what I don't understand is how a template function, instantiated in two different ways, could result in code with the same (mangled) function names.  Isn't everything relevant included in the function name?

**Comment by ochachacha** [comment]
> Thanks for the further info, and congratulations on figuring out the cause of the crash! That must have been hard.
> 
> But what I don't understand is how a template function, instantiated in two different ways, could result in code with the same (mangled) function names. Isn't everything relevant included in the function name?

Thank you! :) It took a while but was worth it.

The mangled name only keeps track of the type signature and not what's actually in there. Here's a more detailed explanation on what's going on:

Let's say we have the following function:
```
void F()
{
    vector<A> x;
    const int NEWSIZE = 10;
    x.resize(NEWSIZE);
}
```
The compiler will translate it into assembly code doing something like:
```
void F()
{
generate_x(); // note that the memory for individual A elements are not allocated here, because no need yet.
// ---start to expand x.resize as it's inline code in stl_vector.h---
if (NEWSIZE > x.size())
{
    vector<A>_M_default_append(NEWSIZE - size()); // this is a function call
}
else if (NEWSIZE < x.size()) {
 // do other things
}
// ---end of expanding x.resize---
delete x; // auto-generated code to delete the local object
}
```
At the same time, the following code is also kept in the .o file, and the function call above calls into this function:
```
auto vector<A>_M_default_append(int size)
{
  elements = new A[size]; // the "new" happens here
// other things...
}
```

Now, suppose we are compiling without GC.
These two functions (now in assembly code) both survive into the .o file. Let's say they are put into "mathicgb.o".

------

Suppose, somewhere else in GC-managed code (e.g. in the main engine), we had another code that also uses vector<A> in a similar way. But this time, since "new" and "delete" have been reloaded, the compiler generates the following assembly code:
```
void G()
{
generate_x();
if (NEWSIZE > x.size())
{
    vector<A>_M_default_append(NEWSIZE - size());
}
else if (NEWSIZE < x.size()) {
 // do other things
}
// ---end of expanding x.resize---
GC_FREE(x); // "delete" reloaded
}
auto vector<A>_M_default_append(int size) // note we have same signature as above
{
  elements = GC_malloc_uncollectable(sizeof(A) * size); // "new" reloaded
// other things...
}
```
And these two functions got put into, say, main_engine.o.

------

Fiasco occurs when we try to link main_engine.o with mathicgb.o. The linker sees two copies of vector<A>_M_default_append. Because it's supposed to be the same code, the linker only keeps one copy--in this case it kept the "main_engine" copy.
This results in the following incorrect code in the final assembly:
```
void F()
{
generate_x();
if (NEWSIZE > x.size())
{
    vector<A>_M_default_append(NEWSIZE - size()); // Oh no
}
else if (NEWSIZE < x.size()) {
 // do other things
}
delete x; // CRASH
}
void G()
{
generate_x();
if (NEWSIZE > x.size())
{
    vector<A>_M_default_append(NEWSIZE - size());
}
else if (NEWSIZE < x.size()) {
 // do other things
}
// ---end of expanding x.resize---
GC_FREE(x);
}
auto vector<A>_M_default_append(int size)
{
  elements = GC_malloc_uncollectable(sizeof(A) * size);
}
```

**Comment by mikestillman** [comment]
I'll take a look.  I was under the impression that nothing from mathic or mathicgb would interact with the garbage collector.

**Comment by mikestillman** [comment]
What version of M2 are you working with with cygwin, the latest master or development branch, or 1.16 ,or ...?

**Comment by ochachacha** [comment]
> What version of M2 are you working with with cygwin, the latest master or development branch, or 1.16 ,or ...?

1.16.0.1 (I just checked out the master branch)

**Comment by mikestillman** [comment]
I'm a bit confused by this.  We are no longer (since 1.16) changing global new, delete.  So the versions of these two pieces of code should be the same?  I must be missing some subtlety, any suggestions?

**Comment by ochachacha** [comment]
> I'm a bit confused by this. We are no longer (since 1.16) changing global new, delete. So the versions of these two pieces of code should be the same? I must be missing some subtlety, any suggestions?

The new/delete are replaced (as inline functions) whenever you include the gc/gc_cpp.h header file (the inclusion is in turn from gc-include.h).

**Comment by mikestillman** [comment]
Thanks, @ochachacha .  I had forgotten about that.  @DanGrayson This means we cannot include that file, gc/gc_cpp.h, which defines 2 base classes we want.  Very annoying!  However, we can define these ourselves, I guess, even lifting the code from that include file if needed.

**Comment by DanGrayson** [comment]
Yes, let's add that file to our source code with those two definitions commented out.

Shall I do it?

**Comment by DanGrayson** [comment]
By the way, what do inline function declarations have to do with errors at link-time?

**Comment by mikestillman** [comment]
@DanGrayson Yes, that sounds good, please make that change.  I'm still a bit confused about which versions of global new the file is actually defining.  Also, in the past I have had trouble with this file in debug mode (doesn't compile correctly, or maybe it was when I actually tried to use `gc_cleanup`).

As for inline declarations: if the inline declaration is available, it (probably) uses it, and if not, it uses the function version instead.  If they are different, and the compiler decides to inline one use, but not another, for some reason, I would expect that would be bad...

**Comment by mikestillman** [comment]
Is that an error at link time?  Instead, I think that is when the bug manifests itself.

**Comment by ochachacha** [comment]
> @DanGrayson Yes, that sounds good, please make that change. I'm still a bit confused about which versions of global new the file is actually defining. Also, in the past I have had trouble with this file in debug mode (doesn't compile correctly, or maybe it was when I actually tried to use `gc_cleanup`).
> 
> As for inline declarations: if the inline declaration is available, it (probably) uses it, and if not, it uses the function version instead. If they are different, and the compiler decides to inline one use, but not another, for some reason, I would expect that would be bad...

In principle this wouldn't cause trouble if the computer is treating source code as-is. The problem kicks in when the linker tries to save space and rerouted two calls to standard STL functions (which are actually pointing at different implementations now because one of them has new/delete replaced). There is no specified behavior on how this space-saving should occur, so things happen at the linker's mercy. Please see my comment above for more details.

**Comment by DanGrayson** [comment]
> Is that an error at link time? Instead, I think that is when the bug manifests itself.

I guess so, because the title of this thread is "Incorrect STL merging by ld"

**Comment by DanGrayson** [comment]
It appears that only if __CYGWIN__ is defined as a preprocessor macro does gc_cpp.h define those global inline functions.

@ochachacha -- could you experiment and see whether `#undef __CYGWIN__` fixes it for you?  (The file is also included twice in `Macaulay2/system/*.h`.)  If so, we can insert just that into our source code for you.  Or you could build with `-U__CYGWIN__` on the command line.

(So our other builds are okay!)

Here is a little test program to use for experiments:
```c++
#include <new>
#include <stdlib.h>
#define __CYGWIN__
#include <gc_cpp.h>
void operator delete[](void* obj) throw() { abort(); }
void operator delete(void* obj) throw() { abort(); }
void* operator new(size_t size) throw(std::bad_alloc) { abort(); }
void* operator new[](size_t size) throw(std::bad_alloc) { abort(); }
int main () { return 0; }
```

**Comment by ochachacha** [comment]
> It appears that only if **CYGWIN** is defined as a preprocessor macro does gc_cpp.h define those global inline functions.
> 
> @ochachacha -- could you experiment and see whether `#undef __CYGWIN__` fixes it for you? (The file is also included twice in `Macaulay2/system/*.h`.) If so, we can insert just that into our source code for you. Or you could build with `-U__CYGWIN__` on the command line.
> 
> (So our other builds are okay!)
> 
> Here is a little test program to use for experiments:
> 
> ```c++
> #include <new>
> #include <stdlib.h>
> #define __CYGWIN__
> #include <gc_cpp.h>
> void operator delete[](void* obj) throw() { abort(); }
> void operator delete(void* obj) throw() { abort(); }
> void* operator new(size_t size) throw(std::bad_alloc) { abort(); }
> void* operator new[](size_t size) throw(std::bad_alloc) { abort(); }
> int main () { return 0; }
> ```

Sorry for the delay; I just tried adding -U__CYGWIN__ to the CXXFLAGS and the configure script complains as follows.
```
configure:6902: checking whether exceptions are caught
configure:6929: g++ -o conftest.exe -std=gnu++14 -U__CYGWIN__ -g3 -O2 -I/usr/include -I/usr/local/include  -DNDEBUG -L/usr/lib -L/usr/local/lib  -g3 conftest.cpp  >&5
In file included from /usr/lib/gcc/x86_64-pc-cygwin/8.3.0/include/c++/x86_64-pc-cygwin/bits/gthr.h:148,
                 from /usr/lib/gcc/x86_64-pc-cygwin/8.3.0/include/c++/ext/atomicity.h:35,
                 from /usr/lib/gcc/x86_64-pc-cygwin/8.3.0/include/c++/bits/basic_string.h:39,
                 from /usr/lib/gcc/x86_64-pc-cygwin/8.3.0/include/c++/string:52,
                 from /usr/lib/gcc/x86_64-pc-cygwin/8.3.0/include/c++/stdexcept:39,
                 from conftest.cpp:16:
/usr/lib/gcc/x86_64-pc-cygwin/8.3.0/include/c++/x86_64-pc-cygwin/bits/gthr-default.h:113:1: error: 'sched_yield' was not declared in this scope
 __gthrw(sched_yield)
 ^~~~~~~
/usr/lib/gcc/x86_64-pc-cygwin/8.3.0/include/c++/x86_64-pc-cygwin/bits/gthr-default.h:113:1: note: suggested alternative: 'sched_param'
/usr/lib/gcc/x86_64-pc-cygwin/8.3.0/include/c++/x86_64-pc-cygwin/bits/gthr-default.h: In function 'int __gthread_yield()':
/usr/lib/gcc/x86_64-pc-cygwin/8.3.0/include/c++/x86_64-pc-cygwin/bits/gthr-default.h:692:33: error: '__gthrw_sched_yield' cannot be used as a function
   return __gthrw_(sched_yield) ();
                                 ^
configure:6929: $? = 1
configure: program exited with status 1
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME "Macaulay2"
| #define PACKAGE_TARNAME "Macaulay2"
| #define PACKAGE_VERSION "1.16.0.1"
| #define PACKAGE_STRING "Macaulay2 1.16.0.1"
| #define PACKAGE_BUGREPORT "Macaulay2@math.uiuc.edu"
| #define PACKAGE_URL "http://macaulay2.com/"
| #define CONFIG_ARGS " '--enable-download' '--enable-encap' '--prefix=/home/User/' '--disable-cygwin' 'CXXFLAGS=-U__CYGWIN__'"
| #define NODENAME "User-PC"
| #define ISSUE "Cygwin"
| #define OS "MicrosoftWindows"
| #define REL "3.1.6(0.340-5-3)"
| #define ARCH "x86_64"
| /* end confdefs.h.  */
|
|     #include <stdexcept>
|     #include <string>
|     int main () {
|       const std::string s("caught");
|       try { throw(std::runtime_error(s)); }
|       catch (std::runtime_error e) { }
|       return 0;
|     }
configure:6933: result: no, use a different C++ compiler
```

**Comment by DanGrayson** [comment]
Okay, try this instead.  Surround the three lines that include gc_cpp.h with `#undef __CYGWIN__` and `#define __CYGWIN`, so just the one include file is affected.

**Comment by ochachacha** [comment]
> Okay, try this instead. Surround the three lines that include gc_cpp.h with `#undef __CYGWIN__` and `#define __CYGWIN`, so just the one include file is affected.

This does the trick. No problem so far.

**Comment by DanGrayson** [comment]
Good.  Let us know the final result.

**Comment by ochachacha** [comment]
> Good. Let us know the final result.

All packages compiled without error.

**Comment by DanGrayson** [comment]
I guess now you have to see whether it crashes in the way originally reported.  Or not?

**Comment by mikestillman** [comment]
> > Okay, try this instead. Surround the three lines that include gc_cpp.h with `#undef __CYGWIN__` and `#define __CYGWIN`, so just the one include file is affected.
> 
> This does the trick. No problem so far.

@DanGrayson Just to be clear: is this supposed to be `#define __CYGWIN__`?

**Comment by DanGrayson** [comment]
Right, it's the undef that's wrong.

Experiment with that little test program to prove that the strategy will work.

**Comment by ochachacha** [comment]
> I guess now you have to see whether it crashes in the way originally reported. Or not?

The original test no longer crashes.

**Comment by DanGrayson** [comment]
So, I guess we can just add those lines to our source code.  I'll take care of that.
