### ISSUE TITLE
problem with 3edc32e42063fece3f99b7209c13b971753a57e9

### ISSUE THREAD

**Issue by pzinn** [Macaulay2/M2#1418]
the recent commit 3edc32e42063fece3f99b7209c13b971753a57e9 breaks a hack used by http://habanero.math.cornell.edu:3690/ which is to redefine `open` for its own purposes. now I don't necessarily condone this hack but I do think the user should be given a choice as to which program should be launched in such circumstances; a simple fix would be to move the line https://github.com/Macaulay2/M2/blob/1b1df7a362b8ecb008c5397513c93c831d4bd647/M2/Macaulay2/m2/html.m2#L48 
two lines up as the first test of `browser()`?
incidentally I don't think https://github.com/Macaulay2/M2/blob/1b1df7a362b8ecb008c5397513c93c831d4bd647/M2/Macaulay2/m2/html.m2#L39
is correct.

**Comment by DanGrayson** [comment]
Good idea.

But what did you have in mind when fn ==  ""?

**Comment by pzinn** [comment]
I just meant that that line seems pointless; maybe it was meant to be:
```
if fn == "" then return false;
```

**Comment by DanGrayson** [comment]
Oh, right!

**Comment by d-torrance** [comment]
As the author of the offending commit, that sounds fine to me!  My big issue was that `open` doesn't open a web browser on Ubuntu 18.04 (and other older Linuxes with the `open -> openvt` symlink).  Having an environment variable be the first check sounds like a great solution.  Then if a user wants to use `my-favorite-browser` for `viewHelp`, then can just set `WWWBROWSER=my-favorite-browser`.
