### ISSUE TITLE
scc1 line and column numbers

### ISSUE THREAD

**Issue by mahrud** [Macaulay2/M2#1420]
scc1 inserts line numbers in the code so that when an error occurs, the compiler can point to the right line in the .d or .dd source, but the columns are always confused:
```
/home/mahrud/Projects/M2/M2/M2/Macaulay2/d/regex.d:84:19: error: conflicting types for ‘rawRegexSearch’
   84 |     when e is s:Sequence do
      |                   ^~~~~~~~~     
compilation terminated due to -Wfatal-errors.
```
Is there anything that I'm missing, or is this expected behavior?

With `-noline` option given to scc1, this is the correct error:
```
Macaulay2/d/regex-tmp.c:1103:19: error: conflicting types for ‘rawRegexSearch’
 1103 | static parse_Expr rawRegexSearch(parse_Expr e){
      |                   ^~~~~~~~~~~~~~
compilation terminated due to -Wfatal-errors.
```

This particular error is in a new code, just to demonstrate the issue.

**Comment by DanGrayson** [comment]
The compiler gets the C code, so if the compiler indicates a column position in an error message, it will always
refer to the C code, not to the D code.  

By the way, we think of "raw" things as referring to things coming from Mike's C++ code, so you might want to name
your function "regexSearch".

**Comment by mahrud** [comment]
I think most compilers do that nowadays. Is there a better way to handle this so the errors are not so confusing?

**Comment by DanGrayson** [comment]
Yes, add
```
CFLAGS="-fno-diagnostics-show-caret -fno-show-column"
CXXFLAGS="-fno-diagnostics-show-caret -fno-show-column"
```

**Comment by mahrud** [comment]
Thanks. I guess this is as good a resolution as I expected.
