### ISSUE TITLE
building dmg fails on dynamically linked readline

### ISSUE THREAD

**Issue by tom111** [Macaulay2/M2#1426]
I'm on the Mac using 1.16.0.1 from yesterdays' HEAD.

After building everything using the instructions in `INSTALL.mac` I try to build the dmg using the Makefile in `M2/M2/tmp/distributions/dmg` and this fails with:

    library preparation: error *** : file files/Macaulay2-1.16.0.1/bin/M2-binary uses dynamic library /Users/tom/temp/M2/M2/tmp/usr-host/lib/libreadline.6.dylib

**Comment by DanGrayson** [comment]
Give either `--disable-shared` or `--enable-dmg` to the configure script.  (The new gatekeeper doesn't like us distributing shared libraries, so we're trying to be ready to satisfy it.)
