### ISSUE TITLE
Toplevel make file does not seem to pick up glibtool

### ISSUE THREAD

**Issue by tom111** [Macaulay2/M2#1434]
This is on a recent Mac.  This has a system wide libtool under `/usr/bin/libtool` and also a homebrew libtool under `/usr/local/bin/glibtool`.  When I run gmake -f Makefile in the toplevel source directory, it complains about a too old libtool.  Now I try to alias, but still:

```
➜  M2 git:(master) alias libtool=/usr/local/bin/glibtool
➜  M2 git:(master) libtool --version
glibtool (GNU libtool) 2.4.6
Written by Gordon Matzigkeit, 1996

Copyright (C) 2014 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
➜  M2 git:(master) gmake -f Makefile
GNU make version okay
GNU autoconf version okay
GNU automake version okay
gmake[1]: Entering directory '/Users/tom/temp/M2-MacInstall/M2'
=============================================================================
error: the libtool program installed on your system (libtool is /usr/bin/libtool) is not GNU.
```

From what I can see in the Makefile, it tries things like `type libtool` and `which libtool` in a subshell without that alias?

**Comment by tom111** [comment]
P.S. so this is one location where the file `INSTALL.mac` does not work 'out of the box'.

**Comment by tom111** [comment]
> P.S. so this is one location where the file `INSTALL.mac` does not work 'out of the box'.

My experience from the last days is that following the `INSTALL.mac` file is the only working way to build on MacOS. I've tried CMAKE,  homebrew gcc (which used to work well for me in earlier update rounds).

**Comment by DanGrayson** [comment]
I've just pushed commit 056541fc4e0df1b955d817e91f90c6bbfad67dfb to the development branch, which should fix it, by always getting libtool.  That's probably the only reliable way to go.

An alias won't work, because the shells in the build process are non-interactive.  The way to make glibtool impersonate libtool would be by putting a symbol link to it in a directory on your PATH.  But then later on you might have a weird failure of other software getting built and expecting libtool to be the Apple XCode program.

Re-open if that doesn't fix it.

**Comment by mahrud** [comment]
Strange that it doesn't see the alias `libtool -> /usr/local/bin/glibtool`. I wish the brew package for libtool would also create `` `brew --prefix libtool`/libexec/gnubin/libtool``, which is what the brew package for `make` and `tar` do.

**Comment by DanGrayson** [comment]
> Strange that it doesn't see the alias `libtool -> /usr/local/bin/glibtool`.

That's because aliases are defined in .bashrc, which is not loaded in a non-interactive shell.
