### ISSUE TITLE
Build failures on MacOS with cmake

### ISSUE THREAD

**Issue by tom111** [Macaulay2/M2#1436]
Here I'm following the file `INSTALL.cmake.md` word by word. I get to the line

`cmake --build BUILD/build --target build-libraries build-programs`

which fails linking normaliz:

```
libtool: link: /Library/Developer/CommandLineTools/usr/bin/c++ -Wall -pedantic -Wno-unknown-pragmas -Wno-sign-compare -Xclang -fopenmp -I/usr/local/include -march=native -DNDEBUG -DOM_NDEBUG -DSING_NDEBUG -Wuninitialized -g --sysroot=/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk -I/Users/tom/temp/M2-cmake/M2/BUILD/build/usr-host/include -I/Users/tom/temp/M2-cmake/M2/include -I/Users/tom/temp/M2-cmake/M2/BUILD/build/include -std=gnu++11 -w -Wno-mismatched-tags -Wno-deprecated-register -march=native -g --sysroot=/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk -o dynamic/dynamic dynamic/dynamic.o -Wl,-bind_at_load  -L/usr/local/lib -L/Users/tom/temp/M2-cmake/M2/BUILD/build/usr-host/lib ./.libs/libnormaliz.a -lomp -lgmpxx -lgmp
libtool: link: /Library/Developer/CommandLineTools/usr/bin/c++ -Wall -pedantic -Wno-unknown-pragmas -Wno-sign-compare -Xclang -fopenmp -I/usr/local/include -march=native -DNDEBUG -DOM_NDEBUG -DSING_NDEBUG -Wuninitialized -g --sysroot=/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk -I/Users/tom/temp/M2-cmake/M2/BUILD/build/usr-host/include -I/Users/tom/temp/M2-cmake/M2/include -I/Users/tom/temp/M2-cmake/M2/BUILD/build/include -std=gnu++11 -w -Wno-mismatched-tags -Wno-deprecated-register -march=native -g --sysroot=/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk -o normaliz normaliz.o -Wl,-bind_at_load  -L/usr/local/lib -L/Users/tom/temp/M2-cmake/M2/BUILD/build/usr-host/lib ./.libs/libnormaliz.a -lomp -lgmpxx -lgmp
libtool: link: /Library/Developer/CommandLineTools/usr/bin/c++ -Wall -pedantic -Wno-unknown-pragmas -Wno-sign-compare -Xclang -fopenmp -I/usr/local/include -march=native -DNDEBUG -DOM_NDEBUG -DSING_NDEBUG -Wuninitialized -g --sysroot=/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk -I/Users/tom/temp/M2-cmake/M2/BUILD/build/usr-host/include -I/Users/tom/temp/M2-cmake/M2/include -I/Users/tom/temp/M2-cmake/M2/BUILD/build/include -std=gnu++11 -w -Wno-mismatched-tags -Wno-deprecated-register -march=native -g --sysroot=/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk -o maxsimplex/maxsimplex maxsimplex/maxsimplex.o -Wl,-bind_at_load  -L/usr/local/lib -L/Users/tom/temp/M2-cmake/M2/BUILD/build/usr-host/lib ./.libs/libnormaliz.a -lomp -lgmpxx -lgmp
Undefined symbols for architecture x86_64:
  "___gmpz_fits_si_p", referenced from:
      __gmp_binary_divides::eval(__mpz_struct*, long, __mpz_struct const*) in libnormaliz.a(linear_algebra.o)
Undefined symbols for architecture x86_64:
  "___gmpz_fits_si_p", referenced from:
      __gmp_binary_divides::eval(__mpz_struct*, long, __mpz_struct const*) in libnormaliz.a(linear_algebra.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [dynamic/dynamic] Error 1
make[1]: *** Waiting for unfinished jobs....
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [normaliz] Error 1
Undefined symbols for architecture x86_64:
  "___gmpz_fits_si_p", referenced from:
      __gmp_binary_divides::eval(__mpz_struct*, long, __mpz_struct const*) in libnormaliz.a(linear_algebra.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [maxsimplex/maxsimplex] Error 1
make: *** [all-recursive] Error 1
```

**Comment by mahrud** [comment]
Hmm, could you attach the output of running `cmake .` in the build directory? Specifically, what do you see here:
```
## Library information
     Linear Algebra    = ..
     MP Arithmetic     = ..
```

**Comment by tom111** [comment]
This is it

[cmake-in-build-dir.log](https://github.com/Macaulay2/M2/files/4977262/cmake-in-build-dir.log)

**Comment by mahrud** [comment]
Here is the information I can gather:
- compiler is Xcode 11
- mpir is compiled by us in usr-host
- the following paths are used by normaliz:

```
-I/usr/local/include
-I/Users/tom/temp/M2-cmake/M2/BUILD/build/usr-host/include
-L/usr/local/lib
-L/Users/tom/temp/M2-cmake/M2/BUILD/build/usr-host/lib
```

I think the issue is that you have different version of gmp and mpir in `/usr/local` and `usr-host`. This shouldn't be a problem, except when some components of normaliz use the one in `usr-host` and some use the one in `/usr/local`, and then in that step they fail to link together.

Could you also attach the Normaliz config.log? It should be under the build directory here: `libraries/normaliz/build/config.log`

For now, a workaround is to add `-DUSING_MPIR=OFF` to your cmake line (you will probably need to start a new build). I think I should make that the default.

**Comment by tom111** [comment]
I’m sorry, I’ll only be able to access that machine and test more in about a month.

On 1 Aug 2020, at 8:31, Mahrud Sayrafi wrote:

> Here is the information I can gather:
> - compiler is Xcode 11
> - mpir is compiled by us in usr-host
> - the following paths are used by normaliz:
>
> ```
> -I/usr/local/include
> -I/Users/tom/temp/M2-cmake/M2/BUILD/build/usr-host/include
> -L/usr/local/lib
> -L/Users/tom/temp/M2-cmake/M2/BUILD/build/usr-host/lib
> ```
>
> I think the issue is that you have different version of gmp and mpir in `/usr/local` and `usr-host`. This shouldn't be a problem, except when some components of normaliz use the one in `usr-host` and some use the one in `/usr/local`, and then in that step they fail to link together.
>
> Could you also attach the Normaliz config.log? It should be under the build directory here: `libraries/normaliz/build/config.log`
>
> For now, a workaround is to add `-DUSING_MPIR=OFF` to your cmake line (you will probably need to start a new build). I think I should make that the default.
>
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/Macaulay2/M2/issues/1436#issuecomment-667482193



--
Thomas Kahle
https://www.thomas-kahle.de

**Comment by mahrud** [comment]
No worries. I changed the default to GMP in #1453, so I hope the install manual should work now. It's not a final solution, but I'll need to know what normaliz looks for in `/usr/local` to do anything about it. Please reopen if it isn't fixed when you get a chance to try it again.
