### ISSUE TITLE
Specific minor of a matrix

### ISSUE THREAD

**Issue by fereshteh-bahadory** [Macaulay2/M2#1446]
Hi,
How can I determine a specific minor of a matrix in M2? For example, if I have a $3\times 4$ matrix, how can I choose the $3\times 3$ minor determined by first, second, and the fourth column?

**Comment by DanGrayson** [comment]
Thank you for your query.  A better place for such questions is our google group, as this place for reporting bugs.

Meanwhile, take a look at https://faculty.math.illinois.edu/Macaulay2/doc/Macaulay2-1.15/share/doc/Macaulay2/Macaulay2Doc/html/___Matrix_sp_us_sp__List.html and https://faculty.math.illinois.edu/Macaulay2/doc/Macaulay2-1.15/share/doc/Macaulay2/Macaulay2Doc/html/___Matrix_sp%5E_sp__List.html .
