### ISSUE TITLE
degrees appear in bad positions labeling matrix rows

### ISSUE THREAD

**Issue by DanGrayson** [Macaulay2/M2#1457]
... as here:
```m2
Macaulay2, version 1.16
with packages: ConwayPolynomials, Elimination, IntegralClosure, InverseSystems, LLLBases,
               MinimalPrimes, PrimaryDecomposition, ReesAlgebra, TangentCone, Truncations

i1 : QQ[x];

i2 : transpose matrix {{x,x^2,x^3}}

o2 = {-1} | x  |
     {-2} | x2 |
     {-3} | x3 |

                   3             1
o2 : Matrix (QQ[x])  <--- (QQ[x])

i3 : compactMatrixForm = false

o3 = false

i4 : transpose matrix {{x,x^2,x^3}}

o4 = {-1} |  x |
     {-2} |    |
     {-3} |  2 |
          | x  |
          |    |
          |  3 |
          | x  |

                   3             1
o4 : Matrix (QQ[x])  <--- (QQ[x])
```

**Comment by pzinn** [comment]
This beginner is going to propose a PR fixing this. but first, quick question, any reason the degrees appear in { } ?
would it look better without them, like
```
o4 = -1 |  x |
        |    |
        |  2 |
     -2 | x  |
        |    |
        |  3 |
     -3 | x  |
```

**Comment by pzinn** [comment]
PS. in the case of a multigrading it would then look like
```
-1 0  | 1  x   |
-3 0  | x2 x3  |
-1 -2 | y2 xy2 |
```
or in non compact mode
```
-1   0  |   1    x   |
        |            |
        |   2    3   |
-3   0  |  x    x    |
        |            |
        |   2     2  |
-1  -2  |  y   x*y   |
```

**Comment by DanGrayson** [comment]
> This beginner is going to propose a PR fixing this. but first, quick question, any reason the degrees appear in { } ?
> would it look better without them, like
> 
> ```
> o4 = -1 |  x |
>         |    |
>         |  2 |
>      -2 | x  |
>         |    |
>         |  3 |
>      -3 | x  |
> ```

That would be a good improvement, when the DegreeRank is 1.

**Comment by DanGrayson** [comment]
> PS. in the case of a multigrading it would then look like
> 
> ```
> -1 0  | 1  x   |
> -3 0  | x2 x3  |
> -1 -2 | y2 xy2 |
> ```
> 
> or in non compact mode
> 
> ```
> -1   0  |   1    x   |
>         |            |
>         |   2    3   |
> -3   0  |  x    x    |
>         |            |
>         |   2     2  |
> -1  -2  |  y   x*y   |
> ```

The degree is actually a list, so why not show it?

**Comment by mahrud** [comment]
I feel like not changing it is better, since currently the annotations always match the output of `degrees`:
```m2
i1 : R = QQ[x, Degrees => {2}]

o1 = R

o1 : PolynomialRing

i2 : transpose matrix {{x,x^2,x^3}}

o2 = {-2} | x  |
     {-4} | x2 |
     {-6} | x3 |

             3       1
o2 : Matrix R  <--- R

i3 : degrees transpose matrix {{x,x^2,x^3}}

o3 = {{{-2}, {-4}, {-6}}, {{0}}}

o3 : List
```

Including in multigraded case:
```m2
i15 : R=QQ[x,y,Degrees=>{{0,1},{1,0}}]

o15 = R

o15 : PolynomialRing

i16 : transpose matrix {{x,x^2,x^3}}

o16 = {0, -1} | x  |
      {0, -2} | x2 |
      {0, -3} | x3 |

              3       1
o16 : Matrix R  <--- R

i17 : degrees transpose matrix {{x,x^2,x^3}}

o17 = {{{0, -1}, {0, -2}, {0, -3}}, {{0, 0}}}

o17 : List
```

**Comment by pzinn** [comment]
OK I will leave the degrees as a {list} then.

**Comment by pzinn** [comment]
this needs closing I think
