### ISSUE TITLE
Keywords for packages

### ISSUE THREAD

**Issue by mahrud** [Macaulay2/M2#1459]
A feature that has been frequently requested at workshops is having keywords for packages and group them together in the list of packages.

I can include this as a part of #1454, which also adds a page for package authors. My current suggestion is to have `newPackage` accept a list of strings as the option Keyword. The first one would be used to group the packages together, the rest would only be displayed next to the package or on the top page of the package.

@DanGrayson @mikestillman how does this sound?

**Comment by DanGrayson** [comment]
Sounds good. The keywords should also be included in the search conducted by `about`.

But small pull requests are better than big ones.

**Comment by mahrud** [comment]
Here's what it will look like:
![image](https://user-images.githubusercontent.com/3147718/89726656-6e9f6e80-d9e2-11ea-8d07-2c9ec3e6fb05.png)

Now it remains to classify about 200 packages!

**Comment by mahrud** [comment]
Should we categorize the packages ourselves, then send a message to the group to have the authors fix any mistakes, or should all packages be uncategorized by default and have the authors slowly add keywords? I prefer the former.

**Comment by DanGrayson** [comment]
Me, too.  We don't claim to be able to guess our authors' preferences, but at least it will get done, and changes from authors would be accepted.

**Comment by mahrud** [comment]
I'm reopening this, since most packages still need keywords.
