### ISSUE TITLE
Trim of ideal over ZZ computed incorrectly

### ISSUE THREAD

**Issue by psuchand** [Macaulay2/M2#146]
--The generators of trim(J) to not generate J
--The second assertion fails while the first one succeeds.

P = ZZ[a, c1, c2, d]

J = ideal(3_a_c1^2+2_a^2_c2-6_c1^2-11_a_c2-6_c2^2+6_a+39_c2-38,a_c1^2_d+a^2_c2_d-2_c1^2_d-4_a_c2_d-2_c2^2_d+2_a_d+15_c2_d-17_d-1,a^2_c2^2+3_a_c1^2+2_a_c2^2+3_c1^2-9_a_c2+3_c2^2+6_a-13_c2+6,a^3_c2+5_a_c2-13_a-13,a^2_c1^2-a_c1^2-3_a^2_c2-2_a_c2^2+2_a^2-2_c1^2+6_a_c2-2_c2^2-2_a+13_c2-4,a^3_c1^2+2_a^3+a^2_c2+10_c1^2+27_a_c2+10_c2^2-39_a-52*c2+7 ); J = promote(J,P);

Jmin = trim J

assert (Jmin == J)
assert (ideal first entries gens Jmin == J)

**Comment by mikestillman** [comment]
I disabled the 'trim' in this case (GB in poly rings over ZZ).  I'm leaving the issue open, but moving it to version 1.9.  At least now it doesn't give an incorrect answer.
