### ISSUE TITLE
M2 path setup doesn't work for zsh

### ISSUE THREAD

**Issue by helluvaworld** [Macaulay2/M2#1460]
The instructions for using "setup()" to allow users to run Macaulay by typing "M2" don't work for zsh users (because setup only changes the bashrc). In particular, Catalina switched to zsh recently, so it would really help Mac users to have a zsh version of setup, or at least a note in the installation page on the website to write "mv .bashrc .zshrc" in a terminal window after running setup.

**Comment by mahrud** [comment]
Are you using M2 v1.16? `setup()` _should_ modify `.zprofile`. Could you paste here the result of `code methods setup`?

**Comment by mahrud** [comment]
A new beta release, 1.16.99 is now available: https://faculty.math.illinois.edu/Macaulay2/Downloads/MacOSX/index.html

Let us know if this issue is still present!
