### ISSUE TITLE
.bash_profile

### ISSUE THREAD

**Issue by kschwede** [Macaulay2/M2#1462]
This is probably not a bug, but it should be documented at least.

Ok, so in the current (compiled today 8/11) version of M2, when you run setup(), it creates a .bash_profile file and puts some Macaulay2 stuff in there.

The only problem is that at least on Ubuntu 20.04, .bash_profile is not created by default, and in some cases if it exists, it is used *instead* of .bashrc, when logging in in certain ways.  

Thus you are setting up a system where all the users .bashrc commands will be ignored, and they probably don't want that
(sorry, I just spent 20 minutes tryijng to figure out why my .bashrc wasn't loading).

**Comment by DanGrayson** [comment]
Definitely a bug, which I introduced July 15.  Fixed now in commit ace5069c868460f16044e89379d88b5a53e63f4d, thanks to your prompt report.  I'm glad people are running from current source code.

By the way, you must have meant .profile instead of .bashrc.

**Comment by kschwede** [comment]
Of course you are right, sorry, my .profile loads .bashrc.
