### ISSUE TITLE
trim the path

### ISSUE THREAD

**Issue by DanGrayson** [Macaulay2/M2#1472]
The directory `/Applications/Macaulay2-1.16/share/Macaulay2/Core/` should be removed from the path after loading all of the files in it.

```m2
Macaulay2, version 1.16
with packages: ConwayPolynomials, Elimination, IntegralClosure, InverseSystems,
               LLLBases, MinimalPrimes, PrimaryDecomposition, ReesAlgebra, TangentCone,
               Truncations

i1 : stack path

o1 = ./
     /Users/dan/Library/Application Support/Macaulay2/code/
     /Users/dan/Library/Application Support/Macaulay2/local/share/Macaulay2/
     /Applications/Macaulay2-1.16/share/Macaulay2/Core/
     /Applications/Macaulay2-1.16/share/Macaulay2/
```

**Comment by mahrud** [comment]
Here's a good fix for this:
0. never add either of those directories to the path! Instead:
1. move `Macaulay2/m2 -> Macaulay2/Core`
2. move `Macaulay2/Core/setup.m2 -> Macaulay2/packages/Core.m2` and have it load all the files in `Macaulay2/Core` and delete `Macaulay2/m2/Core.m2`
3. load `Macaulay2/packages/Core.m2` from `startup.m2`

**Comment by DanGrayson** [comment]
> In particular, it would be amazing if Core could be reloaded the same way that any other package is. Would make development so much easier!

That would be good, but there are various things in the core that should not be done twice.  For example, this:
```m2
     close = new Manipulator from close;
     closeIn = new Manipulator from closeIn;
     closeOut = new Manipulator from closeOut;
     flush = new Manipulator from flush;
     endl = new Manipulator from endl;
```
