### ISSUE TITLE
unexported methods

### ISSUE THREAD

**Issue by mahrud** [Macaulay2/M2#1494]
I just noticed that even unexported methods are visible by the `methods` command. Is this intended?

```m2
i3 : methods DocumentTag 

o3 = {0 => (-*Function*-, DocumentTag)                }
     {1 => (-*Function*-, DocumentTag)                }
     {2 => (-*Function*-, DocumentTag)                }
     {3 => (?, DocumentTag, DocumentTag)              }
     {4 => (?, DocumentTag, String)                   }
     {5 => (?, String, DocumentTag)                   }
     {6 => (fetchPrimaryRawDocumentation, DocumentTag)}
     {7 => (fetchRawDocumentation, DocumentTag)       }
     {8 => (fetchRawDocumentationNoLoad, DocumentTag) }
     {9 => (formattedKey, DocumentTag)                }
     {10 => (headline, DocumentTag)                   }
     {11 => (help, DocumentTag)                       }
     {12 => (htmlFilename, DocumentTag)               }
     {13 => (infoTagConvert, DocumentTag)             }
     {14 => (makeDocumentTag, DocumentTag)            }
     {15 => (net, DocumentTag)                        }
     {16 => (packageName, DocumentTag)                }
     {17 => (toString, DocumentTag)                   }
```

I think maybe 3 or 4 of the 17 methods above are actually exported.

**Comment by DanGrayson** [comment]
Those method functions include fetchRawDocumentation, fetchRawDocumentationNoLoad, getPrimaryTag, etc., which are in the Core, but not, as you say, exported.  Perhaps your idea is to add code to check whether the method function is accessible via a symbol in a dictionary on the dictionaryPath.  But then this would make debugging hard.  Suppose the debugger has stopped at a line where the method for "fetchRawDocumentation DocumentTag" is about to be called, and you want to find the code for that.  Then what?  It might be better to just leave it.

**Comment by mahrud** [comment]
I somehow fixed this! Not sure how exactly.
