### ISSUE TITLE
Package "ToricVectorBundles" returns wrong Cartier index of a Weil divisor

### ISSUE THREAD

**Issue by dimitrim2010** [Macaulay2/M2#1508]
Example

```  
loadPackage Polyhedra;
loadPackage "ToricVectorBundles";
RayMatrix=transpose matrix{{1,0,0},{0,1,0},{1,2,4},{-1,-2,-2}};
FanFromRays=ccRefinement RayMatrix;
print rays FanFromRays;
cartierIndex({0,1,0,0},FanFromRays)
--
-- Returns 4, though the correct index is 2.
-- Compare with the other toric package:
--
loadPackage "NormalToricVarieties";
X=normalToricVariety(FanFromRays);
rays X 
--
-- We have checked that the order of rays is the same as in the previous
-- package, so the weights {0,1,0,0} represent the same Weil divisor
-- D1 in both computations.
--
D1=toricDivisor({0,1,0,0},X);
isCartier D1 -- false
isCartier (2*D1) -- true
-- The last two commands show that the Cartier index of D1 is 2
```

**Comment by a-hochenegger** [comment]
The method `cartierIndex` works well in principle, only that when internally setting up the toric reflexive sheaf (of rank 1), the rays get mixed up. One can see this by continuing your example with the following code (partially taken from the method `cartierIndex`):
`debug ToricVectorBundles`
`L = makeVBKlyachko(1, FanFromRays, apply( {0,1,0,0} , l->matrix{{1_QQ}}), apply( {0,1,0,0} , l->matrix{{-l}}));`
`rays L`
`details L`
Here you can see the internal order of the rays (different from the one of `FanFromRays`) and that `L` corresponds to the Weil divisor for the ray `{1,2,4}`, which has `cartierIndex` four. 
Now you can check that this coincides with the results from
`isCartier toricDivisor({0,0,0,2},X)`
`isCartier toricDivisor({0,0,0,4},X)`
So the actual error is that `cartierIndex` returns the result for a different Weil divisor. 

To get the internally used order of rays for `toricVectorBundles`, you can use
`rays toricVectorBundle(1, FanFromRays)`
which gets the order of rays of the structure sheaf (obviously, this solution is not ideal).

**Comment by a-hochenegger** [comment]
With the new version 1.24, the package `ToricVectorBundles` provides the method `raySortOfFan` which returns the precise order of the rays used for the bundles. So in your example use
`raySortOfFan FanFromRays`

**Comment by dimitrim2010** [comment]
Thank you, good to know that the internal order of rays differs from the
one displayed by the "rays" command!
