### ISSUE TITLE
Failing run program test

### ISSUE THREAD

**Issue by dylanpeifer** [Macaulay2/M2#1509]
A test in `tests/normal/programs.m2` is failing for me. The test itself fails on line 19 (when checking the output). I think a simpler version of the same failure is

```macaulay2
i1 : run("echo -n Hello World")
-n Hello World

o1 = 0
```

which ignores the `-n` flag that removes the trailing newline when I run `echo -n Hello World` on a separate terminal. I'm using `MacOS-10.15.6` and have compiled off the latest version of the master branch. I wasn't able to track down exactly what `run` is doing, though it looks like it is setup on line 1053 of `d/actors3.d` and might be imported from somewhere on line 117 in `d/system.d`. Any suggestions?

**Comment by DanGrayson** [comment]
That's probably because you have your SHELL environment variable set to "/bin/sh", whose built-in "echo" command doesn't support "-n".

For predictability of the behavior of the "run" command, we should set SHELL to "/bin/sh" in the script "M2".

**Comment by mahrud** [comment]
> For predictability of the behavior of the "run" command, we should set SHELL to "/bin/sh" in the script "M2".

This would not make it predictable, because on Fedora `/bin/sh` is a symlink to bash while on Ubuntu/Debian it's a symlink to dash, which has a smaller syntax.

**Comment by d-torrance** [comment]
Since `echo` isn't portable, I've just opened #1510 switching this test to use `printf`, which is.
