### ISSUE TITLE
relative links not right in top viewHelp page

### ISSUE THREAD

**Issue by DanGrayson** [Macaulay2/M2#1516]
If M2 is started without the option "-q" on the command line, then it makes an index of packages as an html file in the user's application directory, and "viewHelp" shows it.  Normally the package "Style" is not installed there also, and the link to the CSS file is absolute, e.g., "file:///Applications/Macaulay2-1.16/share/Macaulay2/Style/doc.css".  But if the package "Style" is installed, it tries to create a relative link and fails, putting something involving the path to the current directory ("../../../../../private/tmp/foo/share/Macaulay2/Style/doc.css") there instead of ""../../../../Macaulay2/Style/doc.css"/".

This affects version 1.16.

**Comment by d-torrance** [comment]
Closed by #3277
