### ISSUE TITLE
To figure out that the proper package for the documentation of "integralClosure(Ideal)" is "IntegralClosure" presents a problem.  From

### ISSUE THREAD

**Issue by DanGrayson** [Macaulay2/M2#1528]
This code is wrong:
```
     /Applications/Macaulay2-1.15/share/Macaulay2/Core/packages.m2:470:23-470:44: --source code:
     package Sequence := s -> youngest (package\s)
```
because it depends on the hash code of the package object.  Hash codes always increase as time goes on, but objects of type Package may not be created in dependency order, chronologically.  The Package object is created by "newPackage", and *after* that, other packages may be loaded by the code inside the package, or by the newPackage function taking care of the PackageExports and PackageImports options.

Here is a way to get the hashcodes of the packages in the right order: we update the hashcode in the endPackage function. To make a new Package object from an old one this code suffices: new Package from new MutableHashTable from Foo. There shouldn't be any pointers to the old package lying around, but in case there are, it might be good instead to have "newPackage" make the package of type MutableHashTable instead of being of type Package, and then in "endPackage" we could do new Package from Foo instead.

**Comment by mahrud** [comment]
I guess I'm confused at a lower level: why is knowing the package of a method function useful? I can only think of two useful information: the file and line number of the code, the file and line number of its documentation, if it is found in cache. Is there another use?

**Comment by DanGrayson** [comment]
To generate a link to the html file of a documentation node, you need to know the package.

**Comment by mahrud** [comment]
That's a bad reason. It makes a lot more sense to assume that you should use `"IntegralClosure :: integralClosure(Ideal)"` for that purpose:
```m2
i1 : makeDocumentTag "IntegralClosure :: integralClosure(Ideal)"

o1 = IntegralClosure :: integralClosure(Ideal)

o1 : DocumentTag

i2 : package oo

o2 = IntegralClosure
```

**Comment by DanGrayson** [comment]
Anything that makes life easier for users is a good reason.

**Comment by mahrud** [comment]
We make their life easier by giving an informative error, saying that this method wasn't found either in Core or in the current package, so you should change it to the format above.

Trying to guess which external package the user means only causes confusion, for instance because different packages may have different meanings, implementations, or documentation for something like "(graph, Ideal)"!

**Comment by mahrud** [comment]
By the way, I take this view mainly because I've fixed dozens of missing documentation links that previously silently broke, but now give an error so the user can fix them.

**Comment by DanGrayson** [comment]
> We make their life easier by giving an informative error, saying that this method wasn't found either in Core or in the current package, so you should change it to the format above.

We can make their life even easier by finding the right package for them.

> 
> Trying to guess which external package the user means only causes confusion, for instance because different packages may have different meanings, implementations, or documentation for something like "(graph, Ideal)"!

Yes, if "graph" and "Ideal" do not come from the package that defines the method, then there's currently no way to tell, but one way to fix that is to tag each function with the package that created it.

**Comment by mahrud** [comment]
> We can make their life even easier by finding the right package for them.

This is bad, because we can't (I'll give an example below), and so end up producing broken links.

> Yes, if "graph" and "Ideal" do not come from the package that defines the method, then there's currently no way to tell, but one way to fix that is to tag each function with the package that created it.

I don't know how to make this more clear. Try putting a link to `isSmooth` somewhere in the VirtualResolutions package. You'll be surprised to see that the link is made to "Polyhedra :: isSmooth", despite the fact that Polyhedra is not on the PackageExports but SpaceCurves is, and SpaceCurves has a isSmooth function! Now, try putting "SpaceCurves" last in the PackageExports list, and the result is reversed.

This unpredictability serves literally nobody. Trying to make the symbol system more intricate as you suggest only makes it more messy.

The best, and probably only, solution is to completely disallow linking to documentation nodes in packages other than current package and Macaulay2Doc without the "PackageName ::" prefix. That's the only bulletproof way to get the correct link.

**Comment by mahrud** [comment]
Here's an even worse situation that can happen:
- I write package Foo which exports packages Bar1, Bar2, let's say in that order.
- Let's say only Bar1 exports a symbol isSmooth.
- In documentation for Foo, I link to isSmooth.
- Later, after I've moved on from this package, Bar2 developers add a different symbol isSmooth.
- This might break examples, but maybe I don't actually use isSmooth, so nothing breaks
- But now the link instead points to the isSmooth in Bar2, which may be completely different.

This is why I think users should make the package of a link explicit.

**Comment by DanGrayson** [comment]
> Here's an even worse situation that can happen:
> 
> * I write package Foo which exports packages Bar1, Bar2, let's say in that order.
> * Let's say only Bar1 exports a symbol isSmooth.
> * In documentation for Foo, I link to isSmooth.
> * Later, after I've moved on from this package, Bar2 developers add a different symbol isSmooth.
> * This might break examples, but maybe I don't actually use isSmooth, so nothing breaks
> * But now the link instead points to the isSmooth in Bar2, which may be completely different.
> 
> This is why I think users should make the package of a link explicit.

We could simply make it an error (in `makeDocumentTag`, presumably) to create a documentation link with a symbol name (i.e., a string) that occurs twice in dictionaries listed in `dictionaryPath`, forcing the user at that time to make a link with the package name explicit.

**Comment by mahrud** [comment]
makeDocumentTag is called thousands of times and the smallest slow down in it really shows up. This is a bad idea.

**Comment by mahrud** [comment]
Related: #818
