### ISSUE TITLE
print missing key in error message

### ISSUE THREAD

**Issue by mahrud** [Macaulay2/M2#1530]
I often run into mysterious error messages like this:
```m2
stdio:11:59:(3): error: key not found in hash table
```
In this instance, I was trying to figure out the issue mentioned in [this comment](https://github.com/Macaulay2/M2/pull/1502#issuecomment-703167874), and this error is utterly unhelpful.

@DanGrayson I figure the best solution is to perhaps print the key in the error message, which happens here:
https://github.com/Macaulay2/M2/blob/7ba26782adc33cb23f4ca3522130721f53b93fb8/M2/Macaulay2/d/hashtables.dd#L319-L326
One wrinkle is that the key can be any Expr object, and probably turning it into a string is not always the best idea. Could we print it if it's an integer or string perhaps? Do you have any better ideas?

**Comment by DanGrayson** [comment]
In `robust.m2` are `silentRobustNetWithClass` and `silentRobustNet`, which print things while limiting the size.  They are used in error messages like this one:
```m2

i4 : (300:1) + (300:2)
stdio:4:9:(3): error: no method for binary operator + applied to objects:
--            (1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1. (of class Sequence)
--      +     (2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2. (of class Sequence)
```

(I wish there were 3 dots instead of just one at the cutoff points.)
