### ISSUE TITLE
FourTiTwo not working in the Macaulay2Web interface

### ISSUE THREAD

**Issue by kaiekubjas** [Macaulay2/M2#1534]
It seems that FourTiTwo package is not working in the Macaulay2Web interface (I have found FourTiTwo package on the web interface especially useful, since 4ti2 is difficult to install). The code I tried to run is

needsPackage “FourTiTwo"
A = matrix"1,1,1,1;0,1,2,3"
M = toricMarkov(A)

Thanks!

**Comment by DanGrayson** [comment]
@pzinn @d-torrance

**Comment by d-torrance** [comment]
The underlying issue seems to be that the `markov` binary (which `findProgram` is calling to find the location of 4ti2)  calls the `which` command, which apparently isn't available on the web interface's system:

```m2
i21 : markov = "/usr/libexec/Macaulay2/bin/markov"


o21 =  /usr/libexec/Macaulay2/bin/markov 

i22 : run(markov | " -h")

/usr/libexec/Macaulay2/bin/markov: line 24: which: command not found
Error: Unable to find 4ti2 executable `4ti2int64'

o22 =  256 

i23 : (lines get markov)#23


o23 =  SCRIPT=`which "$0"` 
```

**Comment by pzinn** [comment]
weird, the examples in the doc work, suggesting that at some point in the past it worked fine. I'll look into it.

**Comment by pzinn** [comment]
fixed. will ship with the next update of the server, in a few days.

**Comment by pzinn** [comment]
it's up now. please test and close the issue if resolved.

**Comment by d-torrance** [comment]
It works for me now!

**Comment by DanGrayson** [comment]
Was it just a matter of installing `which`?

**Comment by pzinn** [comment]
yes
