### ISSUE TITLE
check "Core"

### ISSUE THREAD

**Issue by d-torrance** [Macaulay2/M2#1547]
Currently, this does nothing:

```m2
i1 : check "Core"

i2 :
```

Should it do something?  Maybe run the tests in `M2/Macaulay2/tests`?  They aren't currently installed, though.

(Based on the `M2 --help` description, it seems like this should be what `M2 --check 2` runs.  In #1542, I had it check "Macaulay2Doc" instead, since that seems to be the closest thing we can do at the moment.)

**Comment by DanGrayson** [comment]
Yes, Macaulay2Doc is just the documentation for the core, so what you did makes sense.  I suppose it might make sense eventually to arrange for all the tests in `tests` to be installed and easily runnable, since due to upgrades to shareable libraries, such tests might eventually fail.  But running all the tests of all the packages is already a formidable test suite.

**Comment by mahrud** [comment]
This will be resolved when (eventually) Core becomes a "real" package, and the documentation from "Macaulay2Doc" will be moved there. How this will happen hasn't been decided.

On a related note, Macaulay2Doc has a number of tests sprinkled among the documentation, which is kind of annoying.

**Comment by DanGrayson** [comment]
> On a related note, Macaulay2Doc has a number of tests sprinkled among the documentation, which is kind of annoying.

On the other hand, for a test of a feature to be near the documentation of the feature is not a bad thing.

**Comment by mahrud** [comment]
> On the other hand, for a test of a feature to be near the documentation of the feature is not a bad thing.

It's a thing that has made debugging harder for me, maybe because the documentation is kind of a hodgepodge at the moment as well, so it's still a bad thing in my opinion.

**Comment by d-torrance** [comment]
Perhaps all the `Core` tests should be merged into the same place?  Macaulay2Doc doesn't test everything.  For example, for the new `Core` functions I've contributed recently (`regexQuote`, `findProgram` and `runProgram`), I only wrote tests for `M2/Macaulay2/tests/normal`.  Macaulay2Doc got examples, of course, but no additional tests.

**Comment by d-torrance** [comment]
This was addressed in #1725.  Closing
