### ISSUE TITLE
make fails on newest commit (995c6fd) but works on the previous commit

### ISSUE THREAD

**Issue by Dylan1496** [Macaulay2/M2#1549]
Using the makepkg available on the Arch AUR ([https://aur.archlinux.org/packages/macaulay2/](url)), the build fails when it's setting up help for emacs. The error that occurs is the following:

`make[2]: *** No rule to make target '../editors/emacs/make-M2-emacs-help.m2', needed by 'TAGS'. Stop.`

This issue does not occur with the previous commit (8b41c61). So something appears to be broken here, as there is no way to prevent this from building to allow the makepkg to create the package successfully.

**Comment by d-torrance** [comment]
It looks like the [M2-emacs](https://github.com/Macaulay2/M2-emacs) submodule hasn't been initialized.  Glancing at https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=macaulay2, I think the following line should be added before the call to `make` in line 34:
```
git submodule update --init Macaulay2/editors/emacs
```

**Comment by Dylan1496** [comment]
Turns out the issue was a bit easier: I needed to first run make before running the configure command, as per the instructions in INSTALL. Then after that it built correctly.
The corrected pkgbuild is here: https://pastebin.com/7Ey2DfNi

So this issue is solved and can be closed.
