### ISSUE TITLE
Cygwin build failing

### ISSUE THREAD

**Issue by DanGrayson** [Macaulay2/M2#155]
Building M2 under cygwin currently fails because of a bug in "ld".  The configure
script of pari fails to detect libgmp (installed by mpir) because of it, but hides the
error messages.

The bug causes "ld" to crash with a segmentation fault while reading libgmp.a.
A work-around is to replace libgmp.a by the entire list of *.o files it contains, and it
can be seen to be in "ld" by using "gcc -v" to figure out how gcc calls it.  Running
ranlib on libgmp.a makes no difference.

**Comment by DanGrayson** [comment]
This branch offers the best chance for using gmp instead of pari now: https://github.com/DanGrayson/M2/tree/use-native-gmp-mfpr-pari

**Comment by dimpase** [comment]
by the way, MPIR 2.7.0 has been released, perhaps better luck with Cygwin?

**Comment by DanGrayson** [comment]
Thanks -- it turns out another hint helped: linking MPIR dynamically instead of statically.  So I'm making progress here: https://github.com/DanGrayson/M2/commits/release-1.8-cygwin

**Comment by DanGrayson** [comment]
We've given up on cygwin, closing...
