### ISSUE TITLE
separate should allow length 0 delimiters

### ISSUE THREAD

**Issue by mahrud** [Macaulay2/M2#1553]
This is something that wasn't possible previously, but with lookaheads and lookbehinds it is possible to split a string without consuming any characters.

Current behavior on main branch:
```m2
i1 : separate("(?=a)", "ahoabba")
o1 = {ahoabba}
```

Behavior in node:
```js
> "ahoabba".split(/(?=a)/)
[ 'aho', 'abb', 'a' ]
> "ahoabba".split(/(?<=a)/)
[ 'a', 'hoa', 'bba' ]
```

**Comment by pzinn** [comment]
beat me to it!

**Comment by mahrud** [comment]
Oh, I forgot to mentioned that you reported this. Thanks for the javascript code! I don't know why it didn't work when I tried.
