### ISSUE TITLE
primaryDecomposition and minimalPresentation

### ISSUE THREAD

**Issue by psuchand** [Macaulay2/M2#156]
Some small issues. Need for scripted interaction with Macaulay2.

---Primary decomposition
P = ZZ/2[x0, x1]
I = ideal(0 ); I = promote(I,P);

primaryDecomposition I
--This prints an error: "error: expected a list or sequence of integers or variables in the same ring"

--Running the same command again prints a different error: "error: algorithm missed components!"
primaryDecomposition I

--trimming I returns the first error again.
primaryDecomposition trim I 

------------------
restart
S = ZZ[a]/(2*a - 1)
R = ZZ[x,y]/(2*x - 1, y-1)

--Both of these commands return "error: can't promote number to ring"
S = minimalPresentation S
R = minimalPresentation R

**Comment by mikestillman** [comment]
Second part fixed in commit b6405af47af15a506d4157dbfac86eba2df9a056.
