### ISSUE TITLE
Lisp equality of functions

### ISSUE THREAD

**Issue by mahrud** [Macaulay2/M2#1567]
Why is === defined the way it is for functions? I imagine == is rather difficult for functions, but shouldn't === just check that the lisp version of both functions are the same? I think that would make sense, but I'm actually surprised about this:

```m2
i1 : f = x -> y -> 2*x;

i2 : (f 2) == (f 2)
stdio:2:7:(3): error: no method for binary operator == applied to objects:
--            -*Function[stdio:1:12-1:17]*- (of class FunctionClosure)
--     ==     -*Function[stdio:1:12-1:17]*- (of class FunctionClosure)

i3 : (f 2) === (f 2)

o3 = false -- WHAT??

i4 : code (f 2) == code (f 2)

o4 = true

i5 : code (f 2) === code (f 2)

o5 = true

i6 : code (f 2) == code (f 3)

o6 = false

i7 : code (f 2) === code (f 3)

o7 = false

i8 : disassemble (f 2) == disassemble (f 2)

o8 = true

i9 : disassemble (f 2) === disassemble (f 2)

o9 = true

i10 : disassemble (f 2) == disassemble (f 3)

o10 = true -- WHAT??

i11 : disassemble (f 2) === disassemble (f 3)

o11 = true -- WHAT??

```

_Originally posted by @mahrud in https://github.com/Macaulay2/M2/pull/1385#issuecomment-719007041_

**Comment by mahrud** [comment]
>> Why is === defined the way it is for functions? I imagine == is rather difficult for functions, but shouldn't === just check that the lisp version of both functions are the same? I think that would make sense, but I'm actually surprised about this:
>
>The code for `f===g` is designed to never go into an infinite loop, and part of the way of ensuring that is that cycles in the graph of pointers are not traversed.  That's why mutable objects are compared, not by comparing their contents, but by comparing the pointers to them.  Functions are mutable objects, because the values stored as the values of local variables can be changed.
>
>Anyway, just don't use functions as keys -- it's easy to avoid.

_Originally posted by @DanGrayson in https://github.com/Macaulay2/M2/pull/1385#issuecomment-719018348_

**Comment by mahrud** [comment]
Despite the argument above, I think === equality of functions should be based on comparison of the "disassembled" version of it. Specifically, this reasoning doesn't make sense to me:

> Functions are mutable objects, because the values stored as the values of local variables can be changed.

If two functions parse to the same lisp-like program and use the same local (or even global) variables in the same way, then their behavior is exactly the same. There's no point in considering them to be different functions.

**Comment by DanGrayson** [comment]
Function closures include pointers to current values of local variables -- that's what makes them mutable.  One important consistency property of the comparison operation `f===g` is that if it's true once, it will still be true later.  That's not true for mutable objects.

Here's how to create a function closure with a cycle of pointers in it:
```m2
i2 : f = x -> y -> x=y ;

i3 : g = f 1 ;

i4 : g g ;
```
Now the function `g` points to itself, because a pointer to `g` is stored as the value of the variable `x` in `g`.

**Comment by mahrud** [comment]
I don't understand how this is relevant. You can do this in any language, but at the end of the day the parsed representation of the program is identical and can be compared.

In other words: consider all mutable objects pointed to by a function closure to be inputs to the function. If two functions applied to the same input (including mutable objects) give the same output, then they are the same.

You don't actually have to check the pointers, because you can just take it as an input value that will be provided at runtime.

**Comment by DanGrayson** [comment]
No, the values of local variables stored inside a function closure cannot be considered as inputs -- they are part of the function closure, and they affect its behavior.  Equal objects must have the same behavior.  Here is an example where you would declare two functions, g and h, to be equal, but their behavior would be different.
```m2
Macaulay2, version 1.16.0.2
with packages: ConwayPolynomials, Elimination, IntegralClosure, InverseSystems, LLLBases, MinimalPrimes, PrimaryDecomposition, ReesAlgebra, TangentCone, Truncations

i1 : f = x -> y -> (t := x; x = y; t);

i2 : g = f 1;

i3 : h = f 2;

i4 : g ()

o4 = 1

i5 : h ()

o5 = 2
```

**Comment by mahrud** [comment]
This doesn't make any sense. Clearly g and h are not equal here, because the pointer contained in them is not pointing to the same location! In one of them "x" points to some block X1, in the other one "x" points to some block X2, and clearly X1 and X2 are not equal since their values is different.

I'm saying that if X1 and X2 pointed to the same address then g and h would be equal. Consider this:
```m2
i1 : f = x -> y -> x#y;

i2 : L = new MutableList from {1,2,3};

i3 : g = f L

o3 = g

o3 : FunctionClosure

i4 : h = f L

o4 = h

o4 : FunctionClosure

i5 : all(3, i -> g i === h i)

o5 = true

i6 : h === g

o6 = false
```

Here, both g and h have a mutable object as a local variable, but even without checking the value of the pointer, it is enough to know that they point to the same address, hence they will give the same output even if L had changed.

**Comment by DanGrayson** [comment]
> No, the values of local variables stored inside a function closure cannot be considered as inputs -- they are part of the function closure, and they affect its behavior. Equal objects must have the same behavior. 

Now you're contradicting what you said before, which is this:  

"consider all mutable objects pointed to by a function closure to be inputs to the function. If two functions applied to the same input (including mutable objects) give the same output, then they are the same."

**Comment by mahrud** [comment]
How am I contradicting myself? I'm repeatedly saying that you can just compare the pointers without looking at their value.

**Comment by DanGrayson** [comment]
Sometimes you seem to be saying that when comparing g with h, you will not consider the value of x, and sometimes you will.  Which is it?
```m2

i1 : f = x -> y -> (t := x; x = y; t);

i2 : g = f 1;

i3 : h = f 2;
```

**Comment by mahrud** [comment]
Ignore the value, compare the pointers, don't look at the value of the pointers.

**Comment by DanGrayson** [comment]
I don't know what you mean by the value of a pointer, but perhaps you are saying that when comparing g and h above, you will  regard g and h as being equal only if the values they have for x are the same as pointers.  Is that right?

**Comment by mahrud** [comment]
Perhaps function closures are implemented in a nonstandard way that I'm unaware of it, leading to confusion. I imagine this is what is happening inside any interpreter [conceivable](https://proxy.c2.com/cgi/wiki?GreenspunsTenthRuleOfProgramming) by me:

1. `f = x -> y -> x + y` is defined in the top level, and is transformed into a lisp-like program:
```lisp
(:(=), :f, (:->, :x, (:block,
      :(#= none:1 =#),
      (:->, :y, (:block,
          :(#= none:1 =#),
          (:call, :+, :x, :y)
        ))
    )))
```
2. `g = f(A)` and `h = f(B)` are defined in the top level, and are transformed into lisp-like programs:
```lisp
(:(=), :g, (:call, :f, :A))
(:(=), :h, (:call, :f, :B))
```
3. At this point, g and h can be compared as follows:
  - start at the root (`:(=)`) and compare the two inputs, return false if not equal
  - `:f` is a pointer, so comparison is done at the pointer level
  - if `:A` and `:B` are pointers, they are compared as pointers, if neither are equality on the objects is checked (e.g. if they were 1 and 2), otherwise they are not equal.
4. There is no possibility of an infinite loop here, because we never look at the content of pointers.

----

Here is the result in Julia, for instance:
```julia
julia> f = x -> y -> x + y
#1 (generic function with 1 method)

julia> g = f(1)
#2 (generic function with 1 method)

julia> h = f(1)
#2 (generic function with 1 method)

julia> g == h
true

julia> g === h
true

julia> k = f(2)
#2 (generic function with 1 method)

julia> g == k
false

julia> g === k
false
```

**Comment by DanGrayson** [comment]
> 1. `g = f(A)` and `h = f(B)` are defined in the top level, and are transformed into lisp-like programs:
> 
> ```lisp
> (:(=), :g, (:call, :f, :A))
> (:(=), :h, (:call, :f, :B))
> ```
> 

I don't understand your syntax, but if `:A` denotes a reference to the variable A, then I disagree that any interpreter would behave that way: when you evaluation `g=f(A)` you'll be passing the value of A to f, not its name.

**Comment by DanGrayson** [comment]
(I deleted my previous reply.)

You omitted a step between 2 and 3 above: evaluation of the assignment statements compiled in 2.

Also, the root of g and h is not `:(=)`.

**Comment by mahrud** [comment]
I updated the lisp code. X and Y are just placeholders. They could be objects like 1 or matrix or pointers like a mutable matrix.

**Comment by DanGrayson** [comment]
When you evaluate `g = f(X)`, X better have a value.  It can't be a place holder.

**Comment by mahrud** [comment]
> (I deleted my previous reply.)
> 
> You omitted a step between 2 and 3 above: evaluation of the assignment statements compiled in 2.
> 
> Also, the root of g and h is not `:(=)`.

Sure, the root is `(:call)`, but surely you understood my point.

> When you evaluate `g = f(X)`, X better have a value. It can't be a place holder.

Come on, Dan, they are placeholders for you and I, not in the language. Do I have to write `%PLACEHOLDER STRING 1%` and `%PLACEHOLDER STRING 2%`?

I don't understand why you're complaining about the minutiae of my pseudo-code and ignoring the substance of my comment, which I'm fairly certain you can extrapolate from your own knowledge.

**Comment by DanGrayson** [comment]
Sorry, but I have not the vaguest idea what the substance of your comment is.

By the way, in M2, the value of a variable is *always* a pointer.

**Comment by mahrud** [comment]
> Sorry, but I have not the vaguest idea what the substance of your comment is.

The substance, summarized neatly in point 4, is that we should be able to check equality of functions via their parsed representation without the danger of an infinite loop, as you indicated. Remember when you said "The code for f===g is designed to never go into an infinite loop, and part of the way of ensuring that is that cycles in the graph of pointers are not traversed"? I gave an algorithm to do so, and presented an example of a language where this is done.

> By the way, in M2, the value of a variable is _always_ a pointer.

Again, X and Y are not variables, they are placeholders for one of the following:
- a mutable object
- an immutable object

We compare immutable objects by their value and mutable objects by the pointer to them. In step 3 above, two mutable objects are equal if they point to the same object. That's all.

**Comment by DanGrayson** [comment]
You seem to think that the value of g is the code for executing `f(A)`.  No, the value of g will be the value obtained by evaluating `f(A)`.

**Comment by mahrud** [comment]
> You seem to think that the value of g is the code for executing `f(A)`. No, the value of g will be the value obtained by evaluating `f(A)`.

This should make comparing g and h even easier then, because we get: `(:->, :y, (:block, (:call, :+, X, :y)))` and `(:->, :y, (:block, (:call, :+, Y, :y)))` (again, X and Y are placeholders, not variables), which we can compare with the algorithm above.

**Comment by DanGrayson** [comment]
I don't even know what you mean by "placeholder".

**Comment by mahrud** [comment]
> I don't even know what you mean by "placeholder".

Put whatever you want in there.

**Comment by DanGrayson** [comment]
There used to be `:x` there -- what happened to it?

**Comment by mahrud** [comment]
> There used to be `:x` there -- what happened to it?

Where? We evaluate `g = f(X)`, so the `:x` in `(:->, :x, (...))` (the code for f) is evaluated and the `:x` is changed to `X`. Isn't this what you meant by "the value obtained by evaluating `f(X)`"?

---

Do you at least understand the particular deficiency of Macaulay2 that I'm pointing to in this issue, or are we just wasting each other's time? If you don't, then look at the Julia example I provided. M2 can't do that, and this issue is saying that it should.

If you do understand the deficiency I'm pointing to, do you disagree that it is a deficiency, do you think fixing it is an impossibility, do you think it simply doesn't matter, or do you not understand my solution for it?

**Comment by DanGrayson** [comment]
> > There used to be `:x` there -- what happened to it?
> 
> Where? We evaluate `g = f(X)`, so the `:x` in `(:->, :x, (...))` (the code for f) is evaluated and the `:x` is changed to `X`. 

No, evaluation of a function doesn't change the code for the function it runs it.

> Isn't this what you meant by "the value obtained by evaluating `f(X)`"?

No.

> 
> Do you at least understand the particular deficiency of Macaulay2 that I'm pointing to in this issue, or are we just wasting each other's time? If you don't, then look at the Julia example I provided. M2 can't do that, and this issue is saying that it should.

I see that you would like comparison of functions to do something different, as Julia does.  I just don't know how to make it behave the way Julia does.

> 
> If you do understand the deficiency I'm pointing to, do you disagree that it is a deficiency, do you think fixing it is an impossibility, do you think it simply doesn't matter, or do you not understand my solution for it?

I disagree that it's a deficiency.  I don't understand your proposal.

**Comment by DanGrayson** [comment]
By the way, evaluation of 
```m2
i1 : z = something ;

i2 : f = x -> y -> (foo(x); x=y ;)

i3 : g = f z ;
```
results in `g`  being a "function closure".  A function closure contains, among other things, a pointer the the value that z had which line 3 was executed, which is used as the value of x when the code `x=y` is (later) executed.

Thus `g` is not an entity that can be completely captured by looking at its source code, as you seem to imply.

**Comment by mahrud** [comment]
> Thus `g` is not an entity that can be completely described by looking at its source code, as you seem to imply.

The function closure g, as you say, has "a pointer to the value that z had when line 3 was executed". If another function closure h is defined in the next line, it will also have a pointer to the same value of z, hence the pointers are equal and can be compared. How could this possibly end in an infinite loop?

Maybe function closures in M2 are weird, in which case we can improve them, but the information in a function closure should be the same as the information in `(:call, :f, :z)`, where, again, both `f` and `z` can be compared.

**Comment by DanGrayson** [comment]
> > Thus `g` is not an entity that can be completely described by looking at its source code, as you seem to imply.
> 
> The function closure g, as you say, has "a pointer to the value that z had when line 3 was executed". If another function closure h is defined in the next line, it will also have a pointer to the same value of z, hence the pointers are equal and can be compared. How could this possibly end in an infinite loop?

If there is a cycle in the pointer-graph, it could end in an infinite loop.

Here's how to create a function closure with a cycle of pointers in it:
```m2
i2 : f = x -> y -> x=y ;

i3 : g = f 1 ;

i4 : g g ;
```
Now the function `g` points to itself, because a pointer to `g` is stored as the value of the variable `x` in `g`.

**Comment by mahrud** [comment]
Please elaborate here. I don't see any infinite loops.

**Comment by DanGrayson** [comment]
While evaluating whether g is equal to something else that looks much like it, call it h, eventually you'll check whether the value stored under x in g is the same as the value stored under x in h, so you'll come back right back to evaluating whether g is equal to h.  And again.  And again.

**Comment by mahrud** [comment]
> you'll come back right back to evaluating whether g is equal to h. And again. And again.

You seem to be implying that when `g g;` is called, the definition of `g` changes to something like `f g`. If this is the case, then indeed function closures are implemented in a nonstandard way. It shouldn't be possible to change anything about g after line 3 in your example.

That seems to be the case:
```m2
i1 : f = x -> y -> (print(x,y); x=y);

i2 : g = f 1 ;

i3 : g(2)
(1, 2)

o3 = 2

i4 : g(3)
(2, 3)

o4 = 3

i5 : g(4)
(3, 4)

o5 = 4

i6 : g(4)
(4, 4)

o6 = 4

i8 : g g
(4, g)

o8 = g

o8 : FunctionClosure

i9 : g 1
(g, 1)

o9 = 1
```

In other words, variables in function closures are "static", which is not standard as far as I know. So now the question is, what purpose does this serve?

**Comment by DanGrayson** [comment]
> > you'll come back right back to evaluating whether g is equal to h. And again. And again.
> 
> You seem to be implying that when `g g;` is called, the definition of `g` changes to something like `f g`.

No, definitions of functions don't change.  What changed during the evaluation of `g g` is the value of x stored in the function closure.

> If this is the case, then indeed function closures are implemented in a nonstandard way. It shouldn't be possible to change anything about g after line 3 in your example.

The assignment statement `x=y` easily changes things after line 3 in my example.

...

> In other words, variables in function closures are "static", which is not standard as far as I know. So now the question is, what purpose does this serve?

I don't know what you mean by "static" -- that word has the connotation of "not changing", whereas the value stored for x in g can change.

It's certainly standard.  Here's the same code in julia:
```julia
julia> f = x -> y -> x = y;

julia> g = f(1);

julia> h = g(g);
```

**Comment by mahrud** [comment]
Sorry I meant static as in the C/C++ keyword for variable lifetime: https://en.cppreference.com/w/cpp/language/storage_duration

I'll look to see how Julia avoids infinite loop then.

**Comment by mahrud** [comment]
This is interesting, not quite sure how to interpret it:
```julia
julia> f = x -> y -> x + y
#1 (generic function with 1 method)

julia> g = f(1); h = f(1); g == h
true

julia> f = x -> y -> x = y
#5 (generic function with 1 method)

julia> g = f(1); h = f(1); g == h
false
```

**Comment by DanGrayson** [comment]
Maybe Julia uses the presence of assignment statements to determine whether g and h are mutable.  In the (first) immutable case, it compares the values and succeeds.  In the (second) mutable case it refuses to be sucked into a possible infinite loop and simply returns false.

**Comment by mahrud** [comment]
I think the thing that bothers me here is that function closures aren't "functional" in the sense of functional programming. The side effect of changing the state of a function closure by _calling_ it seems unsafe. Is it intentionally used anywhere?

**Comment by DanGrayson** [comment]
Yes, Macaulay2 is not a functional programming language.  Of course, functions only do stuff when you call them.  Maybe what you really object to is assignment statements, and, of course, they are used all over our code.  In a functional programming language there would be none.  Julia isn't functional, either.

**Comment by DanGrayson** [comment]
Julia has the same convention as M2 regarding comparison of mutable objects:
<img width="689" alt="Screen Shot 2020-10-31 at 7 39 41 PM" src="https://user-images.githubusercontent.com/700228/97792777-e54aa300-1bb0-11eb-892d-f8c21d0ade21.png">


https://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.394.2808&rep=rep1&type=pdf

**Comment by DanGrayson** [comment]
But this seems to squash my theory:
```julia

julia> f = (x -> y -> x=y)(1);

julia> ismutable(f)
false
```

**Comment by mahrud** [comment]
This will shed some light on what is happening: https://discourse.julialang.org/t/how-is-equality-of-anonymous-function-closures-checked/49397/9

**Comment by DanGrayson** [comment]
So I was right.

**Comment by mahrud** [comment]
Not sure how you conclude that. In particular, Julia doesn't seem to have an issue with equality of anonymous functions. Function closures seem to depend on whether they contain mutable objects. This should be easily implementable.

**Comment by DanGrayson** [comment]
I'm saying that this was right: "Maybe Julia uses the presence of assignment statements to determine whether g and h are mutable. In the (first) immutable case, it compares the values and succeeds. In the (second) mutable case it refuses to be sucked into a possible infinite loop and simply returns false."
