### ISSUE TITLE
components for other bilinear functors

### ISSUE THREAD

**Issue by DanGrayson** [Macaulay2/M2#1569]
We currently keep track of the components of direct sums of modules.  It would be good to do the same thing for `M**N` and `Hom(M,N)`.    @mikestillman  and @eisenbud want this facility.  Maybe also generate the induced sum components if M and/or N have sum components.  That might also make it possible to generate the associativity isomorphisms in a robust new way.

It should also be possible to attach labels to modules, and have them get used.  For example, if M and N are labelled x and y, then x and y should be usable for getting the components of M++N.  (Hmm?  What does getting M from x have to do with M++N?)

Also, it would be good to have tensor product of multiple modules, rather than of just 2.  That would be analogous to `directSum`.

**Comment by mahrud** [comment]
> Also, it would be good to have tensor product of multiple modules, rather than of just 2. That would be analogous to `directSum`.

@pepperhdj suggested the this in #1222.

**Comment by mahrud** [comment]
Can #417 be closed now?

**Comment by DanGrayson** [comment]
> Can #417 be closed now?

Commented and closed.

**Comment by mahrud** [comment]
What about #535? It isn't fixed yet, but it might be easier to fix now.
