### ISSUE TITLE
height of empty Net

### ISSUE THREAD

**Issue by pzinn** [Macaulay2/M2#1594]
something I don't understand:
```
i1 : a=net ""

o1 = 

i2 : b=stack{}

o2 = 

i3 : height a

o3 = 1

i4 : height b

o4 = 0
```
why are the results different? and which one is the "correct" one?

**Comment by DanGrayson** [comment]
I think they're both correct.  All strings convert to nets of height 1.

**Comment by pzinn** [comment]
OK!
