### ISSUE TITLE
oddities in documentation

### ISSUE THREAD

**Issue by pzinn** [Macaulay2/M2#1601]
I'm taking a closer look at the documentation and finding various oddities. here's one:
```
i1 : help hooks

o1 = hooks -- list hooks
     *******************

     Description
     ===========

     Synopsis
     ========

       * Usage: 
             methods(X, f)
       * Inputs:  * x, a mutable hash table
       * Outputs:  * a vertical list of those hooks associated with X#f

[...]

     Synopsis
     ========

       * Usage: 
             methods(X, f)
       * Inputs:  * x, a hash table
       * Outputs:  * a vertical list of those hooks associated with X.cache#f
[...]
```
`methods` -> `hooks` ?

**Comment by DanGrayson** [comment]
That's also fixed by undoing commit c7f4e4c9f0beeb208f779cc374266cda26f48f3b

**Comment by pzinn** [comment]
I'm not sure I understand how it's related to that commit. the issue is Usage: "methods".

**Comment by pzinn** [comment]
maybe I'll just use this issue to list other documentation minor issues. renaming

**Comment by DanGrayson** [comment]
Because the list of inputs use LI : 
```m2

i9 : (help hooks)#1#1#1#1

o9 = Inputs:  * x, a mutable hash table

o9 : LI
```

**Comment by pzinn** [comment]
the documention of `symbol :=` says
```
     By contrast, addition of complex numbers is not internal, and can be overridden.

```
but that doesn't seem true; running the example below:
```
i3 : CC + CC := (w,z) -> w*z

o3 = -*Function[stdio:4:18-4:23]*-

o3 : FunctionClosure

i4 : ii+ii

o4 = 2*ii

o4 : CC (of precision 53)
```

**Comment by pzinn** [comment]
> Because the list of inputs uses LI :
> 
> ```m2
> i9 : (help hooks)#1#1#1#1
> 
> o9 = Inputs:  * x, a mutable hash table
> 
> o9 : LI
> ```

I'm thoroughly confused. the Inputs line looks fine to me.

**Comment by mahrud** [comment]
This doesn't seem to be specifically related to hooks, but since an existing PR is making substantial changes to the documentation of hooks, please don't make any changes there.

**Comment by pzinn** [comment]
how is this not related to hooks? all I'm saying is, the Usage seems wrong in the documentation of hooks.
but if there is a PR changing this documentation, I'll just wait.

**Comment by mahrud** [comment]
I think there was some confusion from the beginning. Perhaps is better to not have unrelated problems in the same issue.

The incorrect usage in the documentation of hooks is fixed in #1385.
The `CC + CC` issue is unrelated.
The issue Dan is talking about is also unrelated.

**Comment by pzinn** [comment]
the problem, I have 10 more such minor things... should I open an issue for each of them? seems a bit silly.

**Comment by DanGrayson** [comment]
> > Because the list of inputs uses LI :
> > ```m2
> > i9 : (help hooks)#1#1#1#1
> > 
> > o9 = Inputs:  * x, a mutable hash table
> > 
> > o9 : LI
> > ```
> 
> I'm thoroughly confused. the Inputs line looks fine to me.

Version 1.16:

```m2

i9 : (help showStructure)#1#2#1#1

o9 = Inputs:
       * X, a type
       * Y, a type

o9 : LI
```

Now:

```m2

i1 : (help showStructure)#1#2#1#1

o1 = Inputs:  * X, a type
              * Y, a type

o1 : LI
```

Now, but with that commit undone:

```m2

i1 : (help showStructure)#1#2#1#1

o1 = Inputs:
       * X, a type
       * Y, a type

o1 : LI
```

**Comment by pzinn** [comment]
yes, I understand now. but my issue was unrelated, as Mahrud pointed out.

**Comment by pzinn** [comment]
```
help minus
...
minus(x,y) yields x-y but see also difference.
...
```
but
```
i1 : minus(1,2)
stdio:1:1:(3): error: expected 1 argument
```

**Comment by DanGrayson** [comment]
I think that's an error in the documentation.

**Comment by pzinn** [comment]
```
help exit
...
Functions registered with addStartFunction are called
...
```
shouldn't it be `addEndFunction`?

**Comment by DanGrayson** [comment]
> ```
> help exit
> ...
> Functions registered with addStartFunction are called
> ...
> ```
> 
> shouldn't it be `addEndFunction`?

Thanks, I'm fixing it ...

**Comment by DanGrayson** [comment]
> > ```
> > help exit
> > ...
> > Functions registered with addStartFunction are called
> > ...
> > ```
> > 
> > 
> > shouldn't it be `addEndFunction`?
> 
> Thanks, I'm fixing it ...

... in commit 63ba3d7110cc0c4eb3e0c298a4f7a3401f3cad2b

**Comment by pzinn** [comment]
```
help binomial
...
Caveat
Doesn't do polynomials, things like binomial(x,3) where x is an element of a ring other than ZZ
```
but
```
i1 : R=QQ[x];binomial(x,3)

     1 3   1 2   1
o2 = -x  - -x  + -x
     6     2     3

o2 : R
```

**Comment by pzinn** [comment]
one more... soon I'll start fixing them too!
```
i1 : help "lists and sequences"
.
.
.
     Lists and sequences can be used as vectors, provided their elements are the
     sorts of things that can be added and mutliplied.

     +---------------------------+
     |  10000*{3,4,5} + {1,2,3}  |
     +---------------------------+
```
only works with lists, not sequences.
```
i2 : (1,2,3)+(4,5,6)
stdio:2:8:(3): error: no method for binary operator + applied to objects:
--            (1, 2, 3) (of class Sequence)
--      +     (4, 5, 6) (of class Sequence)

```

**Comment by pzinn** [comment]
and another, from the help page "kernel and image of a ring map":
The kernel and image of a ring map can be computed using image and kernel . The output of ker is an ideal and the output of image is a ring or quotient ring.
but 
```
i1 : image map(ZZ[x],ZZ[y],{x})
stdio:3:1:(3): error: no method found for applying image to:
     argument   :  map (ZZ[x], ZZ[y], {x}) (of class RingMap)
```
the help seems to suggest that it should simply be implemented as source / kernel, but it was never done.

**Comment by DanGrayson** [comment]
> and another, from the help page "kernel and image of a ring map":
> The kernel and image of a ring map can be computed using image and kernel . The output of ker is an ideal and the output of image is a ring or quotient ring.
> but
> 
> ```
> i1 : image map(ZZ[x],ZZ[y],{x})
> stdio:3:1:(3): error: no method found for applying image to:
>      argument   :  map (ZZ[x], ZZ[y], {x}) (of class RingMap)
> ```
> 
> the help seems to suggest that it should simply be implemented as source / kernel, but it was never done.

We don't have a notion of "subring", so implementing the image of a ring homomorphism is not possible.  But we do implement the coimage:
```m2

i6 : coimage map(QQ[x],QQ[y,z],{x,x})

     QQ[y..z]
o6 = --------
       y - z

o6 : QuotientRing
```

**Comment by pzinn** [comment]
I'm not arguing with the logic of the code, which I agree with, just the documentation. so the reference to `image` should be removed and replaced with a reference to `coimage`.

**Comment by DanGrayson** [comment]
Right.

**Comment by pzinn** [comment]
The example for `override` is not so great: it should declare `defs` as an `OptionTable` rather than a `HashTable`, as the text right above it suggests:
```
override(defaults,args) overrides default values for optional arguments present in the argument sequence args.
One possibility is for the argument defaults to be an immutable hash table (of type OptionTable)
...
defs = new HashTable from { a => 1, b => 2 };
```

**Comment by DanGrayson** [comment]
Thanks, fixed in commit b68711b59fecd11714b2775973796d9de1ca2008

**Comment by pzinn** [comment]
another minor issue to add to the list:
```
i1 : scan({1,2,3},{10,100,1000},(i,j)->print(i+j))
11
102
1003
```
works fine but `help scan` or `methods scan` do not include the possibility of having *two* lists to scan from (just like `apply`)

**Comment by pzinn** [comment]
`help memoize` says "Warning: when the value returned by f is null, it will always be recomputed, even if the same arguments are presented.". I don't think this is true:
```
i1 : f=memoize(x->print("new value",x))

o1 = f

o1 : FunctionClosure

i2 : f 1
(new value, 1)

i3 : f 1

i4 : f 1 === null

o4 = true
```

**Comment by pzinn** [comment]
This thread has served us well, but I think it's time to retire it.
