### ISSUE TITLE
missing methods

### ISSUE THREAD

**Issue by mahrud** [Macaulay2/M2#1604]
Here are various things that are incomplete:
```m2
i2 : 0 < #methods(resolution, Ideal)

o2 = false

i9 : #methods symbol= === #methods sequence symbol=

o9 = false

i11 : code methods (symbol!, symbol=)

o11 = -- no method function found: = !
```
There are more. I'll fix these in #1385

**Comment by DanGrayson** [comment]
You probably meant `0 < # methods(resolution, Ideal)`

**Comment by mahrud** [comment]
Yes. Also, looking at the code for methods, I don't understand the point of these lines:
- This one implies there are types `T` with a hash table entry `K => f` where `K` is a keyword and `f` is a function. Is there any such an example? I tried adding such a key to a type, but it wasn't callable.
https://github.com/Macaulay2/M2/blob/8219a0a0a89cb4d626f1d6776bb4c9164feb126b/M2/Macaulay2/m2/code.m2#L109
- This line implies the existence of types `T1` with a hash table entry `T2 => f` where `T2` is also a type. Is there such an example? I also couldn't construct anything like this.
https://github.com/Macaulay2/M2/blob/8219a0a0a89cb4d626f1d6776bb4c9164feb126b/M2/Macaulay2/m2/code.m2#L120

**Comment by DanGrayson** [comment]
The code is strange, because `instance(key, Symbol) and instance(key,Keyword)` is equivalent to `instance(key,Keyword)`.

I managed it this way:
```m2

i2 : R = QQ[x]

o2 = R

o2 : PolynomialRing

i3 : R#symbol ! = p -> p^3;

i4 : x!

      3
o4 = x

o4 : R
```

Perhaps `if key === F then found#(F,x) = true ` is not needed and could go.

**Comment by mahrud** [comment]
Well, I changed and simplified it quite a bit. I think everything that was returned before is still returned, and a bunch of things that were returned incorrectly (e.g `code` didn't work on them) are now corrected.

Try it out and let me know if anything is missing.

**Comment by mahrud** [comment]
Were you able to create anything of the second type? Like `T1.T2`?

**Comment by DanGrayson** [comment]
I think you mean `T1#T2` -- in any case, no, I think it's not a thing.
