### ISSUE TITLE
topCoefficients crashes easily

### ISSUE THREAD

**Issue by DanGrayson** [Macaulay2/M2#162]
i1 : topCoefficients matrix {{1}}
-- SIGSEGV
-- stack trace, pid 70500:
level 0 -- return addr: 0x0x10471947f -- frame: 0x0x10ae26110
level 1 -- return addr: 0x0x10474425b -- frame: 0x0x10ae26130
level 2 -- return addr: 0x0x107f24da0 -- frame: 0x0x107f22840
-- end stack trace

Process M2 exited abnormally with code 1

**Comment by mikestillman** [comment]
fixed in commit 5fa9b4ae9943599644e5748f79cf6ec4fa7d0bf8
