### ISSUE TITLE
Coefficient ring of a local ring

### ISSUE THREAD

**Issue by mahrud** [Macaulay2/M2#1625]
It's unclear to me what the correct answer should be. Specifically, I believe `coefficientRing localRing(ZZ[x], ideal x)` should be `QQ`, not `ZZ`:

```m2
i1 : needsPackage "LocalRings"

o1 = LocalRings

o1 : Package

i2 : RP = localRing(ZZ[x], ideal x)

o2 = RP

o2 : LocalRing, maximal ideal x

i3 : f=2_RP; g=3_RP

o4 = 3

o4 : RP

i5 : f/g

     2
o5 = -
     3

o5 : RP
```

On the other hand, per @DanGrayson:

> It's not correct to take the fraction field here, as not all nonzero elements of the coefficient ring of R become invertible in R_P.  Example:
```m2

i1 : needsPackage "LocalRings";

i3 : R = ZZ[x];

i4 : I = ideal(2,x)

o4 = ideal (2, x)

o4 : Ideal of R

i5 : S = localRing (R,I)

o5 = S

o5 : LocalRing, maximal ideal (2, x)

i6 : coefficientRing S

o6 = QQ

o6 : Ring
```

Also, normally the coefficient ring is one of the base rings:
```m2

i17 : S.baseRings

o17 = {ZZ, R}

o17 : List
```

_Originally posted by @DanGrayson in https://github.com/Macaulay2/M2/pull/1385#discussion_r531232374_

**Comment by DanGrayson** [comment]
I think the coefficient ring of a local ring R_P should be the coefficient ring of R.

**Comment by mahrud** [comment]
I think I appreciate the simplicity of leaving it this way, and I don't have a specific reason why this could make doing math harder.

**Comment by DanGrayson** [comment]
The example with (2,x) in ZZ[x] shows the result returned is wrong mathematically, so it should be fixed.

**Comment by mahrud** [comment]
It's returning ZZ now, is that wrong?

**Comment by DanGrayson** [comment]
So it is, I didn't know it had changed, closing, thanks.
```m2

+ M2 --no-readline --print-width 195
Macaulay2, version 1.16.99
with packages: ConwayPolynomials, Elimination, IntegralClosure, InverseSystems, LLLBases, MinimalPrimes, PrimaryDecomposition, ReesAlgebra, Saturation, TangentCone

i1 : needsPackage "LocalRings";

i2 : R = ZZ[x];

i3 : I = ideal(2,x)

o3 = ideal (2, x)

o3 : Ideal of R

i4 : S = localRing (R,I)

o4 = S

o4 : LocalRing, maximal ideal (2, x)

i5 : coefficientRing S

o5 = ZZ

o5 : Ring
```
