### ISSUE TITLE
more than two summand in components?

### ISSUE THREAD

**Issue by pzinn** [Macaulay2/M2#1629]
I'm not sure if this is a bug or a feature:
```
i1 : ZZ^3 ++ ZZ^5 ++ ZZ^7 

       15
o1 = ZZ

o1 : ZZ-module, free

i2 : components oo

        8    7
o2 = {ZZ , ZZ }

o2 : List
```
shouldn't it keep track of the 3 parts?

**Comment by DanGrayson** [comment]
It's just the way syntax works : `++` is a binary operator.  Use `directSum` to form sums of more than 2 modules.

**Comment by pzinn** [comment]
yes, but shouldn't `directSum` be smarter? why shouldn't `directSum(ZZ^3,directSum(ZZ^5,ZZ^7))` result in the same as `directSum(ZZ^3,ZZ^5,ZZ^7)` ?

**Comment by DanGrayson** [comment]
I think it is smarter:
```m2

i1 : components directSum(ZZ^3,ZZ^5,ZZ^7)

        3    5    7
o1 = {ZZ , ZZ , ZZ }

o1 : List

i2 : components directSum(ZZ^3,directSum(ZZ^5,ZZ^7))

        3    12
o2 = {ZZ , ZZ  }

o2 : List
```

**Comment by DanGrayson** [comment]
Maybe I misunderstood: are you saying you'd like the components of ((M++N)++P) to be M, N, and P?

**Comment by pzinn** [comment]
That's right.

**Comment by DanGrayson** [comment]
Ah, that's tempted me at various times.  One drawback is that you lose information about how the module was formed.  Another problem is that the bookkeeping is much larger, especially if you extend the idea to other situations:  Should R^n have n components?  Should Hom(M,N++P) and M ** (N++P) have components?  What about Tor and Ext?

**Comment by pzinn** [comment]
OK. I want to think about this some more.

**Comment by mikestillman** [comment]
One problem with doing that automatically, is that when one is creating block matrices (e.g. In the EagonResolutions package), one would need to make special cases depending on whether the summands were already direct sums.  I think that the way it is done now (2 at a time with ++, as many as desired with directSum) is good.  I too at first wanted to change this behavior.

**Comment by pzinn** [comment]
I don't see why that's a problem. This can be implemented incrementally, not necessarily covering all the cases at once. But basic associativity of direct sum seems reasonable.

**Comment by DanGrayson** [comment]
Actually, when the modules are general subquotients, the (M++N)++P and M++(N++P) are not exactly equal.

**Comment by pzinn** [comment]
> One drawback is that you lose information about how the module was formed.

on the contrary, the information is lost now:
```
i1 : R=QQ[x]; (R^1++R^2)++R^3

      6
o2 = R

o2 : R-module, free

i3 : peek oo.cache

o3 = CacheTable{cache => MutableHashTable{}              }
                degrees => {{0}, {0}, {0}, {0}, {0}, {0}}
                rank => 6
                                         3   3
                formation => directSum (R , R )
                                3   3
                components => {R , R }
```
the `formation` should have the iterated `directSum`.

> Actually, when the modules are general subquotients, the (M++N)++P and M++(N++P) are not exactly equal.

What do you mean? do you have a simple example?

**Comment by DanGrayson** [comment]
> > One drawback is that you lose information about how the module was formed.
> 
> on the contrary, the information is lost now:

No, it's recoverable:
```m2
Macaulay2, version 1.16.99
with packages: ConwayPolynomials, Elimination, IntegralClosure, InverseSystems, LLLBases, MinimalPrimes, PrimaryDecomposition, ReesAlgebra, Saturation, TangentCone

i1 : R=QQ[x]; M=(R^1++R^2)++R^3;

i3 : formation M

                 3   3
o3 = directSum (R , R )

o3 : Expression of class FunctionApplication

i5 : formation o3#1#0

                 1   2
o5 = directSum (R , R )

o5 : Expression of class FunctionApplication
```

**Comment by DanGrayson** [comment]
> > Actually, when the modules are general subquotients, the (M++N)++P and M++(N++P) are not exactly equal.
> 
> What do you mean? do you have a simple example?

Oops, no, I was wrong about that -- they are equal.

**Comment by pzinn** [comment]
ah yes, I spoke too fast about the information being lost. In any case `formation` and `components` contain different information -- my proposal wouldn't affect `formation`.

**Comment by DanGrayson** [comment]
We might want to get rid of  "components", since "formation" does everything it does.

I think, by making `(A++B)++C` have A, B, and C as components, you remove options from the user, who might want a module with 2 components.  Alternatively, if the user wants a module with 3 components, `directSum(A,B,C)` is available.

**Comment by mahrud** [comment]
> One of the underlying issues, when one writes `A++B++C`, one doesn't necessarily think of it as `(A++B)++C`.

This is arguably the fault of the user, since `++` is a binary operator, and so inevitably one of them has to go first. I imagine there could be an interpreter rule to change such extended binary operations to an operation on a sequence, but it's probably much simpler for the user to use `directSum` instead.

**Comment by mikestillman** [comment]
It is important to think of `(A++B)++C` as a sum of two modules.  For instance, `D := A++B` might have been constructed elsewhere, and you might be doing `D ++ C`, and you don't want to be surprised at the internal structure of `D`.  This gets used in a number of places, e.g. in the `EagonResolution` package.

**Comment by pzinn** [comment]
OK I'll give up on this for now.
Anyway this was all because I needed to write matrices in block form, and I wrote this nice little function `block` (note the mode agnosticity), and was disappointed when `++` didn't work as I expected it to.
![block](https://user-images.githubusercontent.com/4632711/102657856-8970c380-41ca-11eb-9b0d-7b5742bb4f7b.png)

**Comment by DanGrayson** [comment]
That looks great!

And by the way, "matrix" does the right thing:
```m2
Macaulay2, version 1.16.99
with packages: ConwayPolynomials, Elimination, IntegralClosure, InverseSystems, LLLBases, MinimalPrimes, PrimaryDecomposition, ReesAlgebra, Saturation, TangentCone

i1 : R = ZZ^2; f = matrix {{3,4},{5,6}}; matrix {{f,0,0},{0,f,0},{0,0,f}}

              2        2
o2 : Matrix ZZ  <--- ZZ

o3 = | 3 4 0 0 0 0 |
     | 5 6 0 0 0 0 |
     | 0 0 3 4 0 0 |
     | 0 0 5 6 0 0 |
     | 0 0 0 0 3 4 |
     | 0 0 0 0 5 6 |

              6        6
o3 : Matrix ZZ  <--- ZZ

i4 : components source o3

        2    2    2
o4 = {ZZ , ZZ , ZZ }

o4 : List

i5 : components target o3

        2    2    2
o5 = {ZZ , ZZ , ZZ }

o5 : List
```

**Comment by pzinn** [comment]
I did not know `matrix` could do that, interesting.
Anyway, it's time to close this thread; I won't change anything and will use if necessary `formation` to reconstruct recursively the full block decomposition.
