### ISSUE TITLE
Escaped \ in documentation

### ISSUE THREAD

**Issue by pzinn** [Macaulay2/M2#1632]
Yet another documentation problem, which I think deserves its own issue...
help.m2 uses `format` quite a bit for strings, but that can cause problems, cf
```
i1 : help symbol \

o1 = \ -- a binary operator
     **********************

     Ways to use \:
     ==============

       * "Command \ Set"
       * "Function \ Set"
       * "Function \\ Ideal" -- see "Ideal / Function" -- apply a function to generators of an ideal
       * "Command \\ VirtualTally" -- see "VisibleList / Function" -- apply a function to elements of a list
       * "Command \\ VisibleList" -- see "VisibleList / Function" -- apply a function to elements of a list
       * "Function \\ VirtualTally" -- see "VisibleList / Function" -- apply a function to elements of a list
       * "Function \\ VisibleList" -- see "VisibleList / Function" -- apply a function to elements of a list
       * "RingMap \\ List" -- see "VisibleList / Function" -- apply a function to elements of a list
       * "SelfInitializingType \\ VisibleList" -- see "VisibleList / Function" -- apply a function to elements of a list

...
```
where *some* of the `\` are doubled, as pointed out below...

**Comment by mahrud** [comment]
Hmm, why are the first couple not doubled?

**Comment by DanGrayson** [comment]
This worked in 1.16 -- let's get it fixed for 1.17.

**Comment by mahrud** [comment]
I don't think it's as simple as that.

As I'm sure you know, `* String` is a method that prints the help node with the given formatted key, and is very useful when used in Emacs. Now observe this:
```m2
i1 :        * "Command \\ VisibleList" -- see "VisibleList / Function" -- apply a function to elements of a list

o1 = VisibleList / Function
     **********************
....

i2 :        * "Command \ VisibleList" -- see "VisibleList / Function" -- apply a function to elements of a list
stdio:2:10:(0): error: unknown escape sequence: \ 
```

So you're picking between two opposing features here :/

**Comment by pzinn** [comment]
I'm not sure I understand how that's related. you certainly should type `\\` as input. I'm talking about the output here.

**Comment by pzinn** [comment]
oh. I see. it's because you want to be able to copy/paste in emacs *sigh*.

**Comment by pzinn** [comment]
I've been using my own interface for too long, I forget these things :-P

**Comment by DanGrayson** [comment]
That's a good point Mahrud has made -- can we make it both look and act right?

**Comment by mahrud** [comment]
I don't know how. In times like this I see the wisdom of keeping single quotes for strings 😁

**Comment by pzinn** [comment]
Right. I think everything works as intended, then. My mistake.
It does look a bit weird that the lines with an unquoted string have a single `\`, whereas those with a quoted string have a double `\\`.

**Comment by DanGrayson** [comment]
> I don't know how. In times like this I see the wisdom of keeping single quotes for strings 😁
> 
> Maybe we could put it in /// if there are certain characters in the key, but that looks rather ugly and confusing.

A big regret of mine is that /// is not """ instead.

**Comment by pzinn** [comment]
Actually, my statement above is incorrect in normal mode (say in emacs): all lines have quoted strings, even the ones with single `\` (again, I got confused because in webapp mode the lines with single `\` are unquoted, as I stated). I was about to close this issue but there remains this minor mystery...
