### ISSUE TITLE
Selecting preloaded packages in init.m2

### ISSUE THREAD

**Issue by mahrud** [Macaulay2/M2#1644]
> A general comment, I think it would be good if the user could control what packages were loaded by default.

_Originally posted by @kschwede in https://github.com/Macaulay2/M2/issues/641#issuecomment-309957744_

This would likely involve some changes here:

https://github.com/Macaulay2/M2/blob/1e47260755100936bafd60d64013672dedd3941f/M2/Macaulay2/m2/last.m2#L30-L54

**Comment by mahrud** [comment]
@d-torrance can you think of a nice way to do this? It would be nice to customize the list. For instance, I don't know why `ConwayPolynomials, InverseSystems, LLLBases, OnlineLookup, ReesAlgebra, TangentCone` are loaded by default.

**Comment by mahrud** [comment]
That seems worth a try!

**Comment by d-torrance** [comment]
Fixed in #3312
