### ISSUE TITLE
Split factory into its own set of packages in Debian/Ubuntu

### ISSUE THREAD

**Issue by d-torrance** [Macaulay2/M2#1681]
> We definitely need all the gf tables.
> 
> Ideally factory and gftables would be debian packages, too, and we could just use them. But maybe now is not the time to arrange that, if time is tight.

That should be pretty easy to do.  We could still just have one singular source package, but split out the factory stuff into a few binary packages (probably something like `libsingular-factory4`, `libsingular-factory-dev`, and maybe `singular-factory-data`) that Macaulay2 could depend on.

Because of the new binary packages, it would have to go through the NEW queue again.  So it's probably best to wait until after bullseye is released and shoot for Debian 12 (bookworm).  I'd also have to make sure it's okay with the other interested parties -- in particular the Sage maintainers.

_Originally posted by @d-torrance in https://github.com/Macaulay2/M2/issues/1679#issuecomment-742755726_

**Comment by d-torrance** [comment]
Note to self:  Investigate which of these actually use factory.

```
(sid-amd64)profzoom@peg-amy:/$ apt rdepends libsingular4m1
libsingular4m1
Reverse Depends:
  Depends: libsingular4-dev (= 1:4.1.1-p2+ds-4+b2)
  Depends: singular-ui-xterm
  Depends: singular-ui-emacs
  Depends: singular-ui (= 1:4.1.1-p2+ds-4+b2)
  Depends: singular-modules (= 1:4.1.1-p2+ds-4+b2)
  Depends: macaulay2
  Depends: sagemath
  Depends: libpynac18py3
```

**Comment by d-torrance** [comment]
I think this is still a problem, but it's a Debian issue and not a Macaulay2 one. Closing

**Comment by mikestillman** [comment]
@d-torrance @DanGrayson @mahrud A question about this: It sounds like we are not using the latest version of factory?  Can you check and/or confirm that we are up to date in cmake and autotools build with that?
