### ISSUE TITLE
line wrapping for net(Ring)

### ISSUE THREAD

**Issue by mahrud** [Macaulay2/M2#1683]
I noticed this on the documentation of Grassmannian, which is unreadable on a terminal (it's strange, but readable on emacs)
![image](https://user-images.githubusercontent.com/3147718/101874489-951b1500-3b4e-11eb-9667-0b369d897121.png)

The ideal itself has a ton of generators, but `(net, Ideal)` wraps properly, whereas `(net, Ring)` doesn't seem to wrap.

**Comment by mahrud** [comment]
The same is, of course, true of any other object that has any relation to such a ring, like `Module`, `Proj`, `Spec`, and even worse for `Matrix` or `RingMap` which involve more than one ring.

**Comment by DanGrayson** [comment]
A fix is this:
<img width="1372" alt="Screen Shot 2020-12-11 at 7 44 40 PM" src="https://user-images.githubusercontent.com/700228/101969319-62722a80-3be9-11eb-90f1-d4bdb9a1d50d.png">

**Comment by mahrud** [comment]
That works for the ring itself, but doesn't work when the ring appears in the after print of another object:
![image](https://user-images.githubusercontent.com/3147718/101969899-ba5e6080-3bec-11eb-8a83-c5cdfa48a19d.png)
Here's the example, by the way:
```m2
J = Grassmannian(2,5, CoefficientRing => ZZ/31, Variable => T);
```

**Comment by mahrud** [comment]
It would be good to move this code to net.m2 maybe:
https://github.com/Macaulay2/M2/blob/1a01f368e88857a0516858f968cad2cd23a05a49/M2/Macaulay2/m2/last.m2#L18-L25

**Comment by mahrud** [comment]
It would perhaps be good if printing the generators of rings in these cases used `runLengthEncode`.

**Comment by DanGrayson** [comment]
If the terminal is xterm, then the option "+aw" can be used to disable line wrapping.  The corresponding resource can also be set so it happens always.

**Comment by mahrud** [comment]
Right, but that's not relevant here. If I set printWidth I actually want it
to be followed. See the online documentation for Grassmannian for instance,
where the ideal is wrapped but the ring makes the webpage stretch
horizontally.

**Comment by DanGrayson** [comment]
Some users may prefer to have all that junk just truncated.

**Comment by mahrud** [comment]
I'm not sure if I understand what you're arguing in favor of. Note that `describe` does the right thing with the generators, using the `..` notation to write it succinctly.

I'm only saying that the printed output should always be readable, and if printWidth is set then it should also be wrapped correctly by M2 so the monomials and their exponents or indices aren't printed far apart..

**Comment by DanGrayson** [comment]
> I'm not sure if I understand what you're arguing in favor of. Note that `describe` does the right thing with the generators, using the `..` notation to write it succinctly.

That's certainly a good idea.

> 
> I'm only saying that the printed output should always be readable, and if printWidth is set then it should also be wrapped correctly by M2 so the monomials and their exponents or indices aren't printed far apart..

Emacs users especially may prefer wide output not to be wrapped.

**Comment by mahrud** [comment]
Oh, I just realized that printWidth isn't set to 0 on emacs, it's set to the detected width. But still, if matrices and ideals are wrapped, the ring should be too.

But anyway, I think once we get it to use `..` that'll be irrelevant because in almost all cases the generators are sequential.

**Comment by mahrud** [comment]
Can you point me to how this should be used? Not sure how for instance this is printed:
```m2
              ZZ
o4 : Ideal of --[T     ,  ...
              31  0,1,2
```

**Comment by DanGrayson** [comment]
That code is found this way:
```m2

i16 : code lookup ({Standard,AfterPrint},Ideal)

o16 = /Applications/Macaulay2-1.16.99/share/Macaulay2/Core/matrix1.m2:486:67-489:88: --source code:
      Ideal#{Standard,AfterPrint} = Ideal#{Standard,AfterNoPrint} = (I) -> (
           << endl;                             -- double space
           << concatenate(interpreterDepth:"o") << lineNumber << " : Ideal of " << ring I << endl;
           )
```

**Comment by mahrud** [comment]
Unrelated, but not sure how to debug this:
```m2
i1 : class net id_(ZZ^0)

o1 = String

o1 : Type
```

**Comment by DanGrayson** [comment]
> Unrelated, but not sure how to debug this:
> 
> ```m2
> i1 : class net id_(ZZ^0)
> 
> o1 = String
> 
> o1 : Type
> ```

Not really a bug, since a string is a type of net.

**Comment by mahrud** [comment]
> Not really a bug, since a string is a type of net.

That makes sense, I suppose. I was initially startled by this:
```m2
i60 : class net id_(ZZ^0)

o60 = String

o60 : Type

i61 : class net id_(ZZ^1)

o61 = Net

o61 : Type
```
Both have height 1, so I was confused why the type was different.

**Comment by mahrud** [comment]
This will be fixed in the commits linked above, but two things that would be good to improve with `runLengthEncode`:
- Length two sequences don't need to be encoded:
```m2
i1 : QQ[x, y, a, b, X_1, X_2]

o1 = QQ[x..y, a..b, X ..X ]
                     1   2

o1 : PolynomialRing
```
- Also encode more complicated sequences with a common prefix:
```m2
i3 : QQ[x, y, z, Dx, Dy, Dz]

o3 = QQ[x..z, Dx, Dy, Dz]

o3 : PolynomialRing
```

**Comment by DanGrayson** [comment]
The second suggestion won't work:
```m2
i7 : Dx .. Dz
stdio:7:4:(3): error: 'Dx' is not one of the symbols known to 'vars'
stdio:7:1-7:3: here is the first use of 'Dx'
```

**Comment by mahrud** [comment]
That's exactly the point of my suggestion: to get it to work.

**Comment by DanGrayson** [comment]
It might be impossible to do in a way consistent with this behavior:

```m2

i10 : a .. x4

o10 = (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, X, Y, Z, x0, x1, x2, x3, x4)

o10 : Sequence
```

**Comment by mahrud** [comment]
I don't know how you did that:
```m2
i1 : a .. x4
stdio:1:3:(3): error: 'x4' is not one of the symbols known to 'vars'
stdio:1:6-1:8: here is the first use of 'x4'
```
but that would be good to add, for both `x<N>` and `D<N>` and perhaps others.

More generally, the way the indeterminates are handled currently is kind of buggy, mainly in that it is not really thread safe. Could probably use a reevaluation, along with thinking about changing the inheritance of symbols and symbol bodies.

**Comment by DanGrayson** [comment]
Oh, here's the way I did it:
```m2
+ M2-1.16 --no-readline -q --print-width 212
Macaulay2, version 1.16
with packages: ConwayPolynomials, Elimination, IntegralClosure, InverseSystems, LLLBases, MinimalPrimes, PrimaryDecomposition, ReesAlgebra, TangentCone, Truncations

i1 : vars (0 .. 100)

o1 = (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, X, Y, Z, x0, x1, x2, x3, x4, x5, x6, x7, x8, x9, x10, x11,
     ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
     x12, x13, x14, x15, x16, x17, x18, x19, x20, x21, x22, x23, x24, x25, x26, x27, x28, x29, x30, x31, x32, x33, x34, x35, x36, x37, x38, x39, x40, x41, x42, x43, x44, x45, x46, x47, x48)

o1 : Sequence

i2 : a .. x4

o2 = (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, X, Y, Z, x0, x1, x2, x3, x4)

o2 : Sequence
```


It's probably important to preserve the sequence up to `Z`, but after that, the choices of `x0`, etc., are arbitrary and could be something else.
