### ISSUE TITLE
Tag for 1.16.99?

### ISSUE THREAD

**Issue by d-torrance** [Macaulay2/M2#1691]
Will there be a git tag for the beta version?  Currently, this is what `git describe` gives us:

```
profzoom@peg-amy:~/src/macaulay2/M2$ git describe --tags origin/release-1.17
version-1.16.0.2-1111-gc9b654ac1
```

It would be nice if it was `version-1.16.99-(some small integer)-gc9b654ac1` instead.  (I'm thinking of uploading 1.16.99 to Debian [experimental](https://wiki.debian.org/DebianExperimental), and my tarball-generating script uses the most recent tag to generate the version number.)

**Comment by mahrud** [comment]
Not specifically related to the question asked, but for creating releases on github, it would be good to start putting the changelog on the [releases page](https://github.com/Macaulay2/M2/releases). We should do this for 1.17 (but not 1.16.99).

Here is how you can generate a markdown version of the changelog that looks pretty (even has a gold star picture)

```m2
restart
debug Core
markdown CODE := x -> concatenate("```", apply(x, markdown), "```")
markdown IMG := x -> (
    (o, cn) := override(IMG.Options, toSequence x);
    if o#"alt" === null then error ("IMG item is missing alt attribute");
    concatenate("![", format o#"alt", "](", toURL o#"src", ")"))
illinois = "https://faculty.math.illinois.edu/Macaulay2/doc/Macaulay2/share"
X = markdown help "changes, 1.17";
X = replace("^      ", "", X);
X = replace("/home/.*?/common/share", illinois, X);
X = replace("common/share", illinois, X);
<< X
```

I had to replace a couple of methods because I realized they don't work well on github, I'll make a PR to change one of them at least.

**Comment by d-torrance** [comment]
I'm fixing this for now on my end by just having the script make its own `version-1.16.99` tag in its local copy of the repository at 37da738.

**Comment by DanGrayson** [comment]
Done:

```
$ git describe --dirty --long --always --abbrev=40 --tags --match 'version-*'
version-1.16.99-46-g5020153f13a4f9a4ffbb889a39fc2cebd0481247
```

**Comment by DanGrayson** [comment]
I think no one uses the github releases page for M2.

**Comment by mahrud** [comment]
That's not true. Multiple system admins who have been asked to install M2 on their systems started by downloading the latest release tag and compiling from source. We know this because they made issues here when they ran into problems.

It's the first place people look for stable versions on GitHub. Why not start using it?

**Comment by DanGrayson** [comment]
Because none of the versions there are stable versions.

**Comment by mahrud** [comment]
They were at the time the tag was created. We can't get rid of the releases
page, so we shouldn't confuse users by leaving incorrect information there.
I'm just advocating for following standard best practices.

**Comment by d-torrance** [comment]
Seconding Mahrud's point -- it also makes it easier for downstream packaging if the tags point to the official, stable releases.

Right now for the Debian package, I have a [relatively convoluted Python script](https://salsa.debian.org/science-team/macaulay2/-/blob/watch/m2-get-orig-source.py) that checks for the largest version out of the various `release-X.Y` branches and builds a tarball from the current tip of that branch.  But since that branch might get new commits, it appends an ugly string to the version number to differentiate that version from any past or future ones.  For example, `1.16+git55.94c4b7d+ds-1` is the version currently in Debian unstable, and `1.16.99+git40.3a512e5+ds-1` is the version currently awaiting sponsorship for upload to Debian experimental.  (Fedora takes an easier route and just [hardcodes the commit hash in their build script](https://src.fedoraproject.org/rpms/Macaulay2/blob/master/f/Macaulay2.spec#_24).)

It would be a lot nicer if I could scrap my ugly Python script and just point the `debian/watch` file (which tells the `uscan` utility where to find tarballs for the latest release) to the Github releases page.  Plus we'd get nice, pretty version numbers in Debian like `1.17+ds-1` instead of all the `+git` stuff.  (The `+ds` is for "Debian source", since I repack the tarball without some fonts and Javascript libraries that already in Debian.)

**Comment by DanGrayson** [comment]
> They were at the time the tag was created. 

No, that's not true.  I just made those tags right after changing a version number.  The commits that should be regarded as stable releases are the tips of the branches whose names have the form "release-*".

**Comment by DanGrayson** [comment]
Doug, how is it helpful to point a script at the github releases page?  You still have to select one of the releases found there.

**Comment by DanGrayson** [comment]
Doug, what if we start having tags such as `stable-release-1.17`?

**Comment by d-torrance** [comment]
> Doug, how is it helpful to point a script at the github releases page? You still have to select one of the releases found there.

The [`uscan`](https://manpages.debian.org/unstable/devscripts/uscan.1.en.html) utility uses the information from the `debian/watch` file to parse the html for links to tarballs and determines which one of them contains the latest version.  There's really nothing special about a Github releases page -- anything with links to tarballs will do.  (For example, pre-Github, https://faculty.math.illinois.edu/Macaulay2/Downloads/SourceCode/ would have been great!)

My current script generates a webpage with a single link to the most recent tarball (https://science-team.pages.debian.net/macaulay2/) and `debian/watch` tells `uscan` to go there instead.

**Comment by d-torrance** [comment]
> Doug, what if we start having tags such as `stable-release-1.17`?

That would be great!  I could easily tell `uscan` just to look for the tags that begin with `stable-release-`.  Ideally, there would also be a companion tag in the M2-emacs repository.

Also, these stable tags could be potentially used to draft "releases" using Mahrud's code for Markdown-ified changelogs.

**Comment by mahrud** [comment]
> > They were at the time the tag was created. 
> 
> No, that's not true.  I just made those tags right after changing a version number.  The commits that should be regarded as stable releases are the tips of the branches whose names have the form "release-*".

Don't you think you're using the term "release" incorrectly here? When you tag a commit as a Macaulay2 release, it carries a meaning.

> Doug, what if we start having tags such as stable-release-1.17?

Why overcomplicate things by adding yet another prefix? That will even mess up the alphabetic ordering of tags.

Perhaps what you really want is something like this:
```
release-1.17-rc1
release-1.17-rc2
release-1.17
release-1.17.1
...
```

**Comment by DanGrayson** [comment]
> > > They were at the time the tag was created.
> > 
> > 
> > No, that's not true.  I just made those tags right after changing a version number.  The commits that should be regarded as stable releases are the tips of the branches whose names have the form "release-*".
> 
> This is nonstandard and has regularly confused users if you look through the issues.
> 
> Don't you think you're using the term "release" incorrectly here? When you tag a commit as a Macaulay2 release, it carries a meaning.

No, I think the meaning of "release-1.17" is that this is the code from which release 1.17 is built.

> 
> > Doug, what if we start having tags such as stable-release-1.17?
> 
> Why overcomplicate things by adding yet another prefix? That will even mess up the alphabetic ordering of tags.

Because Doug prefers tags to branches.

> 
> Perhaps what you really want is something like this:
> 
> ```
> release-1.17-rc1
> release-1.17-rc2
> release-1.17
> release-1.17.1
> ...
> ```

No, not really: we don't have release candidates, so names like  release-1.17-rc1  are not useful.

**Comment by DanGrayson** [comment]
> > Doug, what if we start having tags such as `stable-release-1.17`?
> 
> That would be great! I could easily tell `uscan` just to look for the tags that begin with `stable-release-`. Ideally, there would also be a companion tag in the M2-emacs repository.

Okay, I've created 5 of them.  What's the point of companion tags in M2-emacs?  Are you bundling it up separately?

**Comment by mahrud** [comment]
1.16.99 should have been a release candidate: if it didn't have any issues it would be the same as 1.17. Even after some fixes, it is far closer to 1.17 than 1.16. Also, where did all the middle versions go? Versions aren't supposed to jump.

Of course, you can come up with whatever convoluted conventions you want. I'm just telling you what's standard practice among the majority of open source projects. Following those helps beginners quickly orient themselves within the project. Not following those just makes the project unpleasantly quirky.

You can also pick your favorite open source project with a healthy developer community and follow their conventions.

**Comment by DanGrayson** [comment]
> 1.16.99 should have been a release candidate: if it didn't have any issues it would be the same as 1.17. Even after some fixes, it is far closer to 1.17 than 1.16. Also, where did all the middle versions go? Versions aren't supposed to jump.

No, for there is no principled way to automate the comparison of version numbers including suffixes such as "-rc1" to put them in the right sequence.  With 1.16.99 and 1.17, the standard way works.

**Comment by d-torrance** [comment]
> Okay, I've created 5 of them.

Thanks!

>  What's the point of companion tags in M2-emacs? Are you bundling it up separately?

No, I'm bundling them together.  But I need a tarball that either contains both of them (what my current Python script does), or two separate tarballs that `uscan` can grab.  I could just tell `uscan` to get the tip of `master`, but potentially that may have some breaking changes that were introduced while working on the next release.  So ideally, there should be a tag at the commit that we know works with each release. (I imagine this would be desirable for https://github.com/Macaulay2/M2-emacs/issues/4, too).

**Comment by DanGrayson** [comment]
The principled way would be to take advantage of M2-emacs being a submodule of M2, and just getting it that way, using git.

**Comment by d-torrance** [comment]
> The principled way would be to take advantage of M2-emacs being a submodule of M2, and just get it that way, using git.

I agree, but `uscan`'s git support is still pretty limited.  It's mostly still a relic of the pre-git "host your tarballs on your webpage" days.  It has some basic git functionality (e.g., for the memtailor/mathic/mathicgb Debian packages, it uses the date of the last commit as part of the version number), but nothing involving submodules yet.

**Comment by d-torrance** [comment]
Actually, the more I think about it, I think I'll probably be just fine without M2-emacs tags.  Most of the time, `uscan` only does the first part of its job -- detect new version numbers.  And the tags in the main M2 repository are sufficient for that.  I'll only need M2-emacs when it's time to create a release tarball, and I can just add a script in the source package that does that using the submodule info.

**Comment by DanGrayson** [comment]
> > > They were at the time the tag was created.
> > 
> > 
> > No, that's not true.  I just made those tags right after changing a version number.  The commits that should be regarded as stable releases are the tips of the branches whose names have the form "release-*".
> 
> This is nonstandard and has regularly confused users if you look through the issues.
> 
> Don't you think you're using the term "release" incorrectly here? When you tag a commit as a Macaulay2 release, it carries a meaning.
> 

No, I don't tag any commits as releases.  All the names of the form "release-x.y" are branches, not tags.

**Comment by d-torrance** [comment]
I've written a script that will locally generate a nice tarball with the contents of both the M2 and M2-emacs for the Debian package, after using `uscan` to determine the latest stable release:
https://salsa.debian.org/science-team/macaulay2/-/blob/debian/development/debian/scripts/m2-get-orig-source.sh

So I'm good on that end.  I withdraw my request for M2-emacs tags.  :)

I do agree with Mahrud somewhat on the overall use of tags.  On one hand, I do like the `stable-release-` prefix to disambiguate the stable release tags from the unstable ones.  In particular, I *don't* want `uscan` thinking that `version-1.17.0.1` is the latest and greatest version of Macaulay2 that should be packaged for Debian once that tag is created.

But on the other hand, I find it strange that both `stable-release-1.16` and `version-1.16` exist and point to different commits.  Perhaps `version-` tags shouldn't be created for numbers that will eventually get a `stable-release-` tag?  And stick to `version-` tags for developer-only releases like `1.X.0.1`, etc.?

**Comment by DanGrayson** [comment]
Here's the single useful thing about the version tags -- they give us a way to use "git describe" to get a description that includes the current version number:
```
$ git describe --dirty --long --always --abbrev=40 --tags --match 'version-*'
version-1.16.99-48-g63f0e55d763ef6829fbc5cb02ded188579c4b906
```
Without them, what would we do?

**Comment by d-torrance** [comment]
I like the `version-*` tags for the same reason.  My main concern is the doubling up of tags with the same number.  I don't think `stable-release-X.Y` and `version-X.Y` should point to different commits.

Perhaps one idea would be to continue to use the `1.(X - 1).99` convention up until the very last commit before release.  That commit could include the update of `M2/VERSION` and be tagged `stable-release-1.X`.  Or maybe even `stable-version-1.X`, so that globbing could be used to catch both cases with `git describe --match '*version-*'`.   Plus then if we run M2 built from one of the stable tags, we'd get something nice like:

```m2
Macaulay2, version 1.17
with packages: ConwayPolynomials, Elimination, IntegralClosure, InverseSystems,
               LLLBases, MinimalPrimes, PrimaryDecomposition, ReesAlgebra,
               Saturation, TangentCone

i1 : version#"git description"

o1 = stable-version-1.17
```

**Comment by DanGrayson** [comment]
The problem with that approach is that after tagging the release, I would then begin to prepare the distributions for the various OSes and architectures, and I might find something that needs fixing.  Such fixes need to be included as part of the "stable release".

**Comment by d-torrance** [comment]
Would it be significantly more effort to do test builds of the various distributions first to make sure everything works nicely, make fixes as necessary, and then tag the release?

**Comment by mahrud** [comment]
> No, I don't tag any commits as releases. All the names of the form "release-x.y" are branches, not tags.

Right, I meant `version-...` tags. I think it is bad that the `version-1.16` tag does NOT point to the commit that produced the 1.16 packages. I know you have the `release-1.16` branch for that, but it's better not to use branches for this purpose. Just keep working on the main branch, and once you're ready to make a distribution, tag that exact commit, possibly with the postfix `-rcN` if it is not quote final for whatever reason.

>  Perhaps version- tags shouldn't be created for numbers that will eventually get a stable-release- tag? And stick to version- tags for developer-only releases like 1.X.0.1, etc.?

This sounds reasonable, though I still find it uncomfortable that the tags aren't sorted correctly. For instance:
```
$ git tag -l --sort=-v:refname
version-1.16.99
version-1.16.0.2
version-1.16.0.1
version-1.16
version-1.15.1.0
...
version-0.9.9
upstream/1.14.0.1.786.g30c2485c7
stable-release-1.16
stable-release-1.15
...
```

> Here's the single useful thing about the version tags -- they give us a way to use "git describe" to get a description that includes the current version number:
> 
> ```
> $ git describe --dirty --long --always --abbrev=40 --tags --match 'version-*'
> version-1.16.99-48-g63f0e55d763ef6829fbc5cb02ded188579c4b906
> ```
> 
> Without them, what would we do?

Oh, I can help with this! Use the VERSION file!

```
[mahrud@noether M2]$ echo version-`cat VERSION`-`git rev-list $(git rev-list -1 HEAD VERSION)..HEAD --count`-g`git rev-parse HEAD`
version-1.16.99-42-g454194f38f3d0e33473e0256f3665f906b4c9179
```

> The problem with that approach is that after tagging the release, I would then begin to prepare the distributions for the various OSes and architectures, and I might find something that needs fixing. Such fixes need to be included as part of the "stable release".

I think using `release-1.17-rc1` ... for this purpose is perfect! If you get it correct right away, you can add a tag `release-1.17` on top of it, otherwise you can go until it's right, then tag `release-1.17`

**Comment by mahrud** [comment]
More default on the command above:

1. `git rev-list -1 HEAD VERSION` gives the last commit that changed the `VERSION` file
2. `git rev-list $(git rev-list -1 HEAD VERSION)..HEAD --count` gives the number of commits since then
3. `git rev-parse HEAD` gives the current commit hash

Personally though, I prefer something shorter like this:
```
[mahrud@noether M2]$ echo version-`cat VERSION`-`git rev-parse --short HEAD`
version-1.16.99-454194f38
```

**Comment by d-torrance** [comment]
> This sounds reasonable, though I still find it uncomfortable that the tags aren't sorted correctly. 

That's a fair point.  I suppose we already have the convention mentioned in `M2/VERSION-README` that only two- and three-part version numbers are intended for distribution.  So that should be sufficient for identifying which tags are stable without needing an additional prefix.  (On the Debian side, I could adjust the regex used in the `debian/watch` file to only look for those.)

**Comment by mahrud** [comment]
Here's a different way, if you want `-dirty` to show up if the state of the repository has changed:
```
[mahrud@noether M2]$ echo version-`cat VERSION`-`git rev-list $(git rev-list -1 HEAD VERSION)..HEAD --count`-g`git describe --dirty --always --match HEAD^1`
version-1.16.100-42-g454194f38-dirty
```

I put the `-g` there because for some reason your commands puts it there. But it's always confusing to me, as it's not a part of the commit, so I think we should remove it! It'll avoid confusing others who would look at `version#"git description"` and find that the hash looking part of the string is not actually a git commit!!

**Comment by DanGrayson** [comment]
> Would it be significantly more effort to do test builds of the various distributions first to make sure everything works nicely, make fixes as necessary, and then tag the release?

Yes, that doubles the number of builds I have to do: a complete set of test builds beforehand, and then all the builds after that.  And it doesn't take into account the cases where a user convinces me, later on, to do a build on yet another system, which might also require changes.

Although, we could consider doing it your way, but adding extra tags for the systems that need changing, such as "stable-release-1.17-ubuntu1604".  That might be better, anyway, because, for I know, adding a line that makes it build on the latest system I've tried might spoil for other ones.

**Comment by d-torrance** [comment]
> > Would it be significantly more effort to do test builds of the various distributions first to make sure everything works nicely, make fixes as necessary, and then tag the release?
> 
> Yes, that doubles the number of builds I have to do: a complete set of test builds beforehand, and then all the builds after that. And it doesn't take into account the cases where a user convinces me, later on, to do a build on yet another system, which might also require changes.

Ah, that makes sense.

> Although, we could consider doing it your way, but adding extra tags for the systems that need changing, such as "stable-release-1.17-ubuntu1604". That might be better, anyway, because, for I know, adding a line that makes it build on the latest system I've tried might spoil for other ones.

That works for me!  As long as there's a tag pointing to a stable release and I can filter out the others with a regex, then I'm happy.  :)

**Comment by DanGrayson** [comment]
Indeed, Mahrud, maybe we should use the VERSION file to construct the description.  And then we could just delete all the tags whose names are of the form "version-*".

We could dispense with "git describe" and do it this way:

```sh
$ echo version-`cat VERSION`-`git rev-parse HEAD``[ "$(git diff --stat)" = '' ] || echo -dirty`
version-1.16.99-cfeee01db983337e583596b2221ab7b9806d9a7a
```


Doug?

**Comment by mahrud** [comment]
@DanGrayson see #1704.

**Comment by d-torrance** [comment]
That sounds good to me!

**Comment by DanGrayson** [comment]
> > This sounds reasonable, though I still find it uncomfortable that the tags aren't sorted correctly.
> 
> That's a fair point. 

What's incorrect about the sort order?

**Comment by DanGrayson** [comment]
Are you both okay with removing all the tags of the form "version-*"?  I could do that right away.

**Comment by d-torrance** [comment]
> Are you both okay with removing all the tags of the form "version-*"? I could do that right away.

Yes

**Comment by mahrud** [comment]
> What's incorrect about the sort order?

I gave an example:
```
$ git tag -l --sort=-version:refname
version-1.16.99
version-1.16.0.2
version-1.16.0.1
version-1.16
version-1.15.1.0
...
version-0.9.9
upstream/1.14.0.1.786.g30c2485c7
stable-release-1.16
stable-release-1.15
...
```
Here:
- `--sort:refname` would sort by tag name
- `--sort:-refname` reverses the list
- `--sort:-version:refname` treats tag names as version strings, so `1.9` < `1.16`

However, even with `version:` prefix, `stable-release-1.16` < `version-0.9.9`, so all the `version-*` tags come first, then `stable-release-*`, then `release-*-stable-*` (did you know you had those too?), then `Macaulay2-*`. There are also a bunch of random tags left around.

> Are you both okay with removing all the tags of the form "version-*"? I could do that right away.

Sure, though the code in master and development wouldn't work until my PR is merged.

**Comment by mahrud** [comment]
> Are you both okay with removing all the tags of the form "version-*"? I could do that right away.

I think both you and @mikestillman should delete the tags locally as well, otherwise they'll come back the first time you push directly to development or master.

**Comment by DanGrayson** [comment]
> > Are you both okay with removing all the tags of the form "version-*"? I could do that right away.
> 
> I think both you and @mikestillman should delete the tags locally as well, otherwise they'll come back the first time you push directly to development or master.

Good idea.  But the tags get pushed only with the `--tags` option.

**Comment by DanGrayson** [comment]
> > What's incorrect about the sort order?
> 
> I gave an example:
> 


If you want them in chronological order, you can do `git tag --sort=-committerdate`.

**Comment by DanGrayson** [comment]
> > Are you both okay with removing all the tags of the form "version-*"? I could do that right away.
> 
> Sure, though the code in master and development wouldn't work until my PR is merged.

I'll wait for that.

**Comment by DanGrayson** [comment]
What's the difference between https://github.com/Macaulay2/M2/releases and https://github.com/Macaulay2/M2/tags ?

**Comment by d-torrance** [comment]
> What's the difference between https://github.com/Macaulay2/M2/releases and https://github.com/Macaulay2/M2/tags ?

You can add a nice Markdown-ified changelog and add additional files to the "releases" page (using the "Draft a new release" button), but "tags" is just a list of tags.

**Comment by mahrud** [comment]
You can also upload the distribution files there. Combined with github actions, you can also have the actions automatically generate the packages and create a new release with the packages whenever a new "release-*" tag is pushed, so people can download the latest binary as soon as possible.

**Comment by DanGrayson** [comment]
Downloading binaries from github is not very useful for systems where Macaulay2 depends on other packages getting installed, too.  That's all the linux systems.

**Comment by DanGrayson** [comment]
Is there a way to restrict the list at https://github.com/Macaulay2/M2/releases to a subset of the tags?

**Comment by mahrud** [comment]
> Downloading binaries from github is not very useful for systems where Macaulay2 depends on other packages getting installed, too. That's all the linux systems.

By binaries I meant binary distributions, e.g. a .deb or .rpm package, with prescribed dependencies. CMake can do this with `cpack -G DEB`, for instance.

**Comment by mahrud** [comment]
> Is there a way to restrict the list at https://github.com/Macaulay2/M2/releases to a subset of the tags?

This has been a request for a few years now: https://github.community/t/tag-without-release/857

The main solution seems to be to actually create releases (with title, markdown changelog, etc.) so users can tell the difference between actual releases. See for instance:
![image](https://user-images.githubusercontent.com/3147718/102414474-3de8ca80-3fbc-11eb-961f-edd392d2a8b4.png)

From here: https://github.com/jupyter/notebook/releases

This is why I keep offering to populate the release page with the changelog or other useful content.

**Comment by DanGrayson** [comment]
> > Downloading binaries from github is not very useful for systems where Macaulay2 depends on other packages getting installed, too. That's all the linux systems.
> 
> By binaries I meant binary distributions, e.g. a .deb or .rpm package, with prescribed dependencies. CMake can do this with `cpack -G DEB`, for instance.

Is `apt --fix-broken install ./macaulay2_1.16.99_amd64.deb ` the preferred way to install a package and its dependencies?

(I don't like the use of the word "broken" here.)

Doug?

**Comment by DanGrayson** [comment]
> This is why I keep offering to populate the release page with the changelog or other useful content.

Well, let's try it and see how it looks.  Can you do it for some past releases, as an experiment?

**Comment by d-torrance** [comment]
> Is `apt --fix-broken install ./macaulay2_1.16.99_amd64.deb ` the preferred way to install a package and its dependencies?
> 
> (I don't like the use of the word "broken" here.)
> 
> Doug?

Until you asked and I did some googling, I honestly didn't know that you could use `apt` to install a local `.deb` file!  It's a "new" feature in that it was introduced in 2015 (https://mvogt.wordpress.com/2015/11/30/apt-1-1-released/).  But I've been using Debian-based distros much longer than that and have always used `dpkg -i` to install local `.deb` files.  I generally try to avoid this and prefer to install packages that I can get from a repository in my `/etc/apt/sources.list`.  I'd say that's probably still the preferred way.

**Comment by DanGrayson** [comment]
But `dpkg -i` doesn't install the dependencies:
```
# dpkg -i macaulay2_1.16.99_amd64.deb 
Selecting previously unselected package macaulay2.
(Reading database ... 
(Reading database ... 5%
(Reading database ... 10%
(Reading database ... 15%
(Reading database ... 20%
(Reading database ... 25%
(Reading database ... 30%
(Reading database ... 35%
(Reading database ... 40%
(Reading database ... 45%
(Reading database ... 50%
(Reading database ... 55%
(Reading database ... 60%
(Reading database ... 65%
(Reading database ... 70%
(Reading database ... 75%
(Reading database ... 80%
(Reading database ... 85%
(Reading database ... 90%
(Reading database ... 95%
(Reading database ... 100%
(Reading database ... 223129 files and directories currently installed.)
Preparing to unpack macaulay2_1.16.99_amd64.deb ...
Unpacking macaulay2 (1.16.99) ...
dpkg: dependency problems prevent configuration of macaulay2:
 macaulay2 depends on 4ti2; however:
  Package 4ti2 is not installed.

dpkg: error processing package macaulay2 (--install):
 dependency problems - leaving unconfigured
Processing triggers for man-db (2.9.3-2) ...
Errors were encountered while processing:
 macaulay2
```

**Comment by d-torrance** [comment]
> But `dpkg -i` doesn't install the dependencies:

Exactly!  That's why I try to avoid it.  :)  Even now that apparently `apt` does install the dependencies for a local `.deb` file, who knows if you can even satisfy those dependencies using the repositories your system knows about.  That's why I like to stick to installing from a repository -- chances are good that all of the dependencies will also be available on that repository.

**Comment by mahrud** [comment]
@DanGrayson here's how a 1.16 release looks like: https://github.com/Macaulay2/M2/releases

**Comment by DanGrayson** [comment]
So we shouldn't put *.deb files on the github releases page, I guess.

**Comment by mahrud** [comment]
> So we shouldn't put *.deb files on the github releases page, I guess.

Since Doug is maintaining the debian repository, I see no reason to do that. But for distributions that are harder to keep up to date, or perhaps for .dmg packages, we should probably do that.

**Comment by DanGrayson** [comment]
> @DanGrayson here's how a 1.16 release looks like: https://github.com/Macaulay2/M2/releases

That looks great, especially the change log, but trying to build from the tar file provided won't work, as the submodule files are not present.

**Comment by mahrud** [comment]
> That looks great, especially the change log, but trying to build from the tar file provided won't work, as the submodule files are not present.

That's less than ideal, but it's not so important. It's just the source code at that point in time, and I think both autotools and cmake warn that since a git repository isn't found the user needs to extract archives of the submodules separately. We can add artifacts to releases, but can't remove the two source archives.

By the way, this is github's suggestion on tagging:
![image](https://user-images.githubusercontent.com/3147718/102429505-30413e00-3fd8-11eb-9b01-039bf3d03b98.png)

I think it would be great if we could tag the appropriate commit for each stable release as `release-X.YY` and get rid of all other version/release/release-stable/Macaulay2/etc. tags (We can keep other development tags though) and use `release-X.YY-rcN` for release candidates moving forward. I created a "pre-release" to see how it looks: https://github.com/Macaulay2/M2/releases.

**Comment by d-torrance** [comment]
> I think it would be great if we could tag the appropriate commit for each stable release as `release-X.YY` and get rid of all other version/release/release-stable/Macaulay2/etc. tags (We can keep other development tags though) and use `release-X.YY-rcN` for release candidates moving forward. I created a "pre-release" to see how it looks: https://github.com/Macaulay2/M2/releases.

If we still have `release-X.YY` branches (and we already do for 1.17), then we'll get `warning: refname 'release-X.YY' is ambiguous` when we try to `git checkout release-X.YY`.  So I'm not sure if that's ideal.  What about `vX.YY` for the tags as suggested by GitHub?

**Comment by mahrud** [comment]
If we use tags instead of branches for each release, including release
candidates, then I don't see a reason to keep the `release-*` branches:
whenever you have a commit that's reasonably ready, tag it
`release-1.17-rc1`, when new issues are found and fixed, tag
`release-1.17-rc2`, until it's ready to be tagged `release-1.17`.

Here's another reason: having fewer branches is good, because it reduces
merge commits and keeps the commit history linear. Already there are 6 or 7
merge commits between release-1.17 and development or master or pre-master.
Here are the last two commits on development:

commit cfeee01db983337e583596b2221ab7b9806d9a7a (upstream/pre-master,
upstream/development, development)
Merge: 4c6ac5e8b 5020153f1
Author: Daniel R. Grayson <dan@math.uiuc.edu>
Date:   Tue Dec 15 10:51:57 2020 -0600

    Merge branch 'release-1.17' into development

commit 5020153f13a4f9a4ffbb889a39fc2cebd0481247
Merge: 8424ff60a 92e576633
Author: Daniel R. Grayson <dan@math.uiuc.edu>
Date:   Tue Dec 15 08:48:27 2020 -0600

    Merge branch 'release-1.17' of github.com:Macaulay2/M2 into release-1.17

That said, I'm okay with using `version-X.YY` or `vX.YY` for tags if Dan
prefers to keep the release branches.
