### ISSUE TITLE
check_2 "LLLBases" killed on s390x

### ISSUE THREAD

**Issue by d-torrance** [Macaulay2/M2#1697]
From a build of the `release-1.17` branch in an s390x Debian unstable chroot using qemu:

```m2
i3 : check(2, "LLLBases", Verbose => true)
-* running test 2 of package LLLBases in file:
   M2/Macaulay2/packages/LLLBases.m2:1385:1:
   rerun with: check_2 "LLLBases" *-

 ulimit -c unlimited; ulimit -t 700; ulimit -m 850000; ulimit -s 8192; ulimit -n 512;  cd /tmp/M2-2956034-0/5-rundir/; GC_MAXIMUM_HEAP_SIZE=400M "/build/macaulay2-1.16.0.2+git1111.c9b654a+ds/M2/usr-dist/s390x-Linux-Debian-unstable/bin/M2-binary" --int --no-randomize --no-readline --silent --stop --print-width 129 -e 'needsPackage("LLLBases", Reload => true, FileName => "/build/macaulay2-1.16.0.2+git1111.c9b654a+ds/M2/Macaulay2/packages/LLLBases.m2")' <"/tmp/M2-2956034-0/4.m2" >>"/tmp/M2-2956034-0/4.tmp" 2>&1
/tmp/M2-2956034-0/4.tmp:0:1: (output file) error: Macaulay2 killed by signal 9
/tmp/M2-2956034-0/4.m2:0:1: (input file)
M2: *** Error 9
stdio:3:13:(3): error: test #2 of package LLLBases failed:

     -- used 5.75332 seconds

i43 :     assert isLLL (a = time LLL(m, Strategy=>{BKZ,Givens,RealQP}))
     -- used 147.152 seconds

i44 :     assert isLLL (a = time LLL(m, Strategy=>{BKZ,Givens,RealQP1}))    
     -- used 149.413 seconds

i45 :     assert isLLL (a = time LLL(m, Strategy=>{BKZ,Givens,RealXD}))
Killed
```

This is a pretty big test -- even on my relatively decent amd64 machine not trying to emulate another architecture, it takes a while:

```m2
i5 : elapsedTime check_2 "LLLBases"
-* running test 2 of package LLLBases in file:
   LLLBases.m2:1385:1:
   rerun with: check_2 "LLLBases" *-
 -- 34.7873 seconds elapsed
```

**Comment by DanGrayson** [comment]
Did it run out of time?

**Comment by d-torrance** [comment]
> Did it run out of time?

Yeah, I believe so.  Based on the output above, we were already over 300 seconds before the last `assert` that was killed, so I wouldn't be surprised if we hit the 700 imposed by `ulimit`.

**Comment by DanGrayson** [comment]
I wonder why we got no message about the exceeded limit.

It probably makes sense to have slower time limits on slower machines.  It would also make sense to have slower time limits for downstream distribution testing (which can be achieved by downstream patching) than for upstream pull request testing and for user testing.

Currently, the time limit is hard coded in the file run.m2.  There are also various time limits in the makefiles in the test directory.  Maybe they should all be handled by the configure script.

**Comment by d-torrance** [comment]
Closing - see https://github.com/Macaulay2/M2/issues/1747#issuecomment-1128032661.
