### ISSUE TITLE
--enable-dmg does not work when building with Apple Clang

### ISSUE THREAD

**Issue by tom111** [Macaulay2/M2#1698]
I'm configuring like this:

`../../configure --enable-download --enable-dmg`

Then I build switch to `distributions/dmg` and `make` and then this:

```
( set -e;											\
  for i in files/Macaulay2-1.17.0.1/bin/* files/Macaulay2-1.17.0.1/libexec/Macaulay2/bin/* ;		\
  do if [ -f $i -a -x $i -a ! -h $i ] ;							\
     then otool -L $i | grep '^\t' | grep -v '^[[:space:]]*\(/usr/lib/\|/System/Library/\)'	\
	  | sed 's/^[[:space:]]*\(.*\) (compatibility version .*/\1/'				\
	  | while read f;									\
	    do echo "library preparation: error *** : file $i uses dynamic library $f" >&2;	\
	       exit 1;										\
	       done ;										\
     fi ;											\
  done												\
) >libraries.tmp ;
library preparation: error *** : file files/Macaulay2-1.17.0.1/bin/M2-binary uses dynamic library /usr/local/opt/gcc/lib/gcc/10/libgfortran.5.dylib
gmake: *** [Makefile:69: library_preparation] Error 1
gmake: Leaving directory '/Users/tom/temp/M2/M2/BUILD/tom/distributions/dmg'
```

I wonder why it is linking against homebrew fortran libraries, probably configure found those and dynamically linked them despite --enable-dmg.

**Comment by DanGrayson** [comment]
I'm not sure why it links against that fortran library -- we'll have to track that down eventually, since, presumably, you're not using a compiler provided by homebrew.  I had the same thing happen.

Meanwhile, there are various work-arounds.

- You could run "make" in the dmg directory this way: "make -o library_preparation".

- Move that library, and all the other dynamic libraries (files with names of the form *.dylib) out of the way, and relink.  That's what I do, for I don't expect other users to have installed brew.  That's a little aggressive, though.

- Don't make a dmg file.  Instead run Macaulay2 in place.  This is the preferred choice for developers, as then the *.m2 files referred to are the ones in the source tree, and it's easy to make changes and to submit pull requests.  Run the command M2 in the top level of the build tree, and in Macaulay2, run "setup()", so later, it knows to run that one.

**Comment by DanGrayson** [comment]
We'll leave this open until we figure out why it links against that fortran library, even though it didn't compile lapack itself.

**Comment by tom111** [comment]
Thanks for the overview of work-arounds.  Here is the linking situation after exactly that compilation mention above:

```
otool -L files/Macaulay2-1.17.0.1/bin/M2-binary
files/Macaulay2-1.17.0.1/bin/M2-binary:
	/System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libLAPACK.dylib (compatibility version 1.0.0, current version 1.0.0)
	/System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/lib/libxml2.2.dylib (compatibility version 10.0.0, current version 10.9.0)
	/usr/lib/liblzma.5.dylib (compatibility version 6.0.0, current version 6.3.0)
	/usr/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.11)
	/usr/local/opt/gcc/lib/gcc/10/libgfortran.5.dylib (compatibility version 6.0.0, current version 6.0.0)
	/usr/local/opt/gcc/lib/gcc/10/libquadmath.0.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1292.0.0)
	/usr/local/opt/singular/lib/libfactory-4.1.3.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/local/opt/ntl/lib/libntl.43.dylib (compatibility version 44.0.0, current version 44.1.0)
	/usr/local/opt/singular/lib/libomalloc-0.9.6.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/local/opt/singular/lib/libsingular_resources-4.1.3.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/lib/libncurses.5.4.dylib (compatibility version 5.4.0, current version 5.4.0)
	/usr/local/opt/flint/lib/libflint-14.dylib (compatibility version 14.0.0, current version 14.0.3)
	/usr/local/opt/glpk/lib/libglpk.40.dylib (compatibility version 44.0.0, current version 44.0.0)
	/usr/local/opt/mpfr/lib/libmpfr.6.dylib (compatibility version 8.0.0, current version 8.0.0)
	/usr/local/opt/gmp/lib/libgmpxx.4.dylib (compatibility version 11.0.0, current version 11.1.0)
	/usr/local/opt/gmp/lib/libgmp.10.dylib (compatibility version 15.0.0, current version 15.1.0)
	/usr/local/opt/bdw-gc/lib/libgc.1.dylib (compatibility version 6.0.0, current version 6.3.0)
	/usr/local/opt/gdbm/lib/libgdbm.6.dylib (compatibility version 7.0.0, current version 7.0.0)
	/usr/local/opt/boost/lib/libboost_stacktrace_addr2line.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/local/opt/boost/lib/libboost_regex-mt.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 904.4.0)
```

**Comment by tom111** [comment]
In `configure.ac` there is some logic that checks for a fortran compiler and then figures out to use `-lgfortran -lquadmath -lm`.

I have
```
LIBS               = -lxml2 -llzma -lz -llapack -lblas  -L/usr/lib -L/usr/local/lib -L/usr/local/Cellar/gc\
c/10.2.0/lib/gcc/10/gcc/x86_64-apple-darwin19/10.2.0 -L/usr/local/Cellar/gcc/10.2.0/lib/gcc/10/gcc/x86_64-apple-darwin19/10.2.0/\
../../.. -lgfortran -lquadmath -lm -lreadline -lcurses -lntl -lglpk -lmpfr -lgmpxx -lgmp -lgc -lgdbm  -lboost_stacktrace_addr2li\
ne -lboost_regex-mt
```
and
```
ac_cv_fc_libs=' -L/usr/lib -L/usr/local/lib -L/usr/local/Cellar/gcc/10.2.0/lib/gcc/10/gcc/x86_64-apple-darwin19/10.2.0 -L/usr/lo\
cal/Cellar/gcc/10.2.0/lib/gcc/10/gcc/x86_64-apple-darwin19/10.2.0/../../.. -lgfortran -lquadmath -lm'
```
as the result of running configure.

**Comment by DanGrayson** [comment]
An experiment under Mac OS X shows that linking with a dynamic library results in an executable that needs it, even if no symbols in the library are needed.

My configure script accepts the command line option `--disable-fc-lib-ldflags`, and then it doesn't link with the fortran libraries.   I suppose that using it might cause a problem if lapack is built.

Somehow the configure scripts incorporates the fortran libraries into the value of LIBS even if lapack is not built.

**Comment by mahrud** [comment]
We never compile lapack, why even bother checking for Fortran?

**Comment by DanGrayson** [comment]
Are we sure there's no longer a system where we need to build it?  There are a lot of systems out there...

**Comment by mahrud** [comment]
Systems that have all of our other requirements, just not lapack? They would have bigger issues I would think. Have you tried building lapack with your makefile recently? It didn't work on my machine several months ago.

**Comment by DanGrayson** [comment]
Okay, I just tried it under Ubuntu 20.10 and got an annoying (new) error:
```
gfortran -O2 -g -c sorcsd2by1.f -o sorcsd2by1.o
sorcsd2by1.f:388:40:

  365 |      $                   0, U1, LDU1, U2, LDU2, V1T, LDV1T, 0, 1, 0, 0,
      |                                      2  
......
  388 |      $                   0, V1T, LDV1T, 0, 1, U1, LDU1, U2, LDU2, 0, 0,
      |                                        1
Error: Type mismatch between actual argument at (1) and actual argument at (2) (INTEGER(4)/REAL(4)).
```

**Comment by DanGrayson** [comment]
But I've just fixed that by upgrading lapack in commit 1dc1bc7eda3bbf9907719734ccca722dc56779ad

**Comment by mahrud** [comment]
> But I've just fixed that by upgrading lapack in commit [1dc1bc7](https://github.com/Macaulay2/M2/commit/1dc1bc7eda3bbf9907719734ccca722dc56779ad)

Does it now work on those old machines you are worried about? There are a lot of systems out there that may not work with lapack 3.9.0!

**Comment by DanGrayson** [comment]
It's bound to work.  If not, we'll fix it when the time comes.  Maybe we'll end up never needing to build lapack again.

**Comment by mahrud** [comment]
I guess my point is that the existence of those checks for fortran are causing issues _right now_, so it doesn't make sense to me to keep those just in case someone needs lapack in the future. Maybe we can remove them and add them again it comes up, or maybe do the fortran checks in the lapack makefile rather than configure.

**Comment by DanGrayson** [comment]
Yes, it's an issue right now, but the work-arounds are easy.

**Comment by mahrud** [comment]
Given that the brew build seems to be working fine, is there any reason to maintain the dmg build?

**Comment by DanGrayson** [comment]
I hope not, but yes, there are two:

We've had one user say he doesn't like installing package managers such as brew, because they offer little benefit.

As I said in the announcement ,"I'm hoping users find the installation approach via brew convenient, so we can
stop making downloadable disk images and posting them on our web site."  So we are obligated to ask them about it.

**Comment by tom111** [comment]
Just a note: In the future it might be expected that a .dmg contains a universal binary that works natively on Apple Silicon and Intel.

**Comment by mahrud** [comment]
For those users who don't like package managers, they can always build M2 from source, right?
It's also possible to simplify the dmg build with [create-dmg](https://github.com/create-dmg/create-dmg).

**Comment by DanGrayson** [comment]
Building from source is too painful, no.

**Comment by mahrud** [comment]
> Building from source is too painful, no.

Maybe with autotools, but cmake is pretty efficient.

**Comment by DanGrayson** [comment]
In a few weeks I'll ask them.

**Comment by mahrud** [comment]
Who is this user?

**Comment by DanGrayson** [comment]
I forget.
