### ISSUE TITLE
Bug in abstractSheaf(..., ChernClass=>..., ...) of Schubert2

### ISSUE THREAD

**Issue by pi-mrlc** [Macaulay2/M2#1702]
Hello, 

While using Schubert2, I realise that the command 'abstractSheaf(..., ChernClass=>..., ...)' seems not working; in the sense that it creates an abstract sheaf of the right rank but with trivial (i.e. 1) Chern classes. 
((But the command 'abstractSheaf(..., ChernCharacter=>..., ...) seems fine))

i2 : X=abstractVariety(3, QQ[c])

o2 = X

o2 : an abstract variety of dimension 3

i3 : F=abstractSheaf(X, ChernClass=> 1+ c,3)

o3 = F

o3 : an abstract sheaf of rank 3 on X

i4 : chern F

o4 = 1

o4 : QQ[c]

**Comment by DanGrayson** [comment]
The documentation is unclear on this point, but what I think is happening is that the `3` is taken as the Chern character of F and your ChernClass option is ignored.  You can do it this way instead: `F=abstractSheaf(X, ChernClass => 1+c,Rank => 3)`.

**Comment by pi-mrlc** [comment]
Thank you very much for your swift reply.
It is my fault then.
Sorry.

**Comment by DanGrayson** [comment]
I'll improve it by providing a suitable error message:
```m2
Macaulay2, version 1.16.99
with packages: ConwayPolynomials, Elimination, IntegralClosure, InverseSystems, LLLBases, MinimalPrimes, PrimaryDecomposition, ReesAlgebra, Saturation, TangentCone

i1 : loadPackage ("Schubert2", DebuggingMode => true)

o1 = Schubert2

o1 : Package

i2 : X=abstractVariety(3, QQ[c])

o2 = X

o2 : an abstract variety of dimension 3

i3 : F=abstractSheaf(X, ChernClass=> 1+ c,3)
../src/M2/M2.git/M2/Macaulay2/packages/Schubert2.m2:240:44:(3):[6]: error: abstractSheaf: Chern class and Chern character options both specified
../src/M2/M2.git/M2/Macaulay2/packages/Schubert2.m2:240:44:(3):[6]: --entering debugger (type help to see debugger commands)
../src/M2/M2.git/M2/Macaulay2/packages/Schubert2.m2:240:44-240:44: --source code:
          if opts.ChernClass =!= null then error "abstractSheaf: Chern class and Chern character options both specified";

ii4 : break

i5 : F=abstractSheaf(X, ChernClass=> 1+ c,Rank => 3)

o5 = F

o5 : an abstract sheaf of rank 3 on X

i6 : chern F

o6 = 1 + c

o6 : QQ[c]
```

**Comment by DanGrayson** [comment]
On second thought, it may not be a good idea, since it can save time if the user can specify both the Chern character and the Chern class.
