### ISSUE TITLE
disallow the use of TEST in Macaulay2Doc

### ISSUE THREAD

**Issue by DanGrayson** [Macaulay2/M2#1712]
> > Is the use of TEST in Macaulay2Doc detected and an error message issued?
> 
> No. I don't think an error is worth it though.

I think it is, since if someone puts a test in and it doesn't get run, that's a bug.  I'll make a new issue.

_Originally posted by @DanGrayson in https://github.com/Macaulay2/M2/issues/1709#issuecomment-748206563_

**Comment by mahrud** [comment]
Why wouldn't it get run?
I think there could be tests specifically for the documentation; e.g. checking that there are no missing links, or things of that sort. That is, not Core tests, but actually Macaulay2Doc tests.

**Comment by DanGrayson** [comment]
> Why wouldn't it get run?

Ah, I just assumed we stop checking Macaulay2Doc, once it had no tests.  I guess not!

> I think there could be tests specifically for the documentation; e.g. checking that there are no missing links, or things of that sort. That is, not Core tests, but actually Macaulay2Doc tests.

Okay, I'll close that issue.
