### ISSUE TITLE
issue with findProgram on Github actions

### ISSUE THREAD

**Issue by mahrud** [Macaulay2/M2#1740]
In the autotools-macos-latest-default job of [this build](https://github.com/Macaulay2/M2/runs/1608316725) (and #1739 in general) the configure script is able to find gfan on the path, hence doesn't build it, but then when installing Macaulay2Doc, the findProgram and runProgram examples fail to find gfan. The executables seem to be on the path, and the lib directory should be set by the `M2` wrapper. Why is it not being found?

cc: @d-torrance no rush, but if you get a chance, let me know if you have any ideas.

**Comment by mahrud** [comment]
Specifically, the error message claims:
```m2
i2 : gfan = findProgram("gfan", "gfan --help", Verbose => true)
checking for gfan in /path/to/gfan/...
    not found
checking for gfan in /Users/runner/work/M2/M2/M2/BUILD/build/usr-dist/x86_64-Darwin-MacOS-10.15.7/libexec/Macaulay2/bin/...
    not found
```
But from earlier in the build:
```
2020-12-25T11:23:09.9367700Z [53/57] Performing install step for 'build-gfan'
2020-12-25T11:23:09.9471730Z cp gfan /Users/runner/work/M2/M2/M2/BUILD/build/usr-dist/x86_64-Darwin-MacOS-10.15.7/libexec/Macaulay2/bin/../bin
2020-12-25T11:23:09.9575170Z cd /Users/runner/work/M2/M2/M2/BUILD/build/usr-dist/x86_64-Darwin-MacOS-10.15.7/libexec/Macaulay2/bin/../bin && ./gfan installlinks
2020-12-25T11:23:09.9670240Z ln -sf gfan gfan_tropicalcurve
...
```

**Comment by d-torrance** [comment]
Very strange!  One possibility is that `gfan --help` isn't returning 0.  Is there a way to check that?

**Comment by mahrud** [comment]
It seems to: [link](https://github.com/mahrud/M2/runs/1610449866?check_suite_focus=true#step:10:23)

**Comment by d-torrance** [comment]
Perhaps the patch below will shed some light on what's going on?


```diff
diff --git a/M2/Macaulay2/m2/programs.m2 b/M2/Macaulay2/m2/programs.m2
index cbef6e20c..ae2b5fa43 100644
--- a/M2/Macaulay2/m2/programs.m2
+++ b/M2/Macaulay2/m2/programs.m2
@@ -20,8 +20,12 @@ addSlash = programPath -> (
 --   if MinimumVersion option is not given or the version number can't be
 --   be determined.
 checkProgramPath = (name, cmds, pathToTry, prefix, opts) -> (
-    found := if all(cmds, cmd -> run(pathToTry | addPrefix(cmd, prefix) |
-       " >/dev/null 2>&1") == 0) then 0 else 1;
+    found := if all(cmds, cmd -> (
+           cmdToRun := pathToTry | addPrefix(cmd, prefix);
+           print("running \"" | cmdToRun | "\" ... ");
+           ret := run(pathToTry | addPrefix(cmd, prefix));
+           print("return value: " | ret | newline);
+           ret == 0)) then 0 else 1;
     msg := "";
     thisVersion := null;
     if found == 0 then (
```

**Comment by mahrud** [comment]
I tried that, see [here](https://github.com/mahrud/M2/runs/1624365053?check_suite_focus=true#step:11:4685). Note:
```m2
2020-12-30T02:49:44.6714280Z cp gfan /Users/runner/work/M2/M2/M2/BUILD/build/usr-dist/x86_64-Darwin-MacOS-10.15.7/libexec/Macaulay2/bin/../bin
```
and:
```m2
2020-12-30T02:51:26.8285340Z configure: using FILE_PREREQS  =  ... /Users/runner/work/M2/M2/M2/BUILD/build/usr-dist/x86_64-Darwin-MacOS-10.15.7/libexec/Macaulay2/bin/gfan ...
```
But:
```m2
i1 : gfan = findProgram("gfan", "gfan --help")
sh: /Users/runner/work/M2/M2/M2/BUILD/build/usr-dist/x86_64-Darwin-MacOS-10.15.7/libexec/Macaulay2/bin/gfan: No such file or directory
...
running "/Users/runner/work/M2/M2/M2/BUILD/build/usr-dist/x86_64-Darwin-MacOS-10.15.7/libexec/Macaulay2/bin/gfan --help" ... 
return value: 32512
```

**Comment by mahrud** [comment]
Oh, autotools deletes and recreates the `usr-dist/x86_64-Linux-Fedora-32/libexec/Macaulay2` directory for some reason! Bizarre ... @DanGrayson any idea where this is happening?

**Comment by mahrud** [comment]
Ah, what's this doing here?!
https://github.com/Macaulay2/M2/blob/67e9aae6beee30c90001d5cb2b452b43f7205346/M2/libraries/Makefile.in#L26-L29

**Comment by mahrud** [comment]
On that note, what's the point of this tar-pipe-untar situation here?
https://github.com/Macaulay2/M2/blob/67e9aae6beee30c90001d5cb2b452b43f7205346/M2/libraries/Makefile.in#L31
The same thing is repeated in multiple places and looks intentionally twisted to make the makefiles unreadable.

**Comment by mahrud** [comment]
Anyway, this wasn't findProgram's fault, and should be fixed in f230bb8, so I'll close it. Thank Doug!

**Comment by DanGrayson** [comment]
> Oh, autotools deletes and recreates the `usr-dist/x86_64-Linux-Fedora-32/libexec/Macaulay2` directory for some reason! Bizarre ... @DanGrayson any idea where this is happening?

Yes, the libraries and programs are built under `usr-host` (where they are used for building) and then they are copied (destructively) to `usr-dist` (where they will be part of the distribution).

**Comment by DanGrayson** [comment]
> On that note, what's the point of this tar-pipe-untar situation here?
> https://github.com/Macaulay2/M2/blob/67e9aae6beee30c90001d5cb2b452b43f7205346/M2/libraries/Makefile.in#L31
> 
> 

It's a way to copy files.

**Comment by mahrud** [comment]
> It's a way to copy files.

What's wrong with `cp`?

**Comment by DanGrayson** [comment]
> > It's a way to copy files.
> 
> What's wrong with `cp`?

That would probably work, too.  What's wrong with `tar`?

**Comment by mahrud** [comment]
Nothing, as long as your intention is making the Makefiles extra unreadable, but that's up to you. I prefer CMakeLists to be readable.
