### ISSUE TITLE
Build fails with ICU 68

### ISSUE THREAD

**Issue by haerski** [Macaulay2/M2#1744]
Recently the Arch Linux repositories upgraded the ICU package (International Components for Unicode) to version 68. This version introduces breaking changes (see [Migration issues](http://site.icu-project.org/download/68)), and since it is a dependency of `libxml2` and `boost-regex`, it also affects building of Macaulay2. I get the following error

```Shell
In file included from /usr/include/unicode/umachine.h:52,
                 from /usr/include/unicode/utypes.h:38,
                 from /usr/include/unicode/ucnv_err.h:88,
                 from /usr/include/unicode/ucnv.h:52,
                 from /usr/include/libxml2/libxml/encoding.h:31,
                 from /usr/include/libxml2/libxml/parser.h:810,
                 from Macaulay2/d/expr-exports.h:27,
                 from /home/haerski/work/M2/M2/Macaulay2/d/scclib.c:5:
/home/haerski/work/M2/M2/Macaulay2/d/../c/compat.h:4:14: error: two or more data types in declaration specifiers
    4 | typedef char bool;
      |              ^~~~
compilation terminated due to -Wfatal-errors.
```

Line 52 in `umachine.h` contains `#include <stdbool.h>`, which interferes with the `typedef` in Macaulay2's `compat.c`.

I tried to build using Cmake with the option `DWITH_XML=OFF`, but it didn't build at all. Building does work when I downgrade `icu` and everything that depends on it.

**Comment by mahrud** [comment]
I don't think Macaulay2 has worked without xml in a long time. It certainly didn't work on with autotools when the cmake build was added.

`compat.h` is a weird file, I'd be happy to see it removed altogether, but since it's in the scc directory, I don't know the extent of the implications. @DanGrayson?

**Comment by mahrud** [comment]
It is strange that you get issues with boost 68 though, since I'm building with 69 without any issues!

**Comment by haerski** [comment]
I'm not on boost 68, I'm on boost 1.75.0. The issue is not with boost, but [ICU](http://site.icu-project.org/home), which is a dependency of boost. I can build Macaulay2 just fine with boost 1.75.0 built against ICU 67.

**Comment by DanGrayson** [comment]
> I don't think Macaulay2 has worked without xml in a long time. It certainly didn't work on with autotools when the cmake build was added.
> 

The inclusion of xml was an experiment -- perhaps we don't need it.

> `compat.h` is a weird file, I'd be happy to see it removed altogether, but since it's in the scc directory, I don't know the extent of the implications. @DanGrayson?

What's weird about it?  It just includes a few standard system files, for the benefit of the *.c files in the c directory.

**Comment by jkyang92** [comment]
I had a similar issue compiling on gentoo. I suspect something (maybe ICU) is pulling in `stdbool.h` which defines `bool`. I assume that this typedef of bool dates to before `stdbool.h` was common. A short fix is adding a `#ifndef bool` arround the typedef but perhaps it is better to switch to using `stdbool.h`?

**Comment by mahrud** [comment]
That sounds like an easy fix. Alternatively, we could check if `stdbool.h` exists beforehand and use `#if HAVE_STDBOOL_H`.

**Comment by haerski** [comment]
After a recent system upgrade, this seems to be fixed now on Arch.
