### ISSUE TITLE
"can't determine symbol whose value is document tag" running "check" on all packages

### ISSUE THREAD

**Issue by d-torrance** [Macaulay2/M2#1748]
Since the recent changes to `check` to use `capture`, the `M2 --check 3` command line option (which checks all packages) isn't working properly if `-q` is also given.  Here's some code that reproduces the problem and also prints the errors that `--check 3` itself hides:

```m2
pkgs = sort separate(" ", version#"packages")
debuggingMode = false
for pkg in pkgs do try (
    print("checking " | pkg | " ...");
    check pkg
    ) else print last capture("check \"" | pkg | "\"")
```

Things run smoothly until we get to `InvariantRing`:

```m2
checking InvariantRing ...

i1 : check "InvariantRing"
/usr/share/Macaulay2/Core/debugging.m2:20:6:(1):[42]: error: can't determine symbol whose value is document tag: false
/usr/share/Macaulay2/Core/methods.m2:105:83:(1):[40]: --back trace--
/usr/share/Macaulay2/Core/option.m2:16:8:(1):[39]: --back trace--
/usr/share/Macaulay2/Core/document.m2:142:13:(1):[38]: --back trace--
/usr/share/Macaulay2/Core/methods.m2:105:83:(1):[37]: --back trace--
/usr/share/Macaulay2/Core/hypertext.m2:231:117:(1):[35]: --back trace--
/usr/share/Macaulay2/Core/hypertext.m2:229:39:(1):[34]: --back trace--
/usr/share/Macaulay2/Core/setup.m2:23:40:(1):[33]: --back trace--
/usr/share/Macaulay2/InvariantRing/HawesDoc.m2:52:53:(2):[32]: --back trace--
/usr/share/Macaulay2/Core/setup.m2:114:27:(1):[31]: --back trace--
/usr/share/Macaulay2/Core/setup.m2:107:18:(1):[30]: --back trace--
/usr/share/Macaulay2/Core/setup.m2:127:41:(1):[29]: --back trace--
/usr/share/Macaulay2/Core/setup.m2:130:6:(1):[28]: --back trace--
/usr/share/Macaulay2/InvariantRing.m2:145:1:(2):[27]: --back trace--
/usr/share/Macaulay2/Core/setup.m2:114:27:(1):[27]: --back trace--
/usr/share/Macaulay2/Core/setup.m2:107:18:(1):[26]: --back trace--
/usr/share/Macaulay2/Core/setup.m2:127:41:(1):[25]: --back trace--
/usr/share/Macaulay2/Core/setup.m2:130:6:(1):[24]: --back trace--
/usr/share/Macaulay2/Core/packages.m2:177:5:(1):[23]: --back trace--
/usr/share/Macaulay2/Core/methods.m2:119:80:(1):[22]: --back trace--
/usr/share/Macaulay2/Core/option.m2:16:8:(1):[21]: --back trace--
/usr/share/Macaulay2/Core/packages.m2:191:10:(1):[20]: --back trace--
/usr/share/Macaulay2/Core/methods.m2:119:80:(1):[19]: --back trace--
/usr/share/Macaulay2/Core/option.m2:16:8:(1):[18]: --back trace--
/usr/share/Macaulay2/Core/testing.m2:62:52:(1):[17]: --back trace--
/usr/share/Macaulay2/Core/methods.m2:119:80:(1):[15]: --back trace--
/usr/share/Macaulay2/Core/option.m2:16:8:(1):[14]: --back trace--
/usr/share/Macaulay2/Core/testing.m2:59:33:(1):[13]: --back trace--
/usr/share/Macaulay2/Core/methods.m2:119:80:(1):[12]: --back trace--
currentString:1:1:(3):[10]: --back trace--
```

There ends up being a bunch of these, all with basically the same error, e.g.,:

```m2
i1 : check "LieTypes"
/usr/share/Macaulay2/Core/debugging.m2:20:6:(1):[45]: error: can't determine symbol whose value is document tag: Ring of Number
...
i1 : check "M0nbar"
/usr/share/Macaulay2/Core/debugging.m2:20:6:(1):[45]: error: can't determine symbol whose value is document tag: Ring of Number
...
i1 : check "Macaulay2Doc"
/usr/share/Macaulay2/Core/debugging.m2:20:6:(1):[50]: error: can't determine symbol whose value is document tag: Ring of Number
```
and so on.  The full log is at https://gist.github.com/d-torrance/6a26199d32c75383f0449b6964232391.

I'm stumped as to what's going on.  Any ideas?

**Comment by mahrud** [comment]
Why are you doing `capture("check \"" | pkg | "\"")`? This isn't what capture is designed for. You should just call `check` on the package.

**Comment by d-torrance** [comment]
> Why are you doing `capture("check \"" | pkg | "\"")`? This isn't what capture is designed for. You should just call `check` on the package.

Just temporarily for the purposes of seeing the error messages.  `--check 3` just does `try check pkg` and increments a counter every time there's an error.  But we don't see the error itself.

**Comment by mahrud** [comment]
You should call `check` with some options instead. Either way, `capture` is a long way from being able to call `capture` inside itself (in this case, `check` calls `capture`) and should not be used like this.

**Comment by d-torrance** [comment]
We're running into the errors before `check` ever gets to calling any `capture`'s inside the outer `capture`. Running `capture("needsPackage \"" | pkg | "\"")` also works at showing what's going on for most of the packages (I think it failed to show the error for `Macaulay2Doc`, which is why I switched to `check`.)

Like I said, this isn't a permanent thing -- just some debugging code so I can figure out why the actual code isn't working:

https://github.com/Macaulay2/M2/blob/67e9aae6beee30c90001d5cb2b452b43f7205346/M2/Macaulay2/m2/startup.m2.in#L527-L531

We don't see error messages that happen inside of `try` unless the code we're running prints them for us (like`check` does after it starts running tests).

I've tried calling `check` with `UserMode` set to `false` and get the same behavior.  And `Verbose` won't be helpful because the errors are happening before any tests are run.

**Comment by mahrud** [comment]
You can use `capture(/// ... ///, Package => pkg, UserMode => false )`, but again, this isn't the purpose of `capture`. I don't think `try` should be used for this purpose either, for that matter, precisely because it hides where the bug is.

**Comment by d-torrance** [comment]
> I don't think `try` should be used for this purpose either, for that matter, precisely because it hides where the bug is.

Yeah, that's a great point.  I think I'll switch `--check 3` to run `check` on each package separately in its own child instance of `M2`.  That should sidestep this issue as well as avoid obscuring things with `try`.

**Comment by mahrud** [comment]
I'll close this, but if you have specific suggestions about how capture should be improved, feel free to bring it up under #1689.
