### ISSUE TITLE
net TABLE bugs

### ISSUE THREAD

**Issue by pzinn** [Macaulay2/M2#1752]
recording for posterity. will fix.
- `net TABLE` incorrectly displays one line tables: compare
```
i1 : needsPackage "Text"; net TABLE {{"one","line"},{"two","lines"}}

o2 = oneline 
     twolines
```
(though spacing could be improved) and
```
i3 : net TABLE {{"one","line"}}

o3 = one 
     line
```
- `net TABLE` does not treat `TR` options correctly:
```
i4 : net TABLE {TR{"one","line","style"=>"background:red"},{"two","lines"}}

o4 = oneline style => background:red
     twolines                       
```

**Comment by pzinn** [comment]
the first bug is of course related to #1548, and it's not the first time I've encountered such issues.

**Comment by DanGrayson** [comment]
A work-around (for better spacing) would be this:
```m2
i9 : netList( {{"one","line"},{"two","lines"}}, Boxes=>false, HorizontalSpace => 2)

o9 = one  line 
     two  lines
```

**Comment by pzinn** [comment]
> A work-around (for better spacing) would be this:
> 
> ```m2
> i9 : netList( {{"one","line"},{"two","lines"}}, Boxes=>false, HorizontalSpace => 2)
> 
> o9 = one  line 
>      two  lines
> ```

Yes, and I see no reason why it wouldn't be part of `net TABLE`, as in the suggested fix.
