### ISSUE TITLE
Empty nets and toExternalString

### ISSUE THREAD

**Issue by d-torrance** [Macaulay2/M2#1763]
There appears to be two families of empty nets:

* The empty string turned into a net, e.g.,:
```m2
i1 : emptyNet = ""^0

o1 = 

i2 : height emptyNet, depth emptyNet

o2 = (1, 0)
```

* The output of `horizontalJoin()` which has zero rows instead of one:

```m2
i3 : emptyNet2 = horizontalJoin()

o3 = 

i4 : class emptyNet2, height emptyNet2, depth emptyNet2

o4 = (Net, 0, 0)
```

The issue is `toExternalString` doesn't play nicely with the second family -- it gives us something belonging to the first family:

```m2
i5 : toExternalString emptyNet2

o5 = ""^-1

i6 : value o5 == emptyNet2

o6 = false

i7 : value o5 == emptyNet^-1

o7 = true
```

**Comment by DanGrayson** [comment]
Thanks!
