### ISSUE TITLE
Cygwin can not get setup from http://macaulay2.com/Repositories/cygwin/

### ISSUE THREAD

**Issue by thuy48** [Macaulay2/M2#1765]
with both 32 and 64 bits versions, I got the same error:
Cygwin can not get setup from http://macaulay2.com/Repositories/cygwin/
What do I need to do?
Thanks

**Comment by DanGrayson** [comment]
We gave up on porting Macaulay2 to cygwin long ago.  If you have Windows 10, you can run it under the ubuntu subsystem, as we describe.

I've edited the web pages to remove those obsolete references to Cygwin.
