### ISSUE TITLE
apply, \, and BasicLists

### ISSUE THREAD

**Issue by d-torrance** [Macaulay2/M2#1776]
The following works as expected:

```m2
i1 : Foo = new Type of BasicList;

i2 : foo = new Foo from {1, 2, 3};

i3 : apply(foo, x -> x^2)

o3 = Foo{1, 4, 9}

o3 : Foo
```

But `\` is only defined for `VisibleLists`'s, so it doesn't work:

```m2
i4 : (x -> x^2) \ foo
stdio:4:12:(3): error: no method for binary operator \ applied to objects:
--            -*Function[stdio:4:4-4:9]*- (of class FunctionClosure)
--      \     Foo{1, 2, 3} (of class Foo)
```

Is this intended, or would it make sense to expand `\` (and `/`) to work for `BasicList`'s?

**Comment by mahrud** [comment]
I don't think so, because you may want to define division on a type that inherits from BasicList.

**Comment by DanGrayson** [comment]
Yes, types inheriting from BasicList are not necessarily to be thought of as lists of similar things, they could classify any sort of thing, so the expansion would not fit the design.

**Comment by d-torrance** [comment]
Makes sense -- thanks for clarifying!
