### ISSUE TITLE
path to file mangled

### ISSUE THREAD

**Issue by DanGrayson** [Macaulay2/M2#1779]
What happened to the initial / in the file name in the error message here?
```m2
+ /Users/dan/src/M2/M2.git/M2/BUILD/dan/builds.tmp/gallium-release-1.17/M2 --no-readline --print-width 105
Macaulay2, version 1.16.99
Users/dan/src/M2/M2.git/M2/Macaulay2/m2/methods.m2:3:1:(1):[6]: error: debug me
```

@mahrud @d-torrance

**Comment by d-torrance** [comment]
I can't reproduce this issue unless my current working directory is a parent of the one containing the file with the error, which is to be expected with `minimizeFilename`.

**Comment by d-torrance** [comment]
Actually, I was able to find a similar issue.  If the error is raised in `startup.m2.in`, then the path isn't correct.  But maybe that's okay since `startup.m2.in` just exists as a string?

```m2
profzoom@peg-amy:/tmp$ M2 --check 4
Macaulay2/Core/startup.m2.in:561:33:(0):[1]: --check 4: expected 1, 2, or 3
Macaulay2/Core/startup.m2.in:561:33:(0):[1]: --entering debugger (type help to see debugger commands)
```

**Comment by DanGrayson** [comment]
Hmm, it came back:
```m2
+ /Users/dan/src/M2/M2.git/M2/BUILD/dan/builds.tmp/gallium-release-1.17/M2 --no-readline --print-width 102
Macaulay2, version 1.16.99
/Users/dan/src/M2/M2.git/M2/Macaulay2/m2/methods.m2:3:1:(1):[6]: error: debug me
```

Closing.
