### ISSUE TITLE
Upgrade to FLINT 2.7.0

### ISSUE THREAD

**Issue by slel** [Macaulay2/M2#1808]
Currently Macaulay2 needs FLINT 2.6.x and won't run with FLINT 2.7.x and
Homebrew install instructions suggest `brew remove flint` as a first step.

Supporting FLINT 2.7.x would help compatibility with other math software.

Indeed, some users might have installed FLINT and other math software
depending on it such as Arb and GAP via brew, and have built SageMath
using those brew installed dependencies.

**Comment by DanGrayson** [comment]
Yes, this should be done.

**Comment by mahrud** [comment]
I'll try to rename flint into a versioned, key only formula for now. We'll see if the build succeeds: https://github.com/Macaulay2/homebrew-tap/pull/58

**Comment by mikestillman** [comment]
I also would prefer to be using 2.7.0.  But wasn't the problem that factory was not updated to use it?

**Comment by mahrud** [comment]
Factory 4.2.0 uses FLINT 2.7.0, but there were a few bugs (e.g. https://github.com/Singular/Singular/issues/1039 and https://github.com/Singular/Singular/issues/1040) early on and I wasn't sure when they would be fixed.

**Comment by DanGrayson** [comment]
I just asked Hans Schoenemann, and he says " Singular 4.2.0 works with flint 2.4.x to 2.7.0, I will extract the factory files soon."

**Comment by mahrud** [comment]
@slel flint@2.6.3 is not keg only, so you can have two different versions installed side by side and M2 will use the correct one.

@DanGrayson, you can remove the passage mentioning that `flint` needs to be removed from the website.

**Comment by DanGrayson** [comment]
> @DanGrayson, you can remove the passage mentioning that `flint` needs to be removed from the website.

Well, I had to remove it to make it work.

**Comment by mahrud** [comment]
It's not necessary anymore.

**Comment by DanGrayson** [comment]
Did you change something?

**Comment by DanGrayson** [comment]
Maybe you changed it to keg-only?

**Comment by mahrud** [comment]
Yes.

**Comment by DanGrayson** [comment]
Ah, okay, I'll fix the web site instructions.
