### ISSUE TITLE
Empty Layout directories

### ISSUE THREAD

**Issue by d-torrance** [Macaulay2/M2#1810]
There are three directories referred to in the `Layout` hash tables which may be empty if Macaulay2 doesn't build any of its dependencies:

```m2
	       "libraries" => "@librariesdir@/",
	       "programs" => "@programsdir@/",
	       "program licenses" => "@licensesdir@/",
```
In the autotools build, all of them are created during `make -C libraries`.  (Until #1803, `@librariesdir@` was only created if needed.)

On one hand, they're referred to in the `Layout` hash tables and in some documentation ([here](http://www2.macaulay2.com/Macaulay2/doc/Macaulay2-1.17/share/doc/Macaulay2/Macaulay2Doc/html/_teaching_sp__M2_sphow_spto_spfind_spits_spshared_splibraries.html), [here](http://www2.macaulay2.com/Macaulay2/doc/Macaulay2-1.17/share/doc/Macaulay2/gfanInterface/html/___Installation_spand_sp__Configuration_spof_spgfan__Interface.html), and [here](http://www2.macaulay2.com/Macaulay2/doc/Macaulay2-1.17/share/doc/Macaulay2/Macaulay2Doc/html/_copyright.html)), so it would make some sense if they exist despite being empty.  But on the other hand, it's odd to be shipping empty directories.  (See, for example, the Lintian [package-contains-empty-directory](https://lintian.debian.org/tags/package-contains-empty-directory.html) warning.)

What would be best?

**Comment by DanGrayson** [comment]
I think it doesn't matter much now, despite the lintian warning.  In the long run, we'll expect to find all needed libraries and programs available as packages, so all the stuff about building submodules and libraries and shipping them with will probably be removed.

**Comment by d-torrance** [comment]
Sounds good.  I'll go ahead and close this then.

(I'm manually removing the empty `libraries` directory in the Debian package to avoid the Lintian warning, and the other two aren't even installed since they're under `$libexecdir`, which I don't even bother installing since it's empty.)
