### ISSUE TITLE
upgrade to flint 2.7.1

### ISSUE THREAD

**Issue by DanGrayson** [Macaulay2/M2#1830]
"This fixes a number of (serious) bugs and build issues with the recent flint-2.7.0."

**Comment by mahrud** [comment]
There's nothing for me to do other than change a submodule hash. You should just fix #1292, then both build systems will follow the same submodule commit. I'll unassign myself.

**Comment by DanGrayson** [comment]
Yes, I should do that, but I don't have time at the moment.

**Comment by d-torrance** [comment]
Fixed in 721e350 (autotools) and 2690ed4 (cmake).
