### ISSUE TITLE
Intel TBB use

### ISSUE THREAD

**Issue by mikestillman** [Macaulay2/M2#1836]
We are thinking of making use of TBB required for Macaulay2 (i.e. to build M2, one would first need to install it from e.g. brew, or the linux installation, ...).  Does anyone know of any hardware/distributions where this would be a problem? @d-torrance @mahrud ?

**Comment by mahrud** [comment]
I don't.

**Comment by d-torrance** [comment]
Looks fine to me.  The TBB package is present on all the official Debian architectures (https://packages.debian.org/sid/libtbb2).

**Comment by DanGrayson** [comment]
The latest CentOS has the library under the name "tbb".

**Comment by DanGrayson** [comment]
... similarly for Arch and Fedora.

**Comment by mahrud** [comment]
Might be worth it to address https://github.com/Macaulay2/mathicgb/issues/23 before doing this. It was causing issues with the brew build, hence why by default the brew package doesn't use tbb.
