### ISSUE TITLE
gcd(0,0,...) leads M2 1.17 to crash

### ISSUE THREAD

**Issue by giovannistagliano** [Macaulay2/M2#1851]
This is a simple example where i get a crash of M2: 
`O = 0_(ZZ/41[x]); gcd {O,O}`

This is another example:
`O = 0_(ZZ/41[x]); gcd {O,O,x}`

But strangely the following work:
`O = 0_(ZZ/41[x]); gcd {O,x,O}; gcd {O,x}; gcd {O}; `

Before my terminal closes I get this error:

`Flint exception (Impossible inverse):
    Cannot invert modulo 41*1
Aborted (core dumped)
`

**Comment by mikestillman** [comment]
I missed this one, apparently.  I'll work on fixing it.  Sorry for the late response on it!

**Comment by mikestillman** [comment]
@DanGrayson This one is easy to fix, I think.  Should I fix it for 1.20?  Or have you already started release builds...?

**Comment by DanGrayson** [comment]
Sure, I can wait a little while.
