### ISSUE TITLE
making QthPower "minimization" example killed on mipsel

### ISSUE THREAD

**Issue by d-torrance** [Macaulay2/M2#1884]
From the [build of the Debian package on mipsel](https://buildd.debian.org/status/fetch.php?pkg=macaulay2&arch=mipsel&ver=1.17.1%2Bds-2&stamp=1611657967&raw=0):

```m2
-- making example results for "minimization"                               
 ulimit -c unlimited; ulimit -t 700; ulimit -m 850000; ulimit -s 8192; ulimit -n 512;  cd /tmp/M2-7649-0/7-rundir/; GC_MAXIMUM_HEAP_SIZE=400M "/<<PKGBUILDDIR>>/M2/usr-dist/mipsel-Linux-Debian-buildd-unstable/bin/M2-binary" -q --int --no-randomize --no-readline --silent --stop --print-width 129 -e 'needsPackage("QthPower",Reload=>true,FileName=>"/<<PKGBUILDDIR>>/M2/Macaulay2/packages/QthPower.m2")' <"/tmp/M2-7649-0/0_minimization.m2" >>"/<<PKGBUILDDIR>>/M2/usr-dist/common/share/doc/Macaulay2/QthPower/example-output/_minimization.errors" 2>&1
/<<PKGBUILDDIR>>/M2/usr-dist/common/share/doc/Macaulay2/QthPower/example-output/_minimization.errors:0:1: (output file) error: Macaulay2 killed by signal 9
/tmp/M2-7649-0/0_minimization.m2:0:1: (input file)
M2: *** Error 9
 -- 680.399 seconds elapsed
 -- storing example results from output file../../../usr-dist/common/share/doc/Macaulay2/QthPower/example-output/_minimization.out
 -- warning: missing file /<<PKGBUILDDIR>>/M2/usr-dist/common/share/doc/Macaulay2/QthPower/example-output/_minimization.out
../../m2/debugging.m2:20:6:(1):[9]: error: installPackage: 1 error(s) occurred running examples for package QthPower:

_minimization.errors
********************
o4 : Sequence

i5 : ic2 = minimization(ic1); toString ic2

o6 = {matrix {{45, 40, 38, 35, 31, 30, 25, 20, 15, 10, 12, 5}}, (ZZ/2)[p_0..p_11], {p_10^3+p_4*p_11, p_4*p_10+p_2*p_11+p_10,
     p_2*p_10+p_11^10+p_10^2*p_11^2+p_10, p_4^2+p_10*p_11^10+p_4*p_11^3+p_4+p_10^2,
     p_2*p_4+p_10^2*p_11^9+p_2*p_11^3+p_4+p_10*p_11^2, p_2^2+p_4*p_11^9+p_11^12+p_11^9+p_10^2*p_11^4+p_2+p_10*p_11^2}}

i7 : ic3 = qthIntegralClosure(ic2#0,ic2#1,ic2#2)
Killed
```

We could probably stand to have a smaller example here.  The same example took nearly 28 seconds during the [amd64 build](https://buildd.debian.org/status/fetch.php?pkg=macaulay2&arch=amd64&ver=1.17.1%2Bds-2&stamp=1611607466&raw=0):

```m2
 -- making example results for "minimization"                                -- 27.8484 seconds elapsed
 -- storing example results from output file../../../usr-dist/common/share/doc/Macaulay2/QthPower/example-output/_minimization.out
```

**Comment by DanGrayson** [comment]
@Douglas-Leonard -- can you think of a good way for us to simplify your example that's failing in certain tests?  The goal would be to consume less memory and less time.

**Comment by d-torrance** [comment]
This also failed on the [riscv64 build](https://buildd.debian.org/status/fetch.php?pkg=macaulay2&arch=riscv64&ver=1.17.1%2Bds-2&stamp=1611697163&raw=0).  It managed to build on [riscv64 in Ubuntu](https://launchpadlibrarian.net/519703563/buildlog_ubuntu-hirsute-riscv64.macaulay2_1.17.1+ds-2_BUILDING.txt.gz), but took 10 minutes!

```m2
 -- making example results for "minimization"                                -- 601.862 seconds elapsed
 -- storing example results from output file../../../usr-dist/common/share/doc/Macaulay2/QthPower/example-output/_minimization.out
```

**Comment by Douglas-Leonard** [comment]
So this worked in 1.16, not so much in 1.17.

There are two minimization examples,
the one you mentioned in the minimization documentation;
another as part of the first test example in the package,
but that seems to work just fine.

Doug

P.S. I sent papers on extension and desingularization to Mike a while ago. These contain M2 code not yet written as a Package. But I think I like my view of desingularization of function fields and need feedback. I also sent him my integral closure of ideals stuff from 2014-Berkeley that never got added into my QthPower package. And I may have sent him code on free resolutions as well. I'm looking for people with interest in any of these.
________________________________

**Comment by d-torrance** [comment]
> So this worked in 1.16, not so much in 1.17.

I think it's likely that it would have failed on these architectures in 1.16, too, but those builds had other problems much earlier on in the process, before they got as far as this example!  :)

**Comment by Douglas-Leonard** [comment]
So what do I do with that info? I have no idea what has changed or what got affected in my package?

Doug
________________________________

**Comment by d-torrance** [comment]
> So what do I do with that info? I have no idea what has changed or what got affected in my package?

I don't think anything has changed other than Macaulay2 now exists as a Debian package, and so it's getting built on a wider variety of systems than it used to, some of which can't handle documentation with large examples.

I think swapping the `minimization` example out with something smaller, like maybe the one you mentioned from the tests, would work.
