### ISSUE TITLE
strategies of resolution

### ISSUE THREAD

**Issue by mahrud** [Macaulay2/M2#1913]
Is there a place to look for the latest strategies for resolutions? I'm specifically curious about 4, 4.1, 5, 5.1. Over the rationals they produce a complex, but the maps are not there somehow.

**Comment by mahrud** [comment]
cc: @mikestillman

**Comment by mikestillman** [comment]
4.1 and 5.1 will be removed.  The resolution code will soon work over all basic ring types.  Currently, over QQ it is doing a complete hack/experiement: using combination real/ZZp to work over QQ.  It was useful for a project I was doing, but not for a general facility.  So it is being removed.  Strategy 4 on the other hand is just the FastNonminimal code.  Currently, it only works over ZZ/p (but soon over other base fields).

**Comment by mahrud** [comment]
Thanks! Roughly speaking, what is the strategy behind 0, 1, 2, and 4? (e.g. are they strategies coming from a paper or not)
