### ISSUE TITLE
exporting methods

### ISSUE THREAD

**Issue by eisenbud** [Macaulay2/M2#192]
It would be nice if packages could add specified methods to the automatically generated lists of hyperlinks even when the methods are installed on previously existing classes and method functions.

eg 

(resolutions, ChainComplex)

as an element of the export list.

**Comment by mahrud** [comment]
This happens with typing `help` now:
```m2
i1 : needsPackage "NormalToricVarieties"

o1 = NormalToricVarieties

o1 : Package

i2 : help ring

o2 = ring -- get the associated ring of an object
     ********************************************

...

       * "ring(NormalToricVariety)" -- make the total coordinate ring (a.k.a. Cox ring)

     For the programmer
     ==================

     The object "ring" is a method function.
```
But not on the online documentation. Is that good enough?

To change the online documentation would require more permeating changes.
