### ISSUE TITLE
documentation HTML link bug

### ISSUE THREAD

**Issue by pzinn** [Macaulay2/M2#1920]
```
i1 : help Matroids
--warning: symbol "Matroids" in PackageDictionary is shadowed by a symbol in User#"private dictionary"
--  use the synonym Package$Matroids

o1 = Matroids -- a package for computations with matroids
     ****************************************************
.
.
.

o1 : DIV

i2 : oo#1#1#2#3

o2 = taking subscripts

o2 : TO2

i3 : html oo
stdio:3:1:(3): error: expected argument 1 to be null, a sequence, list, string, net, hashtable, database, or dictionary
```
The culprit is `fixup` which tries to call `package` on the tag's key:
```
i4 : o2#0

o4 = Matroids :: Matroid _ List

o4 : DocumentTag

i5 : debug Core; fixup o4
stdio:7:1:(3): error: expected argument 1 to be null, a sequence, list, string, net, hashtable, database, or dictionary

i6 : o4.Key

o6 = (_, Matroid, List)

o6 : Sequence
```
that's as far as I got in the debugging, I don't fully understand the inner workings of `package`.

**Comment by mahrud** [comment]
It doesn't have to do with `package`, you just haven't run `needsPackage`, why should that work? The warning is here:
```m2
i1 : help Matroids;
--warning: symbol "Matroids" in PackageDictionary is shadowed by a symbol in User#"private dictionary"
--  use the synonym Package$Matroids
```
Calling `help Matroids` doesn't actually load the package, so in the key `(_, Matroid, List)`, the `Matroid` is not a Type, it's a symbol:
```m2
i2 : help Matroid

o2 = Matroid
     *******

     For the programmer
     ==================

     The object "Matroid" is a symbol.

o2 : DIV
```
So I don't think this is a bug. You could make an argument to have `help [package name]` automatically load the package, but I'm not sure if that's wise.

I wish we could prevent symbols from leaking into the User private dictionary:
```m2
i3 : peek User#"private dictionary"

o3 = GlobalDictionary{"kk" => kk            }
                      "Matroid" => Matroid
                      "Matroids" => Matroids
                      "q" => q
                      "t" => t
                      "v" => v
```
But I don't believe that's avoidable.

It might be an improvement to make the error clearer. You get the same thing if you type some nonsense symbols:
```m2
i4 : makeDocumentTag (symbol_, Blah, Foo)
stdio:13:1:(3): error: expected argument 1 to be null, a sequence, list, string, net, hashtable, database, or dictionary
```
Maybe it should instead say:
```m2
stdio:10:1:(3): error: documentation key for "Blah _ Foo" encountered, but no method installed
```
To match this:
```m2
i10 : package(symbol_, ZZ, List)
stdio:12:1:(3): error: documentation key for "ZZ _ List" encountered, but no method installed
```
But I don't know how to do that easily without breaking other things, and I don't think it's urgent anyway.

**Comment by pzinn** [comment]
OK then why does it even print the documentation page at all when you type `help Matroids` without having loaded the package?
and produce a broken `Hypertext` object. Incidentally, another even more brutal way this occurs is in WebApp mode:
```
i1 : topLevelMode = WebApp; help Matroids
--warning: symbol "Matroids" in PackageDictionary is shadowed by a symbol in User#"private dictionary"
--  use the synonym Package$Matroids
stdio:1:24:(3): error: at print: expected argument 1 to be null, a sequence, list, string, net, hashtable, database, or dictionary
```

**Comment by mahrud** [comment]
It's unfortunate that it doesn't work in webapp mode, but it's a harmless
feature that provides a sneak peek of the documentation for
installed packages without the need to load it. It's simply reproducing
what is stored in the raw documentation database, and unfortunately that
data isn't enough to convert the output to html before the package is
loaded.

You can disable it in webapp mode by overriding allPackages to return an
empty list. This doesn't affect anything else because that function isn't
used anywhere else.

Isn't viewHelp the preferred method for accessing the documentation from
the webapp anyway? I remember you noted a similar issue with help "packages
provided with Macaulay2" taking too long. Why not have help simply call
viewHelp in the webapp mode and open the pre-generated documentation in
another tab?

**Comment by pzinn** [comment]
OK. will think about this some more. I suppose it is not top priority, and in view of the amount of open issues at the moment, I think I'll close this one.
