### ISSUE TITLE
Trying to form the quotient ring of a Laurent polynomial ring hangs

### ISSUE THREAD

**Issue by pzinn** [Macaulay2/M2#193]
The following

R=QQ[x,Inverses=>true,MonomialOrder=>RevLex]
R/ideal(x-1)

results in M2 getting stuck  (the function rawQuotientRing line 195 of quotring.m2 never returns).
If (as I suspect) quotient rings of Laurent polynomial rings are not implemented, M2 should say so.

**Comment by mikestillman** [comment]
Error message added, commit cdb5df8b04

**Comment by mikestillman** [comment]
Changing this to an issue for 1.9

**Comment by DanGrayson** [comment]
The package QuillenSuslin is using this, but perhaps the code is giving wrong answers!

**Comment by mikestillman** [comment]
Quillen-Suslin now doesn't need Groebner operations over Laurent rings.  All uses (I hope) have been removed.  isUnit for Laurent rings is now functional, not using Groebner basis computation.
