### ISSUE TITLE
List << List

### ISSUE THREAD

**Issue by mahrud** [Macaulay2/M2#1945]
This is a suggestion to implement the following method:
```m2
i1 : List << List := (A, B) -> #A == #B and all(#A, i -> A#i <= B#i);

i2 : {1,2,3} << {1,2,3}

o2 = true

i3 : {1,2,3} << {1,5,3}

o3 = true

i4 : {1,2,-1} << {1,5,3}

o4 = true

i5 : {1,2,3} << {1,5,-1}

o5 = false
```
This would be a partial order, which is why `A#i <= B#i` makes more sense, because with `<` we wouldn't know if `A << B and B << A` implies `A==B` or not.

Of course, there are many ways to impose a total order on lists, one for each monomial order probably, but I think this is a natural order to have because `A << B` always implies that the multinomial `x^B` is in the ideal of `x^A`.

I'd like to have this as a simplification in order to generalize `DegreeLimit` options, for instance:
- `res(..., DegreeLimit => {1,2,3})` should compute up to and including degree `<< {1,2,3}` (hence `<=` above)
- `basis({0,0,0},{1,2,3}, R)` currently is not accepted by the basis command, but it could just print the basis for all multidegrees `{0,0,0} << D << {1,2,3}`
- this would match how `submatrixByDegrees` interprets the results.

Tangentially related: I think `CC < CC` should give an error. It's not mathematically correct!

**Comment by mahrud** [comment]
@mikestillman @DanGrayson any objections to this?

**Comment by DanGrayson** [comment]
I can't think of a better use for List << List.  In the documentation, please compare it to the behavior of List ? List and friends (such as List <= List).

What's wrong with CC < CC?   Yes, CC is not an ordered field, but it's convenient, for printing, to put things in order.

**Comment by mahrud** [comment]
> What's wrong with CC < CC? Yes, CC is not an ordered field, but it's convenient, for printing, to put things in order.

Plenty of things that are wrong are convenient, that's not a good reason. If user wants to sort some complex numbers before printing them, then they should provide such a function. This result is meaningless:
```m2
i1 : sort{1+ii, 1-ii}

o1 = {1-ii, 1+ii}

o1 : List

i2 : sort{2_(ZZ/11), 3_(ZZ/11)}

o2 = {3, 2}

o2 : List
```
It should give an error in both cases.

**Comment by mahrud** [comment]
At the very least, a one time warning should be given that this order is made up, like this one:
```m2
-- warning: experimental computation over inexact field begun
--          results not reliable (one warning given per session)
```
