### ISSUE TITLE
fileExists doesn't understand escaped characters

### ISSUE THREAD

**Issue by d-torrance** [Macaulay2/M2#1946]
I noticed this while working on #1944:

```m2
i1 : run ///touch /tmp/foo\ bar///

o1 = 0

i2 : fileExists ////tmp/foo\ bar///

o2 = false

i3 : fileExists ////tmp/foo bar///

o3 = true
```

The same is true for `fileMode`, and I assume other related functions that deal with files.

**Comment by DanGrayson** [comment]
This behavior is intended.  Escaping special characters is relevant only when passing filenames through the parser of a shell.  The function `fileExists`, by contrast, takes a string that is the exact filename.
