### ISSUE TITLE
infinite loop in Matrix//Number

### ISSUE THREAD

**Issue by pzinn** [Macaulay2/M2#1959]
```
i1 : matrix {{1,2},{3,4}}

o1 = | 1 2 |
     | 3 4 |

              2        2
o1 : Matrix ZZ  <--- ZZ

i2 : oo//2
stdio:2:3:(3): error: recursion limit of 300 exceeded

i3 : code(symbol //,Matrix,Number)

o3 = -- code for method: Matrix // Number
     ../../../M2/M2/Macaulay2/m2/matrix2.m2:360:27-360:50: --source code:
     Matrix // Number := (f,r) -> f // promote(r,ring f)
```

**Comment by mahrud** [comment]
Great example of problems with `Number` not inheriting from `RingElement` (https://github.com/Macaulay2/M2/issues/1519).

If it did, this would be dispatched to the following:
```m2
Matrix      // RingElement := (f,r) -> f // (r * id_(target f))
```
and that works:
```m2
i3 : oo // (2 * id_(target oo))

o3 = | 0 1 |
     | 1 2 |
```

**Comment by DanGrayson** [comment]
`RingElement` is, by definition, the ring elements handled by the engine, so it would be inappropriate for Number to inherit from it.

**Comment by mahrud** [comment]
We had this discussion in the issue I referenced. Nothing about the line
```m2
Matrix      // RingElement := (f,r) -> f // (r * id_(target f))
```
is specific to "ring elements handled by the engine," so perhaps what you really need is an `EngineRingElement` type that, along with `Number`, inherits from `RingElement`. I forget if this was exactly the solution that we arrived at in that issue or not.

**Comment by DanGrayson** [comment]
That sounds good.

**Comment by DanGrayson** [comment]
On second thought, that won't even work, as ring elements are basic lists but numbers aren't:
```m2

i4 : ancestors RingElement 

o4 = {RingElement, BasicList, Thing}

o4 : List

i5 : ancestors Number

o5 = {Number, Thing}

o5 : List
```

**Comment by mahrud** [comment]
Yes, this was also discussed in #1519. The design would need to be modified, but there's no major obstacle.

An alternative approach is something I touched on [here](https://github.com/Macaulay2/M2/issues/1910#issuecomment-780906995), which was to implement a "trait" or ["Concepts"](https://en.wikipedia.org/wiki/Concept_(generic_programming)) system in the top level, either to replace or to work aside our "type" system. The idea is that I could have a type T, which can inherit from Number, BasicList, HashTable, or whatever else, and I declare that it satisfies the RingElement "trait", so ring operations are defined on it. Some methods may need to be be specialized, but most will be identical and can use the default implementation.

How does this sound to you?

**Comment by DanGrayson** [comment]
> Yes, this was also discussed in #1519. The design would need to be modified, but there's no major obstacle.

The major obstacle I see is the one I mentioned before.

> 
> An alternative approach is something I touched on [here](https://github.com/Macaulay2/M2/issues/1910#issuecomment-780906995), which was to implement a "trait" or "[Concept](https://en.wikipedia.org/wiki/Concept_(generic_programming))" system in the top level, either to replace or to work aside our "type" system. The idea is that I could have a type T, which can inherit from Number, BasicList, HashTable, or whatever else, and I declare that it satisfies the RingElement "trait", so ring operations are defined on it. Some methods may need to be be specialized, but most will be identical and can use the default implementation.
> 
> How does this sound to you?

What's the point of such traits?  To give an error message if you forget to implement one of the methods?
