### ISSUE TITLE
M2 errors out when `PATH` has bad characters in it

### ISSUE THREAD

**Issue by KaiSforza** [Macaulay2/M2#1977]
I was just testing this out on WSL and noticed a bunch of warnings popping up when I tried to start `M2`. A seemingly random number of 

```
sh: 1: Syntax error: "(" unexpected
```

errors would pop up every time I started M2. It seems that this is caused by the use of `Program Files (x86)` and other such names normally in the `PATH` variable for WSL. I can recreate this on an Ubuntu server as well as a few other errors related to the PATH variable. I'm not sure what is checking the PATH variable but it seems to be part of the user profile, because passing `-q` silences the error.

```
$ uname -srv
Linux 5.8.0-25-generic #26~20.04.1-Ubuntu SMP Thu Oct 15 14:55:06 UTC 2020
$ PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
$ M2 --silent --no-preload

i1 :
$ PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:(test):test:(broken)"
$ M2 --silent --no-preload
sh: 1: Syntax error: word unexpected
sh: 1: Syntax error: word unexpected

i1 :
$ PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:(unexpected)()"
$ M2 --silent --no-preload
sh: 1: Syntax error: "(" unexpected

i1 :
$ M2 --silent --no-preload -q

i1 :
```

For some reason I cannot get this to reproduce on WSL right now, I'm not sure if it's something that I installed or what.

**Comment by d-torrance** [comment]
I think this may be the same issue as #1503, which has been fixed in git.

**Comment by KaiSforza** [comment]
Ah, you are correct. I just looked at that issue. Going to close this one.
