### ISSUE TITLE
using "jekyll" might allow the Macaulay2 web site to be on github pages

### ISSUE THREAD

**Issue by DanGrayson** [Macaulay2/M2#1987]
Jekyll is a ruby package that generates html files from a variety of template languages, and "github pages" will automatically rerun jekyll on your templates when you push changes.

(The reasons we need html pages to be generated from template source are: (1) so the contents of the sidebars will look the same on all the html pages; (2) so the pages that have binary release files can include links to those.)

It might be better for the binary releases files to be posted as github releases.  And we'd have to keep the Ubuntu and Debian repositories alive for a while.

Hat tip: @pdg137.

**Comment by mahrud** [comment]
This was discussed in https://github.com/Macaulay2/Macaulay2-web-site/issues/8
