### ISSUE TITLE
Lapack detection in the build system is faulty

### ISSUE THREAD

**Issue by tom111** [Macaulay2/M2#20]
The lapack detection code in the build system tries to find lapack by trying to find 
-llapack -lblas -lf77blask like this:

```
              AC_SEARCH_LIBS(sgemv,blas f77blas,,BUILD_lapack=yes)
              AC_SEARCH_LIBS(dgetrf,lapack,,BUILD_lapack=yes)
```

On some systems this will fail although a valid lapack implementation is available. For instance for atlas the correct linker flags are:

-latllapack -latlcblas -lf77blas

On platforms where pkg-config is available this could be fixed by quering for the correct link line like so:

$ pkg-config --libs lapack blas 

On recent linux systems this returns the correct -l flags.

**Comment by DanGrayson** [comment]
@tom111 : 

If "-latllapack -latlcblas -lf77blas" is right on some systems, then I'd like to have more
information.  The way autoconf works it is best to search for one symbol at a time.  Presumably
sgemv appears in one of the two blas libraries, but the other is needed to link with it --
if so, it would be good to learn the name of a symbol from the other library that sgemv depends on,
so I could search for it first.  As a result of a successful search, that other library would be
added to the search path for sgemv.

I'm assuming that once that is done, then dgetrf can be found the usual way.

**Comment by tom111** [comment]
Hmm, do be honest, I have no idea. It is very long ago that I looked into this and understood something about it. 
I found this discussion in the sage community:
https://groups.google.com/forum/#!topic/sage-devel/s-Bvb7tjgE8
and then this:
http://www.gnu.org/software/autoconf-archive/ax_lapack.html
Could that obsolete all your lapack detection routines?

**Comment by DanGrayson** [comment]
Thanks, that looks good!

**Comment by DanGrayson** [comment]
Closing, since the changes I made might have been effective.
