### ISSUE TITLE
trouble running M2 on WSL

### ISSUE THREAD

**Issue by DanGrayson** [Macaulay2/M2#2013]
_Originally posted by @SohamPardeshi in https://github.com/Macaulay2/M2/issues/391#issuecomment-810612248_

I am having trouble running M2 on WSL. Not sure if the issue is mine or with one of the builds provided at [the installation instructions](https://faculty.math.illinois.edu/Macaulay2/Downloads/GNU-Linux/Ubuntu/index.html).  I've tried all of the installation methods documented and for each of them I get the following error:
```
soham@Soham-PC:~$ M2
Wrong __data_start/_end pair
Aborted (core dumped)
```
Here are some relevant specs:
```
soham@Soham-PC:~$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.2 LTS
Release:        20.04
Codename:       focal
```
I've tried this for both WSL1 and 2. Any recommendations?

**Comment by SohamPardeshi** [comment]
Thanks! The discussion in [this Google group](https://groups.google.com/g/macaulay2/c/qYMOAEhbl04) was very helpful. 

Although I probably should have tested each step separately, I manually updated `libgc1c2` and `libgc-dev` and also manually installed the package. One or both of these steps solved my problem on WSL 2.

**Comment by DanGrayson** [comment]
I'm glad it worked.  What do you mean by "manually" updating a package?

**Comment by d-torrance** [comment]
> What do you mean by "manually" updating a package?

I'm curious about this, too. If a Debian/Ubuntu package has been put together properly, then any dependencies should be pulled in automatically.   For the PPA package, `libgc1` is a dependency, so things ought to work out of the box:

```
dtorrance@mixtuppa:~$ apt-cache show macaulay2 | grep Depends
Depends: macaulay2-common (= 1.17.2+ds2-0ppa1~ubuntu20.10.1), singular-data, libblas3 | libblas.so.3, libboost-regex1.71.0-icu67, libboost-stacktrace1.71.0, libc6 (>= 2.29), libflint-2.6.3 (>= 2.6.3), libfrobby0 (>= 0.9.1), libgc1 (>= 1:8.0), libgcc-s1 (>= 3.0), libgdbm6 (>= 1.16), libgivaro9 (>= 4.0.2-8~), libgmp10, libgmpxx4ldbl, liblapack3 | liblapack.so.3, libmathic0v5 (>= 1.0~git20200526), libmathicgb0 (>= 1.0~git20200526), libmemtailor0 (>= 1.0~git20160302), libmpfr6 (>= 3.1.3), libmps3 (>= 3.1.8), libntl43 (>= 11.4.3), libreadline8 (>= 6.0), libsingular4m1, libstdc++6 (>= 5.2), libxml2 (>= 2.7.4)
```

(Note that in Ubuntu 20.04 and earlier, it was `libgc1c2` instead of `libgc1`.  They renamed the binary package last April -- see https://sources.debian.org/src/libgc/1:8.0.4-3/debian/changelog/#L42.)
