### ISSUE TITLE
weird behavior of ".."

### ISSUE THREAD

**Issue by pzinn** [Macaulay2/M2#2020]
note that removing `monoid` or replacing `:=` with `=` will make the problem go away. 
```
i1 : R:=QQ(monoid[x,y,z])

o1 = QQ[x..z]

o1 : PolynomialRing

i2 : R_0..R_2

o2 = (x, y, z)

o2 : Sequence

i3 : class\oo -- expected (R,R,R)

o3 = (Symbol, Symbol, Symbol)

o3 : Sequence
```

**Comment by DanGrayson** [comment]
Yes, it would be an improvement if `..` would yield a sequence of variables in the ring, even in a case like this, where `use` has not yet been run on the ring.  But a decision should be made: if R is ``, then what sequence should `R_0 .. R_5` return?  Probably it should return `(R_0,R_1,R_2,R_3,R_4,R_5)` and not `(R_0,R_3,R_5)`, which is what it currently does:
```m2

i1 : R = QQ[a,x,y,b,z,c]

o1 = R

o1 : PolynomialRing

i2 : a..c

o2 = (a, b, c)

o2 : Sequence

i3 : class \ oo

o3 = (R, R, R)

o3 : Sequence
```

So that would be a breaking change, but probably no one depends on that behavior.

**Comment by pzinn** [comment]
I'm not sure I understand this part: "But a decision should be made: if R is ``, then what sequence should R_0 .. R_5 return?"

**Comment by DanGrayson** [comment]
> I'm not sure I understand this part: "But a decision should be made: if R is ``, then what sequence should R_0 .. R_5 return?"

Fixed, by editing.

**Comment by pzinn** [comment]
OK I understand your point. But now I realize I don't understand what I consider the "good" behavior (which isn't what you're suggesting either):
```
i1 : R:=QQ[x,a,y]

o1 = QQ[x, a, y]

o1 : PolynomialRing

i2 : R_0..R_2

o2 = (x, y)

o2 : Sequence

i3 : class\oo

o3 = (QQ[x, a, y], QQ[x, a, y])

o3 : Sequence
```
why aren't the classes `(Symbol,Symbol)` again?

**Comment by DanGrayson** [comment]
I think it makes sense that the first element of `R_0..R_2` is `R_0`.  That's what the notation suggests.

**Comment by pzinn** [comment]
I'm ready to give up on this and close. But first, I'd like to understand this part of the code: (specifically I don't understand the else clauses of L13-14, and L15)
https://github.com/Macaulay2/M2/blob/3c3e3f7ddbc1a0ff20bd6723e41251557dea2936/M2/Macaulay2/m2/dotdot.m2#L12-L19

**Comment by pzinn** [comment]
on second thought, maybe it'd be nice to implement:
> if R is QQ[a,x,y,b,z,c], then what sequence should R_0 .. R_5 return? Probably it should return (R_0,R_1,R_2,R_3,R_4,R_5) and not (R_0,R_3,R_5), which is what it currently does

would it make the whole of dotdot.m2 obsolete?

**Comment by pzinn** [comment]
Another issue I have with dotdot.m2: why
```
i1 : QQ..QQ
stdio:1:3:(3): error: no method for binary operator .. applied to objects:
--            QQ (of class Ring)
--     ..     QQ (of class Ring)
```
when dotdot.m2 is supposed to define a `Thing .. Thing` method?
```
i2 : methods symbol ..

o2 = {0 => ((.., =), Thing, Thing)                         }
     {1 => ((.., =), Type, Type)                           }
[...]
     {24 => (.., Thing, Thing)                             }
     {25 => (.., ZZ, InfiniteNumber)                       }
     {26 => (.., ZZ, ZZ)                                   }
```

**Comment by DanGrayson** [comment]
I'm pretty sure the Thing..Thing method is just for printing error messages.  But it included one level of indirection, which I've just removed in commit b146e8bc5e12461880193a3224555084ff039de4

**Comment by DanGrayson** [comment]
As you say, this is the current behavior:
```m2
i12 : R = QQ[a,c,b];

i13 : a..c

o13 = (a, b, c)

o13 : Sequence
```

I don't know whether it would be "better" to return `(a,c)`, as you suggest.  Perhaps poll the users who like rings with variables not in alphabetical order.

**Comment by DanGrayson** [comment]
About the code in dotdot.m2 that you asked about, I think the idea there is that users could get the benefit of the operator `..` by simply installing methods for `baseName` for their new classes.  But it didn't quite work, as this test shows:
```m2
Macaulay2, version 1.18
with packages: ConwayPolynomials, Elimination, IntegralClosure, InverseSystems, LLLBases, MinimalPrimes, PrimaryDecomposition, ReesAlgebra, Saturation, TangentCone

i1 : X = new Type of BasicList ;

i2 : x = new X;

i3 : baseName X := x -> 3;

i4 : x .. x
stdio:4:3:(3): error: no method for binary operator .. applied to objects:
--            X{} (of class X)
--     ..     3 (of class ZZ)
```

And the change I just made, referred to above, disables even that partial success.

**Comment by pzinn** [comment]
It seems the conclusion is that indeed, dotdot.m2 is not working as expected. Implementing `RingElement..RingElement` (or something akin to it) might allow to remove dotdot.m2 entirely. I'll give it a try.

**Comment by DanGrayson** [comment]
Okay.

**Comment by pzinn** [comment]
I've been experimenting with this (see commit 611603370326a44b23254032bdececde2c86d723). It's now live on Macaulay2web, and I'm not liking the result. The problem is, it's breaking existing code. A typical problem is, currently one is allowed to do something like
```
R=QQ[m_(1,1)..m_(3,3)];
R=QQ[m_(1,1)..m_(2,2)];
```
and the second ring will have, as expected, 4 gens. with the patch above, M2 interprets `m_(1,1)..m_(2,2)` as ring elements of the first ring and expands it to all ring gens in between, including say `m_(1,3)`. that's bad. might give up on this.

**Comment by pzinn** [comment]
Agreed. but I thought we had strict rules about not breaking existing code? because it certainly breaks some of mine.

**Comment by DanGrayson** [comment]
Yes, let's be conservative here and not break code.

**Comment by pzinn** [comment]
closing this. if we ever change our minds, the commits 611603370326a44b23254032bdececde2c86d723 and 2340541e456bb80201283e72f8d1755e67ad932a are stlil there.

**Comment by mahrud** [comment]
Why not just change `RingElement .. RingElement` to promote the symbols to the ring of the input variables **at the end**?
