### ISSUE TITLE
map(Module, Module, RingElement) and grading

### ISSUE THREAD

**Issue by denham0** [Macaulay2/M2#2023]
The result below isn't what one might expect.  Or is it?  Thanks!

R = QQ[x]
M = R^{-1}
N = R^{-2}
f = map(N,M,x)  -- isomorphism?
0 == coker f       -- no!

**Comment by DanGrayson** [comment]
To say that the matrix of f is {{x}} is to say that it sends the basis vector of M to x times the basis vector of N.  So nothing hits the basis vector of N, and the map is not surjective.  To produce the isomorphism you desire, try this code:

```m2

i22 : f = map(N,M,{{1}},Degree=>1) -- isomorphism?

o22 = {2} | 1 |

              1       1
o22 : Matrix R  <--- R

i23 : isHomogeneous f

o23 = true

i24 : isIsomorphism f

o24 = true

i25 : 0 == coker f

o25 = true
```

**Comment by DanGrayson** [comment]
Please close the issue if this answers your question.

**Comment by denham0** [comment]
Thanks, Dan.  So that explains the example below.  I guess I was somehow expecting the induced map on the common ambient free module, even though the documentation is pretty clear in hindsight.

R = QQ[x]
M = image matrix {{x}}
N = image matrix {{x^2}}
f = map(N,M,x)
0 == coker f    -- false!

isIsomorphism inducedMap(N,M,matrix{{x}}) -- this is what I meant

**Comment by DanGrayson** [comment]
Yes, in general, each module is given my generators and relations, and the matrix of a map tells where the generators go.  Maps are not always induced by maps between the corresponding ambient free modules.
