### ISSUE TITLE
using memory pointers that might be null

### ISSUE THREAD

**Issue by DanGrayson** [Macaulay2/M2#2027]
There should not be any places in the code where a pointer obtained from libgc is used without first testing for NULL, so an appropriate out-of-memory error message can be issued by the routine `outofmem` or `outofmem2`.  A pull request fixing that would be welcome.  It might be good to use the macros in `newdelete.hpp`.

_Originally posted by @DanGrayson in https://github.com/Macaulay2/M2/issues/1429#issuecomment-814298409_

Here is an example:
```c++
inline void mpz_reallocate_limbs (mpz_ptr _z)
{ 
  int _s = _z->_mp_size;
  int _as = (_s>0)?_s:-_s;
  mp_limb_t *_p = (mp_limb_t*) GC_MALLOC_ATOMIC(_as*sizeof(mp_limb_t));
  memcpy(_p,_z->_mp_d,_as*sizeof(mp_limb_t));
  mpz_clear(_z);
  _z->_mp_d = _p;
  _z->_mp_size = _s;
  _z->_mp_alloc = _as;
}
```

Here is another:
```c++
      {
        mArray = static_cast<ElementType*>(GC_MALLOC_UNCOLLECTABLE(sizeof(ElementType) * len));
        //        mArray = new ElementType[len];
        for (size_t i = 0; i < len; i++)
          {
            ring().init(mArray[i]);
            ring().set_zero(mArray[i]);
          }
      }
```

**Comment by DanGrayson** [comment]
@jkyang92 -- can we close this now?

**Comment by jkyang92** [comment]
Go ahead and close it. I don't have permission to do so, since you opened the bug
