### ISSUE TITLE
CentOS8 -  `repomd.xml` parser error at line 13

### ISSUE THREAD

**Issue by adamgranthendry** [Macaulay2/M2#2030]
After `wget` of `Macaulay2-8.repo`, a `sudo yum update` yields the following error:

```
Macaulay2 Repository                           3.2 kB/s | 751  B     00:00
Error: Failed to download metadata for repo 'Macaulay2': repomd.xml parser error: Parse error at line: 13 (Opening and ending tag mismatch: img line 0 and body
)
```

On visual inspection of `repomd.xml` at

```
http://www2.macaulay2.com/Macaulay2/Repositories/Scientific/8/repodata/index.html
```

I can't see any issues. I am connected to Internet and able to install other pacakges via `dnf` and `yum`.

**Comment by DanGrayson** [comment]
I just tried updating, removing and re-installing Macaulay2 here on my CentOS virtual machine, and it worked, every time, so I don't know what could be wrong at your end.

By the way, `Macaulay2-8.repo` refers to `http://macaulay2.com/Repositories/Scientific/8`, not to `http://www2.macaulay2.com/Repositories/Scientific/8`.

**Comment by adamgranthendry** [comment]
@DanGrayson I suspect it's a proxy error on my end. `Macaulay2-8.repo` is correctly pointed to `http://macaulay2.com/Repositories/Scientific/8`, but I still get the error.

**Comment by mahrud** [comment]
Closing. feel free to reopen if this is still occurring.
