### ISSUE TITLE
instance vs class inconsistency?

### ISSUE THREAD

**Issue by haerski** [Macaulay2/M2#2041]
The documentation of `instance` says that "`x` is an instance of `X` if `X` is the class of `x`...". However below is a minimal example where this doesn't seem to be true:
```macaulay2
S = QQ[x,y]
SS = new Module of Vector from S^2

class(SS_0) === S^2 --true
class(SS_0) == S^2 --true
instance(SS_0, S^2) --false
```
Does anyone have an idea of what is going on here?

**Comment by DanGrayson** [comment]
This code illustrates the problem better:
```m2
S = QQ[x]
M = S^2
instance(M_0, M) --true
instance(M_0, S^2) --false
```

What's happening here is that `M` is an immutable type, so `===` comparison is accomplished by comparing the contents.  The modules `M` and the second `S^2` have the same contents but different addresses in memory, and the compiled routine `instance` compares the ancestors of the class of its first argument to the second argument by pointer equality, not by `===` equality.  

If that's too annoying, it could be fixed.  The cost would be a slight slowing of the `instance` function.

**Comment by haerski** [comment]
I see, that makes sense.

I read the `class M_0 == S^2` as content equality, and `class M_0 === S^2` as pointer equality...

I suppose this doesn't warrant changing `instance`, so I'll close this.
