### ISSUE TITLE
bug in Schubert2 blowup?

### ISSUE THREAD

**Issue by mikestillman** [Macaulay2/M2#2051]
This is either a bug or a mis-use (posted on google group), I need to look in into it. In any case, I want to do more testing and doc for blowup...

I am  assigning myself, but help is welcome, if you are interested!

```

fabioec...@gmail.com<fabioeccoloqui@gmail.com>
Apr 28, 2021, 4:34:47 AM (10 days ago) 
to Macaulay2
Hi everybody,

I have been experimenting some strange behavior with the Schubert2 package. I am sharing my problem with you, so that you can help me to understand where I got lost.
I want to compute the Euler characteristic of the exterior powers of the cotangent bundle of the blowup of some Grassmannian along some subvariety. Say, you want to blow up Gr(3,5) along a codimension 3 linear section, which is the sectionZeroLocus of 3 copies of the determinant of the dualised tautological rank 3 subbundle.
Here is my code:

needsPackage("Schubert2");
m=3
k=3
n=5
Gr=flagBundle({k,n-k})
B=bundles Gr
F=(dual det first B)^m
toBlow=sectionZeroLocus(F)
bl=blowup (toBlow.StructureMap)
for i from 0 to dim first bl list chi(exteriorPower(i,cotangentBundle(first bl)))

I was expecting integer numbers, but I got
{25/108,-11/72,-245/18,2867/108,-245/18,-11/72,25/108}

The same issues appear with other triples of (m,k,n), e.g., 
(4, 2, 5)
(4, 3, 6)
(4, 4, 6)
(5, 2, 6)
(6, 3, 6)
and with other invariants as well.
```

**Comment by 8d1h** [comment]
Hi, I think the problem is with this line
https://github.com/Macaulay2/M2/blob/e24bc595e079db4de4cedc5db2948de300eec62a/M2/Macaulay2/packages/Schubert2.m2#L1167
Instead of `(todd OO(-x))^-1` we want `todd((-1) * OO(-x))`, the Todd class of the relative tangent bundle of the inclusion of the exceptional divisor, which should be a bundle of rank -1.

Or we can just remove this line altogether and use the Chern classes to compute the Chern character, in which case we will get the same (correct) result.

**Comment by 8d1h** [comment]
Hi again, I saw the recent discussion on google group, and I want to comment that the results given by Macaulay2 are most likely to be correct.

Particularly, in the case (3,3,5), the Euler number of Ytilde is equal to 18, and there are exactly 18 classes, so it's very likely that we already obtained the entire Hodge diamond, and we can just read off the holomorphic Euler characteristics.
```macaulay2
i19 : R = first flattenRing intersectionRing Ytilde; for i from 0 to 6 list numcols basis_i R

o20 = {1, 2, 4, 4, 4, 2, 1}

o20 : List

i21 : euler Ytilde

o21 = 18
```

**Comment by DanGrayson** [comment]
@8d1h -- thanks for your original bug report, together with the suggested work-around, which we have implemented.  Mike will look into the issue of reciprocals in towers of rings.

**Comment by 8d1h** [comment]
Sure! Although it wasn't me who reported the bug...

**Comment by mikestillman** [comment]
@DanGrayson I'm still looking at the bug, but there are duplicates to the names of variables in the ring of td (see code in previous comment).  It seems the ideals in the flattened ring, and in the original ring are different...  Hard to tell, because of the name conflicts...!

**Comment by DanGrayson** [comment]
Can't you just transport one ideal to the other ring and compare with `==`?

**Comment by mikestillman** [comment]
Transporting is interesting, as the names of the variables are the same....

**Comment by DanGrayson** [comment]
I was sort of thinking that you could use the ring isomorphism provided by flattenRing.
