### ISSUE TITLE
update libfactory before next M2 release

### ISSUE THREAD

**Issue by jakobkroeker** [Macaulay2/M2#206]
This is a reminder ticket to update `libfactory`  before next  M2 release  (version 1.8?)
and thus ask the Singular team at some point for another `libfactory` standalone release.

Background: recently more than 21 bugs were fixed by Martin Lee and Hans Schoenemann in `libfactory`. However, I'm still observing new bugs, for example by throwing (millions of) random ideals at different primary decomposition routines in Singular and then comparing the results.

**Comment by DanGrayson** [comment]
done in commit e7be61537f58cd9dcca5233e39865b16a979ac45
