### ISSUE TITLE
maxAllowableThreads test failure

### ISSUE THREAD

**Issue by d-torrance** [Macaulay2/M2#2087]
From an [amd64 PPA build in Ubuntu 21.04](https://launchpadlibrarian.net/539693138/buildlog_ubuntu-hirsute-amd64.macaulay2_1.17.2.1+git202105200015-0ppa202105201002~ubuntu21.04.1_BUILDING.txt.gz):

```m2
testing: threads.m2
       -- If this test fails, it could indicate that the order of *.o files on the linker command line
       -- is wrong.  That affects the order of running the static initializers: in system/supervisor.cpp
       -- there is a static initializer for maxNumThreads, and in d/actors5.d there is a call to 
       -- getMaxAllowableThreads, which uses the value of maxNumThreads.  So we want the files system/*.o 
       -- to come before the files d/*.o on the linker command line.
       assert ( maxAllowableThreads != 0 )
threads.m2:46:1:(3):[4]: error: assertion failed
Command exited with non-zero status 1
```
This is from the new test that was just added in 778fc21f81818f8654b556b7a98ba8d2077b46d2.

**Comment by DanGrayson** [comment]
Was it the autoconf or the cmake build?  (For the cmake build, just advance to commit8c5e3e6143b35efa418a029df057f18c04061d57 ).

**Comment by DanGrayson** [comment]
Hmm!

I wonder if your compiler executes the initializers in right-to-left order.  To determine that, you might temporarily undo commit 6f6cbc571c08691b1b3b9108ba5b32ac74d5da20 and see if then the test succeeds.

**Comment by d-torrance** [comment]
> I wonder if your compiler executes the initializers in right-to-left order. To determine that, you might temporarily undo commit [6f6cbc5](https://github.com/Macaulay2/M2/commit/6f6cbc571c08691b1b3b9108ba5b32ac74d5da20) and see if then the test succeeds.

I can play around with this a bit more later, but it looks like my current working copy of Macaulay2, which is based on commit abef79451d02df7083dbeb458d20e63a06bc741d from Apr. 20 and would have been built using essentially the same environment as the one above (Ubuntu 21.04 amd64 PPA build), would have also had this test fail:

```m2
Macaulay2, version 1.17.2.1
with packages: ConwayPolynomials, Elimination, IntegralClosure, InverseSystems,
               LLLBases, MinimalPrimes, PrimaryDecomposition, ReesAlgebra,
               Saturation, TangentCone

i1 : maxAllowableThreads

o1 = 0
```

**Comment by DanGrayson** [comment]
That's right.  That value is a bug, which was fixed yesterday.

**Comment by d-torrance** [comment]
The test is passing in [Ubuntu 20.10](https://launchpadlibrarian.net/539700334/buildlog_ubuntu-groovy-amd64.macaulay2_1.17.2.1+git202105200015-0ppa202105201127~ubuntu20.10.1_BUILDING.txt.gz), however:

```m2
testing: testskew.m2
testing: testsubring.m2
testing: threads.m2
testing: timing-quotient.m2
testing: toExternalString.m2
```
One difference is Ubuntu went from [gcc 10.2.0 to 10.3.0](https://launchpad.net/ubuntu/+source/gcc-10) between the two releases.  Maybe that's related?  (It also failed in [Ubuntu 21.10](https://launchpadlibrarian.net/539700401/buildlog_ubuntu-impish-amd64.macaulay2_1.17.2.1+git202105200015-0ppa202105201002~ubuntu21.10.1_BUILDING.txt.gz), which also has gcc 10.3.0.)

**Comment by DanGrayson** [comment]
Depending on the order of execution of initializers is fragile.  Maybe I should initialize "maxAllowableThreads" later on, when "main" gets called.

**Comment by d-torrance** [comment]
Did some experimenting in Ubuntu chroots, but everything worked as expected.  I wonder what's different with the PPA builds?

## Ubuntu 20.10
### Before 6f6cbc5
```m2
i1 : version#"compiler"

o1 = gcc 10.2.0

i2 : version#"git description"

o2 = version-1.17.2.1-1265-3626e04e8

i3 : maxAllowableThreads 

o3 = 0
```

### After 6f6cbc5
```m2
i1 : version#"compiler"

o1 = gcc 10.2.0

i2 : version#"git description"

o2 = version-1.17.2.1-1266-6f6cbc571

i3 : maxAllowableThreads 

o3 = 12
```

## Ubuntu 21.04
### Before 6f6cbc5
```m2
i1 : version#"compiler"

o1 = gcc 10.3.0

i2 : version#"git description"

o2 = version-1.17.2.1-1265-3626e04e8

i3 : maxAllowableThreads 

o3 = 0
```

### After 6f6cbc5
```m2
i1 : version#"compiler"

o1 = gcc 10.3.0

i2 : version#"git description"

o2 = version-1.17.2.1-1266-6f6cbc571

i3 : maxAllowableThreads 

o3 = 12
```

**Comment by DanGrayson** [comment]
commit 5053e1a82cbca549ec8c4a8690d41555f339bb88 may fix it ...

**Comment by d-torrance** [comment]
> commit [5053e1a](https://github.com/Macaulay2/M2/commit/5053e1a82cbca549ec8c4a8690d41555f339bb88) may fix it ...

Ok -- I'll uncomment out the test for the next round of PPA builds and report back!

**Comment by d-torrance** [comment]
That must have done the trick!  The PPA builds that were failing before are working again.  Closing.
