### ISSUE TITLE
Symbol not found in cmake-macos-10.15-clang-11 gfan 

### ISSUE THREAD

**Issue by d-torrance** [Macaulay2/M2#2097]
Something's wrong with the copy of gfan in the `cmake-macos-10.15-clang-11` build.  From the artifacts from https://github.com/Macaulay2/M2/actions/runs/869703819:

```m2
 -- /usr/local/bin/gfan exists and is executable. running ...
dyld: Symbol not found: __ZNKSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE7compareEPKc
  Referenced from: /usr/local/bin/gfan
  Expected in: /usr/lib/libstdc++.6.dylib
 in /usr/local/bin/gfan
 -- return value: 6
```

_Originally posted by @d-torrance in https://github.com/Macaulay2/M2/issues/2093#issuecomment-846699871_

**Comment by mahrud** [comment]
It's coming from brew. Perhaps someone using macOS should test the brew bottle again.

**Comment by DanGrayson** [comment]
I'll test it.

**Comment by DanGrayson** [comment]
`gfan` runs here under mac OS X 11.3.1, but it's a mystery why, as you can see:
```sh
$ otool -L /usr/local/bin/gfan
/usr/local/bin/gfan:
	/usr/local/opt/cddlib/lib/libcddgmp.0.dylib (compatibility version 2.0.0, current version 2.2.0)
	/usr/local/opt/gmp/lib/libgmp.10.dylib (compatibility version 15.0.0, current version 15.1.0)
	/usr/local/opt/gcc/lib/gcc/10/libstdc++.6.dylib (compatibility version 7.0.0, current version 7.28.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1281.100.1)
	/usr/local/lib/gcc/10/libgcc_s.1.dylib (compatibility version 1.0.0, current version 1.0.0)
$ /usr/local/bin/gfan --version
UNKNOWN OPTION: --version.
$ nm /usr/local/bin/gfan | grep __ZNKSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE7compareEPKc
                 U __ZNKSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE7compareEPKc
$ nm /usr/local/opt/gcc/lib/gcc/10/libstdc++.6.dylib| grep __ZNKSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE7compareEPKc
00000000000ab480 T __ZNKSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE7compareEPKc
$ nm /usr/lib/libstdc++.6.dylib
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/nm: error: /usr/lib/libstdc++.6.dylib: No such file or directory.
$ nm /usr/lib/libSystem.B.dylib
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/nm: error: /usr/lib/libSystem.B.dylib: No such file or directory.
$ ls -l /usr/lib/libstdc++.*
lrwxr-xr-x  1 root  wheel  21 Jan  1  2020 /usr/lib/libstdc++.6.dylib -> libstdc++.6.0.9.dylib
lrwxr-xr-x  1 root  wheel  17 Jan  1  2020 /usr/lib/libstdc++.dylib -> libstdc++.6.dylib
```

**Comment by mahrud** [comment]
Something changed between version [20210503.2](https://github.com/Macaulay2/M2/runs/2573185832?check_suite_focus=true) and [20210510.1](https://github.com/Macaulay2/M2/runs/2581691895?check_suite_focus=true) of the virtual environment, but both are running Mac OS X 10.15.7 release 19H1030. I'll try building a new gfan bottle.

Just to reiterate:
> @DanGrayson before you make the 1.18 release, please make a release candidate tag `release-1.18-rc1` so I can test building the brew bottle with it. Otherwise if any additional changes are needed to make the brew build work after `release-1.18` is tagged, you'll need to tag them with `release-1.18.1` for the brew formula.

I can't test building a new bottle for Macaulay2 without a pre-release.

**Comment by DanGrayson** [comment]
> > @DanGrayson before you make the 1.18 release, please make a release candidate tag `release-1.18-rc1` so I can test building the brew bottle with it. Otherwise if any additional changes are needed to make the brew build work after `release-1.18` is tagged, you'll need to tag them with `release-1.18.1` for the brew formula.
> 
> I can't test building a new bottle for Macaulay2 without a pre-release.

Will do.

**Comment by d-torrance** [comment]
The new gfan bottle seems to have done the trick -- thanks, Mahrud!  Closing.
