### ISSUE TITLE
parallel_do is removed in tbb 2021

### ISSUE THREAD

**Issue by mahrud** [Macaulay2/M2#2105]
I can't find any mention of it in change logs or release notes, but the 2021 release simply doesn't contain `tbb/parallel_do.h` or any documentation about it. 

https://github.com/Macaulay2/M2/blob/104c35429dbc9d0a9defe0443f82caeaaf440679/M2/Macaulay2/e/NCAlgebras/NCF4.hpp#L6

cc: @mikestillman @moorewf

**Comment by mahrud** [comment]
This is likely a blocker for the brew builds. I opened https://github.com/oneapi-src/oneTBB/issues/416 to ask about this, but if you can use a different API, that would be much easier.

**Comment by mahrud** [comment]
TBB 2021 has gone through a complete revamp. In particular:
> The code base was revamped to improve the usability and simplify the library, see [TBB Revamp: Background, Changes, and Modernization](https://software.intel.com/content/www/us/en/develop/articles/tbb-revamp.html). This version of the library is not backward compatible with any of the previous releases.

The replacement for `parallel_do` is `parallel_for_each`.

**Comment by DanGrayson** [comment]
I can no longer build on the Mac, too.

```
make -C e all 
make[3]: Entering directory '/Users/dan/src/M2/M2.git/M2/BUILD/dan/builds.tmp/gallium-development/Macaulay2/e'
MKDEP interface/groebner.cpp
In file included from /Users/dan/src/M2/M2.git/M2/Macaulay2/e/interface/groebner.cpp:24:
/Users/dan/src/M2/M2.git/M2/Macaulay2/e/NCAlgebras/NCF4.hpp:6:10: fatal error: 
      'tbb/parallel_do.h' file not found
#include <tbb/parallel_do.h>                  // for parallel_do_feeder
         ^~~~~~~~~~~~~~~~~~~
1 error generated.
Makefile:89: interface/groebner.dep: No such file or directory
```

**Comment by DanGrayson** [comment]
```
$ brew info tbb
brew info tbb
tbb: stable 2021.2.0 (bottled)
Rich and complete approach to parallelism in C++
https://github.com/oneapi-src/oneTBB
/usr/local/Cellar/tbb/2020_U3_1 (144 files, 3MB)
  Poured from bottle on 2021-02-23 at 14:16:35
/usr/local/Cellar/tbb/2021.2.0 (174 files, 1.8MB) *
  Poured from bottle on 2021-05-24 at 09:45:00
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/tbb.rb
License: Apache-2.0
==> Dependencies
Build: cmake ✔, swig ✘
Required: python@3.9 ✔
==> Analytics
install: 22,532 (30 days), 51,999 (90 days), 255,175 (365 days)
install-on-request: 3,889 (30 days), 8,418 (90 days), 44,906 (365 days)
build-error: 0 (30 days)

```

**Comment by moorewf** [comment]
Currently working on updating this.  Should have a pull request ready soon.

**Comment by mahrud** [comment]
@DanGrayson try doing `brew install macaulay2/tap/tbb@2020_u3`, then adjust CFLAGS and LDFLAGS appropriately.

**Comment by DanGrayson** [comment]
> Currently working on updating this. Should have a pull request ready soon.

Frank, will it still work with older versions of tbb?

**Comment by mikestillman** [comment]
It seems like we will need to support at least the libraries prior to 2021.2.0 (which appears to be a major breaking non-backword compatible update), unless we distribute the new one with M2? (And we want to use the installed versions on ubuntu if possible, which is probably 2020_U3?  Or even older, for 18.04?

@DanGrayson , @d-torrance what is our best way forward with this?  We certainly want to update our code (and mathicgb) to use the most recent tbb, expecting it will contain useful improvements.  Should configure.ac, cmake install give a #define for which TBB library is installed?

For 1.18, should we insist on builds using `tbb@2020_u3` (or older, but how old)?  We must package the library in any case, as we do with the rest of the dynamic libraries, right?

**Comment by mikestillman** [comment]
Actually, the changes in the revamped file that @mahrud linked to make these sound like good changes.  But I guess we will need to support this and the older version at the same time for a while.

> TBB 2021 has gone through a complete revamp. In particular:
> 
> > The code base was revamped to improve the usability and simplify the library, see [TBB Revamp: Background, Changes, and Modernization](https://software.intel.com/content/www/us/en/develop/articles/tbb-revamp.html). This version of the library is not backward compatible with any of the previous releases.
> 
> The replacement for `parallel_do` is `parallel_for_each`.

**Comment by d-torrance** [comment]
> @DanGrayson , @d-torrance what is our best way forward with this? We certainly want to update our code (and mathicgb) to use the most recent tbb, expecting it will contain useful improvements. Should configure.ac, cmake install give a #define for which TBB library is installed?

This would be my preference, yes.  Support both tbb 2020 and 2021 for the next few years (at least until Debian 11 and Ubuntu 20.04 reach EOL), detecting which one to use during configure.

**Comment by DanGrayson** [comment]
> @DanGrayson try doing `brew install macaulay2/tap/tbb@2020_u3`, then adjust CFLAGS and LDFLAGS appropriately.

Thanks.  I did `brew install tbb@2020` and that worked, too.

**Comment by DanGrayson** [comment]
> > @DanGrayson , @d-torrance what is our best way forward with this? We certainly want to update our code (and mathicgb) to use the most recent tbb, expecting it will contain useful improvements. Should configure.ac, cmake install give a #define for which TBB library is installed?
> 
> This would be my preference, yes. Support both tbb 2020 and 2021 for the next few years (at least until Debian 11 and Ubuntu 20.04 reach EOL), detecting which one to use during configure.

That seems simplest.  Then we don't to add code to the build systems to build the version of tbb we use when it's not found.

Meanwhile, I think we can release Macaulay2 just for the most up-to-date Ubuntu and Debian systems.

**Comment by mikestillman** [comment]
I believe this was fixed, in our tbb pull request recently.  @d-torrance @mahrud @DanGrayson Do you agree?

**Comment by d-torrance** [comment]
Yes, this was fixed.
