### ISSUE TITLE
basis needs to check degreeLength

### ISSUE THREAD

**Issue by mikestillman** [Macaulay2/M2#2117]
If R is a polynomial ring with a multi-grading, and d is an integer, or list with an incorrect length, `basis(d, R)` still gives an answer of some sort.  It should give an error message instead:

```
i1 : S = ZZ/101[x,y,z,DegreeRank => 3];
i2 : basis(3, S) -- unexpected, should be an error...

o2 = | x3 |

             1       1
o2 : Matrix S  <--- S

i3 : basis({3,4}, S) -- even more unexpected, should be an error...

o3 = | x3y4 |

             1       1
o3 : Matrix S  <--- S

i4 : basis({3,3,3}, S) -- correct

o4 = | x3y3z3 |

             1       1
o4 : Matrix S  <--- S
```

**Comment by DanGrayson** [comment]
I think our idea long ago was that trailing zeroes could be omitted.

**Comment by mahrud** [comment]
Here `basis(3, S)` is treated as `basis({3}, S)`, which is then treated as a partial multidegree.

The remaining degrees aren't treated as zero, but as "whatever". This is explained in the documentation of [basis](https://faculty.math.illinois.edu/Macaulay2/doc/Macaulay2/share/doc/Macaulay2/Macaulay2Doc/html/_basis.html):

> A partial multidegree can be given. The given columns generate (form a basis in this case) the degree `{2,*}` part of R, over the subring QQ[d] generated by the variables which have degree `{0,*}`.

**Comment by mikestillman** [comment]
Ah, yes, I recall now!  Thanks! (tagging @eisenbud as we were looking at this together).

**Comment by mahrud** [comment]
By the way, @jkyang92 ran into an issue related to this here: https://github.com/Macaulay2/M2/pull/2056#issuecomment-847475505

Maybe having an optional argument `Partial => true` to allow this behavior, and otherwise give an error would be better?

**Comment by DanGrayson** [comment]
Yes, that sounds more correct than what I said, but then why doesn't that work in this case?

```m2

i4 : R = QQ[x,y,Degrees=>{{1,0},{0,1}}]/(x^6,y^6);

i5 : basis({3},R)

o5 = | x3 |

             1       1
o5 : Matrix R  <--- R
```

**Comment by mahrud** [comment]
> Yes, that sounds more correct than what I said, but then why doesn't that work in this case?

This output seems correct to me, but I think this is wrong:
```m2
i23 : R = QQ[x,y,Degrees=>{{1,0},{0,1}}]/(x^6,y^6);

i24 : basis(3, R, SourceRing => QQ)

o24 = | x3 |

              1        1
o24 : Matrix R  <--- QQ
```
And that's because `SourceRing` is kind of broken, and I believe should be removed (I have a suggestion for what should replace it). I've mentioned this in tests I've added for #2113:
https://github.com/Macaulay2/M2/blob/904d44d81e17da21673c4b3b41fb83f83ed0459a/M2/Macaulay2/tests/normal/basis3.m2#L63-L68

**Comment by jkyang92** [comment]
> Yes, that sounds more correct than what I said, but then why doesn't that work in this case?
> 
> ```m2
> i4 : R = QQ[x,y,Degrees=>{{1,0},{0,1}}]/(x^6,y^6);
> 
> i5 : basis({3},R)
> 
> o5 = | x3 |
> 
>              1       1
> o5 : Matrix R  <--- R
> ```

This gives this answer because basis currently just completely ignores variables with degree 0, And z is degree zero in the first component. This was what I was trying to fix as part of the other pull request.

**Comment by DanGrayson** [comment]
> > Yes, that sounds more correct than what I said, but then why doesn't that work in this case?
> > ```m2
> > i4 : R = QQ[x,y,Degrees=>{{1,0},{0,1}}]/(x^6,y^6);
> > 
> > i5 : basis({3},R)
> > 
> > o5 = | x3 |
> > 
> >              1       1
> > o5 : Matrix R  <--- R
> > ```
> 
> This gives this answer because basis currently just completely ignores variables with degree 0, And z is degree zero in the first component. This was what I was trying to fix as part of the other pull request.

There's no `z` here.

Maybe the heft vector has to be supported on the part of the degree vector that is actually given, for the thing to get the right answer.

It seems there's a bug here somewhere, so reopening.

**Comment by jkyang92** [comment]
> There's no `z` here.

Sorry about the typo, I meant y.

> 
> Maybe the heft vector has to be supported on the part of the degree vector that is actually given, for the thing to get the right answer.
> 
> It seems there's a bug here somewhere, so reopening.

I can get the right answer for the example given above case using my code. I'll push it somewhere in a bit. But it breaks a test in Core that expects a different behavior for `basis({3},QQ[x,y,Degrees=>{{1,0},{0,1}}])` See https://github.com/Macaulay2/M2/pull/2056#issuecomment-847475505

**Comment by mahrud** [comment]
@DanGrayson what do you expect the output to be? The output you see is compatible with the partial multidegree input. It's limiting to a subring `QQ[x, Degrees => {{1,0}}]/(x^6)` as the documentation would imply. It looks correct to me.

@jkyang92 I responded in that thread as well. I don't see any inconsistency here. Am I missing something?

**Comment by jkyang92** [comment]
@DanGrayson Here's the relevant commit https://github.com/Macaulay2/M2/pull/2056/commits/ca27788e19b9797005c6d043dbf19f853e6d8e41. It's worth noting that the change I made was to _relax_ the constraints on heft in the engine and then have M2 actually pass all of the variables to the engine.

For some reason it's failing to build with some factory linking error, but I'm not certain where that's from.

**Comment by DanGrayson** [comment]
@mahrud:

If `basis({3},R)` means `basis({3,*},R)`, then instead of this answer:
```m2
i15 : R = QQ[x,y,Degrees=>{{1,0},{0,1}}]/(x^6,y^6);

i16 : basis({3},R)

o16 = | x3 |

              1       1
o16 : Matrix R  <--- R
```

, I would expect `| x3 x3y x3y2 x3y3 x3y4 x3y5 |`, because those are the monomials with 3 as first component.

**Comment by mahrud** [comment]
@DanGrayson again, this is explained in the documentation of [basis](https://faculty.math.illinois.edu/Macaulay2/doc/Macaulay2/share/doc/Macaulay2/Macaulay2Doc/html/_basis.html):
> A partial multidegree can be given. The given columns generate (form a basis in this case) the degree `{2,*}` part of R, over the subring QQ[d] generated by the variables which have degree `{0,*}`.

Note the second sentence. In the case of your example, `| x3 |` is over the subring `QQ[y, Degree => {0,1}]/(y^6)`, which is correct.

**Comment by DanGrayson** [comment]
> @DanGrayson again, this is explained in the documentation of [basis](https://faculty.math.illinois.edu/Macaulay2/doc/Macaulay2/share/doc/Macaulay2/Macaulay2Doc/html/_basis.html):
> 
> > A partial multidegree can be given. The given columns generate (form a basis in this case) the degree `{2,*}` part of R, over the subring QQ[d] generated by the variables which have degree `{0,*}`.
> 
> Note the end of the second sentence. In the case of your example, `| x3 |` is correct because it generates what you want over the subring `QQ[y, Degree => {0,1}]/(y^6)`.
> 


That clarifies that, thanks.

**Comment by mahrud** [comment]
Should this issue be closed, then? Or is there anything not covered by existing issues that needs to be fixed?
