### ISSUE TITLE
Minimum autoconf version?

### ISSUE THREAD

**Issue by d-torrance** [Macaulay2/M2#2122]
Currently, it's set at 2.71:
https://github.com/Macaulay2/M2/blob/104c35429dbc9d0a9defe0443f82caeaaf440679/M2/Makefile#L19-L24

However, autoconf 2.71 is still relatively new (Jan 2021), and isn't available in any Debian-based distributions yet (except Debian experimental -- https://tracker.debian.org/pkg/autoconf).

I have no problems building Macaulay2 with autoconf 2.69 (which is what's available on my system -- Ubuntu 21.04) after editing the Makefile to allow it.

Is there a reason the minimum version is set to what it's at?  I almost never build any of the included libraries or programs, so maybe one of them needs it?

**Comment by DanGrayson** [comment]
Apparently I bumped it on March 7, without explaining why.  Why don't we put it back to 2.68 and wait until something goes wrong?  (I must have had some reason.)

**Comment by d-torrance** [comment]
Closing since #2125 was merged
