### ISSUE TITLE
proposal: add more labels, e.g a 'bug' label

### ISSUE THREAD

**Issue by jakobkroeker** [Macaulay2/M2#213]
see for some ideas 
https://github.com/jakobkroeker/test_singular/labels

**Comment by DanGrayson** [comment]
Okay, I've added "bug in our code".  I wouldn't want to have as many as Singular has - it's too many.

**Comment by jakobkroeker** [comment]
>  I wouldn't want to have as many as Singular has - it's too many.

I just referenced them as a pool for ideas.

They are not Singulars, it is my personal Singular issue tracker *g

https://github.com/jakobkroeker/test_singular/issues

**Comment by DanGrayson** [comment]
Oh!  Very energetic.

**Comment by jakobkroeker** [comment]
> Oh! Very energetic.

Not really; many of the issues on the list are get fixed by the Singular team.
I track them here, since I can't do that fully in their bug tracker 
Their bug tracker does now not allow comments from others than project members with a login  account in Kaiserslautern (initial posts are allowed)

Also sometimes I have a different opinion on the term  `'fixed'`.

**Comment by DanGrayson** [comment]
Why would members of the singular group even look at your personal list of
issues?

**Comment by jakobkroeker** [comment]
> Why would members of the singular group even look at your personal list of issues?

They don't. Either there is a corresponding upstream report 
e.g 

http://www.singular.uni-kl.de:8002/trac/ticket/686#ticket
which I separately track in 
https://github.com/jakobkroeker/test_singular/issues/132

or I email to developers directly.

Also I use my local issue list to prepare a proper upstream report, 
e.g. I try to find a simple example first.
