### ISSUE TITLE
MSolve for multivariate polynomial system solving

### ISSUE THREAD

**Issue by mahrud** [Macaulay2/M2#2132]
Mike mentioned [MSolve](https://msolve.lip6.fr/) yesterday, so I thought I'd share a few benchmark slides that I had seen in an ICERM talk in February ([video here](https://icerm.brown.edu/video_archive/?play=2455)).

![2021-02-18-09:39:43](https://user-images.githubusercontent.com/3147718/120831669-67bf8a80-c525-11eb-9bcc-4f73bee1598c.png)

![2021-02-18-09:47:49](https://user-images.githubusercontent.com/3147718/120831684-6aba7b00-c525-11eb-88a8-a2e03abe14ac.png)

We switched from PARI to MPSolve for univariate factorizations not too long ago, but MSolve seems to cover the functionality of MPSolve and also add multivariate factorization. In particular, it also depends on Flint.

**Comment by d-torrance** [comment]
It's not in Debian yet (and according to its [website](https://msolve.lip6.fr/), it looks like it only became open source in April!), but it looks like it would be pretty easy to package (standard autotools build and the only dependencies look to be gmp, mpfr, and flint).  I'll work on getting it packaged soon.  Even if we don't end up using it, it would be nice to have it in Debian/Ubuntu!

**Comment by mahrud** [comment]
Closed in #3366.
