### ISSUE TITLE
gfan version 0.5 too low

### ISSUE THREAD

**Issue by AviSteiner** [Macaulay2/M2#2144]
I just updated to M2 version 1.18 a couple hours ago. I got the following error when I tried to use gfan on an ideal: `stdio:3:1:(3): error: found gfan, but version (0.5) is too low`. Here's the code I used:

```
i1 : needsPackage "gfanInterface"

o1 = gfanInterface

o1 : Package

i2 : R = QQ[x]

o2 = R

o2 : PolynomialRing

i3 : gfan ideal x
stdio:3:1:(3): error: found gfan, but version (0.5) is too low
```

**Comment by d-torrance** [comment]
Presumably Macaulay2 could only find gfan 0.5 on your system.  The minimum version of gfan was bumped to 0.6 in Macaulay2 1.18 because of #1962.  Upgrading gfan should fix this.

One way to see how exactly Macaulay2 is finding gfan is to run `findProgram` (which is what the `gfanInterface` package uses internally) with the `Verbose` option:

```m2
i1 : findProgram("gfan", "gfan _version --help", Verbose => true)
 -- /usr/libexec/Macaulay2/bin/gfan does not exist
 -- /home/profzoom/.local/bin/gfan does not exist
 -- /usr/local/sbin/gfan does not exist
 -- /usr/local/bin/gfan does not exist
 -- /usr/sbin/gfan does not exist
 -- /usr/bin/gfan exists and is executable
 -- running "/usr/bin/gfan _version --help":
This program writes out version information of the Gfan installation.
 -- return value: 0

o1 = gfan

o1 : Program
```

**Comment by AviSteiner** [comment]
> Presumably Macaulay2 could only find gfan 0.5 on your system. The minimum version of gfan was bumped to 0.6 in Macaulay2 1.18 because of #1962. Upgrading gfan should fix this.
> 

How do I update gfan? I was under the impression that it updates automatically with Macaulay2.

**Comment by mahrud** [comment]
> How do I update gfan? I was under the impression that it updates automatically with Macaulay2.

It should. Maybe you had a separate installation that should be removed so the one by M2 is found.

**Comment by d-torrance** [comment]
* What system are you on?
* How did you install Macaulay2?
* What is the output of `findProgram("gfan", "gfan _version --help", Verbose => true)`?

**Comment by mahrud** [comment]
I'm guessing this is fixed, Avi? If not feel free to reopen the issue.
