### ISSUE TITLE
genmat.m2 not found

### ISSUE THREAD

**Issue by d-torrance** [Macaulay2/M2#2155]
When starting Macaulay2 (PPA package built from the `development` branch), I get:

```m2
profzoom@peg-amy:~$ M2
Macaulay2, version 1.18.0.1
/usr/share/Macaulay2/Core/debugging.m2:23:6:(1):[14]: error: file not found on path: "genmat.m2"
/usr/share/Macaulay2/Core/debugging.m2:23:6:(1):[14]: --entering debugger (type help to see debugger commands)
/usr/share/Macaulay2/Core/debugging.m2:23:6-23:27: --source code:
     olderror processArgs args)

i1 : 
```

`genmat.m2` doesn't appear in `M2/Macaulay2/m2/loadsequence` (since 183475a9bd10f239bdc7de519619af4c293fe2ed), so it isn't installed, at least by the autotools build.

**Comment by mahrud** [comment]
Strange, I must have made a mistake when rebasing that PR. But why are only the files in `loadsequence` being installed? Why not everything matching `m2/*.m2`?

**Comment by mahrud** [comment]
Here are the only `.m2` files in the `m2` directory that aren't typically loaded:
- macaulay1.m2: contains only 2 functions
- overview.m2: seems to contain a bunch of documentation nodes that are not loaded
- sagbi.m2: is this in working condition?
- workingnotes.m2

Probably doesn't hurt to install them anyway, though eventually they should be moved or finished.

**Comment by DanGrayson** [comment]
Another reason the file `loadsequence` should be complete, is that the `TAGS` file is constructed from it.  Moreover, the TAGS file should mention the *.m2 files in "logical" order, so when running `M-x tags-search` one finds definitions before uses.
