### ISSUE TITLE
hashcodes of mutable objects

### ISSUE THREAD

**Issue by DanGrayson** [Macaulay2/M2#2157]
The problem is that the hash codes of mutable objects are just serial numbers, and the serial number gets incremented by 1 each time one is created.  But once you make a little over 2 billion of them, the hashcode overflows into the sign bit of the 32 bit integer and the hashcodes start coming out negative.  This interferes with the "youngest" routine, which was written under the assumption that the hashcodes are all positive, and things stop working.

Thanks to Orin Gotchey for the report.

**Comment by mahrud** [comment]
This bug was pointed out before in https://github.com/Macaulay2/M2/issues/1773#issuecomment-779381727

**Comment by DanGrayson** [comment]
> This bug was pointed out before in [#1773 (comment)](https://github.com/Macaulay2/M2/issues/1773#issuecomment-779381727)

That's not the same bug.

**Comment by DanGrayson** [comment]
fixed in https://github.com/Macaulay2/M2/commit/a9199f466dafb7c4f830713ae3ff6a9bb350bc26
