### ISSUE TITLE
Unable to find 4ti2 in brewed M2 on M1 

### ISSUE THREAD

**Issue by eisenbud** [Macaulay2/M2#2161]
With Mahrud's fix (reinstalling libomp) I could "brew" an M2, but although brew says that 4ti2 is alive and well, M2 can't find it:
```m2
findProgram("4ti2", "markov -h", Verbose => true)
 -- /Users/de/gitRepos/M2/M2/BUILD/build/usr-dist/arm64-Darwin-macOS-11.4/libexec/Macaulay2/bin/markov does not exist
 -- /Users/de/gitRepos/M2/M2/BUILD/build/usr-dist/arm64-Darwin-macOS-11.4/bin/markov does not exist
 -- /usr/bin/markov does not exist
 -- /bin/markov does not exist
 -- /usr/sbin/markov does not exist
 -- /sbin/markov does not exist
 -- /Applications/Emacs.app/Contents/MacOS/bin-arm64-11_2/markov does not exist
 -- /Applications/Emacs.app/Contents/MacOS/libexec-arm64-11_2/markov does not exist
stdio:2:1:(3): error: could not find 4ti2
```
@d-torrance

**Comment by mahrud** [comment]
@d-torrance this doesn't seem to be related to brew. The terminal can find both M2 and markov (the binaries are in the same directory), but somehow M2 can't find 4ti2.

**Comment by d-torrance** [comment]
Am I remembering correctly that brew installs everything under /usr/local/bin? That's not showing up as one of the attempted paths, so it must be missing from the PATH environment variable, which seems odd, especially if the shell is finding it.

A quick hacky fix would be to set `programPaths#"4ti2"` to the correct directory.

**Comment by mahrud** [comment]
I suspect is has something to do with zsh. A simple fix seems to be also checking the directory where the M2-binary is.
