### ISSUE TITLE
crash after substitution

### ISSUE THREAD

**Issue by DanGrayson** [Macaulay2/M2#2178]
Okay, I reproduced the problem, and it appears that the engine code there doesn't anticipate the possibility of an error occurring in that bit of code.  Mike can easily test the error flag and insert return statements, so I'm assigning this to him.

_Originally posted by @DanGrayson in https://github.com/Macaulay2/M2/discussions/2177#discussioncomment-963119_

**Comment by signedout** [comment]
Hi again, wondering if there are some news concerning this bug? I would be very grateful if it were fixed. Thank you and happy new year!

**Comment by mikestillman** [comment]
Fixed in PR #2480.
