### ISSUE TITLE
M2 --no-readline outputs in the wrong order

### ISSUE THREAD

**Issue by pzinn** [Macaulay2/M2#2210]
This is such a basic problem, and I feel that it needs addressing. 
this is running M2 inside emacs: try running
```
A=QQ[x]
B=QQ[y]
```
by say selecting these two lines and pressing F11 inside a m2 file;
this is what I get (and I'm assuming everyone else)
```
i1 : A=QQ[x]
B=QQ[y]


o1 = A

o1 : PolynomialRing

i2 : 
o2 = B

o2 : PolynomialRing
```
notice how `B=QQ[y]`, instead of coming after i2:, as it should, appears on the second line. 
This may seem like a minor nuisance, but it's actually problematic (for example, it breaks my web interface -- I have to use readline with it, which itself is the source of tons of headaches and creates more output bugs).
I've known this problem for years, of course, but as M2 matures I think it needs to rethink once more its output engine.

**Comment by DanGrayson** [comment]
I think it's emacs that puts B=QQ[y] on the second line, not M2.  M2 is not echoing its input, after all.  If we could get emacs to send M2's input directly to M2 without putting it in the buffer, then we could run `cat|M2` instead of `M2` to get `M2` to echo its input at the right moment.  (I thought `--no-tty` would do that, but apparently not ... )

**Comment by DanGrayson** [comment]
M2 detecting whether it's input is a tty is why we can run examples and get good looking output:
```M2
$ (echo x=1 ; echo y=2; exit) | M2 
Macaulay2, version 1.18
with packages: ConwayPolynomials, Elimination, IntegralClosure, InverseSystems, LLLBases, MinimalPrimes, PrimaryDecomposition, ReesAlgebra, Saturation, TangentCone

i1 : x=1

o1 = 1

i2 : y=2

o2 = 2

i3 : 
```

**Comment by pzinn** [comment]
interesting. can you elaborate on "M2 detecting whether its input is a tty" ? Clearly there's something I don't understand here, because I agree with you that the output of running M2 on the command line is just fine, readline or not, and that's confusing to me.

**Comment by DanGrayson** [comment]
Somewhere in the code we run the function "isatty" in the stdin file descriptor.  If it's a tty, then we depend on the tty to echo the input to the output; if not, we do it ourselves, as in the example `(echo x=1 ; echo y=2; exit) | M2 ` above.  Objects of type "file" have a Boolean-valued field called "echo", and that gets set early on, to determine whether to do the echoing.  Probably that's getting set too early, before the `--no-tty` argument is processed, as I can't get `--no-tty` to provoke echoing when M2 is running in a tty.

**Comment by pzinn** [comment]
still experimenting with this. something slightly unpleasant:
```
(echo "I=ideal 0; x=(\n 1)"; exit) | M2 
Macaulay2, version 1.18.0.1
with packages: ConwayPolynomials, Elimination, IntegralClosure, InverseSystems, LLLBases, MinimalPrimes, PrimaryDecomposition,
               ReesAlgebra, Saturation, TangentCone

i1 : I=ideal 0; x=(

o1 : Ideal of ZZ
      1)

o2 = 1

```

**Comment by DanGrayson** [comment]
I suppose one could fix that, but people probably never type things like that.

**Comment by pzinn** [comment]
I agree the AfterPrint issue above is minor.
my current findings: I could not find any noticeable effect of  `stdIO.inisatty` or  `stdIO.outisatty`. `stdIO.echo` however seems to be the key: when turned on (and `stdIO.readline` is off) the input is printed where it should, except now I get a double echo from the terminal, which can be turned off with `stty -echo`.

**Comment by pzinn** [comment]
a strange bug: with echo on some (two) characters get eaten up after a syntax error
```
stty -echo; M2 --echo
i2 : (
     a
     b
stdio:4:1:(3): error: missing semicolon or comma on previous line?

i2 : 34 -- I typed "1234"

o2 = 1234
```

**Comment by DanGrayson** [comment]
`--echo` is not a valid M2 command line option.

**Comment by pzinn** [comment]
ah, yes. I added this to stdio.d to test the effect of echo:
```
+         if arg === "--echo" then (
+              stdIO.echo = true;
+              stdIO.readline = false;
+         )
+         else
```
if there's a simpler way to achieve the same result, let me know.
alternatively, one can do it your way:
```
echo "(a\nb\n1234\n" | M2
```
though the result is slightly different: all subsequent output is ignored. still investigating.

**Comment by pzinn** [comment]
aha! found the issue. the combination of `stdIO.echo = true` and `stdIO.inisatty = true` works almost perfectly, except for this:
https://github.com/Macaulay2/M2/blob/3c3e3f7ddbc1a0ff20bd6723e41251557dea2936/M2/Macaulay2/d/parser.d#L216
when a syntax error occurs, flushinput is called:
https://github.com/Macaulay2/M2/blob/3c3e3f7ddbc1a0ff20bd6723e41251557dea2936/M2/Macaulay2/d/stdio.d#L363-L367
except the latter forgets to reset `o.echoindex` hence the minor bug I experienced before. (and which does not occur doing `echo "..." | M2` because it's not a tty -- intead it just hangs which is not great but not my concern).
this is easily fixed.

**Comment by DanGrayson** [comment]
Great!

**Comment by pzinn** [comment]
It is indeed pretty great. Let me summarize in case anybody else is interested.
In order to make sure the output of M2 is in the right order (in particular, input being spit it out at the right time, after its prompt), the best method is to *turn off* the "external" echo (coming from the terminal, or emacs) and *turn on* M2's internal echo via stdIO.echo = true. In terminal mode (stdIO.tty = true), this almost works except for a tiny bug reported above which I intend to fix soon.
The immediate application for me is selfish, it's that I can finally get Macauly2Web to have proper output in the right order, something which I've wanted to do for years.
The same could in principle be done in emacs, though I'm afraid my lisp is a bit rusty...

**Comment by pzinn** [comment]
I'm going to close this thread. All the information is in here if anyone wants to play the same trick in emacs as I did in web app mode, in order to resolve the original issue. But I don't have the time/energy to do it myself and I suspect it's not very high on anybody's priority list.
