### ISSUE TITLE
changes 1.8

### ISSUE THREAD

**Issue by DanGrayson** [Macaulay2/M2#222]
Document changes 1.8 in M2/Macaulay2/packages/Macaulay2Doc/changes.m2 before
the new release.

**Comment by DanGrayson** [comment]
Okay, I've added all the changes I can think of, so I'm assigning it to Mike, in case he has any changes to report.

**Comment by DanGrayson** [comment]
See commit 45774abcb3f843042048b92f3dcfcc0d80b83e96 for my 1.8 changes.

**Comment by mikestillman** [comment]
I added some to changes.m2.
