### ISSUE TITLE
`runProgram`, when a program is killed, returns no value

### ISSUE THREAD

**Issue by DanGrayson** [Macaulay2/M2#2228]
`runProgram`, when a program is killed, returns no value.  

In this demo, `cat` waits for input, so I kill it with `killall -9 cat`.

```m2
Macaulay2, version 1.18.0.1

i1 : cat = findProgram ("cat","cat </dev/null")

o1 = cat

o1 : Program

i2 : runProgram (cat, "")
stdio:2:1:(3): error: cat returned an error
running: /usr/bin/cat 
Killed
```

**Comment by d-torrance** [comment]
That's the current intended behavior of `runProgram` -- it raises an error if the program being run has a nonzero return value unless the `RaiseError` option is `false`:

```m2
i17 : runProgram(cat, "", RaiseError => false)

o17 = 15

o17 : ProgramRun
```

**Comment by DanGrayson** [comment]
Ah, okay, thank you.
