### ISSUE TITLE
libgivaro update causes bugs in my Ubuntu 20.04 system

### ISSUE THREAD

**Issue by completementgaga** [Macaulay2/M2#2235]
Dear all,
On my Ubuntu 20.04 some packages were updated recently, due to my installing of your ppa for M2.
This is to report that the update to the ppa's versions 4-1-2 of libgivaro9 and libgivaro-dev caused crashes in my sagemath software, systematic crash on startup. This was solved by downgrading both packages to 4-1-1 and reinstalling sage.

All the best,
Gaël Cousin.

**Comment by d-torrance** [comment]
This would probably be good to report to the givaro developers (https://github.com/linbox-team/givaro).

The givaro package in the Macaulay2 PPA is based on givaro's current release candidate and not a stable release.  However, the CMake build of Macaulay2 fails when built using givaro 4.1.1 (see #1227), hence the update in the PPA (which is used to pull in dependencies for Github builds).

**Comment by d-torrance** [comment]
Is this the error?

```python
>>> from sage import *
/usr/lib/python3/dist-packages/apport/report.py:13: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import fnmatch, glob, traceback, errno, sys, atexit, locale, imp, stat
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/sage/all.py", line 138, in <module>
    from sage.rings.all      import *
  File "/usr/lib/python3/dist-packages/sage/rings/all.py", line 83, in <module>
    from .polynomial.all import *
  File "/usr/lib/python3/dist-packages/sage/rings/polynomial/all.py", line 42, in <module>
    from sage.rings.polynomial.laurent_polynomial_ring import LaurentPolynomialRing
  File "/usr/lib/python3/dist-packages/sage/rings/polynomial/laurent_polynomial_ring.py", line 51, in <module>
    from sage.rings.polynomial.laurent_polynomial import LaurentPolynomial_mpair, LaurentPolynomial_univariate
  File "sage/rings/polynomial/laurent_polynomial.pyx", line 1, in init sage.rings.polynomial.laurent_polynomial (build/cythonized/sage/rings/polynomial/laurent_polynomial.c:40756)
  File "/usr/lib/python3/dist-packages/sage/matrix/__init__.py", line 2, in <module>
    import sage.matrix.args
  File "sage/matrix/args.pyx", line 23, in init sage.matrix.args (build/cythonized/sage/matrix/args.c:21561)
  File "/usr/lib/python3/dist-packages/sage/matrix/matrix_space.py", line 44, in <module>
    from . import matrix_modn_sparse
ImportError: /usr/lib/python3/dist-packages/sage/matrix/matrix_modn_sparse.cpython-39-x86_64-linux-gnu.so: undefined symbol: _ZNK6Givaro7IntegercvNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEB5cxx11Ev
```
So apparently givaro has removed this symbol (`c++filt _ZNK6Givaro7IntegercvNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEB5cxx11Ev` yields `Givaro::Integer::operator std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >[abi:cxx11]() const`) in the release candidate.  Hopefully they'll bump the soname version prior to the next stable release.

I can patch the PPA package to do this in the meantime.  In particular, there would be two coexisting packages, `libgivaro9` from the official 20.04 repository for use with Sage, and `libgivaro10` from the PPA for use with Macaulay2.

**Comment by completementgaga** [comment]
@d-torrance 
I think so. I don't know of a log file I could consult to confirm this. If you know one, I can check.

Sure there was something to  do with /usr/lib/python3/dist-packages/sage/matrix

**Comment by d-torrance** [comment]
It turns out that the givaro developers indeed bumped the soname version to 10 with the release candidate, so this is definitely a PPA bug and not an issue on their end!  I should have it fixed in a few days (need to update the givaro, fflas-ffpack, and macaulay2 packages in succession).

**Comment by completementgaga** [comment]
I am not sure I understand very well the situation. However, I can say that M2 is still working on my machine, with the downgraded version of libgivaro. Thanks for your efforts, anyway.

**Comment by d-torrance** [comment]
Oh, that's good!  It would be not to need to go through this process of downgrading, though.
