### ISSUE TITLE
Groebner basis computation

### ISSUE THREAD

**Issue by mccull29** [Macaulay2/M2#2246]
It seems to me that the following computation is a problem; namely, that the lead term ideal and the Groebner basis should have the same number of elements.

R = ZZ/32003[x_6,x_5,x_4,x_3,x_2,x_1,x_0]
L1 = ideal(x_0,x_3,x_4,x_5,x_6)
L2 = ideal(x_0,x_1,x_4,x_5,x_2+52*x_3+x_6)
L3 = ideal(x_0,x_1,x_2,x_6,x_3+107*x_4+x_5)
L4 = ideal(x_1,x_2,x_3,x_5,x_0+x_4+x_6)
L5 = ideal(x_2,x_3,x_4,x_6,x_0+x_1+x_5)
J = intersect(L1,L2,L3,L4,L5)
transpose mingens gb J
transpose mingens ideal flatten entries leadTerm J   -- These 2 should have the same number of entries but they don't.

Thanks for any help.

- Jason

**Comment by moorewf** [comment]
The `mingens' in mingens gb J is throwing away the non-minimal generators of gb J, which are the last three on the list of lead terms that are missing.  I think this is working as intended.

**Comment by mccull29** [comment]
Oh!  I thought I had typed gens.  My mistake.  Thank you!
