### ISSUE TITLE
AssociativeAlgebras equality fail

### ISSUE THREAD

**Issue by pzinn** [Macaulay2/M2#2248]
Is this too early to submit bugs for `AssociativeAlgebras`? I have found quite a few. Here's one that's been bothering me. I tried to build the group algebra of the symmetric group:
```
i1 : needsPackage "AssociativeAlgebras";

i2 : n=7;

i3 : S=QQ<|t_1..t_(n-1)|>;

i4 : I=ideal (apply(1..n-1,i->t_i^2-1)
    |apply(1..n-2,i->(t_i*t_(i+1)*t_i-t_(i+1)*t_i*t_(i+1)))
    |apply(1..n-3,i->apply(i+2..n-1,j->t_i*t_j-t_j*t_i)));
          
o4 : Ideal of S

i5 : H=S/I
Warning:  Parallel F4 Algorithm not available over current coefficient ring.
Converting to Naive algorithm.

o5 = H

o5 : FreeAlgebraQuotient

i7 : t_2*t_1*t_2*t_3*t_4*t_5*t_6==t_1*t_2*t_3*t_4*t_5*t_6*t_1

o7 = false
```
as you can see `o7` should be true. I don't really understand how that noncommutative stuff works, but one way or another it shouldn't produce a mathematically wrong statement.

**Comment by mikestillman** [comment]
@pzinn Thanks! please keep them coming! -- mike

**Comment by pzinn** [comment]
this should really be fixed. just to show you that I'm not crazy:
```
i23 : t_1*(t_2*t_1*t_3*t_4*t_5*t_6-t_2*t_3*t_4*t_5*t_6*t_1)
o23 = 0
o23 : H

i24 : t_1*t_2*t_1*t_3*t_4*t_5*t_6-t_1*t_2*t_3*t_4*t_5*t_6*t_1
o24 = -t_1*t_2*t_3*t_4*t_5*t_6*t_1+t_2*t_1*t_2*t_3*t_4*t_5*t_6
o24 : H

i25 : t_1*oo
o25 = 0
o25 : H
```

**Comment by pzinn** [comment]
I think I understand why this fails, and it's not top priority. closing.
