### ISSUE TITLE
AssociativeAlgebras map bug

### ISSUE THREAD

**Issue by pzinn** [Macaulay2/M2#2249]
@mikestillman you asked for it :-P
`map` seems to lose denominators in the coefficient ring:
```
i1 : R=frac(QQ[t])

o1 = R

o1 : FractionField

i2 : needsPackage "AssociativeAlgebras"

o2 = AssociativeAlgebras

o2 : Package

i3 : S=R<|T|>

o3 = S

o3 : FreeAlgebra

i4 : f=map(S,S)

o4 = map (S, S, {T, t})

o4 : RingMap S <--- S

i5 : t^(-1)*T

     1
o5 = -T
     t

o5 : S

i6 : f oo

o6 = T

o6 : S
```

**Comment by mikestillman** [comment]
Fixed in PR #2493.  Division was just returning the original element.  It now implements division, when the element is in the coeff ring, and that ring allows division.
