### ISSUE TITLE
MPFI download fails

### ISSUE THREAD

**Issue by blegat** [Macaulay2/M2#2254]
The installation fails as the following URL:
https://github.com/Macaulay2/M2/blob/97f7325791d77fec1028e3db667e7a7f8948121e/M2/cmake/build-libraries.cmake#L303
gives "Forbidden 403".

**Comment by DanGrayson** [comment]
It seems to have gone down, according to https://groups.google.com/g/isl-development/c/JGaMo2VUu_8

**Comment by DanGrayson** [comment]
Debian has a source repository at https://salsa.debian.org/science-team/mpfi

Maybe @d-torrance can recommend whether to use it.

Actually, the best thing to do would be to get the tarfiles from somewhere and put them on our website, as I've done with all the other libraries.

**Comment by d-torrance** [comment]
Salsa is the git repository for the Debian packaging, but you could also use the upstream tarballs that Debian hosts, e.g., http://deb.debian.org/debian/pool/main/m/mpfi/mpfi_1.5.3+ds.orig.tar.xz.

Two possible issues: It's not 1.5.4, and the `+ds` in the filename indicates that it's been repacked.  According to the `Files-Excluded` field in the [debian/copyright](https://salsa.debian.org/science-team/mpfi/-/blob/master/debian/copyright) file, it looks like it's mostly generated autotools files that have been removed, so it might be ok.

**Comment by DanGrayson** [comment]
Thanks, I'll get it from there.

**Comment by DanGrayson** [comment]
Probably a step will have to be added to create the configure script from `autoconf.ac`.  I had to do that for the autotools build.
