### ISSUE TITLE
"reading files" documentation buggy

### ISSUE THREAD

**Issue by pzinn** [Macaulay2/M2#2256]
cf
https://faculty.math.illinois.edu/Macaulay2/doc/Macaulay2-1.18/share/doc/Macaulay2/Macaulay2Doc/html/_reading_spfiles.html
the `i11: input` line messes up the numbering and all that follows is buggy.
the same issue arises in my KaTeX version, BTW:
https://www.unimelb-macaulay2.cloud.edu.au/usr/share/doc/Macaulay2/Macaulay2Doc/html/_reading_spfiles.html

**Comment by DanGrayson** [comment]
Indeed.  Maybe we should not use `input` in documentation nodes.  I'll remove it.
