### ISSUE TITLE
Macaulay2 seems only compatible with yacc from 'bison'

### ISSUE THREAD

**Issue by jakobkroeker** [Macaulay2/M2#228]
getting on 14.04 
```
/home/jakob/Projects/M2-master/M2/BUILD/master/builds.tmp/ubuntu64.production/Macaulay2/c/scc1 -dep  -O /home/jakob/Projects/M2-master/M2/BUILD/master/../../Macaulay2/d/atomic.d
/home/jakob/Projects/M2-master/M2/BUILD/master/../../Macaulay2/c/list.c:101: assertion failed
arithmetic.sig:141 <- here
```
for recent master branch

1.Any idea?
2. reproducible?

**Comment by DanGrayson** [comment]
I've never seen that before, but it certainly indicates a problem.  I built M2 today in Ubuntu
14.04.2 32 bit, and it wasn't a problem.  I could try the 64 bit version in a day or so ...

**Comment by jakobkroeker** [comment]
update: problem caused by usage of yacc from 'byacc' instead of yacc from 'bison'.
If I recall correctly, using yacc from bison++ (instead of bison) resulted in an error on fedora

**Comment by DanGrayson** [comment]
Let's leave this issue open, so I can fix the configure script to detect whether it's byacc and
complain.
