### ISSUE TITLE
Bug: Cannot get the modules of a resolution without first calling `res`

### ISSUE THREAD

**Issue by grunkgrunk** [Macaulay2/M2#2281]
Hi,
I think I might have discovered a bug:
```
restart;
Q = ZZ/2[x,y,z]
I = ideal (x^2,x*y^2,z^2)
apply(1..3, i -> (res I)#i ) -- does not work. "error: key not found in hash table"
res I
apply(1..3, i -> (res I)#i ) -- now works!
```
So it seems I have to call `res I`, before i can index into it. Is this desired behavior? :)

However, I found a workaround. This works:
```
restart;
Q = ZZ/2[x,y,z]
I = ideal (x^2,x*y^2,z^2)
apply(1..3, i -> (res I)_i )
```
That is, indexing with `_` instead of `#` works.

All the best

**Comment by DanGrayson** [comment]
We think of the operator `_` as a mathematical operator and the operator `#` as a computer programming operator, so it's better to use `C_i` to access the objects in a chain complex.  When the new implementation of chain complexes becomes the default, the internal location of the objects will change, so `C#i` will have no chance of working, but `C_i` will still work.

**Comment by mahrud** [comment]
But why doesn't it work? Shouldn't the output hashtable be there after the first call to res?

**Comment by DanGrayson** [comment]
No, we don't extract the modules from the engine resolution object until demanded.

**Comment by mahrud** [comment]
Ah, so when `res I` is called alone, the printing routine extracts that information from the engine, so then it works. I see

**Comment by DanGrayson** [comment]
Yes, that's right.

The behavior of the new chain complex package might be different.
