### ISSUE TITLE
automate the list of contributors

### ISSUE THREAD

**Issue by DanGrayson** [Macaulay2/M2#23]
The page at http://www.math.illinois.edu/Macaulay2/Contributors/ should be generated in an automatic way from the current list of packages.  For hints, see how the page at http://www.math.illinois.edu/Macaulay2/Packages/ has been automated recently.

**Comment by mahrud** [comment]
I believe these are the only author names that need to be changed before this can be automated:
```
Contributing Author: Taylor Brysiewicz
Contributing Author: Diego Cifuentes
Contributing Author: Corey Harris
Contributing Author: Jeff Sommars
Contributing Author: Anna Seigal
Contributing Author: Kaie Kubjas
Contributing Author: Anton Leykin
Contributing Author: Tanner Zielinski
Contributers of note: Alex Diaz, Luis Garcia, Shaowei Lin, Sonja Mapes, Mike Stillman, Doug Torrance
Lars Kastner (Maintaining author)
Diane Maclagan (current maintainer)
Special thanks: Ilir Dema, Nidhi Kaihnsa, Anton Leykin

Daniel R. Grayson (高单)
Daniel R. Grayson
Dan Grayson
Michael Stillman
Michael E. Stillman
Mike Stillman
Daniel Hernandez
Daniel Hernández
Dave Swinarski
David Swinarski
Frank Schreyer
Frank-Olaf Schreyer
Greg Smith
Gregory G. Smith
Luis Garcia
Luis Garcia-Puente
Pablo A. Parrilo
Pablo Parrilo
Steven V Sam
Steven V. Sam
```

Should we contact them individually, or just make appropriate changes based on arXiv names, etc?

**Comment by mahrud** [comment]
For "Contributing Authors" and "Special thanks" we can just use the new `Contributors` section introduced in the SimpleDoc PR, and perhaps a new `Comments` field can be added to replace the "current maintainer" comments.

Actually, another way to do this without changing the repeated names is to add a `Permalink` or something like that for all variations of the same name, but even then only one of the variations will appear on the page, depending on which package comes first on the list of packages.

**Comment by DanGrayson** [comment]
Why do you want to change author names?  Is it because you want to merge variations of the same name?  If so, why not just do it?  If you like, I can select the desired variations.

**Comment by mahrud** [comment]
Okay, I wasn't sure if it's okay to go in and change author names in a bunch of packages, but that's definitely the easiest.

**Comment by DanGrayson** [comment]
Oh, no, if that's the intention, better ask.  I thought you were going to
change the names on the fly while generating the list.

**Comment by mahrud** [comment]
Oh no that would be kinda ugly. Okay, I guess we'll have to ask people.

**Comment by mahrud** [comment]
I'm reopening this, to track work on the list of irregular and repeated author names above.

**Comment by mahrud** [comment]
Remaining author names to fix:
```
Contributers of note: Alex Diaz, Luis Garcia, Shaowei Lin, Sonja Mapes, Mike Stillman, Doug Torrance
Contributing Author: Anna Seigal
Contributing Author: Anton Leykin
Contributing Author: Corey Harris
Contributing Author: Diego Cifuentes
Contributing Author: Jeff Sommars
Contributing Author: Kaie Kubjas
Contributing Author: Tanner Zielinski
Contributing Author: Taylor Brysiewicz
Special thanks: Ilir Dema, Nidhi Kaihnsa, Anton Leykin

Lars Kastner (Maintaining author)

Diane Maclagan
Diane Maclagan (current maintainer)

Michael E. Stillman -- 17
Michael Stillman    -- 5
Mike Stillman       -- 35
```
