### ISSUE TITLE
order of factors in factorization from factory library

### ISSUE THREAD

**Issue by DanGrayson** [Macaulay2/M2#232]
See commit 248abbfe542427722cfddcd4ec76defe3ddb73a1.  There we discover that a 
certain factorization test yields results that depend on whether the machine is 32 bit or
64 bit.  But the algorithm does not depend on that, according to Hans Schoenemann.
Figure it out.

Note: our factorization routines set factory's random number seed to 0 every time.  It might
be better to set it when our random number seed is set, using the same information.

**Comment by d-torrance** [comment]
This was fixed in #1385
