### ISSUE TITLE
Change precedence of `Ring Array`

### ISSUE THREAD

**Issue by mahrud** [Macaulay2/M2#2336]
Following #173, the documentation of `frac` was changed to note that:
> Note that expressions such as `frac QQ[x]` are parsed as `(frac QQ)[x]`. To obtain the fraction field of `QQ[x]` use instead `frac (QQ[x])`.

But now I'm running into a similar issue with `Proj kk[x,y]` and `Proj(kk[x,y])`. In this case an easier solution is to define `ProjectiveVariety Array` to do the right thing, since adjoining variables to a variety doesn't make sense any other way, but honestly it would be nice if all of the following worked right out of the box:
```m2
Proj kk[x,y]
dim kk[x,y]
module kk[x,y]
poincare kk[x]/ideal x^2
```
So I'm wondering if it's possible to change the interpreter so that `Function Ring Array` is interpreted as `Function (Ring Array)` instead of `(Function Ring) Array`. This also makes sense more generally because `f g x` is interpreted as `f(g(x))`, not `(f(g))(x)`! Also, in other situations this rule is followed:
```m2
i1 : R = kk[x];

i2 : I = ideal x;

o2 : Ideal of R

i3 : I ** R[y]

o3 = ideal x

o3 : Ideal of R[y]
```
So unless there's a specific reason I'm missing, I think the current behavior might just be a bug. Right?

**Comment by DanGrayson** [comment]
It's not a bug -- the parsing was set up this way so expressions like `ZZ/101 [x,y,z]` would work, even though SPACE binds more tightly than `/`, which in turn was set up that way so things like ` sin 1 / cos 1 ` would work.

**Comment by mahrud** [comment]
I'm not sure if I follow. It's okay that `/` takes priority, but in an expression like `f g x`, you would always expect `g x` to be computed first, right? Now let `f = Proj`, `g = kk`, and `x = [x,y,z]`. Why does `f g` take priority suddenly?

**Comment by DanGrayson** [comment]
I arranged it that way so `ZZ/101[x]` would work.  I explain it in detail here: https://faculty.math.illinois.edu/Macaulay2/doc/Macaulay2-1.19/share/doc/Macaulay2/Macaulay2Doc/html/_parsing_spprecedence_cm_spin_spdetail.html

**Comment by mahrud** [comment]
I read that page, but what I don't understand is how is my suggestion in contradiction with `ZZ/101[x]` working? For instance, why can't `Proj ZZ/101 [x]` be parsed as `Proj ((ZZ/101) [x])`? I think that follows your rules, since `/` takes priority, then each `SPACE` from right to left, same way that `f g x` would. I think the main difference between `Proj ZZ/101 [x]` and `f g x` is that `ZZ/101` is a ring rather than a function, which makes me think this might even be fixable more easily.

**Comment by mahrud** [comment]
I reread this paragraph:
> One of the most unusual aspects of the parsing precedence table above is that [ is assigned a precedence several steps lower than the precedence of symbols and adjacency, and also lower than the precedence of /. This was done so expressions like R/I[x] would be parsed according to mathematical custom, but it implies that expressions like f g [x] will be parsed in a surprising way, with f g being evaluated first, even if f and g are both functions. Suitably placed parentheses can help, as illustrated in the next example.

But I still don't understand why the following is inconsistent:
```m2
  f/g [x] --->    ((f/g) [x])
  f g [x] --->     (f(g  [x])
h f/g [x] ---> (h ((f/g) [x]))
```
In other words, the precedence order would be `/` then `[` then adjacency.

**Comment by DanGrayson** [comment]
The token `[` has a very low unary binding strength of 6, so every operator to the left of it with a precedence greater than 6 (which is most of them) is bound first, before continuing with the '['.

**Comment by mahrud** [comment]
Why can't `[` be moved to be after `/` but before adjacency? I think making the following work mathematical notation work out of the box is a good motivation:
```m2
Spec ZZ/101[x,y]/(y^2-x^3)
```

**Comment by DanGrayson** [comment]
Well, it seems you also want SPACE to bind more loosely than `/`, which would be a disruptive change.

Besides, when I look at `Spec ZZ/101[x,y]/(y^2-x^3)`, my eyeball screams for disambiguating parentheses, as in `Spec (ZZ/101[x,y]/(y^2-x^3))`

**Comment by mahrud** [comment]
Okay, let's start simpler. How would one make `Proj ZZ/3` to work exactly? What change in `binding.d` would make that work, even if other things break?

**Comment by DanGrayson** [comment]
You would have to change the precedence of SPACE so it binds more loosely than `/`.  And `*`, presumably.

**Comment by mahrud** [comment]
> You would have to change the precedence of SPACE so it binds more loosely than `/`. And `*`, presumably.

The trouble is that I can't make sense of `binding.d` and how that results in the table from `seeParsing`. The documentation page you linked is not clear enough to help either. For instance, what is an "identifier"? It's used only once and never defined. How is the precedence of "function application" determined?

I would like to make a change so that the following code prints `1`:
```
i38 : sin pi/2
stdio:38:1:(3): error: expected a number
```
I understand that it may seem ambiguous, but either way it is ambiguous and we just need to decide on a convention. My proposal is to make this change, run the examples and tests, and if it's not too cumbersome to fix things that break, ask the community to see which convention they prefer. It's a breaking change, but since the goal is to match mathematical notation more closely I think it is at least worth implementing and discussing with others.

**Comment by mahrud** [comment]
To be clear, I'm asking for the specific change in `binding.d` that would result in the change above.

**Comment by DanGrayson** [comment]
You can try this:
```diff
diff --git a/M2/Macaulay2/d/binding.d b/M2/Macaulay2/d/binding.d
index f1b5809b9..4effba167 100644
--- a/M2/Macaulay2/d/binding.d
+++ b/M2/Macaulay2/d/binding.d
@@ -290,6 +290,8 @@ bumpPrecedence();
      precBracket := prec;
      export leftbracket := parens("[","]",precBracket, precRightParen, precRightParen);
      export leftAngleBar := parens("<|","|>",precBracket, precRightParen, precRightParen);
+bumpPrecedence();
+     export AdjacentS:=makeKeyword(binaryright("SPACE"));
 bumpPrecedence();
      export BackslashBackslashS := makeKeyword(binaryright("\\\\"));
      export StarS := makeKeyword(unarybinaryleft("*"));	    -- also binary
@@ -301,7 +303,6 @@ bumpPrecedence();
      export AtS := makeKeyword(binaryright("@"));
 bumpPrecedence();
      precSpace = prec;
-     export AdjacentS:=makeKeyword(binaryright("SPACE"));
      export leftparen   := parens("(",")",precSpace, precRightParen, precRightParen);
      export leftbrace   := parens("{","}",precSpace, precRightParen, precRightParen);
      parseWORD.precedence = prec; parseWORD.binaryStrength = nopr; parseWORD.unaryStrength = nopr;
```

(Each time bumpPrecedence is called, the parsing precedence gets tighter.  So we move the definition of SPACE up a few lines.)

**Comment by mahrud** [comment]
No, I tried this already but it didn't work. That's why I'm asking you to show me something that works.

**Comment by DanGrayson** [comment]
In what sense did it not work?

**Comment by DanGrayson** [comment]
Oops, you have to also move the assignment to precSpace up.

**Comment by DanGrayson** [comment]
```diff
diff --git a/M2/Macaulay2/d/binding.d b/M2/Macaulay2/d/binding.d
index f1b5809b9..610a47b59 100644
--- a/M2/Macaulay2/d/binding.d
+++ b/M2/Macaulay2/d/binding.d
@@ -290,6 +290,9 @@ bumpPrecedence();
      precBracket := prec;
      export leftbracket := parens("[","]",precBracket, precRightParen, precRightParen);
      export leftAngleBar := parens("<|","|>",precBracket, precRightParen, precRightParen);
+bumpPrecedence();
+     precSpace = prec;
+     export AdjacentS:=makeKeyword(binaryright("SPACE"));
 bumpPrecedence();
      export BackslashBackslashS := makeKeyword(binaryright("\\\\"));
      export StarS := makeKeyword(unarybinaryleft("*"));	    -- also binary
@@ -300,8 +303,6 @@ bumpPrecedence();
 bumpPrecedence();
      export AtS := makeKeyword(binaryright("@"));
 bumpPrecedence();
-     precSpace = prec;
-     export AdjacentS:=makeKeyword(binaryright("SPACE"));
      export leftparen   := parens("(",")",precSpace, precRightParen, precRightParen);
      export leftbrace   := parens("{","}",precSpace, precRightParen, precRightParen);
      parseWORD.precedence = prec; parseWORD.binaryStrength = nopr; parseWORD.unaryStrength = nopr;
```

**Comment by mahrud** [comment]
What about the binary strength?

**Comment by mahrud** [comment]
Okay, https://github.com/Macaulay2/M2/commit/df1773be31ad1eb94b076ad8df762e64bd60fb70 more or less works I think. Thanks!

This results in:
```m2
i1 : ZZ/3[x]

     ZZ
o1 = --[x]
      3

o1 : PolynomialRing

i2 : Proj ZZ/3[x]

          ZZ
o2 = Proj(--[x])
           3

o2 : ProjectiveVariety

i3 : ZZ/3[x]/x
stdio:3:8:(3): error: no method for binary operator / applied to objects:
--            [x] (of class Array)
--                        ZZ
--      /     x (of class --[x])
--                         3
```
I think the workaround to get `ZZ/3[x]/x` working is to have `[x]/x` create a `QuotientMonoid` and have `Ring QuotientMonoid` and `QuotientRing Monoid` result in identical outputs. What do you think?

**Comment by mahrud** [comment]
The main breaking change is the following:

Now:
```m2
i1 : sin pi/2
stdio:1:1:(3): error: expected a number

i2 : sin 1 / cos 1

o2 = 1.5574077246549

o2 : RR (of precision 53)
```
Proposed:
```m2
i1 : sin pi/2

o1 = 1

o1 : RR (of precision 53)

i2 : sin 1 / cos 1

o2 = .961050079349205

o2 : RR (of precision 53)
```

**Comment by mahrud** [comment]
With the I realized that with the change above, one thing that's probably annoying to fix is `ring I / I` and the like.

However, I'm hoping to find a way so that `/` is parsed ahead of function application _only_ when it is before `[`. Would that be too convoluted?

**Comment by DanGrayson** [comment]
That seems too convoluted.  And anyway, look at `ring I / I` versus `Spec R / I` to see that it's really not about `[`.

**Comment by mahrud** [comment]
Fair enough. I'll go with my earlier kludge:
> In this case an easier solution is to define `ProjectiveVariety Array` to do the right thing
