### ISSUE TITLE
Links to synonyms in the documentation

### ISSUE THREAD

**Issue by d-torrance** [Macaulay2/M2#2352]
Links to synonyms using `TO` are resolved to their longer forms.  For example:

```m2
i1 : beginDocumentation()

i2 : TO "gens"

o2 = "generators"

o2 : TO
```

This can make the documentation confusing.  For example:

```
i3 : help "extracting generators of an ideal"

o3 = extracting generators of an ideal
     *********************************

    ... [snip] ...

     the generators as a matrix or list of elements
     ==============================================

     Use "generators" or its abbreviation "generators" to get the generators of
     an ideal I as a matrix. Applying first entries to this matrix converts it
     to a list.
```

The intention was for it to say `or its abbreviation "gens"`, as can be seen in the source:
https://github.com/Macaulay2/M2/blob/729dcedb9437682f631c99e1473e47732dc06d1f/M2/Macaulay2/packages/Macaulay2Doc/ov_ideals.m2#L263

**Comment by mahrud** [comment]
Nothing should change about `TO`. That page should instead use `TT "gens"`.
