### ISSUE TITLE
minor: build rpm: not complained about missing 'fakeroot' on fedora 

### ISSUE THREAD

**Issue by jakobkroeker** [Macaulay2/M2#240]
@FAKEROOT@ was replaced by 'false' in case there was no fakeroot installed. =>error when trying to build rpm.

Scripts did not complain.

**Comment by DanGrayson** [comment]
The configure script complains if you have --enable-rpm as an option.  Otherwise, why bother complaining?

**Comment by jakobkroeker** [comment]
>The configure script complains if you have --enable-rpm as an option.

It was: I used  `make -f Makefile.fedora64` (see Makefile.fedora64)
Or, did it complain but continue? 

In any case, this is only minor.

**Comment by DanGrayson** [comment]
Oops, the logic in configure.ac was wrong.  Fixed in commit
c9cdc02849a8f86fa649d2be31dddbbaee65b735

**Comment by jakobkroeker** [comment]
>fixed

confirm
