### ISSUE TITLE
`getWWW` http request deemed invalid by some servers

### ISSUE THREAD

**Issue by pzinn** [Macaulay2/M2#2414]
some servers require the proper \r\n for CRLF, cf
https://stackoverflow.com/questions/5757290/http-header-line-break-style
M2 `endl`, on the other hand, only sends \n.
the result is that `getWWW` (in http.m2) requests are invalid and will be rejected by some servers.
random example: try
```
getWWW "http://wayback.cecm.sfu.ca"
```

**Comment by DanGrayson** [comment]
good catch.

Do you want to be assigned to fix it?

**Comment by mikestillman** [comment]
Yes, good catch!  I had some strange problem with this a while ago, didn't figure it out (I thought it was a problem with the website).  Maybe this will fix it!

**Comment by pzinn** [comment]
yes, I can take care of it
