### ISSUE TITLE
product with negative number argument

### ISSUE THREAD

**Issue by pzinn** [Macaulay2/M2#2437]
`product(ZZ,Function)` does not worry about the case where the first argument is negative. the result is that it outputs the function at 0 in this case, which is not very reasonable:
```
i1 : product(1,x->42)

o1 = 42

i2 : product(0,x->42)

o2 = 1

i3 : product(-1,x->42)

o3 = 42
```
it should either throw an error, or give 1. which?

this affects various functions calling `product`, such as `binomial(RingElement,ZZ)`.

**Comment by pzinn** [comment]
there's the same problem with `sum`.

**Comment by DanGrayson** [comment]
Oops, I wonder how that happened.  I think the good way to go would be to regard those as empty sums and empty products, and to return 0 and 1 respectively.  Which sometimes happens:
```m2
i26 : product (-55, i->33)

o26 = 33

i27 : product (-55, i->i+1)

o27 = 1
```

**Comment by DanGrayson** [comment]
Strike what I said, it seems to be returning the value of the function at 0:
```m2

i28 : product (-55, i->i+11)

o28 = 11
```

**Comment by pzinn** [comment]
I'll take care of it.

**Comment by DanGrayson** [comment]
Thanks!
