### ISSUE TITLE
M2 crash with memory error (default settings not optimal?)

### ISSUE THREAD

**Issue by kschwede** [Macaulay2/M2#2445]
Hi all,

Several years ago @DanGrayson showed me how to compile M2 so that it certain commands don't crash with a complaint about memory, even when there is a great deal of memory available (is this related to the garbage collector?)

``Too many heap sections: Increase MAXHINCR or MAX_HEAP_SECTS
Aborted (core dumped)``

https://groups.google.com/g/macaulay2/c/igGEcSUD1j0/m/ArgDsN_tKy4J

In particular, compiling in the classic way, one can avoid this by compiling with the command:
``
./configure CFLAGS="-DMAX_HEAP_SECTS=16384" --enable-build-libraries="gc" --enable-download
``
(change 16384 if you'd like).
Should something like this be the default?  (Also @mahrud how do you accomplish the same thing if you want to compile with cmake?)

The reason this came up is that Selvi Kara recently pointed out to me that the following computation of hers crashes.  It even crashes on a  Utah departmental machine, running Ubuntu 20.04, Macaulay2 1.19.1, which has _6 terrabytes of ram_.

Compiling as above fixes the issue on the machines I've tried (also running Ubuntu 20.04).

For debugging purposes, here is the set of commands that one can use to debug this.  It uses about 25gb of ram and takes about 1.5-2.0 hours to complete if it's working well.  It crashes much more quickly than that though if not compiled with the alternate settings (ie,if you use the precompiled binary for Ubuntu).  It tends to crash when it gets to about 8.5 gb used if using the default binary or if compiled with default settings.

```

T=QQ[a11,a12,a15,a22,a23,a33,a34,a44,a45,a55,t]

S=QQ[M11,M12,M13,M14,M15,M22,M23,M24,M25,M33,M34,M35,M44,M45,M55, Degrees=>{5,5,5,5,5,5,5,5,5,5,5,5,5,5,5}]


F= map(T,S,{

(a23^2*a45^2-a22*a33*a45^2-a22*a34^2*a55-a23^2*a44*a55+a22*a33*a44*a55)*t,

(a15*a23*a34*a45+a12*a34^2*a55+a12*a33*a45^2-a12*a33*a44*a55)*t,

(a12*a23*a44*a55-a12*a23*a45^2-a15*a22*a34*a45)*t,

(-a15*a23^2*a45+a15*a22*a33*a45-a12*a23*a34*a55)*t,

(a15*a23^2*a44+a15*a22*a34^2-a15*a22*a33*a44+a12*a23*a34*a45)*t,

(a15^2*a34^2-a15^2*a33*a44-a11*a34^2*a55-a11*a33*a45^2+a11*a33*a44*a55)*t,

(a15^2*a23*a44+a12*a15*a34*a45-a11*a23*a44*a55+a11*a23*a45^2)*t,

(-a15^2*a23*a34-a12*a15*a33*a45+a11*a23*a34*a55)*t,

(-a12*a15*a34^2+a12*a15*a33*a44-a11*a23*a34*a45)*t,

(a12^2*a45^2-a12^2*a44*a55-a11*a22*a45^2+a11*a22*a44*a55-a15^2*a22*a44)*t,

(a15^2*a22*a34+a12*a15*a23*a45-a11*a22*a34*a55+a12^2*a34*a55)*t,

(-a12^2*a34*a45-a12*a15*a23*a44+a11*a22*a34*a45)*t,

(a15^2*a23^2-a15^2*a22*a33-a12^2*a33*a55-a11*a23^2*a55+a11*a22*a33*a55)*t,

(a12^2*a33*a45+a12*a15*a23*a34-a11*a22*a33*a45+a11*a23^2*a45)*t,

(a12^2*a34^2-a12^2*a33*a44-a11*a23^2*a44-a11*a22*a34^2+a11*a22*a33*a44)*t

})

time ker F
```

Is there something we should be doing instead?  Is there a way to accomplish this without recompiling?

**Comment by DanGrayson** [comment]
If we find libgc on the system, then we don't compile it ourselves; nowadays we often (or maybe even always) find it on the system.  If we want always to have a version of libgc configured for large memory, we should always build libgc ourselves.

If you want to set that up for yourself without rebuilding all of M2, you can build libgc yourself with the large memory options, and add its location to DYLD_LIBRARY_PATH (under mac os) or to LD_LIBRARY_PATH (under Linux) so your new library gets used instead.

If one doesn't set MAX_HEAP_SECTS, then one could set LARGE_CONFIG instead, and the code in gc_priv.h will select a value.  That's what we currently do, when we build it ourselves.  The largest value it selects is 81920, so it might better to just set MAX_HEAP_SECTS to that.

The maximum value for MAXHINCR used in gc_priv.h is 4096, so we could use that, too.

I'd be happy to set that up for the next release.  (autoconf build)

**Comment by kschwede** [comment]
Setting that for the next release would be great, thanks!

**Comment by DanGrayson** [comment]
Will do.

**Comment by mahrud** [comment]
> Should something like this be the default? (Also @mahrud how do you accomplish the same thing if you want to compile with cmake?)

gc built with cmake or distributed with brew is always compiled with `--enable-large-config`, so this is already the default.
