### ISSUE TITLE
Hom(Module,Matrix)

### ISSUE THREAD

**Issue by DanGrayson** [Macaulay2/M2#246]
The code for Hom(Module,Matrix) seems to give wrong answers in the case where the modules are not all free modules or quotient modules.  Before fixing this, improve the code for Hom(Module,Module) so Hom(M,N) is a subquotient of the best free module possible.  A consequence will be that Hom(R^1,F) will be visibly the same as F for any F, and not just when F is already a quotient module.

First step, disable the method in the case where it is wrong.

**Comment by DanGrayson** [comment]
Here's what we mean by the best free module possible: M is a quotient of the free module ```cover M```, which is the source of ```gens M```, and N is a submodule of ```super N```, which is the same as ```coker relations N``` and is a quotient module of  ```ambient N```.  Thus ```Hom(M,N)``` is a submodule of ```Hom(cover M,super N)```.

**Comment by DanGrayson** [comment]
Here's an example that shows that Hom doesn't always do what we wish:
```

i1 : R=QQ[x]

o1 = R

o1 : PolynomialRing

i2 : image vars R

o2 = image | x |

                             1
o2 : R-module, submodule of R

i3 : Hom(R^1,oo)

o3 = image {1} | 1 |

                             1
o3 : R-module, submodule of R
```

**Comment by DanGrayson** [comment]
Remember to reverse the changes in https://github.com/Macaulay2/M2/commit/f61032ed95270c989882610f8c5fb9878d72b75f after this issue is taken care of.

**Comment by DanGrayson** [comment]
Remember to modify the code for ```homomorphism Matrix```, too.

**Comment by DanGrayson** [comment]
I've started working on this on this branch of mine: https://github.com/DanGrayson/M2/tree/Hom-functoriality

And I've discovered that ```adjoint``` and ```adjoint1``` have bugs, too, see the new failing test file on my branch: https://github.com/Macaulay2/M2/blob/8f7a8e64060e067a07eed457fb7afde8c352dbdb/M2/Macaulay2/packages/Macaulay2Doc/test/adjoint.m2

**Comment by DanGrayson** [comment]
First we fix a bug in Matrix::reshape, to get the degrees right: https://github.com/Macaulay2/M2/commit/2713dbae0d4a16012739234fd87d19619b181f1e

**Comment by DanGrayson** [comment]
We should implement the most general form of the adjointness between Hom and tensor, by providing inverse functions that transform between maps of the form F**G-->H and maps of the form F -> Hom(G,H), as well as inverse isomorphisms between the modules Hom(F**G,H) and Hom(F,Hom(G,H)).

The function ```adjoint``` transforms maps of the form F**G-->H to maps of the form F->Hom(G,H) when F,G,H are all free, so we should just extend it to work for all modules.  The transformation in the other direction could be called ```adjoint'```.

Meanwhile, think of a better name for ```adjoint1```.

**Comment by DanGrayson** [comment]
The current code for ```Hom(Matrix,Module)``` is also wrong.

Try this input:
```
R = ZZ/101[a,b,c]
M = ker vars R
N = ideal vars R * M
f = map(M, N, gens N//gens M) -- the inclusion of N into M
assert isHomogeneous f
assert isWellDefined f
M' = coker presentation M
N' = coker presentation N
f' = map(M',M,1) * f * map(N,N',1)
assert isHomogeneous f'
assert isWellDefined f'
ann prune coker Hom(M',f') -- should be symmetric
ann prune coker Hom(f',M') -- should be symmetric
```
and get this output:
```

ii29 : ann prune coker Hom(M',f') -- should be symmetric

oo29 = ideal (b, a)

oo29 : Ideal of R

ii30 : ann prune coker Hom(f',M') -- should be symmetric

oo30 = ideal (b, a)

oo30 : Ideal of R
```

**Comment by DanGrayson** [comment]
Remember to add ```compose(L,M,N): Hom(L,M)**Hom(M,N) —> Hom(L,N)```

**Comment by DanGrayson** [comment]
Remember to replace ``` mapToHomomorphism ``` in the package ```CompleteIntersectionResolutions```

**Comment by mahrud** [comment]
> Remember to reverse the changes in [f61032e](https://github.com/Macaulay2/M2/commit/f61032ed95270c989882610f8c5fb9878d72b75f) and [32cc2d2](https://github.com/Macaulay2/M2/commit/32cc2d27ff3f3327f30630c2fe772223aa2ded4f) after this issue is taken care of.

I'll do this in #3042.

**Comment by mahrud** [comment]
32cc2d27ff3f3327f30630c2fe772223aa2ded4f still doesn't seem to be working.

**Comment by mahrud** [comment]
Also, why was a strategy for `compose` removed in 1f4bfb3eac0f1daa1c8f623e6df2e869955f4a4e?
There was a comment saying that the remaining strategy is slower by a factor of 5 on big examples.
