### ISSUE TITLE
Typo in headline of schreyerOrder documentation

### ISSUE THREAD

**Issue by morrowmh** [Macaulay2/M2#2461]
In the headline of http://www2.macaulay2.com/Macaulay2/doc/Macaulay2/share/doc/Macaulay2/Macaulay2Doc/html/_schreyer__Order.html there is an 'e' missing from 'Schreyer'.

**Comment by DanGrayson** [comment]
Thanks -- fixed in commit b8e5a5d5203e7f1e0e0245fa872f9e5adaff4c4e .
