### ISSUE TITLE
failing test on debian8 (64 bit)

### ISSUE THREAD

**Issue by jakobkroeker** [Macaulay2/M2#249]
input 
```
R = QQ[a..d]
D = res coker random(R^2,R^{4:-2})
status(D, TotalPairs => true, PairsRemaining => true, Monomials => true)
```
output
```
-- -*- M2-comint -*- {* hash: -885657649 *}

i1 : R = QQ[a..d]

o1 = R

o1 : PolynomialRing

i2 : D = res coker random(R^2,R^{4:-2})

      2      4      4      2
o2 = R  <-- R  <-- R  <-- R  <-- 0
                                  
     0      1      2      3      4

o2 : ChainComplex

i3 : status(D, TotalPairs => true, PairsRemaining => true, Monomials => true)
stdio:3:1:(3): error: key not found in hash table
```
installed lpackages:
```
pkg-config patch libtool autogen autoconf g++ bison gfortran build-essential ncurses-dev libxml2-dev zlibg1-dev liblzma-dev unzip
```
make command: 
`make -f Makefile.debian64`
M2 commit : 2713dbae0d4a16012739234fd87d19619b181f1e

**Comment by DanGrayson** [comment]
Thanks for the detailed bug report.

The problem here is that the documentation of "status" is slightly wrong, and "status" should give a better error message.  Some resolutions are constructed as "engine computations", and they are the one "status" applies to.  The example you give is not constructed that way, because the module is not homogeneous.  In the code for the method ```res Module``` one sees that the use of ```resolutionInEngine``` depends on a test:
```

i1 : code(res,Module)

o1 = -- code for method: resolution(Module)
     Macaulay2/m2/res.m2:194:40-207:36: --source code:
     resolution Module := ChainComplex => o -> (M) -> (
          if M.cache.?ManualResolution then return M.cache.ManualResolution;
          C := runHooks(Module,symbol resolution,(o,M));
          if C =!= null then return C;
          R := ring M;
          if isField R then return chainComplex map(minimalPresentation M,R^0,0);
          k := ultimate(coefficientRing, R);
          oR := options R;
          if engineReady M and (options R).Heft =!= null
          then (resolutionInEngine default(o,if isQuotientRing R or isSkewCommutative R then Strategy2 else Strategy1))(M)
          else if k === ZZ then (resolutionBySyzygies o)(M)
          else if not isHomogeneous M and isCommutative R and degreeLength R === 1 then (resolutionByHomogenization o)(M)
          else (resolutionBySyzygies o)(M)
          )
```

**Comment by DanGrayson** [comment]
... but I see now that was one of our tests, for ```status```, and the matrix should have been viewed as homogeneous, so reopening ...

**Comment by DanGrayson** [comment]
We compile and run tests on ubuntu every night, and this error also showed up there.  You may save yourself some effort if you let us respond first to the overnight tests.

**Comment by jakobkroeker** [comment]
>We compile and run tests on ubuntu every night,

good to know, thanks!

Surprisingly this error did not show up for me on fedora32 VM for whatever reasons
so I thought the error was debian8-specific...
