### ISSUE TITLE
0 / 0

### ISSUE THREAD

**Issue by pzinn** [Macaulay2/M2#2496]
this is weird:
```
i1 : R=QQ[x];

i2 : 0_R/0_R

     0
o2 = -
     0

o2 : frac R

i3 : oo+1
stdio:3:3:(3): error: a non unit was found in a ring declared to be a field
```

**Comment by mikestillman** [comment]
aarggh!  @DanGrayson I need to fix this one too this morning...

**Comment by mikestillman** [comment]
I was sure I had handled all divide by zero issues that were left...  I guess not...!  thanks for catching this @pzinn !

**Comment by pzinn** [comment]
> aarggh! @DanGrayson I need to fix this one too this morning...

Sorry :-P
