### ISSUE TITLE
VersalDeformation test 6 failures on ubuntu on github

### ISSUE THREAD

**Issue by jkyang92** [Macaulay2/M2#2538]
I've had the `VersalDeformation` test 6 fail with "Alarm clock" on two completely unrelated pull requests

https://github.com/Macaulay2/M2/runs/7047611893?check_suite_focus=true#step:12:4370

https://github.com/Macaulay2/M2/runs/7143745455?check_suite_focus=true#step:12:4370

I can't reproduce this is on Arch. Is "Alarm clock" a symptom of a test taking too long?

**Comment by d-torrance** [comment]
I've seen this one before, too:  https://github.com/Macaulay2/M2/issues/1392#issuecomment-739111748

> I can't reproduce this is on Arch. Is "Alarm clock" a symptom of a test taking too long?

I believe so.  I stopped using the default `ulimit`'s for the Debian/Ubuntu package a while back and haven't seen any of these sorts of errors since.

**Comment by DanGrayson** [comment]
I don't see what ulimits have to do with alarms.  Someone's code must be calling the M2 function "alarm".  I'll try to figure it out.

**Comment by DanGrayson** [comment]
I'm trying a fix here:

```sh
commit c12feefd48bf98f0c2f0fea1342dd49bcbc97909 (HEAD -> development, origin/development)
Author: Daniel R. Grayson <dan@math.uiuc.edu>
Date:   Mon Jul 4 19:57:14 2022 -0400

    cancel any alarms that were set by example code when capturing
    
    ... since then the alarm is set in the same process as we are.
```

**Comment by DanGrayson** [comment]
Well, that experiment didn't work, see https://github.com/Macaulay2/M2/actions/runs/2612978297

**Comment by DanGrayson** [comment]
It seems to occur just when building with cmake, not with autotools.  That seems odd.

**Comment by jkyang92** [comment]
I managed to reproduce this on Arch. Compiling with clang, if I run `./M2 --int` and call `check(6, "VersalDeformations")` I get "Alarm clock". Without `--int` the error doesn't happen. With gcc the error doesn't happen. Importantly, ./M2 --check 3 runs its tests with the `--int` flag

On a not completely related note `check(6, "VersalDeformations")` with clang seems much slower (4x) for me than with gcc.

**Comment by DanGrayson** [comment]
That makes sense, because `--int` tells M2 not to handle any interrupts!

**Comment by DanGrayson** [comment]
... and the way cmake runs tests is to use the `--check 3` option.

**Comment by DanGrayson** [comment]
Okay, see commit 7679add0c5de1f696f4f1d34b7c8d21a7da901f6

**Comment by DanGrayson** [comment]
It seems to have worked, see https://github.com/Macaulay2/M2/actions/runs/2658584495 . Thanks, Jay!
