### ISSUE TITLE
isUnit fails for fields defined using toField

### ISSUE THREAD

**Issue by moorewf** [Macaulay2/M2#258]
The command isUnit doesn't seem to work right in case the element is a field defined using toField:

R = QQ[q]/ideal{q^2+q+1}
isUnit q

S = toField(R)
isUnit q

Frank

**Comment by DanGrayson** [comment]
What output do you get?  It works here:
```
Macaulay2, version 1.7.0.1
with packages: ConwayPolynomials, Elimination, IntegralClosure, LLLBases, PrimaryDecomposition, ReesAlgebra, TangentCone

i1 : R = QQ[q]/ideal{q^2+q+1};

i2 : isUnit q

o2 = true

i3 : S = toField(R);

i4 : isUnit q

o4 = true
```

**Comment by moorewf** [comment]
My output says false for the second isUnit call.

This was on my Mac OS X build done at the end of 2014 and also on my Linux
build done at the end of March 2015.  I will rebuild and make sure the
error still occurs but it seems to have been fixed in the interim.  Sorry
about that.

Frank

On Thu, May 28, 2015 at 11:08 AM, Daniel R. Grayson <
notifications@github.com> wrote:

> What output do you get? It works here:
>
> Macaulay2, version 1.7.0.1
> with packages: ConwayPolynomials, Elimination, IntegralClosure, LLLBases, PrimaryDecomposition, ReesAlgebra, TangentCone
>
> i1 : R = QQ[q]/ideal{q^2+q+1};
>
> i2 : isUnit q
>
> o2 = true
>
> i3 : S = toField(R);
>
> i4 : isUnit q
>
> o4 = true
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Macaulay2/M2/issues/258#issuecomment-106389175>.
>



-- 
Dr. W. Frank Moore
Assistant Professor
Department of Mathematics, Wake Forest University

email: moorewf@wfu.edu

**Comment by DanGrayson** [comment]
That's interesting: it fails in 1.7 but not in our current development version.  So it definitely was a bug and definitely worth reporting, thank you for the report -- no apology needed.  I hope we've actually fixed the bug -- perhaps Mike can remember.  Anyway, I'm closing the issue.

**Comment by DanGrayson** [comment]
Mike think he might have actually fixed that.
