### ISSUE TITLE
Strange behavior in assignment of ring variables

### ISSUE THREAD

**Issue by mahrud** [Macaulay2/M2#2602]
Here's an unexpected error:
```m2
i1 : R := QQ(monoid[a,b,c]);

i2 : R = QQ(monoid[a,b,c]);

i3 : m = matrix {{a,b,c}}
stdio:3:5:(3): error: no method found for applying ring to:
     argument   :  a (of class Symbol)
```
Skipping the first line resolves it, but either it shouldn't be an error at all or it should always be an error, because I used `QQ(monoid[a,b,c])` as opposed to `QQ[a,b,c]`.

**Comment by DanGrayson** [comment]
The symbols a,b,c are given values by the assignment statement on line 2, but only if R is a global variable.  The presence of line 1 makes R a local variable.

**Comment by mahrud** [comment]
Ah, right, I was concentrating on the wrong aspect here.
