### ISSUE TITLE
reloadPackage would be useful

### ISSUE THREAD

**Issue by zteitler** [Macaulay2/M2#261]
For convenience (especially for new users) it would be nice to have a command ```reloadPackage``` that would reload an already-loaded package. Perhaps something like this would work:
```
reloadPackage = method();
reloadPackage (Package) := Package => o -> P -> loadPackage(toString P, Reload => true, o)
```

**Comment by zteitler** [comment]
I couldn't get the title via ```P.title``` or similar things.

**Comment by DanGrayson** [comment]
Why not just make loadPackage(Package) a method?

And add a method for reloadPackage(String)?

And submit a pull request for us implementing this?
