### ISSUE TITLE
Saturate slow in code for singular vector tuples

### ISSUE THREAD

**Issue by reamesb** [Macaulay2/M2#268]
Saturate appears to run very slowly in our code for computing SVD tuples of tensors.

```
SingularVectorTuples := (T,x)-> (
 K := ring T; --gets ring of the tensor T
 d:=tensorDims(T); --gets dimensions of the tensor T
 myVars:=for i from 0 to #d-1 list toList(x_(i,0)..x_(i,d#i-1)); --creates variables
 S:=K[flatten flatten myVars]; ---creates polynomial ring
 myVars=for i from 0 to #d-1 list toList(x_(i,0)..x_(i,d#i-1)); ---redefines variables 
 f:=tensorToMultilinearForm(T,S); --converts tensor to its homogenous polynomial form
 L:=for k in 0..#d-1 list for ind in (k,0)..(k,d#k-1) list ind; --intermediate step
 L=sum for i in 0..(#L-1) list minors(2,contract(matrix({myVars#i}),f)||matrix({myVars#i})); ---gets ideal of the tuples 
 myVarsId:=for i in myVars list ideal i;
 L=fold(saturate, join({L},myVarsId)) ---saturates (goes slowly)
)
```

A reference for singular vector tuples is section 1 of http://arxiv.org/abs/1210.8316

**Comment by mikestillman** [comment]
What do I need to load to get this to run?  Tensors.m2, in the Boise workshop?

**Comment by mikestillman** [comment]
Dan, the change that package export names need to be strings is so recent that people at our Boise workshop didn't know about it.  For instance, try loading Tensors.m2, here is my location for it:

load "~/src/M2-workshops/Workshop-2015-Boise/Tensors/Tensors.m2"

How should we handle this?

**Comment by reamesb** [comment]
Hi Mike,

Actually there is a slight bug in this which I am trying to fix....we couldn't figure out the error at the workshop. But, Dan gave me some pointers since then, so I'll give it another shot now. When I figure it out, I'll update the thread and give better instructions on what to run.

Meanwhile, regarding this second message, is there something I need to change so you can access it?

-Ben

**Comment by DanGrayson** [comment]
Now that export only handles strings, the easy fix is to put quotation marks around the names of the symbols.

**Comment by reamesb** [comment]
Okay, I have fixed the bug (or at least it works for me!) and pushed my changes.

To get the code to run you can do:

loadPackage "Tensors"
T=randomTensor(QQ,{2,2,3})
I=singularVectorTuples(T, symbol x)
d=degree I

The singularVectorTuples function on the random tensor as above should produce an ideal I of degree 8 pretty quickly. BUT, if you now do

T=randomTensor(QQ,{2,3,3})
I=singularVectorTuples(T, symbol x)

you may find yourself waiting quite a while (at least it takes a long time for me). If you wait it out, it is supposed to now give an ideal of degree 15.

When we started making this function, we just had a script, so we were running things step by step. When we did these examples, the only step that took a while was the saturate step.

The new code for the function is below, and I've tried to comment it:

singularVectorTuples = method()
singularVectorTuples (Tensor,Symbol) := (T,x)-> (
 K:=ring(T); --gets the ring of the input tensor T
 d:=tensorDims(T); --gets the dimensions of the input tensor T
 myVars:=apply(#d,j->apply(d#j,i->x_(j,i))); --creates variables indexed by an array...first index is the mode, second index runs to dimensions of that mode
 S:=K(monoid flatten myVars);--creates a ring in the new variables
 myVars=apply(#d,j->apply(d#j,i->S_(x_(j,i))));--recreates variables...ugly
 --myVars=for i from 0 to #d-1 list toList(x_(i,0)..x_(i,d#i-1));--this does the same thing as the apply's
 f:=tensorToMultilinearForm(T,S);--converts tensor into homogeneous multilinear form (i.e. feeds it a vector of variables for each mode)
 L:=for k in 0..#d-1 list for ind in (k,0)..(k,d#k-1) list ind; --creates indices...just preparing for next line
 L=sum for i in 0..(#L-1) list minors(2,contract(matrix({myVars#i}),f)||matrix({myVars#i})); ---creates ideal of defining singular vector tuples of the tensor T
 myVarsId:=for i in myVars list ideal i; --creates separate ideal for the variables corresponding to each mode of the tensor T
 L=fold(saturate, join({L},myVarsId)) --saturates one after the other with respect to the variables myVarsId comprises
);

**Comment by reamesb** [comment]
By the way, thanks Dan! The monoid trick worked!

**Comment by mahrud** [comment]
The code above returns a degree 15 ideal in about 25s now, which is about a 11x improvement (from 289s) over the time in v1.16. Closing this issue.
