### ISSUE TITLE
Error linking with libquadmath

### ISSUE THREAD

**Issue by mahrud** [Macaulay2/M2#2682]
I kept getting linking errors for a while, and I just noticed that it's also causing issues building brew bottles on ubuntu:
```
/home/linuxbrew/.linuxbrew/opt/binutils/bin/ld: Macaulay2/d/CMakeFiles/M2-interpreter.dir/boostmath-tmp.cc.o: undefined reference to symbol 'ldexpq@@QUADMATH_1.0'
/home/linuxbrew/.linuxbrew/opt/binutils/bin/ld: /home/linuxbrew/.linuxbrew/opt/gcc/lib/gcc/current/libquadmath.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
```
On my machine linking with `quadmath` resolves this, but apparently this fails on MacOS. @d-torrance any ideas what might be behind this?

**Comment by d-torrance** [comment]
Does defining the `BOOST_MATH_DISABLE_FLOAT128` macro help at all?  We use MFPR for all the Boost special functions, so there's no reason to link against libquadmath for 128-bit floats.

**Comment by mahrud** [comment]
It doesn't seem like it. Can you try seeing if your executables are linked with `libquadmath`, and if so does passing that actually remove it?

**Comment by d-torrance** [comment]
I was able to reproduce this using brew's Boost, which is version 1.80.  The Debian/Ubuntu packages are still at 1.74, which is probably why I never saw this (plus the autotools build was already adding `-lquadmath` to the linker flags -- I'm not 100% sure why...)

This is https://github.com/boostorg/math/issues/733, and linking with `-lquadmath` appears to be the correct solution.

**Comment by mahrud** [comment]
Not the ideal fix, and I'm not sure if it is universal, but closing this for now.
