### ISSUE TITLE
getSymbol doesn't check if name of symbol is valid

### ISSUE THREAD

**Issue by pzinn** [Macaulay2/M2#2713]
For example,
```
i1 : getSymbol "$x"

o1 = $x

o1 : Symbol

i2 : getSymbol "x_1"

i3 : getSymbol "x_1"

o3 = x_1

o3 : Symbol

i4 : getSymbol "x@1"

i5 : getSymbol "x@1"

o5 = x@1

o5 : Symbol

i6 : getSymbol "x@2" <- 3
stdio:6:17:(3): error: '<-': no method for object on left

i7 : getSymbol "x@2" <- 3

o7 = 3

i8 : value getSymbol "x@2"

o8 = 3
```
Interestingly, for some symbols, it will fail the first time but work the second. In any case this behavior can lead to unexpected issues (for example in the printing methods of `Symbol`), so should probably be prevented.

**Comment by DanGrayson** [comment]
I think the problem is that the global symbol is created, but its value isn't set to itself:
```

i1 : getSymbol "x@2"

i2 : getSymbol "x@2"

o2 = x@2

o2 : Symbol

i3 : value oo

i4 : 
```

The relevant (and buggy) code is here:

```
getglobalsym(d:Dictionary,s:string):Expr := (
     w := makeUniqueWord(s,parseWORD);
     when lookup(w,d.symboltable) is x:Symbol do Expr(SymbolClosure(globalFrame,x))
     is null do (
	  if d.Protected then return buildErrorPacket("attempted to create symbol in protected dictionary");
	  t := makeSymbol(w,dummyPosition,d);
	  globalFrame.values.(t.frameindex)));

getglobalsym(s:string):Expr := (
     w := makeUniqueWord(s,parseWORD);
     when globalLookup(w)
     is x:Symbol do Expr(SymbolClosure(if x.thread then threadFrame else globalFrame,x))
     is null do (
	  if globalDictionary.Protected then return buildErrorPacket("attempted to create symbol in protected dictionary");
	  t := makeSymbol(w,dummyPosition,globalDictionary);
	  globalFrame.values.(t.frameindex)));

getGlobalSymbol(e:Expr):Expr := (
     when e 
     is s:stringCell do getglobalsym(s.v)
     is z:Sequence do if length(z) != 2 then WrongNumArgs(2) else (
	  when z.0
	  is dc:DictionaryClosure do (
	       d := dc.dictionary;
	       if !isglobaldict(d) then WrongArg(1,"a global dictionary") else
	       when z.1
	       is s:stringCell do getglobalsym(d,s.v)
	       else WrongArgString(2)
	       )
	  else WrongArg(1,"a dictionary")
	  )
     else WrongArg("a string or a dictionary and a string"));
setupfun("getGlobalSymbol",getGlobalSymbol);
```

**Comment by DanGrayson** [comment]
... and `getSymbol` returns the symbol's value the first time, but the symbol itself the second time.

**Comment by pzinn** [comment]
I can fix this, but first, to clarify: what is a valid `Symbol` name? the doc says
```
Symbols are entered as an alphabetic character followed by a sequence of alphanumeric characters; case is significant. The single symbol character ' is regarded as alphabetic, so that symbols such as x' may be used.
```
but really most characters are (and should be) OK, including `$` (not first character), greek letters or pretty much any uncode, etc.
Is there existing code that does this validity check? I'm assuming there is, since trying to input directly an invalid symbol produces an error (incidentally, why is ` (backquote) an "invalid character"?)

**Comment by DanGrayson** [comment]
Good point.  Maybe fix the documentation by explaining the use of "$".  Those rules about characters allowed in symbols are intended to be used during parsing of code, and using `getSymbol` involves no parsing, so one could go either way with it.  I have a slight preference for not letting `getSymbol` created non-parsable symbols.

**Comment by pzinn** [comment]
I agree `getSymbol` should not be allowed to create non-parsable symbols, even if in principle they don't cause trouble; the issue is with output routines, that can get very confused with nonstandard symbols.
back to my question: where in the d code is the parsing done, where it checks if a symbol is valid?

**Comment by DanGrayson** [comment]
I think it's in the function `gettoken1` in the file "lex.d".

**Comment by pzinn** [comment]
related oddity:
```
i1 : symbol ++

o1 = ++

o1 : Keyword

i2 : getSymbol "++"

i3 : getSymbol "++"

o3 = ++

o3 : Keyword

i4 : o1===o3

o4 = false
```

**Comment by pzinn** [comment]
Actually it's not as simple as I thought. for example, `++` should be a valid symbol and it's not alphanumeric.

**Comment by pzinn** [comment]
or maybe we shouldn't let the user define symbols other than alphanumeric? that would be an easy fix.

**Comment by pzinn** [comment]
argh, but Multiprojectivevarieties defines non-alphanumeric symbols, we already had this issue for #2463 ...

**Comment by pzinn** [comment]
[seeking a volunteer](https://github.com/Macaulay2/M2/labels/seeking%20a%20volunteer) can be dropped, I've got a fix for this. I'm just waiting to PR it because of the current backlog.
