### ISSUE TITLE
NonAssociativeProduct expression

### ISSUE THREAD

**Issue by pzinn** [Macaulay2/M2#2746]
There seems to be an inconsistency in the name and/or function of the `NonAssociativeProduct` type of `Expression`:
```
i1 : (expression a) ** b ** c

o1 = a**b**c

o1 : Expression of class NonAssociativeProduct

i2 : peek oo

o2 = NonAssociativeProduct{a, b, c}
```
If the product is indeed ``nonassociative'' (not that ** is ever used for a non associative product, as far as I know), then certainly the product shouldn't be written as a triple product of `{a,b,c}` but rather as a series of double products, say 
```
BinaryOperation(symbol **,a,BinaryOperation(symbol **,b,c))
```
so either the name should be changed, or the way it works...

**Comment by DanGrayson** [comment]
Good point.  Alternatively, we could decree an order of operations for an expression such as `NonAssociativeProduct{a, b, c}`.

**Comment by pzinn** [comment]
I don't agree. Such reductions should only be done for associative operations.
