### ISSUE TITLE
"no system error indication found" while making example results

### ISSUE THREAD

**Issue by onecan** [Macaulay2/M2#2759]
I'm trying to package M2 for NixOS. When

`"installPackage(\"Topcom\", MakeDocumentation => true, MakeHTML => true, MakeInfo => true, MakePDF => false, RemakeAllDocumentation => false, IgnoreExampleErrors => false, RerunExamples => false, CheckDocumentation => true, UserMode => false, Verbose => false, InstallPrefix => \"/home/cgs/macualay2/M2/M2/usr-dist/\", SeparateExec => true, DebuggingMode => true); exit 0"`

is run during the build process, I get the error

`   -- making example results for "topcomRegularTriangulationWeights(Matrix,List)"Macaulay2/Core/startup.m2.in:116:47:(0):[12]: error: closing output file: no system error indication found`

I'm not sure what this means or what to do about it.

Thanks!

**Comment by DanGrayson** [comment]
"closing output file" indicates that it called the "close" system call

"no system error indication found" indicates that no description of the precise error is available

Other than that, it's hard to tell what's going on.

**Comment by onecan** [comment]
Is the remainder of the trace helpful at all?

```
-- making example results for "topcomRegularTriangulationWeights(Matrix,List)"Macaulay2/Core/startup.m2.in:116:47:(0):[12]: error: closing output file: no system error indication found
../../m2/examples.m2:225:69:(1):[11]: --back trace--
../../m2/installPackage.m2:541:33:(1):[10]: --back trace--
 -- 0.000110768 seconds elapsed
../../m2/installPackage.m2:521:5:(1):[9]: --back trace--
../../m2/installPackage.m2:719:9:(1):[8]: --back trace--
../../m2/methods.m2:154:80:(1):[7]: --back trace--
../../m2/option.m2:17:8:(1):[6]: --back trace--
../../m2/installPackage.m2:606:5:(1):[5]: --back trace--
../../m2/methods.m2:154:80:(1):[4]: --back trace--
../../m2/option.m2:17:8:(1):[3]: --back trace--
currentString:1:1:(3):[2]: --back trace--
Macaulay2/Core/startup.m2.in:563:33:(0):[1]: --back trace--
Macaulay2/Core/startup.m2.in:663:6:(0): --back trace--
make[2]: *** [Makefile:106: /home/cgs/macualay2/M2/M2/usr-dist/x86_64-Linux-nixos-22.11/lib/Macaulay2/Topcom/.installed] Error 1
make[2]: Leaving directory '/home/cgs/macualay2/M2/M2/Macaulay2/packages'
make[1]: *** [Makefile:15: all-in-packages] Error 2
make[1]: Leaving directory '/home/cgs/macualay2/M2/M2/Macaulay2'
make: *** [GNUmakefile:251: all-in-Macaulay2] Error 2
```

**Comment by DanGrayson** [comment]
Not really.

Maybe it's trying to write to a device that is remote mounted as a Network File System.  And thereby
running into some obscure problem.

**Comment by onecan** [comment]
This turned out to be `/run/user` being allocated too little space. Simply enlarging it fixes the problem.
