### ISSUE TITLE
\mathbb{C} showing up as &#x2102; on the website

### ISSUE THREAD

**Issue by mahrud** [Macaulay2/M2#2782]
See for instance the documentation for [gkz](http://www2.macaulay2.com/Macaulay2/doc/Macaulay2/share/doc/Macaulay2/Dmodules/html/_gkz.html):
> \&#x2102;$[\partial_1,...,\partial_n]$

**Comment by pzinn** [comment]
seems to be a mistake in the documentation itself: it is literally `&#x2102` in `Dsystems.m2`.

**Comment by mahrud** [comment]
Oh interesting, then nevermind, this is already being fixed.
