### ISSUE TITLE
libm not found while building on openSUSE

### ISSUE THREAD

**Issue by zuoliang** [Macaulay2/M2#2784]
Following instruction from INSTALL to build release-1.21-branch, got following error message.  Same error message while builidng release-1.20-branch as well.

![make error](https://user-images.githubusercontent.com/2041582/219904925-0b4d21a2-99b9-4da4-86ab-d157e7433324.png)

Following instruction from INSTALL-CMake.md to build release-1.21-branch, failed while linking M2-binary.  However, installation went through when building release-1.20-branch.
 
![cmake error](https://user-images.githubusercontent.com/2041582/219904974-49dbe569-0a17-40c2-b8c3-75d9300dcf2d.png)

**Comment by d-torrance** [comment]
I'm not sure what's going on with the `libm` linking issue in the autotools build, but the cmake issue looks like #2682, which has been fixed in the `master` branch.

**Comment by zuoliang** [comment]
> I'm not sure what's going on with the `libm` linking issue in the autotools build, but the cmake issue looks like #2682, which has been fixed in the `master` branch.

I confirm that the cmake build went fine after switching to `master` branch.   Thanks!
