### ISSUE TITLE
Behaviour of If / Else Statements on Separate Lines and Within Functions

### ISSUE THREAD

**Issue by David-GW** [Macaulay2/M2#2787]
Running
```
if 1 == 2 then
(
    print "yes";
)
else
(
    print "no";
);
```
gives the error
```
error: syntax error at 'else'
```
This behaviour is also present on the web interface.

Changing the example to
```
if 1 == 2 then
(
    print "yes";
) else
(
    print "no";
);
```
removes the error, but strangely so does
```
f=()->(
    if 1 == 2 then
    (
        print "yes";
    )
    else
    (
        print "no";
    );
);
f();
```
Is this intended behaviour?

**Comment by d-torrance** [comment]
I believe this is intended.

In general, Macaulay2 sees a newline and assumes the expression is complete unless it's expecting more.  By itself, `if 1 == 2 then (print "yes";)`is a complete Macaulay2 expression.

But when immediately followed by an `else` or nested inside yet-to-be closed parentheses, it's no longer complete, so it continues to parse the next line as part of the same expression.
