### ISSUE TITLE
Installation ok but Macaulay2 not working [ brew config ]

### ISSUE THREAD

**Issue by Lucqk** [Macaulay2/M2#2791]
Trying to install then to launch Macaulay2 using the home-brew tap 
https://github.com/Macaulay2/homebrew-tap

Installation via home brew : ok

But not working. Indeed,  when trying to run Macaulay2 in a terminal, get the error message  : 
**Segmentation fault: 11**

Setting : 
MacBook Pro 2019
MacOS Ventura 13.2.1

Thank in advance for any help.

**Comment by mahrud** [comment]
Could you show the output of `brew config`?

**Comment by Lucqk** [comment]
Hi. 
Thank you for considering my request so promptly. 


Actually, it works now! 

Yesterday, for some (stupid?) reason, 
I wrote brew --prefix M2`/bin/M2 instead of `brew --prefix M2`/bin/M2, 
with the natural consequence that it did not work. 

Btw thank you for the job you did in creating this homebrew tap. 
This is a great help for the math community. 

Best, 
Luc 



De: "Mahrud Sayrafi" ***@***.***> 
À: "Macaulay2/M2" ***@***.***> 
Cc: "Luc Pirio" ***@***.***>, "Author" ***@***.***> 
Envoyé: Vendredi 10 Mars 2023 05:16:35 
Objet: Re: [Macaulay2/M2] Installation ok but Macaulay2 not working [ brew config ] (Issue #2791) 





Could you show the output of brew config ?

**Comment by Lucqk** [comment]
Hi. 
Thank you for considering my request so promptly.
Actually, it works now! 

Yesterday, for some (stupid?) reason,  
I wrote **brew --prefix M2`/bin/M2** instead of **`brew --prefix M2`/bin/M2**,
with the natural consequence that it did not work.

Btw thank you for the job you did in creating this homebrew tap. 
This is a great help for the math community.

Best, Lucqk

**Comment by mahrud** [comment]
Glad it was resolved, and thank you for the kind words!
