### ISSUE TITLE
concatenate rational matrices

### ISSUE THREAD

**Issue by lcrantonh** [Macaulay2/M2#2801]
I am experiencing unexpected behavior with the concatenation operator.  If I take a rational vector and concatenate with an integer I get another rational vector, but if I concatenate a rational vector with a rational number I get an error.
```
i1 : M = matrix {{1/2},{2/3}}

o1 = | 1/2 |
     | 2/3 |

              2        1
o1 : Matrix QQ  <--- QQ

i2 : M || 0

o2 = | 1/2 |
     | 2/3 |
     | 0   |

              3        1
o2 : Matrix QQ  <--- QQ

i3 : M || 3/4
stdio:3:3:(3): error: no method for binary operator || applied to objects:
--            | 1/2 | (of class Matrix)
--            | 2/3 |
--            3
--     ||     - (of class QQ)
--            4
```

**Comment by d-torrance** [comment]
I've just submitted a pull request to add this feature to the next Macaulay2 version (#2802).  In the meantime, here's one way to do it:

```m2
i3 : sub(matrix {{1/2}, {2/3}} || (3/4)_(QQ[]), QQ)

o3 = | 1/2 |
     | 2/3 |
     | 3/4 |

              3        1
o3 : Matrix QQ  <--- QQ
```

**Comment by lcrantonh** [comment]
Great, thanks!  It also works to put the additional entry inside a matrix of its own.
