### ISSUE TITLE
Heft option more restrictive than it used to be

### ISSUE THREAD

**Issue by pzinn** [Macaulay2/M2#2825]
I'm not sure when this got broken:
```
i1 : QQ[a,b,DegreeRank=>2]

o1 = QQ[a..b]

o1 : PolynomialRing

i2 : describe oo

o2 = QQ[a..b, Degrees => {{1}, {0}}, Heft => {2:1}]
                          {0}  {1}

i3 : value oo

stdio:3:1:(3): error: expected Heft option to be a list of integers

```

**Comment by DanGrayson** [comment]
One should use "toExternalString" here instead of "describe".  But even that doesn't fix the problem.  It worked in version 1.11!

**Comment by DanGrayson** [comment]
Probably a one word fix will work --- when process an incoming heft vector, simply apply "splice" to it.

**Comment by pzinn** [comment]
> One should use "toExternalString" here instead of "describe". But even that doesn't fix the problem. It worked in version 1.11!

That's a matter of taste. I'd use `describe` over `externalString` if I'm staying within M2.
Anyway, splicing the heft works, will PR.

**Comment by DanGrayson** [comment]
No, it's not a matter of taste, for "describe" returns a net, and "value" can't be applied to a net.
