### ISSUE TITLE
check User doesn't work

### ISSUE THREAD

**Issue by mahrud** [Macaulay2/M2#2835]
```m2
i1 : TEST ///print 12///

i2 : check User
 -- capturing check(0, "User")                                               -- 0.0430203 seconds elapsed
stdio:2:1:(3): error: file not found on path: "User.m2"
```
Broken due to https://github.com/Macaulay2/M2/commit/c04e5b054533a6b5c5e21b5be43d826ed454ea90, specifically [this line](https://github.com/Macaulay2/M2/commit/c04e5b054533a6b5c5e21b5be43d826ed454ea90#diff-49fb8ae4d6fda9c0bd5c9c3ce9bbf5a2e8062902c586d309d8269aa728a02c64R191).

Note that I patched this in the brew build, so this only fails in other builds.

**Comment by DanGrayson** [comment]
It's not intended to work.  "User" isn't an actual package.

**Comment by mahrud** [comment]
I don't know what you mean by "actual package". It has type `Package`, has dictionaries, you can add documentation and tests for it, and it is returned when you run `package` on any symbol you've defined. What I've written above used to work, and it's useful for many purposes, in this case running quick tests without creating a temporary package and immediately deleting it.
