### ISSUE TITLE
allow linking with gmp instead of mpir

### ISSUE THREAD

**Issue by DanGrayson** [Macaulay2/M2#285]

**Comment by DanGrayson** [comment]
I've started a branch for this work at https://github.com/DanGrayson/M2/tree/use-native-gmp-mfpr-pari

But it's complicated!  Basically, we are forced to let libgmp use malloc instead of continuing to tell it to use GC_malloc, which we need to do so our top level objects get garbage collected.

**Comment by mikestillman** [comment]
I was wondering about this.  For instance, frobby also uses gmp integers, inside of c++ data structure memory which, I think, gc is not aware of (having been called through malloc or new).  For the part of frobby we use, I think it is not an issue, but if we try to use the rest, it is.

This gmp allocation issue has been thorny for a long time!

**Comment by DanGrayson** [comment]
I'm assuming that libgc cannot find thread local storage created with the __thread compiler keyword, but I could be wrong.  Thread safe 3rd party libraries (such as pari) will use this.  (Actually, pari comes in a non-gmp flavor, too.)  So we cannot force them to use GC_malloc.  Also, we can't set the gmp allocation functions on the fly, because that info is stored in global variables.  (Pari sets them on the fly, which makes the gmp version of pari not thread safe, despite what pari documentation says.)

**Comment by DanGrayson** [comment]
In order to maximize the number of native or homebrew-supplied libraries we can use under Mac OS X, it seems we should compile with clang and clang++, to match what the libraries are compiled with.  So I'm trying that now.

**Comment by mikestillman** [comment]
The clang provided with mac is way too old, I think.  Perhaps with the latest Xcode it is OK, but this is a bit of a problem.

**Comment by DanGrayson** [comment]
How do you compare ages of clang?
```
einsteinium$ ~/Downloads/clang+llvm-3.6.1-x86_64-apple-darwin/bin/clang --version
clang version 3.6.1 (tags/RELEASE_361/final)
Target: x86_64-apple-darwin14.1.0
Thread model: posix
einsteinium$ /usr/bin/clang --version
Apple LLVM version 6.0 (clang-600.0.57) (based on LLVM 3.5svn)
Target: x86_64-apple-darwin14.1.0
Thread model: posix

```

**Comment by DanGrayson** [comment]
I think the only way to fix these issue is to stop setting the GMP memory allocation functions (using ```mp_set_memory_functions```) to versions that invoke LIBGC, because we can never be sure that third party libraries will store those pointers in a place where LIBGC can find them.  So now I'm trying to finalize every top level object that contains a pointer to a GMP integer, a GMP rational, or an MPFR real.

**Comment by mikestillman** [comment]
Another option, possibly a bad one, is to use mpn routines at top level (for M2) and do memory allocation ourselves.  mpn routines, I think, do no memory allocation.

How many gmp functions do you/we interface to?

**Comment by DanGrayson** [comment]
I think that won't work, because it's not just us using GMP routines.

**Comment by DanGrayson** [comment]
Hmm, I take that back... let me think about it.

**Comment by mikestillman** [comment]
I was thinking that all engine objects should be finalized too. Then I can avoid (extra) garbage collection issues in the engine.

**Comment by DanGrayson** [comment]
There are lots of engine objects that might contain pointers to GMP
integers.

Another option would be to copy the array of limbs in every GMP integer
returned by 3rd
party routines into memory obtained from GMP and replace the limb pointer.

**Comment by mikestillman** [comment]
Engine objects, once finalized, can have destructors free the gmp integers (and that is done for finalized objects now)

How much would the limb switch slow things down in the front end?  Maybe not so much?

**Comment by DanGrayson** [comment]
It might be too confusing to have GMP integers floating about, some of
which come from
malloc and some of which come from GC_malloc.

**Comment by mikestillman** [comment]
That is true, but what we do now is also very confusing, and we have spent a lot of time trying to get the logic of it right.  And if we can’t modify library code, then we need to change what we do anyway, it seems.

If all of the engine integers in use come from malloc, and all the front end ones come from GC_malloc, we should be ok, as long as when you pass the engine a gmp int, the engine considers it const (which I do now anyway).  And when the engine wants to hand one to the front end, there could be a routine to create one (I think the number of cases for these two is quite small).

**Comment by DanGrayson** [comment]
Well, I think what I'm currently trying is less confusing, because remembering to convert the malloced GMP to the GCmalloced GMP will be difficult.  See https://github.com/DanGrayson/M2/blob/64e2d6129451ee4d496043411b2839d38a688213/M2/Macaulay2/e/x-relem.cpp#L558 , for example.

**Comment by DanGrayson** [comment]
... and https://github.com/DanGrayson/M2/blob/64e2d6129451ee4d496043411b2839d38a688213/M2/Macaulay2/d/interface.dd#L1146 .

**Comment by mikestillman** [comment]
These are exactly the routines that need to be rewritten, if we change to doing gmp both with malloc and GC_malloc.  And it would be easy to do so.  (There are a few more like this, as we do the same for gmp int’s too).

If you want, I can can check for other changes that would be required.

**Comment by mikestillman** [comment]
This is not for 1.8 though.

**Comment by DanGrayson** [comment]
Right, not for 1.8.

I think you don't treat GMP numbers from the engine as read only.  For example, try changint mpz_ptr to mpz_srcptr in
```
const RingElement *IM2_RingElement_from_Integer(const Ring *R, mpz_ptr d)
{
  return RingElement::make_raw(R, R->from_int(d));
}
```

**Comment by DanGrayson** [comment]
Re: "These are exactly the routines that need to be rewritten"

"These"?

**Comment by mikestillman** [comment]
I just checked the "from_int" routines, and they all consider their argument read only.  I am probably using the wrong type, so that changing one type notation to mpz_srcptr can't work, as I would need to change all the locations where from_int is used too.  Perhaps I should do that.

So in fact, none of these functions (the others refer to the "from_rational" functions) would need to be rewritten.

**Comment by DanGrayson** [comment]
That's probably a good idea in any case.  I'll try it.

**Comment by DanGrayson** [comment]
I successfully changed many of your routines to accepting ```mpz_srcptr``` on my branch.

**Comment by DanGrayson** [comment]
Re: "Another option, possibly a bad one, is to use mpn routines at top level (for M2) and do memory allocation ourselves.  mpn routines, I think, do no memory allocation."

The mpfr library uses also mpz routines, and doesn't provide an interface to avoid that.

**Comment by tom111** [comment]
A comment on this thread from the Gentoo packaging perspective: 
The most important issue from a QA and packaging trouble perspective is that Macaulay2 should not ship it's own versions of libraries that are already on the system. Every time you bump the bundled mpir in Macaulay2, I need to backport the general changes that Gentoo does to its system mpir (security things like executable stacks etc) to the bundled version. It's a pain because I need to sneak in the Gentoo patches to mpir into your build system so that they get into Macaulay2's mpir too.

**Comment by DanGrayson** [comment]
I wasn't aware that mpir executes code on the stack, but, in any case, it would be worthwhile to make progress on this issue -- I'll keep trying.  I hope it doesn't involve too much of a performance hit.

By the way, it's sort of silly to worry about whether M2's stack is executable: much more troubling is the possibility that M2 code will evaluate user data from the internet as M2 code using "value".

**Comment by tom111** [comment]
I agree about the security implications of "value" and the sillyness. The QA in Gentoo is to a certain extend defined by "what can be checked automatically on a distribution scale". For each individual package you can always find different attack vectors. Hardening is hard!

**Comment by DanGrayson** [comment]
See also https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=439888

**Comment by dimpase** [comment]
Would it be easier to package MPIR for Debian (with patches you need...)?
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=708391

**Comment by d-torrance** [comment]
This was my original thought.  But a number of libraries which M2 uses also use gmp themselves, and we don't want gmp and mpir alongside each other.

See [1] for my discussion about this on the mpir developer list.

**Comment by dimpase** [comment]
@d-torrance : I am not aware of any library that must use "real" GMP instead of MPIR. At least with Sage we have a number of such "GMP" dependencies which all are nicely served by MPIR.

**Comment by d-torrance** [comment]
The main issue with packaging M2 for Debian is that we need to use the Debian packages of all the libraries which M2 uses.

While these libraries absolutely can be built against mpir, the Debian packages are currently built against gmp.

**Comment by dimpase** [comment]
Right. Well, one can create versions of the corresponding Debian packages built against MPIR. That's a bit of work, but not hard, in comparison with these tricky GC-related issues.

**Comment by xtaran** [comment]
> Well, one can create versions of the corresponding Debian packages built against MPIR. That's a bit of work, but not hard, [...]

That might work for inoffical packages, but I doubt that the effort to provide two binary versions of multiple libraries is welcome at Debian. It would also involve quite a lot of people who all must agree that it's worth it.  So I don't consider that to be a real option.

**Comment by DanGrayson** [comment]
The only patch we do to MPIR is to disable the routines that are called to set the memory allocation functions.  The only reason we do that is that other third party libraries call them.  But probably the right way to fix that is to insist that no library set the memory allocation functions, on the theory that the choice of memory allocation routines should be left to the author of the top level program (unfortunately, there is no portable way of setting those routines before static initializers are called).  Perhaps PARI is the only offender, and the authors of it would be willing to accept a patch.

**Comment by dimpase** [comment]
@xtaran : distributions routinely provide things built against different libraries with similar functionality (e.g. think about numerous numerical linear algebra libs); I don't see why inclusion of MPIR would be met with resistance. MPIR is mature and popular enough.

**Comment by d-torrance** [comment]
Even if Debian did include mpir, I don't think using the Macaulay2 patched version would be ideal, as other applications built using mpir might want to set the memory functions.  So we'd have the same problem as gmp.

**Comment by d-torrance** [comment]
I've sent a note about this issue to the pari dev mailing list.  [1]  Maybe that will solve it!

[1] http://pari.math.u-bordeaux.fr/archives/pari-dev-1605/msg00003.html

**Comment by dimpase** [comment]
@d-torrance : I presume the MPIR patch can be converted in a proper runtime feature, that can be accepted by upstream.

**Comment by d-torrance** [comment]
I got a nice quick reply from the pari devs [1]!  Basically, they propose adding an additional flag which could be passed to pari_init_opts() which would skip the kernel initialization (and thus skip overwriting the gmp memory functions).

[1] http://pari.math.u-bordeaux.fr/archives/pari-dev-1605/msg00004.html

**Comment by d-torrance** [comment]
I got another response from the pari devs [1].  They suggest a wrapper around the call to pari_init_opts() saving the gmp memory functions.

I'll play around with this and see if it works for the Debian package.  If so, I'll submit a pull request.

[1] http://pari.math.u-bordeaux.fr/archives/pari-dev-1605/msg00005.html

**Comment by dimpase** [comment]
Actually, the PARI devs bring up their [#1317](http://pari.math.u-bordeaux.fr/cgi-bin/bugreport.cgi?bug=1317) which had to do with an analogous issue with Sagemath using PARI and MPIR at the same time.
There is a Sage ticket [#15774](http://trac.sagemath.org/ticket/15774) where the patch akin to the current M2's MPIR patch (well, the patch was for PARI rather than for MPIR, but it served the same purpose) has been removed.

This suggest that M2 could use an analogous wrapper around PARI initialisation to achieve the same effect, and remove MPIR patch.

**Comment by dimpase** [comment]
here is what Sage does (not a wrapper, in fact): right after calling `pari_init_opts()` (which does call `mp_set_memory_functions()`), it calls `mp_set_memory_functions()` itself, passing the needed  MPIR the right memory handling functions to use. 

In the M2 case, I guess that the function to free memory should not do anything.

**Comment by dimpase** [comment]
f6e2f61535dfb8149abd8eaae772cbfb8bf9f653 at https://github.com/DanGrayson/M2/ is Dan's implementation of this for M2, and it actually works!

**Comment by DanGrayson** [comment]
Oops, I removed that branch from DanGrayson/M2 and put it on Macaulay2/M2, see https://github.com/Macaulay2/M2/tree/try-not-patching-mpir -- it's progressed a bit since then.  There are bugs, though.

**Comment by dimpase** [comment]
By "bugs" do you mean the same sort of memory errors, i.e. more libraries do mess around with MPIR/GMP memory allocators? Or is it something else?

**Comment by DanGrayson** [comment]
We're getting many calls to "abort()" from "free()" complaining about pointers to memory not obtained with "malloc()".  It happens inside ntl.

**Comment by dimpase** [comment]
Sage applies the following patch to NTL: https://github.com/sagemath/sage/blob/master/build/pkgs/ntl/patches/new_singular.patch

(replacing `new (std::nothrow)` with `new` in NTL's smart pointer class)

Without this, Sage gets a problem with (lib)Singular...

**Comment by DanGrayson** [comment]
That can't be it, because the calls to abort() stop happening if I strip M2-binary.

**Comment by dimpase** [comment]
I will be at the workshop around 10am, hope to have a closer look then.

**Comment by d-torrance** [comment]
A possible update:

I finally got around to sending a backtrace to the PARI devs of where the M2 build fails when using the Debian GMP package, and they replied saying that there was a possible bug in PARI [1].  I tried building M2 again after making a small change in the PARI code, and it worked!

(Well, for a moment.  Then I ran into #460...)

[1] https://pari.math.u-bordeaux.fr/archives/pari-dev-1706/msg00010.html

**Comment by mahrud** [comment]
Is this resolved now?

**Comment by dimpase** [comment]
@d-torrance should know all about it, I believe.

**Comment by d-torrance** [comment]
Yes, linking with gmp works beautifully now!
