### ISSUE TITLE
Slowdown in map(Module,Module,Matrix) on v1.22

### ISSUE THREAD

**Issue by mahrud** [Macaulay2/M2#2898]
Comparing `map(Module,Module,RawMatrix)`:
https://github.com/Macaulay2/M2/blob/5572c8a245d187f6c22f8eaa0b03cac0b8d86e02/M2/Macaulay2/m2/matrix.m2#L19-L31
and `map(Module,Module,Matrix)`:
https://github.com/Macaulay2/M2/blob/5572c8a245d187f6c22f8eaa0b03cac0b8d86e02/M2/Macaulay2/m2/matrix1.m2#L76-L87

Note that the first one only calls `rawMatrixRemake2(...)` but the second calls `reduce(M, rawMatrixRemake2(...))`.

I ran into an example of a 96x1 matrix `B` where `B_{0}` (yes, the whole matrix) was instantaneous in v1.21 but taking a full minute in v1.22 because of this extra `reduce`.

My question is:
1. Why are the two methods above different? Can we not just use this?
```m2
map(Module,Module,Matrix) := Matrix => o -> (M,N,f) -> map(M, N, raw f, o)
```
2. If they are actually different, can we safely remove the `reduce`?

**Comment by DanGrayson** [comment]
The reduce is present so that equality comparisons of matrices will work.  We have to add it to the first method, also.

**Comment by mahrud** [comment]
Perhaps == should call reduce. Why should changing the target of a module induce a groebner basis computation?
