### ISSUE TITLE
Macauly on Mac

### ISSUE THREAD

**Issue by adlin83539** [Macaulay2/M2#2903]
I try to download macaulay through homebrew in my Mac using my terminal. Home installs just fine but when I run the code to download macaulay it was fails. And I can understand why it does. If someone had this same problem and could help that would be amazing.

**Comment by trevorkarn** [comment]
@adlin83539 Are you having problems with icu4c?

**Comment by mahrud** [comment]
If either of you are still running into problems, please open an issue on the [Macaulay2/homebrew-tap](https://github.com/Macaulay2/homebrew-tap) repository, making sure to include the output of `brew config` and `brew doctor` in your report.
