### ISSUE TITLE
Printing a Resolution Within a Function Affects Which Keys Are Returned

### ISSUE THREAD

**Issue by David-GW** [Macaulay2/M2#2910]
Running
```
R=ZZ/2[x];
testFunction=M->(
    FR:=res M;
    return keys FR;
);
testFunction R^1
```
returns `{Resolution, dd, ring, cache}`, however
```
R=ZZ/2[x];
testFunction=M->(
    FR:=res M;
    print FR;
    return keys FR;
);
testFunction R^1
```
returns `{0, 1, complete, Resolution, ring, dd, cache}` after printing the resolution.

This is using version 1.22, and also occurs on the web interface.

**Comment by DanGrayson** [comment]
That's the expected behavior.  If a resolution is created by the engine, then we lazily import the free modules and homomorphisms from the engine to the front end.
