### ISSUE TITLE
Building fails on ForeignFunctions examples on Fedora 38

### ISSUE THREAD

**Issue by QMeqGR** [Macaulay2/M2#2919]
Building on Fedora 38. Make fails when it gets to ForeignFunctions examples. 
(building version 1.22)

...
make[2]: Entering directory '/home/packages/SOURCE/M2/M2/Macaulay2/man'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/packages/SOURCE/M2/M2/Macaulay2/man'
make -C packages all 
make[2]: Entering directory '/home/packages/SOURCE/M2/M2/Macaulay2/packages'
: installing package ForeignFunctions
/usr/bin/install -c -d ForeignFunctions-temporary
make: Entering directory `/home/packages/SOURCE/M2/M2/Macaulay2/packages/ForeignFunctions-temporary'
cd ForeignFunctions-temporary && /home/packages/SOURCE/M2/M2/usr-dist/x86_64-Linux-Fedora-38/bin/M2  -q --stop --silent --no-preload -e errorDepth=0 -e debugLevel=0  -e "installPackage(\"ForeignFunctions\", MakeDocumentation => true, MakeHTML => true, MakeInfo => true, MakePDF => false, RemakeAllDocumentation => false, IgnoreExampleErrors => false, RerunExamples => false, CheckDocumentation => true, UserMode => false, Verbose => false, InstallPrefix => \"/home/packages/SOURCE/M2/M2/usr-dist/\", SeparateExec => true, DebuggingMode => true); exit 0"
 -- making example results for "foreignSymbol"                              
 ulimit -c unlimited; ulimit -t 700; ulimit -m 850000; ulimit -s 8192; ulimit -n 512;  cd /tmp/M2-306513-0/1-rundir/; GC_MAXIMUM_HEAP_SIZE=400M "/home/packages/SOURCE/M2/M2/usr-dist/x86_64-Linux-Fedora-38/bin/M2-binary" -q --no-randomize --no-readline --silent --stop --print-width 77 -e 'needsPackage("ForeignFunctions",Reload=>true,FileName=>"/home/packages/SOURCE/M2/M2/Macaulay2/packages/ForeignFunctions.m2")' <"/tmp/M2-306513-0/0_foreign__Symbol.m2" >>"/home/packages/SOURCE/M2/M2/usr-dist/common/share/doc/Macaulay2/ForeignFunctions/example-output/_foreign__Symbol.errors" 2>&1
/home/packages/SOURCE/M2/M2/usr-dist/common/share/doc/Macaulay2/ForeignFunctions/example-output/_foreign__Symbol.errors:0:1:(3):[12]: (output file) error: Macaulay2 exited with status code 1
/tmp/M2-306513-0/0_foreign__Symbol.m2:0:1: (input file)
M2: *** Error 1
 -- 0.409486 seconds elapsed
../../m2/debugging.m2:18:6:(1):[9]: error: installPackage: 1 error(s) occurred running examples for package ForeignFunctions
../../m2/installPackage.m2:729:18:(1):[8]: --back trace--
../../m2/methods.m2:154:80:(1):[7]: --back trace--
../../m2/option.m2:17:8:(1):[6]: --back trace--
../../m2/installPackage.m2:607:5:(1):[5]: --back trace--
../../m2/methods.m2:154:80:(1):[4]: --back trace--
../../m2/option.m2:17:8:(1):[3]: --back trace--
currentString:1:1:(3):[2]: --back trace--
../../m2/startup.m2.in:562:33:(0):[1]: --back trace--
../../m2/startup.m2.in:662:6:(0): --back trace--
make[2]: *** [Makefile:106: /home/packages/SOURCE/M2/M2/usr-dist/x86_64-Linux-Fedora-38/lib64/Macaulay2/ForeignFunctions/.installed] Error 1
make[2]: Leaving directory '/home/packages/SOURCE/M2/M2/Macaulay2/packages'
make[1]: *** [Makefile:15: all-in-packages] Error 2
make[1]: Leaving directory '/home/packages/SOURCE/M2/M2/Macaulay2'
make: *** [GNUmakefile:251: all-in-Macaulay2] Error 2

**Comment by d-torrance** [comment]
Would you please share the contents of the file `/home/packages/SOURCE/M2/M2/usr-dist/common/share/doc/Macaulay2/ForeignFunctions/example-output/_foreign__Symbol.errors`?

**Comment by QMeqGR** [comment]
Yes, thank you.

cat /home/packages/SOURCE/M2/M2/usr-dist/common/share/doc/Macaulay2/ForeignFunctions/example-output/_foreign__Symbol.errors
-- -*- M2-comint -*- hash: 180350256

i1 : mps = openSharedLibrary "mps"

o1 = mps

o1 : SharedLibrary

i2 : cplxT = foreignStructType("cplx_t", {"r" => double, "i" => double})

o2 = cplx_t

o2 : ForeignStructType

i3 : foreignSymbol(mps, "cplx_i", cplxT)

o3 = HashTable{"i" => 1}
               "r" => 0

o3 : ForeignObject of type cplx_t

i4 : foreignSymbol("cplx_i", cplxT)
stdio:4:1:(3): error: /home/packages/SOURCE/M2/M2/usr-dist/x86_64-Linux-Fedora-38/bin/M2-binary: undefined symbol: cplx_i

**Comment by d-torrance** [comment]
Thanks!  I *think* that the problem may be that `libmps` is statically linked instead of dynamically linked to the Macaulay2 binary, so it can't find the `clpx_i` symbol for that example.  What does the following give you?

```
ldd /home/packages/SOURCE/M2/M2/usr-dist/x86_64-Linux-Fedora-38/bin/M2-binary | grep libmps
```

**Comment by QMeqGR** [comment]
OK, I think I need to rebuild from scratch. The original error message was that it couldn't find libmps.so, so I installed it and just tried to restart make. So I probably need to run 'configure' again and rebuild. Let me try that and I'll let you know if I still get a build error. Thanks again!

**Comment by QMeqGR** [comment]
After installing libmps everything builds without error. Thanks.

**Comment by gadnuk** [comment]
> Thanks! I _think_ that the problem may be that `libmps` is statically linked instead of dynamically linked to the Macaulay2 binary, so it can't find the `clpx_i` symbol for that example. What does the following give you?
> 
> ```
> ldd /home/packages/SOURCE/M2/M2/usr-dist/x86_64-Linux-Fedora-38/bin/M2-binary | grep libmps
> ```

I think I'm getting this same problem in archlinux, but haven't been able to fix it by simply rebuilding mpsolve.
I believe the problem may be the one you mentioned since I see libmps.a and not libmps.so in my build directory.

**Comment by d-torrance** [comment]
Did you build mpsolve (as part of the M2 build process) or are you using the arch package (https://aur.archlinux.org/packages/mpsolve)?

**Comment by gadnuk** [comment]
> Did you build mpsolve (as part of the M2 build process) or are you using the arch package (https://aur.archlinux.org/packages/mpsolve)?



> Did you build mpsolve (as part of the M2 build process) or are you using the arch package (https://aur.archlinux.org/packages/mpsolve)?



> Did you build mpsolve (as part of the M2 build process) or are you using the arch package (https://aur.archlinux.org/packages/mpsolve)?

I was able to solve the issue by setting the BUILD_SHARED_LIBS variable to ON when building mpsolve. I was building mpsolve as part of the M2 building process with ninja.
