### ISSUE TITLE
CentOS 7.9, non-root, source (1.22) build possible?

### ISSUE THREAD

**Issue by hpcpony** [Macaulay2/M2#2936]
I've been trying to build from source (git clone of 1.22) and running into problem after problem.  They all seem to be build related (as opposed to gcc, autotools version, etc...)  

Fixing little things here and there as the 'make' crashes I've gotten as far as the following:

```
checking for GIVARO usability... no
configure: error: The Givaro library could not be used with the compiler and the flags set up by the configure script
make: *** [submodules/fflas_ffpack/Makefile] Error 1
```

At this point I think it's worth asking whether what I'm attempting is even possible.  If I can get an existence proof from somebody (and may some hints) I'll keep at it, but otherwise I might as well move on.

Thanks.

**Comment by d-torrance** [comment]
I don't have any experience building Macaulay2 on CentOS or any other rpm-based distributions, but perhaps you can get some insight from the .spec file used by the maintainer of the Fedora package?

https://src.fedoraproject.org/rpms/Macaulay2/tree/rawhide

**Comment by hpcpony** [comment]
Thanks.  Based on what I saw in the .spec file it looks like building from source is not a trivial endeavor.  For now I'll have to move on.

**Comment by mahrud** [comment]
Did you try using the [CMake](https://github.com/Macaulay2/M2/blob/master/M2/INSTALL-CMake.md) build? Both @pzinn and myself use this to build from source on Fedora. I've also used it to build on CentOS and Ubuntu LTS servers.

**Comment by hpcpony** [comment]
I looked at it but I don't have all the prerequisite packages and the sysadmins are reluctant to add a bunch of stuff.  It's on my list to revisit, but I'm not sure when I'll get to it.
