### ISSUE TITLE
Logic for deciding if a GB algorithm applies is incomplete

### ISSUE THREAD

**Issue by mikestillman** [Macaulay2/M2#294]
In m2/gb.m2, we need to make the following tests for correctness:

If the base ring is ZZ (ultimately), then the only allowed algorithm is “Inhomogeneous”
If the monomial order is a local order (even in a coefficient ring), then the algorithm must be “Inhomogeneous”
BUT: if both of these hold, then a “not implemented yet” error should be given.

(the “Inhomogeneous" algorithm is the only one to be able to handle the base being ZZ, or having local rings).  Actually, the GB routine itself can handle it, but my minimalization algorithm isn’t designed for that case (yet).

I can change this in the engine, but the front end is probably where these checks should be.

**Comment by mikestillman** [comment]
Some examples:
```
A = ZZ/5[a,b,c,MonomialOrder=>RevLex,Global=>false]
B = A[x,y,z] -- How do we tell that this has a local term order?  (monoid B).Options.Global is true
gens gb matrix{{a*x, a-a^2}} -- works, as it should

C = ZZ[d,e,f]
I = ideal(3*d-2, 5*e-1)
gens gb(I, Algorithm=>Homogeneous2)  -- should fail, and it does
gens gb(ideal(3*d-2*e, 4*d-f), Algorithm=>Homogeneous2) -- should fail
gens gb(ideal(a^2-b^2, a*b), Algorithm=>Homogeneous2) -- should fail too

D = ZZ[g,h,MonomialOrder=>RevLex,Global=>false]
gens gb ideal(3*g,5*h) -- should fail? GB can be computed, but it hangs when trying to minimize it.
```

**Comment by DanGrayson** [comment]
I did nothing about the case in the last line of your sample code.

**Comment by mikestillman** [comment]
I think that your changes don't quite work.  In fact, there are 90 errors in building examples!

The problem appears to be related to looking for FlatMonoid in QQ, which isn't a key (or least that was one of the errors).

**Comment by mikestillman** [comment]
Oops, my bad, you fixed it already.
