### ISSUE TITLE
gftables

### ISSUE THREAD

**Issue by DanGrayson** [Macaulay2/M2#295]
The gftables seem to be included in factory, so we shouldn't need to have a separate library for installing them.  The only problem is getting them installed in the right place at the right time.

```
$ find usr* -name 961
usr-dist/common/share/Macaulay2/Core/factory/gftables/961
usr-host/share/factory/gftables/961
```

**Comment by mahrud** [comment]
Closing this, since #377 seems to have fixed it. Please reopen if that's incorrect.
