### ISSUE TITLE
Ambiguous printing of matrices over fraction fields

### ISSUE THREAD

**Issue by d-torrance** [Macaulay2/M2#2952]
For example:

```m2
i1 : R = frac(QQ[x])

o1 = R

o1 : FractionField

i2 : matrix {{1/(2*x)}}

o2 = | 1/2x |

             1       1
o2 : Matrix R  <--- R
```

It's not clear if that means $\dfrac{1}{2x}$ or $\dfrac{1}{2}x$.  It should probably print `1/(2x)` instead.

**Comment by pzinn** [comment]
This is intentional. with `compactMatrixForm=true`, the display is intentionally the shortest possible, for example one also has
```
i7 : matrix{{x^2}}

o7 = | x2 |
```
which is not proper mathematical notation either.

**Comment by d-torrance** [comment]
Yeah, good point.  It turns out that it's not as ambiguous as I originally thought, as long as you understand M2's printing rules.  In the case of $\dfrac{1}{2}x$, the $x$ gets moved to the numerator:

```m2
i2 : matrix{{1/2*x}}

o2 = | x/2 |

             1       1
o2 : Matrix R  <--- R
```

I'll close this.
