### ISSUE TITLE
fork() and temporaryFileName()s

### ISSUE THREAD

**Issue by bapike** [Macaulay2/M2#296]
The `fork()` function does not change the temporary directory used in `temporaryFileName()`, for either the parent or child.

One consequence is that this code does not do what I expect, namely, pass the answer from a calculation back to the parent:
```
f=rootPath|temporaryFileName();
t=fork();
if (t==0) then (
  -- Is the child
  stdio<<"Sample temporaryFileName for child="<<temporaryFileName()<<endl;
  calculation=1+1;
  f<<calculation<<close;
  exit(0); -- This will delete all files in the temporary directory!
) else (
  -- is the parent
  stdio<<"Sample temporaryFileName for parent="<<temporaryFileName()<<endl;
  wait(t);
  answer=value get(f); -- The file does not exist!
);
```
(This also exhibits that there could quite easily be clashes between `temporaryFileName()`s in parent and child.)

As another test, when the child exits, any temporary files that were created by the parent will be deleted without the parent's knowledge (consequently, a `restart` may be needed before running this example):
```
f=rootPath|temporaryFileName();
f<<toString(1)<<close;
t=fork();
if (t==0) then (
  -- Is the child
  exit(0); -- This will delete all files in the temporary directory!
) else (
  -- is the parent
  wait(t);
  answer=value get(f); -- The file does not exist!
);
```
In fact, the whole temporary directory will be deleted, so that creation of temporary files in the parent will fail (another `restart` may be needed here):
```
f=rootPath|temporaryFileName();
t=fork();
if (t==0) then (
  -- Is the child
  exit(0); -- This will delete all files in the temporary directory!
) else (
  -- is the parent
  wait(t);
  g=rootPath|temporaryFileName();
  g<<"Test"<<close; -- Fail because directory was deleted
);
```

I propose that fork() should change the temporary directory of the child (if it has been chosen), and that this should be more clearly documented.  I am happy to do this work.

**Comment by DanGrayson** [comment]
Probably the right way to fix it is simply to invalidate the cached result of the computation of the temporary directory name in the variable ```temporaryDirectoryName``` in the file ```m2/files.m2``` when it is detected that ```processID()``` gives a different result than it did before.  That's better than changing ```fork```, which is designed to be as close as possible to the unix system call.

I'd be happy for you to do the work and submit a pull request.
