### ISSUE TITLE
cohomCalg can't be downloaded

### ISSUE THREAD

**Issue by dimpase** [Macaulay2/M2#2963]
While trying to build the latest development branch, I get
```
-- Using src='https://faculty.math.illinois.edu/Macaulay2/Downloads/OtherSourceCode/cohomCalg-0.32.tar.gz'
-- Retry after 60 seconds (attempt #5) ...
-- Using src='https://faculty.math.illinois.edu/Macaulay2/Downloads/OtherSourceCode/cohomCalg-0.32.tar.gz'
CMake Error at src/build-cohomcalg-stamp/download-build-cohomcalg.cmake:170 (message):
  Each download failed!

    error: downloading 'https://faculty.math.illinois.edu/Macaulay2/Downloads/OtherSourceCode/cohomCalg-0.32.tar.gz' failed
          status_code: 7
          status_string: "Couldn't connect to server"
          log:
          --- LOG BEGIN ---
            Trying 128.174.199.46:443...

  connect to 128.174.199.46 port 443 failed: Connection refused

  Failed to connect to faculty.math.illinois.edu port 443 after 236 ms:
  Couldn't connect to server
```
And also 
```
$  wget https://faculty.math.illinois.edu/Macaulay2/Downloads/OtherSourceCode/cohomCalg-0.32.tar.gz
Resolving faculty.math.illinois.edu... 128.174.199.46
Connecting to faculty.math.illinois.edu|128.174.199.46|:443... failed: Connection refused.
```

Is this the same tarfile as on GitHub: https://github.com/BenjaminJurke/cohomCalg/releases/tag/v0.32 ?

The latter is probably a safer URL to use.

**Comment by d-torrance** [comment]
All the `faculty.math.illinois.edu` URL's have been broken for a month or two and won't be replaced.  Everything has been moved over to `macaulay2.com`.

I'm not very familiar with the cmake build, but I think this line is causing the problem:
https://github.com/Macaulay2/M2/blob/ad69301082ce85fe06b1759bc793a08a7682c4a7/M2/cmake/build-libraries.cmake#L13

Replacing the URL with https://macaulay2.com/Downloads/OtherSourceCode/ should do the trick.
