### ISSUE TITLE
Graphs with vertices from different classes lead to errors

### ISSUE THREAD

**Issue by windisch** [Macaulay2/M2#297]
Constructing graphs with vertices from different classes leads to errors in all methods from Graphs.m2 where the `==` operator is needed. For example,

``` 
i1 : G=graph({{1,2},{a,b}})

o1 = Graph{1 => {2}}
           2 => {1}
           a => {b}
           b => {a}

o1 : Graph

i2 : connectedComponents G
Graphs.m2:1049:39:(3):[6]: error: no method for binary operator == applied to objects:
--            1 (of class ZZ)
--     ==     a (of class Symbol)
Graphs.m2:1049:39:(3):[6]: --entering debugger (type help to see debugger commands)
Graphs.m2:1049:37-1049:42: --source code:
    i := position(vertexSet G, u -> u == v);
```
Is it possible to treat elements from `ZZ` or `RR` as symbols? Otherwise I think it should be forbidden (in the constructor) to construct graphs of this type.

**Comment by moorewf** [comment]
This just means that the === comparison operator should have been used
instead, probably.

On Mon, Jun 8, 2015 at 5:08 PM, Tobias Windisch <notifications@github.com>
wrote:

> Constructing graphs with vertices from different classes lead to errors in
> all methods from Graphs.m2 where the == operator is needed. For example,
>
> i1 : G=graph({{1,2},{a,b}})
>
> o1 = Graph{1 => {2}}
>            2 => {1}
>            a => {b}
>            b => {a}
>
> o1 : Graph
>
> i2 : connectedComponents G
> Graphs.m2:1049:39:(3):[6]: error: no method for binary operator == applied to objects:
> --            1 (of class ZZ)
> --     ==     a (of class Symbol)
> Graphs.m2:1049:39:(3):[6]: --entering debugger (type help to see debugger commands)
> Graphs.m2:1049:37-1049:42: --source code:
>     i := position(vertexSet G, u -> u == v);
>
> Is it possible to treat elements from ZZ or RR as symbols? Otherwise I
> think it should be forbidden (in the constructor) to construct graphs of
> this type.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Macaulay2/M2/issues/297>.
>



-- 
Dr. W. Frank Moore
Assistant Professor
Department of Mathematics, Wake Forest University

email: moorewf@wfu.edu

**Comment by DanGrayson** [comment]
Yes, this line needs to be changed:
```
    i := position(vertexSet G, u -> u == v);
```

**Comment by windisch** [comment]
I fixed more occurrences of this issue in b6ab87818d8e8c8064b7a4592cfb7df54284e0a1. Could you please verify my fix in 5e2d2f5fb6f2af23bfec4e16d9a49bbd26d8185f? I don't know if replacing `sort` by making sets is the smartest and  most efficient thing to do.

**Comment by DanGrayson** [comment]
I'm confused: those two commits of yours seem to be in our repository, but they aren't really.  What's going on?

**Comment by DanGrayson** [comment]
Maybe github refers any commit number in a URL to any fork that has it?

**Comment by DanGrayson** [comment]
It's much easier for me to verify changes if they are in a pull request.  Why not just make one with a comment that David Cook should approve it first?

**Comment by windisch** [comment]
I was also surprised that my commit appears here, sorry for that. To what is github refering if my fork has an issue with exactly the same number?

**Comment by DanGrayson** [comment]
No need to apologize, it must be an secret feature of github.
