### ISSUE TITLE
A bug about freeAlgebra

### ISSUE THREAD

**Issue by wp-hhh** [Macaulay2/M2#3019]
I am learning Macaulay2 now. When I try to use the method "freeAlgebra(QQ,{x,y,z})" to create a free algebra as shown in the example of the documentation, where the example is in the website, "https://macaulay2.com/doc/Macaulay2/share/doc/Macaulay2/AssociativeAlgebras/html/_free__Algebra.html", I get a mistake as shown in the fig.1.  When I try to use it online, I also get the mistake as shown in the fig.2. Do I do something wrong or are there some bugs in the method "freeAlgebra"?
![fig.1](https://github.com/Macaulay2/M2/assets/102017612/e8688ad5-1fa4-477c-9e27-4899e2db51ac)
![fig.2](https://github.com/Macaulay2/M2/assets/102017612/df98a593-1848-40dc-95f5-765abb39472b)

**Comment by moorewf** [comment]
You need to run the command

needsPackage “AssociativeAlgebras”

before using any of the noncommutative functionality.

Best,
Frank

**Comment by wp-hhh** [comment]
OK, I solved it by your advice. 

Thanks.
