### ISSUE TITLE
lcm(0_QQ,0_QQ)

### ISSUE THREAD

**Issue by pzinn** [Macaulay2/M2#3061]
what is the expected behaviour of `lcm` and `gcd` when applied to rational numbers? in any case, this doesn't seem right:
```
i1 : lcm(0,0)

o1 = 0

i2 : lcm(0_QQ,0_QQ)
stdio:2:3:(3): error: division by zero
```

**Comment by d-torrance** [comment]
I'm surprised that `lcm(0,0)` works:

```m2
i1 : code (lcm, ZZ, ZZ)

o1 = -- code for method: lcm(ZZ,ZZ)
     M2/Macaulay2/m2/integers.m2:61:20-61:47: --source code:
     lcm(ZZ,ZZ) := (f,g) -> abs f * (abs g // gcd(f,g))
```

So we're computing `0 // 0`, which seems like it should raise an error, but it doesn't:

```
i2 : 0 // 0

o2 = 0
```
