### ISSUE TITLE
Use of Python.m2

### ISSUE THREAD

**Issue by sommars** [Macaulay2/M2#307]
When I try to loadPackage "Python", the following list of errors are thrown that seem to be related to exportFrom_Core and the package doesn't load.
```
/usr/local/share/Macaulay2/Core/packages.m2:292:116:(1):[9]: error: key not found in dictionary
/usr/local/share/Macaulay2/Core/classes.m2:45:52:(1):[8]: --back trace--
/usr/local/share/Macaulay2/Core/packages.m2:292:120:(1):[7]: --back trace--
Python.m2:3:11:(2):[5]: --back trace--
/usr/local/share/Macaulay2/Core/setup.m2:111:27:(1):[5]: --entering debugger (type help to see debugger commands)
/usr/local/share/Macaulay2/Core/setup.m2:111:27-111:35: --source code:
                    ret = loadfun fullfilename;
```

**Comment by DanGrayson** [comment]
That's an experiment with running Sage inside Macaulay2, but we don't maintain it.  If you want to try it out, you will have to build Macaulay2 from source code and add --with-python to the configure script command line.

**Comment by dimpase** [comment]
Looks like we need to resurrect the M2 package of Sage, if only  just to maintain the symmetry :-)
