### ISSUE TITLE
Cmake minimum version?

### ISSUE THREAD

**Issue by jkyang92** [Macaulay2/M2#3075]
`build-libraries.cmake` has `cmake_policy(SET CMP0135 NEW)`, which only works for cmake >=3.24, on the other hand, `cmake_minimum_version` is set to 3.15. A minor annoyance with simply updating `cmake_minimum_version` is that Ubuntu's current LTS only has cmake 3.22

**Comment by mahrud** [comment]
It's silly that CMake can't just silently ignore non-existent policies ...
I've just been commenting that line on older systems, but probably the simplest solution is to add a version check before the `cmake_policy` line and I'm fine if you want to do that.

**Comment by mahrud** [comment]
(Will be) fixed by #3373.
