### ISSUE TITLE
Inconsistent "installMethod" error messages

### ISSUE THREAD

**Issue by d-torrance** [Macaulay2/M2#3076]
Sometimes, we get an error when trying to install a method with the wrong number of arguments, which is good:

```m2
i1 : foo = method()

o1 = foo

o1 : MethodFunction

i2 : foo Thing := () -> null
stdio:2:11:(3): error: expected method for unary operator to be a function of 1 variable
```

But it doesn't always work like this.  One would expect the following to all raise errors, but they don't:

```m2
i3 : installMethod(foo, x -> null)

o3 = FunctionClosure[stdio:3:21-3:24]

o3 : FunctionClosure

i4 : foo(Thing, Thing) := x -> null

o4 = FunctionClosure[stdio:4:23-4:26]

o4 : FunctionClosure

i5 : foo(Thing, Thing, Thing) := x -> null

o5 = FunctionClosure[stdio:5:30-5:33]

o5 : FunctionClosure
```

**Comment by DanGrayson** [comment]
```
i1 : (x->x)(a,b)

o1 = (a, b)

o1 : Sequence
```

**Comment by d-torrance** [comment]
Just to make sure I understand the comment -- 1-argument functions can be installed regardless of the number of expected arguments because the caller can just pass a sequence with (hopefully) the correct number of arguments?

Is this necessary so that we can allow non-`FunctionClosure` functions as methods? Now that I think of it, all `CompiledFunction`'s take a single `Expr`, which will be a sequence when we have anything but 1 argument.

**Comment by DanGrayson** [comment]
```
i1 : ((x)->x)(a,b)
stdio:1:5:(3): error: expected 1 argument, but got 2
```

**Comment by d-torrance** [comment]
Wait, so what's the difference between `x -> x` and `(x) -> x`?   The former allows `x` to be a sequence, but the latter unpacks any sequence into distinct arguments?  Is this documented anywhere?

**Comment by d-torrance** [comment]
Ah, I found the documentation! 
 https://macaulay2.com/doc/Macaulay2/share/doc/Macaulay2/Macaulay2Doc/html/_making_spfunctions_spwith_spa_spvariable_spnumber_spof_sparguments.html

> As an aside, we reveal that there is a way to define a function of one argument that will signal an error if it's given more than one argument: put parentheses around the single parameter in the definition of the function.

I'll close this, since I think everything is working as intended.
