### ISSUE TITLE
induced maps between chain complexes

### ISSUE THREAD

**Issue by DanGrayson** [Macaulay2/M2#308]
More methods for chain complexes, analogous to those for modules, might be useful:

```

i4 : methods inducedMap

o4 = {(inducedMap, ChainComplex, ChainComplex)}
     {(inducedMap, Module, Module)            }
     {(inducedMap, Module, Module, Matrix)    }
     {(inducedMap, Module, Nothing, Matrix)   }
     {(inducedMap, Nothing, Module, Matrix)   }
     {(inducedMap, Nothing, Nothing, Matrix)  }

```

Do the same for the maps mentioned in https://github.com/Macaulay2/M2/issues/254 .

**Comment by DanGrayson** [comment]
Some of this might be provided by Mike and Greg when they finish their work on chain complexes.

**Comment by ggsmith** [comment]
Yes, these methods and several more are already part of the Complexes package.

**Comment by mikestillman** [comment]
Closing this issue, see instead #254
