### ISSUE TITLE
Concepts library requires C++20, not supported in older compilers

### ISSUE THREAD

**Issue by d-torrance** [Macaulay2/M2#3130]
After #3127, the new file [M2/Macaulay2/e/PolynomialStream.hpp](https://github.com/Macaulay2/M2/blob/development/M2/Macaulay2/e/PolynomialStream.hpp) includes the following line:

```c++
#include <concepts>
```

The [concepts library](https://en.cppreference.com/w/cpp/concepts) was added in C++20, which apparently wasn't supported until [GCC 10](https://gcc.gnu.org/projects/cxx-status.html#cxx20).

**Comment by moorewf** [comment]
@mikestillman I thought we had removed this from our pull request...

**Comment by mikestillman** [comment]
@moorewf I thought so too, maybe I missed one call, but then I would have thought it would not have compiled...

**Comment by mikestillman** [comment]
Although we commented out use of concepts, the header file include was not commented out.  After PR #3131 , it is commented out.
