### ISSUE TITLE
Equality of modules with different monomial orders

### ISSUE THREAD

**Issue by mahrud** [Macaulay2/M2#3135]
Can we change `Module === Module` in the interpreter to ignore Schreyer orders? This is causing too many problems, almost exclusively for free modules:
```m2
  R = QQ[x,y,z]/(x^2,y^2,z^2)
  C = res coker vars R
  M = ambient coker C.dd_3
  F = R^{6:-2}
  -- both free modules:
  M ==  F -- true
  M === F -- false
  intersect(M, F) -- error
  remainder(M, F) -- error
  inducedMap(M, F, id_(2 * F)) -- error
```
And here is the problem: (scroll to the right)
```m2
i49 : peek M

o49 = Module of Vector{cache => CacheTable{...4...}                                                                 }
                       numgens => 6
                       RawFreeModule => free(rank 6 degrees = {T2, T2, T2, T2, T2, T2}z2.0 yz.1 xz.2 y2.3 xy.4 x2.5)
                       ring => R

i50 : peek F

o50 = Module of Vector{cache => CacheTable{...5...}                                    }
                       numgens => 6
                       RawFreeModule => free(rank 6 degrees = {T2, T2, T2, T2, T2, T2})
                       ring => R
```
All of these can be solved with an appropriate change of `===` to `==` in Core, such as in 1338599bee952ce060d207b4fe5e10468f6b1b74 and 7f1c585cfb58574afb1dd8f5a493452ebaf7f1ed, but this will have a negative effect on speed when the modules are not free and there needs to be a gb computation instead.

**Comment by DanGrayson** [comment]
The idea of `Module === Module` is that *everything* should be equal.  The idea of `Module == Module` is that the comparison takes just the mathematically relevant things into account.

**Comment by mahrud** [comment]
I am aware. And yet, some things are allowed to be different:
```m2
i2 : M = R^1;

i3 : N = prune R^1;

i4 : M === N

o4 = true

i5 : peek M.cache

o5 = CacheTable{cache => MutableHashTable{}}

i6 : peek N.cache

o6 = CacheTable{cache => MutableHashTable{}                              }
                pruningMap => | 1 |
                                                                        1
                minimalPresentation => (OptionTable{Exclude => {}}) => R

```
At least for free modules, I propose that monomial order should be ignored, similar to how cached info are ignored.

**Comment by mahrud** [comment]
Maybe before you respond, try this code for yourself first:
```m2
  R = QQ[x,y,z]/(x^2,y^2,z^2)
  C = res coker vars R
  M = ambient coker C.dd_3
  F = R^{6:-2}
  intersect(M, F) -- error
```
David reached out to me saying this was a bug. Why shouldn't someone less experienced immediately stop using M2 after running into this?

**Comment by mahrud** [comment]
@mikestillman This comment in the engine means this is actually a bug:
https://github.com/Macaulay2/M2/blob/d9bdb52edc3f1d54eb4b6532271c640530aa9ceb/M2/Macaulay2/e/interface/freemodule.cpp#L103-L106

```m2
i4 : R = QQ[x,y,z]/(x+y+z)

i5 : R^{3:-1} === ambient coker(res coker vars R).dd_2

o5 = false

i6 : R^{3:-1} == ambient coker(res coker vars R).dd_2

o6 = true
```

**Comment by mikestillman** [comment]
You are right!  @mahrud Can you try commenting out the two lines in `e/freemod.cpp` in `is_equal` (lines 166, 167), and see if the examples and tests run.  If so, let's remove these two lines.  I can try this myself, but not until after tomorrow.
```
  if (schreyer != nullptr) return schreyer->is_equal(F->schreyer);
  if (F->schreyer != nullptr) return false;
```

**Comment by mahrud** [comment]
I was just testing this right now!

**Comment by mahrud** [comment]
A test (`schorder2.m2`) failed and I'm not sure what's going on.

Also, @DanGrayson I think this should have been alarming to you:
```m2
i1 : R = QQ[a..d];

i2 : M = source schreyerOrder vars R

      4
o2 = R

o2 : R-module, free, degrees {4:1}

i3 : N = source vars R

      4
o3 = R

o3 : R-module, free, degrees {4:1}

i4 : M === N

o4 = false

i5 : hash M === hash N

o5 = true
```
Different things can have the same hash, but for two things so similar to have the same hash seems bad.
