### ISSUE TITLE
testing guide for developers and distributors

### ISSUE THREAD

**Issue by DanGrayson** [Macaulay2/M2#314]
We need to write a guide to Macaulay2 developers and distributors:

Things to include:
- print " **\* " in error messages for tests, so we can find them in the lengthy output from make
- test every distribution by logging in as a user who has no access to /usr/local, nor to the user that build the program
  - we also need a quick test suite for that user to run.  It should test GF to see if Conway polynomials are found, for example.

**Comment by mahrud** [comment]
I propose making the list here: https://github.com/Macaulay2/M2/wiki/Release-Checklist
