### ISSUE TITLE
Cannot load package "ToricVectorBundles" in version 1.23

### ISSUE THREAD

**Issue by a-hochenegger** [Macaulay2/M2#3163]
When using `loadPackage "ToricVectorBundles"`, I get the error message:
`ToricVectorBundles.m2:589:17:(2):[8]: error: expected left hand parameter to be a function, type, or a hash table`
I'm using Macaulay2, version 1.23, on Ubuntu 20.04.6 from the repository (the exact version is `1.23+ds~js-1~ubuntu20.04.1`). I've also removed completely Macaulay2 and all its dependencies, and reinstalled it, but the problem remains.
I had a look at line 589 of `/usr/share/Macaulay2/ToricVectorBundles.m2`, but there is just a commented line, so I couldn't figure out, what might cause that error.
On another computer with Debian 11, I'm using version 1.17 of Macaulay2, where I don't have this problem. So it might be that this problem appeared somewhere between version 1.18 and 1.23.

**Comment by d-torrance** [comment]
I'm not able to reproduce this.  Is there a chance you have an older version of the `ToricVectorBundles` package saved locally? You might try running the following:

```m2
uninstallPackage "ToricVectorBundles"
```
That would uninstall the older version so that the next to you try to load it, it will load the newer, 1.23-compatible version.

**Comment by a-hochenegger** [comment]
I have to apologise: there was an old version of `ToricVectorBundles` in my working directory, which caused the problem. Sorry, I was not aware that I was loading a local package.
