### ISSUE TITLE
Crash on negative rational exponents

### ISSUE THREAD

**Issue by jkyang92** [Macaulay2/M2#3168]
The following code crashes M2 with "fatal: internal error: negative exponent for integer power"
```
2^(-1_QQ)
```
Note the all of the following work fine
```
2^(-1)
2^(-1/2)
2^(2_QQ)
(2_QQ)^(-1_QQ)
```

**Comment by jkyang92** [comment]
Nevermind, I think it's not present on the current version

**Comment by d-torrance** [comment]
Yeah, it was fixed in #2982.
