### ISSUE TITLE
toField() leads to a crash

### ISSUE THREAD

**Issue by glenndavis52** [Macaulay2/M2#3172]
input:
```
Qi  =  toField( QQ[i]/(i^2+1) )

R   = Qi[u,v]

(u + v) / i
```

output:
```
-- SIGSEGV
-* stack trace, pid: 12251
 0# 0x000000000064E665 in /usr/bin/M2-binary
 1# 0x000000000064E8D3 in /usr/bin/M2-binary
 2# 0x00007FC88D820760 in /lib64/libc.so.6
 3# 0x00000000009224AF in /usr/bin/M2-binary
...
38# 0x00007FC88E41D9A8 in /lib64/libgc.so.1
39# GC_call_with_stack_base in /lib64/libgc.so.1
40# 0x00007FC88D86BB17 in /lib64/libc.so.6
41# clone in /lib64/libc.so.6
-- end stack trace *-
```

Without the` toField()`, all is OK.

I am using:  
    Macaulay2Web
    Macaulay2, version 1.22.0.1

**Comment by pzinn** [comment]
Yes this is the same issue that was reported before in the mailing list. It's my fault, I inadvertently let a PR slip into the web version which has not been tested thoroughly yet, namely, fraction fields of iterated polynomial rings.
In normal M2 you'd just get the error message `error: not implemented yet: fraction fields of polynomial rings over rings other than ZZ, QQ, or a finite field`. The way to avoid this is to not ask M2 to use the fraction field:
```
i4 : (u+v)*i^-1

o4 = - i*u - i*v

o4 : Qi[u..v]
```

**Comment by mikestillman** [comment]
@d-torrance @pzinn can we close this issue?
