### ISSUE TITLE
mingw 64 port

### ISSUE THREAD

**Issue by DanGrayson** [Macaulay2/M2#32]
We'd like to port Macaulay2 code to native Windows binary code.  

One way is to use cygwin as the build system and mingw64 as the target host system.  The branch https://github.com/Macaulay2/M2/tree/release-1.6-mingw represents a start on the work, based on the stable 1.6 branch, in that the program builds and links.

The remaining problems are:
- that we can't call pari from M2 because pari compiles itself without  gmp/mpir support, and that's because the mpir limbs are 64 bit and pari wants them to be 32 bit.  This involves writing two-way conversion routines in C between the two types of big integers.
- that when cygwin starts M2 then M2 can't find the file setup.m2.  That's because the root of the cygwin file system is different from the root of the windows file system.  This involves a bit of rewriting of startup.m2.in.
- the program crashes often.  The debugger shows memory scrambling, so it's problem a libgc/pthreads problem.  This will be a hard bug to figure out and probably require much time in gdb.

I might be able to return to this in August, but if someone else wants to try, assign yourself and give it a try!

**Comment by DanGrayson** [comment]
With the help of David Grayson, I made some progress using msys2 instead of cygwin, as the
ambient OS within Windows.  See https://github.com/DanGrayson/M2/commits/native-windows-port-via-mingw64-and-msys2

**Comment by mahrud** [comment]
I was wondering if, given the option of using M2 via WSL (and potentially Docker in the future), porting to native Windows binary is still a priority. This would simplify M2lib.c and the source tree to some extent, for instance we won't need to patch gtest, gdbm, and readline libraries for mingw.

**Comment by DanGrayson** [comment]
Yes, porting to Windows is no longer a goal.  In any case, those attempts were 7 years ago, and the changes associate with them are probably obsolete.
