### ISSUE TITLE
wrong sign convention for factor(polynomial in iterated polynomial ring)

### ISSUE THREAD

**Issue by pzinn** [Macaulay2/M2#320]
It's simpler to explain with an example: currently

R=QQ[x]; R2=R[t]; factor promote(x,R2)

return (-1)*(-x), which is correct but ugly.
This is because the statement (that I wrote...) in the definition of factor
               if conv(leadCoefficient pp) > 0 then pp else (if odd(exps#i) then c=-c; -pp)
gets confused because leadCoefficient x is x (as an element of the base ring R) and conv(x)=0.
I'll make a pull request for a simple fix later today.

**Comment by pzinn** [comment]
I'm still thinking about this. I'll propose a better fix soon.

**Comment by pzinn** [comment]
OK I think I nailed it.
Now I want to point out one of the things that bothered me:
at the moment, M2 does not allow factor of an element of a QuotientRing.
however, it does allow factor of an element of a PolynomialRing over a QuotientRing...
e.g.
R=QQ[t]/ideal(t^3-1); R2=R[];
factor(t^2-1) will fail, but factor sub(t^2-1,R2) will succeed...
doesn't seem very logical to me.

**Comment by DanGrayson** [comment]
Certainly "factor" should succeed only in the cases where we have a unique factorization domain and an algorithm for factoring, so it should check, for example, that we are in a polynomial ring over a field.

**Comment by pzinn** [comment]
Agreed. (though do you really mean polynomial ring over a field? what about over ZZ?). Anyway, this should probably be made into a separate issue. The original problem was with non-quotient iterated rings, and I believe my fix works there for all base rings.

**Comment by DanGrayson** [comment]
Sure -- polynomial rings over ZZ, as well.
