### ISSUE TITLE
GCD in iterated polynomial ring?

### ISSUE THREAD

**Issue by pzinn** [Macaulay2/M2#321]
Speaking of iterated polynomial rings, a problem I've encountered recently.
I'm not sure why one can't compute say
gcd(x^2-t^2,x^3-t^3)
in R2=R[t], R=QQ[x]. (it returns: error: not implemented yet)

Apparently the condition is that R2 should be "factoryAlmostGood" but I think this is too restrictive. 
In fact
rawGCD(raw (x^2-t^2), raw (x^3-t^3))
produces the correct answer.
Any thoughts?

**Comment by DanGrayson** [comment]
Iterated polynomial rings are represented internally by "flattened" polynomial rings, so we should be able to make this work.

**Comment by pzinn** [comment]
... 6 years later, I want to close this issue. but first, a basic problem: shouldn't `gcd` test that the ring is a UFD?
```
i1 : R=ZZ[x]/(x^2+3)

o1 = R

o1 : QuotientRing

i2 : gcd(4,2*(1+x)) -- that's one answer:

o2 = 2

o2 : R

i3 : (1+x)*(1-x) -- but (1+x) would work too

o3 = 4

o3 : R
```

**Comment by DanGrayson** [comment]
Or better, just give an error if the ring is a quotient ring.
