### ISSUE TITLE
Iterated Laurent polynomial ring

### ISSUE THREAD

**Issue by pzinn** [Macaulay2/M2#328]
Playing with iterated polynomial rings has led me to yet another bug (which, incidentally, predates any of the changes that I made to the handling of Laurent polynomials, so is unrelated to them)
write
R=QQ[x,Inverses=>true,MonomialOrder=>Lex];
R2=R[t,Inverses=>true,MonomialOrder=>Lex];
then several functions will be confused, notably
numerator(t+x^(-1))
will answer t+x^(-1), which I consider an incorrect answer.
similarly, factor will produce wrong results.

**Comment by DanGrayson** [comment]
That doesn't seem wrong to me.  If we have a fraction ring of a ring B, then for
b,c in B, the numerator of b/c should be b, even if B is itself a ring of fractions.

**Comment by pzinn** [comment]
Fair enough. I'll think some more about this, because I still think some other functions produce wrong results.

**Comment by DanGrayson** [comment]
Another point to consider: perhaps "numerator" and "denominator" should be well defined
functions from the fraction ring to the ring.  I wonder how generally that can be achieved.

**Comment by DanGrayson** [comment]
Closing.  Reopen this if you want us to consider it further.
