### ISSUE TITLE
Escaped message printed during findProgram examples

### ISSUE THREAD

**Issue by mahrud** [Macaulay2/M2#3292]
```m2
 -- capturing example results for "findProgram"                             This program writes out version information of the Gfan installation.
[[0,0,0,1],[1,0,0,1],[0,1,0,1],[1,1,0,1],[0,0,1,1],[1,0,1,1],[0,1,1,1],[1,1,1,1]]
[[7,6,5,4,3,2,1,0],[6,7,4,5,2,3,0,1],[4,6,5,7,0,2,1,3],[0,4,2,6,1,5,3,7]]
This program writes out version information of the Gfan installation.
 -- 0.267105 seconds elapsed
```

**Comment by mahrud** [comment]
Also:
```m2
 -- warning: R cannot be found; ending
```

**Comment by d-torrance** [comment]
The R message is intended.  I think it's useful for the user to know that the RInterface package wasn't properly loaded.

**Comment by d-torrance** [comment]
Yeah, that's weird.  I suppose that's coming from when Macaulay2Doc is building the "packages provided with Macaulay2" page?

**Comment by mahrud** [comment]
I thought so as well, but that page only calls `readPackage "RInterface"` which should stop after the call to `newPackage`. Other possibility is a link to a documentation node in RInterface which isn't prefaced with `RInterface::`, I think.

**Comment by d-torrance** [comment]
I think I figured out the problem.  At the end of `installPackage`, when we actually generate the info and/or html files for the "packages provided with Macaulay2" page, we call `info TO pkg` and/or `html TO pkg` for every package.  They in turn call `fixup(DocumentTag)`, which eventually calls the following, completely loading the package:
https://github.com/Macaulay2/M2/blob/ec9e9ac60ed4a8e791448942202f077a88a87e15/M2/Macaulay2/m2/packages.m2#L200

**Comment by d-torrance** [comment]
Related: #1643
