### ISSUE TITLE
repository set up script for users

### ISSUE THREAD

**Issue by DanGrayson** [Macaulay2/M2#33]
Under Debian and Ubuntu, it would be convenient for users to have a short shell script that could be run as root and would download the Macaulay2 public key, install it, and then use it to call "apt-get" to install Macaulay2.  The script would be easy to write.  Thanks to Thomas Kahle for the idea.

**Comment by DanGrayson** [comment]
This script seems to work:
```
apt-key adv --keyserver hkp://keys.gnupg.net --recv-key	CD9C0E09B0C780943A1AD85553F8BD99F40DCB31
echo 'deb http://www.math.uiuc.edu/Macaulay2/Repositories/Debian stable main' > /etc/apt/sources.list.d/macaulay2.list
apt-get update
apt-get install macaulay2
```

**Comment by DanGrayson** [comment]
I've documented these lines on the downloads pages on our web site, at least.

**Comment by mahrud** [comment]
Closing this, as it seems to be resolved. Feel free to open if there's anything left to do.
