### ISSUE TITLE
Flint version issue with autotools

### ISSUE THREAD

**Issue by MichaelABurr** [Macaulay2/M2#3360]
@d-torrance On my most recent install of M2 (1.24.05-release) using autotools, I ran into a Flint issue.  I have Flint version 3.1.2 installed via MacPorts.  Configure used this version of Flint, but there were errors during the compilation process (the wrong prototypes were called from Flint).  I deactivated the version of Flint from MacPorts and there were no issues in the install process (M2 installed its own version of Flint).

I thought that Flint 3 should work with M2, but, if it isn't compatible, perhaps there should be an upper limit of the version in the build information to prevent this error.

**Comment by d-torrance** [comment]
1.24.05 does support Flint 3.  Would you be able to attach a build log showing the errors?

**Comment by MichaelABurr** [comment]
The issue appears in the build of factory.  Here's the build log (if I deactivate the Flint from macports, this issue does not arise).
[FlintFailure.txt](https://github.com/user-attachments/files/16238132/FlintFailure.txt)

**Comment by d-torrance** [comment]
I think this was fixed in #3273 (setting it to build Factory 4.4.0 instead of 4.3.0).  Does building from the `development` branch (or from the `master` branch after running `git cherry-pick db8b27d`) work?

**Comment by MichaelABurr** [comment]
Yes, this appears to be a duplicate issue.  Thanks!
