### ISSUE TITLE
Optional submodules

### ISSUE THREAD

**Issue by d-torrance** [Macaulay2/M2#340]
Currently, in my draft of the Debian Macaulay2 package, I remove large swaths of Makefiles to skip the use of git submodules for memtailor, mathic, and mathicgb since I use the Debian packages of these libraries instead [1].

Would it be possible to check for the presence of these libraries during configure and only use the git submodules if not they're not found, much like most of the existing non-submodule libraries?

Thanks!

[1] https://github.com/d-torrance/M2/blob/master/debian/patches/skip_submodules.patch

**Comment by DanGrayson** [comment]
Good idea.

**Comment by DanGrayson** [comment]
@mikestillman -- is this a good idea, or do we want the Macaulay2 makefile to have total control
about which releases of mathicgb, etc., are in use?  Another way to have control would be to
add version number checking to the configure script, I guess, but then the info would be in two places.

**Comment by DanGrayson** [comment]
This branch of mine adds optional compilation of submodules:
https://github.com/DanGrayson/M2/tree/optional-submodules

It seems to work just fine.

**Comment by d-torrance** [comment]
Thanks for working on this!

When I try to build in that branch with the Debian memtailor/mathic/mathicgb packages installed, configure runs just fine, but make eventually fails with this:

    make[1]: Leaving directory '/root/M2/M2/libraries'
    make: *** No rule to make target 'all-in-submodules', needed by 'all-in-Macaulay2'.  Stop.
    make: Leaving directory '/root/M2/M2'

**Comment by DanGrayson** [comment]
Okay, I think I fixed it.

**Comment by d-torrance** [comment]
It did -- thank you!

**Comment by DanGrayson** [comment]
Resolved in https://github.com/Macaulay2/M2/pull/385
