### ISSUE TITLE
Windows 10 Issue

### ISSUE THREAD

**Issue by jaredlpainter** [Macaulay2/M2#342]
I don't know if this has been brought up, but it doesn't appear that the current version of Emacs works in Windows 10.  I installed Macaulay using cygwin and whenever I go to open the program now the emacs window flashes briefly and then closes.  I have tried running the program in multiple different compatibility modes with no success.  Has anyone else experienced this issue?

**Comment by DanGrayson** [comment]
When you speak of "running the program", are you referring to Macaulay2 or to emacs?

**Comment by jaredlpainter** [comment]
emacs with not run.  I have tried by clicking the icons that are installed with Macaulay and also by trying to manually start the Xwinserver and go into emacs manually from there.  All things I can do on a Windows 7 computer.  It appears that Windows 10 is not allowing these programs to run.

**Comment by DanGrayson** [comment]
If you try to run emacs from a shell, instead of by clicking on an icon, is
there any
visible error output?

If not, all I can think of is that you might want to check the bug reports
at cygwin.com.
