### ISSUE TITLE
Feature request: cdot or ⋅ as a binary operator

### ISSUE THREAD

**Issue by mahrud** [Macaulay2/M2#3434]
Currently we have a number of unicode synonyms defined in [exports.m2](https://github.com/Macaulay2/M2/blob/ec9e9ac60ed4a8e791448942202f077a88a87e15/M2/Macaulay2/m2/exports.m2#L1277-L1302). I think it would be useful to introduce the [interpuct](https://en.wikipedia.org/wiki/Interpunct) ($\cdot$) as a binary operator. This could be implemented as a synonym to a binary keyword `cdot` (similar to `and`, `or`, etc. but bound to a top-level method).

However, it would even be more interesting if M2-mode (and other editors) could automatically convert `\cdot` to $\cdot$ similar to, for instance, in [agda-mode](https://agda.readthedocs.io/en/v2.7.0/tools/emacs-mode.html#unicode-input), and we could freely type `C⋅D` (without spaces) and have M2 recognize this.

This would be pretty straightforward, mostly duplicating sections related to `and` in the interpreter, but there are two tricky things:
1. What's the best way to allow installing methods from top-level?
2. How do we parse `⋅` as a keyword operator in the interpreter so that `C⋅D` works?

The main applications for this is intersection product and of course dot product of vectors. If this goes well, I think replacing `@@` with `circ` and $\circ$ would be amazing!

**Comment by mahrud** [comment]
This is of course related to #1069 for working with unicode characters. @pzinn have you tried something like this?

**Comment by d-torrance** [comment]
Parsing without spaces doesn't work:

```m2
i4 : v·w

o4 = v·w

o4 : Symbol
```

But `locate` seems to work:

```m2
i6 : methods symbol ·

o6 = {0 => ((·, =), Type, Type)  }
     {1 => ((·, =), Thing, Thing)}
     {2 => (·, Thing, Thing)     }
     {3 => (·, Vector, Vector)   }

o6 : NumberedVerticalList

i7 : locate 3

o7 = stdio:1:20-1:60

o7 : FilePosition

i8 : code oo

o8 = stdio:1:20-1:60: --source code:
     Vector · Vector := (v, w) -> ((transpose v#0) * w#0)_(0, 0)
```

**Comment by mahrud** [comment]
That's not what I meant, is this output the same if you replace + with cdot?
```m2
i2 : peek locate (pseudocode functionBody(() ->   1     +     1))

o2 = FilePosition{stdio, 2, 45, 2, 58, 2, 51}
```

**Comment by d-torrance** [comment]
It ends at column 59 instead of 58, so I'm guessing that's comma from the extra byte in the Unicode character.

```m2
i2 : peek locate (pseudocode functionBody(() ->   1     ·     1))

o2 = FilePosition{stdio, 2, 45, 2, 59, 2, 51}
```

**Comment by mahrud** [comment]
> Parsing without spaces doesn't work:

It would be ideal if we could get this to work, for instance `A⊗B` seems to parse correctly:
```m2
i25 : A⊗B
stdio:25:0:(3): error: no method for binary operator ** applied to objects:
            A (of class Symbol)
     **     B (of class Symbol)
```

**Comment by pzinn** [comment]
the reason `⊗` works (and more generally, a variety of mathematical symbols) is the following commits:
8936f64c85b7eddc83aef6e6c8fa3edff3cf28db
ecde3f8a77d02cef36b0e58352aa5089a8cf76db
sadly this dot is not a "mathematical" symbol -- its unicode doesn't start with 226 -- so the code there doesn't immediately apply. one could try to rewrite these commits to allow for general unicode symbols, but that will require some significant changes to the parser.

**Comment by mahrud** [comment]
Thanks! This is very helpful. Taking a brief look, is it not possible to add cdot as an exception? I don't think there are too many of them.

**Comment by pzinn** [comment]
why don't you use `⋅` for \cdot?
```
i1 : ascii "⋅"

o1 = {226, 139, 133}
```

**Comment by pzinn** [comment]
Incidentally, if you want to see all characters starting with 226 (which contains a bunch of non mathematical symbols as well -- we could be more selective), try in the browser:
```
needsPackage "Text"; TABLE table(2^6,2^6,(i,j)->ascii{226,128+i,128+j})
```

**Comment by mahrud** [comment]
`v·w` still won't work. This requires a change in the interpreter.

**Comment by pzinn** [comment]
actually in your original post you used `·`, not `·`. why would you use the latter?

**Comment by mahrud** [comment]
What difference does it make?

**Comment by pzinn** [comment]
`⋅` starts with 226 in UTF8, so there's no need to change existing code besides what @d-torrance did.

**Comment by mahrud** [comment]
In emacs, enter `M-x set-input-method` and type `TeX`. Then open M2 and type `ascii "\cdot"`. It'll be converted to this:
```m2
i1 : ascii "·"

o1 = {194, 183}
```
We want something that is easily usable.
