### ISSUE TITLE
Tests seem to hang (without being run) sometimes, using ninja

### ISSUE THREAD

**Issue by mikestillman** [Macaulay2/M2#3458]
On my branch complexes-for-1-24-11, I run all of the tests, using `ninja check-packages`.  But a couple of packages seem to hang (without actually running M2 heavily): TerraciniLocus, and SpecialFanoFourfolds.

This is with a cmake build, on mac apple silicon, runnning Sonoma 14.6.1.

If I simply do `ninja -k0 check-TerraciniLoci`, it seems to hang, not running any examples.  If inside of M2, I type `check "TerraciniLoci"`, it finishes all tests in a second or two.

Was this a know issue that has been fixed recently? I might need to merge development into my branch?  (Although it will soon, hopefully, be merged into development)

**Comment by d-torrance** [comment]
`TerraciniLoci` uses threads (via the `FastMinors` package), so maybe that's the problem?

**Comment by mikestillman** [comment]
How are running the package tests handled on github?

**Comment by d-torrance** [comment]
I think the GitHub cmake builds run `M2 --check 3`.

I'm wondering if `capture` is causing problems for the `TerraciniLoci` tests?  Does the following help?

```diff
--- a/M2/Macaulay2/packages/TerraciniLoci.m2
+++ b/M2/Macaulay2/packages/TerraciniLoci.m2
@@ -182,6 +182,7 @@ doc ///
 -- just the faster (< 1s) examples
 
 TEST ///
+-- no-capture-flag
 -- rational normal curves
 needsPackage "Resultants"
 assertEmptyTerracini = (r, f) -> assert Equation(terraciniLocus(r, f), 1)
@@ -198,6 +199,7 @@ assert Equation(terraciniLocus(2, veronese(1, 3), Threads => 2), 1)
 ///
 
 TEST ///
+-- no-capture-flag
 -- del pezzo surfaces
 delPezzoSurface = t -> (
     kk := ZZ/32003;
@@ -225,6 +227,7 @@ assert Equation(
 ///
 
 TEST ///
+-- no-capture-flag
 -- veronese
 needsPackage "Resultants"
 
@@ -232,6 +235,7 @@ assert Equation(terraciniLocus(2, veronese(2, 3)), 1)
 ///
 
 TEST ///
+-- no-capture-flag
 -- segre-veronese
 
 segreVeronese = (n, d) -> (
```

**Comment by mikestillman** [comment]
Doug, yes, this appears to fix the problem.  Thanks!  I will add those, and see if any others are needed too.
