### ISSUE TITLE
"Duplicate large block deallocation" message when calling numRealTrace from realroots.m2

### ISSUE THREAD

**Issue by larstiq** [Macaulay2/M2#35]
M2 aborts after outputting the message "Duplicate large block deallocation" when running the following code:

https://gist.github.com/larstiq/5676124  (it seems github does not support file attachements but wants one to post a "gist", hrmph).

It fails on 64bit Debian Wheezy and Ubuntu 12.04 computers.  The computation is
still running on my 32bit laptop but  it may just be slow.

The code depends on http://www.math.tamu.edu/~sottile/research/ps/realroots.m2 as featured in
the chapter "From Enumerative Geometry to Solving Systems of Polynomial Equations" of the 
"Computations in algebraic geometry with Macaulay2" book.

**Comment by mahrud** [comment]
Closing this issue since the example seems to work now and there seem to be related patches merged in 2015. Feel free to reopen if it is still an issue.
