### ISSUE TITLE
Slight error in install documentation

### ISSUE THREAD

**Issue by ihoover** [Macaulay2/M2#353]
Had permissions issue with the command given for editing `/etc/apt/sources.list`. Specifically,

    echo 'deb http://www.math.uiuc.edu/Macaulay2/Repositories/Ubuntu XXXX main' >/etc/apt/sources.list.d/macaulay2.list

doesn't work with sudo since the `>` isn't modified (I guess I could have used an elevated shell? Not really sure). I needed to use the following command to append a line to my file via command line.

	echo "deb http://www.math.uiuc.edu/Macaulay2/Repositories/Ubuntu trusty main" | sudo tee -a /etc/apt/sources.list

My apologies if this is not the right place to report this. On the website it asked to let you guys know if something didn't work, and this is the only way I could see to do that.

**Comment by DanGrayson** [comment]
On the web site we say to use the command "as root".  As you surmise, that means
to use an elevated shell.  You could use the "tee" command as you say (but I would
not use the "-a" option), but it is easier to just get a shell with:
```sh
sudo bash
```
