### ISSUE TITLE
error in linking GC on Ubuntu 22.04

### ISSUE THREAD

**Issue by p-goerlach** [Macaulay2/M2#3534]
trying to compile M2 with @mahrud, we got stuck here:
```
/usr/bin/ld: usr-host/lib/libgc.a(gc.c.o): in function `GC_get_full_gc_total_time':
/home/paulg/software/M2/M2/submodules/bdwgc/extra/../alloc.c:84: multiple definition of `GC_get_full_gc_total_time'; Macaulay2/d/CMakeFiles/M2-interpreter.dir/actors5-tmp.c.o:/home/paulg/software/M2/M2/Macaulay2/d/actors5.d:2072: first defined here
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
```

**Comment by mahrud** [comment]
@d-torrance is GC_get_full_gc_total_time introduced in a more recent version of gc than the one in the submodules directory?

**Comment by mahrud** [comment]
Ah, we realized weren't on development. The build finished there, but there was one minor issue: cmake could not locate `gc/gc_cpp.h` for the life of it ...
