### ISSUE TITLE
chainComplex does not work for simplicial complexes

### ISSUE THREAD

**Issue by alessiodali** [Macaulay2/M2#3559]
After loading the package SimplicialComplexes, attempting to call the routine chainComplex for a given simplicial complex K results in an error.

**Comment by mahrud** [comment]
In the most recent version, the package has migrated to using [Complexes](https://macaulay2.com/doc/Macaulay2/share/doc/Macaulay2/Complexes/html/), so use `complex` instead of `chainComplex`.
