### ISSUE TITLE
problem with rank of a matrix

### ISSUE THREAD

**Issue by naddington** [Macaulay2/M2#359]
The following code gives a nonsensical answer (rank = 12) in my installation of 1.8.2, but the right answer (rank = 4) on version 1.6 on another machine.

k = ZZ/101
R = k[x_0..x_5]
M = random(R^6, R^{6:-1})
M = M - transpose M
S = R/pfaffians(6,M)
N = sub(M,S)
rank N

Thanks as always for this fantastic piece of software.

Nick Addington

**Comment by DanGrayson** [comment]
Indeed, it gives the wrong answer in 1.8.2, but gives the right answer in the current
development version on the master branch.  Mike, do you remember a change that
might have fixed this?

**Comment by naddington** [comment]
Judging by a few other examples it seems to be the right answer times the degree of Proj S.  Maybe it's misusing some coefficient of some Hilbert polynomial?

**Comment by mikestillman** [comment]
It appears to now give the correct answer.  I'm not sure what fixed it, but I'll close this issue for now.

**Comment by naddington** [comment]
Thanks!
