### ISSUE TITLE
Building on Arch/Manjaro

### ISSUE THREAD

**Issue by antonydellavecchia** [Macaulay2/M2#3590]
I am running into some errrors when trying to build on an Arch/manjaro system.

To get around a first error with gc I configured using the command

```
../../configure --enable-download --without-system-gc
```

Running `make` I run into the following error

```
make: Leaving directory `/home/antonydv/projects/M2/M2/BUILD/build/Macaulay2/packages/NumericalSemigroups-temporary'
ls -l NumericalSemigroups-temporary
total 0
rm -rf NumericalSemigroups-temporary
if [ -e /home/antonydv/projects/M2/M2/BUILD/build/usr-dist/common/share/info/NumericalSemigroups.info ]; then install-info --info-dir=/home/antonydv/projects/M2/M2/BUILD/build/usr-dist/common/share/info /home/antonydv/projects/M2/M2/BUILD/build/usr-dist/common/share/info/NumericalSemigroups.info; fi
make[2]: Leaving directory '/home/antonydv/projects/M2/M2/BUILD/build/Macaulay2/packages'
make[1]: *** [Makefile:15: all-in-packages] Error 2
make[1]: Leaving directory '/home/antonydv/projects/M2/M2/BUILD/build/Macaulay2'make: *** [Makefile:57: all-in-Macaulay2] Error 2
make: Leaving directory '/home/antonydv/projects/M2/M2/BUILD/build'
```

**Comment by mahrud** [comment]
If you look at a few lines higher, there should be a line telling you what documentation example failed to generate and why. Can you copy maybe another 20 or so lines?

**Comment by antonydellavecchia** [comment]
Sorry, I didn't get the full error because was running make in parallel.

i reconfigured with 

```
../../configure --enable-download --without-system-gc --without-libffi
```

I am currently get this error now

/usr/bin/ld: ../e/dmat.o: undefined reference to symbol 'cblas_saxpy'
/usr/bin/ld: /usr/lib/libcblas.so.3: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[2]: *** [Makefile:133: /home/antonydv/projects/M2/M2/BUILD/build/usr-dist/x86_64-Linux-ManjaroLinux-24.1.2/bin/M2-binary] Error 1
make[2]: Leaving directory '/home/antonydv/projects/M2/M2/BUILD/build/Macaulay2/bin'
make[1]: *** [Makefile:15: all-in-bin] Error 2
make[1]: Leaving directory '/home/antonydv/projects/M2/M2/BUILD/build/Macaulay2'make: *** [Makefile:57: all-in-Macaulay2] Error 2
make: Leaving directory '/home/antonydv/projects/M2/M2/BUILD/build'
```

**Comment by d-torrance** [comment]
Have you installed the `openblas` package? It should provide the cblas symbols
