### ISSUE TITLE
gfanInterface: Issue with gfanConvertToNewRing

### ISSUE THREAD

**Issue by felixlotter** [Macaulay2/M2#3600]
There is an issue with the method gfanConvertToNewRing in gfanInterface.m2 after loading NCAlgebra.m2. For example:

```
needsPackage "gfanInterface"
R1 = QQ[a,b]
I = ideal(a-b)
gfanHomogeneitySpace(I) -- works
needsPackage "NCAlgebra"
gfanHomogeneitySpace(I) -- does not work
```

This throws an error "expected substitution values to be ring elements or numbers" on line 761 in gfanInterface.m2.

@bkholler

**Comment by d-torrance** [comment]
Fixed in #3611
