### ISSUE TITLE
LDL package cannot be installed

### ISSUE THREAD

**Issue by dimpase** [Macaulay2/M2#363]
Contrary to what's written on http://www.math.uiuc.edu/Macaulay2/Packages/ I see (with M2 version 1.8.2 on Ubuntu 14.04 ) the following:

```
i2 :  getPackage "LDL"
--fetching package LDL, version 1.4 from http://www.math.uiuc.edu/Macaulay2/Packages/LDL/
--file downloaded: LDL.m2
/tmp/M2-975-0/1/LDL.m2:27:1:(2):[10]: error: 'export' no longer accepts symbols (such as ldl); enclose the name in quotation marks
```

**Comment by DanGrayson** [comment]
Thanks!

Meanwhile, you can put quotation marks around that one exported symbol and it might work for you.

**Comment by dimpase** [comment]
In fact, I was looking for a way to install another Peyrl's package, SOS, for sums of squares (which needs LDL), but SOS (http://www.mit.edu/~parrilo/pubs/files/PeyrlParrilo-ComputingSumOfSquaresDecompositionsWithRationalCoefficients.pdf SOS) is just gone, at least I wasn't able to find it anywhere... :-[

**Comment by DanGrayson** [comment]
Why not ask the authors?

**Comment by dimpase** [comment]
I did...

**Comment by mikestillman** [comment]
In fact, it would be nice to have those installed into M2.  We should ask Pablo to do that.

**Comment by dimpase** [comment]
I've found an (hopefully) up to date email of Peyrl:  helfried.peyrl@ch.abb.com and wrote to him (I already wrote to Pablo).

**Comment by DanGrayson** [comment]
Okay, we'll wait until you hear from Peyrl.

**Comment by dimpase** [comment]
I emailed him on 10th of Jan, and still no reply.

**Comment by jmokland** [comment]
Is it a question of the license or would having the files help? I found version 1.5 of SOS in my old files complete with a version of simpleSDP, LDL and BlkDiag. It loads without error on a M2 version 1.2 on a debian x86_64 machine, but the examples of the paper @dimpase links to just give me errors. I never had SOS working properly, but evidence of some version of it working on M2 0.9.95 is [here](http://folk.uio.no/johnco/SOSrun.txt). 
Attached: [code.zip](https://github.com/Macaulay2/M2/files/1235558/code.zip)

**Comment by dimpase** [comment]
I completely missed this, thanks.
