### ISSUE TITLE
DEBUG

### ISSUE THREAD

**Issue by DanGrayson** [Macaulay2/M2#367]
In debug mode we define the C preprocessor variable DEBUG, but it might be
more standard to define NDEBUG for non-debug mode.  The library flint
defines DEBUG now for itself in the file flint-2.4.5/fmpz_factor/factor_pp1.c,
producing an error from the compiler.  Before making the change we should audit our
code, replacing uses of DEBUG by NDEBUG.

**Comment by mikestillman** [comment]
Perhaps we should have a M2_NDEBUG, to not conflict with other library desires?

**Comment by DanGrayson** [comment]
I think the meaning of NDEBUG is standard, so we won't need that.

**Comment by DanGrayson** [comment]
fixed in commit 0c90490d3205b30130387dba8a337720bdf0fc43
