### ISSUE TITLE
the symbol 'info' is protected, name should be changed?

### ISSUE THREAD

**Issue by mikestillman** [Macaulay2/M2#369]
'info' is (apparently) an internal symbol.  Perhaps it should have a longer name (older code of mine no longer works because of this symbol being protected). (e.g. createInfoPages)

**Comment by DanGrayson** [comment]
I see nothing called createInfoPages in M2.  What are you referring to?  If it's something not in M2, just fix it.

**Comment by mikestillman** [comment]
I wasn’t sure what the name should be changed to.  The doc says it is an internal function, and I didn’t look into it yet.  But if that potential new name is accurate, I’ll simply make the change.

**Comment by DanGrayson** [comment]
I think it's good that we export it, even though we don't document it, for
testing purposes.

**Comment by DanGrayson** [comment]
The name `info` is going to stay, closing.
