### ISSUE TITLE
gftables not found during final check

### ISSUE THREAD

**Issue by DanGrayson** [Macaulay2/M2#382]
@d-torrance :

Thank you for https://github.com/Macaulay2/M2/pull/377 .  Could you take a look at
our latest release on the master branch and update your code in configure.ac for
locating gftables so it finds it also in the location where we put it when we build factory?
Probably it just has to look in the right directory to see if it's there.

We put it in usr-dist/common/share/Macaulay2/Core/factory/gftables in the build directory,
and the final check is performed in the directory `check-configure` by running `make check`.

In the latest release, I set PGK_CONFIG_PATH so it should find factory.pc, at least.

When this check is running, it "doesn't know" that factory has been built by us, so it has
no reason to trust that gftables is there.

**Comment by d-torrance** [comment]
Thanks for the comment!  I'll look into it.

**Comment by DanGrayson** [comment]
I could also look into it (today).  It seems to me that if we find 'factory' pre-installed, then
we can assume that it knows where gftables is, and we don't have to concern ourselves with it,
as we do when we call `setFactoryGFtableDirectory` in `m2/factor.m2`.

**Comment by d-torrance** [comment]
I had this same thought when I was initially putting together #377.  But it when I tried to build M2 with pre-installed factory but did not call `setFactoryGFtableDirectory`, then factory couldn't find the tables.  Indeed, later in the build process when the documentation was being built, there was an error when dealing with some finite field operations.

This seems like a bug in factory.  If I'm understanding [1], it looks like it only prepends the directory to the gftables path if `gftable_dir` is defined.  And this is only defined if the `set_gftable_dir` function is called (which is what `setFactoryGFtableDirectory` does).

[1] https://github.com/Singular/Sources/blob/ec3d9a4cd4ac241b8dec6377b20f0658bf3f1341/factory/gfops.cc#L108

**Comment by DanGrayson** [comment]
Thanks, you're right.

I'll take a look at it today.

**Comment by DanGrayson** [comment]
By the way, I finally ran into a related issue myself yesterday and fixed it today (on the eigen branch).  Same problem.
