### ISSUE TITLE
"Prem" if we don't build factory

### ISSUE THREAD

**Issue by d-torrance** [Macaulay2/M2#384]
In [1], we patch factory to make "Prem" visible.  However, if we use a pre-built factory, this won't necessarily be true.

Would it be worth submitting this patch upstream to the Singular devs?

[1] https://github.com/Macaulay2/M2/blob/4af5a550200754e6b44dc4f0e5cca47a49ad97b1/M2/libraries/factory/patch-4.0.2

**Comment by DanGrayson** [comment]
Yes, at least that would make your new code in configure.ac work, as we do
need Prem to be declared!
Feel free to submit it for us.  Perhaps they'll have a work-around for us,
too.  It's referred to in e/x-factor.cpp.

**Comment by d-torrance** [comment]
The Singular devs merged my pull request [1].  But until the next Singular release (and until everyone upgrades to that release) we will still encounter factory without public Prem in the wild.  So I imagine some kind of check is still in order.

[1] https://github.com/Singular/Sources/commit/45ed963

**Comment by DanGrayson** [comment]
Great, thanks for doing that.
