### ISSUE TITLE
Ubuntu under Windows

### ISSUE THREAD

**Issue by DanGrayson** [Macaulay2/M2#391]
If Microsoft Windows will be able to run Ubuntu programs, then it will be able
to run Macaulay2, see http://www.linuxjournal.com/content/ubuntu-windows

**Comment by maxlieblich** [comment]
I tried this yesterday, and it seems to work great. I installed via the Ubuntu ppa instructions, fired up M2, loaded a code file, and did a computation. I'm just a casual (and new) user, though, so I didn't do anything involved. Are there unit tests somewhere? I'm happy to run them and let you know what happens.

**Comment by DanGrayson** [comment]
You could try running "installPackage" and "check" on several packages, but we have no run-time test suite, as such.

But the article I linked to didn't indicate that it was ready to go, nor how to get it, nor what version of Windows it runs under.  What all did you actually do?

**Comment by maxlieblich** [comment]
Build 14316 of Windows 10 enables bash on Windows (and a bunch of other things). I got it by signing up for the "fast ring" of the Windows Insider program (which is just a giant public beta test).

Even these early builds seem quite solid; nothing in the Linux subsystem has broken for me yet. I've installed emacs (both the Ubuntu binary package and by building the latest version from source), installed vim and built YouCompleteMe, installed texlive and texed some files, and installed M2 and run it! (But there is no upstart, you can't run an ssh server, I've heard you can't use docker, they say they are still working on getting enough done to make tmux work, etc. I tried installing Go and something got weird, but I haven't tried again to see where the issue actually was.) 

The main drawback right now that I've found is that the terminal doesn't handle color schemes right, and none of the enhanced Windows terminals (ConEmu, ConsoleZ, ...) seem to handle arrow keys right. These are just irritating non-structural problems.

I'll try what you suggest soon.

**Comment by DanGrayson** [comment]
This is great news!

Can you run ubuntu M2 inside ubuntu emacs in a *M2* buffer, as usual?

**Comment by DanGrayson** [comment]
Did getting Build 14316 involve a lot of downloading?  (I'm thinking of users with poor internet connections.)

**Comment by DanGrayson** [comment]
More details here: https://blogs.msdn.microsoft.com/wsl/2016/04/22/windows-subsystem-for-linux-overview/

**Comment by DanGrayson** [comment]
@maxlieblich -- which version of Ubuntu did you get running under Windows?  Can you upgrade it to a more recent one?

**Comment by nawaz705** [comment]
@DanGrayson --Dear Sir I have tried a lot to install macaulay2 on Ubuntu 17.04LTS but never got through. Hope you will provide some help.

**Comment by DanGrayson** [comment]
@nawaz705 This conversation is about running Macaulay2 under Windows.  If you could prepare a detailed bug report, that would be a good start for a new issue, here on github.  If not, a good place to post your request for help would be our google group at http://groups.google.com/group/macaulay2 .

**Comment by nawaz705** [comment]
Respected Sir, 
I just want to install Macaulay2 on Ubuntu 17.04 LTS.  I don't know the installation procedure. I have tried to install it via terminal but I couldn't.  
I want yourself to provide me the guidelines for the installation. Thanking in anticipation.


 Shahnawaz Ahmad Department of Mathematics
Central university of Jammu,J&K
 

    On Wednesday, 26 July 2017, 17:57, Daniel R. Grayson <notifications@github.com> wrote:
 

 @nawaz705 This conversation is about running Macaulay2 under Windows. If you could prepare a detailed bug report, that would be a good start for a new issue, here on github. If not, a good place to post your request for help would be our google group at http://groups.google.com/group/macaulay2 .—

**Comment by DanGrayson** [comment]
@nawaz705 Okay, but this github web site issue thread is devoted to another topic, so we should move to another venue.  (This thread is about running Macaulay2 under Windows.) If you could prepare a detailed bug report, that would be a good start for a new "issue", here on github. If not, a good place to post your request for help would be our google group at http://groups.google.com/group/macaulay2 .

**Comment by eivan** [comment]
Hello, I've assembled a quick tutorial with a few steps to set up Ubuntu bash under Windows 10 with the Linux subsystem, with Macaulay 2 and all at https://gist.github.com/eivan/cab0b0a29eebd91d767ea6ad7448368e .
(Note that there are details included about setting up GUI emacs, with Macaulay2 support, under Win10.)

**Comment by DanGrayson** [comment]
Thanks!  I'll add a link to it, but first, is that long hex number going to stay the same?

Also, it would be good if links to URLs starting with `http://www.math.uiuc.edu/Macaulay2/doc/Macaulay2-1.10` were changed to start with `http://www.math.uiuc.edu/Macaulay2/doc/Macaulay2`, so they would always point to the latest version and not disappear.

**Comment by eivan** [comment]
@DanGrayson I modified the links in the gist (removed "-1.10"), the hex did not change, and should not change in the future!

**Comment by DanGrayson** [comment]
Okay, thanks!  I've added the link from our website to your gist.

I'm closing this issue, as it seems that running M2 under Windows 10 is not a problem any longer, and we have now good documentation about how to do it.

**Comment by Sarasij93** [comment]
I am still unable to get M2 to work on Windows 10 Home. I used the Linux subsystem, added the line deb https://faculty.math.illinois.edu/Macaulay2/Repositories/Ubuntu bionic main in 2 separate ways (individually, uninstalling the entire thing and starting again)

(a) installed emacs and did sudo emacs /etc/apt/sources.list and added the line

(b) did sudo -i to get to root and typed echo 'deb https://faculty.math.illinois.edu/Macaulay2/Repositories/Ubuntu bionic main' >/etc/apt/sources.list.d/macaulay2.list

But then I am very confused about the key;; I tried sudo apt-key adv --keyserver hkp://keys.gnupg.net --recv-key CD9C0E09B0C780943A1AD85553F8BD99F40DCB31 but it says No dirmngr, IPC connection failed; I tried sudo apt-key add Macaulay2-key but no key found; I tried sudo apt-get update -q but it says no key available, not signed; 

Any help will be really nice.

**Comment by DanGrayson** [comment]
Thanks for the info!

**Comment by DanGrayson** [comment]
I'll make this a new issue for you.  (I don't know a solution.)  There has also been a discussion on our google group -- see https://groups.google.com/g/macaulay2/c/qYMOAEhbl04
