### ISSUE TITLE
Timestamp and reproducible builds

### ISSUE THREAD

**Issue by d-torrance** [Macaulay2/M2#395]
Currently, reproducible builds [1] of Macaulay2 are not possible due to the use of the DATE and TIME macros in [2].

[1] https://reproducible-builds.org/
[2] https://github.com/Macaulay2/M2/blob/ac3ae8f/M2/Macaulay2/bin/timestamp.c

**Comment by DanGrayson** [comment]
Great idea!

**Comment by DanGrayson** [comment]
I wonder how we could create a tar file without it incorporating times for the files in it.

**Comment by d-torrance** [comment]
For gzipped tarballs, the -n option skips adding a timestamp.  (See [1].)

[1] https://lintian.debian.org/tags/package-contains-timestamped-gzip.html

**Comment by DanGrayson** [comment]
That's a separate issue.  The program "tar" records the times of the files inside the archive.  Here is an example:
```
einsteinium$ ls -l dump-stack encrypt
-rwxr-xr-x 1 dan staff 401 Sep 26  2014 dump-stack
-rwxr-xr-x 1 dan staff  38 Nov 11  2013 encrypt
einsteinium$ tar cf - dump-stack encrypt | tar tfv -
-rwxr-xr-x  0 dan    staff     401 Sep 26  2014 dump-stack
-rwxr-xr-x  0 dan    staff      38 Nov 11  2013 encrypt
```

**Comment by d-torrance** [comment]
Are the files which are being archived with "tar" being generated during the build?  If not, then they should have the same timestamp from one build to the next, as long as the source itself hasn't changed.  

Things like `make dist` certainly aren't reproducible for exactly this reason, but I don't think that's the goal of the "reproducible builds" movement.

As long as the M2 binary, generated documentation, etc., are reproducible from the same source, I think everything should be okay.

For example, all of the M2 dependencies I've packaged for Debian so far pass the reproducible build tests except frobby[1], which has "/today" in its TeX manual.

[1] https://tests.reproducible-builds.org/rb-pkg/unstable/amd64/frobby.html

**Comment by DanGrayson** [comment]
Yes, for example, the binary file M2-binary ends up in a tar file.  But you
ask the wrong question.  Even
the source files have indeterminate creation times.  When you download the
source with "git clone",
the creation time is the time of download.

But you make a good point -- let's just forget about reproducibility of
*.tar.gz files, *.dmg files, etc.

**Comment by d-torrance** [comment]
That's true.  One way around this is to use the tarballs from the "Releases" page.  Then the timestamps correspond to the tag, e.g.,

    profzoom@cayke:~/tmp$ gunzip M2-version-1.8.2.1.tar.gz 
    profzoom@cayke:~/tmp$ tar tvf M2-version-1.8.2.1.tar | head -n5
    drwxrwxr-x root/root         0 2015-09-03 08:49 M2-version-1.8.2.1/
    -rw-rw-r-- root/root       306 2015-09-03 08:49 M2-version-1.8.2.1/.gitignore
    -rw-rw-r-- root/root       915 2015-09-03 08:49 M2-version-1.8.2.1/.gitmodules
    drwxrwxr-x root/root         0 2015-09-03 08:49 M2-version-1.8.2.1/M2/
    -rw-rw-r-- root/root      4765 2015-09-03 08:49 M2-version-1.8.2.1/M2/.gitignore

**Comment by DanGrayson** [comment]
No, let's just not worry about target files with timestamps in them, such
as tarballs, as
git is really our primary source.

**Comment by DanGrayson** [comment]
One reason we'll never have reproducible builds is that authors like to include timing commands in their example code for the documentation.

**Comment by d-torrance** [comment]
This is no longer a problem when using the [`SOURCE_DATE_EPOCH`](https://reproducible-builds.org/docs/source-date-epoch/) environment variable.  For example, in the Debian package, I always get:

```m2
i2 : version#"compile time"

o2 = Sep  6 2015, 04:03:15
```

This is coming from the date in [`debian/changelog`](https://salsa.debian.org/science-team/macaulay2/-/blob/master/debian/changelog), which I haven't bothered to change in 5 years.

I'm going to go ahead and close this issue.
