### ISSUE TITLE
Request for 1.9/1.9.0.1 tags

### ISSUE THREAD

**Issue by d-torrance** [Macaulay2/M2#418]
The latest M2 releases don't appear on the "Releases" page.

**Comment by DanGrayson** [comment]
I think the appropriate time to generate a release is after the code on the 1.9 branch is stable, and that won't happen until we have made all the binary distributions we want to.

But why bother with "releases" when one has branches?

**Comment by d-torrance** [comment]
Ok -- that makes sense.  I suppose I had assumed that 1.9 was stable since some of the binary distributions were already on the M2 homepage.

From a downstream package maintainer's standpoint, it's nice to have tags to pinpoint exactly which commit corresponds to a given release.  Debian specifically likes tarballs (see [1]).  (Note that it specifically says not to "do releases only as tags", but this is moot I think on GitHub since tarballs are automatically created for tags on the Releases page.)

Thanks!

[1] https://wiki.debian.org/UpstreamGuide#Releases_and_Versions





Thanks!

[1] https://wiki.debian.org/UpstreamGuide#Releases_and_Versions

**Comment by DanGrayson** [comment]
I make tags when I start a release branch, and github doesn't seem to make releases for them.

Since you're a downstream maintainer, you don't need my help for standardization -- just pick a commit number and stick with it.  Why bother with tags?

**Comment by d-torrance** [comment]
Each tag at [1] has a ".zip" and ".tar.gz" link for downloading snapshots.  These are what I'm referring to.  They also seem to be mentioned as the current official method of obtaining tarballs at [2].

On the Debian side of things, it's nice to have a webpage somewhere with links to tarballs from which version numbers can be parsed.  The program uscan [3] is frequently used by maintainers to both obtain tarballs from upstream and to track new releases.

Another completely unrelated advantage to tags is the "git description" element of the "version" hash in M2.  If I were to build M2 from the current tip of the master branch, it would be "version-1.8.2.1-715-ga98c1daff10da00e6d788b8c9b7d2c847d697c20-dirty" instead of "version-1.9-something".

Anyway, you're right that I can just come up with my own versioning scheme -- that's what I currently do with memtailor/mathic/mathicgb since they have no tags.

Thanks!

[1] https://github.com/Macaulay2/M2/releases
[2] http://www.math.illinois.edu/Macaulay2/Downloads/SourceCode/
[3] https://manpages.debian.org/cgi-bin/man.cgi?sektion=1&query=uscan&apropos=0&manpath=sid&locale=en

**Comment by DanGrayson** [comment]
Okay, good.

Maybe you're right about the automatic releases corresponding to tags that start with "version-".  In which case, none of them are any good, since "version-1.8.2" points to the commit that incremented the version number to 1.8.2 for the first time.  I'd like to delete all the releases and have that under manual control.

**Comment by DanGrayson** [comment]
It seems that *every* tag produces a release.  So we have 91 releases, mostly worthless.  I should go through and delete them all except for those you are actually use.

**Comment by DanGrayson** [comment]
Which of the releases at https://github.com/Macaulay2/M2/releases are you using?  I'd like to delete all the others and prevent any from being made automatically.

**Comment by DanGrayson** [comment]
It seems I can't delete a release, and every tag corresponds to a release.  I bet all those tar files are not made prospectively but instead are made on demands, so perhaps it's not a waste of github's disk space.

But somehow we should make people aware that the only tags worth grabbing as tar files are the ones with the word "stable" in them.

**Comment by d-torrance** [comment]
Right now, my draft of the Debian package is set up for uscan to parse [1] for tags of the form "version-*" and selects the highest version number.  But that can be changed to whatever scheme you end up using.

One way to point out the important releases is to use the "Draft a new release" button at [1].  It will appear in a larger font and you can add release notes.  I put together a quick example at [2].

[1] https://github.com/Macaulay2/M2/releases
[2] https://github.com/d-torrance/M2/releases/tag/version-1.8

**Comment by DanGrayson** [comment]
Perhaps
```
stable-release-VERSION-YYYYMMDD
```
would be good.

**Comment by DanGrayson** [comment]
Yes, let's do that.  Closing.
