### ISSUE TITLE
Error when building with existing givaro

### ISSUE THREAD

**Issue by d-torrance** [Macaulay2/M2#420]
I just noticed this when switching my Debian packaging work over to 1.9, now that givaro is included by default.

If givaro is installed prior to building M2, then it is detected during configure and not built.  Then the following build error occurs:

```
aring-gf-givaro.cpp: In constructor 'M2::ARingGFGivaro::ARingGFGivaro(M2::ARingGFGivaro::UTT, M2_arrayint_struct* const&, M2_arrayint_struct* const&, const PolynomialRing&)':
aring-gf-givaro.cpp:87:165: error: no matching function for call to 'Givaro::GFqDom<long int>::GFqDom(M2::ARingGFGivaro::UTT&, M2::ARingGFGivaro::UTT&, std::vector<long unsigned int>, std::vector<long unsigned int>)'
       givaroField( FieldType( charact_,mDimension, ARingGFGivaro::M2arrayToStdVec(charact_, modPolynomial), ARingGFGivaro::M2arrayToStdVec(charact_, generatorPoly) )),
                                                                                                                                                                     ^
In file included from aring-gf-givaro.hpp:45:0,
                 from aring-gf-givaro.cpp:3:
/usr/include/givaro/givgfq.h:94:2: note: candidate: Givaro::GFqDom<TT>::GFqDom(const Givaro::GFqDom<TT>&) [with TT = long int]
  GFqDom( const GFqDom<TT>& F)
  ^
/usr/include/givaro/givgfq.h:94:2: note:   candidate expects 1 argument, 4 provided
/usr/include/givaro/givgfq.h:92:6: note: candidate: template<class Vector> Givaro::GFqDom<TT>::GFqDom(Givaro::GFqDom<TT>::UTT, Givaro::GFqDom<TT>::UTT, const Vector&)
      GFqDom(const UTT P, const UTT e, const Vector& modPoly);
      ^
/usr/include/givaro/givgfq.h:92:6: note:   template argument deduction/substitution failed:
aring-gf-givaro.cpp:87:165: note:   candidate expects 3 arguments, 4 provided
       givaroField( FieldType( charact_,mDimension, ARingGFGivaro::M2arrayToStdVec(charact_, modPolynomial), ARingGFGivaro::M2arrayToStdVec(charact_, generatorPoly) )),
                                                                                                                                                                     ^
In file included from /usr/include/givaro/givgfq.h:366:0,
                 from aring-gf-givaro.hpp:45,
                 from aring-gf-givaro.cpp:3:
/usr/include/givaro/givgfq.inl:973:12: note: candidate: Givaro::GFqDom<TT>::GFqDom(Givaro::GFqDom<TT>::UTT, Givaro::GFqDom<TT>::UTT) [with TT = long int; Givaro::GFqDom<TT>::UTT = long unsigned int]
     inline GFqDom<TT>::GFqDom(const UTT P, const UTT e)
            ^
/usr/include/givaro/givgfq.inl:973:12: note:   candidate expects 2 arguments, 4 provided
In file included from aring-gf-givaro.hpp:45:0,
                 from aring-gf-givaro.cpp:3:
/usr/include/givaro/givgfq.h:82:2: note: candidate: Givaro::GFqDom<TT>::GFqDom() [with TT = long int]
  GFqDom(): zero(0), one(1), mOne(-1), _log2pol(0), _pol2log(0),_plus1(0) {}
  ^
/usr/include/givaro/givgfq.h:82:2: note:   candidate expects 0 arguments, 4 provided
Makefile.common:23: recipe for target 'aring-gf-givaro.o' failed
```

This is certainly due to the lack of the patch [1].

Of course, one solution is to _always_ build givaro, but that goes against the Debian package's goal of using existing Debian packages for all of the libraries.  We could submit the patch to givaro, hope they merge it, and add a check to see if at least that future version is installed.

Are there any other solutions?

Thanks!

[1] https://github.com/Macaulay2/M2/blob/a98c1da/M2/libraries/givaro/patch-3.7.0

**Comment by DanGrayson** [comment]
I don't know anything about givaro.  Maybe @mikestillman  or @jakobkroeker could say something.

**Comment by jakobkroeker** [comment]
@d-torrance 
I will ask If the givaro team is willing to include our patch or a equivalent modification of it
(open a pull request)

**Comment by d-torrance** [comment]
@jakobkroeker - Great, thank you!

**Comment by d-torrance** [comment]
Since it's been a little while, I went ahead and took the liberty of submitting a pull request to givaro with the M2 patch [1].

[1] https://github.com/linbox-team/givaro/pull/18

**Comment by d-torrance** [comment]
FYI, the patch was merged into givaro.

I suppose it remains to add a check in configure.ac as to whether the system givaro has this this patch or not.  If not, set BUILD_givaro to yes.  I'll submit a pull request in a few days.

**Comment by dimpase** [comment]
Good to know that this is now done; one less obstacle for M2 in Sage.

**Comment by d-torrance** [comment]
Givaro 4.0.2 was released recently and includes the M2 patch.

They moved around some header file locations between version 3.7.x and 4.0.x, so M2 doesn't build against the new givaro right now.

**Comment by DanGrayson** [comment]
That should be fixable.

**Comment by dimpase** [comment]
Sagemath now has a ticket (in review) to upgrade to givaro 4.0.2:
https://trac.sagemath.org/ticket/17635
it looks as if linbox and ffpack must be upgraded in lockstep.

**Comment by DanGrayson** [comment]
We've just upgraded givaro and fflas-ffpack.
