### ISSUE TITLE
html documentation includes links to methods of packages

### ISSUE THREAD

**Issue by DanGrayson** [Macaulay2/M2#422]
For example, try `viewHelp depth`, and you'll see broken links to methods defined
in the package Depth.  Those methods are not listed by `help depth`.

**Comment by jkelleyy** [comment]
Additionally, it would be nice if the documentation for the versions of depth defined by Depth appeared with the Depth package documentation.

**Comment by DanGrayson** [comment]
That's up to the author of Depth, since it is not handled automatically for them.  @bartsnapp ?

**Comment by bartsnapp** [comment]
I originally wrote depth, but have now "turned-it-loose." At the moment, I don't have time to make modifications. Anyone who is interested can work on it.

**Comment by DanGrayson** [comment]
Thanks, Bart.

**Comment by DanGrayson** [comment]
One documentation node in the package Depth serves to document each of the following
methods:
```
	  (depth, Ideal, Ring),
	  (depth, Ring),
	  (depth, Ideal, Module),
	  (depth, Module),
	  (depth, Ideal, Ideal),
	  (depth, Ideal, PolynomialRing),
	  (depth, Ideal, QuotientRing)
```
but it doesn't mention that the second argument could be a module.  That's a separate issue from the issue I've reported here, so I've reported it here: #438 .  Volunteers are welcome.

**Comment by DanGrayson** [comment]
The documentation node for "packages provided with Macaulay2" loads every package and then effectively dismisses it.  The only reason it does that is to get the values of the parameters "Headline" and "Certification" to "newPackage".  The problem is that package dismissal is incomplete: methods added to global method functions, such as "depth", remain, and then (broken) links to the documentation for those methods are made.  That's related to the problem that we don't record the source package when installing such global methods, nor do we record a list of all global methods functions installed by a package when it is loaded.

**Comment by eisenbud** [comment]
Your shell script is happily running on one of my machines. I hope for the best!

Thanks,

David
--
David Eisenbud
Director, Mathematical Sciences Research Institute; and
Professor of Mathematics,University of California, Berkeley
www.msri.org/~de

**Comment by mahrud** [comment]
This is fixed now, although it is somewhat opposite of what #192 asked. I'll close this now, but if a change is needed, the discussion can continue there.

**Comment by DanGrayson** [comment]
Here's how it looks now:

![Uploading Screen Shot 2020-12-02 at 1.08.05 PM.png…]()

**Comment by mahrud** [comment]
I don't think you fully uploaded the screenshot.

**Comment by DanGrayson** [comment]
Oh, I see -- I have to wait!

**Comment by mahrud** [comment]
Is this not the intended output? I think if you want `(depth, Module)` to show up you need to add `Depth` to preloaded packages.

**Comment by DanGrayson** [comment]
No, it's okay now: no broken links.
