### ISSUE TITLE
d/M2lib.c triggers frame-address warning

### ISSUE THREAD

**Issue by tom111** [Macaulay2/M2#430]
With -Werror=frame-address ( seemingly a default in gcc-6 ) you get the following compile failure:

../../../../Macaulay2/d/M2lib.c:157:14: error: calling '__builtin_return_address' with a nonzero argument is unsafe [-Werror=frame-address]
 #   define D fprintf(stderr,"level %d -- return addr: 0x%p -- frame: 0x%p\n",i,__builtin_return_address(i),__builtin_frame_address(i))

According to the gcc manual:

> This function returns the return address of the current
> function, or of one of its callers. The level argument is
> number of frames to scan up the call stack. A value of 0 yields
> the return address of the current function, a value of 1 yields
> the return address of the caller of the current function, and
> so forth. When inlining the expected behavior is that the
> function returns the address of the function that is returned
> to. To work around this behavior use the noinline function
> attribute.

> The level argument must be a constant integer.

> On some machines it may be impossible to determine the return
> address of any function other than the current one. in such
> cases, or when the top of the stack has been reached, this
> function returns 0 or a random value. In addition,
> __builtin_frame_address may be used to determine if the top of
> the stack has been reached.

> Additional post-processing of the returned value may be needed,
> see __builtin_extract_return_addr.

> Calling this function with a nonzero argument can have
> unpredictable effects, including crashing the calling
> program. As a result, calls that are considered unsafe are
> diagnosed when the -Wframe-address option is in effect. Such
> calls should only be made in debugging situations.

This seems to be a macro only relevant for debugging anyway?  Should -Werror be bypassed for normal builds, or the macro changed?

**Comment by DanGrayson** [comment]
I've never found that stack trace to be useful, anyway.  It works just as well to get a core dump
and use gdb to find out what the stack looked like.  So you could comment out that
code or use "-Wno-error=frame-address" on the command line.
