### ISSUE TITLE
HTML page "Beginning Macaulay2" is broken.

### ISSUE THREAD

**Issue by tom111** [Macaulay2/M2#436]
Looking for tutorials I came here:
http://www.math.uiuc.edu/Macaulay2/GettingStarted/
and clicked on the first link, which leads to the broken page:
http://www.math.uiuc.edu/Macaulay2/doc/Macaulay2-1.9/share/doc/Macaulay2/BeginningMacaulay2/html/

**Comment by DanGrayson** [comment]
Oh, yes, that was mentioned in #432 and fixed on the master branch.  I'll apply the fix also to this release and repost the documentation.

**Comment by DanGrayson** [comment]
(We've been incorrectly rendering the html for displayed math equations for a long
time, and finally browsers have decided to be more intolerant of our error.)

**Comment by DanGrayson** [comment]
Fixed.
