### ISSUE TITLE
fflas_ffpack name does not match the tarfile name fflas-ffpack

### ISSUE THREAD

**Issue by dimpase** [Macaulay2/M2#441]
the only way to find out how to specify correctly 

    ./configure --enable-build-libraries="fflas-ffpack"

was to inspect `./configure` contents; the tarfile is `fflas-ffpack-*.tar.gz`, and should be renamed...

**Comment by DanGrayson** [comment]
We don't rename the tarfiles of 3rd party software developers.  To discover the names of the libraries, one may look in the directory `M2/libraries` or read the output from `./configure --help`.
