### ISSUE TITLE
Macaulay2/d/pari-c.c should not use voir() macro

### ISSUE THREAD

**Issue by dimpase** [Macaulay2/M2#446]
Since pari-2.4, `void` was renamed to `dbgGEN`. 

One sees `#define voir dbgGEN` in a pari (compatibility ?) header `pariold.h`.

Lining against Sage's pari-2.8 gives "undefined reference` to `voir`. So it has to be renamed to `dbgGEN`.

**Comment by DanGrayson** [comment]
Done in commit 579f446cc5cb73fc41634824a909c756afdc9a3b
Branch     : try-not-patching-mpir
Remote     : git@github.com:Macaulay2/M2
