### ISSUE TITLE
check typical values

### ISSUE THREAD

**Issue by DanGrayson** [Macaulay2/M2#448]
Code like this should give an error:

```
stableIntersection = method(TypicalValue =>(TropicalCycle,TropicalCycle))
```

because the typical value should be a type, not a sequence of types.

**Comment by mahrud** [comment]
This seems to have been fixed, however, why not allow sequences of specific types? For instance returning a list of integers or sequence of ideals.

**Comment by DanGrayson** [comment]
Returning a sequence of types might make sense, because the documentation already allows multiple outputs to be listed, i.e., the usage can be of the form `(x,y) = foo()`, and you can have separate entries in `Outputs` for x and y.  And some functions take advantage of this, including `flattenRing`.
