### ISSUE TITLE
improve documentation of keyword 'export', 'doc' 

### ISSUE THREAD

**Issue by jakobkroeker** [Macaulay2/M2#45]
Dear Dan,

in the documentation of the 'export' keyword it is not mentioned, that variables should sometimes(?)  be protected from evaluation by putting them into quotes (").
Do you think, such a remark should be added?

Same issue for 'doc'

What is/would be the first place to find this information?

Best,

Jack

**Comment by DanGrayson** [comment]
It is now mandatory.
