### ISSUE TITLE
fixing dynamic linking of givaro

### ISSUE THREAD

**Issue by dimpase** [Macaulay2/M2#460]
[res.errors.txt](https://github.com/Macaulay2/M2/files/285298/res.errors.txt)

The following describes an experiment of building and running M2 (the branch 'try-not-patching-mpir') using libraries and executables (such as 4ti2, etc) supplied by Sage 7.2 on Ubuntu 14.04, with two patches from M2 (one for givaro, and another for ffpack).
`configure.ac` was modified to stop building mpir and mpfr. 

If givaro is dynamically linked with M2 then M2 builds, but crashes very early on with an error related to calling `free()` from `~Rational::zero` (from `kernel/rational/givrational.h:48`) on a memory location not under GC control.

Statically linked givaro, achieved by specifying `./configure  --enable-debug --prefix=$SAGE_LOCAL --enable-build-libraries="givaro"` does not show this behaviour. 
It took 2+ hours of tests running to get the 1st `Invalid pointer passed to free()`

```
   GC Warning: Finalization cycle involving 0x2ce2000
   Attempt to free invalid pointer 0x3b6cc50
   Invalid pointer passed to free()
   Aborted (core dumped)
```

in `MultipolynomialResultants` test.

As givaro is currently not (really) used by M2, it's not too urgent though.

**Comment by DanGrayson** [comment]
It would be good to know what OS and environment you did the experiment under, and whether the only difference was linking dynamically or statically, or whether another difference was telling M2 to build givaro itself.

**Comment by dimpase** [comment]
I've updated the report above. I'll also check whether switching off debugging makes a difference.

**Comment by dimpase** [comment]
In non-debugging mode, the tests stop at the same place, on `MultipolynomialResultants`.

**Comment by dimpase** [comment]
As we found out with Anton, the latter error comes from dynamic linking of flint. Including flint into `enable-build-libraries` fixes this error, and the rest of the tests pass.

It should be mentioned that neither `givaro` nor `flint` are linked dynamically in M2 from the binary dpkg for Ubuntu, so this is not a coincidence...

**Comment by dimpase** [comment]
One way to use an external static givaro would be to explicitly link against `<blah>/givaro.a`, and not doing  `-L<blah> -lgivaro`, which by default prefers the dynamic linking.

**Comment by d-torrance** [comment]
I think this issue has been fixed at some point, as I'm able to build Macaulay2 successfully now using the givaro dynamic library.

**Comment by DanGrayson** [comment]
@dimpase -- feel free to close this
