### ISSUE TITLE
ffpack+givaro+linbox update

### ISSUE THREAD

**Issue by jakobkroeker** [Macaulay2/M2#462]
look at this one (work in progress)
https://github.com/jakobkroeker/M2/commit/f9e79a408e2903f5585e701b9ad9972c932bc4fc
## Remaining issues: 

for some older computers 
we need to pass --disable-sse to fflas-ffpack as configure option, otherwise the compilation fails
- in  M2/libraries/fflas_ffpack/Makefile.in 
  i hardwired  /usr/lib64/atlas/libsatlas.so.3
  (with other blas I was not yet available to compile M2 (fedora 21, 64 bit)

Mike or Dan, could you dig into that?

on my test system was installed:
blas-3.5.0-10.fc21.x86_64
lapack-3.5.0-10.fc21.x86_64
openblas-devel-0.2.14-1.fc21.x86_64
atlas-3.10.1-18.fc21.x86_64

**Comment by DanGrayson** [comment]
Why?  What does the flag do?  Where is it documented?

**Comment by DanGrayson** [comment]
Fedora 23 is the current version.  I see no reason to make M2 compile under Fedora 21.

**Comment by jakobkroeker** [comment]
> Fedora 23 is the current version. I see no reason to make M2 compile under Fedora 21.

no problem, I will update fedora and check how it goes with fedora 23
I could also test the patch with ubuntu.

> Why? What does the flag do?

do you mean --disable-sse?
the enable-sse is documented in ffpack ('./configure --help; #enables sse 4.1), 
I do not know what the  disable-sse flag for ffpack-fflas does, but without it on my machine M2 does not compile at places where it uses  fflas-ffpack

```
In file included from /usr/lib/gcc/x86_64-redhat-linux/4.9.2/include/x86intrin.h:41:0,
                 from /usr/include/c++/4.9.2/x86_64-redhat-linux/bits/opt_random.h:33,
                 from /usr/include/c++/4.9.2/random:50,
                 from /usr/include/c++/4.9.2/bits/stl_algo.h:66,
                 from /usr/include/c++/4.9.2/algorithm:62,
                 from ../../../../Macaulay2/e/dmat.hpp:6,
                 from ../../../../Macaulay2/e/mat.cpp:4:
/usr/lib/gcc/x86_64-redhat-linux/4.9.2/include/smmintrin.h: In statischer Elementfunktion »static Simd128_impl<true, false, true, 4>::vect_t Simd128_impl<true, false, true, 4>::floor(Simd128_impl<true, false, true, 4>::vect_t)«:
/usr/lib/gcc/x86_64-redhat-linux/4.9.2/include/smmintrin.h:125:1: Fehler: »inline« beim Aufruf von always_inline »__m128 _mm_round_ps(__m128, int)« gescheitert: target specific option mismatch
 _mm_round_ps (__m128 __V, const int __M)
 ^
/home/jakob/Projects/M2UpdateFFlas/M2/BUILD/master/usr-host/include/fflas-ffpack/fflas/fflas_simd/simd128_float.inl:323:63: Fehler: von hier aufgerufen
     static INLINE CONST vect_t floor(const vect_t a) { return _mm_floor_ps(a); }
```

**Comment by DanGrayson** [comment]
Here's what their `./configure --help` shows:
```
  --enable-sse            Use Intel(r) SSE 4.1
```
That implies that sse is off by default, but the code shows it's on by default.  Someone should
report that documentation bug to them.  Similarly for `--enable-avx`.

We should have our configure script test whether these two options work and report on that.

**Comment by jakobkroeker** [comment]
same issues on fedora 23, opened upstream tickets

**Comment by jakobkroeker** [comment]
@mikestillman 
Could you check, if the compilation succeeds (or fails) without the '--disable-sse' flag? 
Since that is not a compatibility issue with msse 4.1
(see https://github.com/linbox-team/fflas-ffpack/issues/22) 
the above described issue (`target specific option mismatch`) might be located in the related M2 source.
The issue with the configuration flags in fflas-ffpack was fixed upstream: (https://github.com/linbox-team/fflas-ffpack/issues/21 )

**Comment by DanGrayson** [comment]
Givaro and fflas-ffpack have been brought up to date.
