### ISSUE TITLE
testing for _ntl_GetTime() does not work on OSX

### ISSUE THREAD

**Issue by dimpase** [Macaulay2/M2#467]
In configure.ac an NTL test uses a call to `_ntl_GetTime()`, something that does not work on OSX
(probably never did?)
Anyway, 
```
--- a/M2/configure.ac
+++ b/M2/configure.ac
@@ -1241,7 +1241,7 @@ then AC_LANG(C++)
      do  test "$lib" && LIBS="$lib $LIBS"
         AC_LINK_IFELSE([AC_LANG_SOURCE([
                 #include <NTL/tools.h>
-            int main () { _ntl_GetTime(); }
+          int main () { NTL::GetTime(); }
                 ])],
             FOUND=yes; break;,
             LIBS=$SAVELIBS)
```
does the trick. Probably `_ntl_GetTime()` is a very old hack from early C++ years, and should just be
replaced as above.

**Comment by DanGrayson** [comment]
No, it works fine.  In `NTL/tools.h` is the declaration `double _ntl_GetTime();`.

**Comment by dimpase** [comment]
Oops, sorry for barking up the wrong tree. The actual problem is that factory has its own recognition code for NTL, and this one fails. (It did "work" for me on linux, although it tested for NTL in the wrong place (in /usr/lib/) and then used the one supplied by Sage instead).

Anyway, I don't see why one needs to use an internal `_ntl_GetTime`, while `NTL::GetTime` works, is documented, etc...

**Comment by DanGrayson** [comment]
Good point, changed in commit 4ef6d8edd51624ed03df124455044b5c28a27119
