### ISSUE TITLE
memory leak in fast nonminimal resolution code

### ISSUE THREAD

**Issue by mikestillman** [Macaulay2/M2#468]
The following is an example, from Christian Bopp, that shows the excessive use of memory in version 1.9.  I need to do a memory audit of this code.  But a first glance at it shows several problems, it looks like it will be easy to fix.
```
loadPackage"RandomCanonicalCurves"

--initialization:
g=9;
p=12347;
numEx=100;
T=ZZ/p[t_0..t_(g-1)]
--
i=0;
L={};
while  (i < numEx) do (
    IC=(random canonicalCurve)(g,T);
    --L=L|{betti(res(IC,FastNonminimal=>true),Minimize=>true)};
    betti(res(IC,FastNonminimal=>true),Minimize=>true);
    IC=symbol IC;
    print(i);
    i=i+1;
    )
```

**Comment by mikestillman** [comment]
Dan made a change to the (random CanonicalCurve) code, and I fixed a number of memory leaks, and did a memory code review of new free resolution code.  It appears that now, once the garbage collector collects a free resolution, it doesn't leak memory.  There is still an issue as to why the random CanonicalCurve code was causing free resolutions to not be freed.  Dan, should we close this, or can you add in an example that we want to revisit for 2.0?

**Comment by DanGrayson** [comment]
Yes, #488 covers the remaining leak.  Closing.
