### ISSUE TITLE
build on ubuntu 12.04 LTS, small issue with gc

### ISSUE THREAD

**Issue by jakobkroeker** [Macaulay2/M2#470]
there is an libatomic_ops.a on the 12.04 LTS system with is detected by
the main configure script,

but when building the gc, it seemed not happy (complaining about missing atomic_ops).
However, if I build the M2-shipped atomic_ops manually first,
then building of gc succeds.

The problem is: I cannot reproduce the issue...

**Comment by mahrud** [comment]
Closing this, as the issue is old and we will soon not use atomic_ops at all.
