### ISSUE TITLE
test for building flint should check whether it was built with --enable-gc

### ISSUE THREAD

**Issue by dimpase** [Macaulay2/M2#471]
M2 should not use external flint which was built without --enable-gc.
I suppose using such a flint instance was the reason for the crash reported in the 4th comment on issue #460

**Comment by DanGrayson** [comment]
I wonder if a way to detect that could be found.  If so, we could add it to the configure script.

**Comment by dimpase** [comment]
I've [asked](https://groups.google.com/d/msg/flint-devel/6C48DAuinZc/88_uC9MmBQAJ) Flint devs.

**Comment by dimpase** [comment]
Bill said: test the preprocessor variable `HAVE_GC` in `flint/config.h`.
If it is 1 then Flint was built with `--enable-gc`, else it would be 0.

**Comment by DanGrayson** [comment]
Okay.  Now what is the reason that we should not use flint that doesn't use gc?

**Comment by dimpase** [comment]
Bill says they added this option because it was requested by you, guys. I suppose the crash mentioned above (in the issue report) has to do with this.

**Comment by mikestillman** [comment]
This was needed because flint encodes polynomials, by shifting their values a few bits.  gc cannot detect that they are pointers, and consequently frees the limb space used.  The enable-gc option action is to keep an array of pointers to mpz structs which are in use, and to keep also a freelist, so that unnecessary allocations are not done.

So we need that.

However, I believe there is a (flint) bug with the interaction of their arrays (freelists) and finalizers in gc. I need to make a coherent bug report to flint about that yet.  It has kept me from using flint integers and rational numbers so far.

— mike

**Comment by DanGrayson** [comment]
Okay, if the solution of #460 turns out to require us to implement your suggestion in this issue, we can do it at that time, so I'll close the issue.  Feel free to reopen the issue if some more information becomes available.

**Comment by DanGrayson** [comment]
Okay, Mike, thanks, reopening...

**Comment by dimpase** [comment]
Would you like me to provide a `confugure.ac` patch to test for `HAVE_GC` in `flint/config.h`?

Regarding a probable flint bug, I can say that the debugging log of `MultipolynomialResultants` package produces a lot of  `GC Warning: Finalization cycle involving` (even though flint is correctly configured with `--enable-gc`).

**Comment by DanGrayson** [comment]
Yes, and include Mike's justification for it in a comment.  Thanks!

**Comment by DanGrayson** [comment]
I think we need to always compile flint, since we are always compiling mpir.  When that changes, we can look at this again.

**Comment by dimpase** [comment]
I thought we have found out that we do not need to patch mpir, and thus we do not need to always compile it. The flint story is different.

**Comment by DanGrayson** [comment]
Yes, we have a plan for that, and I'm trying to implement that on a branch.  It's not in place yet on the master branch.

**Comment by mahrud** [comment]
We don't compile flint with --enable-gc anymore, so I'll close this. Feel free to reopen if I'm mistaken about what else needs to be done.
