### ISSUE TITLE
FourTiTwo.m2 documentation does not show correctly in browser.

### ISSUE THREAD

**Issue by lkastner** [Macaulay2/M2#472]
Going to
[doc of FourTiTwo.m2](http://www.math.uiuc.edu/Macaulay2/doc/Macaulay2-1.9/share/doc/Macaulay2/FourTiTwo/html/)
gives the following:
```
XML Parsing Error: not well-formed Location: http://www.math.uiuc.edu/Macaulay2/doc/Macaulay2-1.9/share/doc/Macaulay2/FourTiTwo/html/ Line Number 23, Column 30:
<table class="matrix" border=1><tr><td><table><tr><td> 3</td><td>2</td><td>1</td><td>0</td></tr><tr><td> 0</td><td>1</td><td>2</td><td>3 </td></tr></table></td></tr></table>
-----------------------------^
```
My browser is Firefox 46.0.1

**Comment by DanGrayson** [comment]
I think I fixed the bug, but must have forgotten to post the fixed documentation ...

**Comment by DanGrayson** [comment]
Nope.  Okay, maybe commit 6d13f1b90e3c0e3ab6e1cd38e9029ba5aff3d378 will fix it ...

**Comment by DanGrayson** [comment]
Okay, that fixed it.
