### ISSUE TITLE
Source code for calculate the factorial.???

### ISSUE THREAD

**Issue by robotden** [Macaulay2/M2#480]
Hello everybody.
I have just start to use M2 Software on Ubuntu.
I want to view source code for calculate the factorial (!) but I do not know that where it located.
Could you help me!
Thanks

**Comment by DanGrayson** [comment]
It's in the external library "MPIR", which we call here:

https://github.com/Macaulay2/M2/blob/master/M2/Macaulay2/d/gmp.d#L1346

**Comment by robotden** [comment]
Thank you very much
