### ISSUE TITLE
mpc is now required

### ISSUE THREAD

**Issue by DanGrayson** [Macaulay2/M2#484]
`M2/Macaulay2/d/pari-gnump.h`, added by Guillem Blanco last fall, includes `mpc.h` now, thus
it is now required to install the mpc library.  (How did this ever compile for me on my various
virtual machines, without mpc being there?)

Can we fix it so it doesn't?  I'm under the impression we use none of the code in mpc.

Under ubuntu, the package is libmpc-dev.

@gblanco92

**Comment by mikestillman** [comment]
@gblanco92 : I'm also making slight modifications to polyroots.hpp, cpp, to get it to compile with no warnings.  Here are the three changes needed, are these OK?  I will check this in, into master on M2, assuming it is ok.

[1] I place the following code to get the compiler to not complain about pari code:

```
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wconversion"
#include <pari/pari.h>
#pragma GCC diagnostic pop
```

(I've done similar around flint code and ntl code).

[2] I added a static_cast in polyroots.cpp, line 136:
```
    result->len = static_cast<int>(num_roots);
```

[3] The third one, I'm not sure the best way to fix this, below is what I have just done.  Can you check if this is an OK solution?

Here is the error I get from gcc 4.9:

```
                 ^
../../../../../../Macaulay2/e/polyroots.cpp:160:76: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
         CCC->ring().to_ring_elem(m2_root, **reinterpret_cast<mpfc_t*>(&root));
```

Here is how I fixed it (define root1 separately).  Does this fix seem ok?

```
        mpc_t root;
        auto root1 = reinterpret_cast<mpfc_t*>(&root);
        pari_mpc_init_set_GEN(root, gel(roots, 1 + i), GMP_RNDN);
        //        CCC->ring().to_ring_elem(m2_root, **reinterpret_cast<mpfc_t*>(&root));
        CCC->ring().to_ring_elem(m2_root, **root1);
        result->array[i] = RingElement::make_raw(CCC, m2_root);
```

**Comment by DanGrayson** [comment]
Okay on 1 and 2.  For 3, can we just define root as mpfc_t to begin with?  That ought to work, since mpc_t is used nowhere else.

**Comment by DanGrayson** [comment]
If we are going to continue to require it, configure.ac should test for its presence.

**Comment by gblanco92** [comment]
For some reason Github was not notifying me and I'm seeing this now for the first time, I'm sorry about this. Thank you @mikestillman for fixing my issues. If there is anything else I can do, Github will keep me posted now.

**Comment by DanGrayson** [comment]
The configure script now checks for mpc, see commit 712e43109c
