### ISSUE TITLE
computing determinant causes a segmentation fault?

### ISSUE THREAD

**Issue by ggsmith** [Macaulay2/M2#487]

**Comment by ggsmith** [comment]
Macaulay2, version 1.9
with packages: ConwayPolynomials, Elimination, IntegralClosure, LLLBases, PrimaryDecomposition, ReesAlgebra,
               TangentCone

i1 : d = 3;

i2 : needsPackage "Cyclotomic";

i3 : KK = QQ[r]/cyclotomicPoly(d,r);

i4 : S = KK[x_0..x_11];

i5 : A = matrix{
       {x_0 + r*x_1+r^2*x_2,0,0},
       {0,r*(x_0 + r*x_1+r^2*x_2),0},
       {0,0,r^2*(x_0 + r*x_1+r^2*x_2)}}

o5 = | x_0+x_1r-x_2r-x_2 0                 0                  |
     | 0                 x_0r-x_1r-x_1+x_2 0                  |
     | 0                 0                 -x_0r-x_0+x_1+x_2r |

             3       3
o5 : Matrix S  <--- S

i6 : det A

      3       2                  2    3              2                   2           2          
o6 = x  + 3r*x x  + (- 3r - 3)x x  + x  + (- 3r - 3)x x  + 6x x x  + 3r*x x  + 3r*x x  + (- 3r -
      0       0 1              0 1    1              0 2     0 1 2       1 2       0 2          
     -----------------------------------------------------------------------------------------------
          2    3
     3)x x  + x
        1 2    2

o6 : S

i7 : B = genericMatrix(S,x_3,3,3)

o7 = | x_3 x_6 x_9  |
     | x_4 x_7 x_10 |
     | x_5 x_8 x_11 |

             3       3
o7 : Matrix S  <--- S

i8 : M = matrix{{A,B,0*id_(S^3)},{0*id_(S^3),r*A,r*B},{r^2*B,0*id_(S^3),r^2*A}}

o8 = | x_0+x_1r-x_2r-x_2 0                 0                  x_3               x_6               
     | 0                 x_0r-x_1r-x_1+x_2 0                  x_4               x_7               
     | 0                 0                 -x_0r-x_0+x_1+x_2r x_5               x_8               
     | 0                 0                 0                  x_0r-x_1r-x_1+x_2 0                 
     | 0                 0                 0                  0                 -x_0r-x_0+x_1+x_2r
     | 0                 0                 0                  0                 0                 
     | -x_3r-x_3         -x_6r-x_6         -x_9r-x_9          0                 0                 
     | -x_4r-x_4         -x_7r-x_7         -x_10r-x_10        0                 0                 
     | -x_5r-x_5         -x_8r-x_8         -x_11r-x_11        0                 0                 
     -----------------------------------------------------------------------------------------------
     x_9               0                  0                 0                 |
     x_10              0                  0                 0                 |
     x_11              0                  0                 0                 |
     0                 x_3r               x_6r              x_9r              |
     0                 x_4r               x_7r              x_10r             |
     x_0+x_1r-x_2r-x_2 x_5r               x_8r              x_11r             |
     0                 -x_0r-x_0+x_1+x_2r 0                 0                 |
     0                 0                  x_0+x_1r-x_2r-x_2 0                 |
     0                 0                  0                 x_0r-x_1r-x_1+x_2 |

             9       9
o8 : Matrix S  <--- S

i9 : det M
-- SIGSEGV
-- stack trace, pid 16191:
level 0 -- return addr: 0x0x10b05eacf -- frame: 0x0x700000b94260
level 1 -- return addr: 0x0x0 -- frame: 0x0x700000b94280
level 2 -- return addr: 0x0x10b0c95fd -- frame: 0x0x700000b94830
level 3 -- return addr: 0x0x10d3bd9f0 -- frame: 0x0x10e0f0b60
-- end stack trace

Process M2 exited abnormally with code 1

**Comment by ggsmith** [comment]
Although I attempted many similar calculations, none of them produced such an error.  In particular, I was unable to generated a smaller example.

**Comment by mikestillman** [comment]
@DanGrayson This problem still occurs, although it hangs, rather than crashes for me.  The problem here is that even though the coefficient ring KK is a quotient of a polynomial ring, the Bareiss algorithm is being chosen.  The default in that case should be Cofactor (in which case the determinant computed is immediately returned).  We need a good predicate for the case of a polynomial ring to make sure no coefficient ring is also a quotient polynomial ring.  I have needed this before.  Should we create one?  I'm not sure how it should be written though.

**Comment by DanGrayson** [comment]
We should fix the engine so it doesn't hang or crash, but gives an error message.  Can you do that?  Then I'm sure I could devise the appropriate test at top level.  Let's collaborate on a branch.

**Comment by d-torrance** [comment]
Closed by #2546 and unit test added in #3304.
