### ISSUE TITLE
phase out wiki.macaulay2.com

### ISSUE THREAD

**Issue by DanGrayson** [Macaulay2/M2#492]
phase out the wikis to save money, in favor of github wikis
or find a way to host them statically and cheaply

**Comment by mahrud** [comment]
Both http://wiki.macaulay2.com/Snowbird/ and http://wiki.macaulay2.com/Macaulay2/ are failing at the moment.

**Comment by mahrud** [comment]
Also, would be good to transfer issues with this label to https://github.com/Macaulay2/Macaulay2-web-site.

**Comment by DanGrayson** [comment]
Well, if the wiki servers have been failing for weeks and no one has complained, I think I can just go ahead and shut them down.  The other thing hosted on the same virtual machine are a few subversion repositories, which can migrate to github as github repositories.

**Comment by mahrud** [comment]
What? I'm complaining!! I wanted to refer to the "tips after the workshop" page after a friend asked me something about Macaulay2.

**Comment by mahrud** [comment]
I have referred those wikis many times over the years to find useful code that is not distributed with Macaulay2.

@DanGrayson don't just shutdown useful repositories without notice. Give me access and I'll try to migrate them to github wiki.

**Comment by DanGrayson** [comment]
Re: "without notice" -- posting this issue is giving notice, isn't it?

**Comment by DanGrayson** [comment]
Okay, they're working now.  All I did was to update ubuntu, and they magically started working.

**Comment by DanGrayson** [comment]
Oh, I thought you were going to convert them to github wikis.  Okay -- but how about just submitting a pull request?

**Comment by mahrud** [comment]
It's going to require some testing, and you literally only have a file
called `foo.html` there! Are you worried about me breaking something?!

**Comment by mahrud** [comment]
> Oh, I thought you were going to convert them to github wikis. Okay -- but how about just submitting a pull request?

I told you, I tried that, but it doesn't look decent inside github!

**Comment by DanGrayson** [comment]
Okay, I've given you temporary write access to it.
