### ISSUE TITLE
Visualize Documentation Links

### ISSUE THREAD

**Issue by bstone** [Macaulay2/M2#497]
It seems that some links in the documentation are not working properly on the website. In particular here:

http://www.math.uiuc.edu/Macaulay2/doc/Macaulay2-1.9.1/share/Macaulay2/Visualize/graph-example.html

One thought I have is that I wrote this using html5. Does the server only know html4.1? If so, would it be easy to upgrade the server? Or do I need to revisit my code?

I will say the documentation seems to work well if you run installPackage and view it locally.

**Comment by DanGrayson** [comment]
The best way to fix HTML validity problems is with the validator at https://validator.w3.org/.  Give it a try.

Servers don't care whether a web page is HTML 4 or HTML 5 -- each page says what it is and each browser adapts to that.

I don't know why browsers are more particular about errors in web pages from the internet than about errors in web pages from the local file system.  Perhaps it's a newly heightened security concern.  We did notice that, too, and as a result, all the web pages we generate that are deposited in `share/doc/Macaulay2` are validated by the same validator.

**Comment by mahrud** [comment]
@bstone I'd be interested in getting this to work again, if you have time! What is the status now?

**Comment by bstone** [comment]
I plan on working on this package during the workshop next week. I am not sure how to fix this, but if you have ideas and want to help that would be wonderful.

**Comment by mahrud** [comment]
I just realized this works here:
http://www2.macaulay2.com/Macaulay2/doc/Macaulay2-1.16/share/Macaulay2/Visualize/graph-example.html
but not here:
https://faculty.math.illinois.edu/Macaulay2/doc/Macaulay2-1.16/share/Macaulay2/Visualize/graph-example.html

**Comment by DanGrayson** [comment]
Probably because the apache http server on www2 is ignoring the directive `AddType 'application/xhtml+xml' .html` in the file `doc/.htaccess`.  Maybe that subjects the file to more rigorous checking.

**Comment by mahrud** [comment]
Then remove that directive to solve this issue! It's not an `xhtml` document. What's wrong with `html`? See that the www2 page only has a few minor validation issues: https://validator.w3.org/nu/?doc=http%3A%2F%2Fwww2.macaulay2.com%2FMacaulay2%2Fdoc%2FMacaulay2-1.16%2Fshare%2FMacaulay2%2FVisualize%2Fgraph-example.html

No reason to wholesale block the webpage from being usable.

I've said this before, that putting stringent requirements on validity at the cost of actually being user-friendly is going in the wrong direction. When a mathematician is trying to find out if M2 can solve a problem for them they don't see if there are missing attributes on the html tags!! They just want the documentation to be easy to read, navigate, and search for what they want.

This kind of validation may have been necessary when Netscape was the most popular browser, but now if a browser isn't years ahead of the standards, it quickly loses popularity.

**Comment by DanGrayson** [comment]
All the other html files, thousands of them, are xhtml.

**Comment by mahrud** [comment]
> All the other html files, thousands of them, are xhtml.

Great, let's make them all html :)

**Comment by DanGrayson** [comment]
No, I like validation.

**Comment by DanGrayson** [comment]
Anyway, this might have been fixed in https://github.com/Macaulay2/M2/pull/1612

**Comment by mahrud** [comment]
All links are broken now: https://faculty.math.illinois.edu/Macaulay2/doc/Macaulay2/share/doc/Macaulay2/Visualize/html/index.html

**Comment by d-torrance** [comment]
I think this can be closed.  Everything works now that we're no longer using XHTML.  See for example https://macaulay2.com/doc/Macaulay2/share/Macaulay2/Visualize/graph-example.html.
