### ISSUE TITLE
Sage.m2 can probably be removed

### ISSUE THREAD

**Issue by lkastner** [Macaulay2/M2#505]
If someone were to interface Sage, he would probably have to start from scratch anyway. I made a quick grep for Sage.m2 and it does not seem to be used anywhere. It has no version, author, documentation or tests. Keeping it alive at this point might just mean extra work, even if it is just very little work. One can always go back to this version if one needs the code in the future.

**Comment by DanGrayson** [comment]
The log shows I wrote it, and it would be useful to keep if someone wants to revive it in the future.  It's not on the distribution list, so it doesn't get advertised.  So let's keep it.

As an alternative, it might be good to do away with the distribution list, and take every file in the packages directory as a package to be distributed.  Then files such as Sage.m2 that are not ready for prime time could be in another directory, such as `packages-devel`.

**Comment by mikestillman** [comment]
I like the alternative suggestion, I think that makes things somewhat simpler, and clearer.

**Comment by DanGrayson** [comment]
Yes, and we recently had a package `RationalMaps` added that didn't make it onto the distribution list, through an oversight.  I may have to release 1.9.2 to include it.

**Comment by lkastner** [comment]
Yes, I saw that Sage.m2 wasn't distributed. I just looked at the git log for it and it seemed like you modified it several times for 'Python stuff'. If there were many packages like this, the time spent on these might sum up. Having it in a separate folder will not change whether you have to repair it.

**Comment by DanGrayson** [comment]
We may never "have to" repair it.  The reason to keep it is if someone wants to make it work again.  For all we know, it still does work.

**Comment by lkastner** [comment]
Ok, then I am closing this issue.
