### ISSUE TITLE
new option for newPackage

### ISSUE THREAD

**Issue by DanGrayson** [Macaulay2/M2#508]
In the file `M2/Macaulay2/packages/Macaulay2Doc/overview_packages.m2` we load every package just to get the headlines.  A new option to `needsPackage`, `loadPackage`, and `newPackage` called `HeaderOnly` would allow for a solution of lighter weight -- the package file would stop loading after the `newPackage` command, so the header information would be available (where?), but the rest of the package would not be loaded.

**Comment by mahrud** [comment]
Consolidated in #1085.
