### ISSUE TITLE
automagic linking of internal mpir

### ISSUE THREAD

**Issue by tom111** [Macaulay2/M2#509]
This is for the Gentoo distribution again.  We build M2's copy of mpir internally (which we don't like, but do anyway).  This internal mpir links to the mpir that is already present on the system. It looks like this:

```
atlantis ~ # ldd /usr/lib64/Macaulay2/x86_64-Linux-Gentoo/lib/libmpirxx.so.4.0.21
        linux-vdso.so.1 (0x00007fffad5fe000)
        libmpir.so.11 => /usr/lib64/libmpir.so.11 (0x00007f85ea387000)
        libstdc++.so.6 => /usr/lib/gcc/x86_64-pc-linux-gnu/4.9.3/libstdc++.so.6 (0x00007f85ea02e000)
        libm.so.6 => /lib64/libm.so.6 (0x00007f85e9d38000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f85e999c000)
        libgcc_s.so.1 => /usr/lib/gcc/x86_64-pc-linux-gnu/4.9.3/libgcc_s.so.1 (0x00007f85e9785000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f85ea820000)
```
Does anybody have an idea why this happens, or how it can be prevented?  It leads to trouble.

**Comment by DanGrayson** [comment]
Because you didn't set the environment variable LD_LIBRARY_PATH to include the directory where our private libmpir.so.11 sits.

**Comment by tom111** [comment]
I can't change it globally for the whole M2 build, because I want it to link with system libraries where possible. I would need to figure out how to set it locally for the build system of the mpir that comes with M2.

**Comment by tom111** [comment]
OK, my previous comment makes little sense. What is the preference ordering of the LD_LIBRARY_PATH variable? Should I prepend or append the local mpir directory?

**Comment by DanGrayson** [comment]
Our makefiles already set LD_LIBRARY_PATH globally for the whole build, with no problem.
What's wrong with just using our makefiles as is?

(The load library path works like any other path: it is scanned from left to right until a match
is found.)

**Comment by DanGrayson** [comment]
PS: Our script M2 also sets it.

**Comment by tom111** [comment]
The package manager overwrites it during the build. I don't fully understand it. It seems to have to do with cross-compilation compatibility built into the package manager.

**Comment by DanGrayson** [comment]
Overwrites what?

**Comment by DanGrayson** [comment]
Our makefiles are in charge of the build -- nothing else happens while they're running.

**Comment by tom111** [comment]
When libmpirxx.so is first linked, it links to the internal version of libmpir.so, but during make install there is a relinking stage.  The package manager seems to arrange everything so that then as much as possible is relinked against system libraries. So this is not a Macaulay2 issue, but a Gentoo issue. Sorry for the noise.

**Comment by tom111** [comment]
(something like this is happening: https://lists.gnu.org/archive/html/libtool/2011-06/msg00034.html)

**Comment by DanGrayson** [comment]
Yes, libtool does relink things.  For some it's a great convenience, for me, it's a great annoyance.  You should be able to avoid libtool doing anything to our binaries after we make them.  Perhaps if you delete all the *.la files in site, then libtool will be flummoxed.
