### ISSUE TITLE
URL change in libraries/mpir/Makefile?

### ISSUE THREAD

**Issue by jimmymathews** [Macaulay2/M2#515]
Following the install instructions for Raspbian, at some point the libraries/mpir/Makefile fails after trying to wget

http://www.math.uiuc.edu/Macaulay2/Downloads/OtherSourceCode/**trunk**/mpir-2.6.0.tar.bz2

The HTTP server returns 404 not found.
I removed **trunk** from the script and it seems to work.

**Comment by DanGrayson** [comment]
You must be using an old version of our code.  If so, simply try compiling from our git repository on the branch release-1.9.2.

Let us know whether I'm right.

**Comment by jimmymathews** [comment]
This basically worked (rather than branch release-1.6 as indicated in the INSTALL file).

I tried to build from source on the Raspberry Pi A+ because the new Raspbian OS version jessie wasn't supported... In the end there was something awry, compilation was taking 1-2 days, and g++ hangs at some point.

**Comment by DanGrayson** [comment]
Okay, good to hear.

I've improved the INSTALL file, see commit f1640e1b8a78b7049181b1561999554b626026c5
