### ISSUE TITLE
new packages

### ISSUE THREAD

**Issue by DanGrayson** [Macaulay2/M2#530]
I see that the following packages have been added to the packages directory without being added to the list of distributed packages.  Is that intentional?

`AlphaTest, MonodromySolver, NumericalImplicitization, ReactionNetworks`

**Comment by DanGrayson** [comment]
@antonleykin  Can you answer the question previously asked?

**Comment by antonleykin** [comment]
We can release all of these.
You may want to ask the authors of `NumericalImplicitization` if there is an updated version.

**Comment by DanGrayson** [comment]
MonodromySolver runs phc, so it needs cached example output files.

`check NumericalImplicitization` fails with error such as this one:
```
stdio:6:51:(3):[1]: error: no method for binary operator == applied to objects:
--            NumericalInterpolationTable (of class NumericalInterpolationTable)
--     ==     35 (of class ZZ)
```

One of the examples in ReactionNetworks doesn't work.

There are some wrong email addresses:
```
ReactionNetworks.m2:7:	     {Name => "Anton Leykin", Email => "doe@math.uiuc.edu"},
ReactionNetworks.m2:8:	     {Name => "Timothy Duff", Email => "doe@math.uiuc.edu"},
ReactionNetworks.m2:9:	     {Name => "Kisun Lee", Email => "doe@math.uiuc.edu"},
ReactionNetworks.m2:10:	     {Name => "Cvetelina Hill", Email => "doe@math.uiuc.edu"}
```

**Comment by antonleykin** [comment]
I fixed the emails in ReactionNetworks.

Justin and Joe (in CC): Where is the most current NumericalImplicitization?
Can you make sure the tests work?

**Comment by DanGrayson** [comment]
I've added `AlphaTest` to the distribution list and postponed the target milestone for this issue to 2.0.  If you want to get any of the packages into 1.9.3, which will be released soon, let me know.

**Comment by antonleykin** [comment]
Did you add 'MonodromySolver' and 'ReactionNetworks"?

**Comment by DanGrayson** [comment]
No, because they still don't work, I assume.

**Comment by antonleykin** [comment]
Should this issue be closed?

**Comment by DanGrayson** [comment]
Yes, closing, thanks.
