### ISSUE TITLE
toExternalString change

### ISSUE THREAD

**Issue by sommars** [Macaulay2/M2#532]
If I run 
```
R = QQ[x,y]
S = R[z]
toExternalString S
```
the output is
```
R(monoid[z, Degrees => {1}, Heft => {1}, MonomialOrder => VerticalList{MonomialSize => 32, GRevLex => {1}, Position => Up}, DegreeRank => 1])
```
This is annoying, because the first `R` can't be read by a new instance of M2. It would be nice if toExternalString could output something like this instead:

`QQ(monoid[x..y, Degrees => {2:1}, Heft => {1}, MonomialOrder => VerticalList{MonomialSize => 32, GRevLex => {2:1}, Position => Up}, DegreeRank => 1])(monoid[z, Degrees => {1}, Heft => {1}, MonomialOrder => VerticalList{MonomialSize => 32, GRevLex => {1}, Position => Up}, DegreeRank => 1])`

because that could be read into a new Macaulay2 process. Could toExternalString be modified to make this work or is there some reason that this is not possible?

Thanks,
Jeff

**Comment by DanGrayson** [comment]
Take a look at the package "Serialize" and see whether it does what you want.

**Comment by sommars** [comment]
Thanks, I didn't know about the Serialize package; it's much closer to what I want.

Why does `serialize(CC[x,y])` throw an error? What other situations does serialize not support?

**Comment by DanGrayson** [comment]
Oh, it's called Serialization.

The package is only partially implemented.  And getting it "completely"
implemented will be hard, but
it should not be too hard to add "CC".

**Comment by sommars** [comment]
Thanks!
