### ISSUE TITLE
kernel forgets direct sum components

### ISSUE THREAD

**Issue by mikestillman** [Macaulay2/M2#535]
Problem: `kernel` changes the ambient free module.  For instance, the original might have direct sum components, as in the example below, but the call to 'kernel' loses this information.

```  
  S = ZZ/101[a..d]
  M = S^1 ++ S^2
  F = S^2
  f = random(F,M)
  K = kernel f  
  assert(target generators K == M)
  assert(target generators K === M)
  assert(components target generators K == components M) -- fails
```
The `ambient` of the map should also remember this information.

```
  g = K_{0}
  ambient g
  target ambient g === M
  components M
  components target ambient g
  assert(components M == components target ambient g)
```

**Comment by eisenbud** [comment]
There is (or recently was) the same problem with tensor products and Hom. I wrote special versions “tensorWithSummands” etc to fix this. Mike or Dan commented that making this the global option would potentially increase storage requirements for some processes.

DE

**Comment by DanGrayson** [comment]
But in this case, there is no computation to do to preserve the information.

**Comment by mahrud** [comment]
Closing this issue in favor of #2891.
