### ISSUE TITLE
syntax highlighting bug in emacs

### ISSUE THREAD

**Issue by pzinn** [Macaulay2/M2#537]
This is a bug I'm sure we all know about:
Currently, the two-character sequence {- is incorrectly interpreted as the start of a comment by emacs.
This is due to a weird limitation of the comment highlighting syntax of emacs, which allows two different two-character comment sequences *only* if they start with the same first character, which is not the case in Macaulay2: 
{* 
comment style 1
*} 
vs:
-- comment style 2
this is easy to fix and I finally got around to doing it, so this is only a heads up that I will soon submit a pull request for that (maybe after the current one is validated?).

**Comment by DanGrayson** [comment]
This has annoyed me forever.  Shall we just change the comment sequence?
I don't much like {- -} anyway, because lists of numbers should be able to typed like this: {-2,3,4}.

**Comment by mikestillman** [comment]
What would you suggest as an alternative?  {* *} ?

**Comment by DanGrayson** [comment]
Sounds good, but could emacs handle it?

**Comment by pzinn** [comment]
I'm not sure I understand. {- is *not* a comment. I use it all the time for example to type lists with negative integers. it just annoys me that emacs *believes* it's a comment.
Or maybe you're just asking how I'm fixing the problem: I only declare {* and *} as comments, and manually add in M2-symbols.m2 that regexp --*. has comment font. I'm of course not changing any functionality of Maculay2
the only side-effect I can see is rather minor: it's that in interactive mode, commented out parts of the input (with --) are not highlighted any longer after input is executed (in line with the fact that highlighting is only turned on for code you're currently typing, but contrary to say strings and comments, whose highlighting is coded at a different level and which therefore remain highlighted even after execution)

**Comment by DanGrayson** [comment]
Oops, I was confused and thought we were using {- -} rather than {* *}.

It sounds like you have a good fix.  Thanks!

**Comment by mikestillman** [comment]
Yes, I don’t know what I was thinking,  multiline comments are already {* … *} !
