### ISSUE TITLE
matrix inversion

### ISSUE THREAD

**Issue by sommars** [Macaulay2/M2#538]
`inverse(matrix({{2,0},{0,1}}))` throws a `matrix not invertible` error, as do all other integer options I try except for the identity matrix. Also, it seems that inverses of matrices of polynomials aren't working.

**Comment by pzinn** [comment]
that's normal behavior. your matrix is by default in ZZ, and is indeed it's not invertible within ZZ-valued matrices. you can promote it to QQ if you want to invert it:
```
i1 : inverse promote(matrix({{2,0},{0,1}}),QQ)

o1 = | 1/2 0 |
     | 0   1 |

              2        2
o1 : Matrix QQ  <--- QQ
```

**Comment by sommars** [comment]
Ok, that makes sense. Thanks!
