### ISSUE TITLE
enable-download link not working in 1.6

### ISSUE THREAD

**Issue by sdlaw** [Macaulay2/M2#541]
When attempting to compile from source on SL7.2, the "--enable-download" option with configure fails to download from www.math.uiuc.edu (192.17.3.239). The site is live but I guess the relevant download isn't as it gives a 404.

**Comment by DanGrayson** [comment]
Tell us the most recent commit number on your M2 repository and the name and path of the relevant download file.

**Comment by DanGrayson** [comment]
Feel free to reopen this issue after giving us the info requested previously.
