### ISSUE TITLE
lyubeznik complex error

### ISSUE THREAD

**Issue by DanGrayson** [Macaulay2/M2#55]
Reported by:	esaenz-d (on trac)

In function lyubeznik complex from package "SimplicialComplexes?" I obtain the following strange error message apparently when it tries to construct a SimplicialComplex? from an empty list
I=monomialIdeal(x2,y2,x*z,y*t)
oo16 : MonomialIdeal? of R
ii17 : lyubeznikComplex I
new nonfaces in degree 1: {}
new nonfaces in degree 2: {}
new nonfaces in degree 3: {}
new nonfaces in degree 4: {}
stdio:2:1:(3): error: expected a polynomial ring without quotient elements

**Comment by mikestillman** [comment]
Fixed in commit 0ccce3513167b49000c0401aff96d2c65c3902f6.
