### ISSUE TITLE
repeated macro definition

### ISSUE THREAD

**Issue by DanGrayson** [Macaulay2/M2#552]
`M2_ASSERT` is defined twice, see below.  Also, there are many files where `M2_ASSERT` is defined to be `assert` even if we are not in debug mode.

```
 ** compiling /home2/dan/src/M2/M2/Macaulay2/e/util.cpp
In file included from ../d/engine-exports.h:58:0,
                 from /home2/dan/src/M2/M2/Macaulay2/e/engine-includes.hpp:15,
                 from /home2/dan/src/M2/M2/Macaulay2/e/util.hpp:7,
                 from /home2/dan/src/M2/M2/Macaulay2/e/util.cpp:4:
/home2/dan/src/M2/M2/Macaulay2/e/newdelete.hpp:4:0: warning: "M2_ASSERT" redefined
 #define M2_ASSERT assert
 ^
In file included from /home2/dan/src/M2/M2/Macaulay2/e/util.cpp:3:0:
/home2/dan/src/M2/M2/Macaulay2/e/stdinc-m2.hpp:21:0: note: this is the location of the previous definition
 #define M2_ASSERT(X)
 ^
```

**Comment by mikestillman** [comment]
The intent is to use M2_ASSERT rather than assert, to theoretically have slightly more control over when they are actually not compiled out.  But perhaps this is not needed.  Maybe I should just change all uses of M2_ASSERT back to assert.

**Comment by DanGrayson** [comment]
Our configure script supports only "debug" or "don't debug".  A third option "partly debug" seems of marginal utility.

**Comment by mikestillman** [comment]
I don’t think we want it yet, but I could imaginie:
  1. Don’t debug
  2. M2_ASSERT_ALWAYS (used for not so expensive tests)
  3. M2_ASSERT (only with NDEBUG not set)
The problem with assert in optimized code, is it will crash things.  But that is likely better than incorrect answers.

For now, I will remove M2_ASSERT.  It just defaults to assert anyway, so later it is easy to search for assert, and deal with them if we choose to change to something like the above M2_ASSERT_...(which we might not!).

**Comment by DanGrayson** [comment]
Okay, but instead of M2_ASSERT_ALWAYS call it assert_always.

**Comment by mikestillman** [comment]
I have left M2_ASSERT in, but replaced all current uses with assert.  M2_ASSERT is defined in only one place too.  Perhaps we should delete this code.  Still, I'm closing this issue.
