### ISSUE TITLE
add two programs

### ISSUE THREAD

**Issue by DanGrayson** [Macaulay2/M2#559]
cohomcalg:  http://wwwth.mpp.mpg.de/members/bjurke/cohomcalg/

topcom:  http://www.rambau.wm.uni-bayreuth.de/TOPCOM/

**Comment by DanGrayson** [comment]
@mikestillman where is the source code of cohomcalg?

**Comment by mikestillman** [comment]
It is in the zip file at http://wwwth.mppmu.mpg.de/members/bjurke/cohomcalg/content/cohomCalg-031b.zip

**Comment by DanGrayson** [comment]
How many of these do we really want?:
```
cohomcalg
  -rwxr-xr-x 1 dan staff  396196 Jan  3 12:58 B_A
  -rwxr-xr-x 1 dan staff  576624 Jan  3 12:58 checkregularity
  -rwxr-xr-x 1 dan staff  450700 Jan  3 12:19 cross
  -rwxr-xr-x 1 dan staff  466056 Jan  3 12:19 cube
  -rwxr-xr-x 1 dan staff  216656 Jan  3 12:19 cyclic
  -rwxr-xr-x 1 dan staff  265476 Jan  3 12:19 hypersimplex
  -rwxr-xr-x 1 dan staff  252372 Jan  3 12:19 lattice
  -rwxr-xr-x 1 dan staff 1087452 Jan  3 12:19 points2allfinetriangs
  -rwxr-xr-x 1 dan staff 1087444 Jan  3 12:19 points2alltriangs
  -rwxr-xr-x 1 dan staff  451644 Jan  3 12:19 points2chiro
  -rwxr-xr-x 1 dan staff  472984 Jan  3 12:19 points2facets
  -rwxr-xr-x 1 dan staff  477264 Jan  3 12:19 points2finetriang
  -rwxr-xr-x 1 dan staff 1087444 Jan  3 12:19 points2finetriangs
  -rwxr-xr-x 1 dan staff 1087428 Jan  3 12:19 points2flips
  -rwxr-xr-x 1 dan staff 1087452 Jan  3 12:19 points2nallfinetriangs
  -rwxr-xr-x 1 dan staff 1087444 Jan  3 12:19 points2nalltriangs
  -rwxr-xr-x 1 dan staff 1087444 Jan  3 12:19 points2nfinetriangs
  -rwxr-xr-x 1 dan staff 1087436 Jan  3 12:19 points2nflips
  -rwxr-xr-x 1 dan staff 1087436 Jan  3 12:19 points2ntriangs
  -rwxr-xr-x 1 dan staff  442888 Jan  3 12:19 points2placingtriang
  -rwxr-xr-x 1 dan staff 1087436 Jan  3 12:19 points2triangs
  -rwxr-xr-x 1 dan staff  454728 Jan  3 12:19 points2volume
  -rwxr-xr-x 1 dan staff  544752 Jan  3 12:19 santos_22_triang
  -rwxr-xr-x 1 dan staff  562000 Jan  3 12:19 santos_dim4_triang
  -rwxr-xr-x 1 dan staff  549736 Jan  3 12:19 santos_triang
  -rwxr-xr-x 1 dan staff  485812 Jan  3 12:19 B_A_center
  -rwxr-xr-x 1 dan staff  489892 Jan  3 12:19 B_D
  -rwxr-xr-x 1 dan staff 1087444 Jan  3 12:19 chiro2allfinetriangs
  -rwxr-xr-x 1 dan staff 1087436 Jan  3 12:19 chiro2alltriangs
  -rwxr-xr-x 1 dan staff  417908 Jan  3 12:19 chiro2circuits
  -rwxr-xr-x 1 dan staff  404008 Jan  3 12:19 chiro2cocircuits
  -rwxr-xr-x 1 dan staff  371184 Jan  3 12:19 chiro2dual
  -rwxr-xr-x 1 dan staff  460132 Jan  3 12:19 chiro2finetriang
  -rwxr-xr-x 1 dan staff 1087444 Jan  3 12:19 chiro2finetriangs
  -rwxr-xr-x 1 dan staff  533216 Jan  3 12:19 chiro2mintriang
  -rwxr-xr-x 1 dan staff 1087452 Jan  3 12:19 chiro2nallfinetriangs
  -rwxr-xr-x 1 dan staff 1087444 Jan  3 12:19 chiro2nalltriangs
  -rwxr-xr-x 1 dan staff 1087444 Jan  3 12:19 chiro2nfinetriangs
  -rwxr-xr-x 1 dan staff 1087436 Jan  3 12:19 chiro2ntriangs
  -rwxr-xr-x 1 dan staff  425764 Jan  3 12:19 chiro2placingtriang
  -rwxr-xr-x 1 dan staff 1087436 Jan  3 12:19 chiro2triangs
  -rwxr-xr-x 1 dan staff  435772 Jan  3 12:19 cocircuits2facets
```

**Comment by DanGrayson** [comment]
See https://github.com/Macaulay2/M2/commit/4fbba4912ae0491c153b00cc6dee6216d5c0db63

**Comment by mikestillman** [comment]
Uugh, that is alot.

To start, I need the following 2 only: checkregularity, points2finetriang.

Hopefully, once the structure is in place, if we need more, it is something easy for me to just do.  But I probably won’t be needing many others...

**Comment by mikestillman** [comment]
Thanks!

**Comment by DanGrayson** [comment]
See commit 50b17f74ff4a1b942d8beb87a3e5b793671bafff

**Comment by DanGrayson** [comment]
Please test it now.  Reopen if there's a problem.

**Comment by mikestillman** [comment]
error in build: lrslib.html not found…

make: Entering directory '/Users/mike/src/M2/M2/BUILD/mike/builds.tmp/darwin64-gcc4.9/libraries/lrslib/build/lrslib-062'
+ for p in lrs
+ set -x
+ /usr/bin/install -c lrs /Users/mike/src/M2/M2/BUILD/mike/builds.tmp/darwin64-gcc4.9/usr-host/bin
/usr/bin/install -c -d /Users/mike/src/M2/M2/BUILD/mike/builds.tmp/darwin64-gcc4.9/usr-host/licenses/lrslib
set -e ; cd build/lrslib-062 && for p in lrslib.html COPYING ; do (set -x ; /usr/bin/install -c -m 644 "$p" /Users/mike/src/M2/M2/BUILD/mike/builds.tmp/darwin64-gcc4.9/usr-host/licenses/lrslib) ; done
+ /usr/bin/install -c -m 644 lrslib.html /Users/mike/src/M2/M2/BUILD/mike/builds.tmp/darwin64-gcc4.9/usr-host/licenses/lrslib
install: lrslib.html: No such file or directory
make[2]: *** [.installed-062] Error 71
make[2]: Leaving directory `/Users/mike/src/M2/M2/BUILD/mike/builds.tmp/darwin64-gcc4.9/libraries/lrslib'

**Comment by mikestillman** [comment]
It looks like we also need to store the lrslib tar file on uiuc.

**Comment by DanGrayson** [comment]
Yes, storing it there is an issue already.

Fixed the problem in commit a559e30d2a9b0a9d6bb55de9e086527b97b93e70
Author: Daniel R. Grayson <dan@math.uiuc.edu>
Date:   Tue Jan 3 20:21:51 2017 -0600

    fix a makefile

**Comment by mikestillman** [comment]
That was only one aspect. The other one was the build failed in lrslib.

**Comment by DanGrayson** [comment]
The lrslib.html thing is fixed in that commit.

**Comment by mikestillman** [comment]
Oops, yes, thanks!

There a quite a few warnings when building topcom, all of the following form:

ld: warning: directory not found for option '-L/Users/mike/src/M2/M2/BUILD/mike/builds.tmp/darwin64-gcc4.9/submodules/memtailor/.libs'
ld: warning: directory not found for option '-L/Users/mike/src/M2/M2/BUILD/mike/builds.tmp/darwin64-gcc4.9/submodules/mathic/.libs'
ld: warning: directory not found for option '-L/Users/mike/src/M2/M2/BUILD/mike/builds.tmp/darwin64-gcc4.9/submodules/mathicgb/.libs'
ld: warning: PIE disabled. Absolute addressing (perhaps -mdynamic-no-pic) not allowed in code signed PIE, but used in ___gmpn_divexact_1 from ../external/lib/libgmp.a(dive_1.o). To fix this warning, don't compile with -mdynamic-no-pic or link with -Wl,-no_pie

**Comment by DanGrayson** [comment]
The one about .libs not found is just because the libraries are compiled
before the submodules.  I haven't had the
energy to think about it.

Feel free to tell the author of topcom about the last one.

**Comment by mikestillman** [comment]
Just compiled to completion on macosx 10.10.5, gcc 4.9.
