### ISSUE TITLE
ChainComplexExtras bug

### ISSUE THREAD

**Issue by DanGrayson** [Macaulay2/M2#562]
The function `prependZeroMap` unintentionally changes the sign of the differential,
because the operation `C[-1]` intentionally does so.  Now that comparison of chain
complexes has been repaired, a test fails.

```
i1 : loadPackage "ChainComplexExtras"

o1 = ChainComplexExtras

o1 : Package

i2 : R = QQ[x]

o2 = R

o2 : PolynomialRing

i3 : C = chainComplex matrix {{x}}

      1      1
o3 = R  <-- R
             
     0      1

o3 : ChainComplex

i4 : C.dd_1

o4 = | x |

             1       1
o4 : Matrix R  <--- R

i5 : prependZeroMap C

             1      1
o5 = 0  <-- R  <-- R
                    
     -1     0      1

o5 : ChainComplex

i6 : oo.dd_1

o6 = | -x |

             1       1
o6 : Matrix R  <--- R
```

**Comment by DanGrayson** [comment]
resolved by #564

**Comment by mikestillman** [comment]
David, it is possible that your fix broke BGG.  Could you try running the tests (via 'check') for BGG?  I get one error, which seems to indicate that isChainComplexMap is (now) being called incorrectly?  Perhaps a function needs to be able to handle 'infinity', not just elements of ZZ?

**Comment by eisenbud** [comment]
Ouch! Will do.

David
--
David Eisenbud
Director, Mathematical Sciences Research Institute; and
Professor of Mathematics, University of California, Berkeley
www.msri.org/~de

**Comment by mikestillman** [comment]
This appears to have been fixed (as the tests don't fail now), but not closed.  I am closing it.
