### ISSUE TITLE
inverse of a matrix with random CC entries freezes

### ISSUE THREAD

**Issue by DanGrayson** [Macaulay2/M2#57]
Reported by:	anton (on trac)

    i1 : R = CC; inverse map(R^1, R^1, (i,j)->random R)      
    -- warning: experimental computation over inexact field begun
    --          results not reliable (one warning given per session)

    o2 = | .819187-.5071i |

		    1          1
    o2 : Matrix CC    <--- CC
		  53         53

    i3 : R = CC; inverse map(R^2,R^2,(i,j)->random R) -- freezes!

**Comment by mikestillman** [comment]
Hmm, this works in 1.7 ok, and also in master branch.  So I'm closing this issue.
