### ISSUE TITLE
compilation fails on debian 8 when following M2/INSTALL.

### ISSUE THREAD

**Issue by schloegl** [Macaulay2/M2#587]
When trying to compile M2 on debian 8, according to the instructions in M2/INSTALL it fails. 

Unlike the instruction in M2/INSTALL, also the following configuration options were needed:
   `--enable-build-libraries="givaro fflas_ffpack"`

Otherwise it would fail with the following error:

[m2.compile.error.txt](https://github.com/Macaulay2/M2/files/880507/m2.compile.error.txt)

Although the packages were installed: 

> $ dpkg -l|grep givaro
ii  libgivaro-dev                          3.7.2-1                              amd64        arithmetic and algebraic computations - development files
ii  libgivaro1:amd64                       3.7.2-1                              amd64        arithmetic and algebraic computations
$ dpkg -l|grep fflas
ii  fflas-ffpack                           1.6.0-1                              amd64        Finite field linear algebra subroutines/package
ii  fflas-ffpack-common                    1.6.0-1                              all          Finite field linear algebra subroutines/package - common files

I guess this should be fixed in M2/INSTALL.

Unfortunately, that does not seem to be sufficient. There are more errors. Below I've also added the log files for the last runs of 
   make 
and 
   make check 

[make.log.txt](https://github.com/Macaulay2/M2/files/880570/make.log.txt)
[make.check.log.txt](https://github.com/Macaulay2/M2/files/880571/make.check.log.txt)

**Comment by DanGrayson** [comment]
Which branch are you on?

**Comment by DanGrayson** [comment]
I suspect your log files include only stdout and not stderr, so they're hard to analyze.  But perhaps all that happened was that the checking of the package "AnalyzeSheafOnP1" failed.  That shouldn't prevent you from installing and using Macaulay2.

**Comment by DanGrayson** [comment]
I've just built the master branch under Debian 8.  There was one minor problem with the
3rd party program "topcom" not finding the copy of gmp it thought it was building, and I 
fixed that.  All tests succeeded.

**Comment by schloegl** [comment]
I'm using the branch 
     release-1.9.2

attached are the the output of stderr and stdout 
[make.error.txt](https://github.com/Macaulay2/M2/files/884879/make.error.txt)
[make.log.txt](https://github.com/Macaulay2/M2/files/884880/make.log.txt)


I'll try the master branch as well.

**Comment by DanGrayson** [comment]
Show me some of those error output files, such as ../../../usr-dist/common/share/doc/Macaulay2/Macaulay2Doc/example-output/_diff_lp__Matrix_cm__Matrix_rp.errors

I don't understand these errors, since there's no error message preceding them:
```
Makefile:88: recipe for target '/localhome/schloegl/src/M2/M2/usr-dist/x86_64-Linux-Debian-8.7/lib/Macaulay2/x86_64-Linux-Debian-8.7/Macaulay2Doc/.installed' failed
make[2]: Leaving directory '/localhome/schloegl/src/M2/M2/Macaulay2/packages'
Makefile:20: recipe for target 'all-in-packages' failed
make[1]: Leaving directory '/localhome/schloegl/src/M2/M2/Macaulay2'
GNUmakefile:178: recipe for target 'all-in-Macaulay2' failed
make: Leaving directory '/localhome/schloegl/src/M2/M2'
```

**Comment by schloegl** [comment]
`$ cat  usr-dist/common/share/doc/Macaulay2/Macaulay2Doc/example-output/_diff_lp__Matrix_cm__Matrix_rp.errors
-- -*- M2-comint -*- {* hash: -402041375 *}
Segmentation fault
`

**Comment by DanGrayson** [comment]
Okay, the M2 binary doesn't work at all.  There are various possible reasons for this, and
none are easy to determine indirectly.  But if you know how to use a debugger, such 
as gdb, you might be able to figure it out for us.  You could start over and compile it in
debugging mode to get the symbol tables and debugging information retained in the 
binary.

**Comment by mahrud** [comment]
@schloegl is this still an issue for you?
