### ISSUE TITLE
Minor issue: Can't put infinity in matrices

### ISSUE THREAD

**Issue by dibernst** [Macaulay2/M2#588]
Not a big deal, but it would be nice to be able to do something like

`M = matrix{{infinity,0},{0,1}}`

without getting an error message

**Comment by DanGrayson** [comment]
You can do it this way:
```

i8 : matrix {{1/0.,1,2,3}}

o8 = | infinity 1 2 3 |

                1          4
o8 : Matrix RR    <--- RR
              53         53
```

The point is that "infinity" gives you a symbolic infinity, not an element of RR.

**Comment by dibernst** [comment]
Sounds good. Thanks
