### ISSUE TITLE
Endianness issue

### ISSUE THREAD

**Issue by jamesjer** [Macaulay2/M2#589]
While building version 1.9.2 for Fedora 26, the build failed on the ppc64 (big endian) builder.  The issue turns out to be this, from parse-exports.h:

typedef struct parse_Nothing_struct *parse_Nothing;
typedef struct tagged_union *parse_Expr;
struct tagged_union {
  unsigned short type_;
};
struct parse_Nothing_struct BASECLASS {
  unsigned int type_;
};

When accessing the type of parse_nullE via a cast to the tagged_union type, little endian machines get the low order 2 bytes, which happens to work, but big endian machines get the high order 2 bytes, which is 0.  Should line 307 of M2/Macaulay2/c/cprint.c:

       put("unsigned int type_;");

instead be:

       put("unsigned short type_;");

so the type_ field sizes match?

**Comment by DanGrayson** [comment]
Gee, if that's right, how could it ever have worked?  Please try this patch and let me know if you see an improvement:
```
diff --git a/M2/Macaulay2/c/cprint.c b/M2/Macaulay2/c/cprint.c
index dec892917..760246815 100644
--- a/M2/Macaulay2/c/cprint.c
+++ b/M2/Macaulay2/c/cprint.c
@@ -304,7 +304,7 @@ static void cprintobjectdef(node t){
      cprintstructtag(t,TRUE);
      printf(" {");
      if (istaggedobjecttype(t)) {
-       put("unsigned int type_;");
+       put("unsigned short type_;");
        had_a_member = TRUE;
      }
      for (m=typedeftail(t); m != NULL; m = CDR(m)) {
```

**Comment by DanGrayson** [comment]
... or did you already try it?

**Comment by DanGrayson** [comment]
I've applied a fix that ought to work for you.

**Comment by DanGrayson** [comment]
Thanks!
