### ISSUE TITLE
Document the build/test workflow

### ISSUE THREAD

**Issue by DanGrayson** [Macaulay2/M2#59]
Reported by:    charles (on trac)

There should be a wiki page for keeping track of everything involved in the workflow for build/test of M2.

**Comment by mahrud** [comment]
[INSTALL-CMake.md](https://github.com/Macaulay2/M2/blob/master/M2/INSTALL-CMake.md), along with various ["M2 Internals"](https://github.com/Macaulay2/M2/wiki/%22M2-internals%22-notes) notes now accomplish this task. Shall we close this?
