### ISSUE TITLE
crash with SIGSEGV in "res" over CC

### ISSUE THREAD

**Issue by DanGrayson** [Macaulay2/M2#592]
```
idealOfPoints = method()
idealOfPoints (Ring, Matrix) := Ideal => (R,M) -> (
    intersect apply(entries transpose M, r -> minors(2,matrix{gens R,r}))
)
idealOfPoints Matrix := Ideal => M -> idealOfPoints(ring M, M)
R = CC[x,y,z]                   
M = transpose matrix{{0,2,1},{0,-2,1},{1,3,1},{2,0,1},{3,1,1},{5,-1,1},{6,0,1_R}}
I = idealOfPoints(M)
res I        
```

**Comment by mikestillman** [comment]
Fixed, we now give an error message, as of commit c827c47f61f729.  As mentioned in the commit message, it should be possible to implement our non-minimal free resolution code over RR or CC, but someone should request that, if it would be useful, or better, help to implement that!  I'll close this issue, please re-open or open a new git issue if this would be useful to you.
