### ISSUE TITLE
crash in modules over local rings

### ISSUE THREAD

**Issue by gblanco92** [Macaulay2/M2#595]
The following code: 

`R = QQ{t}`
`(1//t)*(R^2)`

crashes in M2 1.9.2 for Mac. In Linux, you get

> stdio:2:7:(3): error: monomial overflow

However, the following seems to work:

`R = QQ{t}`
`M = mutableMatrix(R, 2, 2)`
`M_(0,0) = 1//t`
`image matrix M`

**Comment by DanGrayson** [comment]
Thanks, that looks like a bug.

**Comment by gblanco92** [comment]
The bug reduces to

`R = QQ{t}`
`(1//t)*1`

But everything works if `R = QQ{t, Inverses => true, MonomialOrder => RevLex}`.

I guess the element `1//t` shouldn't be allowed to exist if `Inverses => false` (in the same way as `t^(-1)`)

**Comment by mikestillman** [comment]
Fixed in PR #2493.
