### ISSUE TITLE
emacs: comment with a string (in quotes) does not highlight properly

### ISSUE THREAD

**Issue by antonleykin** [Macaulay2/M2#616]
`-- comment without string`
is fine, but 
`-- comment with "a string" `
does not highlight as a comment

**Comment by DanGrayson** [comment]
It looks fine at this end:
<img width="247" alt="screen shot 2017-05-28 at 3 19 03 pm" src="https://cloud.githubusercontent.com/assets/700228/26531893/114e66d6-43b9-11e7-8a41-2fa3ec1f56e9.png">

**Comment by DanGrayson** [comment]
I'm using emacs 25.1.1

**Comment by antonleykin** [comment]
I have this problem both in 

GNU Emacs 22.1.1 (mac-apple-darwin) of 2017-03-16 on osx338.sd.apple.com

and

Aquamacs 3.3  GNU Emacs 25.1.1 (x86_64-apple-darwin14.1.0, NS appkit-1344.72 Version 10.10.2 (Build 14C109))
 of 2016-09-19 on 24a02dbf6b34ae061ef4df89f15bfbc5d3ed497e

**Comment by DanGrayson** [comment]
Then that indicates it was a bug in emacs that has been fixed.

**Comment by DanGrayson** [comment]
... although, your aquamacs indicates it is up-to-date, since it's 25.1.1.  Hmm...

**Comment by DanGrayson** [comment]
It works at this end in aquamacs:
<img width="609" alt="screen shot 2017-05-28 at 4 00 50 pm" src="https://cloud.githubusercontent.com/assets/700228/26532143/e7d9a166-43be-11e7-884f-d62fd29001ce.png">

**Comment by pzinn** [comment]
I'm afraid this is a side effect of #551. Basically, -- comments are no more considered comments: as explained in #527, emacs only allows 2 types of comment sequences if they share the first character, which is not the case in Macaulay2, -- vs {*. So I suggested to recode -- as normal syntax highlighting, which means the quote highlighting takes priority. I'll provide a fix.

**Comment by DanGrayson** [comment]
See https://github.com/Macaulay2/M2/issues/674 .  The changes in the commits that
resolved that may have resolved this.

**Comment by pzinn** [comment]
so what's the status now? is {* ... *} still valid, or is it only -* ... *-
from now on, potentially breaking old code?

On Sun, Aug 6, 2017 at 10:12 PM, Daniel R. Grayson <notifications@github.com

**Comment by DanGrayson** [comment]
The old syntax still works, but M2-mode in emacs won't attempt to colorize it -- no code 
will break.
```

i1 : {* asdf *} 5

o1 = 5

i2 : -* asdf *- 5

o2 = 5
```

We also fixed the ///.../// string parsing, but mixtures of the two won't work properly, I think.

**Comment by DanGrayson** [comment]
I should have paid more attention to your June 29 message!  We could have come up with the idea then, if I had been attentive.

**Comment by mahrud** [comment]
This issue seems to be fixed.
