### ISSUE TITLE
AlphaTest

### ISSUE THREAD

**Issue by DanGrayson** [Macaulay2/M2#626]
AlphaTest needs a better name and headline.

**Comment by DanGrayson** [comment]
How about "NumericalCertification" for a name and "certifying solutions to square polynomial systems (Smale's alpha test)" for a headline?

**Comment by antonleykin** [comment]
I think what you propose is a good idea -- the package may grow to include other techniques in the future. One should make sure "AlphaTest" gets renamed in several pieces of code elsewhere.

**Comment by DanGrayson** [comment]
okay, thanks.
