### ISSUE TITLE
allow degrees to have torsion

### ISSUE THREAD

**Issue by mikestillman** [Macaulay2/M2#632]
Degrees are currently expected to be elements of ZZ^n.  It would be very useful to allow degrees to be any f.g. Abelian group.  Via smith normal form, we could assume in the engine that the degrees are in ZZ^n x ZZ/n1 x ... x ZZ/nr.

A key application would be for the Cox homogeneous ring of a toric variety, whose class group has torsion.  Currently, we canny handle such rings.

**Comment by mahrud** [comment]
I just realized I've closed this already in https://github.com/Macaulay2/M2/pull/2681 :)
