### ISSUE TITLE
Should symbol ^* be a binary operator?

### ISSUE THREAD

**Issue by kschwede** [Macaulay2/M2#635]
Hi all,

A quick thought that was recently suggested to me.  Currently ^* is a unary postfix operator.  

"used for indicating pullback maps"

Given a ring map, f : R -> S, and given an R-module M, or a sheaf of O_{Spec R}-modules, one typically uses f^* M to denote M pulled back to S.  Ie, M \otimes_R S.  

However, since ^* is a postfix operator, the way I could imagine dealing with this is for f^* to create a function that takes in Modules and outputs Modules.  In particular, it might be valuable for Macalay2 to create a (currently empty) (symbol ^*, RingMap) ringMapPullback method that could be overloaded take in other objects.  Thus other people could overload it so that other things can be pulled back.   I could imagine a number of things could be pulled back via a ring map.

Alternately, one could make ^* a binary operator?

The same issue makes sense for _*

**Comment by DanGrayson** [comment]
Nothing prevents you from installing a method as the method function for f^*, to achieve what you want.  Also, there is ^**, which is binary, and is used for tensor power.

**Comment by kschwede** [comment]
That's true, I guess I'll just do that.  Thanks!

**Comment by DanGrayson** [comment]
Also, I think my framework doesn't allow operators to be both postfix and binary, for some reason that I don't recall.  Closing.  Reopen if desirable.
