### ISSUE TITLE
program detection, gfan and nauty

### ISSUE THREAD

**Issue by DanGrayson** [Macaulay2/M2#639]
Under Arch Linux, the programs `gfan` and `nauty` exist, so we don't have to build them.  We need code in `configure.ac` to detect their presence, so they don't get built.  Then the interface packages that run them have to be modified slightly to find them still.

**Comment by mahrud** [comment]
What is the usual address for `nauty`? On Fedora I only have a bunch of binaries with prefix `nauty-*` and `dreadnaut`. Compiling from source also produces the same, except without the prefix.

**Comment by DanGrayson** [comment]
I don't know.  I guess the person who made the Fedora nauty package decided they should all have a prefix, which is a good idea, since there are so many of them.

**Comment by d-torrance** [comment]
I believe this issue was closed by 4dccf1f and 338a609.
