### ISSUE TITLE
GradedModules don't always have a cache

### ISSUE THREAD

**Issue by jkyang92** [Macaulay2/M2#640]
Some GradedModules are created without a cache. This causes isDirectSum and components to fail with a 'key not found in hash table'. This affects at least `homolgy(ChainComplex)` and `directSum(GradedModule)` (But not `++`).
This leads to the following line of code failing. `isDirectSum directSum(M,N)` where`M` and `N` are graded modules

I presume this can be fixed just by writing an explicit constructor for `GradedModule` that creates the cache, but I was uncertain if there was some reason that this isn't already done.

**Comment by mahrud** [comment]
Fixed in 2be15bbcb61.
