### ISSUE TITLE
configure: error: C compiler cannot create executables due to c++ libs in LDFLAGS

### ISSUE THREAD

**Issue by dimpase** [Macaulay2/M2#654]
While building M2 1.10 from source, I got this problem building memtailor; this happens due to `LDFLAGS` containing C++ libraries (gmpxx), coming from `LIBS` (?), , and `ac_link` fails somewhere early while running configure. Unsetting  `LDFLAGS` in `configure.ac` works:
```
 AC_INIT([memtailor], [1.0]) # package, version, bug-report-email

+SAVE_LDFLAGS=$LDFLAGS
+LDFLAGS=
```
then the same problem occurs while building mathics (and can be fixed in the same way).

These are probably not the right fixes though, as the problem is in how the installations are invoked from the main building script.

**Comment by DanGrayson** [comment]
It would be good if you could figure out the real problem.  How about sending me, by email, the
memtailor config.log that didn't work?

**Comment by dimpase** [comment]
here is what I see (without the hack) while running the main `make`
```
...
/usr/bin/install -c -d submodules/memtailor
make: Entering directory '/mnt/opt/M2/M2/submodules/memtailor'
+ /mnt/opt/M2/M2/submodules/memtailor/configure --prefix=/mnt/opt/M2/M2/usr-host PKG_CONFIG_PATH=/mnt/opt/M2/M2/usr-host/lib/pkgconfig: GTEST_PATH=/mnt/opt/M2/M2/usr-host/include/gtest AR=ar AS=as DLLTOOL=false OBJDUMP=objdump STRIP=strip 'CXXFLAGS=-std=gnu++11 -O2' 'CFLAGS=-std=gnu11 -O2' FFLAGS=-O2 FCFLAGS=-O2 TARGET_ARCH= 'CPPFLAGS=-isystem /mnt/opt/M2/M2/include -isystem /mnt/opt/M2/M2/include -isystem /mnt/opt/M2/M2/usr-host/include  -I/mnt/opt/M2/M2/submodules/memtailor/src  -I/mnt/opt/M2/M2/submodules/mathic/src  -I/mnt/opt/M2/M2/submodules/mathicgb/src  -I/mnt/opt/M2/M2/submodules/fflas_ffpack/src -isystem /usr/include/libxml2      -DNDEBUG' CC=gcc CXX=g++ 'LDFLAGS=-L/mnt/opt/M2/M2/usr-host/lib  -L/mnt/opt/M2/M2/submodules/memtailor/.libs  -L/mnt/opt/M2/M2/submodules/mathic/.libs  -L/mnt/opt/M2/M2/submodules/mathicgb/.libs ' LOADLIBES= LDLIBS= 'LIBS=-lxml2 -llzma -lz  -L/usr/lib/gcc/x86_64-pc-linux-gnu/6.3.0 -L/usr/lib/gcc/x86_64-pc-linux-gnu/6.3.0/../../../../lib64 -L/lib/../lib64 -L/usr/lib/../lib64 -L/usr/lib/gcc/x86_64-pc-linux-gnu/6.3.0/../../../../x86_64-pc-linux-gnu/lib -L/usr/lib/gcc/x86_64-pc-linux-gnu/6.3.0/../../.. -ldl -lgfortran -lm -lquadmath -llapack -lblas -lblas -lgdbm -lgc -lfrobby -lgmpxx -lgmp -lreadline -lncurses -lpthread -ldl ' --with-gtest=yes
checking for gcc... gcc
checking whether the C compiler works... no
configure: error: in `/mnt/opt/M2/M2/submodules/memtailor':
configure: error: C compiler cannot create executables
See `config.log' for more details
make: *** [GNUmakefile:171: submodules/memtailor/Makefile] Error 77
make: Leaving directory '/mnt/opt/M2/M2'
```
And here is the [link](http://users.ox.ac.uk/~coml0531/memtailor_error.log) to the memtailor's config.log.

**Comment by DanGrayson** [comment]
The failing command line was this:
```
gcc -std=gnu11 -O2 -isystem /mnt/opt/M2/M2/include -isystem /mnt/opt/M2/M2/include -isystem /mnt/opt/M2/M2/usr-host/include  -I/mnt/opt/M2/M2/submodules/memtailor/src  -I/mnt/opt/M2/M2/submodules/mathic/src  -I/mnt/opt/M2/M2/submodules/mathicgb/src  -I/mnt/opt/M2/M2/submodules/fflas_ffpack/src -isystem /usr/include/libxml2      -DNDEBUG -L/mnt/opt/M2/M2/usr-host/lib  -L/mnt/opt/M2/M2/submodules/memtailor/.libs  -L/mnt/opt/M2/M2/submodules/mathic/.libs  -L/mnt/opt/M2/M2/submodules/mathicgb/.libs  conftest.c -lxml2 -llzma -lz  -L/usr/lib/gcc/x86_64-pc-linux-gnu/6.3.0 -L/usr/lib/gcc/x86_64-pc-linux-gnu/6.3.0/../../../../lib64 -L/lib/../lib64 -L/usr/lib/../lib64 -L/usr/lib/gcc/x86_64-pc-linux-gnu/6.3.0/../../../../x86_64-pc-linux-gnu/lib -L/usr/lib/gcc/x86_64-pc-linux-gnu/6.3.0/../../.. -ldl -lgfortran -lm -lquadmath -llapack -lblas -lblas -lgdbm -lgc -lfrobby -lgmpxx -lgmp -lreadline -lncurses -lpthread -ldl
```

The program was a C program, so there is no visible reason for any part of libgmpxx.a to be linked in.  Let's find out why it's getting linked in by removing -lgmpxx from the command line and trying again.  Here is the C program:
```
int
main ()
{

  ;
  return 0;
}
```

**Comment by dimpase** [comment]
On 19 Jul 2017 7:29 pm, "Daniel R. Grayson" <notifications@github.com>
wrote:

The failing command line was this:

gcc -std=gnu11 -O2 -isystem /mnt/opt/M2/M2/include -isystem
/mnt/opt/M2/M2/include -isystem /mnt/opt/M2/M2/usr-host/include
-I/mnt/opt/M2/M2/submodules/memtailor/src
-I/mnt/opt/M2/M2/submodules/mathic/src
-I/mnt/opt/M2/M2/submodules/mathicgb/src
-I/mnt/opt/M2/M2/submodules/fflas_ffpack/src -isystem
/usr/include/libxml2      -DNDEBUG -L/mnt/opt/M2/M2/usr-host/lib
-L/mnt/opt/M2/M2/submodules/memtailor/.libs
-L/mnt/opt/M2/M2/submodules/mathic/.libs
-L/mnt/opt/M2/M2/submodules/mathicgb/.libs  conftest.c -lxml2 -llzma
-lz  -L/usr/lib/gcc/x86_64-pc-linux-gnu/6.3.0
-L/usr/lib/gcc/x86_64-pc-linux-gnu/6.3.0/../../../../lib64
-L/lib/../lib64 -L/usr/lib/../lib64
-L/usr/lib/gcc/x86_64-pc-linux-gnu/6.3.0/../../../../x86_64-pc-linux-gnu/lib
-L/usr/lib/gcc/x86_64-pc-linux-gnu/6.3.0/../../.. -ldl -lgfortran -lm
-lquadmath -llapack -lblas -lblas -lgdbm -lgc -lfrobby -lgmpxx -lgmp
-lreadline -lncurses -lpthread -ldl

The program was a C program, so there is no visible reason for any part of
libgmpxx.a to be linked in. Let's find out why it's getting linked in by
removing -lgmpxx from the command line and trying again.

I don't quite understand the suggestion. Gmpxx is getting in from the
LDFLAGS respected by memtailor's configure script.

Imho the question is why the installation of memtailor is being run with
LDFLAGS so set.




Here is the C program:

int
main ()
{

  ;
  return 0;
}

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Macaulay2/M2/issues/654#issuecomment-316475825>, or mute
the thread

**Comment by dimpase** [comment]
I should correct myself: `-lgmpxx` comes from `LIBS`. It's hard for me to say how `LIBS` is formed prior to the attempt at installing memtailor. I don't even know where `LIBS` are hardcoded and when, after running the top `./configure`, or at the other moment,

Could the problem be caused by the updated gtest? (see https://github.com/Macaulay2/M2/issues/653)

**Comment by DanGrayson** [comment]
Let's ignore the value of LIBS for now, and see what's wrong why libgmpxx.a is getting linked in, as I explained above.

**Comment by dimpase** [comment]
I don't know how to implement your proposal, as I don't know how and where
the failing call in question is constructed.

**Comment by dimpase** [comment]
More precisely, all I know that it is coming from some check run by
memtailor's configure early on. I know that if I sanitise LDFLAGS early on
there, everything passes. That is to say, that -lgmpxx there is not needed.
And it must not be there in this particular configuration (some other
compilers/linkers would be OK though).

**Comment by DanGrayson** [comment]
I'd like you to run that single command line, manually, without the -lgmpxx, on the C program the script used, so we can see why something from libgmpxx was linked in.

**Comment by dimpase** [comment]
Ah, right, of course, sorry. In fact, the error boils down to `frobby` installed system-wide.

Specifically, if I remove only `-lgmpxx` then I see a bunch of errors like 
```
/usr/lib/gcc/x86_64-pc-linux-gnu/6.3.0/../../../../lib64/libfrobby.so: undefined reference to `operator<<(std::ostream&, __mpq_struct const*)'
```
And if I also remove `-lfrobby` then the test passes. Indeed, I do have `/usr/lib64/libfrobby.so`,  more precisely Gentoo's `sci-mathematics/frobby-0.9.0-r2` installed (from a failed attempt to install M2 Gentoo's package---but indeed one cannot assume it is not there.)

After removing `sci-mathematics/frobby-0.9.0-r2`, the build completes.

**Comment by DanGrayson** [comment]
Presumably, when M2/configure was checking for frobby, the linking worked.  So now the difference must be that -lgmpxx finds the library from the mpir library that we compile.  In that case, the correct work-around would be for you to arrange for us to build frobby, too.  Could you add --enable-build-libraries=frobby to the top level configure script command line and try again?  If that works, we should arrange to build frobby ourselves as long as we are building gmp or mpir.

**Comment by dimpase** [comment]
I tried (with frobby re-installed system wide) to add  --enable-build-libraries=frobby, as you write, and this works; so indeed, this is a workaround.

The linking of C++ libraries works if done with g++, not with gcc (unless it is a "fake" gcc, like on latest versions of OSX). 

I am confused by the fact that with frobby installed, and linked againts libgmpxx installed systemwide, they both get automatically added to the list of libraries to link against, even if the linker won't handle C++ libraries; looks like a bug to me, but I might be wrong (e.g. it might be that such a configuration won't work due to GC limitations). If you aim at allowing M2 to use systemwide mpir(xx)/gmp(xx), then this seems to be something to look into in more detail.

**Comment by DanGrayson** [comment]
There is no difference between a C++ library and a C library, as far as the linker is concerned.  The problem must be an incompatibility between the system libgmpxx library and the one we build.

I'll take care of arranging for frobby to be built, as long as we are building gmp or mpir, and then we can close this issue.

**Comment by dimpase** [comment]
This still seems to be not fixed...

**Comment by DanGrayson** [comment]
Try now...
