### ISSUE TITLE
tensor product of rings sharing a variable

### ISSUE THREAD

**Issue by craicu** [Macaulay2/M2#655]
The following gives rise to a potential confusion when constructing tensor products (or the natural maps from the factors to the tensor products) of rings sharing a subset of the variables.

R1 = QQ[a]
R2 = QQ[a]
R = R1 ** R2
dim R     --M2 recognizes that the dimension of the tensor product is two
i1 = map(R,R1)
i2 = map(R,R2)
i1(R1_0) - i2(R2_0)     --M2 doesn't make the distinction between the two copies of a

**Comment by DanGrayson** [comment]
Yes, that's confusing, but the confusing aspect comes from depending on Macaulay2
to look at the names of the variables when constructing the maps i1 and i2.  There are
more reliable ways to make maps.

**Comment by craicu** [comment]
Is the following construction safe, or are there circumstances when the tensor product arranges the variables in unexpected ways?

R = R1 ** R2
n1 = numgens R1
n2 = numgens R2
i1 = map(R,R1,apply(n1, j -> R_j))
i2 = map(R,R2,apply(n2, j -> R_(n1+j)))

**Comment by DanGrayson** [comment]
That ought to work in all cases.

Closing.
