### ISSUE TITLE
embedded hash_map in embedded frobby fails to build on MacOS Mavericks

### ISSUE THREAD

**Issue by tom111** [Macaulay2/M2#66]
Hi,
I'm compiling the latest git on MacOS Mavericks. The compiler is llvm from Xcode:

gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 5.0 (clang-500.2.79) (based on LLVM 3.3svn)
Target: x86_64-apple-darwin13.0.2
Thread model: posix

When compiling the automatically downloaded frobby, it fails as follows

In file included from src/hash_map/hash_map:64:
src/hash_map/hashtable.h:79:14: error: no member named '_Construct' in namespace
      'std'
  using std::_Construct;
        ~~~~~^
src/hash_map/hashtable.h:80:14: error: no member named '_Destroy' in namespace
      'std'
  using std::_Destroy;
        ~~~~~^
src/hash_map/hashtable.h:84:14: error: no member named '__iterator_category' in
      namespace 'std'
  using std::__iterator_category;
        ~~~~~^

and so on... Is this supposed to work, or is gcc mandatory?

**Comment by mahrud** [comment]
Closing this, as I assume frobby is working now. Please reopen if I'm mistaken.
