### ISSUE TITLE
setting the print width for M2 in an emacs buffer

### ISSUE THREAD

**Issue by DanGrayson** [Macaulay2/M2#661]
In M2.el it would be better to use window-body-width instead of window-width because it
gives the width of the buffer.

But both ignore font size changes accomplished with text-scale-adjust, so
perhaps that's an emacs bug.

**Comment by mahrud** [comment]
From [here](https://www.gnu.org/software/emacs/manual/html_node/elisp/Window-Sizes.html):
> For compatibility with previous versions of Emacs, window-height is an alias for window-total-height, and window-width is an alias for window-body-width. These aliases are considered obsolete and will be removed in the future.
