### ISSUE TITLE
M2 emacs info doc not indexed in rpm based OS's

### ISSUE THREAD

**Issue by DanGrayson** [Macaulay2/M2#678]
I'll take care of this while preparing the distribution for an RPM based system.

**Comment by mahrud** [comment]
What is the "M2 emacs info doc"? Is this issue still relevant?

**Comment by mahrud** [comment]
Should this be done in this release?

**Comment by DanGrayson** [comment]
It would be good to finally take care of that -- I'll try.

**Comment by DanGrayson** [comment]
I built M2 under Fedora and tried the rpm out  ---   it updated the info doc "dir" file just fine, so closing.
