### ISSUE TITLE
Install instructions for macOS

### ISSUE THREAD

**Issue by zteitler** [Macaulay2/M2#680]
The install instructions for macOS give some out-of-date directions for brew.

1. homebrew/versions and homebrew/homebrew-x11 are deprecated.

2. brew no longer has a formula named gmake. There are `homebrew/dupes/make` (perhaps with `--with-default-names` option?) and `remake`.

3. A question, would it be suitable to install gcc-4.8 or gcc-4.9 via brew with the `--build-from-source` (or `-s`) option? E.g., `brew install -s gcc@4.9`. If this is acceptable, it would be simpler than the current directions for "compiling the most recent GNU C compiler" (which by the way is not really accurate; gcc is up to 7.1). (The compiling directions would have to stay for non-mac systems, but macs might as well use brew I think.)

**Comment by DanGrayson** [comment]
Thanks, I've fixed the INSTALL file.

Using "-s" with "brew" would work, but it would just slow things down.

**Comment by mikestillman** [comment]
We compile fine with the clang++ on the mac too, or the latest one through brew.

**Comment by zteitler** [comment]
I thought gcc would need to be built from source, because (at least on my laptop) `brew install gcc@4.9` results in a gcc that doesn't catch exceptions. But if clang++ or other approaches work, great.
