### ISSUE TITLE
Homepage and repositories down

### ISSUE THREAD

**Issue by dadexix86** [Macaulay2/M2#689]
I get a Page not Found when I try to access the homepage (or any other page indexed by search engines).

I found the problem when trying to update my Ubuntu distro and receiving an error from Macaulay2 repository.

See screenshot here: http://imgur.com/a/YcJuy

**Comment by DanGrayson** [comment]
Thank you, I've already reported it to the webmaster, who introduced a new math department web page today and must have broken the link.  Meanwhile, please use our [mirror](www2.macaulay2.com).

**Comment by DanGrayson** [comment]
It's been fixed.

**Comment by dadexix86** [comment]
Thank you!

Davide Alberelli

Il 25 ago 2017 15:32, "Daniel R. Grayson" <notifications@github.com> ha
scritto:
