### ISSUE TITLE
Unexpected type: Tally + Set

### ISSUE THREAD

**Issue by aarondall** [Macaulay2/M2#690]
The types `Tally` and `Set` have  youngest common ancestor `Tally`, so intuitively this should be the type of their sum. Instead the sum defaults to their second youngest common ancestor `HashTable`. 

> i1 : class (set {1} + tally {1}) === Tally
> o1 = false
> i2 : class (set {1} + tally {1}) === HashTable
> o2 = true

The same behavior occurs for `VirtualTally + Thing` when `class (Thing)` is either `Tally` or `Set`, and also when `+` is replaced by `-`.  

Is this a bug? Or a safeguard in place because the operations `+` and `-` behave so differently on these classes?

**Comment by DanGrayson** [comment]
Thanks for the report!  Here is the code:
```
     ../src/M2/M2-Macaulay2/M2/Macaulay2/m2/set.m2:29:33-29:46: --source code:
     Tally + Tally := Tally => (x,y) -> merge(x,y,plus)
```
I should fix the function "merge" so the class of the result is the least common ancestor of the classes of x and y.  Also it seems that Tally and VirtualTally should trade places in the hierarchy:
```
i9 : showStructure ( Tally, VirtualTally , Set )

o9 = Thing : HashTable : Tally : Set
                                 VirtualTally
```

**Comment by aarondall** [comment]
There is similar weirdness for scalar products of different types of tallies. Is it better to file those as their own issue or simply add them to this one?

**Comment by DanGrayson** [comment]
Please add them here.

**Comment by aarondall** [comment]
An integer *n* times a `Set` should be a `Set` if and only if  *n* is zero or one. In the former case, it should be the empty set, `set{}`. But we have the following instead. For any other positive integer, it should either be undefined or a tally.

>i1 : s0 = (0 * set{3})
>o1 = set {3}
>o1 : Set

>i2 : s0 === set {}
>o2 = false

Taking a peek at `s0` shows why

>i3 : peek s0
>o3 = Set{3 => 0}

Multiplying a set by `1` gives the expected result.

>i4 : s1 = (1 * set{3})
>o4 = set {3}
>o4 : Set

>i5 : s1 === set {3}
>o5 = true

Multiplying by integers greater than `1` gives a hash table that looks like a tally but is of type `Set`.

>i6 : s2 = (2 * set{3})
>o6 = set {3}
>o6 : Set

>i7 : s2 === set {3}
>o7 = false

>i8 : peek s2
>o8 = Set{3 => 2}

>i9 : s2 === tally {3,3}
>o9 = false

Multiplying a (`Virtual`)`Tally` by 0 gives an "empty but not empty" result similar to that of `0*Set`.

**Comment by pzinn** [comment]
I'm on a mission to fix all these simple issues! Now before I submit a pull request for this one, a question: why is it that `merge` refuses `MutableHashTable` as input? (this is all in evaluate.d:1660) It's particularly strange considering afterwards (in evaluate.d) it declares the output to be mutable iff the first input is (which it isn't, since it would've produced an error message at the start).

**Comment by pzinn** [comment]
I'm going to take a guess that mutable was refused precisely because it couldn't handle mixed mutable/unmutable input, and go ahead and submit.

**Comment by aarondall** [comment]
Thanks for your work on this! 

Some while back Dan wrote:

> I should fix the function "merge" so the class of the result is the least common ancestor of the classes of x and y. Also it seems that Tally and VirtualTally should trade places in the hierarchy:
> 
> i9 : showStructure ( Tally, VirtualTally , Set )
> 
> o9 = Thing : HashTable : Tally : Set
>                                  VirtualTally

Will this be implemented?

**Comment by pzinn** [comment]
I agree there's a logical inconsistency here, since clearly a Tally is a particular kind of VirtualTally (a nonnegative one), but not vice versa. But this requires a decision to be made by the Authorities, so I will not implement for now.
