### ISSUE TITLE
syntax error in Graphs package

### ISSUE THREAD

**Issue by d-torrance** [Macaulay2/M2#693]
I get the following error when I attempt to load the Graphs package:

    Macaulay2, version 1.10
    with packages: ConwayPolynomials, Elimination, IntegralClosure, InverseSystems,
                   LLLBases, PrimaryDecomposition, ReesAlgebra, TangentCone

    i1 : loadPackage "Graphs"
    Graphs.m2:3:48:(3):[7]: error: syntax error at 'of'
    stdio:1:1:(3): --backtrace: parse error--

**Comment by d-torrance** [comment]
I think this *probably* is related to #694, as Graphs loads SimplicialComplexes. In fact, when I type the error message from SimplicialComplexes into M2, I get exactly the Graphs error message:

    i2 : recursion limit of 300 exceeded
    stdio:2:17:(3): error: syntax error at 'of'

**Comment by DanGrayson** [comment]
I can't reproduce your problem here.  Try adding `-q` to the command line.
