### ISSUE TITLE
Debian (Wheezy) packages are missing

### ISSUE THREAD

**Issue by tom111** [Macaulay2/M2#696]
Hi,
I pointed our sysadmin to this page 
http://www2.macaulay2.com/Macaulay2/Downloads/GNU-Linux/Debian/index.html
so that he can installs M2 on a compute server running Debian Wheezy. He came back saying that the repository does not work / contain a package.
What is the status of these Debian builds? (I see some issues related to Debian here in the tracker...)

**Comment by DanGrayson** [comment]
Oh, yes, that's Debian 7, and we're already up to Debian 9, so I deleted the older ones.
