### ISSUE TITLE
package PruneComplex

### ISSUE THREAD

**Issue by DanGrayson** [Macaulay2/M2#717]
Various documentation nodes in the package PruneComplex have example code that uses functions of the package that are not exported, such as `freeRes`, and to get access to the functions, the example code starts off with the line `debug needsPackage "PruneComplex"`.  In general, the users should not be exposed to undocumented, unavailable functions in the documentation.

**Comment by mahrud** [comment]
The intention behind using `freeRes` in the documentation was to make an intentionally non-minimal resolution and give a demonstration of pruning. In particular, for the example in the help page of `PruneComplex`, since the ideal is homogeneous, using `res` would already give a minimal resolution.
On the other hand, I didn't want to export `freeRes` because it's otherwise useless.
Any suggestions on what would be a good compromise?

**Comment by DanGrayson** [comment]
Can you think of a way of using `res(...,FastNonminimal=>true)` instead of `freeRes` in the documentation?  Since all you want is a nonminimal resolution, perhaps you can settle for a different one, for demonstration purposes.

Since `freeRes` is not documented, the use of it in documentation will confuse the user, who won't know what it does.

**Comment by mahrud** [comment]
That's exactly what `freeRes` does, so I copied the contents of `freeRes` in the two examples that used it and to provide some clarity added some comments within the example.
The commit is here: https://github.com/mahrud/M2/commit/54bdb47f8fa403cadb073e041eb17232ebbc1fec
I think I have access to push now, but I'm not sure what's the best way to push only this commit and not the other changes in my local repository. Do you know of any easy solutions?

**Comment by DanGrayson** [comment]
What you want to do is to bring your master branch up to date with ours, then make a new branch based on it.  To that branch, you can add the changes desired, using, for example, `git cherry-pick`.  Once the branch contains the changes you want us to have, you submit a pull request on github.  You don't have push access to our repository.  (I hope!)

**Comment by mahrud** [comment]
Sorry for the delay--grad apps are time-consuming!
Let me know if there are any other changes I should make.

**Comment by DanGrayson** [comment]
I have nothing further to recommend.
