### ISSUE TITLE
package ReflexivePolytopesDB depends on web site

### ISSUE THREAD

**Issue by DanGrayson** [Macaulay2/M2#731]
The package ReflexivePolytopesDB depends on the web site http://quark.itp.tuwien.ac.at ,
so when it's down (as now) our overnight tests fail.

How long will it be down?

Is the database too big to incorporate into M2 distributions?

**Comment by k1-hedayati** [comment]
I was trying to install M2 and had a back luck with that server as well. There is a feature in Github called LFS that is basically an storage for large files like this. Maybe it can help fixing this issue.
https://git-lfs.github.com/

Related: #664, #663

**Comment by k1-hedayati** [comment]
I've started a wget with unlimited retries to get the file as soon as the server comes back, when I get the it I'll try add that using LFS.
If LFS doesn't work there other options such as Dropbox, Drive or even S3, they're not ideal but at latest availability is granted.

**Comment by k1-hedayati** [comment]
Server came back online and I downloaded the file, it was just 600KB, I think it's totally fine to add it directly to git repository, I was thinking the file is larger than 100MB. 
I wanted to remove the download part and replace it with existing file but I have no idea how to do it.
https://github.com/Macaulay2/M2/blob/master/M2/Macaulay2/packages/ReflexivePolytopesDB.m2#L118

**Comment by mikestillman** [comment]
I’m a little confused.  The Kreuzer skarke database is many gigabytes.  We can’t easily store those, and even if we could, we are using their web interface to return the (usually small) amount of data we need.

We could write the package so that if the web access fails, it tries the few cases that we have stashed.  That would work, but would not inform us that the web interface is no longer working (if they change something).

But it is a pain that the M2 build fails, since it can’t access the web.

Mike

**Comment by k1-hedayati** [comment]
This is my first time compiling M2 so I'm not sure about details, when compiling M2 tries to download following file:
http://hep.itp.tuwien.ac.at/~kreuzer/pub/K3/RefPoly.d3
And this file is 600KB so it's possible to add it to repository. 
I don't know [what this function of this line](https://github.com/Macaulay2/M2/blob/c27ce84b40dccb61bfc8fdb62093a976bbacfa3a/M2/Macaulay2/packages/ReflexivePolytopesDB.m2#L119), you might be mentioning that one.

**Comment by mikestillman** [comment]
Ahh, that one we could  include directly, I agree.  But the examples will still fail, if the web site is down, or you are offline, even if we include that, as it also tries to get a 4d polytope, and that will then fail.

One way to get around getting this error while running the examples, is when you compile M2, run 'make -k' (or 'gmake -k' on a mac), then errors will not stop the build.  Afterwords (assuming you ran that command in emacs), you can search for errors by looking for *** (3 stars in a row). This catches all errors, but possibly a few non-errors as well, so you need to look at the output to see what errors you found.

**Comment by mikestillman** [comment]
The newest version of `ReflexivePolytopesDB` pushed in commit ecad39b305ab6fd167 includes the dim=3 file mentioned above, and also does not access the web during install or doing tests.  There is a function `onlineTests()` that checks the actual connection, that one can run if desired.  Finally, the interface has changed, and the package is not version 1.0.
