### ISSUE TITLE
inconsistency in enginering.m2

### ISSUE THREAD

**Issue by pzinn** [Macaulay2/M2#739]
At the moment, one cannot do the following:
```
i1 : R=ZZ[x]

o1 = R

o1 : PolynomialRing

i2 : x/2
stdio:2:2:(3): error: can't promote number to ring
```
Considering how enginering.m2 tries so hard to promote various rings in order to make sense of products, sums, quotients, etc, this seems a bit surprising.
Indeed, the problem can be traced back to the following excerpt from enginering.m2:
```
RingElement / Number := frac0 @@ promoterightexact
InexactNumber / RingElement := frac0 @@ promoteleftinexact
RingElement / InexactNumber := RingElement / Number := (f,g) -> (1/g) * f
```
note how RingElement / Number is defined twice; removing the second definition, we get the expected behavior:
```
i1 : R=ZZ[x]

o1 = R

o1 : PolynomialRing

i2 : x/2

     x
o2 = -
     2

o2 : frac(R)
```

**Comment by DanGrayson** [comment]
Good catch!  Although, it might surprise the user to have x/2 end up in the fraction ring instead of in the ring.  I've removed it.

**Comment by pzinn** [comment]
Ah, oops! you're right, it's not that simple. if say R=QQ[x], we want x/2
to be in R, not in frac R.
so this requires some thought.

**Comment by DanGrayson** [comment]
Oops, you're right.  I've undone it.

**Comment by pzinn** [comment]
how about
RingElement / Number := (f,g) -> if member(QQ,(ring f).baseRings) then (1/g)*f else frac0@@promoterightexact(f,g)
?

**Comment by DanGrayson** [comment]
That seems too tricky, in the sense that users used to the behavior of x/2 in QQ[x] will be startled by the appearance of frac(ZZ[x]) when using ZZ[x].

Maybe the current behavior is the "right" one.

**Comment by pzinn** [comment]
all right I give up on this one. on to my next issue :-P

**Comment by DanGrayson** [comment]
On second thought, it now seems odd to me that x/2 doesn't end up in a fraction ring if 2/x, x/y, and 4/2 do, so in commit c2fe9aaf0fd8d72866298c1959ad48d80757fd34 I make it uniform: they all end up in a fraction ring.

**Comment by mikestillman** [comment]
I just rebuilt M2 (on master), and SchurRings has 9 failing examples, possibly all related to this change.  So I'm reopening the issue.  This might just be a simple change in that package.

**Comment by DanGrayson** [comment]
We had lots of failures in the overnight test.  In commit 3e329d60815da32442a69b29066b0ab26b8862f7 I undo it.

**Comment by pzinn** [comment]
since this got reopened, another variant of my solution above (slightly more robust)
RingElement / Number := (f,g) -> try (1/g)*f else frac0@@promoterightexact(f,g)

**Comment by DanGrayson** [comment]
I think of that as less robust, since "try" masks all errors, even ones the user may wish to see, and since the type of the return value depend on whether there was an error.
