### ISSUE TITLE
Vector stuff

### ISSUE THREAD

**Issue by pzinn** [Macaulay2/M2#745]
some minor Vector issues. I will submit a patch now for 1-3.

1. "vector Matrix" isn't defined.

2. Inversely, "new Vector from Matrix" is defined by ignoring the first argument completely, which is a bit ridiculous:
```
new Vector from Matrix := (M,f) -> (
     if not isFreeModule source f or numgens source f =!= 1 then error "expected source to be free with rank 1";
     if M === Vector then error "expected a module";
     new target f from {f})
```
Might as well use "vector Matrix", then. Otherwise one should perform checks on M, so we don't end up defining nonsensical things like
```
i4 : R=QQ[x,y,z]; new R^3 from matrix {{x}}

o4 = | x |

      3
o4 : R
```
(note that the fact that we write "new target f" at the end rather than M doesn't even imply that the class will be corrected to the right module)

3. "Vector % Ideal" isn't defined.

4. Incidentally, why is it that Matrix % Ideal has a different definition depending on whether the number of rows of the matrix is equal to 1 or not? (in matrix1.m2) Shouldn't one decide once and for all which definition is better and stick to it?

**Comment by DanGrayson** [comment]
@pzinn - I see two new unmerged commits mentioning this issue.  Do you want them to go in?

**Comment by pzinn** [comment]
Yes I was traveling and had no time to wrap this up. I will submit a PR this week.

**Comment by DanGrayson** [comment]
Okay, that will be good, because 1.11.1 is about to come out.

**Comment by pzinn** [comment]
Actually I think I must've referred to the wrong issue, or something of the sort. In any case, the one that I'm working on is #782. closing again.
