### ISSUE TITLE
Comprehensive Documentation

### ISSUE THREAD

**Issue by jasonmlutz** [Macaulay2/M2#75]
It would be helpful to be able to compile the documentation for M2 along with all of the packages included in the distribution. My understanding is that there is already a script that compiles the documentation for posting on the M2 website, so perhaps this could be modified so that users could compile more documentation on a local machine.

(from discussions at the 2014 M2 workshop in Berkekey)

**Comment by DanGrayson** [comment]
It's hard to tell what feature is being requested here.   So closing, but reopen if something still is needed.
