### ISSUE TITLE
factor a monomial in ring with inverses

### ISSUE THREAD

**Issue by aarondall** [Macaulay2/M2#752]
`factor` works as expected on monomials over polynomial rings with `Inverses => false`:

```
i1 : R = ZZ[a,b];
i2 : factor R_{1,1}
o2 = (b)(a)

i3 : S = newRing (R, MonomialOrder => GLex);
i4 : factor S_{1,1}
o4 = (b)(a)
```

But when `Inverses => true` monomials do not get factored.

``` 
i5 : T = newRing (S, Inverses => true);
i6 : factor T_{1,1}
o6 = (a*b)
```

**Comment by pzinn** [comment]
This is working as expected. the monomials are invertible elements in the second case, and therefore not part of the factorization.

**Comment by aarondall** [comment]
Ah, of course! Thanks for clearing that up!
