### ISSUE TITLE
RandomObjects problem

### ISSUE THREAD

**Issue by DanGrayson** [Macaulay2/M2#753]
The package RandomObjects exports a symbol called "Certification", which obscures the core symbol of the same name, so that loading RandomObjects first and then a certified package results in an error like this:
```
MonomialAlgebras.m2:3:1:(3):[10]: error: encountered an unknown key or option: Certification
```

**Comment by d-torrance** [comment]
This was fixed in https://github.com/Macaulay2/M2/commit/f27c50b986ac5580713bb9d5c5a7be07bc60323c.
