### ISSUE TITLE
block comments

### ISSUE THREAD

**Issue by DanGrayson** [Macaulay2/M2#754]
With the release of 1.12, we will take the opportunity to disable the old style of block comments, which are currently deprecated, see https://github.com/Macaulay2/M2/issues/674

**Comment by mikestillman** [comment]
When did we change over to the new block comment syntax?  I thought that 1.10 still only used the old style? (I’m not 100% sure of that though) If so, we should wait another release at least, I think.

**Comment by DanGrayson** [comment]
Right, but 1.11 has the new style.  So 1.12 can get rid of the old.

**Comment by DanGrayson** [comment]
resolved by commit bc59b7532bcaf74c95fae12b35cafd36e8934612
