### ISSUE TITLE
Degree lost in ring over a fraction field

### ISSUE THREAD

**Issue by pzinn** [Macaulay2/M2#760]
A bug/feature I just came across.
Compare
```
i1 : R=QQ[x,y,DegreeRank=>2]

o1 = R

o1 : PolynomialRing

i2 : degree y

o2 = {0, 1}

o2 : List

i3 : R2=R[z]

o3 = R2

o3 : PolynomialRing

i4 : degree(y*z)

o4 = {1, 0, 1}

o4 : List
```
M2 has correctly concatenated the degree rings; and:
```
i1 : R=frac(QQ[x,y,DegreeRank=>2])

o1 = R

o1 : FractionField

i2 : degree(x/y)

o2 = {1, -1}

o2 : List

i3 : R2=R[z]

o3 = R2

o3 : PolynomialRing

i4 : degree(y*z)

o4 = {1}
```
this time the degree ring of R has mysteriously disappeared...

**Comment by DanGrayson** [comment]
Yes, but this time R is a field, so it's not a graded ring, and there's no use pretending it is.

**Comment by pzinn** [comment]
hmm good point. it's still a bit confusing that R has a degrees ring then but not R2.
OK closing.

**Comment by DanGrayson** [comment]
Well, that is confusing.  Maybe we should fix "frac" so its degree length is 0.

Reopening for that purpose.

**Comment by mikestillman** [comment]
Maybe, but it is useful to be able to determine the degree of a fraction.

One problem we have is that coefficient rings (e.g. finite fields, QQ, ZZ, and fraction fields, I think) are not graded: a free module cannot be given other gradings.  One can get away with this by doing something like:  kk = ZZ/101; A = kk[], to get a polynomial ring, which does have graded modules.

We used to allow all rings to have graded modules, but for some reason, we changed this behavior probably 15-20 years ago.  I forget why.

**Comment by pzinn** [comment]
Originally I was thinking, either (1) neither R = frac (...) nor R2=R[...] should have a degree ring or (2)  both should.
And I agree with Mike that degrees of fractions are useful (i.e., there's still a torus acting on R=frac(...), and even though it doesn't form a graded ring, there are still elements that happen to be eigenvectors of the torus action, and then we call "degree" their weight). Then (2) seemed the correct solution to me.
But as Dan pointed out, keeping the degree ring of R in R2 makes it a weird hybrid object, a ring with a degree ring that's not a graded ring...

**Comment by pzinn** [comment]
The more I think about it, the more I think it's fine as is. Anyway I'll let you guys decide to close as you see fit.
