### ISSUE TITLE
runLengthEncoding failing on subscripted variables

### ISSUE THREAD

**Issue by pzinn** [Macaulay2/M2#765]
another easy one:
```
i1 : R=QQ[a..e]; describe R

o1 = QQ[a..e, Degrees => {5:1}, Heft => {1}, MonomialOrder => {MonomialSize => 32}, DegreeRank => 1]
                                                              {GRevLex => {5:1}  }
                                                              {Position => Up    }
```
but:
```
i1 : R=QQ[x_1..x_10]; describe R

o1 = QQ[x , x , x , x , x , x , x , x , x , x  , Degrees => {10:1}, Heft => {1}, MonomialOrder => ...]
         1   2   3   4   5   6   7   8   9   10                                                  
                                                                                                 
```
`runLengthEncoding` didn't do his job in the second case (should be x_1..x_10). the reason seems to be that it is given as input R.generatorExpressions, which in the case of subscripted variables are "Expression of class Subscript", and seems to expect "IndexedVariable" instead.

will work on this one next

**Comment by pzinn** [comment]
I'm still working on that one. tried various fixes, but not satisfied yet. I suspect only a complete rewrite would solve all the problems.

**Comment by DanGrayson** [comment]
Great, thanks!

**Comment by DanGrayson** [comment]
runLengthEncoding should handle both subscript expressions and indexed variables, right?
