### ISSUE TITLE
RationalMaps still references invertBirMap

### ISSUE THREAD

**Issue by jkelleyy** [Macaulay2/M2#770]
This was breaking the documentation for me. The changes file seems to suggest that `invertBirMap` has been replaced with `inverseMap` so I've attached a patch that replaces all references to `invertBirMap` with `inverseMap`. I didn't know whether to make a pull request since I'm not in charge of the package.
[0001-replace-references-to-invertBirMap-with-inverseMap.txt](https://github.com/Macaulay2/M2/files/1901371/0001-replace-references-to-invertBirMap-with-inverseMap.txt)

**Comment by kschwede** [comment]
Please go ahead and change it. Or let me know if you want me to.

Best wishes

Karl
