### ISSUE TITLE
GMP 5.1.1. and MPFR 3.0.1 are not compatible?

### ISSUE THREAD

**Issue by jakobkroeker** [Macaulay2/M2#79]
when building M2 using GMP instead of mpir, 
I hit following issue

```
In file included from mpfr-impl.h:81:0,
                 from exceptions.c:23:
mpfr.h:181:1: Fehler: unbekannter Typname: »__gmp_const«
[...]
```

**Comment by mahrud** [comment]
Closing this, as it doesn't seem to be an issue anymore with more recent versions. Feel free to reopen if I'm mistaken.
