### ISSUE TITLE
checking a package that needs a new package or a new version of a package

### ISSUE THREAD

**Issue by DanGrayson** [Macaulay2/M2#800]
When Macaulay2 runs examples for a package or checks a package, it does it in a temporary directory, so even though "./" is on the path, it does not find any files that were in the directory where the "check" command was issued.

One workaround is to add a temporary line to the top of the package that prepends the absolute path to the directory where the needed files can be found.

In the long term, we may consider doing that automatically for the user.

**Comment by DanGrayson** [comment]
Maybe we don't have to do anything, see the replies to https://github.com/Macaulay2/Workshop-2018-Leipzig/issues/10

**Comment by mahrud** [comment]
Why not just install the new package, then check the package that depends on the new package?

**Comment by DanGrayson** [comment]
Yes, that's a work-around, closing.
