### ISSUE TITLE
mpz_srcptr

### ISSUE THREAD

**Issue by DanGrayson** [Macaulay2/M2#808]
It would be good to change as many uses of mpz_ptr in the engine to mpz_srcptr as possible (it declares the contents as `const`).  There are also some uses of mpz_t for parameters to functions -- we should reserve it for cases where we actually want to allocate memory for the struct.

Similarly for mpq.

**Comment by mikestillman** [comment]
We should also have another type (typedef at least), for GC collected gmp values?  Perhaps even our current gmp_ZZ, gmp_QQ, gmp_RR, ... 

And also we then need a single function to transform from mpz_t to gmp_ZZ, and, perhaps, one the other direction (although, that is probably just e.g. something like: mpz_init_set(result, gmp_ZZ)).

**Comment by DanGrayson** [comment]
See commit 98ab83f3ab77a95bcb456fd7bc664688ca4cab30

**Comment by mikestillman** [comment]
This has been finished on the `eigen` branch, but I don't want to include it in 1.14 (but will want to merge it in soon after its release).

**Comment by mikestillman** [comment]
I'll close this now.  The engine has changed to using mpz_srcptr, etc, after the eigen branch merge.  Reopen if you think it is not complete.
