### ISSUE TITLE
determining the package of a method function

### ISSUE THREAD

**Issue by DanGrayson** [Macaulay2/M2#818]
Here is an example of a common problem: the package Functoriality defines a method for Tor(ZZ, Matrix, Module), but all of the elements of that are defined in the Core package, so we don't permit the package to document it, and we can't tell that the method function comes from the package.

Even more odd is that the Core defines a method for Tor(ZZ, Matrix, Ideal), which doesn't work unless Functoriality is added.

**Comment by mahrud** [comment]
Related: #192

**Comment by mahrud** [comment]
How come Functoriality is no longer distributed?

**Comment by DanGrayson** [comment]
> How come Functoriality is no longer distributed?

I think it never was.
