### ISSUE TITLE
BoijSoederberg decompose should throw an error

### ISSUE THREAD

**Issue by christineBerkesch** [Macaulay2/M2#823]
The decompose function should throw an error instead of printing
NOT IN THIS SIMPLEX OF PURE BETTI DIAGRAMS
when it cannot decompose.

needsPackage "BoijSoederberg"
t := new BettiTally from { 
    (0,{0},0) => 1, (0,{2},2) => 2, 
    (1,{1},1) => 3, (2,{2},2) => 4, 
    (3,{3},3) => 5, (4,{5},5) => 6, 
    (5,{7},7) => 7, (5,{9},9) => 8 }; 
decompose t

**Comment by DanGrayson** [comment]
fixed in commit 9d2dcf762f1d13ed450ebb97f3261558692d6ec8
```
commit 9d2dcf762f1d13ed450ebb97f3261558692d6ec8 (HEAD -> master)
Author: Daniel R. Grayson <dan@math.uiuc.edu>
Date:   Tue Jun 26 19:19:47 2018 -0400

    convert print statements into errors
```
