### ISSUE TITLE
Better sorting

### ISSUE THREAD

**Issue by tom111** [Macaulay2/M2#830]
Searching for "sort" in this list of all functions https://faculty.math.illinois.edu/Macaulay2/doc/Macaulay2-1.11/share/doc/Macaulay2/Macaulay2Doc/html/___Function.html reveals an entry `sort(List,Function) (missing documentation)` which seems to indicate that there is functionality to sort by user given comparison. However, there does not seem to be an implementation or documentation. It should implement Quicksort. Could it be added? 

I think the second argument should take two objects of the same type and return a `Boolean` that corresponds to "greater or equal".

**Comment by DanGrayson** [comment]
I think that method got onto the list because it's defined in the package `Matroids`, and because we load all the packages while generating the core documentation.  Here's the definition:
```
sort (List, Function) := opts -> (L, f) -> (
	H := hashTable((a, b) -> (a, b), apply(L, l -> f(l) => l));
	deepSplice join apply(sort keys H, k -> H#k)
)
```

**Comment by jchen419** [comment]
Hi Thomas, I wrote this function for the following purpose: given a list L and a function f : L -> T where T is a totally ordered set, sort L by its values under f (if f is not injective, I think the ordering of a single fiber is basically random). It works quite well in certain cases (in particular, sorting by size is essentially instantaneous). This is a little different than the binary method you proposed though - it might be good to implement something like Quicksort as well.

**Comment by mahrud** [comment]
Closing in favor of #1154.
