### ISSUE TITLE
Normaliz improvement

### ISSUE THREAD

**Issue by DanGrayson** [Macaulay2/M2#834]
The routines of the [normaliz library](https://www.normaliz.uni-osnabrueck.de/) are available either through a stand-alone program or through a library.  The Macaulay2 package [Normaliz](https://faculty.math.illinois.edu/Macaulay2/doc/Macaulay2-1.12/share/doc/Macaulay2/Normaliz/html/index.html) currently operates by calling the program, but it might be faster if the library were linked in to the M2 binary and the routines were called directly.

So, an interesting project might be to improve the package by linking with the library.

**Comment by DanGrayson** [comment]
Closing for lack of interest.

**Comment by mikestillman** [comment]
We need to update and improve the list of projects.  GThis would be a good one to add to that list.

**Comment by DanGrayson** [comment]
Well, if somebody would convince us that there really would be a speed-up.
