### ISSUE TITLE
The documentation on the web is missing

### ISSUE THREAD

**Issue by tom111** [Macaulay2/M2#835]
To reproduce, go to 
http://www2.macaulay2.com/Macaulay2/
Search something in the help box on the left.
Click on one of the Google results to get a 404.

Some help page that is missing:
http://www2.macaulay2.com/Macaulay2/doc/Macaulay2-1.12/share/doc/Macaulay2/Macaulay2Doc/html/_help.xhtml

Some help pages are there:
http://www2.macaulay2.com/Macaulay2/doc/Macaulay2-1.12/share/doc/Macaulay2/Visualize/html/

**Comment by DanGrayson** [comment]
I've been failing to convince google to index the pages at https://faculty.math.illinois.edu/Macaulay2/ , so that's responsible for any 404's, as far as I know.

Your example of a missing help page should no longer be returned by google in searches, because it has been indexing www2.macaulay2.com regularly.

**Comment by tom111** [comment]
Hmm, what would be the URL for help then? This one here gives a 404 too:
https://faculty.math.illinois.edu/Macaulay2/doc/Macaulay2-1.12/share/doc/Macaulay2/Macaulay2Doc/html/_help.xhtml

**Comment by DanGrayson** [comment]
Just change xhtml to html.

Where did you find that URL?

**Comment by tom111** [comment]
Oh I just concatenated your base URL with the file name from the google index...

In any case, if you are aware of this and we are just waiting for the google indexer to time out waiting for these pages to come back online, it's OK.  I did not know that the move is intentional.

**Comment by tom111** [comment]
Oh, now I discovered that Google has a lot of .xhtml pages in its index and exactly those are not working. The results that end in .html are working.

**Comment by DanGrayson** [comment]
I was using xhtml pages temporarily, but then switched back to html.  Google will catch up in due course as it reindexes pages.

**Comment by DanGrayson** [comment]
Closing, in favor of #836.
