### ISSUE TITLE
quotient bug

### ISSUE THREAD

**Issue by aarondall** [Macaulay2/M2#841]
For a polynomial ring _R_ with _n_ indeterminates, the socle of the principal ideal _I_ generated by the lcm of the generators (i.e., the quotient of _I_ by the maximal ideal of _R_) is the ideal generated by the set of all products of _n_-1 indeterminates. But for _n_ > 1, M2 incorrectly returns that _I_ is its own socle. 

```
i1 : R = ZZ[a,b];
i2 : I = ideal lcm R_*;
i3 : m = ideal R_*;
i4 : I:m == I
o4 = true
```

**Comment by DanGrayson** [comment]
Let's see, for `a` to be an element of `I:m`, where `I = (ab)` and `m = (a,b)`, we must have `a*m ⊆ I`.  But `a*m = a*(a,b) = (a^2,ab) ⊈ (ab)`.

**Comment by aarondall** [comment]
Of course, you're right. I was just carelessly forgetting to include powers of variables in my ideal. Closed.
