### ISSUE TITLE
404 Error - XML Parsing Error

### ISSUE THREAD

**Issue by FatemehTarashi** [Macaulay2/M2#853]
On the [GettingStarted page](https://faculty.math.illinois.edu/Macaulay2/GettingStarted/) of the site, the first link (Beginning Macaulay2) has 404 error. 
I think it's okay to change the URL address to 
https://faculty.math.illinois.edu/Macaulay2/doc/Macaulay2/share/doc/Macaulay2/BeginningMacaulay2/html/index.html.

And [ BeginningMacaulay2 link ](https://faculty.math.illinois.edu/Macaulay2/doc/Macaulay2/share/Macaulay2/BeginningMacaulay2/) at the bottom of the [this page](https://faculty.math.illinois.edu/Macaulay2/doc/Macaulay2/share/doc/Macaulay2/BeginningMacaulay2/html/index.html), the last sentence has XML Parsing Error.

**Comment by DanGrayson** [comment]
Thanks, I fixed it!
