### ISSUE TITLE
format of help

### ISSUE THREAD

**Issue by pzinn** [Macaulay2/M2#856]
apologies if this is a well-known issue, but I only noticed recently.
why is it that help (I do mean in TopLevelMode=Standard !) has TeX commands within?
try
`?basis`
or
`help basis`
and you'll see things like
```
Notice that {\tt phi} is a matrix whose source is a free module, and whose target is the ideal.
"super" is used to get the actual elements of $I$.
{\bf Basis ina specific multi-degree}
```
(sic)
this has been there since at least 1.12

**Comment by DanGrayson** [comment]
Yes, probably something should be done about that eventually.

**Comment by mahrud** [comment]
Math is still displayed inside `$...$`, but `tt, it, bf, em, url` tags are now fixed.
