### ISSUE TITLE
Macaulay2 for Window 7-32bit

### ISSUE THREAD

**Issue by sondangnguyen** [Macaulay2/M2#867]
Hi, I followed the steps in

 https://faculty.math.illinois.edu/Macaulay2/Downloads/Microsoft-Windows/Cygwin/index.html

but  I get the error message

“Unable to get setup.ini .."
What should I do?
Thank you so much.

**Comment by DanGrayson** [comment]
It should have worked.  Perhaps you entered the URL incorrectly when you added it to the list.

But we have given up on cygwin and Windows many versions ago, so it would be best for you to get Macaulay2 a different way, so you'd have a modern version of Macaulay2.

**Comment by sondangnguyen** [comment]
I tried to both typing and copy paste your link to add it.  Do you mean that I cannot use Macaulay2 for window 7?  I download the version 1.6.

**Comment by sondangnguyen** [comment]
When you say " highlight a Cygwin mirror site geographically near you by clicking on it (all of the other names on the list are names of Cygwin mirror sites", what do you mean?

I clicked and kept both macaulay2 and another link.

**Comment by DanGrayson** [comment]
You should be able to get Macaulay2 1.6 to work under Windows 7, but Macaulay2 1.12 would be better for you.

**Comment by DanGrayson** [comment]
> When you say " highlight a Cygwin mirror site geographically near you by clicking on it (all of the other names on the list are names of Cygwin mirror sites", what do you mean?
> 
> I clicked and kept both macaulay2 and another link.

That sounds right to me.

**Comment by DanGrayson** [comment]
Please reopen if we can help further.
