### ISSUE TITLE
crash in computation of inverse

### ISSUE THREAD

**Issue by pzinn** [Macaulay2/M2#874]
Macaulay2 fails to compute the inverse of this invertible element (and crashes):
```
i1 : R=(frac(QQ[z]))[q]/ideal(q^10)

o1 = R

o1 : QuotientRing

i2 : (z+q)^(-1)
--internal error: ring element gcd computation failed
/bin/sh: line 1:  3646 Aborted                 (core dumped) M2 --no-readline --print-width 115

Process M2 exited abnormally with code 134

``

**Comment by radoslavraynov** [comment]
Hi, inverse should never work on a non-scalar, right? Instead, you can represent `1_R` in that basis.
```
i1 : R=(frac(QQ[z]))[q]/ideal(q^10); inv=1//matrix{{z+q}}

o3 = {1} | (-1)/z10q9+1/z9q8+(-1)/z8q7+1/z7q6+(-1)/z6q5+1/z5q4+(-1)/z4q3+1/z3q2+(-1)/z2q+1/z |

             1       1
o3 : Matrix R  <--- R

i4 : assert((z+q)*inv_(0,0)===1_R)
```

The internal error and crash are unwanted. The way this is handled gets fixed in [#928](https://github.com/Macaulay2/M2/pull/928) &mdash;
```
i1 : R=(frac(QQ[z]))[q]/ideal(q^10); (z+q)^(-1)
stdio:5:38:(3): error: division is not defined in this ring
```

**Comment by DanGrayson** [comment]
Despite #928 being pulled, this is still a problem.

**Comment by radoslavraynov** [comment]
I think it's be because I reverted 0d26ecb. I'll rework it this weekend.

**Comment by mikestillman** [comment]
I made a change to the C++ code today which might have fixed this, although your solution might be more flexible.

**Comment by DanGrayson** [comment]
Saturday morning I start making the next release, version 1.14.

**Comment by pzinn** [comment]
If nobody objects I will close this issue. AFAICT the original bug is resolved.

**Comment by DanGrayson** [comment]
Okay, closing, thanks!
