### ISSUE TITLE
shebang is needed by Python Expect in M2 startup script

### ISSUE THREAD

**Issue by dimpase** [Macaulay2/M2#885]
Python (more precisely, it's Expect module) has trouble finding out the type of file `M2`, this breaks the Sage interface, one gets
`OSError: [Errno 8] Exec format error`. The fix is to add a shebang in the beginning of the file, i.e. to have it looks something like
```
#!/bin/bash
exec /mnt/opt/bla/foo/baz/M2 "$@"
```
Needless to say, `/bin/bash` ought to be replaced by the value of `$SHELL` at the installation time.

**Comment by DanGrayson** [comment]
Thanks, fixed in commit 51b13123b327dd84f4db7d94451559cfba7baa1e
