### ISSUE TITLE
inheritance of module structure

### ISSUE THREAD

**Issue by eisenbud** [Macaulay2/M2#895]
If phi: S-->R is a ring homomorphism, M is an S-module and N is an R module, then there is an unambiguous structure of R-module on M\otimes N relative to phi. 

In many cases, for example when R has been defined as S/I, one can write
map(R,S)
in M2 without specifying the map -- that is, there is a "natural" choice.

I suggest that in exactly these cases M**N should be defined as an R-module. More generally,
I suggest that one allow a syntax like tensor(phi, M, N) to be the R-module as above.

**Comment by DanGrayson** [comment]
Sounds good to me.

**Comment by mahrud** [comment]
Since `phi ** M` in M2 gives an R-module (here is the [documentation](https://faculty.math.illinois.edu/Macaulay2/doc/Macaulay2-1.15/share/doc/Macaulay2/Macaulay2Doc/html/___Ring__Map_sp_st_st_sp__Matrix.html)), is this the same as `phi ** M ** N`?

**Comment by mahrud** [comment]
I believe my last comment means this issue can be closed, but we can reopen it if I'm missing something.

> Since `phi ** M` in M2 gives an R-module (here is the [documentation](https://faculty.math.illinois.edu/Macaulay2/doc/Macaulay2-1.15/share/doc/Macaulay2/Macaulay2Doc/html/___Ring__Map_sp_st_st_sp__Matrix.html)), is this the same as `phi ** M ** N`?
