### ISSUE TITLE
remove duplicate documentation

### ISSUE THREAD

**Issue by DanGrayson** [Macaulay2/M2#904]
see commit 765805dab6625c9cd3b185f629a32e7a6711f400, where I remove some duplicate documentation

@ycid - could you check that I commented out the right one?  Then we could remove the comment.

**Comment by ycid** [comment]
@DanGrayson thank you very much for fixing this! Now it is OK.

**Comment by DanGrayson** [comment]
Thanks, comment removed in commit 662d47c6e9247189fd7eeeea68e1ed73b6ad6c4c
