### ISSUE TITLE
Unable to Open Help Pages or Try it Out 

### ISSUE THREAD

**Issue by adrallab** [Macaulay2/M2#922]
When I try to open pages of Macaulay2 documentation, I keep getting a "404 Not Found" error.  My advisor also tried and had the same issue.  The "Try it Out" online Macaulay2 is also not working; when I try to go to web.macaulay2.com from the Macaulay2 site, I get a "this site can't be reached" error.

This has been happening for perhaps the last week or so.

**Comment by DanGrayson** [comment]
Could you tell us the URL that is not found, and the URL of the page on which it occurs?

**Comment by adrallab** [comment]
For example, 

https://faculty.math.illinois.edu/Macaulay2/doc/Macaulay2-1.9/share/doc/Macaulay2/MonomialAlgebras/html/index.html

appearing on page

https://www.google.com/search?q=regularity&q=site%3Awww.math.uiuc.edu+inurl%3AMacaulay2

and 

http://habanero.math.cornell.edu:3690/

appearing on page 

http://www2.macaulay2.com/Macaulay2/TryItOut/

**Comment by DanGrayson** [comment]
Well, the first one is gone because version 1.9 is old, and I have deleted the corresponding documentation.  For the second one, perhaps habanero is down again -- @mikestillman ?

**Comment by adrallab** [comment]
I see.  If I replace 1.9 with 1.12 or 1.13, the page loads fine.  I suppose I can do this in the future if I am trying to find documentation via google.

**Comment by DanGrayson** [comment]
If I could figure out how to have the nginx server return "removed permanently" instead of "not found", then google would probably stop delivering those hits sooner.

**Comment by adrallab** [comment]
In the meantime, I don't mind editing the URL.  One concern I have is that some things don't appear to be searchable within version 1.12 or version 1.13, but they are for a previous version (so if you got rid of the previous version altogether, I'm not sure how I would find them).  For example, if I search for "monomial ideal" from the "search the web site" on the Macaulay page, the first result is 

https://faculty.math.illinois.edu/Macaulay2/doc/Macaulay2-1.9.2/share/doc/Macaulay2/Macaulay2Doc/html/_monomial__Ideal_lp__Ideal_rp.html

which I can edit to version 1.12 or 1.13 and learn about monomialIdeal.

However, if I just search within version 1.12 or version 1.13, I don't see a result with the desired page.

**Comment by DanGrayson** [comment]
Somehow google is very slow to index our pages.  I've tried asking it to do it, but it doesn't work.

**Comment by adrallab** [comment]
I see.  Thank you for your help!
