### ISSUE TITLE
Modulo operator % over integers producing incorrect results

### ISSUE THREAD

**Issue by odovacris** [Macaulay2/M2#931]
This may be related to the issue #146.

The "%" operator over the integers is incorrect. 
```
R = ZZ[x, y]
f1 = 3*x^2*y + 9*x^2 + 2*x*y + 5*x + y - 3;
f2 = 2*x^3*y + 6*x^3 - 2*x^2 - x*y - 3*x - y + 3;
f2 % f1
```
output: 
```
   3      3    2      2
- x y - 3x  + x y + 2x  + 5x
```
This is false since `x^3 y` is the leading monomial of f1 and a reduction is still possible.

Great program, though! Best of luck. I hope this helps.

**Comment by odovacris** [comment]
The output formatting should be 
-x^3 y - 3x^3 + x^2 y + 2x^2 + 5 x.
Github is a bit overzealous with its markup parsing.

**Comment by odovacris** [comment]
I'm so sorry for the multiple comments, but I thought I should explain a bit more.

The first step in the reduction should look like
fm = f2*3 - 2*f1*x
and the second step
fm = fm*3 + 4*f1.

A correct answer is thus
-12 x^2 - 7 x y + 11 x - 5 y + 15 (up to possible unit normalization, i.e., multiplication by -1).

Macaulay2 does this properly when you input it in manually.

**Comment by DanGrayson** [comment]
Here's a readable version:
```

o16 = R

o16 : PolynomialRing

i17 : f1 = 3*x^2*y + 9*x^2 + 2*x*y + 5*x + y - 3;

i18 : f2 = 2*x^3*y + 6*x^3 - 2*x^2 - x*y - 3*x - y + 3;

i19 : f2%f1

         3      3    2      2
o19 = - x y - 3x  + x y + 2x  + 5x

o19 : R
```

**Comment by DanGrayson** [comment]
This is not a valid reduction step:
```
fm = f2*3 - 2*f1*x
```
because of the presence of `3`.  It looks like what you really want to do is to computer a Groebner basis.

**Comment by odovacris** [comment]
If we took the principal ideal I = (f1), then we would want this f2 % f1 to be the same as f2 % I, unless you are using a very non-standard definition of modulo. Up to you, of course. You may be using the term "reduction" in an odd way (my source is B. Buchberger. "Gröbner Bases: An Algorithmic Method in Polynomial Ideal Theory." (1985)). Good luck.

**Comment by radoslavraynov** [comment]
You are working in `ZZ[x,y]`, that is, the coefficient ring in not a field. In that case, quotient is `x-1` and the remainder is what M2 gives you. To get what you want, up to a unit, just work over `QQ[x,y]`. You can reach out to the community on the mailing list: http://groups.google.com/group/macaulay2.

**Comment by DanGrayson** [comment]
> If we took the principal ideal I = (f1), then we would want this f2 % f1 to be the same as f2 % I, unless you are using a very non-standard definition of modulo. Up to you, of course. You may be using the term "reduction" in an odd way (my source is B. Buchberger. "Gröbner Bases: An Algorithmic Method in Polynomial Ideal Theory." (1985)). Good luck.

Those two things are currently the same:
```

i4 : f2 % f1

        3      3    2      2
o4 = - x y - 3x  + x y + 2x  + 5x

o4 : R

i5 : f2 % ideal f1

        3      3    2      2
o5 = - x y - 3x  + x y + 2x  + 5x

o5 : R
```
