### ISSUE TITLE
Issue with "roots" (multiple roots of +1/-1)

### ISSUE THREAD

**Issue by jchen419** [Macaulay2/M2#932]
The command "roots" seems to give inaccurate results for univariate polynomials of the form (x - 1)^n or (x+1)^n for certain values of n (e.g. n odd, or n = 6), cf. this [Google groups post](https://groups.google.com/d/msg/macaulay2/hjHPMnW-tzE/C8mPOTbTCQAJ). The issue seems to happen whenever the coefficient field has floating-point arithmetic.

**Comment by mikestillman** [comment]
This is (I think) fixed by changing our `roots` function from using `pari` to using `mpsolve`, available in M2 1.16
