### ISSUE TITLE
LoadPackage

### ISSUE THREAD

**Issue by HamidHassanzadeh** [Macaulay2/M2#939]
Hi,
When I am loading the package RandomIdeals on my computer I encounter a problem. On other computers it does not make this problem. 
Id be grateful if one can help

i1 : loadPackage"RandomIdeals"
--loading configuration for package "Graphs" from file /Users/Hamid/Library/Application Support/Macaulay2/init-Graphs.m2
Library/Application Support/Macaulay2/local/share/Macaulay2/RandomIdeals.m2:430:1:(2):[7]: error: no method for adjacent objects:
--            doc (of class Symbol)
--    SPACE   "                                                         . (of class String)
--            Key                                                       .
--                 RandomIdeals                                         .
--            Headline                                                  .
--                 A package to construct various sorts of random ideals.
--            Description                                               .
--             Text                                                     .
--                 This package can be used to                          .

i2 :

**Comment by DanGrayson** [comment]
We can see that the package is being loaded from your application directory.
Try adding "-q" to the M2 command line, so it doesn't look for packages in your application directory, or else use "uninstallPackage" or "uninstallAllPackages" to get rid of that thing that's sitting there.

**Comment by DanGrayson** [comment]
Closing.  Please reopen this issue if it is still a problem.
