### ISSUE TITLE
'variety Ring' is defined both in NormalToricVarieties and Schubert2

### ISSUE THREAD

**Issue by mikestillman** [Macaulay2/M2#943]
Here is an example of the issue:  The NormalToricVarieties package redefined 'variety Ring', for the Cox ring of a toric variety.  This then makes certain basic functions in Schubert2 fail.

For example:
```
needsPackage "NormalToricVarieties"
V = smoothFanoToricVariety(3, 2)
assert(variety V_0 === V)
IV = intersectionRing V
assert(variety IV === null)

aV = abstractVariety(V, point)
intersectionRing aV
assert(variety IV === aV) -- variety IV is null in M2 1.13
assert(instance(OO(IV_0), AbstractSheaf)) -- error in M2 1.13, since Schubert2 is asking for variety of the ring of IV_0
```

'variety' is defined in Core.  It uses the stashed key 'variety' (often times).  NormalToricVarieties also uses this same key to stash the variety of the Cox ring.  Schubert2 uses the key `Variety` instead, and the result of calling `variety` is an AbstractVariety.

My suggested solution:  Move `variety Ring` and `variety RingElement` to the Core, without suggested return types.  They will simply query the `variety` key in `Ring`.  Change Schubert2 to use the key `variety` instead of `Variety`.

I am assigning myself to this one, and will fix it (hopefully) today.

**Comment by mikestillman** [comment]
Right now, I'm going to make the following changes:

1. move `variety Ring`, `variety RingElement` to Core
2. take those out of the two packages
3. Change .Variety to .variety in Schubert2 (and remove the 2 spurious uses as well).
4. Document these in Macaulay2Doc, change or remove doc in Schubert2 and NormalToricVarieties.

Afterwords, we can include `abstractVariety Ring` too (or maybe that should be the next point I do here).

**Comment by DanGrayson** [comment]
> From my perspective, the Core is “missing” the method (variety, Ring) so I would like to see it added.

Hmm, i.e., one would define
```
variety Ring := R -> R.Variety
```
in the core, and document it in the core by saying this is a convenience for packages.  But then how would the method be documented in the various packages, which put it to different uses?  At least if we keep things pure, then documentation can be done.

It's hard to assert that the Core is missing the method if nothing in the Core depends on it.

**Comment by mikestillman** [comment]
I am about to commit one version of what we have discussed: I kept `variety Ring`, documented it in Macaulay2, and noted that it is potentially useful for package developers.

But @DanGrayson 's comment that it is not possible to document it easily has merit.  How about: documenting e.g.  `abstractVariety Ring` (in Schubert2, in this case), and saying in the documentation for that that one can also use `variety R`?

**Comment by DanGrayson** [comment]
Many of the comments on this thread are said to be in the future.

**Comment by DanGrayson** [comment]
> I am about to commit one version of what we have discussed: I kept `variety Ring`, documented it in Macaulay2, and noted that it is potentially useful for package developers.
> 
> But @DanGrayson 's comment that it is not possible to document it easily has merit. How about: documenting e.g. `abstractVariety Ring` (in Schubert2, in this case), and saying in the documentation for that that one can also use `variety R`?

That would work.

**Comment by mikestillman** [comment]
Interesting, @ggsmith comment is showing up on github that it appeared 7 hours earlier!  A time change bug...

**Comment by mikestillman** [comment]
It is true that `variety Ring` will then return different things, depending on whether the ring is a Cox ring or an intersection ring. But I don't think I see that as a problem (but can be convinced otherwise).  It is easier to remember, than all these other names (e.g. normalToricVariety, abstractVariety), I guess.

**Comment by mikestillman** [comment]
It turns out that `variety A`, previously, in Schubert2, gave an error if A did not have a variety associated to it.  For the moment, it is instead returning null.  However, the Schubert2 code in a number of places uses `try` instead of checks for non-null-ness, so 4 tests failed last night due to that.

I have two options: either fix these calls (not completely trivial), or have this function give an error if no variety is associated with A.  There is precisely one test in NormalToricVarieties that checks that the result is null.  However, the rest of the package assumes that it will work, and so currently the error message will be strange (cannot apply XXX function to null).  So I am tempted to change behavior (back) to give an error if the key doesn't exist.  But I would probably give an error saying: no variety has been associated with this ring.

 @DanGrayson , @ggsmith : do you have any comments/preferences about this?

**Comment by ggsmith** [comment]
Having this function give an error message like "no variety associated to this ring" makes the most sense to me.

**Comment by mikestillman** [comment]
@ggsmith , I changed the doc for (variety, NormalToricVariety) as follows:
```
         Text
             If the polynomial ring is not constructed from a variety, then
-  	    this method returns @TO null@.
+  	    this method produces an error: "no variety associated with ring".
         Example  
      	   S = QQ[x_0..x_2];
     	   gens S
     	   degrees S
-    	   assert (null === normalToricVariety S)	   
-    	   assert (null === variety S)
+    	   assert (try (normalToricVariety S; false) else true)
+    	   assert (try (variety S; false) else true)
```

Would you prefer to change this text/test?

**Comment by ggsmith** [comment]
This change looks fine to me.

**Comment by mikestillman** [comment]
Fixed in commit 226e7466dc (and several before that)

**Comment by mahrud** [comment]
A couple of points in retrospect:
- I think this output is a bit unusual:
```m2
i1 : variety ring Proj(kk[x])
stdio:1:1:(3): error: no variety associated with ring
```
- as I mentioned in https://github.com/Macaulay2/M2/commit/226e7466dce49ee577432586dfafd15c0c17a1ca#r60857412, I tried to change this so when a variety isn't already defined it returns Proj S if S is homogeneous and otherwise Spec S. However, this led to errors because of the `try variety S else ...` pattern in Schubert2, but I feel like that pattern is bug prone. Does anyone feel strongly about this?
- `Spec` and `Proj` store the ring in `X.ring`, but for Cox rings it's in `X.cache.ring`. Can we reconcile this difference? I'd prefer if it was possible to have code that runs on Proj or a toric variety seemlessly.

Lastly, what would you all think about extracting `varieties.m2` into a simple package, maybe `Varieties` or `AlgebraicGeometry`, which is preloaded and imported by packages that deal with varieties? Contributing changes to the Core for beginners (for instance to volunteer to resolve issues like #1358 which are labeled as being good for beginners) is significantly harder than contributing changes to a package, since you can install and run examples and tests much more easily.

**Comment by DanGrayson** [comment]
It's a good idea to put more code into packages, but make sure that no code in the core uses it.
