### ISSUE TITLE
GC_REDIRECT_TO_LOCAL

### ISSUE THREAD

**Issue by mikestillman** [Macaulay2/M2#965]
@DanGrayson: In e/newdelete.hpp, we define GC_REDIRECT_TO_LOCAL.  However, it appears that it hasn't been a part of the Boehm garbage collector for awhile, so can we just remove this def? (or am I not understanding how we are using it?)

**Comment by DanGrayson** [comment]
It must have become obsolete long ago, so feel free to remove it.
