### ISSUE TITLE
dpkg-dev needed for deb packages

### ISSUE THREAD

**Issue by galettof** [Macaulay2/M2#966]
https://github.com/Macaulay2/M2/blob/e7267ee8c23cbc4000d1a4ee42f8ef9625015d2b/M2/INSTALL#L64

A small issue with a possible solution, in case others have a similar experience.

In order to compile Macaulay2 (branch 1.14) and have it produce .deb files on Debian 10, I needed to also install the package dpkg-dev. Without it, make raised an error seemingly caused by the absence of dpkg-architecture.

Cheers!

**Comment by DanGrayson** [comment]
I'll make a Debian 10 VM and confirm that, and also make an M2 distribution for it.

**Comment by DanGrayson** [comment]
Thanks, fixed in commit d12974daf468ac59e4abd458e564bd2edc9e7c55
