### ISSUE TITLE
behaviour of describe

### ISSUE THREAD

**Issue by mwageringel** [Macaulay2/M2#967]
In the interface to Macaulay2 that is included with SageMath, we use `describe` to get a textual representation of elements in order to circumvent that types like polynomial rings print as their global variable name. There are two problems:

- `describe` cannot be called with Sequences – it would be very convenient if this was possible. This is probably easy to fix by using `Dispatch=>Thing`.

- The output for matrices such as `net describe matrix {{1,2},{3,4}}` changed from
  ```
  | 1 2 |
  | 3 4 |
  ```
  to
  ```
         2    2
  map (ZZ , ZZ , {{1, 2}, {3, 4}})
  ```

  in Macaulay2 version 1.13. Is this change intentional? While the new output seems more complete, it is less useful for visual representation. Matrices do not acquire the global variable name, so the new behaviour is a bit unexpected.

(This came up in https://trac.sagemath.org/ticket/11217#comment:10.)

**Comment by mwageringel** [comment]
A related question: Is there a way to assign a value to a global variable and explicitly control whether it acquires the name of that variable?

The interface in Sage internally assigns global variables `sage1`, `sage2`,… which are not meaningful to a user, so polynomial rings should not assume those names. However, when assigning it to a meaningful name later on, the name should be acquired. For example, this ring should assume the name `R`:

    sage1 = QQ[x,y];
    R = sage1;

If this could be controlled explicitly, it would avoid the need to call `describe` on everything in the first place.

The closest solution I can think of is to store the internal values in a `MutableHashTable` instead. This is different from global assignment in that one has to additionally call `use`. Are there any other differences to keep in mind?

Another workaround could be to call the `GlobalReleaseHook` of `sage1` before assigning `R`, but that would require knowning the variable to which the ring was first assigned.

By the way, `use` cannot be invoked on Sequences, either.

**Comment by DanGrayson** [comment]
The more recent way "describe" works does seem more accurately descriptive.  By why not just use "net" instead for matrices, as here?:

```

i5 : f = matrix {{1,2},{3,4}}

o5 = | 1 2 |
     | 3 4 |

              2        2
o5 : Matrix ZZ  <--- ZZ

i6 : net f

o6 = | 1 2 |
     | 3 4 |
```

For the related question, there is a way to prevent things such as rings from "acquiring" the names of the variables to which they are assigned: use the other assignment operator:
```
i11 : symbol S <- ZZ[x]

o11 = ZZ[x]

o11 : PolynomialRing
```

@pzinn -- the behavior was introduced by you in https://github.com/Macaulay2/M2/commit/5d2988b2b0

**Comment by pzinn** [comment]
in general, `describe` now produces an `Expression` rather than a `Net`. the reason I introduced this change is to make `describe` output-mode-agnostic.
a side benefit is, one can `value` it and recover the original object (in this case, the matrix).
I do not use SageMath so cannot really comment on the original issue.

**Comment by mwageringel** [comment]
Thanks a lot for the quick responses. The `<-` operator will be immensely useful. My preliminary tests were successful. Such a simple solution.

As for calling `net` on matrices, indeed that works – it just requires special treatment for the type Matrix. That is fine though. I do not mind either way, but just wanted to be sure this is correct.

The main issue that remains is that `describe` and `use` cannot be called with type Sequence. It is just a minor problem that is simple to work around. Feel free to close this issue if this should not be changed.

**Comment by DanGrayson** [comment]
What would you like `describe` and `use` to do when given sequences?

**Comment by mwageringel** [comment]
Nothing in particular. It would just be convenient if the first two commands below worked and had the same effect as the other two.
```
i1 : use(1..5)
stdio:1:1:(3): error: no method found for applying use to:
     argument   :  (1, 2, 3, 4, 5) (of class Sequence)

i2 : describe(1..5)
stdio:2:1:(3): error: no method found for applying describe to:
     argument   :  (1, 2, 3, 4, 5) (of class Sequence)

i3 : (lookup(use, Sequence)) (1..5)

o3 = (1, 2, 3, 4, 5)

o3 : Sequence

i4 : (lookup(describe, Sequence)) (1..5)

o4 = (1, 2, 3, 4, 5)
```

**Comment by DanGrayson** [comment]
You could do something like this:
```

i12 : R = ZZ[x]

o12 = R

o12 : PolynomialRing

i13 : describe R

o13 = ZZ[x, Degrees => {1}, Heft => {1}, MonomialOrder => {MonomialSize => 32}, DegreeRank => 1]
                                                          {GRevLex => {1}    }
                                                          {Position => Up    }

i14 : describe (1:R)

o14 = ZZ[x, Degrees => {1}, Heft => {1}, MonomialOrder => {MonomialSize => 32}, DegreeRank => 1]
                                                          {GRevLex => {1}    }
                                                          {Position => Up    }
```

**Comment by mwageringel** [comment]
Fair enough. What I would expect in this case is the description of a Sequence, not a PolynomialRing. However, I am fairly new to Macaulay2, so I am not sure what is idiomatic.

**Comment by DanGrayson** [comment]
What would a "description" of a sequence be?

**Comment by mwageringel** [comment]
Well, I am not asking for a more descriptive representation of Sequences. One can call `describe` with any Thing and get a description that looks similar to its Net while avoiding its global variable name, except if that thing is a Sequence. Of course, if one knows the thing at hand is a Sequence, there is no need to call `describe` instead of `net`, but when writing generic code with arbitrary types this is not so clear.

I understand that Sequences play a special role in function calls, but for methods that only ever take a single argument it seems strange if this argument cannot be a Sequence when the method is defined for a parent of Sequence.

**Comment by DanGrayson** [comment]
Well, it is illogical that those two method functions could take multiple arguments, so I've changed that in commit 3fddf0530ceb3a9fc2666e48f8c51e412f2169e7 for you.

**Comment by mwageringel** [comment]
Thank you. I am closing this then.
