### ISSUE TITLE
Comparing VirtualTally to 0

### ISSUE THREAD

**Issue by jkyang92** [Macaulay2/M2#969]
Comparing virtual tallys (as opposed to tallys) to 0 yields the following unexpected results. `(new VirtualTally from {}) == 0` returns false. but `(new VirtualTally from {}) ? 0` returns `==`

Here's a patch that rewrites `==` to call `?`

[0001-Make-empty-virtual-tallys-compare-to-0.txt](https://github.com/Macaulay2/M2/files/3427792/0001-Make-empty-virtual-tallys-compare-to-0.txt)

**Comment by DanGrayson** [comment]
Thanks for noticing that bug.  It may be better, though, to create fewer new tallies with a change like this:
```
diff --git a/M2/Macaulay2/m2/set.m2 b/M2/Macaulay2/m2/set.m2
index 9821859b0..de6bfb658 100644
--- a/M2/Macaulay2/m2/set.m2
+++ b/M2/Macaulay2/m2/set.m2
@@ -42,15 +42,22 @@ VirtualTally ? VirtualTally := (x,y) -> (
      else if all(w,i -> i<0) then symbol <
      else incomparable)
 
-zeroTally = tally{}
+zeroVirtualTally := new VirtualTally from {}
+toVirtualTally := i -> if i === 0 then zeroVirtualTally else error "comparison of a virtual tally with a nonzero integer"
+VirtualTally == ZZ := (x,i) -> x === toVirtualTally i
+ZZ == VirtualTally := (i,x) -> toVirtualTally i === x
+VirtualTally ? ZZ := (x,i) -> x ? toVirtualTally i
+ZZ ? VirtualTally := (i,x) -> toVirtualTally i ? x
+
+zeroTally := new Tally from {}
 toTally := i -> if i === 0 then zeroTally else error "comparison of a tally with a nonzero integer"
-VirtualTally == ZZ := (x,i) -> x === toTally i
-ZZ == VirtualTally := (i,x) -> toTally i === x
-VirtualTally ? ZZ := (x,i) -> x ? toTally i
-ZZ ? VirtualTally := (i,x) -> toTally i ? x
+Tally == ZZ := (x,i) -> x === toTally i
+ZZ == Tally := (i,x) -> toTally i === x
+Tally ? ZZ := (x,i) -> x ? toTally i
+ZZ ? Tally := (i,x) -> toTally i ? x
      
-sum(VirtualTally) := (w) -> sum(pairs w, (k,v) -> v * k)
-product(VirtualTally) := (w) -> product(pairs w, (k,v) -> k^v)
+sum VirtualTally := (w) -> sum(pairs w, (k,v) -> v * k)
+product VirtualTally := (w) -> product(pairs w, (k,v) -> k^v)
 
 new Set from List := Set => (X,x) -> set x
 
```

**Comment by jkyang92** [comment]
That looks good. 

I also notice something somewhat related. `elements` when applied to a virtual tally only returns the elements with positive index. `keys` is an adequate substitute unless a virtual tally is created manually with a 0 value (i.e. `new VirtualTally from {1 => 0}`). But this might be a obscure enough case that simply documenting that elements returns only the positive elements or restricting it to Tally/BettiTally might be reasonable.

**Comment by DanGrayson** [comment]
Thanks, I'll restrict `elements` just to the class Tally.  (It's not the same as `keys`, by the way.)
