### ISSUE TITLE
development manual

### ISSUE THREAD

**Issue by dimpase** [Macaulay2/M2#971]
Absence of a proper development manual makes contributing harder than needed, in particular for people who do not spend a lot of time working with/on M2. E.g. every time I hit an error in M2 tests I have to search through my old emails to figure out where the corresponding log file may be found, etc.

**Comment by dimpase** [comment]
@mkoeppe

**Comment by DanGrayson** [comment]
One wouldn't want to have to search through documentation, either.  I hope the error messages themselves give enough information.  Don't they?

**Comment by dimpase** [comment]
On Fri, 26 Jul 2019 at 17:13, Daniel R. Grayson <notifications@github.com>
wrote:

> One wouldn't want to have to search through documentation, either. I hope
> the error messages themselves give enough information. Don't they?
>

maybe that was not the best example, but there are surely thing that are
very hard to figure out in the M2 building process.

**Comment by mahrud** [comment]
The internal notes in wiki are starting to fill this gap, so I'll close this.
Feel free to reopen if there's a specific example error that requires looking into.
