### ISSUE TITLE
"help" multiple "Usage" (and viewHelp)

### ISSUE THREAD

**Issue by antonleykin** [Macaulay2/M2#975]
This concerns documentation nodes that list several ways to call the function (`Usage` in SimpleDoc).
```
i1 : installPackage "MonodromySolver"

i2 : help createSeedPair

o2 = createSeedPair -- create initial seed for the homotopy continuation
     *******************************************************************

     Synopsis
     ========

       * Usage: (p0,x0) = createSeedPair PS(p0, x0) = createSeedPair(PS,x0)
...
```
Note: no linebreak above. Also, note that `viewHelp` does put a line break.
 
Another observation:
```
i3 : help (createSeedPair,System)
```
works but 
```
i4 : viewHelp (createSeedPair,System)
```
does **not** since it takes only `String`... but it would be nice if it did.

**Comment by DanGrayson** [comment]
It would be good to regard this issue as partially subsumed by #926, because each way of using the function should have a separate synopsis, with its own inputs and outputs.

**Comment by antonleykin** [comment]
@jchen419 @kroner
