### ISSUE TITLE
yum repo

### ISSUE THREAD

**Issue by pieterbowman** [Macaulay2/M2#979]
Will the yum repo for RHEL7/CentOS7/ScientificLinux7 for Macaulay2 be updated with the latest version?

**Comment by DanGrayson** [comment]
Thanks for the reminder!  Try it now and let me know.

**Comment by pieterbowman** [comment]
>> ...
>> Thanks for the reminder!  Try it now and let me know.
>> ...

Thanks for the quick response.  We are partly there.  I use reposync
to copy yum repos to our systems and received these packages:

(1/3): Macaulay2-1.12-1.x86_64-Linux-rhel-7.4.rpm          |  13 MB   00:01     
(2/3): Macaulay2-1.14-1.x86_64-Linux-scientific-7.6.rpm    |  13 MB   00:00     
(3/3): Macaulay2-1.11-1.x86_64-Linux-rhel-7.4.rpm          |  63 MB   00:03     

Unfortunately, when trying to update a system I get the following:

Resolving Dependencies
--> Running transaction check
---> Package Macaulay2.x86_64 0:1.10-1 will be updated
---> Package Macaulay2.x86_64 0:1.14-1 will be an update
--> Processing Dependency: Macaulay2-common = 1.14 for package: Macaulay2-1.14-1.x86_64
--> Finished Dependency Resolution
Error: Package: Macaulay2-1.14-1.x86_64 (Macaulay2)
           Requires: Macaulay2-common = 1.14
           Installed: Macaulay2-common-1.10-1.noarch (@Macaulay2)
               Macaulay2-common = 1.10-1
           Available: Macaulay2-common-1.8.2-1.noarch (Macaulay2)
               Macaulay2-common = 1.8.2-1
           Available: Macaulay2-common-1.9.2-1.noarch (Macaulay2)
               Macaulay2-common = 1.9.2-1


It appears as though the Macaulay2-common packages are missing.

I also tried pointing to the macaulay2.com repo, so I'm pretty sure
reposync isn't the problem.

Thanks again for your help.

Pieter

**Comment by DanGrayson** [comment]
Oh, yes, now try it.

**Comment by pieterbowman** [comment]
>> ...
>> Oh, yes, now try it.
>> ...

The packages are now there and install, as long as gpgcheck=0 is in
the Macaulay2-7.repo.  Otherwise yum complains that the packages are
not signed:

Package Macaulay2-1.14-1.x86_64-Linux-scientific-7.6.rpm is not signed
(1/2): Macaulay2-1.14-1.x86_64-Linux-scientific-7.6.rpm                                    |  13 MB  00:00:00     
(2/2): Macaulay2-1.14-1.common.rpm                                                         |  20 MB  00:00:00     
------------------------------------------------------------------------------------------------------------------
Total                                                                              72 MB/s |  33 MB  00:00:00     


Package Macaulay2-1.14-1.common.rpm is not signed


Pieter

**Comment by DanGrayson** [comment]
Thank you for the feedback -- I've just added the signatures.

**Comment by pieterbowman** [comment]
>> ...
>> Thank you for the feedback -- I've just added the signatures.
>> ...

Looks good.  Out Macaulay2 users should be happy to have an updated
version.


Thanks again,

Pieter

**Comment by DanGrayson** [comment]
Thanks for getting in touch.  It seems I've forgotten about that repository for years!
