### ISSUE TITLE
eigen branch todo list

### ISSUE THREAD

**Issue by mikestillman** [Macaulay2/M2#989]
Here are some things that need to be accomplished before we merge the `eigen` branch into `master`. @DanGrayson , @antonleykin 

- search for eigen3 library first, but allow it to be downloaded too? (configure.ac)
- ubuntu (after installing package `libeigen3-dev`) places eigen3 header files (it is a header only library) into `/usr/include/eigen3`, and the mac (after `brew install eigen3`) places the files in `/usr/local/include/eigen3`.  We are currently (in e.g. e/eigen.cpp) doing e.g. `#include <Eigen/SVD>`.  Perhaps the easist change is to to `#include <eigen3/Eigen/SVD>` instead?
- we no longer need to build gmp or mpir.  But how do we prefer builtin mpir (which is not built with gmp compatibility?)
- we no longer need to rebuild pari, I think, either.
- similiarly, for flint.  This branch is no longer patching flint (also pari).
- We had a complicated (for me at least!) way to get static initialized gmp values in libraries to run after gc is initialized (using `M2inits1.cc, M2inits2.cc, M2inits3.cc`).  These should (hopefully!) not be needed anymore.  Can we remove them here, and in the Makefile linking M2? **Done**
- The code in `M2inits.cc` can be simplified too.  All I did was comment out code not needed anymore, I didn't remove the actual routines themselves. **Done, in fact much more has been removed**

**Comment by mikestillman** [comment]
Also:
- update the INSTALL file to pre-install `eigen3`?

**Comment by DanGrayson** [comment]
The library is called `libeigen3-dev` in Ubuntu 19.04.

**Comment by mikestillman** [comment]
I'll edit the todo list, I think that is the name also in 18.04.

**Comment by DanGrayson** [comment]
The correct way to include the files in eigen is to add the appropriate directory to the search path with something like -I/usr/include/eigen3, because the package documents using including <Eigen/foobar.h> to get its files.  The configure script should handle that, after detecting the package's location.

**Comment by DanGrayson** [comment]
The configure script will find the location with this command:
```
$ pkg-config eigen3 --cflags
-I/usr/include/eigen3
```

**Comment by mikestillman** [comment]
In `configure.ac`, can we also remove the `CONSTRUCTOR_ORDER` logic?

**Comment by DanGrayson** [comment]
This has to be removed from the e/Makefile.in : 
```
 -I/usr/local/include/eigen3 -I/usr/local/include/eigen3/unsupported -I/nethome/aleykin3/include/eigen-git-mirror -I/nethome/aleykin3/include/eigen-git-mirror/unsupported
```

**Comment by mikestillman** [comment]
absolutely!

**Comment by DanGrayson** [comment]
I think it's better for the configure script to use -I/usr/include/eigen3 -I/usr/include/eigen3/unsupported.

**Comment by DanGrayson** [comment]
Using this will make it safer:
```
$ pkg-config eigen3 --cflags-only-I
-I/usr/include/eigen3
```

**Comment by DanGrayson** [comment]
> In `configure.ac`, can we also remove the `CONSTRUCTOR_ORDER` logic?

yes, since that was concerned only with beating the other libraries to setting the gmp allocator.

**Comment by dimpase** [comment]
pkg-config comes with handy autoconf macros, such as PKG_CHECK_MODULES.
So `PKG_CHECK_MODULES([EIGEN3],...)` will fill in various variables, cf. e.g. https://autotools.io/pkgconfig/pkg_check_modules.html

**Comment by mahrud** [comment]
The relevant package in fedora is `eigen3-devel`. Setting `CPPFLAGS="-I/usr/include/eigen3 -I/usr/include/eigen3/unsupported"` on the configure command worked for me (both are needed, I'm not sure how to get the second one from `pkg-config`).

Also, it seems like setting `ulimit -v 850000` causes tests and examples to fail. In particular:
```
$ ulimit -v 850000; ./build/M2
pthread_create: failed: Cannot allocate memory
Aborted (core dumped)
```
(My machine has 16GB memory and M2 works fine without the ulimit set.)

**Comment by mikestillman** [comment]
I am going to make the following changes in d directory related to this issue.  I will edit this comment when I find more things to change.
- remove files: M2init1,2,3.cc, gmp_init.h, gmp_init.cc
- in `d/M2inits.c`: remove `malloc_function`, `realloc_function` and `free_function`.  Remove `enterM2`, `check_M2init`, `M2inits_linker_dummy`, 
- in `d/debug.h`:
  Remove GMP_GC_CHECK
 - Remove all references and calls to `initializeGMP_Cwrapper` and `initializeGMP`, and refs to it (these are in `gmp_init.c`).
- `M2mem.c`: get rid of dead code, probably the long comment (which is possibly out of date).  Also remove `enter_getmem` and `exit_getmem`.

**Comment by mikestillman** [comment]
It seems that I can remove d/M2-factory.{h,cpp} too?  (and remove the line in e/engine.cpp and one e unit test which calls `factory_setup_1`), and all uses in `Makefile.in` and `Makefile-files.in`.  @DanGrayson , does this seem correct to you?

**Comment by mikestillman** [comment]
@DanGrayson : do we need `scc_core_prepare`, which is defined in `d/M2initis.c`?  I don't see it being used anywhere?  Except: perhaps scc is inserting a call to it when it translates d code?

**Comment by DanGrayson** [comment]
Re: `scc_core_prepare` -- we have to make sure we run GC_INIT before doing anything else, and that's one of the crucial things this function does.  But there seems to be a version of it in the c directory, which probably can be used.

**Comment by mikestillman** [comment]
> Re: `scc_core_prepare` -- we have to make sure we run GC_INIT before doing anything else, and that's one of the crucial things this function does. But there seems to be a version of it in the c directory, which probably can be used.

M2inits is run before main starts (in `M2inits.h`):
`extern void M2inits(void) __attribute__ ((constructor));`
and `M2inits` calls `GC_INIT`.  And `scc_core_prepare` only calls init_gc, which only calls GC_INIT.

So I guess if ((constructor)) is ignored, then we need to run it.  But if not, maybe we can remove it.

In fact, perhaps we should just call `GC_INIT` in the main function `M2main`?

**Comment by mikestillman** [comment]
I'm also removing `M2inits_firsttime` and `M2inits_run`.  They appear to never be used.  I do a grep from Macaulay2 to check this, so even if scc creates code to call this, I would probably notice.  But just in case, @DanGrayson this is why I am mentioning this.

**Comment by DanGrayson** [comment]
Calling GC_INIT from M2main ought to be enough.

**Comment by mikestillman** [comment]
Actually, interestingly, we are calling GC_INIT in Macaulay2_main, as well as in M2inits.c.  I wonder if GC_INIT is idempotent?  We are currently calling this function not at the top of Macaulay2_main.  I suggest we call that right away, as the first line of that function (and that I remove its use in M2inits.c, possibly removing M2inits.c totally?).  @DanGrayson am I missing some subtle logic?

**Comment by mikestillman** [comment]
`IM2_initialize()` is also called in `Macaulay2_main`, so I am going to remove the files `M2inits.{c,h} `. 

Actually, I can't quite do this yet, I guess.  `M2inits.c` also contains `progname`, `arginits`, and also `scc_core_prepare()`.  @DanGrayson It seems like these could be in `M2lib.c` ?  Also, `arginits` seems like a strange name for this function.

**Comment by mikestillman** [comment]
In the file `d/M2inits.c`, there is the following comment:
```
/* this file contains all initializations needed to get going, even if 
Macaulay2_main() is not called at all */
```

@DanGrayson : Is this important?  I am in the process of removing this file, by placing some parts of it into M2lib.c (or just removing it).  But I should not do so if we need this functionality...

**Comment by DanGrayson** [comment]
GC_INIT is idempotent.  The reason to put it in M2inits was so it would get called before all the other constructors.  Do you have any constructors in your code that allocate memory with gc?

**Comment by DanGrayson** [comment]
I'm pretty sure you can remove M2inits.c

**Comment by DanGrayson** [comment]
As I mentioned, there is a version of scc_core_prepare in the c directory.  Perhaps it can be used.

I can't tell whether arginits is ever called!

**Comment by mikestillman** [comment]
> GC_INIT is idempotent. The reason to put it in M2inits was so it would get called before all the other constructors. Do you have any constructors in your code that allocate memory with gc?

I don't think so.  All initializations I have are done via IM2_initialize() (which itself is idempotent).

**Comment by mikestillman** [comment]
It seems that `factory_setup_1()` is no longer needed either, so I will remove it, and all uses in d and e.

**Comment by mikestillman** [comment]
> As I mentioned, there is a version of scc_core_prepare in the c directory. Perhaps it can be used.
> 
> I can't tell whether arginits is ever called!

All arginits does is set progname.  But that doesn't seem to ever be used in the d directory, unless scc incorporates it somehow.  It is also being set directly in `Macaulay2_main`.

I think I will remove `progname` and `arginits`.

**Comment by mikestillman** [comment]
`interpFunc` calls `arginits`.  @DanGrayson : what does `interpFunc` do?  It calls the function, which sets progname, but that is never used, as far as I can tell, unless somehow `scc` is inserting calls to it.  I'll try removing it from that function.

**Comment by mikestillman** [comment]
> `interpFunc` calls `arginits`. @DanGrayson : what does `interpFunc` do? It calls the function, which sets progname, but that is never used, as far as I can tell, unless somehow `scc` is inserting calls to it. I'll try removing it from that function.

Removing it caused no link error.

**Comment by DanGrayson** [comment]
Sounds good.

**Comment by mikestillman** [comment]
The `enter_getmem`and `exit_getmem` functions in `M2mem.c` are no-ops.  I will remove them.  @DanGrayson OK?

**Comment by DanGrayson** [comment]
ok

**Comment by mikestillman** [comment]
The `BUILD_ALWAYS` (in `configure.ac`) configure variable logic needs to be changed: we don't need to build some of these libraries anymore.
